### ISSUE TITLE
[Question]How do i make a POST requests in a playwright driver ? (python)

### ISSUE THREAD

**Issue by NoName7258** [microsoft/playwright-python#1009]
How do i make a POST requests in a playwright driver ? (python)

**Comment by kumaraditya303** [comment]
It would be nice if it could be a context manager to auto dispose it after use, https://playwright.dev/docs/next/api/class-apirequestcontext#api-request-context-dispose

**Comment by kumaraditya303** [comment]
It should also be integrated with the pytest plugin.

**Comment by kumaraditya303** [comment]
Duplicate of https://github.com/microsoft/playwright-python/issues/1004
