### ISSUE TITLE
[Question]: Response body after expect_response

### ISSUE THREAD

**Issue by daruizr** [microsoft/playwright-python#1011]
### Your question

Hello all,

I am working with an api response to make the next request with playwright but I am having problems to have the response body with expect_response or page.on("request")

This is my code:

```
 async with page.expect_response("**/WebAPI/*") as response_info:
        response_body = await response_info._future.body()
```
and also I have tried to:

```
async def testfunction(response):
    if '/WebAPI/' in response.url:
        return await response.body()

response_body = page.on('response', testfunction)
```
I am waiting to have the response_body like this but it is not working. How I can have it?

I need the body to keep working but I don't know how I can have the body as a return from the function.

Thank you and sorry if the question is too basic.

**Comment by pashkatrick** [comment]
not too basic, but issue closed... classic
