### ISSUE TITLE
Make pyright default type checker and remove mypy

### ISSUE THREAD

**Issue by kumaraditya303** [microsoft/playwright-python#1014]
Given that mypy supports less features compared to pyright and also has many bugs which haven't been fixed yet for instance https://github.com/microsoft/pyright/issues/2532 and https://github.com/python/mypy/issues/2427, pyright should be the default type checker for this project. However, **this does not mean** that the library users need to use pyright, they can continue using mypy or whatever type checker they use, this is strictly scoped for internal type checking of this project so the project type stubs are high quality.

**Comment by mxschmitt** [comment]
I would keep them both for now, had the case when working on some changes that only mypy would report issues.

**Comment by kumaraditya303** [comment]
> I would keep them both for now, had the case when working on some changes that only mypy would report issues.

Sometimes mypy provides false-positive for cases where it is obviously wrong, Pyright is smarter :)

**Comment by mxschmitt** [comment]
Lets keep it for now!
