### ISSUE TITLE
[Bug]: Playwright not working on a specific website (detected as bot)

### ISSUE THREAD

**Issue by ramzitra** [microsoft/playwright-python#1026]
### Playwright version

1.16.1

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### Other information

python 3.7.6

### What happened? / Describe the bug

using playwright for this web page does not work "https://www.realestate.com.au/property-house-vic-doncaster-137523806"
Inspecting network shows that the request has a status code 429 too many requests.
On normal browser, this behavior does not exist

### Code snippet to reproduce your bug

```shell
from playwright.sync_api import sync_playwright
import time

url  = "https://www.realestate.com.au/property-house-vic-doncaster-137523806"

with sync_playwright() as p:
	browser = p.chromium.launch(headless=False)
	page = browser.new_page()
	page.goto(url)
	print("title :", page.title())
	time.sleep(10)
	browser.close()
```

**Comment by AntoinePaix** [comment]
Playwright uses a patched version of the chrome browser. The user agent is modified (the string "headless" is added) and the navigator.webdriver variable is initialized to true.

You can use Firefox browser for your job which does not modify these attributes. This makes it harder for bots to detect you.

Also, don't use the `time.sleep(10)` method but `page.wait_for_timeout(10_000)` instead.

```python
from playwright.sync_api import sync_playwright

url  = "https://www.realestate.com.au/property-house-vic-doncaster-137523806"

with sync_playwright() as p:
    browser = p.firefox.launch(headless=False)
    page = browser.new_page()
    page.goto(url)
    print("title :", page.title())
    page.wait_for_timeout(10_000)
    browser.close()
```

**Comment by ramzitra** [comment]
thanks for your answer, seems with firefox like you suggested works and I can see the web page but I got another issue.
here my code :
`from playwright.sync_api import sync_playwright
import time
url  = "https://www.realestate.com.au/property-house-vic-doncaster-137523806"
with sync_playwright() as p:
	browser = p.firefox.launch(headless=False)
	page = browser.new_page()
	page.goto(url)
	print("title :", page.title())
	page.wait_for_timeout(10000)
	browser.close()`

and here the output error :
Traceback (most recent call last):
  File "playwright_test.py", line 10, in <module>
    page.goto(url)
  File "C:\Users\Ramzi\AppData\Local\Programs\Python\Python37\lib\site-packages\playwright\sync_api\_generated.py", line 7141, in goto
    url=url, timeout=timeout, waitUntil=wait_until, referer=referer
  File "C:\Users\Ramzi\AppData\Local\Programs\Python\Python37\lib\site-packages\playwright\_impl\_sync_base.py", line 111, in _sync
    return task.result()
  File "C:\Users\Ramzi\AppData\Local\Programs\Python\Python37\lib\site-packages\playwright\_impl\_page.py", line 474, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "C:\Users\Ramzi\AppData\Local\Programs\Python\Python37\lib\site-packages\playwright\_impl\_frame.py", line 119, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Users\Ramzi\AppData\Local\Programs\Python\Python37\lib\site-packages\playwright\_impl\_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "C:\Users\Ramzi\AppData\Local\Programs\Python\Python37\lib\site-packages\playwright\_impl\_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://www.realestate.com.au/property-house-vic-doncaster-137523806", waiting until "load"
============================================================

I tried other waiting until like "domcontentloaded" and "networkidle" and still same error.
I also tried page.set_default_timeout(0), in that case the script is stack waiting forever.

The problem is I see in the browser that the page is loaded and not waiting for anything.
Any help on this ?
Thanks in advance

**Comment by mxschmitt** [comment]
Bot detection can happen in various ways. Often via user agent which you can override when creating a new context. Closing since the issue seems answered. For the timeout issue, I would recommend to enable [debug logs](https://playwright.dev/docs/debug#verbose-api-logs) or use the [trace viewer](https://playwright.dev/docs/trace-viewer) to debug the issue further:
