### ISSUE TITLE
[Bug]: Overriding record_video_dir keeps creating videos in default path

### ISSUE THREAD

**Issue by nusnuson** [microsoft/playwright-python#1033]
### Playwright version

1.16.1+

### Operating system

Linux

### What browsers are you seeing the problem on?

Chromium

### Other information

Running on Playwright's own Dockerfile (integrated with my project), so the base image is the normal playwright docker image.

### What happened? / Describe the bug

I am trying to allocate a single folder for the video recording of the tests but they keep appearing in `tests-results` as well as in my defined location (so I get duplicated video file).

I'm using pytest plugin and overriding the browser context via conftest.py.

### Code snippet to reproduce your bug

```shell
# conftest.py
import os

import pytest


@pytest.fixture(scope='session')
def browser_context_args(browser_context_args):
    return {
        **browser_context_args,
        'ignore_https_errors': True,
        'record_video_dir': os.environ['MY_OUTPUT_DIR_PATH'],
    }
```

**Comment by mxschmitt** [comment]
When using pytest-playwright its not supported to have the videos saved in another directory. You could implement [page.video.save_as](https://playwright.dev/python/docs/videos/) etc. yourself, then you could store it wherever you want.
