### ISSUE TITLE
[Bug]: Docker under a proxy with no proxy set leads to timeouts

### ISSUE THREAD

**Issue by KotlinIsland** [microsoft/playwright-python#1034]
### Playwright version

1.16.1

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### Other information

python 3.10.0
docker image based FROM mcr.microsoft.com/playwright:v1.16.1

### What happened? / Describe the bug

I'm under a corporate proxy, when I run this snippet it works fine on my windows machine as chrome is picking up my system settings, when I run it in a docker container with the proxy settings enabled, it runs fine, but with out the proxy settings it has strange behavior.

I would expect the logs to be a little more revealing as to whats going on.

### Code snippet to reproduce your bug

```shell
from playwright.sync_api import sync_playwright

with sync_playwright() as pw:

    page = pw.chromium.launch(
        # proxy={"server": "AMONGUS:100"},  # valid proxy server
    ).new_page()

    page.goto("https://reddit.com")
    print("The title is:", page.title())  # empty string
    s = page.screenshot()  # hangs then hits 30 second timeout
```

### Relevant log output

```shell
# python test.py
  pw:api navigating to "https://reddit.com/", waiting until "load" +0ms
  pw:api   navigated to "https://reddit.com/" +49ms
  pw:api   "domcontentloaded" event fired +3ms
  pw:api   "load" event fired +0ms
The title is:
  pw:api   "networkidle" event fired +499ms
Traceback (most recent call last):                     
  File "test.py", line 11, in <module>
    s = page.screenshot()  # hangs then hits 30 second timeout                                         
  File "/venv/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 7684, in screenshot
    self._sync(                                                                                        
  File "/venv/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 111, in _sync         
    return task.result()
  File "/venv/lib/python3.10/site-packages/playwright/_impl/_page.py", line 588, in screenshot
    encoded_binary = await self._channel.send("screenshot", params)
  File "/venv/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/venv/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 57, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
```

**Comment by mxschmitt** [comment]
The screenshot issue might be fixed when you upgrade your Docker container to `mcr.microsoft.com/playwright:v1.16.3`. (we fixed a related bug there)

Normally when no proxy is configured but required, the page.goto should end up in a timeout.

**Comment by KotlinIsland** [comment]
@mxschmitt Is there somewhere I can get notified about new docker image releases?

**Comment by mxschmitt** [comment]
We currently have the Python Docker inside the main Docker image, so the minor versions to Python could differ since they are in sync with the main project. In the future we want to move the Python image into a separate image, so it's in sync with the Python releases.

To answer your question, you can subscribe to the releases here: https://github.com/microsoft/playwright as of today.
