### ISSUE TITLE
Drop Python 3.7 support

### ISSUE THREAD

**Issue by kumaraditya303** [microsoft/playwright-python#1035]
Numpy has already dropped support for Python 3.7 https://github.com/numpy/numpy/blob/a1b5d443c375f9b63a415027da66f3d729cd59b5/setup.py#L410  so playwright can also drop support for it as most packages follow numpy release support. Doing this would also remove certain 3.7 specific hacks/workarounds.

**Comment by mxschmitt** [comment]
I checked various famous libraries, here is a brief investigation:
- Tensorflow: Python 3.6+ (https://www.tensorflow.org/install/pip)
- Pytorch, Python 3.6.2+ (https://github.com/pytorch/pytorch/blob/master/setup.py)
- Django 3.6+ (https://docs.djangoproject.com/en/3.2/faq/install/#what-python-version-can-i-use-with-django)
- Flask, 3.7+ (https://flask.palletsprojects.com/en/2.0.x/installation/)

I would wait a bit more to drop the Python 3.7 support.

**Comment by kumaraditya303** [comment]
Most of async libraries have dropped support for it 

- aiohttp https://github.com/aio-libs/aiohttp/blob/8987460cf1bf7abf28cee7fc043715b972c4293c/setup.py#L7 
 
- to be added 

Some benefits :
- Better process management as newer versions have threadedchildwatcher fixes https://github.com/microsoft/playwright-python/pull/966

- Better Syntax for typing, no more quotes for some classes

-  Better typing support, will not require typing-extensions to be installed at all.

- Walrus operator

**Comment by mxschmitt** [comment]
aiohttp and uvloop require Python >= 3.7, so they are on the same minimum version as we are.

**Comment by kumaraditya303** [comment]
> aiohttp and uvloop require Python >= 3.7, so they are on the same minimum version as we are.
> 
> 

Sorry copy & paste error.

**Comment by kumaraditya303** [comment]
@mxschmitt fixed list

**Comment by mxschmitt** [comment]
Closing for now, lets keep supporting Python 3.7 for now.
