### ISSUE TITLE
[Question]: Playwright slow when parallel execution

### ISSUE THREAD

**Issue by daruizr** [microsoft/playwright-python#1039]
### Your question

Hello everyone,

I am running playwright async to execute 10 browser (in this case with firefox) at the same time. The browsers are alive for a long time and I realize that they are a lot more slow that execute only one, obviously, but my computer resource are not at 100%. I was reading about asyncio.create_task and asyncio gather but looks like it does not use all the resources you have.

So in my opinion, the problem is that I am not using properly the resources and I am saturating the execution somehow.

This is my code:

```
server_name = 'srv1'
concurrent_process = 10

import asyncio
from playwright.async_api import async_playwright
import time
from src import browser_running


async def main():
    while True:
        L = await asyncio.gather(*[await asyncio.get_running_loop().run_in_executor(None, browser_running.main, _, server_name) for _ in range(concurrent_process)])

asyncio.run(main())
```

the browser_running.main only execute the browser and its activities:

```
async def main(user_slot, servername):
    async with async_playwright() as playwright:
        await run(playwright, user_slot, servername)
```

It's possible  to use multiprocessing or any other way to make this code more efficient and improve the performance? The process are totally isolated and they don't share information so it make easier.

The issue https://github.com/microsoft/playwright-python/issues/886 talk a bit about that but not about resource use and task performance.

Thank you a lot for your help.

**Comment by mxschmitt** [comment]
I would recommend to instead of creating multiple Playwright instances to create a single one, a single browser but multiple browser contexts, see here for an example: https://github.com/microsoft/playwright-python/issues/886#issuecomment-911469049

**Comment by daruizr** [comment]
> I would recommend to instead of creating multiple Playwright instances to create a single one, a single browser but multiple browser contexts, see here for an example: [#886 (comment)](https://github.com/microsoft/playwright-python/issues/886#issuecomment-911469049)

Cool, I am going to test it and report here the improvement.

Thank you
