### ISSUE TITLE
Use wider collection types instead of narrow in parameters

### ISSUE THREAD

**Issue by kumaraditya303** [microsoft/playwright-python#1049]
Use collections.abc.Sequence instead of typing.List in func parameters etc.

**Comment by mxschmitt** [comment]
Could you elaborate on that? What it gives us, the risks and whats required in terms of changes?

**Comment by kumaraditya303** [comment]
Playwright requires List here https://github.com/microsoft/playwright-python/blob/174d6249228c74813a23eeaa2df26dee73ba86d3/playwright/async_api/_generated.py#L11040 but it should accept any sequence otherwise even tuple cannot be used there.

See also https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#wide-vs-narrow-types

**Comment by mxschmitt** [comment]
We recommend lists and internally check always for `isinstance(..., list)`. This would require changes in playwright.dev, internally classes and generator so we keep it for now how it is caused by the complexity of the changes.
