### ISSUE TITLE
[Bug]: Improve Auto-waiting doc page for Python

### ISSUE THREAD

**Issue by AutomationPanda** [microsoft/playwright-python#1053]
### Playwright version

1.17.0

### Doc page link

https://playwright.dev/python/docs/actionability

### Improvement requests

The actionability checks table currently looks like this:
![Screen Shot 2021-11-23 at 2 39 27 PM](https://user-images.githubusercontent.com/43835014/143092364-f1685995-f755-40c1-b6be-3599f62ec7de.png)

All the actions listed in this table are written in `lowerCamelCase`, but the Python API uses `snake_case`. This confused me at first. For example, the table has `getAttribute`, but the Python call is `page.get_attribute(...)`. If someone were to try `page.getAttribute(...)`, Python would try to run it but then yield a cryptic error message about `page` not having an attribute named `getAttribute` (I believe). This could frustrate users.

I also noticed that this table is incomplete. For example, it does not include `input_value`. I do not know if the table is missing other methods. Furthermore, I think there is ambiguity in this table. If a method is missing, then does that mean no actionability checks are performed for it, or does it mean that the table simply does not provide information about it? One of the points in the Zen of Python is, "Explicit is better than implicit." It would be clearer if the table included all methods and had "no" or "-" in columns were no actionability check is performed. (I don't know if there are any like that because I am new to Playwright, but if there are, they should be made explicit.)

Finally, the sorting order for the rows makes it hard to find individual actions. For example, as a programmer, I'd want to visit this page to see what actionability checks are done for a particular method I'm trying to use. (In fact, I visited this page looking for `input_value`, but it was missing!) For example, if I try to look for `get_attribute`, apart from the fact that the table has `getAttribute` instead, the table isn't in alphabetical order. Visually, I scan up and down the column looking for it. Eventually, I either find it or I try Ctrl-F. At a second glance, I noticed that the columns are sorted visually based on the check type (Attached, Visible, etc.), but I don't think most folks would visually scan this table looking for things in that way. Alphabetizing the actions makes it much easier to visually search. Perhaps column sorters could be added for users to sort rows how they please.

### Code snippet to reproduce your bug

```shell
N/A
```

### Relevant log output

```shell
N/A
```

**Comment by mxschmitt** [comment]
Closing for now, since we could reference in theory to `Page.click`, `ElementHandle.click`, or `Locator.click` - but as you know we recommend `Locator.click`.

To not confuse them we that much - we think keeping it like that is the best for now even tho the casing is different.
