### ISSUE TITLE
[Bug]: Playwright doesn't work in my computer

### ISSUE THREAD

**Issue by guimendesjulio** [microsoft/playwright-python#1058]
### Playwright version

1.17.0

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium, Firefox, WebKit

### Other information

Python Version 3.8.8
![Capturar12](https://user-images.githubusercontent.com/95357261/144241352-d50867dc-1b1d-43ae-a6b5-427ce030ea8c.PNG)
![Capturar123](https://user-images.githubusercontent.com/95357261/144241358-4a2ccea2-be0f-455a-a533-a77803b5a2e6.PNG)

### What happened? / Describe the bug

My playwright does not work, even following the instructions in this link: https://playwright.dev/python/docs/intro/

So I called my friend that works with python longer than me, and we check some requirements:

1. python version;
2. pip version;

And it are the same as mine.

So he run the "pip install playwright" and "install playwright" and it did work on his pc that have the same settings that mine.

So he send me his 'pip list' and I installed the same packages that he has and it still didn't work

I'd like to know what happens and what I can do to solve this problem.

### Relevant log output

```shell
[Running] python -u "c:\Users\ME\Desktop\VSCODE\playwright.py"
Traceback (most recent call last):
  File "c:\Users\ME\Desktop\VSCODE\playwright.py", line 1, in <module>
    from playwright.sync_api import sync_playwright
  File "c:\Users\ME\Desktop\VSCODE\playwright.py", line 1, in <module>
    from playwright.sync_api import sync_playwright
ModuleNotFoundError: No module named 'playwright.sync_api'; 'playwright' is not a package

[Done] exited with code=1 in 0.054 seconds
```

**Comment by mxschmitt** [comment]
Which pip and python version are you using?

```
python --version
pip --version
```

some guess: the problem _might_ be that your file is named `playwright.py`, maybe try renaming it to `trying_playwright.py` instead.

**Comment by mxschmitt** [comment]
Closing since it seems stale. Please create a new issue if you still encounter bugs.

**Comment by Rwinkah** [comment]
Had the same issue , bloody ridiculous!. Changing the file name from playwright.py solved the issue

**Comment by abdalrhman-abas-0** [comment]
how can I change the  playwright.py file name, what it's directory?

**Comment by PyScriptZenith** [comment]
Good afternoon guys! I have a very strange situation - the playwright library does not work for me. I run the script with an example from the documentation and nothing happens, the script does not complete. I tried adding print(), but it also doesn't output anything to the console. I wrote to my friend and sent my script - everything works for him. Please help me, I don't understand at all what the problem might be, because obviously there are no errors? The process does not complete and the console output remains in the same state as in the screenshot (see attachment). Tell me, please, how can I try to fix this?

Playwright Version 1.42.0
Python 3.11.4
Windows 10

from playwright.sync_api import sync_playwright

 ```
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch(headless=False)
    page = browser.new_page()
    print(browser)
    print(page)
    page.goto("https://playwright.dev/")
    page.screenshot(path="example.png")
    browser.close()
![playwright_error](https://github.com/microsoft/playwright-python/assets/134920106/8ec64d3a-5a41-41ba-bfe6-6cbfeb6f9bfe)

 ```

**Comment by kevit-hardik-mehta** [comment]
> Which pip and python version are you using?
> 
> ```
> python --version
> pip --version
> ```
> 
> some wild guess: the problem _might_ be that your file is named `playwright.py`, maybe try renaming it to `trying_playwright.py` instead.

This worked for me, but can someone explain to me the reason behind it?

**Comment by mxschmitt** [comment]
Python recognises `playwright` as a module and so the import doesn't work.
