### ISSUE TITLE
[Feature]: `playwright --version` is confusing

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright-python#1063]
### Feature request

```
> playwright --version
Version 1.17.1

> pip show playwright
Name: playwright
Version: 1.17.2
```
i think `playwright --version` should show both the playwright "core" version and the playwright python version, something like:
```
> playwright --version
Core Version 1.17.1
Python Version 1.17.2
```

**Comment by mxschmitt** [comment]
Done in .NET/Python and moved Java to https://github.com/microsoft/playwright-java/issues/742
