### ISSUE TITLE
[Question]: How to run installation from Python script?

### ISSUE THREAD

**Issue by lanzorg** [microsoft/playwright-python#1069]
### Your question

I can do it with playwright-dotnet.

```c#
Microsoft.Playwright.Program.Main(new[] {"install", "firefox"});
```

How to do the same with the Python variant?

**Comment by mxschmitt** [comment]
This is not possible, what is your use-case for it?

**Comment by lanzorg** [comment]
I just discovered it was possible with playwright-dotnet so I wanted to test with the python and node variants.

I don't really have a specific use case in mind.

**Comment by mxschmitt** [comment]
With .NET this isn't officially supported either. (Not documented anywhere).

Closing since there isn't a specific problem/issue which this is solving.
