### ISSUE TITLE
[Feature]: Change max_size argument value when connecting to playwright server websocket endpoint

### ISSUE THREAD

**Issue by inuatsu** [microsoft/playwright-python#1071]
### Feature request

In our company's project, I launch a server using `playwright launch-server chromium` command in one container, and connect to the server container via websocket from other containers using `browser_type.connect` method.

I noticed that when trying to take a full screenshot of a very lengthy page (for example [this one](https://www.smashingmagazine.com/2017/05/long-scrolling/)), I always encounter the following error.

```
File "/var/task/playwright/sync_api/_generated.py", line 7850, in screenshot
    self._sync(
File "/var/task/playwright/_impl/_sync_base.py", line 111, in _sync
    return task.result()
File "/var/task/playwright/_impl/_page.py", line 591, in screenshot
    encoded_binary = await self._channel.send("screenshot", params)
File "/var/task/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
File "/var/task/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Playwright connection closed
```

I read the [websockets library document](https://websockets.readthedocs.io/en/9.0.1/api/client.html#using-a-connection) and found out there is a incoming message size limit of 1MiB in default.

> The `max_size` parameter enforces the maximum size for incoming messages in bytes. The default value is 1 MiB. `None` disables the limit. If a message larger than the maximum size is received, recv() will raise ConnectionClosedError and the connection will be closed with code 1009.

[This code](https://github.com/microsoft/playwright-python/blob/main/playwright/_impl/_transport.py#L195-L199) connects to the websocket server using `websockets.client.connect` method in websockets library. Here `max_size` argument is not specified, thus default value of `1048576` is used.

Once I change the code as the following (add `max_size=None` argument in `websocket_connect` method), full screenshot can be taken without error even if the page is very lengthy.

```
    async def connect(self) -> None:
        try:
            self._connection = await websocket_connect(
                self.ws_endpoint, max_size=None, extra_headers=self.headers
            )
        except Exception as exc:
            self.on_error_future.set_exception(Error(f"websocket.connect: {str(exc)}"))
            raise exc
```

It would be more convenient if other arguments than `extra_headers` can be configurable when connecting to websocket endpoint.

**Comment by mxschmitt** [comment]
We'll soon rewrite the websocket connection logic (BrowserType.connect) and move it over to the Node.js driver side. This then gets resolved automatically.

**Comment by mxschmitt** [comment]
I'll fold it into https://github.com/microsoft/playwright-python/issues/1177
