### ISSUE TITLE
[Question]: Thread is blocked in the await self._transport.wait_until_stopped() statement

### ISSUE THREAD

**Issue by CodePythonFollow** [microsoft/playwright-python#1075]
### Your question

Use the return statement inside the "async with async_playwright() as driver" statement. If i do not close the browser before the return statement, the program will be blocked in the "await self._transport.wait_until_stopped()" statement.

**Comment by mxschmitt** [comment]
I can repro with the following:

```python
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()
    page.goto("http://playwright.dev")
    print(page.title())
    # browser.close()
print("done")
```

**Comment by mxschmitt** [comment]
Closing since its stale.
