### ISSUE TITLE
[Question]: Tips to make Playwright more 'resilient' against fingerprinting

### ISSUE THREAD

**Issue by sla-te** [microsoft/playwright-python#1079]
### Tips to make Playwright more 'resilient' against fingerprinting

Are there any launch options or integrated switches I could set, in order to achieve, what is described in the topic? I'm currently using Firefox with a "random" viewport and screensze, as well as color theme but thats about it.

**Comment by mxschmitt** [comment]
Playwright is designed for end-to-end testing - since this is not a direct use-case for it, I'm closing it.

If you want to make it resilient against fingerprinting, you can use different context and launch options. Usually User-Agent and IP are important factors.
