### ISSUE TITLE
[playwright._impl._api_types.TimeoutError: Timeout while waiting for event "popup"]

### ISSUE THREAD

**Issue by oioie** [microsoft/playwright-python#1080]
This is my python's code:
![image](https://user-images.githubusercontent.com/66261721/146747952-f5d68561-9e11-43a0-9fdd-93f7391c2506.png)
This is my html's code:
![image](https://user-images.githubusercontent.com/66261721/146747876-098e1c54-a728-47af-918f-5edb1b603abb.png)
This is my pic of html 
![image](https://user-images.githubusercontent.com/66261721/146748400-2fb7ea43-efb3-4281-b20d-5bdf7d555ee6.png)
detail:When my code is running,it's stuck here for 'popup',but browser opened  popup,After, its always in here,not print title.. not close.
omg!pls.

**Comment by yury-s** [comment]
You might want to remove 'javascript:' prefix from the js snippet. Please share the code of the repro inlcuding `showDetailWin` so that we can help you.

**Comment by oioie** [comment]
> 您可能希望从 js 代码段中删除 'javascript:' 前缀。请分享包含复制代码的代码，`showDetailWin`以便我们为您提供帮助。
![image](https://user-images.githubusercontent.com/66261721/146853375-f4b46432-f36d-4e5e-8351-c2259002b296.png)


()It's look like a button,If i clicked.It jumps out of a window, a process described in the Ourselves DOC.

**Comment by yury-s** [comment]
Please share the code, otherwise it's hard to advise.

**Comment by oioie** [comment]
> 请分享代码，否则很难建议。
def Detail(page,context):#订单详情
  k=len(page.query_selector_all('//*[@id="queryOrderGrid"]/tbody/tr'))
  print(k)
  for i in range(2,k+1):
    data={}
    if i%2!=0:
      continue
    else:
      data['order']=page.query_selector('//*[@id="queryOrderGrid"]/tbody/tr['+str(i)+']').text_content()[0:11]
      with page.expect_popup() as popup_info:
        js='javascript:showDetailWin("'+data['order']+'");'
        page.evaluate(js)
      new_page=popup_info.value
      # new_page.wait_for_load_state()
      print(new_page.title())
      time.sleep(1)

**Comment by oioie** [comment]
i find the webpage's js source code of showDetailWin！：
function showDetailImageVC(imgItem) {
    var url=$(imgItem).attr("src");
    window.open(url);
}

**Comment by oioie** [comment]
> 请分享代码，否则很难建议。 
I shared my code of showDetaiWin.sir.

**Comment by oioie** [comment]
> 请分享代码，否则难受。
I shared my code of showDetaillwin.

**Comment by oioie** [comment]
> 您可能希望从 js 代码段中删除 'javascript:' 前缀。请分享包含复制代码的代码，`showDetailWin`以便我们为您提供帮助。
Sir, I removed ‘javascript:’ for you advice.,but it are not getting better.

**Comment by mxschmitt** [comment]
We need to have the full code so we can run it locally, otherwise we can't act on it.

In the meantime I'd recommend to check out this page, for debugging the issue further: https://playwright.dev/python/docs/debug

**Comment by mxschmitt** [comment]
Closing since we can't act on that without having a repro. Please create a new issue with more details.
