### ISSUE TITLE
[Question]:Node.exe can't run!

### ISSUE THREAD

**Issue by oioie** [microsoft/playwright-python#1084]
### Your question

Unable to locate the program output point GetHostNameW on ws2_32.dll.

**Comment by mxschmitt** [comment]
Which operating system are you using or what are the details of your environment?

**Comment by oioie** [comment]
> 您使用的是哪种操作系统或您的环境的详细信息是什么？
Windows server 2008 R2 pk1

**Comment by oioie** [comment]
> 您使用的是环境信息或您的环境的详细信息是什么？

windows server 2008 R2 pk1

**Comment by mxschmitt** [comment]
Windows Server 2008 R2 has reached E
EOL (end of life) see here: https://docs.microsoft.com/en-us/troubleshoot/windows-server/windows-server-eos-faq/end-of-support-windows-server-2008-2008r2

So there is no support guaranteed in the future.

**Comment by oioie** [comment]
![1640573397(1)](https://user-images.githubusercontent.com/66261721/147429528-6de423fb-0574-40fd-89c1-14eb1b303380.jpg)
I know the version was EEQL,but a lot of company chiose it for server in chinese. i saw the node.js official site. i replace v13 for v16.and not working.I want to replace ws2_32.dll.maybe?

**Comment by mxschmitt** [comment]
The only way is to use an older version of Playwright, you can install it e.g. with `pip install playwright==1.16` and go as low as the latest supported version was.

Replacing just files does not work - you could replace the node folder with the actual Node.js 14.X release, this probably works but is not recommended.

**Comment by abubelinha** [comment]
@mxschmitt I got a similar issue on Windows 7 64bit, Python 3.8
```python
pip install playwright
C:\Python38\scrps\playwright -V
```
Messagebox: _The Procedure Entry Point GetHostNameW Could Not Be Located in the Dynamic Link Library ws2_32.dll_.

Is there any version of playwright that I can somehow run on this machine?
Thanks
