### ISSUE TITLE
[Bug]: pyinstaller cannot run after packaging

### ISSUE THREAD

**Issue by 265525** [microsoft/playwright-python#1090]
### Playwright version

1.17

### What happened? / Describe the bug

![91Y4 5GX40X%DOGI54S 77A](https://user-images.githubusercontent.com/30653455/147901295-0658a51e-3a51-4b51-909b-fe9030486522.png)
My pyinstaller version is 4.7
When i open the exe
![8DW%9LXLL0W $2MV9U2E()Y](https://user-images.githubusercontent.com/30653455/147901396-90fc9cc0-2781-4af8-bd96-a85502180357.png)
I am running Windows 10

**Comment by 265525** [comment]
Oh，I have solved this problem now，https://github.com/microsoft/playwright-python/issues/829，thank you

**Comment by mxschmitt** [comment]
See here yeah: https://playwright.dev/python/docs/next/intro#pyinstaller
