### ISSUE TITLE
[Bug]: The latest version of add_cookies sets the cookie invalid, but the same code 1.11.1 is possible

### ISSUE THREAD

**Issue by zhang52linux** [microsoft/playwright-python#1092]
### Playwright version

1.17.1

### What happened? / Describe the bug

context = await browser.new_context()
if cks:
       await context.add_cookies(cks)
page = await context.new_page()

### Code snippet to reproduce your bug

```shell
context = await browser.new_context()
        if cks:
            await context.add_cookies(cks)
        page = await context.new_page()
```

**Comment by mxschmitt** [comment]
What does `cks` contain?

**Comment by zhang52linux** [comment]
sorry，cks Something like [{"name": "x", "value": "123456"}]

**Comment by zhang52linux** [comment]
I follow the Parameters
        ----------
        cookies: List[{name: str, value: str, url: Union[str, NoneType], domain: Union[str, NoneType], path: Union[str, NoneType], expires: Union[float, NoneType], httpOnly : Union[bool, NoneType], secure: Union[bool, NoneType], sameSite: Union["Lax", "None", "Strict", NoneType]}]
To define cks,

**Comment by mxschmitt** [comment]
Can you provide us a repro for it? Probably you hit a breaking change which Chromium has made a few months ago. Try to specify the `url` or `domain`.

**Comment by mxschmitt** [comment]
Closing since its stale.
