### ISSUE TITLE
[internal] api review for 1.18

### ISSUE THREAD

**Issue by dgozman** [microsoft/playwright-python#1097]
- [x] `await expect(locator).toBeChecked({ checked })`
- [x] `await expect(response).toBeOK()`
  - [x] it is async, check docs!
  - [x] microsoft/playwright#11303
- [x] `locator.dragTo(locator)`
- [x] `test.extendTest(test)` to merge two test objects
  - [x] rename to `_extendTest` and remove from .d.ts.
- [x] `testInfo.attach(...)`
  - [x] `attach(name, options: { contentType: string, path: string, body: string|Buffer })`
  - [x] explain contentType inference thoroughly
- [x] `test.fixme('testname', () => {})` - top-level similar to `test.skip`
- [x] option fixtures `{ option: true }`
- [x] `test.info()`
- [x] `acceptDownloads` defaults to true everywhere
- [x] assertions api in python
  - [ ] https://github.com/microsoft/playwright/pull/11227/files for python?
- [x] `Suite.hooks` in reporter api that contains beforeAll/afterAll hooks
  - [x] hide for now
- [x] `locator('button', { hasText: 'Submit' })`
- [x] `apiRequestContext` in java

**Comment by mxschmitt** [comment]
Done!
