### ISSUE TITLE
如何使用FastApi调用Playwright

### ISSUE THREAD

**Issue by lvyaoyu** [microsoft/playwright-python#1099]
![This is an image](https://github.com/lvyaoyu/lvyaoyu/blob/master/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20220112171332.png)

**Comment by lvyaoyu** [comment]
> 你能用 Python 3.9 或 3.10 试试吗？

I used python3.9.9, but it still didn't work

**Comment by lvyaoyu** [comment]
> 你能用 Python 3.9 或 Python 3.10 试试吗？

import uvicorn
from fastapi import FastAPI
from playwright.async_api import async_playwright
from playwright.sync_api import sync_playwright

from tests import test5

app = FastAPI()


@app.get('/async_html')
async def get_html(
        url: str
) -> str:
    playwright = await async_playwright().start()
    browser = await playwright.chromium.launch()
    context = await browser.new_context()

    page = await context.new_page()
    await page.goto(url)
    html = await page.content()
    await playwright.stop()
    return html


if __name__ == '__main__':
    uvicorn.run(app='test4:app', host="0.0.0.0", port=8080, reload=True, debug=True)

**Comment by Rebely22** [comment]
uvicorn use WindowsSelectorEventLoopPolicy on windows as default eventloop policy, 
see https://github.com/encode/uvicorn/pull/1257

but WindowsSelectorEventLoopPolicy did not implement loop.subprocess_exec method, at least on python3.9, which playwright replies on.
switch eventloop to ProcatorEventLoop then your code will work,

`   loop = asyncio.ProactorEventLoop()
    asyncio.set_event_loop(loop)
    config = Config(
        app=app,
        loop=loop,
    )
    server = Server(config)
    loop.run_until_complete(server.serve())
`

the side effect is that uvicorn hot reload feature will not work

**Comment by Rebely22** [comment]
this is a issue with uvicorn default event loop.
uvicorn use ProactorEventLoop as default eventloop on windows, which doesn't work well with playwright
see https://playwright.dev/python/docs/intro#incompatible-with-selectoreventloop-of-asyncio-on-windows

you can force uvicorn to use  SelectorEventloop, but fastapi will lose ability to reload.

**Comment by phoenixor** [comment]
> force uvicorn to use SelectorEventloop

how to force uvicorn to use SelectorEventloop

**Comment by Leon0824** [comment]
I solved this by opening another process.

Here is an example:

```py
import multiprocessing as mp
from fastapi import FastAPI
from playwright.sync_api import Locator, sync_playwright

app = FastAPI()

def crawl_page(page: int, q: mp.Queue):
    with sync_playwright() as pw:
        # Put Playwright code here
        crawled_page = 'ABC' 
        q.put(crawled_page)

@app.get(path='/')
def get_page(page: int):
    q = mp.Queue()
    process = mp.Process(target=crawl_page, args=(page, q))
    process.start()
    response = q.get()
    process.join
    return response
```

**Comment by williambarberjr** [comment]
> I solved this by opening another process.
> 
> Here is an example:
> 
> ```python
> import multiprocessing as mp
> from fastapi import FastAPI
> from playwright.sync_api import Locator, sync_playwright
> 
> app = FastAPI()
> 
> def crawl_page(page: int, q: mp.Queue):
>     with sync_playwright() as pw:
>         # Put Playwright code here
>         crawled_page = 'ABC' 
>         q.put(crawled_page)
> 
> @app.get(path='/')
> def get_page(page: int):
>     q = mp.Queue()
>     process = mp.Process(target=crawl_page, args=(page, q))
>     process.start()
>     response = q.get()
>     process.join
>     return response
> ```

FastAPI hangs for me when I use this example code. It never gets back to return the response. Is anyone else able to get this solution to work for them?

**Comment by Leon0824** [comment]
@williambarberjr 

There is an mistake in my snippet. `join()` should be an function. I have fixed the snippet.

**Comment by williambarberjr** [comment]
> @williambarberjr
> 
> There is a mistake in my snippet. `join()` should be a function. I have fixed the snippet.

Got it, thanks, I've sorted out that I'm using gunicorn not uvicorn, and pm2. Followed this setup: https://travisluong.medium.com/how-to-deploy-fastapi-with-nginx-and-pm2-94176902460b

So that's probably part of the problem as well.

**Comment by pheman** [comment]
just set reload=False in uvicorn.run
find more at https://github.com/tiangolo/fastapi/issues/5446

**Comment by kaonick** [comment]
My solution is add below code before unicorn run:

```
asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())
```

**Comment by CNSeniorious000** [comment]
For those who are still suffering from this behavior, I found a way to use playwright together with uvicorn with live reload. Just replace

```sh
uvicorn main:app --reload --....
```

with

```sh
watchfiles "uvicorn main:app --...."
```

This approach works fine for me.

---

I prefer uvicorn's CLI usage over its Python API because I think this is the right way to boot an ASGI application.

In fact, I usually use hypercorn instead of uvicorn in production environments.
