### ISSUE TITLE
[BUG]: Timeout when trying to access iframe content

### ISSUE THREAD

**Issue by eckhards** [microsoft/playwright-python#1102]
**Context:**
- Playwright Version: 1.16
- Operating System: Linux
- Python version: 3.8
- Browser: Chromium

**Problem**

I am loading a page that includes 3 iframes, all non-ssl-encrypted (I assume that is the issue). I need to access child frames and grab their content, or at least gracefully handle the error in case they are not accessible for some reason.

In this case I can neither get the iframe url, nor is an exception thrown that i could catch. The script just runs into a timeout when trying to access the iframe content.

Any idea what the problem is, and how I could gracefully exit, e.g. by detecting the problem before trying to access the iframe content? Thanks!

**Code Snippet**

```
import asyncio
from playwright.async_api import async_playwright

async def main():

	async with async_playwright() as p:
		for browser_type in [p.chromium]:
			browser = await browser_type.launch()
			page = await browser.new_page()
			try:
				await page.goto(url='https://www.buergerhilfe-sachsen.de/',wait_until = 'networkidle',timeout = 5000)
			except:
				pass

			main_frame = page.main_frame
			child_frames = main_frame.child_frames
			print("child_frames length:",len(child_frames))
			if(len(child_frames) > 0):
				for frame_index in (0,len(child_frames)-1):
					try:
						print("iframe url",child_frames[frame_index].url)
						source = await child_frames[frame_index].content()
					except Exception as ex:
						print(str(type(ex).__name__) + str(ex.args))
						print("something went wrong")

			await browser.close()

asyncio.get_event_loop().run_until_complete(main())

**Comment by mxschmitt** [comment]
Probably the iframe gets lazily initialised and thats the reason why the iframe is not there. I was not able to repro the case that it leads to a timeout error, for me it always ended up in child_frames=0.
I'd recommend to use frame locators if you want to interact with elements across different iframes, they also wait always until the iframe is loaded, the element visible etc.: https://playwright.dev/python/docs/api/class-framelocator
