### ISSUE TITLE
[BUG] Cannot get before_unload to work cross browser (webkit, chromium, firefox)

### ISSUE THREAD

**Issue by dwt** [microsoft/playwright-python#1105]
**Context:**
- Playwright Version: 1.17.2 (self reports as 1.17.1 with `playwright --version`)
- Operating System: Mac
- Python version:  3.9.9
- Browser: All

**Code Snippet**

```

from playwright.sync_api import sync_playwright

import pytest

HEADLESS = True
HEADLESS = False

WAIT = 5000

@pytest.fixture(scope='session', params=('firefox', 'chromium', 'webkit'))
def browser_vendor(request):
    yield request.param

@pytest.fixture(scope='session')
def browser(browser_vendor):
    with sync_playwright() as playwright:
        browser = getattr(playwright, browser_vendor)
        instance = browser.launch(headless=HEADLESS)
        yield instance
        instance.close()

@pytest.fixture
def context(browser):
    context = browser.new_context()
    yield context
    context.close()

@pytest.fixture
def page(context):
    page = context.new_page()
    page.set_default_timeout(WAIT)
    yield page



html = '''
<form>
    <label for=input_id id=label>input_label</label>
    <input id=input_id class=input_class name=input_name value=input_value 
        title=input_title placeholder=input_placeholder aria-label=input_aria_label>
    <div id=div_id>div_text</div>
</form>
'''

ask_to_leave_script = '''
// interestingly Firefox webdriver doesn't show thes dialogs at all, even though this code works in normal Firefox
window.addEventListener('beforeunload', function (e) {
    // Cancel the event
    e.preventDefault(); // mozilla will now always show dialog
    // Chrome requires returnValue to be set
    e.returnValue = 'Fnord';
});
'''

def test_before_unload(page):
    # delay unload
    page.set_content(html)

    page.evaluate(ask_to_leave_script)
    # page needs a change otherwise the onbeforeunload doesn't trigger
    page.fill('text=input_label', value='fnord')
    
    did_handle_beforeunload = False
    def handle_dialog(dialog):
        # breakpoint()
        global did_handle_beforeunload
        assert dialog.type == 'beforeunload'
        dialog.dismiss()
        did_handle_beforeunload = True
    page.on('dialog', handle_dialog)
    page.close(run_before_unload=True)
    # Fails, not sure why that is, the dialog just doesn't show up
    assert did_handle_beforeunload
```

**Describe the bug**

All browsers fail in different ways on this code. Firefox doesn't even show the dialog and just errors out. Chromium and Webkit both show the dialog but aren't able to close it in the dialog handler.

I'm honestly a bit at a loss on what to do here. Am I using the API wrong? Am I missing some setting that needs to be added to these browsers? Is this just a bug in the playwright api?

**Comment by dwt** [comment]
To execute

```shell
$ mktmpenv
$ pip install playwright pytest
$ playwright install
$ pytest reproduction.py
```

**Comment by mxschmitt** [comment]
By default the before unload event does not get fired. You can opt-in by passing it when closing the page (`page.close(run_before_unload=True)`).
In your test-the scope of the `did_handle_beforeunload` variable is not ending up the same inside the function, thats why its always False.

I rewrote it a bit, here you see a working example:

```py
from playwright.sync_api import sync_playwright

import pytest

HEADLESS = True
HEADLESS = False

WAIT = 5000

@pytest.fixture(scope='session', params=('firefox', 'chromium', 'webkit'))
def browser_vendor(request):
    yield request.param

@pytest.fixture(scope='session')
def browser(browser_vendor):
    with sync_playwright() as playwright:
        browser = getattr(playwright, browser_vendor)
        instance = browser.launch(headless=HEADLESS)
        yield instance
        instance.close()

@pytest.fixture
def context(browser):
    context = browser.new_context()
    yield context
    context.close()

@pytest.fixture
def page(context):
    page = context.new_page()
    page.set_default_timeout(WAIT)
    yield page
    page.close(run_before_unload=True)



html = '''
<form>
    <label for=input_id id=label>input_label</label>
    <input id=input_id class=input_class name=input_name value=input_value 
        title=input_title placeholder=input_placeholder aria-label=input_aria_label>
    <div id=div_id>div_text</div>
</form>
'''

ask_to_leave_script = '''
// interestingly Firefox webdriver doesn't show thes dialogs at all, even though this code works in normal Firefox
window.addEventListener('beforeunload', function (e) {
    // Cancel the event
    e.preventDefault(); // mozilla will now always show dialog
    // Chrome requires returnValue to be set
    e.returnValue = 'Fnord';
});
'''

def test_before_unload(page):
    # delay unload
    page.set_content(html)

    page.evaluate(ask_to_leave_script)
    # page needs a change otherwise the onbeforeunload doesn't trigger
    page.fill('text=input_label', value='fnord')
    
    page.click("body")

    with page.expect_event("dialog") as dialog_info:
        page.close(run_before_unload=True)
    dialog = dialog_info.value
    assert dialog.type == "beforeunload"

    with page.expect_event("close"):
        dialog.accept()

```

**Comment by dwt** [comment]
> By default the before unload event does not get fired. You can opt-in by passing it when closing the page (`page.close(run_before_unload=True)`). 

I am slightly confused - I did do this, no?

> In your test-the scope of the `did_handle_beforeunload` variable is not ending up the same inside the function, thats why its always False.

I did check by adding breakpoints in the handler - it was never called, I'll give the global handling another try, I may be misunderstanding my python here, so that's something I definitely need to check.

Turns out I am. TIL: This is how it's supposed to work in python:

```python
#!/usr/bin/env python3

def outer():
    variable = 'foo'
    def inner():
        nonlocal variable
        variable = 'bar'
    inner()
    print(variable)

outer()
```

> I rewrote it a bit, here you see a working example:

This is _really_ helpful. Thanks a lot!

Using that code I refined my example, and can now trigger a consistent pattern that might be a bug or maybe another thing that I'm learning about python that I didn't know before.

```python
def test_before_unload(page):
    # delay unload
    page.set_content(html)

    page.evaluate(ask_to_leave_script)
    # page needs a change otherwise the onbeforeunload doesn't trigger
    page.fill('text=input_label', value='fnord')
    page.click('body')
    
    did_handle_beforeunload = False
    def handle_dialog(dialog):
        nonlocal did_handle_beforeunload
        assert dialog.type == 'beforeunload'
        breakpoint()
        dialog.dismiss()
        breakpoint()
        did_handle_beforeunload = True
    page.on('dialog', handle_dialog)
    page.close(run_before_unload=True)
    # Fails, not sure why that is, the dialog just doesn't show up
    breakpoint()
    assert did_handle_beforeunload
```

Things I had to adapt:
1. `page.click('body'` seems to be required for FF to trigger the dialog at all
2. `nonlocal did_handle_beforeunload` is the right way to do it in python3 

What this shows is that the last line of the function `assert did_handle_beforeunload` is executed _before_ `handle_dialog()` is called - which is why the assert always fails.

Is that a bug in the way playwright executes the `handle_dialog()` or is that a restriction in python where it simply is not possible another way? If it is the latter that should definitely [be documented](https://playwright.dev/python/docs/api/class-page#page-event-dialog) as that is a serious difference from what one would expect.

In the meantime, your example has shown me a way to move forward, so many thanks for providing me with a workaround for my use case.

**Comment by mxschmitt** [comment]
> I am slightly confused - I did do this, no?

You are right - you did the right thing there already!

Regarding the events, it depends how they are coming in, it's not ensured that page.close waits for the dialogs to emit. 
 Since we don't know if there are before unload handlers etc. Using `expect_event("dialog")` should help there to fix this race as seen in my example above.

Closing since all questions are answered.
