### ISSUE TITLE
[BUG] Official docs missing 1.18 version

### ISSUE THREAD

**Issue by nusnuson** [microsoft/playwright-python#1116]
**Describe the bug**

The latest release is 1.18(.1) but the official docs say 1.17.
![image](https://user-images.githubusercontent.com/74551562/150339913-4fe69d09-af40-4552-b604-8cadfe289196.png)

**Comment by mxschmitt** [comment]
They are currently getting published.

**Comment by nusnuson** [comment]
Oh, I thought it was part of the deployment pipeline as a step _before_ it goes public. Now I know :)
