### ISSUE TITLE
[BUG] Failed to launch browser when runs in QThread

### ISSUE THREAD

**Issue by zhanghua000** [microsoft/playwright-python#1119]
**Context:**
- Playwright Version: Version 1.18.1
- Operating System: Windows
- Python version: 3.10.2
- Browser: Edge, Chromium, Firefox are tested
- Extra: PySide6 version: 6.2.2.1

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally.
```python
from PySide6.QtCore import QObject,QThread,Signal
from PySide6.QtWidgets import QApplication,QWidget,QHBoxLayout,QPushButton,QLabel
from playwright.sync_api import sync_playwright

class SubThreadObject(QObject):
    stop=Signal()
    msg=Signal(str)
    def __init__(self) -> None:
        super().__init__()
    def start(self):
        with sync_playwright() as p:
            self.msg.emit("launching...")
            browser=p.chromium.launch(channel="msedge")
            context=browser.new_context()
            page=context.new_page()
            page.goto("https://bing.com")
            self.msg.emit("done")
            browser.close()
            self.stop.emit()
    
if __name__=="__main__":
    app=QApplication()
    window=QWidget()
    layout=QHBoxLayout()
    thread=QThread()
    work=SubThreadObject()
    label=QLabel()
    work.moveToThread(thread)
    work.stop.connect(thread.quit)
    work.msg.connect(label.setText)
    thread.started.connect(work.start)
    button=QPushButton("Start")
    button.clicked.connect(thread.start)
    layout.addWidget(label)
    layout.addWidget(button)
    window.setLayout(layout)
    window.show()
    exit(app.exec())
```
**Describe the bug**

Run this script with `pythonw` rather than `python`, after window appears, click "Start" button.
**Expected behavior:**
QLabel shows "launching..." and then shows "done"
**Actual behavior:**
Nothing happens.
**Notes:**
Although I am using sync api, async api also has this problem. Also, running script with `python` can also fix this.

**Comment by rwoll** [comment]
Closing as part of triage. If this is still preventing you from using Playwright, please re-file and explain your overall usecase. Perhaps there's another recommendation.

Thanks!
