### ISSUE TITLE
[BUG] Slow `page.evaluate` after period of time.

### ISSUE THREAD

**Issue by byehack** [microsoft/playwright-python#1121]
**Context:**
- Playwright Version: [what Playwright version do you use?]
- Operating System: win10 20h2
- Python version: 3.7 x86
- Browser: Chromium
- Extra: 

**Code Snippet**
```python
import time
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch_persistent_context("E:\\temp", channel='chrome', headless=False, no_viewport=True)
    page = browser.new_page()
    page.goto("https://google.com")
    page.wait_for_timeout(5000)
    time.sleep(60*2)

    page.evaluate("4 +5")  # It takes too much time.
    browser.close()

```

**Describe the bug**

this occurs only when for a while code is stoped. like in `input()` or `time.sleep()`.

**Comment by byehack** [comment]
temporary workaround:
use `page.evaluate('1+2')` every 3 seconds in main thread.

**Comment by mxschmitt** [comment]
does it also happen when you use `page.wait_for_timeout(60*2)` instead of `time.sleep`?

Be aware of this: https://playwright.dev/python/docs/intro#timesleep-leads-to-outdated-state

**Comment by byehack** [comment]
> does it also happen when you use `page.wait_for_timeout(60*2)` instead of `time.sleep`?
> 
> Be aware of this: https://playwright.dev/python/docs/intro#timesleep-leads-to-outdated-state

yes, tested with `page.wait_for_timeout`, `time.sleep` and 2minute wait for user input.

**Comment by mxschmitt** [comment]
I tried the following which works for me without any issues, see here:

```py
from datetime import datetime
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch_persistent_context(
        "./foo", channel="chrome", headless=False, no_viewport=True
    )
    page = browser.new_page()
    page.goto("https://google.com")
    page.wait_for_timeout(30 * 1000)

    for i in range(50):
        print(datetime.now())
        page.evaluate("4 + 5")
    browser.close()
```
