### ISSUE TITLE
Could not find version that satisfied >= 1.18

### ISSUE THREAD

**Issue by thewasta** [microsoft/playwright-python#1122]
**Context:**
- Operating System: Linux armv71 (raspberry pi)
- Python version: 3.8
- pip version: pip 21.3.1 from /usr/lib/python3.8/site-packages/pip (python 3.8)

I create a `requirements.txt` file and this content this:
```txt
playwright >= 1.18
```
And to install I use `pip install -r requirements.txt`, return this error:
```bash
$ pip install -r requirements.txt 
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement playwright>=1.18 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 
0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.0.18, 0.7.0, 0.7.1, 0.8.0, 0.140.0, 0.142.0, 0.142.1, 0.142.2,
 0.142.3, 0.150.0, 0.151.0, 0.151.1, 0.152.0, 0.162.0, 0.162.1, 0.162.2)
ERROR: No matching distribution found for playwright>=1.18   
```

And I decided to install it by following guide
```
pip install --upgrade pip
pip install playwright
```
Not errors, but the version is `0.162.2`
```python
>>> from playwright._repo_version import version
>>> print(version)
0.162.2
```
I trying updating but same... (`apt update && apt upgrade`)

**Comment by mxschmitt** [comment]
armv71 is Raspberry PI 32 bit which is not supported by Playwright.
