### ISSUE TITLE
[Question]: Using the async version: How to access the Response object when using page.expect_request_finished() from inside the given predicate?

### ISSUE THREAD

**Issue by sla-te** [microsoft/playwright-python#1135]
e.g. for checking the status code

**Comment by sla-te** [comment]
Its probably  a bug or I have overseen something. In any case monkey patching the `WaitHelper's` `waIt_for_event()` to this super hacky thing makes it work..

```
	def wait_for_event(
		self,
		emitter: EventEmitter,
		event: str,
		predicate: Callable = None,
	) -> None:

		if (isinstance(predicate, FunctionType) and ((closure := (c.cell_contents for c in predicate.__closure__))
			and ((wrapped_func := next((c for c in closure if isinstance(c, FunctionType)), None))
			and asyncio.iscoroutinefunction(wrapped_func)))
		):
			async def listener(event_data: Any = None) -> None:
				if await predicate(event_data):
					self._fulfill(event_data)
		else:
			def listener(event_data: Any = None) -> None:
				if not predicate or predicate(event_data):
					self._fulfill(event_data)

		emitter.on(event, listener)
		self._registered_listeners.append((emitter, event, listener))
```

**Comment by mxschmitt** [comment]
It's important that the predicate is resolved synchronously otherwise events are processed out of order. You should use the "expect_response" context manager, filter by the response and when you are happy with it and get the request from the response and call "await request.finished()".

**Comment by sla-te** [comment]
Ah, alright, was not aware it can work properly like that, thanks!

**Comment by sla-te** [comment]
Just to clarify, there is no method `finished()` inside the `Request` object, that you get after awaiting ```response_obj = await response.value``` and then getting the corresponding request via `request = response.request`.  - There is only a method `finished` inside the `response_obj ` object itself.
