### ISSUE TITLE
[BUG] `playwright install` installs incorrect browser versions.

### ISSUE THREAD

**Issue by pgoy-dod** [microsoft/playwright-python#1136]
**Context:**
- Playwright Version: 1.9.1
- Operating System: Max OS Big Sur 11.6.1 (20G224)
- Python version: 3.10.1
- Browser: All

**Code Snippet**

```bash
pip install playwright
playwright install
pytest
```
(my test script is run, where i do `sync_playwright().start()`, and get this:)

```
E       playwright._impl._api_types.Error: Executable doesn't exist at /Users/perrygoy/Library/Caches/ms-playwright/chromium-956323/chrome-mac/Chromium.app/Contents/MacOS/Chromium
E       ╔═════════════════════════════════════════════════════════════════════════╗
E       ║ Looks like Playwright Test or Playwright was just installed or updated. ║
E       ║ Please run the following command to download new browsers:              ║
E       ║                                                                         ║
E       ║     playwright install                                                  ║
E       ║                                                                         ║
E       ║ <3 Playwright Team                                                      ║
E       ╚═════════════════════════════════════════════════════════════════════════╝

```

(these are the available browsers installed just moments ago:)

```bash
$ ls /Users/perrygoy/Library/Caches/ms-playwright
chromium-854489 ffmpeg-1005     firefox-1234    webkit-1438
```

**Describe the bug**

None of the correct browser versions are installed by `playwright install`. It seems like they are all behind. The versions that playwright-in-the-code is looking for are these:

```quote
chromium-956323
firefox-1313
webkit-1596
```

The ones that playwright actually installs are these:

```quote
chromium-854489
firefox-1234
webkit-1438
```

Running `playwright install` again does not do anything.

**Comment by mxschmitt** [comment]
You probably have multiple versions of Playwright installed and/or configured the PATH variable incorrectly. Try removing existing global Playwright Installations or use e.g. virtualenv.

**Comment by pgoy-dod** [comment]
> You probably have multiple versions of Playwright installed and/or configured the PATH variable incorrectly. Try removing existing global Playwright Installations or use e.g. virtualenv.

I am using virtualenv, and this is the first time i've ever installed Playwright. I've also done `rm -rf /Users/perrygoy/Library/Caches/ms-playwright` and done `playwright install` a second time. The same, incorrect versions are installed again.

**Comment by mxschmitt** [comment]
Could you try recreating your virtualenv and use the latest Playwright 1.18?

**Comment by pgoy-dod** [comment]
Uh... yeah, woops, that was the problem! I must have installed playwright globally by accident and it's using that one instead!

Thanks @mxschmitt! Closing as PEBCACK. 🤦

**Comment by OskarDamkjaer** [comment]
thanks @pgoy-dod creating the issue, I just got burnt on the same thing when migrating to PNPM 😄
