### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by px-tech** [microsoft/playwright-python#1138]
**Context:**
- Playwright Version: [what Playwright version do you use?]
- Operating System: [e.g. Windows, Linux or Mac]
- Python version: [e.g. 3.7, 3.9]
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally.
```

**Describe the bug**

Add any other details about the problem here.
![Screenshot_2022-01-30-17-35-11-1520574598](https://user-images.githubusercontent.com/70459087/151694406-f6c9855b-2773-4fb0-8220-a658a84b5456.png)

**Comment by mxschmitt** [comment]
This is an issue in greenlet, see here with a possible workaround: https://github.com/python-greenlet/greenlet/issues/46#issuecomment-872489205
