### ISSUE TITLE
[Question]: Access Denied when `headless=True`

### ISSUE THREAD

**Issue by SIC98** [microsoft/playwright-python#1139]
### Your question

A problem occurred while executing the simple code below.

```python
from playwright.sync_api import sync_playwright

url = 'https://www.bybit.com'

with sync_playwright() as p:
    # Launch the browser
    browser = p.chromium.launch(headless=True)

    # Open a new browser page
    page = browser.new_page()

    page.goto(url)
    page_content = page.content()
    print(page_content)
```

In line 7 of the code, if `headless=Flase`, `page_content` has normal html. But if `headless=True`, `page_content` has the following value.

```html
<html><head>
<title>Access Denied</title>
</head><body>
<h1>Access Denied</h1>
 
You don't have permission to access "http://www.bybit.com/" on this server.<p>
Reference #18.5f973b17.1643538644.2e2a9002


</p></body></html>
```

This access denied problem seems to occur only with a few urls. Why does this problem occur? And is there a way to solve it while maintaining the `headless=True` argument?

**Comment by mxschmitt** [comment]
Probably they filter requests by the user agent which is different in headed to headless.

Closing since this is not an issue in Playwright.
