### ISSUE TITLE
Unable to view all child frames

### ISSUE THREAD

**Issue by samim2022** [microsoft/playwright-python#1141]
**Context:**
- Playwright Version: 1.18.1
- Operating System: Windows
- Python version: 3.9
- Browser: Chromium
- Extra: [any specific details about your environment]

I am trying to display all the frames of my application. My application has more than  22 nested frames. But it is just displaying single frame. it is used to work in 1.13.1 version on chromium 93. but in chrome 98 I am unable to retrieve all child frames.

with sync_playwright() as p:
    for browser_type in [p.chromium]:
        browser = browser_type.launch(headless=False)
        page = browser.new_page()
        page.goto('http://...../')
        time.sleep(10)
        frames = page.frames
        browser.close()

**Comment by mxschmitt** [comment]
Can you provide us a reproducible? Without we can't act on this.

Be aware to not use time.sleep and use page.wait_for_timeout instead, see here: https://playwright.dev/python/docs/intro#timesleep-leads-to-outdated-state

**Comment by samim2022** [comment]
Thanks for the quick responce. I am unable to give the exact URL as that is privately deploy. The above issue come when few frames has different domain. Please check below example code.

with sync_playwright() as p:
    for browser_type in [p.chromium]:
        browser = browser_type.launch(headless=False)
        #context=browser.new_context()
        #page=context.new_page()
        page = browser.new_page()
        page.goto('https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_doc_domain')
        frames = page.frames
        print(len(frames))
        browser.close()

**Comment by mxschmitt** [comment]
What is expected here?

```python
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    for browser_type in [p.chromium]:
        browser = browser_type.launch(headless=False)
        #context=browser.new_context()
        #page=context.new_page()
        page = browser.new_page()
        page.goto('https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_doc_domain')
        frames = page.frames
        print(list(map(lambda x: (x.name, x.url), frames)))
        browser.close()
```

`[('', 'https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_doc_domain'), ('iframeResult', 'about:blank'), ('__tcfapiLocator', 'about:blank'), ('__uspapiLocator', 'about:blank')]` is the output there on my end.

**Comment by samim2022** [comment]
As you can see in that website there many other frames also available. Why it is not showing all the available frames ?

**Comment by samim2022** [comment]
I also try to getFrameTree using CDP commands but it is also not giving all the frames.

**Comment by mxschmitt** [comment]
Then this sounds like a chromium change and nothing Playwright related. Please file a bug on their end: crbug.com
