### ISSUE TITLE
[BUG] There are no windows wheels for `1.18.2`

### ISSUE THREAD

**Issue by KotlinIsland** [microsoft/playwright-python#1144]
https://pypi.org/project/playwright/1.18.1/#files
![image](https://user-images.githubusercontent.com/65446343/152098069-b66134cd-c2f5-4d98-ac2c-7f1a15e575be.png)

https://pypi.org/project/playwright/1.18.2/#files
![image](https://user-images.githubusercontent.com/65446343/152098094-58a4fc72-edb8-4935-b7c9-3ed7153b43c8.png)

**Comment by mxschmitt** [comment]
We hit the PIP package upload limits, I've raised an issue to increase them for our project: https://github.com/pypa/pypi-support/issues/1646

Thanks for reporting!

**Comment by mxschmitt** [comment]
@KotlinIsland files should be published now.

**Comment by mxschmitt** [comment]
Fixed in https://github.com/pypa/pypi-support/issues/1646.
