### ISSUE TITLE
[Question]: How to switch to a new window?

### ISSUE THREAD

**Issue by aprilahijriyan** [microsoft/playwright-python#1146]
### Your question

In selenium supports switching to a new window using `driver.window_handles` and `driver.switch_to.window()`

Does the playwright have such a feature?

**Comment by Svilen88** [comment]
https://playwright.dev/python/docs/api/class-browsercontext#browser-context-wait-for-page
https://playwright.dev/python/docs/api/class-browsercontext#browser-context-pages

I think you should use Browser Context with browser_context.expect_page() function. Or if you having couple of pages opened browser_contenxt.pages[ind].
