### ISSUE TITLE
[BUG] Page.type stop typing if networkidle event is reached

### ISSUE THREAD

**Issue by Svilen88** [microsoft/playwright-python#1147]
**Context:**
- Playwright Version: 1.5.* and 1.8.*
- Operating System: Linux
- Python version: 3.9
- Browser: Firefox, Chromium (can't test with WebKit, dependency issues on my side)
- Extra: None

**Code Snippet**
```
import os
os.environ['DEBUG'] = "pw:api"

from playwright.sync_api import sync_playwright, Page

def run(playwright):
    chromium = playwright.chromium # or "firefox" or "webkit".
    browser = chromium.launch(headless=False)
    page: Page = browser.new_page()
    page.goto('https://www.laptop.bg')
    try:
        page.click("//a[contains(text(), 'Към сайта')]", timeout=10000)
    except:
        pass
    page.type("#q", "MacBook Pro", delay=300)
    page.wait_for_timeout(10000)
    browser.close()

def main():
    with sync_playwright() as playwright:
        run(playwright)

if __name__ == "__main__":
    main()
```

**Describe the bug**

If `networkidle` event is reached while typing, will stop the typing and continue with the next command without any warning or error. This happens when dynamic search is implemented on the website and requests are sent with every keystroke.
Set the delay on 1ms or use fill instead of type are possible workarounds.

**Comment by mxschmitt** [comment]
I can't reproduce on my side. Could you try on a more recent Playwright version like 1.18.2?
