### ISSUE TITLE
[BUG] `playwright` hangs when an operation is interrupted

### ISSUE THREAD

**Issue by qwark97** [microsoft/playwright-python#1150]
**Context:**
- Playwright Version: 1.18.2 (but tested also with 1.15.3)
- Operating System: Linux
- Python version: 3.8.10
- Browser: Chromium, Firefox
- Extra:
The bug is also present inside Docker container

**Code Snippet**
Repo to present bug:
https://github.com/qwark97/hanging_operations_bug

**Describe the bug**
If during executing some `playwright` action (e.g. `page.goto()`) python process receives SIGTERM (which causes `KeybortInteruption` exception), the next `playwright` action will hang indefinitely. The browser itself closes (at least it looks like it closes in headed mode) but the python process will be stuck.

I've only tested it with python sync API, I don't know whether such behavior is also with async API

Idk whether it is expected behavior or not - I would expect receiving some exception and closing the process (even without `playwright` cleaning up after itself) but maybe you guys have some other thoughts about it

**Add any other details about the problem here.**
When I was testing it outside the docker I always was receiving this behavior. When I was using container, sometimes I was able to see "proper" behavior (process has ended) and once I saw such traceback (and process ended):
```bash
Traceback (most recent call last):
  File "run.py", line 45, in <module>
    start()
  File "run.py", line 30, in start
    page.close()
  File "/usr/local/lib/python3.8/dist-packages/playwright/sync_api/_generated.py", line 7901, in close
    self._sync(
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_sync_base.py", line 111, in _sync
    return task.result()
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_page.py", line 625, in close
    raise e
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_page.py", line 622, in close
    await self._owned_context.close()
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_browser_context.py", line 325, in close
    raise e
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_browser_context.py", line 321, in close
    await self._channel.send("close")
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Browser closed.
==================== Browser output: ====================
<launching> /ms-playwright/chromium-956323/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-83iNBa --remote-debugging-pipe --no-startup-window
<launched> pid=128
[pid=128][err] [0204/113852.435100:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[pid=128][err] [0204/113852.435398:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[pid=128][err] [0204/113852.457820:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
[pid=128][err] [0204/113852.488242:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[pid=128] <gracefully close start>
ERROR: 1
```

**Comment by arvinsebastian** [comment]
i am getting same messages while trying to launch electron playwright test in mcr.microsoft.com/playwright:v1.20.0-focal docker container.
`23:48:18 2022-03-23T18:18:18.343Z pw:browser <launched> pid=210
23:48:18 2022-03-23T18:18:18.519Z pw:browser [pid=210][err] [0323/181818.518120:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
23:48:18 2022-03-23T18:18:18.521Z pw:browser [pid=210][err] [0323/181818.520529:WARNING:bluez_dbus_manager.cc(248)] Floss manager not present, cannot set Floss enable/disable.
23:48:18 2022-03-23T18:18:18.523Z pw:browser [pid=210][err] [0323/181818.523396:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
23:48:18 2022-03-23T18:18:18.562Z pw:browser [pid=210][err] [0323/181818.558075:WARNING:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
23:48:20 2022-03-23T18:18:20.388Z pw:browser <ws connecting> ws://127.0.0.1:40797/7774371c42729d639fb6d3e28110c6b9
23:48:20 2022-03-23T18:18:20.417Z pw:browser <ws connecting> ws://127.0.0.1:40797/7774371c42729d639fb6d3e28110c6b9
23:48:20 2022-03-23T18:18:20.418Z pw:browser <ws connected> ws://127.0.0.1:40797/7774371c42729d639fb6d3e28110c6b9
23:48:20 2022-03-23T18:18:20.458Z pw:browser <ws connected> ws://127.0.0.1:40797/7774371c42729d639fb6d3e28110c6b9
23:48:21 2022-03-23T18:18:21.590Z pw:browser <ws disconnecting> ws://127.0.0.1:40797/7774371c42729d639fb6d3e28110c6b9
23:48:21 PASS browser: chromium src/test/sampleTestCase.spec.js
23:48:21 2022-03-23T18:18:21.639Z pw:browser <ws disconnected> ws://127.0.0.1:40797/7774371c42729d639fb6d3e28110c6b9 code=1005 reason=
23:48:22 2022-03-23T18:18:22.291Z pw:browser <launching> /project/node_modules/electron/dist/electron --inspect=0 --remote-debugging-port=0 --no-sandbox --enable-logging .
23:48:22 2022-03-23T18:18:22.301Z pw:browser <launched> pid=344
23:48:22 2022-03-23T18:18:22.515Z pw:browser [pid=344][err] Debugger listening on ws://127.0.0.1:44471/78d720ae-a973-47d3-a2f6-a7fa8867e316
23:48:22 2022-03-23T18:18:22.516Z pw:browser [pid=344][err] For help, see: https://nodejs.org/en/docs/inspector
23:48:22 2022-03-23T18:18:22.517Z pw:browser <ws connecting> ws://127.0.0.1:44471/78d720ae-a973-47d3-a2f6-a7fa8867e316
23:48:22 2022-03-23T18:18:22.523Z pw:browser <ws connected> ws://127.0.0.1:44471/78d720ae-a973-47d3-a2f6-a7fa8867e316
23:48:22 2022-03-23T18:18:22.525Z pw:browser [pid=344][err] Debugger attached.
23:48:22 2022-03-23T18:18:22.952Z pw:browser <ws disconnected> ws://127.0.0.1:44471/78d720ae-a973-47d3-a2f6-a7fa8867e316 code=1006 reason=
23:48:22 2022-03-23T18:18:22.958Z pw:browser [pid=344] <process did exit: exitCode=null, signal=SIGTRAP>
23:48:22 2022-03-23T18:18:22.961Z pw:browser [pid=344] starting temporary directories cleanup
23:48:23 2022-03-23T18:18:23.094Z pw:browser <ws disconnecting> ws://127.0.0.1:40797/7774371c42729d639fb6d3e28110c6b9
23:48:23 2022-03-23T18:18:23.096Z pw:browser [pid=344] finished temporary directories cleanup
23:48:23 FAIL browser: chromium src/test/electron/app.spec.js
23:48:23   ??? Check app launch, with version
23:48:23 
23:48:23     electron.launch: Process failed to launch!
23:48:23 
23:48:23        7 |   // const procEnv = process.env;
23:48:23        8 |   // procEnv.APP_DATA_PATH = `/tmp/${_deviceId}/`;
23:48:23     >  9 |   electronApp = await electron.launch({
23:48:23          |                                ^
23:48:23       10 |     args: ['--no-sandbox', '--enable-logging', '.'],
23:48:23       11 |   });
23:48:23       12 | });
23:48:23 
23:48:23       at src/test/electron/app.spec.js:9:32`

**Comment by adebayor123** [comment]
+1, similar issue: https://github.com/microsoft/playwright/issues/14078

**Comment by mxschmitt** [comment]
I tried to reproduce it but it was working fine for me. Closing as part of the triage process since it seemed stale and fixed. Please create a new issue with a detailed reproducible or feature request if you still face issues.

Thanks!
