### ISSUE TITLE
[Question]: how to use function CreateElement

### ISSUE THREAD

**Issue by gogenus123** [microsoft/playwright-python#1151]
### Your question

hi, i am beginner in python.
pls help me how it work

```
with sync_playwright() as p:
    response = requests.request("GET", url, headers=headers, data=payload).json()
    port = ((response['automation'])['port'])
    wsEndpoint = ((response['automation'])['wsEndpoint'])
    token = ("token")
    browser = p.chromium.connect_over_cdp('ws://127.0.0.1:' + str(port) + wsEndpoint, )
    context = browser.contexts[0]
    page = context.new_page()
    page.goto('https://www.google.com/')
    time.sleep(3)
    frame=page.main_frame
    time.sleep(0.05)
    el="iframe"
    abc=page.evaluate("document.createElement ('iframe')")
    print(abc)
    print(type(abc))
```
    
    
and i have answer
```
None
<class 'NoneType'>
```

**Comment by mxschmitt** [comment]
hi, don't use time.sleep see [here](https://playwright.dev/python/docs/intro#timesleep-leads-to-outdated-state).

What are you trying to achieve? You need to pass valid JavaScript into evaluate, currently you use the wrong type of brackets in the arguments and it can't destructure them.

**Comment by gogenus123** [comment]
> 

i dele

> hi, don't use time.sleep see [here](https://playwright.dev/python/docs/intro#timesleep-leads-to-outdated-state).
> 
> What are you trying to achieve? You need to pass valid JavaScript into evaluate, currently you use the wrong type of brackets in the arguments and it can't destructure them.

hi, thx, i delete all time functions and update my answer

**Comment by gogenus123** [comment]
hello, I found a temporary solution - running a js file, however, I think there is another way, can I somehow run the js code from several lines?

**Comment by mxschmitt** [comment]
you can create multi line string variables like this:

```python
foo = """Creating Python Comments. Python provides a single option to create a comment, using the pound sign, sometimes called the hash symbol
Python Multiline Comments with Consecutive Single-Line Comments
Python Multiline Comments with Multiline Strings
"""
```
