### ISSUE TITLE
[BUG] AttributeError: 'AsyncEventInfo' object has no attribute 'json'

### ISSUE THREAD

**Issue by ZenMaxe** [microsoft/playwright-python#1161]
**Context:**
- Playwright Version: Latest
- Operating System: Windows
- Python version: 3.8.6 
- Browser: Chromium
- Extra: 

```
async def get_offers(self):
        async with async_playwright() as playwright:
            chromium = playwright.chromium
            browser = await chromium.launch(executable_path=f"{self.file}/chrome-win/chrome.exe",headless=True)
            context = await browser.new_context()
            page = await browser.new_page()
            async with page.expect_response(lambda response:  'www.example.com' in response.url ) as res_info: #and 'Example' in response.json()['data']
                await page.goto("https://Example/home")
            a = await res_info.json()
```
Output :
```
a = await res_info.json()
AttributeError: 'AsyncEventInfo' object has no attribute 'json'
```

and when i use this :
`async with page.expect_response(lambda response:  'www.example.com' in response.url and 'Example' in response.json()['data'] ) as res_info: `

i get Error that said Coruntine doesn't have attribute json

Why i Get This Error?

**Comment by mxschmitt** [comment]
You need to await the value first like this:

```python
async with page.expect_response(lambda response:  'www.example.com' in response.url ) as res_info: #and 'Example' in response.json()['data']
    await page.goto("https://Example/home")
response = await response_info.value

a = await response.json()
```

**Comment by ZenMaxe** [comment]
> You need to await the value first like this:
> 
> ```python
> async with page.expect_response(lambda response:  'www.example.com' in response.url ) as res_info: #and 'Example' in response.json()['data']
>     await page.goto("https://Example/home")
> response = await response_info.value
> 
> a = await response.json()
> ```

Thanks
You Saved My Life

**Comment by ZenMaxe** [comment]
> You need to await the value first like this:
> 
> ```python
> async with page.expect_response(lambda response:  'www.example.com' in response.url ) as res_info: #and 'Example' in response.json()['data']
>     await page.goto("https://Example/home")
> response = await response_info.value
> 
> a = await response.json()
> ```

can you give me some hint for this:
```
async with page.expect_response(lambda response: 'www.example.com' in response.url and 'Example' in response.json()['data'] ) as res_info:
```
i get this error :
```
TypeError: 'coroutine' object is not subscriptable
```

**Comment by mxschmitt** [comment]
`response.json()` this is a coroutine, you need to await it.

**Comment by ZenMaxe** [comment]
i need use 'example' in response.json() in expect_response method (async)

**Comment by mxschmitt** [comment]
What are you trying to do?

**Comment by ZenMaxe** [comment]
> What are you trying to do?

ommm

scrape gaming.amazon.com with django (playwright based)

in jupyter , celery and cpanel playwright need to be async


i want say if program find "s" data on response.data.json() stop load

like expect_response

**Comment by mxschmitt** [comment]
Playwright is focused on e2e testing, so I’m closing this ticket for now.
