### ISSUE TITLE
Continuing the problem in a new issue

### ISSUE THREAD

**Issue by ThomasTrovon** [microsoft/playwright-python#1162]
You don't need to determine the browser paths yourself, we do this already for you and it's called channels: https://playwright.dev/python/docs/browsers#google-chrome--microsoft-edge

Also the command is not working because environment prefixing works only in Linux. In your case you need the PowerShell or batch approach. See here for a how to guide: https://playwright.dev/python/docs/intro#pyinstaller

Last but not least regarding the size, it's can't be less than 30-40mb, because the Playwright driver is that big, which can't be left out. For further issues please file a new issue.

_Originally posted by @mxschmitt in https://github.com/microsoft/playwright-python/issues/342#issuecomment-1039654821_

Brother.

About me trying to point the binaries directory on the computer, that's exactly why the following code didn't work with pyinstaller

![image](https://user-images.githubusercontent.com/10778234/153961982-5d1fceba-23a9-42e3-97b9-cae6623b8f00.png)

About page tutorial https://playwright.dev/python/docs/intro#pyinstaller I tried with PowerShell the following commands:

    $env:PLAYWRIGHT_BROWSERS_PATH="0"
    playwright install chromium
    pyinstaller -F main.py

And got the same errors after compiling with PyInstaller.

![image](https://user-images.githubusercontent.com/10778234/153962196-d2add3b9-ec04-421b-8784-fdc8afa928fc.png)

![image](https://user-images.githubusercontent.com/10778234/153962237-bf6d3b22-6b44-4648-b066-3cc9689bf16b.png)

And about the file size, if it was up to 40 MB, it would be fine. The problem is that it was 137 MB

**Comment by ThomasTrovon** [comment]
I believe I have found a solution for you..

I had pyee updated to its latest version 9.0.4. Amazingly, inside PyCharm it works. But when compiling with PyInstaller, version incompatibility does not allow correct compilation. So I simply downgraded pyee to version 8.1.0, and then compiling with PyInstaller started working.

I believe that many of the people who are having problems compiling with PyInstaller are having problems for this reason. Therefore, I believe it is interesting to inform in the documentation (https://playwright.dev/python/docs/intro#pyinstaller) the specific version that pyee should be in to avoid compilation problems.

**Comment by mxschmitt** [comment]
We pin pyee to 8.1.0 so we should be good. Are there any other open issues? It' expected that the file size of the bundle is not small. But in your case you could as I said just use the driver and use the channels. So don't do: `playwright install chromium` which would put the browser inside the pyinstaller bundle.

**Comment by ThomasTrovon** [comment]
> We pin pyee to 8.1.0 so we should be good. Are there any other open issues? It's expected that the file size of the bundle is not small. But in your case you could as I said just use the driver and use the channels. So it would be around ~40MB. So don't do: `playwright install chromium` which would put the browser inside the pyinstaller bundle.

In what link do you pin pyee 8.1.0? I don't see here (https://playwright.dev/python/docs/intro#pyinstaller) in this page. Maybe it's on another page, but my suggestion is that it should be posted on this one, which talks about PyInstaller, and "Known Issues". But obviously the choice is yours. I just made a suggestion. 

About the size around ~40mb, I understand what you are saying, but I don't understand how to do that. Maybe it's because I'm a noob. I will need more guidance. 

I'll make a clean project, so if you want to help me, I'll tell you step by step what I did, and you tell me where I went wrong.

I made a new PyCharm project, with a new clena venv and put the following code:

![image](https://user-images.githubusercontent.com/10778234/154273117-18f966fa-d03a-4036-bfa9-fc6c45fd04ad.png)

So, I install playwright:

![image](https://user-images.githubusercontent.com/10778234/154273344-9139e0a6-ff41-40c6-bd04-9a8deb60ba4f.png)

My english is not so good, but, I think that you say to me "don't execute the `playwright install chromium` command", am I right?

If I try to run the program, without this command, I get the following error:

![image](https://user-images.githubusercontent.com/10778234/154276844-669f3ab9-b7e5-4533-828f-112039a76ae9.png)

Where am I going wrong? What am I not understanding? If I try to compile this way with pyinstaller, without running the command  `playwright install chromium` , the program doesn't open.

![image](https://user-images.githubusercontent.com/10778234/154278092-b2f242f8-e9a7-4238-bf55-f1ead7b23f17.png)
![image](https://user-images.githubusercontent.com/10778234/154278174-a23e7c86-d459-40e8-90d0-ec6909f9c9f6.png)

If I execute `playwright install chromium`, the code pass to work. But when I make `pyinstaller -F main.py` the file becomes ~40MB, but does not open:

![image](https://user-images.githubusercontent.com/10778234/154279231-581ec97f-64b5-4b1b-9516-05e7ccb72dca.png)

![image](https://user-images.githubusercontent.com/10778234/154279309-847d3729-221a-4ca4-9983-e9e405a66a43.png)

Above the print of the ~40MB file.

So, only when I make:

$env:PLAYWRIGHT_BROWSERS_PATH="0"
playwright install chromium

![image](https://user-images.githubusercontent.com/10778234/154279594-05f4c1b9-3571-4420-81a2-07f45c89da42.png)

And `pyinstaller -F main.py` again:

![image](https://user-images.githubusercontent.com/10778234/154280292-cd2cd7b0-7246-4c0d-a1a6-2538db1eb9b0.png)

The program works. But, the file size go to ~142MB. So, I can make a functional executable, but not ~40MB. Only ~142MB.

Where am I going wrong? Can you guide me please?

**Comment by mxschmitt** [comment]
> n what link do you pin pyee 8.1.0?

See here: https://github.com/microsoft/playwright-python/blob/main/setup.py#L213

(gets used when you do `pip install -e .`.)

> My english is not so good, but, I think that you say to me "don't execute the playwright install chromium command", am I right?

Exactly, but this means you need to modify your `chromium.launch` to: `chromium.launch(channel="chrome")`.

See here: https://playwright.dev/docs/browsers#google-chrome--microsoft-edge

So TL;DR: if you do `channel="chrome"` and your host/customer's computer has Chrome installed, you should be good and have only a 35 MB binary.

**Comment by ThomasTrovon** [comment]
> > n what link do you pin pyee 8.1.0?
> 
> See here: https://github.com/microsoft/playwright-python/blob/main/setup.py#L213
> 
> (gets used when you do `pip install -e .`.)

Yes, But some people update their packages from time to time. I'm one of then. So, when I was update my package, I got this problem. My suggestion to put this advise there is to alert that type of person to do not do that, do not update pyee, understand my point? Principally if the person use `pip install pip-review` like me.. So now, after one `pip-review --auto` I need to make one `pip install pyee==8.1.0`. This is my point.

> > My english is not so good, but, I think that you say to me "don't execute the playwright install chromium command", am I right?
> 
> Exactly, but this means you need to modify your `chromium.launch` to: `chromium.launch(channel="chrome")`.
> 
> See here: https://playwright.dev/docs/browsers#google-chrome--microsoft-edge
> 
> So TL;DR: if you do `channel="chrome"` and your host/customer's computer has Chrome installed, you should be good and have only a 35 MB binary.

WWOOOOOOWWWWW.. What kind of Witchcraft was this? Works! hahaha
One doubt. I can use Browser redundancy? For example, if the person doesn't have microsoft edge, they can use chrome.

**Comment by mxschmitt** [comment]
> Yes, But some people update their packages from time to time

Playwright is a dependency, usually people don't have pyee as a dependency or updater their peer dependency.

You can't, you need to know beforehand which browser the user has, usually msedge is always pre-installed on Windows.
