### ISSUE TITLE
[BUG] When launching pythonw.exe, launches empty CMD window

### ISSUE THREAD

**Issue by aidvai-sp** [microsoft/playwright-python#1168]
**Context:**
- Playwright Version: 1.18.1
- Operating System: Windows
- Python version: 3.10
- Browser: All
- Extra: used in Flask webapp. Application is launched using batch file. It launches virtual env, enters it and launches my webserver. The webserver itself then launches playwright when it's needed.

**Code Snippet**

I launch browser with this snippet:
```
    def _start_browser(self):
        self._browser = sync_playwright().start()
        self._browser_instance = self._browser.chromium.launch(channel="msedge", headless=False)
        # self._browser_instance = self._browser.firefox.launch(headless=True)
        self._page = self._browser_instance.new_page()
```
If launched from VSCode directly, it doesn't create any CMD windows, even when in headless mode. But if it's launched by calling pythonw.exe ./file_name.py, for every created browser, it creates new CMD window and if you close it, playwright crashes (reports closed page I think). The playwright launches this cmd: venv\Lib\site-packages\playwright\driver\playwright.cmd

**Comment by mxschmitt** [comment]
We use this inside our code:

```py
        if sys.platform == "win32" and sys.stdout is None:
            creationflags = subprocess.CREATE_NO_WINDOW
```
which was introduced in #729 

Could you try to print your `sys.stdout` to see if it's None or not? Maybe we can remove the `sys.stdout is None` check entirely.

**Comment by aidvai-sp** [comment]
Will try out and let you know how it goes.

**Comment by aidvai-sp** [comment]
It worked, thank you a lot for you help

**Comment by kcvinker** [comment]
> We use this inside our code:
> 
> ```python
>         if sys.platform == "win32" and sys.stdout is None:
>             creationflags = subprocess.CREATE_NO_WINDOW
> ```
> 
`subprocess.CREATE_NO_WINDOW` solved my problem. Now, there is no cmd window is poping up. Thanks.
