### ISSUE TITLE
[BUG] After Update to 1.19, not all Firefox dependencies are installed

### ISSUE THREAD

**Issue by MrJohz** [microsoft/playwright-python#1169]
**Context:**
- Playwright Version: 1.19
- Operating System: Linux/Ubuntu
- Python version: 3.7
- Browser: Firefox
- Extra: Duplicate of microsoft/playwright#12075

**Describe the bug**

I believe it's the same problem as in the core playwright repo (linked above) - installing the dependencies for Firefox doesn't install `libxtst6`, which is now necessary.

I'm not sure if something needs to be fixed here as well, or if there just needs to be a new release which will include that bugfix, but it would be useful to have this fix soon, because currently our pipelines aren't working.

Thanks!

**Comment by mxschmitt** [comment]
Yeah we are planning to release the fix in 1.19.1 of Python today or tomorrow.

**Comment by mxschmitt** [comment]
Should be fixed in 1.19.1 - got published a few seconds ago.
