### ISSUE TITLE
[Question] How to turn off log errors generated by interception

### ISSUE THREAD

**Issue by jw-star** [microsoft/playwright-python#1185]
```
async def no_static(route, req):
    if req.resource_type in {"image", "media", "font"}:
        try:
            await route.fulfill(status=404, content_type="text/plain", body="not found!")
        except:
            pass
    else:
        await  route.continue_()
```

```
future: <Task finished name='Task-320' coro=<Channel.send() done, defined at C:\Users\jiawei\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py:38> exception=Error('Route is already handled!')>
Traceback (most recent call last):
  File "C:\Users\jiawei\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "C:\Users\jiawei\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Route is already handled!
```

**Comment by mxschmitt** [comment]
Could you provide us a full example of your code? I tried the following which was working fine for me:

```py
import asyncio
from playwright.async_api import async_playwright

async def no_static(route, req):
    if req.resource_type in {"image", "media", "font"}:
        try:
            await route.fulfill(status=404, content_type="text/plain", body="not found!")
        except:
            pass
    else:
        await  route.continue_()

async def main():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=False)
        page = await browser.new_page()
        await page.route("**/*", no_static)
        await page.goto('http://microsoft.com/')
        await page.screenshot(path=f'example.png')
        await browser.close()

asyncio.run(main())
```

Make sure that you only call a single time fulfill/continue/abort. Otherwise "Route is already handled! gets thrown.

**Comment by caramdache** [comment]
Hm... I just discovered that I suddenly get myriads of errors like the following. Nothing has changed in my code though. The only change is that I upgraded recently to Playwright 1.20.1.

```python
2022-04-26 10:12:17,907 ERROR Task exception was never retrieved
future: <Task finished name='Task-2788' coro=<Channel.send() done, defined at /var/www/django/python3.9/lib/python3.9
/site-packages/playwright/_impl/_connection.py:38> exception=Error('Route is already handled!')>
Traceback (most recent call last):
  File "/var/www/django/python3.9/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/var/www/django/python3.9/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 63, in inner_sen
d
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Route is already handled!
```

**Comment by BruceLee569** [comment]
> Could you provide us a full example of your code? I tried the following which was working fine for me:
> 
> ```python
> import asyncio
> from playwright.async_api import async_playwright
> 
> async def no_static(route, req):
>     if req.resource_type in {"image", "media", "font"}:
>         try:
>             await route.fulfill(status=404, content_type="text/plain", body="not found!")
>         except:
>             pass
>     else:
>         await  route.continue_()
> 
> async def main():
>     async with async_playwright() as p:
>         browser = await p.chromium.launch(headless=False)
>         page = await browser.new_page()
>         await page.route("**/*", no_static)
>         await page.goto('http://microsoft.com/')
>         await page.screenshot(path=f'example.png')
>         await browser.close()
> 
> asyncio.run(main())
> ```
> 
> Make sure that you only call a single time fulfill/continue/abort. Otherwise "Route is already handled! gets thrown.

I also encountered this problem, calling function `context.route()` will throw this exception !

```Python
import asyncio
from playwright.async_api import async_playwright


async def no_static(route, req):
    if req.resource_type in {"image", "media", "font"}:
        try:
            await route.fulfill(status=404, content_type="text/plain", body="not found!")
        except:
            pass
    else:
        await  route.continue_()


excluded_resource_types = ["stylesheet", "script", "image", "font"]


async def main():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=False)
        context = await browser.new_context()
        await context.route('**/*', no_static)
        page = await context.new_page()
        await page.goto('http://microsoft.com/')
        await browser.close()


asyncio.run(main())

```

**Comment by saisua** [comment]
Well, I've had this problem too, because I worry applying page.on(event) every single time I open a website might slow down things, even with Cython, so my solution was to check the source code.
The quick fix I did was to change only one line:

In playwright / _impl / _connection
&nbsp;In line 63 : Channel.inner_send<br/>
`result = next(iter(done)).result()`
to
`future = next(iter(done))`
`if(future.exception() is not None):`
`____return None`
`result = future.result()`

**Comment by mxschmitt** [comment]
In the route handler its not supported to pass coroutines, the functions need to be sync. When modifying your repro @jw-star and removing the async and await, then it works as expected.

**Comment by BruceLee569** [comment]
> In the route handler its not supported to pass coroutines, the functions need to be sync. When modifying your repro @jw-star and removing the async and await, then it works as expected.

```
from playwright.sync_api import sync_playwright


def no_static(route, req):
    if req.resource_type in {"image", "media", "font"}:
        try:
            route.fulfill(status=404, content_type="text/plain", body="not found!")
        except:
            pass
    else:
        route.continue_()


def main():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        context = browser.new_context()
        context.route('**/*', no_static)
        page = context.new_page()
        page.goto('http://microsoft.com/')
        browser.close()


main()
```

I've tried synchronous code above before my last comment, and the error reporting is the same as asynchronous.

**Comment by chujian521** [comment]
I have this problem too, this error occurs when using context.route()

**Comment by chujian521** [comment]
Modify this file : ~Lib\site-packages\playwright\driver\package\lib\server\network.js
Line 250, class Route
Determine if it has been handled. If not, start Handling.
```javascript
if(!this._handled){
      this._startHandling();
}
```
I don't know if this is the right thing to do, but it does not report any error!

**Comment by BruceLee569** [comment]
@mxschmitt Hello, how about re-open this issue?

**Comment by rwoll** [comment]
v1.23 introduced async route handlers. There is one known, pending issue regarding errant logs, so please follow: https://github.com/microsoft/playwright-python/issues/1402
