### ISSUE TITLE
playwright._impl._api_types.Error: connect ETIMEDOUT[Question]: 

### ISSUE THREAD

**Issue by AmericanY** [microsoft/playwright-python#1187]
### Your question

I Got the following error:

```
playwright._impl._api_types.Error: connect ETIMEDOUT
```

I believe that i need to Except it from `from playwright._impl._api_types import Error` 

Or i should Except it from `from playwright._impl._api_types import TimeoutError`

>This error happened under `context.get`

why we couldn't use `from playwright.async_api import TimeoutError` ?

I reviewed the class but still have confusion! isn't that just a `Timeout` error ?

```python
class Error(Exception):
    def __init__(self, message: str) -> None:
        self.message = message
        self.name: Optional[str] = None
        self.stack: Optional[str] = None
        super().__init__(message)


class TimeoutError(Error):
    pass

```

**Comment by AmericanY** [comment]
Hmmm, just noticed now that i need to `Except` both of them ! wired behavior!

**Comment by mxschmitt** [comment]
This looks stale, please file a new issue with a repro.
