### ISSUE TITLE
[BUG] Pytest's html reporter doesn't take/show screenshot in the test reports

### ISSUE THREAD

**Issue by nileshpandey3** [microsoft/playwright-python#1198]
**Context:**
- Playwright Version: [0.2.3]
- Operating System: [Mac]
- Python version: [3.9]
- Browser: [Chromium]
- Extra: [pytest version == 7.0.1]

**Code Snippet**

    def test_pw():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        page = browser.new_page()
        page.goto("http://www.html")
        browser.close()
```
```
- Run command : 
- `pytest --html report_pw1.html`
```
Issue:
- Pytest's html reporter doesn't take/show screenshot in the test reports for pytest-playwright based tests
- I tried to run my first playwright test using pytest-playwright and the test runs fine but when I tried to use the pytest html reporter to show me the report with a screenshot for a failed test it doesn't work
- Can anyone please suggest what am i missing here? I read the [docs](https://pytest-html.readthedocs.io/en/latest/) for pytest html and it says that a screenshot should automatically be included by default for failed tests but its not happening so
```

![Screen Shot 2022-03-09 at 6 24 24 PM](https://user-images.githubusercontent.com/15132522/157577179-bf182fcc-500b-4eb0-8e90-67a0003a010f.png)

**Comment by mxschmitt** [comment]
`playwright-pytest` is not integrated with the pytest html report. You can enable screenshots or on failure via a CLI flag, see [here](https://playwright.dev/python/docs/test-runners#cli-arguments). These screenshots get then saved to the `test-results` directory.

**Comment by arizzubair** [comment]
@nileshpandey3 ,  You can use pytest_html hook to add a screenshot to the test report.
See this answer: https://stackoverflow.com/questions/70761764/pytest-html-not-displaying-image
