### ISSUE TITLE
[BUG] Information of launch option "IgnoreDefaultArgs" is wrong

### ISSUE THREAD

**Issue by TBatist** [microsoft/playwright-python#1199]
Hello,

I just found a minor bug. The information of the launch option `IgnoreDefaultArgs` is 

`If true, Playwright does not pass its own configurations args and only uses the ones from args. Dangerous option; use with care.`

This is the same information as the launch option `IgnoreAllDefaultArgs`. Also, the type of `IgnoreDefaultArgs` is `IEnumerable<string>?` which does not match with the information, which state you have to  provide a `boolean`.

My suggestion is to change the information of `IgnoreDefaultArgs` with something like "Default arguments that will be ignored" or something like that.

**Comment by rwoll** [comment]
This is a documentation error. In .NET the boolean is not support, just the list of strings.
