### ISSUE TITLE
[Question]: invalid Docker documentation / how to pull Python Docker image

### ISSUE THREAD

**Issue by louis030195** [microsoft/playwright-python#1204]
### Your question

Hi, on `https://playwright.dev/python/docs/docker`, you say that there is a Docker image to use Playwright with Python:

`docker pull mcr.microsoft.com/playwright/python:focal`

>Error response from daemon: manifest for mcr.microsoft.com/playwright/python:focal not found: manifest unknown: manifest tagged by "focal" is not found

Please, could you indicate where to pull the image or any documentation to use Playwright in Docker with Python?

Thanks a lot

**Comment by mxschmitt** [comment]
Once we release Playwright for Python v1.20 (in the next few hours) its then getting published. Sorry for the inconvenience !

**Comment by mxschmitt** [comment]
Should be fixed now!
