### ISSUE TITLE
[Question]: Is there a way to run a playwright instance in a background task?

### ISSUE THREAD

**Issue by elkd** [microsoft/playwright-python#1207]
### Your question

Hi, I am launching an instance of sync playwright as an object attribute and I want to use the object in the background task but I'm failing. The code is something like this:

`       self.playwright = sync_playwright().start()
`
How can I run playwright of this instance in a separate task? By task, I mean either another process or another thread?

THREADING: If I pass the object to another thread, I get a cute greenlet exception, can't switch to another thread (I read, sync PW isn't thread-safe)

MULTIPROCESSING; If I pass the object to another process, I'm greeted by an Exception that playwright can't find any running event loop. If I acquire the running event_loop in my main process and pass it to another process, I can't find a way to run it in another process.

I am aware of sthing like xdist's pytest  -n should launch multiple new PW instances but I want only 1 to be reused in another process. How can I use the same sync PW instance in another process?

**Comment by mxschmitt** [comment]
You need to start a new Playwright instance for each thread. Passing it to different threads does not work.

See these issues which contain various examples:
- https://github.com/microsoft/playwright-python/issues/623
- https://github.com/microsoft/playwright-python/issues/886#issuecomment-911469049

If you are using pytest, we recommend using e.g. xdist, this should also work out of the box and create a new playwright instance for each worker. Reusing is not possible.
