### ISSUE TITLE
[Question]: expect_response pattern

### ISSUE THREAD

**Issue by agent666** [microsoft/playwright-python#1214]
### Your question

Hi, I can't figure out how I can use patterns in playwright expect_response

```
with page.expect_response('**image/**') as test:
    page.goto('https://thesite.com/page/')
    page.is_visible('.images')
```
The abow code works but i don't allways want the first image.
How can i skip the firt image if its is an .png?

**Comment by mxschmitt** [comment]
This pattern matching is based on glob see here: https://en.wikipedia.org/wiki/Glob_(programming)

For PNG images its e.g. `**image/**/*.png`
