### ISSUE TITLE
[BUG]Force update

### ISSUE THREAD

**Issue by xiaolushuo** [microsoft/playwright-python#1221]
**Context:**

- Operating System:  Mac
- Python version: 3.7.3
- Browser: Chromium, Firefox, WebKit

**Code Snippet**
command.<anonymous>: Executable doesn't exist at /Users/*****/Library/Caches/ms-playwright/chromium-978106/chrome-mac/Chromium.app/Contents/MacOS/Chromium
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝
    at Command.listener [as _actionHandler] (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/playwright/driver/package/node_modules/commander/lib/command.js:488:17) {
  name: 'Error'
}

** Describe the bug **

My local version is /Users/*****/Library/Caches/ms-playwright/chromium-939194，But force me to update, otherwise I will report an error，As a result, the original script cannot be used.

How can this be avoided ？

**Comment by mxschmitt** [comment]
Which Playwright version are you using? do `python -m playwright install` and then it will work.

**Comment by xiaolushuo** [comment]
Playwright version Version 1.20.0, `python -m playwright install` this command is ok, Yes, but this happens every once in a while, How to avoid repeated installation？

**Comment by mxschmitt** [comment]
If you pin your Python dependency to 1.20.0 then you only have to install browsers once. If you don't pin and always install e.g. playwright>=1.20 it will occur over and over again.

**Comment by xiaolushuo** [comment]
emmmm, How to fix python dependency version, I never actively update it, it's wired

**Comment by mxschmitt** [comment]
This is most likely not an issue with Playwright and more an issue with the venv / global path mapping.

Closing by that.
