### ISSUE TITLE
[Question]: How to type inside a modal form?

### ISSUE THREAD

**Issue by pauloventurab** [microsoft/playwright-python#1223]
### Your question

Hello,

I'm trying to type a form that is inside a modal, but when I put the code

page.type('input#user_email', Config.USERNAME)
page.type('input#user_email', Config.PASSWORD)

I also tried

page.type('input[name="user[email]"]', Config.USERNAME)
page.type('input[name="user[password]"]', Config.PASSWORD)

I get no responses....

![image](https://user-images.githubusercontent.com/49717827/159685769-ec843238-a496-453b-be96-833dbe9b3a5e.png)

![image](https://user-images.githubusercontent.com/49717827/159686087-cee64ab3-75f7-4e84-9064-398396fb3330.png)

**Comment by mxschmitt** [comment]
Try using Locators instead, maybe there are multiple elements with the same selector on the page: https://playwright.dev/docs/next/locators#locator-vs-elementhandle

Also I'd recommend to set the `DEBUG=pw:api` env or record a trace to find out why its not working: https://playwright.dev/python/docs/next/trace-viewer#recording-a-trace

**Comment by pauloventurab** [comment]
With locator I get the error : TypeError: Object of type Locator is not JSON serializable

Code:

username_input = page.locator('input#user_email')
page.type(username_input, Config.USERNAME)

password_input = page.locator('input#user_password"]')
page.type(password_input, Config.PASSWORD)

Record trace:

If I put the tracer before the below code I have a trace.zip file just with the page.goto .

If I put after the code I get the error.

**Comment by mxschmitt** [comment]
Locators work differently, it should be:

```
username_input = page.locator('input#user_email')
username_input.type(Config.USERNAME)

password_input = page.locator('input#user_password"]')
password_input.type(Config.PASSWORD)
```

Trace should be enabled before and stopped after your error occurs. Then you can find out where the click was actually happening. Alternatively you can just set the `PWDEBUG=1` env var and you can step through your code.

**Comment by pauloventurab** [comment]
Not working for me, the same as before "waiting for selector 'input#user_email'".

Maybe you can try by yourself: https://support-shop.astoreprocurement.com/access/unauthenticated

**Comment by mxschmitt** [comment]
Your elements are actually in an iframe, so the following should work:

```ts
  await page.goto('https://support-shop.astoreprocurement.com/access/unauthenticated');
  const iframe = page.frameLocator('iframe');
  await iframe.locator('input[name="user\\[email\\]"]').fill('foo@bar.com');
  await iframe.locator('input[name="user\\[password\\]"]').fill('kek@star.com');
```

**Comment by pauloventurab** [comment]
Thank you so much

Pyhon:

# Fill the Login Forms
    username = page.frame_locator('iframe').locator('#user_email')
    username.fill(Config.USERNAME)
    
    password = page.frame_locator('iframe').locator('#user_password')
    password.fill(Config.PASSWORD)
