### ISSUE TITLE
[Question]: How to use “record_video_dir” in "connect_over_cdp"?

### ISSUE THREAD

**Issue by 1138559250** [microsoft/playwright-python#1225]
### Your question

- Context:
- Operating System: windows
- Python version: 3.7.3
- Browser: Chromium, Firefox, WebKit

I want to get a playwright instance with the "connect_over_cdp" method so that I don't have to worry about some browser detection issues.
The open browser already has a "BrowserContext", and I can't set the "BrowserContext" to something like "proxy" or " record_video_dir", but I want to save the record_video, how can I do that?
Looking forward to your reply, thanks!

**Comment by mxschmitt** [comment]
you can connect over CDP and create a new context. In the context options you can pass the video dir: https://playwright.dev/python/docs/api/class-browser#browser-new-context

Recording on an existing context is not supported.

**Comment by jiliu88** [comment]
You can set chrome to open like this. The proxy type can only be set to http and https
cd C:\Program Files\Google\Chrome\Application\&chrome.exe --user-data-dir=C:\Program Files\Google\Chrome\Application\new_user_data" --remote-debugging-port={} --proxy-server=127.0.0.1:808

**Comment by mxschmitt** [comment]
Closing since the issue seems answered.
