### ISSUE TITLE
[Question]: How to automate local msedge browser in Python

### ISSUE THREAD

**Issue by sydusername** [microsoft/playwright-python#1227]
### Your question

In the document, I noticed this line of code--<browser = playwright.chromium.launch(channel="msedge")>--, but he is running in the headless mode, can't judge whether it is useful, local browser.
When you join this--<browser = playwright.chromium.launch(channel="msedge",headless=False)>--, the local browser found is not used, how can I automate the local browser?

**Comment by mxschmitt** [comment]
This works for me! which OS/version are you using? Do you have Microsoft Edge installed?

```py
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch(channel="msedge", headless=False)
    page = browser.new_page()
    page.goto('http://whatsmyuseragent.org/')
    browser.close()
```

Where is your msedge installed?

**Comment by sydusername** [comment]
My version is 99.0.1150.52 (official version)(64-bit).
Executable file path:C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe.

**Comment by sydusername** [comment]
> This works for me! which OS/version are you using? Do you have Microsoft Edge installed?
> 
> ```python
> from playwright.sync_api import sync_playwright
> 
> with sync_playwright() as p:
>     browser = p.chromium.launch(channel="msedge", headless=False)
>     page = browser.new_page()
>     page.goto('http://whatsmyuseragent.org/')
>     browser.close()
> ```
> 
> Where is your msedge installed?

My version is 99.0.1150.52 (official version)(64-bit).
Executable file path:C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe.

**Comment by sydusername** [comment]
> This works for me! which OS/version are you using? Do you have Microsoft Edge installed?
> 
> ```python
> from playwright.sync_api import sync_playwright
> 
> with sync_playwright() as p:
>     browser = p.chromium.launch(channel="msedge", headless=False)
>     page = browser.new_page()
>     page.goto('http://whatsmyuseragent.org/')
>     browser.close()
> ```
> 
> Where is your msedge installed?

Thank you for your answer. I tried the code you said, it was able to start the MSEDGE browser, but it and Chromium is too like, I didn't pay attention.

**Comment by mxschmitt** [comment]
Closing since the issue seems answered. If there are further questions, please file a new issue.
