### ISSUE TITLE
[Question]: Can I share the browser cache between multiple runs?

### ISSUE THREAD

**Issue by simonw** [microsoft/playwright-python#1230]
### Your question

My [shot-scraper](https://datasette.io/tools/shot-scraper) CLI tool uses Playwright Python and lets me run things like this:

```
pip install shot-scraper
shot-scraper install # To install the Playwright browser
shot-scraper javascript https://simonwillison.net/2022/Mar/24/datasette-061/ "
async () => {
  const readability = await import('https://cdn.skypack.dev/@mozilla/readability');
  return (new readability.Readability(document)).parse();
}"
```
As described in https://til.simonwillison.net/shot-scraper/readability this will run the Mozilla [Readability.js](https://github.com/mozilla/readability) library against the page and return the result to standard output.

Problem is... every time I run the command, Playwright will fetch a new copy of that JavaScript library from the CDN.

I'd love to take advantage of the browser cache here, but as far as I can tell the browser cache is not persisted between multiple runs of my tool.

Is it possible to opt-in to persisting the browser cache between runs?

**Comment by simonw** [comment]
On writing this up, I realize that the cache may not help as much as I hoped - presumably for privacy reasons a copy of a JavaScript library loaded on one domain is no longer cached and reused for other domains.

So I guess a feature request I have is for a way to opt back out of that, so the browser cache for `cdn.skypack.dev` is once again shared across multiple other page hosting domains.

**Comment by rwoll** [comment]
Based on the details in this issue, it sounds like you're injecting the Readability.js library from a CDN. CDNs should be super quick, but if you want to optimize further, you can download this file out-of-band and save it to disk, and then serve it locally going forward; or download the file and inject it into the page. (context.add_init_script and/or request interception may be of interest to you).

**Comment by simonw** [comment]
Thanks, those are both great ideas. It looks like I could use `page.add_script_tag(...)` to load a script file from disk too, which might work for me here.

**Comment by rwoll** [comment]
Awesome! Closing per the above, but if you have follow up, please re-open or open a new issue.

**Comment by dgtlmoon** [comment]
I found this via google search - would love to know the answer, using the following didnt seem to help

Specifying `--user-data-dir=/tmp/profile` on connection along with 

```
    environment:
     - PREBOOT_CHROME=true
     - KEEP_ALIVE=true
```

Did not seem to help
