### ISSUE TITLE
[Question]: How can we schedule many Playwright python scripts ?

### ISSUE THREAD

**Issue by pauloventurab** [microsoft/playwright-python#1233]
### Your question

Hello everyone,

After create around 30 (and more than 100 if everything works fine), now we need to schedule it and I'm trying to search the best solution....

Ok, just to give you what we are doing to understand the full idea:

We use SSIS to do ETLs, and migrating to Azure in a couple of months, but to start this ETL's we recieve files from different peoples trough a website that insert the file in our Datalake.

What we are doing on Playwright is, stop ask people insert data manually, and doing the job for them, then we just need playwright to do the webscraping and insert the data on datalake, after it, SSIS do the ETL's.

But we have problems to install Python on Server (we can't run python scripts on job monitor).

So the question is:

How can I schedule this scripts 24/7, without let my pc online?

I tried use Airflow, but isn't working... ModuleNotFoundError: No module named 'playwright' (The image is working inside the container).
![image](https://user-images.githubusercontent.com/49717827/161343958-cc918cda-2138-40ad-b9da-45cbf3f8c69d.png)

Then, I tried to have it inside a notebook (not working, sync and async), not working as well...

Can someone help me to schedule this python scripts without error please?

**Comment by mxschmitt** [comment]
Since this is a very specific use-case and is not about a bug / feature for Playwright for Python, I'm closing it. I'd recommend to file an issue in the Airflow repository.

For using Playwright for Python we recommend our Docker image: https://playwright.dev/python/docs/docker

Installing the dependencies there and using Playwright will work.

**Comment by pauloventurab** [comment]
Sorry I don't think thisis a specific use-case, the question is **How can we schedule many Playwright python scripts ?**, How do you schedule many Playwright Python Scripts, not just using Airflow, but in others tools....

**Comment by mxschmitt** [comment]
It's not specific to Playwright, the question is more in general: how can you run scheduled Python scripts.

For that I don't have an answer, probably like scheduled serverless functions or Airflow? In the worst case you need to build something specific based on some queues and microservices.
