### ISSUE TITLE
[BUG] Async request interception stalls browser

### ISSUE THREAD

**Issue by piercefreeman** [microsoft/playwright-python#1235]
**Context:**
- Playwright Version: 1.20.1
- Operating System: Mac
- Python version: 3.10.2
- Browser: Chromium
- Extra: M1 & Intel, separate test environments

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```python
import pytest
from playwright.async_api import TimeoutError as PlaywrightTimeoutError, async_playwright

@pytest.mark.asyncio
async def test_browser():
    async with async_playwright() as p:
        optional_args = {}

        browser = await p.chromium.launch(headless=False)
        context = await browser.new_context(ignore_https_errors=True)
        page = await context.new_page()

        async def resolve_cache(route, request):
            headers = {
                **request.headers,
                "foo": "bar", # set "foo" header
                "origin": None # remove "origin" header
            }
            await route.continue_(headers=headers)
          
        # this stalls
        await page.route(
            "**/*",
            resolve_cache
        )

        # this works
        await context.route(
            "**/*",
            resolve_cache
        )

        await page.goto("http://www.daringfireball.net")
```

**Describe the bug**

A relatively simple request interception stalls program execution and never completes. Code will execute until it hits the `await page.route` block and then will stall. This occurs for both headless and headfull browsers.

However, if I instead change the route to affect the context (context.route) instead of the page, this works fine. Is this intended behavior? Ideally I should be able to intercept page network requests even when there's a limited context around it.

**Comment by mxschmitt** [comment]
Pytest by default does not show `Task exception was never retrieved` warnings. If you add the `-s` flag you should see the following error:

```
Task exception was never retrieved
future: <Task finished name='Task-6' coro=<Channel.send() done, defined at /Users/max/development/playwright-python/playwright/_impl/_connection.py:38> exception=Error('headers[4].value: expected string, got object')>
```

Removing headers is not supported by passing `None`. But you can just leave it out in the object, then it will work (aka. `del headers["origin"]`.

**Comment by piercefreeman** [comment]
Thanks for the tip @mxschmitt - [this example](https://playwright.dev/python/docs/api/class-route) in the docs threw me off. Looks to be working now!
