### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by PalaChen** [microsoft/playwright-python#1239]
### Your question

```
<div class="Button-module-main-3ayh Button-module-primary-3Pyh Button-module-btn-5iyh" data-enabled="true" data-auto="start-button" role="button" style="width: 120px; min-width: 0px;"><span></span>Start<span></span></div>
```
Button-module-main-xxxx
Button-module-primary-xxxx
Button-module-btn-xxxx
 i Can't locate via css，Because the css name part is random，i want to  use data-auto="start-button" to locate

how to write code ?

**Comment by mxschmitt** [comment]
you can do the following: `page.locator("[data-auto='start-button']").click()` which is a CSS attribute selector, see here: https://playwright.dev/docs/next/selectors#css-selector

**Comment by PalaChen** [comment]
thanks
