### ISSUE TITLE
[BUG] 'browser.new_context' parameter 'locale' accepts any meaningless string

### ISSUE THREAD

**Issue by AIGeneratedUsername** [microsoft/playwright-python#1243]
```python
async with async_playwright() as p:
      browser = await p.chromium.launch()
      context = await browser.new_context(locale="foO bAr Spam EGgs")  # <-- NO ERROR HERE
```

# Expected behavior 

Accept only adequate [Languages Codes](https://developers.google.com/admin-sdk/directory/v1/languages). Raise `ValueError` for any non-existing code.

---

Another problem is that nobody knows which strings Playwright accepts. 

- 'zh' ? 
- 'zh-CN' ?
- 'zh_CN' ?

Ideally, a `typing.Literal` must be defined with a list of accepted languages' codes.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.
