### ISSUE TITLE
[BUG] "Error: EPERM: operation not permitted" on installation.

### ISSUE THREAD

**Issue by brunoboaventura** [microsoft/playwright-python#1248]
**Context:**
- Playwright Version: 1.20
- Operating System: Windows
- Python version: 3.10.4
- Browser: All

**Describe the bug**

playwright install fails with the output:

playwright install
Downloading Playwright build of chromium v978106 - 103.8 Mb [====================] 100% 0.0s
Failed to install browsers
Error: Failed to download chromium v978106, caused by
Error: EPERM: operation not permitted, open 'C:\cecop\playwright_browsers\chromium-978106\chrome-win\chrome.exe'

**Comment by brunoboaventura** [comment]
I have permission to write into that folder.

**Comment by mxschmitt** [comment]
Seems like the process has no permissions to write into that folder. Why did you change the default location to a custom one?

**Comment by mxschmitt** [comment]
seems like then something is off with the user who is running the process. Maybe you have some special anti virus software running? This could cause such things as well.

**Comment by mxschmitt** [comment]
and updates @brunoboaventura?
