### ISSUE TITLE
'page.expect_download()' can not download some files by a file URL

### ISSUE THREAD

**Issue by AIGeneratedUsername** [microsoft/playwright-python#1264]
**Context:**
- Playwright Version: 1.20
- Operating System: Lubuntu 20.04
- Python version: 3.10
- Browser: Firefox

```python
import asyncio
from playwright.async_api import async_playwright

# This URL will work fine:
# random_sample_file_url_for_testing = "https://filesamples.com/samples/video/3gp/sample_1280x720.3gp"

# This URL will fail:
# random_sample_file_url_for_testing = "https://file-examples.com/storage/fea53c46ea62599c9983460/2017/10/file_example_JPG_2500kB.jpg"

# This URL will fail too:
# random_sample_file_url_for_testing = "https://file-examples.com/wp-content/uploads/2017/10/file_example_JPG_100kB.jpg"

parameters = {
    "accept_downloads": True,
}


async def main():
    async with async_playwright() as p:
        browser = await p.firefox.launch()
        context = await browser.new_context(**parameters)
        page = await context.new_page()

        async with page.expect_download() as download_info:
            print("Opening file URL...")
            await page.goto(random_sample_file_url_for_testing)
            download = await download_info.value
            # print(f"download_value: {download}")
            print(f"is done: {download_info.is_done()}")
            # waits for download to complete
            path = await download.path()
            print(f"path: {path}")
            await browser.close()


asyncio.run(main())
```

**Problem**

The code fails for https://file-examples.com/storage/fea53c46ea62599c9983460/2017/10/file_example_JPG_2500kB.jpg with the error:
```
playwright._impl._api_types.TimeoutError: Timeout 30000.0ms exceeded while waiting for event "download"
=========================== logs ===========================
waiting for event "download"
============================================================
```

But the code works for https://filesamples.com/samples/video/3gp/sample_1280x720.3gp

**Expected behaviour**

Playwright must be able to download any file. The same as a real web browser can.

---

Am I doing something wrong here? Maybe I overlooked another way to download a file by its URL?
Maybe I am wrong, but my guess is that some URLs trigger a 'download' event and some URLs does not. If this is true, then the problem is how to distinguish such URLs.

**Comment by rwoll** [comment]
If you run in headful, do you see a download triggered, or is the jpg just rendered as an image in the browser? If it's the latter, it's expected that there is not a download event, and you can can save it off from the response of the goto (https://playwright.dev/python/docs/api/class-page#page-goto-return) instead.

**Comment by AIGeneratedUsername** [comment]
> If you run in headful, do you see a download triggered, or is the jpg just rendered as an image in the browser? If it's the latter, it's expected that there is not a download event, and you can can save it off from the response of the goto (https://playwright.dev/python/docs/api/class-page#page-goto-return) instead.

Ok, then I will need to:
1. Try to wait for a download
2.  If a download does not start, then catch `playwright.async_api.TimeoutError` and download response as a regular page (not sure that this is correct).

Some code if someone will come here from the web search:
```python
async with page.expect_download() as download_info:
    response = await page.goto(url)
    try:
        download = await download_info.value
    except playwright.async_api.TimeoutError:
        # Save the file manually (maybe save response bytes, I do not understand now how exactly).
```

**Comment by rwoll** [comment]
@AIGeneratedUsername To clarify, if you're not trying to test for a download event, but you're just trying to unconditionally save off the response (whether it triggers a download or not), you can modify the example from https://playwright.dev/python/docs/api/class-apiresponse

```python
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    context = playwright.request.new_context()
    response = context.get("https://example.com/user/repos")
    # change the blow line to write body to a file
    assert response.body() == '{"status": "ok"}'
```

so you don't have to try timing out for a dowload.
