### ISSUE TITLE
Is it possible to create allure-reports on playwright python

### ISSUE THREAD

**Issue by bindumadhav100** [microsoft/playwright-python#1265]
### Your question

i used below line of code for python playwright and ran below command to create allure-reports

import allure

@allure.feature("Login")
def sync_playwright(page) :
    browser = page.webkit.launch()
    page = browser.new_page()
    page.goto("http://whatsmyuseragent.org/")
    page.screenshot(path="example.png")
    browser.close()

command ran for allure reports generation

pytest googlesearch.py --alluredir=allure --clean-alluredir

reports folder generated with empty folder please help me with this allure reports folder with reports generation

**Comment by mxschmitt** [comment]
Playwright for Python has no Allure integration. But you can use e.g. [allure-pytest](https://pypi.org/project/allure-pytest/) in combination with [pytest-playwright](https://playwright.dev/python/docs/test-runners).

Closing as per above, for Allure specific issues I recommend to file issues against this repo: https://github.com/allure-framework/allure-python
