### ISSUE TITLE
[BUG] `ValueError: list.remove(x): x not in list` randomly happens for random URLs when calling `page.goto()`

### ISSUE THREAD

**Issue by AIGeneratedUsername** [microsoft/playwright-python#1268]
# Versions
- Playwright Version: 1.20.1
- Operating System: Lubuntu 20.04
- Python version: 3.10
- Browser: Firefox

# DEBUG log

[playwright_valueerror.tar.gz](https://github.com/microsoft/playwright-python/files/8528331/playwright_valueerror.tar.gz)

# Code

To be honest, the code snippet is useless because the error happens randomly for random URLs when you request URLs one by one. 

```python
import asyncio

import playwright.async_api
from playwright.async_api import async_playwright

async def main():
    async with async_playwright() as p:
        browser = await p.firefox.launch()
        page = await browser.new_page()
        for url in urls:
                await page.goto(url)
        await browser.close()

asyncio.run(main())
```

# Possible solution

The most obvious workaround is to suppress the error, but this may be not correct because I do not know how do you handle frames further:
```python
# /playwright/_impl/_page.py


class Page(ChannelOwner):


    def _on_frame_detached(self, frame: Frame) -> None:
        with suppress(ValueError):  # A frame may be already removed even if a user did no interactions with a webpage.
            self._frames.remove(frame)
```

**Comment by mxschmitt** [comment]
can you share with us a url where it happens?

**Comment by mxschmitt** [comment]
Closing for now since it seems stale, please reopen if you have a concrete repro!

**Comment by JannisBush** [comment]
I also run into this issue.
I consistently get it while navigating to a large test page with many nested frames that send postMessages to the parent and the frames get removed after some time.

I try to generate a minimal reproducible example or see if I can share the full test page.
