### ISSUE TITLE
[BUG] Page.goto() not returning

### ISSUE THREAD

**Issue by OxNinja** [microsoft/playwright-python#1280]
**Context:**
- Playwright Version: `1.21.0`
- Operating System: Linux
- Python version: `3.10.4`
- Browser: Chrome
- Extra: USB Android device

**Code Snippet**

Need an USB device with USB debug enabled (connected with ADB)

Requires `ppadb playwright` and a running ADB server (`adb start-server`)

```python
import asyncio

from playwright.async_api import async_playwright
from ppadb.client import Client


# This function works
def forward(port):
    """Creates a port forwarding for one device"""
    client = Client()
    device = client.devices()[0]
    device.forward(local=f"tcp:{port}", remote="localabstract:chrome_devtools_remote")


# This function blocks on the goto()
async def run(port):
    """Connects to a USB device over CDP (via the port forwarding) and visit an URL"""
    async with async_playwright() as pw:
        browser = await pw.chromium.connect_over_cdp(f"http://localhost:{port}")

    # Infinite wait
    await browser.contexts[0].pages[0].goto("https://google.com")


if __name__ == '__main__':
    forward_port = 9001

    # Create port forwarding
    forward(forward_port)

    # Run the async function
    asyncio.run(run(forward_port))
```

**Describe the bug**

The line `await browser.contexts[0].pages[0].goto("https://google.com")` never returns and the script is stuck in an infinite loop.

My guess is that the`goto` method is not compatible with remote CDP:
* The `browser` object is defined with no error
* I can open a new page/tab with `await browser.contexts[0].new_page()`
* The `browser.contexts[0].pages[0]` object is a `Page` with all the corresponding attributes (including the method `goto`)

**Comment by mxschmitt** [comment]
Connecting to an android device is not supported out of the box, I'd recommend to wait until https://github.com/microsoft/playwright-python/issues/1281 is implemented.
