### ISSUE TITLE
[Question]: Get the content of an HTML tag with a specific class (Python)

### ISSUE THREAD

**Issue by GTP95** [microsoft/playwright-python#1284]
### Your question

My question is similar to issue #438, but reading there didn't help me. As a test, I'm trying to get the user agent from http://whatsmyuseragent.org/ and store it in a variable. By looking at the page's source, you can see that it is stored inside the following tag:
```HTML
<p class="intro-text">The text I wish to get goes here</p>
```
To retrieve such a text, I tried some variations of the following:
```PYTHON
class MyTestCase(unittest.TestCase):
    def test_userAgent(self):
        with sync_playwright() as playwright:
            browser = settings.run_as_mobile(playwright, True)  # emulate a mobile device in headless mode
            page = browser.new_page()
            page.goto("http://whatsmyuseragent.org/")
            userAgent = page.inner_text("intro-text", 2000) # timeout after 2 seconds
            print(userAgent)
```
But to no avail. I get no errors except the test failing, so I guess that page.inner_text times out. What would be the correct way of doing this?
BONUS: If you inspect the page's HTML you see that there are actually two tags with that class, is there a way to iterate over all tags with a specific class to get the content of each of them?

Thank you for your help

**Comment by mxschmitt** [comment]
Playwright supports different selector engines, for example the CSS selector engine which you want.

`.intro-text` would be the right selector for your scenario: https://playwright.dev/docs/next/selectors#css-selector

A full example see here:

```pythonfrom playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()
    page.goto("http://whatsmyuseragent.org/")
    intro_texts = page.locator(".intro-text")
    print(intro_texts.nth(0).inner_text())
    print(intro_texts.nth(1).inner_text())
    browser.close()
```

Regarding your second question: https://playwright.dev/python/docs/next/locators

**Comment by GTP95** [comment]
This works, thank you!
