### ISSUE TITLE
[Question]: expect_response break before timeout

### ISSUE THREAD

**Issue by denismur** [microsoft/playwright-python#1285]
### Your question

After clicking on button I need to listen for one or two responses, it depends on first_response_json['status'] (if I got  'success' I don't need to wait for second response).
Now I use timeout in second response to break event listening, maybe there is another option? 
I  found there is `page.remove_listener()` but it looks like it doesn't work inside `expect_response()`

```
async with page.expect_response(lambda response: "second_response" in response.url, timeout=500) as second_response_info:
	async with page.expect_response(lambda response: "first_response" in response.url, timeout=0) as first_response_info:
		await button_locator.click()
	first_response = await first_response_info.value
	first_response_json = await first_response.json()
second_response = await second_response_info.value
second_response_json = await second_response.json()
```

**Comment by denismur** [comment]
Any ideas?

**Comment by rwoll** [comment]
Closing per above as part of triage. Feel free to re-open!

**Comment by imaxwen** [comment]
> You can create a `Future` and resolve it inside a response handler to achieve the custom logic.
> 
> See https://playwright.dev/python/docs/network#network-events and https://docs.python.org/3/library/asyncio-future.html. Instead of the `print`, you can resolve a `Future`.

this cannot work properly, after using `Future`, I got an error:
```
got Future <Future pending> attached to a different loop
```

here is my sample code:

```python
import asyncio
from playwright.async_api import async_playwright

fut = asyncio.Future()

def on_response(response):
    if 'downloadClientQR' in response.url:
        print('get the captcha image response')
        fut.set_result(response)
        fut.done()


async def main():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=False)
        context = await browser.new_context()
        page = await context.new_page()

        page.on('response', lambda resposne: on_response(resposne))
        await page.goto('https://mysite.com/')

        res = await fut

        print(f'res: {res}')


if __name__ == '__main__':
    asyncio.run(main())

```

**Comment by dan65t** [comment]
`page.expect_responses` this feature would be much helpful than the other solution that doesn't work on all cases

**Comment by 954-Ivory** [comment]
I need the solution too.

**Comment by morphf** [comment]
Same
