### ISSUE TITLE
[Feature] Expose locator from LocatorAssertions

### ISSUE THREAD

**Issue by Mr-Pepe** [microsoft/playwright-python#1286]
I want to retrieve the locator from a `LocatorAssertions` instance and later retrieve its selector and page. However, the locator seems to only be accessible via the implementation object by using `locator = locator_assertions._impl_obj._actual_locator`. The selector and page are then accessible via `locator._selector` and `locator.page`. 

I'd rather not rely on those internals and instead access the locator directly with `locator_assertions.locator`, which also returns the locator I originally passed to `expect` instead of the implementation object.

Can we add the locator passed to the `expect` function as an attribute to `LocatorAssertions`?

**Comment by mxschmitt** [comment]
What is the use-case of it? If you have a good use-case for it we might expose it on all our language bindings.

**Comment by Mr-Pepe** [comment]
Sorry for the late reply. I am working on a test framework for robotic systems. It provides a number of drivers to interact with the system under test and generates a unified log that makes it easy to figure out the exact state the system was in when a test failed. One of the drivers wraps Playwright and adds additional logging by wrapping some functions, e.g., methods of the `LocatorAssertions` class. I want to take a screenshot of the web page whenever an assertion fails. I would thus like to retrieve the locator and its page and selector from the assertions object.

**Comment by alexmavr** [comment]
We also have a use case of managing an AsyncExitStack to better report on timeouts from locators, and access to an assertion's locator would be helpful
