### ISSUE TITLE
[Question]: Can the browsers be installed manually?

### ISSUE THREAD

**Issue by mueller-f** [microsoft/playwright-python#1292]
### Your question

Hello, 
I want to install playwright behind a strict firewall. It is possible to do "pip install playwright" via a repository manager. 
But the installation (as expected) always fails at the "playwright install" part because the browser binaries cannot be downloaded:
    `
    Failed to install browsers 
    Error: Failed to download chromium v1000, caused by 
    Error: getaddrinfo ENOTFOUND playwright.azureedge.net 
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) `

I managed to download the zip-file as in setup.py from (1.21 is the correct version):
https://playwright.azureedge.net/builds/driver/next/playwright-1.21.0-linux.zip

(Also: I can't use a proxy.)

I am also able to transfer these to where I want playwright to be installed. But how do I make playwright use them? Or do I need to download something else?

**Comment by mxschmitt** [comment]
Installing the browsers manually is not supported, but you can have a custom CDN aka. artifactory in between which acts as a reverse proxy: https://playwright.dev/docs/next/browsers#download-from-artifact-repository

**Comment by mueller-f** [comment]
In the documentation you provided is explained how to point to the artifact repository, but can you please explain what exactly needs to be in the artifact repository? The conda-forge channel is already provided in the artifact repository, I have access to. Would it be enough to also have the conda channel 'microsoft'?

Thanks in advance

**Comment by Ennissay** [comment]
Good news, it is possible to manually install the browser. Download the file https://playwright.azureedge.net/builds/chromium/1005/chromium-win64.zip and extract it (which will be installed manually).

For your information, when trying to run the test (with pytest in this case), I received the following error message:

``playwright._impl._api_types.Error: Executable doesn't exist at C:\Users....\AppData\Local\ms-playwright\chromium-1055\chrome-win\chrome.exe. 
After opening the previously downloaded zip file, there is a chrome-win\chrome.exe file. So, I went to C:\Users....\AppData\Local\ms-playwright, created the directory chromium-1055, and copied and pasted the \chrome-win file from the zip. And magically, the test worked.

**Comment by Darrenbydesign** [comment]
Dude thanks! 
> Good news, it is possible to manually install the browser. Download the file https://playwright.azureedge.net/builds/chromium/1005/chromium-win64.zip and extract it (which will be installed manually).
> 
> For your information, when trying to run the test (with pytest in this case), I received the following error message:
> 
> ``playwright._impl._api_types.Error: Executable doesn't exist at C:\Users....\AppData\Local\ms-playwright\chromium-1055\chrome-win\chrome.exe. 
> After opening the previously downloaded zip file, there is a chrome-win\chrome.exe file. So, I went to C:\Users....\AppData\Local\ms-playwright, created the directory chromium-1055, and copied and pasted the \chrome-win file from the zip. And magically, the test worked.

**Comment by viorelsfetea** [comment]
**A 2025 update:**

I know that the official way is tinkering with a proxy until it works, but I am behind a pretty strict network and I wanted to download the browsers manually to just quickly test something out.

You know need to add some _empty_ files that tell Playwright that the browsers are installed correctly. They are currently called DEPENDENCIES_VALIDATED and INSTALLATION_COMPLETE. 

My %USERPROFILE%\AppData\Local\ms-playwright looks like this for Playwright 1.44:

- chromium-1117
-- chrome-win (folder exactly as found in the downloaded archive)
-- DEPENDENCIES_VALIDATED
-- INSTALLATION_COMPLETE

- ffmpeg-1009
-- ffmpeg-win64.exe
-- DEPENDENCIES_VALIDATED
-- INSTALLATION_COMPLETE

- firefox-1449
-- firefox (folder exactly as found in the downloaded archive)
-- DEPENDENCIES_VALIDATED
-- INSTALLATION_COMPLETE

- webkit-2003
--  webkit files exactly as found in the downloaded archive
-- DEPENDENCIES_VALIDATED
-- INSTALLATION_COMPLETE

**Comment by Alpaq92** [comment]
> Good news, it is possible to manually install the browser. Download the file https://playwright.azureedge.net/builds/chromium/1005/chromium-win64.zip and extract it (which will be installed manually).

I've give it a deep dive and we need to fetch [DownloadPaths from here](https://raw.githubusercontent.com/microsoft/playwright/main/packages/playwright-core/src/server/registry/index.ts) and enrich them with [browser details available here](https://raw.githubusercontent.com/microsoft/playwright/main/packages/playwright-core/browsers.json) and that's would be it ;) For example:

>   # Chromium (Chrome for Testing — uses browserVersion, NOT revision)
>   {mirror}/builds/cft/{browserVersion}/{platform}/chrome-{platform}.zip
>     platform tokens: win64, win32, linux64, mac-x64, mac-arm64
> 
>   # Chromium linux-arm64 (still revision-based, NOT CFT)
>   {mirror}/builds/chromium/{revision}/chromium-linux-arm64.zip
> 
>   # Firefox
>   {mirror}/builds/firefox/{revision}/firefox-{platform}.zip
>     platform tokens: win64, mac, mac-arm64, ubuntu-20.04, ubuntu-22.04, ubuntu-24.04, debian-11, debian-12, ...
> 
>   # WebKit
>   {mirror}/builds/webkit/{revision}/webkit-{platform}.zip
>     platform tokens: win64, mac-13, mac-13-arm64, mac-14, mac-14-arm64, mac-15, mac-15-arm64,
>                      ubuntu-20.04, ubuntu-22.04, ubuntu-24.04, debian-11, debian-12, ...
> 
>   Concretely, today's "latest" Windows zips are:
> 
>   - https://cdn.playwright.dev/dbazure/download/playwright/builds/cft/149.0.7827.3/win64/chrome-win64.zip
>   - https://cdn.playwright.dev/dbazure/download/playwright/builds/firefox/1522/firefox-win64.zip
>   - https://cdn.playwright.dev/dbazure/download/playwright/builds/webkit/2291/webkit-win64.zip
