### ISSUE TITLE
[Feature] Add new docker image for Ubuntu 22.04 Jammy Jellyfish LTS

### ISSUE THREAD

**Issue by str0zzapreti** [microsoft/playwright-python#1294]
Jammy Jellyfish is the latest Ubuntu LTS release and it includes support for Python 3.10 (Previous versions of Ubuntu require using a PPA or compiling from source to install Python 3.9+). 3.10 is the first major version of Python where the type annotation system can be considered "feature complete" and is therefore highly desirable for teams which want typed python tests or supporting libraries. For instance, while our team does not annotate our E2E tests themselves, we do write supporting page objects which are 100% typed. 

Unfortunately, the browser requirements specified by the `--with-deps` install flag don't all seem to be presently supported in 22.04 so a custom image isn't feasible (nor desirable, we would prefer to use an official Playwright Python image as the basis for running our tests rather than maintaining our own). Based on the focal and bionic docker images, it looks like playwright and its dependencies are now being loaded locally when the image is generated, so presumably this could be done for jammy as well to create a fully configured playwright image with python 3.10 installed by default.

**Comment by mxschmitt** [comment]
This is blocked by https://github.com/microsoft/playwright/issues/13738 but once its done we will add it based on interest (upvotes).
