### ISSUE TITLE
[BUG] TimeoutError always raised when handling popup pages in headless mode

### ISSUE THREAD

**Issue by xueke477** [microsoft/playwright-python#1295]
**Context:**
- Playwright Version: v1.21.0
- Operating System: Windows 10 64-bit
- Python version: 3.9.7
- Browser: Chromium
- Extra: None

**Code Snippet**

The reproduction repo and description of issue is at: https://github.com/xueke477/playwright-issue-reprod

**Describe the bug**

I wrote a program that collects certain data from a public website. At one step, I used the snippet from https://playwright.dev/python/docs/pages#handling-popups to trigger and handle popup pages. The program works perfectly in headed mode but always throw a TimeoutError at the step of triggering the popup page in headless mode. More details can be found from the reproduction repo linked above.

**Comment by mxschmitt** [comment]
I tried to run your repro, but it seems like they have some bot protection on their site, since the site is not working for me anymore (Access denied + connection timeout). Maybe thats the reason why its not working for you anymore.

**Comment by xueke477** [comment]
Hi Max,

Thanks for you reply!

After reading your comment, I realized that I have an old project that also involves handling popups. I upgraded that project's Playwright to v1.21.0 and ran it in headless mode — everything works well (for a different target website). I think this means it's truly due to a bot protection feature of the target website and not Playwright. Sorry about the false flag!

On the other hand, I come up with another question about Playwright itself while investigating the bot protection of QCOR. Basically, I inserted some simple snippets like `print(page.evaluate('() => window.sth'))` into the code to take a look at certain global variables of the target page. **When running in headless and headed mode, the outputs to stdout are different. Is this because there's some difference in the execution of JS code on the target page between headless and headed mode, or is it also caused by the bot protection in your opinion?** I've updated my repro. If you run it in both modes, you can see the difference.

Screenshots of the difference:
Headless:
![headless](https://user-images.githubusercontent.com/72355409/167895787-64827c30-97bd-442c-be34-b8327b00ac16.png)
Headed:
![headed](https://user-images.githubusercontent.com/72355409/167895809-b9a2f862-0ac3-47b7-9a1e-bd1345ce1a59.png)

**Comment by mxschmitt** [comment]
Most likely because bot protection, but I can't tell, because I didn't implement their bot protection. :)

I'd recommend to use user-agent emulation on headless, then it might work out.

Closing for now, since the questions are answered and its not e2e testing related.

**Comment by xueke477** [comment]
Hi Max,

Just want to say thank you! I used user-agent emulation and it just worked!

**Comment by a-3isa** [comment]
Hi ke, 
Can you show me how did you use ser-agent emulatoion?

**Comment by kxue43** [comment]
> Hi ke, Can you show me how did you user-agent emulation?

https://playwright.dev/python/docs/emulation#user-agent

Just pass whatever user-agent string to the `user_agent` argument.
