### ISSUE TITLE
[Question]: when the page  logs out, how automatically logs in and goes to the previous page?

### ISSUE THREAD

**Issue by god-pane** [microsoft/playwright-python#1297]
### Your question

We have a service that automatically logs out when it logs in and goes to a page and waits for a while.
I would like to implement that when it logs out, it automatically logs in and goes to the previous page.
But we have many pages with the same url, I use page.on('response', event), through response.status == 401, event monitor, but the page before the problem I mark out is always incorrect, how should I do it?

**Comment by god-pane** [comment]
But before determining the response.status == 401 I'm determining which page is the current page based on the element, which is not the page before exit. Is there another way, please?

**Comment by rwoll** [comment]
1. Would https://playwright.dev/python/docs/auth#reuse-authentication-state be helpful for you?
2. Which test runner are you using? Are you using [playwright-pytest](https://playwright.dev/python/docs/test-runners)?
