### ISSUE TITLE
KeyError: "name='ttwid', domain=None, path=None"

### ISSUE THREAD

**Issue by StefanoGITA** [microsoft/playwright-python#1298]
> > This error is coming from the `requests` library, this has nothing to do with Playwright for Python.
> 
> But i'm not directy importing requests i'm tring to use the example of the lib, this is my test_tiktok_api.py:
> 
> ```python
> from TikTokApi import TikTokApi
> 
> # Watch https://www.youtube.com/watch?v=-uCt1x8kINQ for a brief setup tutorial
> # V4
> # api = TikTokApi.get_instance()
> # for trending_video in api.by_trending():
> #     print(trending_video.author.username)
> 
> # V5
> with TikTokApi() as api:
>     for trending_video in api.trending.videos(count=50):
>         # Prints the author's username of the trending video.
>         print(trending_video.author.username)
> ```

Tiktokapi is using it internally. Please reach out to them.

_Originally posted by @mxschmitt in https://github.com/microsoft/playwright-python/issues/498#issuecomment-1124690825_

**Comment by StefanoGITA** [comment]
Excuse me @mxschmitt, but I never meets issue with **requests**.
I've also tried this lib on a clean virtualenv on a ubuntu machine and I gotten the same error.
is possibile that this lib necessity  to have a specific version of requests?

**Comment by mxschmitt** [comment]
Can you share a repro with us which does not involve any external library except Playwright?

**Comment by StefanoGITA** [comment]
Hi @mxschmitt this is the output of the the test in a clean venv:
```
Microsoft Windows [Versione 10.0.19044.1645]
(c) Microsoft Corporation. Tutti i diritti sono riservati.

C:\Users\sgiostra\Progetti\PycharmProjects\test>_venv\Scripts\activate

(_venv) C:\Users\sgiostra\Progetti\PycharmProjects\test>dir
 Il volume nell'unità C è Windows

 Directory di C:\Users\sgiostra\Progetti\PycharmProjects\test

12/05/2022  13:36    <DIR>          .
12/05/2022  13:36    <DIR>          ..
11/05/2022  18:06               492 test_tiktok_api.py
12/05/2022  13:36    <DIR>          _venv
               1 File            492 byte
               3 Directory  142.261.301.248 byte disponibili

(_venv) C:\Users\sgiostra\Progetti\PycharmProjects\test>pip list
Package            Version
------------------ ---------
certifi            2021.10.8
charset-normalizer 2.0.12
greenlet           1.1.2
idna               3.3
pip                21.2.4
playwright         1.21.0
pyee               8.1.0
requests           2.27.1
setuptools         58.1.0
TikTokApi          5.1.1
urllib3            1.26.9
websockets         10.1
WARNING: You are using pip version 21.2.4; however, version 22.1 is available.
You should consider upgrading via the 'C:\Users\sgiostra\Progetti\PycharmProjects\test\_venv\Scripts\python.exe -m pip install --upgrade pip' command.

(_venv) C:\Users\sgiostra\Progetti\PycharmProjects\test>python test_tiktok_api.py
Traceback (most recent call last):
  File "C:\Users\sgiostra\Progetti\PycharmProjects\test\test_tiktok_api.py", line 12, in <module>
    for trending_video in api.trending.videos(count=50):
  File "C:\Users\sgiostra\Progetti\PycharmProjects\test\_venv\lib\site-packages\TikTokApi\api\trending.py", line 40, in videos
    ttwid = spawn.cookies["ttwid"]
  File "C:\Users\sgiostra\Progetti\PycharmProjects\test\_venv\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\sgiostra\Progetti\PycharmProjects\test\_venv\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='ttwid', domain=None, path=None"
```

As wrote before, this is a clean venv where i made only:
```
pip install TikTokApi
python -m playwright install
playwright install-deps
```

I'm testing the lib so in this venv as script there is only **test_tiktok_api.py** that have the 15 rows that You have seen before and the libs are only that required by _TikTokApi_.

In attach [output_titokapi_test_on_linux.log](https://github.com/microsoft/playwright-python/files/8684982/output_titokapi_test_on_linux.log) the output of the test in ubuntu.

You need something else, just tell me.

Stefano G.

**Comment by mxschmitt** [comment]
As you can see in your stack trace:

```py
(_venv) C:\Users\sgiostra\Progetti\PycharmProjects\test>python test_tiktok_api.py
Traceback (most recent call last):
  File "C:\Users\sgiostra\Progetti\PycharmProjects\test\test_tiktok_api.py", line 12, in <module>
    for trending_video in api.trending.videos(count=50):
  File "C:\Users\sgiostra\Progetti\PycharmProjects\test\_venv\lib\site-packages\TikTokApi\api\trending.py", line 40, in videos
    ttwid = spawn.cookies["ttwid"]
  File "C:\Users\sgiostra\Progetti\PycharmProjects\test\_venv\lib\site-packages\requests\cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "C:\Users\sgiostra\Progetti\PycharmProjects\test\_venv\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='ttwid', domain=None, path=None"
```

there is no mention about playwright, this means this is not an error inside Playwright. Maybe file an issue inside the TikTokApi repository instead?

**Comment by StefanoGITA** [comment]
i thought the 2 libraries were interdependent, my foult, now i open the ticket on tiktokapi. Thanks

**Comment by bilalahmedkhatri** [comment]
> 2.27.1

@StefanoGITA did you find solution ?
