### ISSUE TITLE
[Feature] Including iframe content when calling page.content()

### ISSUE THREAD

**Issue by sla-te** [microsoft/playwright-python#1302]
Does not seem to be possible yet and can be very helpful when logging the full page html along with a screenshot.

**Comment by mxschmitt** [comment]
Is this for debugging a failing end-to-end test? Then having a trace file instead would be the recommended way for Playwright: https://playwright.dev/python/docs/next/trace-viewer

**Comment by sla-te** [comment]
Very interesting, was not aware that this existed, really nice. Does tracing have to be stopped, to release the reserved resources, in case I dont want to save the trace?

**Comment by mxschmitt** [comment]
> Very interesting, was not aware that this existed, really nice. Does tracing have to be stopped, to release the reserved resources, in case I dont want to save the trace?

Yes, either just close the context or call context.tracing.stop()

**Comment by sla-te** [comment]
Alright, I take it only closing the context would be sufficient then. - Wow you have just leveled up my debugging from 0.1 to 3.0 x)
