### ISSUE TITLE
[Question]:  main code is delayed while getting buffer data from response. 

### ISSUE THREAD

**Issue by hhk22** [microsoft/playwright-python#1303]
### Your question

while getting the buffer data, the main-code is delayed.

Here is my code. 

```
self.page.on('response', self._save_image_from_response)

await self.page.goto(url)
print('goto finished')

await self.page.wait_for_timeout(2000)  # blocked here
print('wait for time finished')
await self.page.evaluate('window.scrollTo(0, 0)')

async def _save_image_from_response(self, res):
    s = time.time()
    resource_type = res.request.resource_type
    if resource_type == 'image':
        buffer = await res.body()
        print(f"Image loading Done... {res.url} || {time.time()-s}")
```

```
log:
Image loading Done... url1 || 0.2
Image loading Done... url2 || 0.3
Image loading Done... url3 || 0.3
goto finished  
Image loading Done... url4 || 15.3  --> delayed
Image loading Done... url5 || 0.5
Image loading Done... url6 || 0.2
Image loading Done... url7 || 0.1
Image loading Done... url8 || 1.3
wait for time finished  --> wait for 20 sec after "goto finished" ( 2 sec normally )

```

Most websites seem like working fine, but on some websites, image loading is very slow blocking main-code to flow. 
Specifically, gif image which is bigger than 2MB (but not too big maybe 5MB?), await res.body() looks like making the code slow.. 
+) the website has about 300images(>2KB) in response
+) it happens on chromium, the code works fine on firefox.

thanks

**Comment by mxschmitt** [comment]
> res.body() is a heavy operation, it goes to the browser etc. and fetches the response payload. As bigger the response size is, as longer it takes.

Do you have a repro which you can share with us? 15.3 seconds is definitely too high! Happy to take a look if we have something which we can run locally.
