### ISSUE TITLE
[Question]: How to "flush" intercepted requests?

### ISSUE THREAD

**Issue by sueskind** [microsoft/playwright-python#1305]
### Your question

I record requests the following way:

```python
from playwright.sync_api import sync_playwright

url = "..."

with sync_playwright() as pw:

    browser = pw.chromium.launch()
    page = browser.new_page()
    page.goto(url)

    page.on("request", lambda r: print(r))
    page.click("button")
```

On my website, clicking on the button will send a PUT request. However, it is not printed to the console, even if some more clicks are done afterwards. Only when I do another `page.goto()` all requests that were done up to this point are printed.

Is there a way to perform this "flushing" without the additional `page.goto()`?

**Comment by mxschmitt** [comment]
The reason is that page.goto will wait until the page is fully loaded, only after it you are adding the event listener. If you change order by first adding the event listener and then doing page.goto then it should work.

```
    page.on("request", lambda r: print(r))
    page.goto(url)
```

**Comment by sueskind** [comment]
Thank you for your reply.

I am trying to test the functionality of the button on a single-page application, i.e. whether the correct request is made. Because the "intent" to record requests, the actual clicking and the assertions need to be in different functions, I can't use the `page.expect_request()` context manager.

Is there any other way than reloading the page to intercept the request via `page.on("request")`?

**Comment by Unintendedz** [comment]
> Is there any other way than reloading the page to intercept the request via `page.on("request")`?除了重新加载页面以通过page.on（“request”）拦截请求之外，还有其他方法吗？

I guess you're looking for `page.route` or `browser_context.route`

**Comment by sueskind** [comment]
@Unintendedz Thank you for the suggestion, sadly these to seem to behave the exact same way...

**Comment by sueskind** [comment]
I rephrased the question as #1318
