### ISSUE TITLE
[Question]: How to wait for page loading in playwright

### ISSUE THREAD

**Issue by hhroh** [microsoft/playwright-python#1306]
### Your question

How to wait for page loading in playwright?
I want to use Selenium's implicitly_wait in playwright.

**Comment by Unintendedz** [comment]
You don't need to, Playwright will do this for you. 
https://playwright.dev/python/docs/navigations#auto-wait

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/14213
