### ISSUE TITLE
[Feature] Add custom expect messages

### ISSUE THREAD

**Issue by Mr-Pepe** [microsoft/playwright-python#1310]
I was looking for a way to specify custom error messages for assertions and it looks like they are available in [Node.js](https://playwright.dev/docs/test-assertions#custom-expect-message) Playwright. How much effort would it be to also implement them in Python? With a little hint on where to start, I could give it a try.

**Comment by alexspurling** [comment]
I would also like this feature. At the very least let's update the documentation so that it explicitly states this is a feature that is not available (and perhaps even with a link to this Github issue so those who want it can voice their support).

**Comment by aspenboy** [comment]
+1 for this feature!

**Comment by at0m1x19** [comment]
+1 would be really nice to have it

**Comment by mgolubovich** [comment]
+1 really need this one!
