### ISSUE TITLE
[BUG] playwright install not working as intended

### ISSUE THREAD

**Issue by VBoB13** [microsoft/playwright-python#1311]
**Context:**
- Playwright Version: 1.22.0
- Operating System: Ubuntu 20.04 (VM)
- Python version: 3.8.10
- Browser: All
- Extra: This is happened right after upgrading from 1.11.2-> 1.22.0

So, I upgraded from 1.11.2 to 1.22.0 and then, as I was told to, I entered `playwright install` to install the browsers. That's when the below error message appeared...

```pw:channel:event {
  pw:channel:event   guid: '',
  pw:channel:event   method: '__create__',
  pw:channel:event   params: {
  pw:channel:event     type: 'Playwright',
  pw:channel:event     initializer: {
  pw:channel:event       chromium: [Object],
  pw:channel:event       firefox: [Object],
  pw:channel:event       webkit: [Object],
  pw:channel:event       android: [Object],
  pw:channel:event       electron: [Object],
  pw:channel:event       utils: [Object],
  pw:channel:event       deviceDescriptors: [Array],
  pw:channel:event       selectors: [Object],
  pw:channel:event       preLaunchedBrowser: undefined,
  pw:channel:event       socksSupport: undefined
  pw:channel:event     },
  pw:channel:event     guid: 'Playwright'
  pw:channel:event   }
  pw:channel:event } +3ms
  pw:install Chromium 102.0.5005.40 (playwright build v1005) is already downloaded. +0ms
  pw:install downloading FFMPEG playwright build v1007 - attempt #1 +3ms
  pw:install running download: +0ms
  pw:install -- from url: https://playwright.azureedge.net/builds/ffmpeg/1007/ffmpeg-linux.zip +0ms
  pw:install -- to location: /tmp/playwright-download-ffmpeg-ubuntu20.04-1007.zip +0ms
  pw:install attempt #1 - ERROR: getaddrinfo EAI_AGAIN playwright.azureedge.net +10s
  pw:install FAILED installation FFMPEG playwright build v1007 with error: Error: getaddrinfo EAI_AGAIN playwright.azureedge.net +0ms
Failed to install browsers
Error: Failed to download FFMPEG playwright build v1007, caused by
Error: getaddrinfo EAI_AGAIN playwright.azureedge.net
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
```

I am running 1.22.0 on my local (physical) macOS without issues.
Before this message appeared, there was a warning from Python saying that the script that was executing should use `Buffer.from()` instead of `Buffer()` due to security reasons. However, since it was just a warning and not an error, I would assume that is not the key issue.

**Comment by VBoB13** [comment]
I managed to actually solve the problem through doing a simple `python3 -m pip install --force-reinstall playwright`.
However, that doesn't mean that the issue doesn't still exist... Although I can't really re-produce it now either...
I guess one could try and intentionally install version 1.11.2 and then upgrade to 1.22.0 and see if that works.
Feel free to close the issue if you guys feel like it isn't important :)

**Comment by mxschmitt** [comment]
force-reinstall seems unrelated to it.

Its more like an DNS issue on your side what the errors says `Error: getaddrinfo EAI_AGAIN playwright.azureedge.net +0ms`

Could you try using a different DNS server?

**Comment by VBoB13** [comment]
I see. Oh well, since it did work after re-installing, I suppose I have learned a new type of error and know what's going on if it appears again ;)
Thank you!
