### ISSUE TITLE
[Feature] Make page.request.fetch work as described in Node.js docs

### ISSUE THREAD

**Issue by sla-te** [microsoft/playwright-python#1312]
I have tried to use this code translated to python https://playwright.dev/docs/network#modify-responses
```python
r = await page.request.fetch(route.request)
await route.fulfill(
	status=r.status,
	body=await r.body(),
	headers=r.headers,
	content_type=r.headers['content-type'],
	response=r,
)
```
and it throws `AssertionError: First argument must be either URL string or Request`, anything Iam doing wrong?

NOTE: If i remove the assertion, the API will return 400 bad request.

**Comment by mxschmitt** [comment]
sounds like we did not port all tests from it.
