### ISSUE TITLE
Target page, context or browser has been closed - METAMASK SIGN

### ISSUE THREAD

**Issue by DiMiTriFrog** [microsoft/playwright-python#1316]
Using Metamask Extension when i try to Sign wallet the Browser closes suddenly and show the error:

`"Target page, context or browser has been closed"`

The code:

```
async def connect_dextools_metamask(browser,actual_page): 
        print('<- Connecting Metamask to dextools ->')
        await actual_page.goto('https://www.dextools.io/app/user/account')
        await asyncio.sleep(2)
        
        await actual_page.locator('xpath=//html/body/app-root/div/div/main/app-register/app-layout/div/div/div[2]/div[1]/div[2]/button').click(timeout=30000)
        print('Click -> Connect')
        await asyncio.sleep(2)
        
        await actual_page.locator('text="MetaMask"').click(timeout=30000)
        print('Click -> MetaMask')
        await asyncio.sleep(3)
        
        metamask_page = await browser.new_page()
        await metamask_page.goto(f'chrome-extension://{EXTENSION_ID}/notification.html')
        await asyncio.sleep(3)
        
        await metamask_page.locator('text="Next"').click(timeout=30000)
        await asyncio.sleep(2)

        await metamask_page.locator('text="Connect"').click(timeout=30000)
        await asyncio.sleep(2)
        
        await metamask_page.locator('text="Sign"').click(timeout=30000)
        await asyncio.sleep(2)
```

I have two more interactions with Metamask -> Next and Connect, and both works perfectly but the thirds isn't working.
I could access from another link to Sign the same transaction, and the browser is closing too. I dont know what it happens.
I used Arsenic for do the same and works perfectly.

Any could help me?

**Comment by mxschmitt** [comment]
You could try setting the `DEBUG=pw:browser,pw:api` environment variable, to see what is actually happening. Maybe Chromium crashed but most likely your page just closed.

**Comment by DiMiTriFrog** [comment]
Was a metamask issue.
If I get the notifications through -> chrome-extension://{EXTENSION_ID}/home.html, the browses keep opened!
