### ISSUE TITLE
AWS Lambda Executable doesn't exist at /home/sbx_user1051/.cache/ms-playwright/chromium-1005/chrome-linux/chrome

### ISSUE THREAD

**Issue by DiMiTriFrog** [microsoft/playwright-python#1317]
**Context:**
- Playwright Version: [1.22.0]
- Operating System: [DOCKER UBUNTU 20.04]
- Python version: [3.8]
- Browser: [Chromium]
- Extra: [Aws Lambda]
**
Executable doesn't exist at /home/sbx_user1051/.cache/ms-playwright/chromium-1005/chrome-linux/chrome
   ║ Please run the following command to download new browsers: ║
   ║                                                                                                               ║
   ║ playwright install                                                                                 ║
   ║                                                                                                               ║
   ║ <3 Playwright Team                                                                           ║
 ╚════════════════════════════ ╝
**

```(Part of Docker that
FROM ubuntu:20.04 as base-image
# Define function directory
ARG FUNCTION_DIR="/function"
ARG RUNTIME_VERSION="3.9"

RUN apt-get update && DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install unzip wget xvfb \
 libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++ \
 libgl1-mesa-dev libxi-dev curl libx11-dev xvfb python3-tk python3-dev \ 
 dbus-x11 pulseaudio curl udev software-properties-common make cmake python3.8 python3-pip libcurl4-openssl-dev
RUN apt upgrade -y

RUN chmod 755 -R /opt
RUN chmod 755 -R /home
RUN chmod 777 -R /tmp

ARG FUNCTION_DIR
WORKDIR "/function"

RUN wget -q --continue -P "/function" "URL_APP.py"
RUN wget -q --continue -P "/opt" "URL_EXTENSION"
RUN wget -q --continue -P "/tmp" "URL_GENERIC_REQUIREMENTS"
RUN unzip -o "/opt/10.14.6_0.zip" -d "/opt"

RUN pip3 install --upgrade pip -q
RUN pip3 install -r /tmp/requirements.txt -q

#Install  Special Libs
RUN pip3 install playwright
RUN playwright install chromium --with-deps --force
RUN pip3 install \
    --target "/function" \
    awslambdaric

COPY 10.14.6_0 /opt
RUN chmod 777 -R /opt/10.14.6_0

ENTRYPOINT [ "python3", "-m", "awslambdaric" ]
CMD [ "app.handler" ]
```

**When I try to invoke a lambda function I receive the message error I put on top about the binary of chromium isn't on these directory. I run the command -> RUN playwright install chromium --with-deps --force for install the needed libs and I chmod 777 for the directory /home, but isn't working...
I used a own Docker image with ubuntu because I want to run playwright python with pyvirtualdisplay for use extensions
Could I specify thee binary path for chomium? And chromedriver? I think it will solve the issue.
**

**Comment by mxschmitt** [comment]
Seems like your Docker image during build uses a different user than during the execution of the lambda function. By default the browser downloads are per OS user.

You can change this behaviour to some shared folder, see here: https://playwright.dev/docs/browsers#managing-browser-binaries

**Comment by DiMiTriFrog** [comment]
So for example, i need to :
pip3 install playwright
PLAYWRIGHT_BROWSERS_PATH=/opt/
python3 -m playwright install

??

**Comment by mxschmitt** [comment]
You need to set it during "playwright install" and during the execution of your program. "python foo.py"

A simple `env PLAYWRIGHT_BROWSERS_PATH=/opt/` inside your Dockerfile before it should work.

**Comment by vietnguyengit** [comment]
didn't even say thank you? @DiMiTriFrog
