### ISSUE TITLE
[Question]: Why are requests not recorded earlier?

### ISSUE THREAD

**Issue by sueskind** [microsoft/playwright-python#1318]
### Your question

This is a rephrasing of question #1305 to clarify what the problem is.

I try to test whether a click on a button sends a specific (PUT) request. Since I want to separate the "intent" of listening for (specific) requests from the assertion that the request was made, I can't use `page.expect_request()`.

Therefore, my code is as follows:

```python
from playwright.sync_api import sync_playwright

with sync_playwright() as pw:

    browser = pw.chromium.launch()
    page = browser.new_page()
    page.goto("<some-url>")

    requests = []
    def record_request(r):
        requests.append(r)

    page.on("request", record_request)

    # ...

    page.click("button")

    # assert that specific request is in 'requests'
```

The request is definitely made when the button is clicked since it shows up in the DevTools, but it does not appear in the list. Using `page.route()` or trying both methods on the page's context instead does not help either.

Furthermore, a workaround seems to be to navigate, for example to the same page again: `page.goto("<some-url>")`. However, I would like to optimize my tests for speed and this second navigation would double the execution time. So I have the following questions:

1. Why are the requests not intercepted earlier when using `page.on()` or `page.route()`? Because with the `page.expect_request()` context manager everything seems to work fine (although sadly it is not applicable to my use-case).
2. Is there any workaround that does not include time-consuming operations like navigation?

**Comment by mxschmitt** [comment]
1. page.click will only wait until the click has finished, and maybe a navigation has occurred. If the click handler on the page does additional magic, timeouts or something like that, the click finishes before the network request occurs.
2. You could do wait_for_response in combination with page.on maybe.

**Comment by sueskind** [comment]
@mxschmitt thank you for your suggestion.

I could not find a `wait_for_response` so I assume you mean `wait_for_event("response")`. This does indeed solve my problem, at least as a workaround. To fix the example above I did the following:

```python
from playwright.sync_api import sync_playwright

with sync_playwright() as pw:

    browser = pw.chromium.launch()
    page = browser.new_page()
    page.goto("<some-url>")

    requests = []
    def record_request(r):
        requests.append(r)

    page.on("request", record_request)

    # ...

    page.click("button")

    def is_wanted(r):
        return r.request.method == "PUT"  # specify what response to wait for

    page.wait_for_event("response", is_wanted)

    # assert that specific request is in 'requests'
```
