### ISSUE TITLE
[Feature] page.expect_response() with multiple responses match, not the first one

### ISSUE THREAD

**Issue by denismur** [microsoft/playwright-python#1330]
As my [question](https://github.com/microsoft/playwright-python/issues/1285) wasn't answered I've decided to ask for a feature.

Sometimes after button click I need to wait for multiple or only one response. 
It depends on a first response answer, if json data comes with a status 'Ok', then I don't need to wait while timeout of second response

**Comment by rwoll** [comment]
Folding into https://github.com/microsoft/playwright-python/issues/1285
