### ISSUE TITLE
[Question]: about the close() function

### ISSUE THREAD

**Issue by CodarMonkey** [microsoft/playwright-python#1331]
### Your question

when I run my code, even if close() is not called, my browser is closed. how can I not close the browser and continue using the browser at the same point it is? as in selenium, when not passed close(), my browser remains open and can I continue getting information whenever an update occurs on the site? could you give me a small example of what this senario would be like if it is possible

**Comment by mxschmitt** [comment]
Depending on your testing setup you can re-use the context. But we discourage from doing this, because if one test in the beginning is failing, all the following tests will fail. Its important to have context isolation, which you can only achieve when creating a new context for every test case.
