### ISSUE TITLE
[Question]: Why is it very slow to load after I use "context.route()"?

### ISSUE THREAD

**Issue by chujian521** [microsoft/playwright-python#1333]
### Your question

I want to use "context.route()" to modify requests, but after I use this,  web pages sometimes load very slowly when running code. Why is it so?

```python
def route_hook(route: Route, req: Request):
    if req.post_data:
        post_data=modify(req.post_data)
        route.continue_(post_data=post_data)
    else:
        route.continue_()
......
......
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()

    # Open new page
    page = context.new_page()

    context.route("**", lambda route, req: route_hook(route, req))
.......
```

**Comment by rwoll** [comment]
What sites are you loading that you observe this? With routing enabled, browser caches are disabled due to implementation details (at least for Chromium), so some perf hit is expected (which—in a testing context—we assume to be OK).

**Comment by chujian521** [comment]
Thanks for your reply! I used a test site I built myself. This is much better when I use Firefox instead of Chromium.
