### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by enragedsweat** [microsoft/playwright-python#1344]
**Context:**
- Playwright Version: 1.22.0
- Operating System: Windows
- Python version: 3.10.4
- Browser: Chromium
- Extra: cmd

**Code Snippet**
![image](https://user-images.githubusercontent.com/104448363/171632262-70d4b59e-3686-437e-85ab-50e13de0c60c.png)

**Comment by mxschmitt** [comment]
As the error suggests, you need to execute `playwright install`.

If your Python is not correctly configured, you might have to do `python -m playwright install` to download the browsers.

**Comment by enragedsweat** [comment]
thanks

**Comment by enragedsweat** [comment]
Hi mxschmitt, this isnt exactly about playwright, but i got a question. 
![image](https://user-images.githubusercontent.com/104448363/171635553-b48826fc-8288-4d7e-b4f7-b48ff99c80a5.png)
What the hell should i do there

**Comment by mxschmitt** [comment]
pytube -> playwright.

`python -m playwright install  `
