### ISSUE TITLE
[BUG] PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD not works

### ISSUE THREAD

**Issue by scruel** [microsoft/playwright-python#1345]
**Context:**
- Playwright Version: 1.22.0
- Operating System: Windows 10 21H2
- Node.js version: 16.15.1
- Browser: All

C:\Users\user>set PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
C:\Users\user>playwright install
Downloading Chromium 102.0.5005.40 (playwright build v1005) - 104.1 Mb [                    ] 0% 535.2s Terminate batch job (Y/N)?

**Describe the bug**
Keep downloading browsers after set PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1.

**Comment by mxschmitt** [comment]
Setting this env var and calling `playwright install` does not make much sense. Why you simply just don't call `playwright install` in the first place?

**Comment by scruel** [comment]
> 

https://playwright.dev/python/docs/intro#installation
![image](https://user-images.githubusercontent.com/16933298/172014030-0ea73b5a-d84e-4341-8e04-a6708686a39a.png)

It appears on your document...

**Comment by mxschmitt** [comment]
Yes, because most of the users need browsers, thats why they execute it. If you don't want browsers, and use e.g. chromium channels then you don't need to run this command.

**Comment by scruel** [comment]
> Yes, because most of the users need browsers, thats why they execute it. If you don't want browsers, and use e.g. chromium channels then you don't need to run this command.

Ok, thanks, but I think you can just remove that or add something like:
If you want to download browsers, then execute `playwright install`
