### ISSUE TITLE
[Question]:  'playwright' is not recognized as an internal or external command, operable program or batch file. 

### ISSUE THREAD

**Issue by Mateusz404** [microsoft/playwright-python#1355]
### Your question

Hello!

### Installation process

I've installed playwright using the following commands in my command prompt:
**pip install --upgrade pip**
**pip install playwright**

but when I write the following:
**playwright install**

### Problem

Command Prompt says that
_'playwright' is not recognized as an internal or external command,
operable program or batch file._

### How can I fix that?

--

### Additional Information

**pip install --upgrade pip**
Requirement already satisfied: pip in _c:\users\mateusz\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (22.1.2)_

**pip install playwright**
_Requirement already satisfied: playwright in c:\users\mateusz\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (1.22.0)
Requirement already satisfied: websockets==10.1 in c:\users\mateusz\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from playwright) (10.1)
Requirement already satisfied: pyee==8.1.0 in c:\users\mateusz\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from playwright) (8.1.0)
Requirement already satisfied: greenlet==1.1.2 in c:\users\mateusz\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from playwright) (1.1.2)_

**playwright install**
_'playwright' is not recognized as an internal or external command,
operable program or batch file._

**Comment by mxschmitt** [comment]
This usually happens if the Python module scripts are not added to the PATH env var / the python installation is not installed correctly.

As a workaround you can prefix it with `python -m` aka `python -m playwright --help`

**Comment by mxschmitt** [comment]
Then you most likely have different Python versions installed at the same time. Make sure that the CLI and your executable both point to the same one.

**Comment by Mateusz404** [comment]
Oh, thanks! 

Solution for anyone facing the same issue:

1. Click Search on your windows and type:
"**Manage App Execution Aliases**"

2. **Turn OFF** all App Installer that has python.exe below the name (also python3.exe etc)

3. Search again, this term:
"**Edit the system environment variables**"

4. Click "**Environment Variables...**"

5. In the "System variables" list, select a **Variable** named "**Path**" and click the "**Edit**" button below the list.

6. In the "Edit environment variable popup, click the "New" button and then write:
"_C:\Users\YOURUSERNAME\AppData\Local\Programs\Python\Python310_"
and do the same with the second one:
"_C:\Users\YOURUSERNAME\AppData\Local\Programs\Python\Python310\Scripts_"

The path from step 6 might need modification, depending on your Python version.

**Comment by Th30v3rf10w** [comment]
What about step #2?
Keep it turned OFF?
