### ISSUE TITLE
[Question]: page.route request.response() is None

### ISSUE THREAD

**Issue by CGpythoner** [microsoft/playwright-python#1366]
### Your question

page.route callback function get_async_data  request.response() is None

async def get_async_data(route, request):
    """
    pass 无法通过此方法拦截响应结果
    :param route: 
    :param request: 
    :return: 
    """
    logger.info(f'route:{route}')
    logger.info(f'request:{request}')
    resp = await request.response()
    logger.info(f'resp:{resp}')
    text = await resp.text()
    logger.info(f'text:{text}')

**Comment by mxschmitt** [comment]
can you provide us a full repro which we can run locally?

**Comment by CGpythoner** [comment]
`
# -*- coding:utf-8 -*-


async def local_request_finished_info(request_finished):
    """可以通过request.response() 获取响应"""
    if request_finished.url == 'https://www.facebook.com/api/graphql/':
        logger.info(request_finished)
        finish_resp = await request_finished.response()
        logger.info(f'finish_resp:{finish_resp}')
        graphql_result = await finish_resp.text()
        with open('./finish_resp_result.json', 'w', encoding='utf-8')as f:
            f.write(graphql_result)


async def get_async_data(route, request):
    """
    pass 无法通过此方法拦截响应结果
    :param route:
    :param request:
    :return:
    """
    logger.info(f'route:{route}')
    logger.info(f'request:{request}')
    resp = await request.response()
    logger.info(f'resp:{resp}')
    text = await resp.text()
    logger.info(f'text:{text}')
    with open('./response_graphql.json', 'w', encoding='utf-8')as f:
        f.write(text)


async def main():
    async with async_playwright() as p:
        browser = await p.chromium.launch(
            headless=False,
            devtools=True,
        )
        page = await browser.new_page()
        # page.on('requestfinished', local_request_finished_info)
        await page.route('/api/graphql/', get_async_data)
        await page.goto('https://www.facebook.com/twdaynews', timeout=300000)
        await page.wait_for_load_state('load', timeout=300)
        print(f'title:{await page.title()}')

asyncio.run(main())
`

**Comment by CGpythoner** [comment]
use function local_request_finished_info   await request.response  -> await response.text()  can return response.text
