### ISSUE TITLE
[BUG] Apple M1 - issue with playwright Installation

### ISSUE THREAD

**Issue by TzachiGuetta** [microsoft/playwright-python#1367]
**Context:**
- Operating System: MAC 12.4
- apple silicon 

**Describe the bug**
I'm getting this error when I trying to install :
% pip install --upgrade pip
Requirement already satisfied: pip in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (21.3.1)
% pip install playwright
ERROR: Could not find a version that satisfies the requirement playwright (from versions: none)
ERROR: No matching distribution found for playwright

**Comment by mxschmitt** [comment]
Python 3.6 is not supported, we recommend 3.10

**Comment by pkrefta** [comment]
@mxschmitt Should `playwright-python` work properly on Mac OS Ventura ? I'm trying to install it but I've the same error as @TzachiGuetta 
```
(project-py3.10) project-YvDiPli1-py3.10 ❯ pip install playwright
ERROR: Could not find a version that satisfies the requirement playwright (from versions: none)
ERROR: No matching distribution found for playwright
```

**Comment by mxschmitt** [comment]
@pkrefta looks like a separate issue, could you file a separate issue for it? And provide some more details aka.

```txt
python --version
pip --version
pip debug
```
