### ISSUE TITLE
[BUG] - Unable to run "playwright install" from office laptop

### ISSUE THREAD

**Issue by KaranAgarwal1987** [microsoft/playwright-python#1369]
**Context:**
- Playwright Version: [what Playwright version do you use? - Latest]
- Operating System: [e.g. Windows]
- Python version: [3.10.5]
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally.

```python
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()
    # ...
    browser.close()
```
Facing the below issue in downloading the binaries.
(venv) C:\Users\karan.agarwal\PycharmProjects\Playwright_demo>playwright install
Failed to install browsers
Error: Failed to download Chromium 102.0.5005.40 (playwright build v1005), caused by
Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
I have also set the env variable --> set PLAYWRIGHT_DOWNLOAD_HOST=192.0.2.1

I am not very expert in understanding the [proxy](https://playwright.dev/python/docs/browsers#install-behind-a-firewall-or-a-proxy), Can you please help with the step by step instructions for the same.
Add any other details about the problem here.

**Comment by mxschmitt** [comment]
It sounds like you need to set a custom proxy, see here: https://playwright.dev/docs/browsers#install-behind-a-firewall-or-a-proxy

Setting `PLAYWRIGHT_DOWNLOAD_HOST ` is not right, since you want to configure a proxy not a custom CDN mirror.
