### ISSUE TITLE
The offender may have garbled characters in a screenshot while using the same screen

### ISSUE THREAD

**Issue by ReadSmall** [microsoft/playwright-python#1370]
### Your question
The offender may have garbled characters in a screenshot while using the same screen

![image](https://user-images.githubusercontent.com/48905684/174875801-821b8d8d-d1eb-4cc7-be50-d560b7839bfc.png)

**Comment by mxschmitt** [comment]
Whats the environment in which you launch the browser? container, vm, os?

**Comment by ReadSmall** [comment]
Centos8，After I installed the Chinese font, it was solved. Thank you for your reply. Thank you.




---Original---
From: "Max ***@***.***&gt;
Date: Wed, Jun 22, 2022 17:19 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [microsoft/playwright-python] The offender may have garbled characters in a screenshot while using the same screen (Issue #1370)




 
Whats the environment in which you launch the browser? container, vm, os?
