### ISSUE TITLE
[Question]: Get clipboard's content

### ISSUE THREAD

**Issue by GTP95** [microsoft/playwright-python#1371]
### Your question

Hello,

I'm looking for a way to get the clipboard's content after clicking on a button that copies an email address to the clipboard. I saw that in JS you can use `navigator.clipboard` to interact with the clipboard, but this doesn't seem to work in the Python version. Currently, I'm invoking xclip as a workaround, but it doesn't seem to work in the production environment where I'll need to run my code. Is there any way to get the clipboard's content in Playwright Python? I'm using chromium as browser but I can switch to another one if needed.
Thanks,

Giacomo

**Comment by mxschmitt** [comment]
There is a feature request for it: https://github.com/microsoft/playwright/issues/8114

Folding into that.
