### ISSUE TITLE
[BUG] CLI ISSUE

### ISSUE THREAD

**Issue by 9Samzer** [microsoft/playwright-python#1373]
Infos
- Playwright Version: Latest
- Operating System: Windows
- Python version: 3.10
- Browser: Firefox

Hey, when i try to use async Playwright with threads (threading.Thread()), it works perfectly on VSC. But when i used Pyarmor (+pyinstaller) to build my app, process of threads is stuck on exe without showing error, just stuck...
Thx in advance for your resp

**Comment by mxschmitt** [comment]
Pyarmor is not supported. If you find a workaround or a bug inside Playwright which makes it work, we're happy to land, but we can't provide unfortunately any official support for it.
