### ISSUE TITLE
[BUG] Python memory usage increases with goto or reload

### ISSUE THREAD

**Issue by z719893361** [microsoft/playwright-python#1377]
**Context:**
- Playwright Version: 1.22.0
- Operating System: Windows11
- Python version: 3.10
- Browser: All

**Code Snippet**

```python
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    with p.chromium.launch(headless=False) as browser:
        with browser.new_context() as context:
            with context.new_page() as page:
                while True:
                    page.goto('https://www.baidu.com')


```

**Describe the bug**
After testing, whether synchronous or asynchronous, the repeated goto of context reuse will continuously increase the memory

![image](https://user-images.githubusercontent.com/38043183/175573892-6d2ecdb1-012d-4f47-b232-83ecf8031eab.png)

**Comment by mxschmitt** [comment]
This is expected. You need to close the context to release memory.
