### ISSUE TITLE
Downstream test organization

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright-python#138]
The idea is that our downstream tests will be 1:1 to our upstream tests:

- We will convert all the test names to pytest identifiers `test_foo` using canonical name conversion (replacing all non-identifier characters with _)
- We will keep them in the files named similarly to upstream, foo.spec.js -> test_foo.py
- For tests that we don't think are worth porting, we will have `pass` in them and a 1-line comment suggesting that we don't want to port this test

We should be able to run a script that would tell us how many tests are not yet ported relative to the upstream state

**Comment by rwoll** [comment]
@pavelfeldman Have you already started working on this? I'll have a some time this evening where I could contribute a script.

For the node tests, I was thinking of using the out output of:

```
$ REPORT_ONLY_PLATFORM=1 jest --json
```

and use it with the output of:

```
pytest --collect-only
```

Some alternatives:
* Regex to extract the names from the source files
* Use @babel/parser and a Python equivalent to operate on the AST
