### ISSUE TITLE
[Feature] Return all object attributes when calling response.security_details()

### ISSUE THREAD

**Issue by byt3bl33d3r** [microsoft/playwright-python#1380]
The [`Network.SecurityDetails`](https://chromedevtools.github.io/devtools-protocol/tot/Network/#type-SecurityDetails) object returns  useful information about the TLS cert however Playwright only seems to exposes 5 of the many object attributes.

https://github.com/microsoft/playwright-python/blob/f742da90a9f2ab48149759b3ec7b50c707a0d6ad/playwright/_impl/_api_structures.py#L147-L152

Lot of the object attributes are missing in this response (including the `sanList` which is super important):

<img width="837" alt="image" src="https://user-images.githubusercontent.com/5151193/175719504-bf888c9d-43bb-400f-a121-72247b894be7.png">

All of these attributes should be returned when calling `response.security_details()`

**Comment by rwoll** [comment]
Folding into https://github.com/microsoft/playwright/issues/6759. **Please comment there with your use case.** 

NB: Unless it is exposed on all the browsers Playwright integrates with, it's unlikely to be added. I did some work upstream to start getting more bits expose in WebKit Linux, but it's been a while and has unfortunately shifted in priority for me.
