### ISSUE TITLE
[Feature]specify a video file name not the file path

### ISSUE THREAD

**Issue by AllenLuosong** [microsoft/playwright-python#1388]
Like the script as below, I just want to generate a video file with specify name, but I did not find there is method that I can get in playwright。
context = browser.new_context(record_video_dir="videos/")

**Comment by rwoll** [comment]
Videos are mostly for use in traces, so the default names are not intended to be human readable. There's at least one per page, and a page can go to many URLs, so it's not clear what name should be used by specifying at the context level.  **However, you can save with custom names by calling [`page.video()`](https://playwright.dev/python/docs/api/class-page#page-video) for each page, and then use [`video.save_as(…)`](https://playwright.dev/python/docs/api/class-video#video-save-as).**
