### ISSUE TITLE
[BUG] Instance loop looks like shared, alawyas get "Please use the Async API instead." after first run.

### ISSUE THREAD

**Issue by hkfsc** [microsoft/playwright-python#1391]
**Context:**
- Playwright Version: Playwright 1.22.0
- Operating System: Windows10
- Python version: 3.8.10
- Browser: All

**Code Snippet**

```python
from playwright.sync_api import sync_playwright
sync_playwright().start()
sync_playwright().start()
```

**Describe the bug**
Function `sync_playwright().start()` will not be callable after first run, always get:
```
playwright._impl._api_types.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
```

**Comment by rwoll** [comment]
Thanks for the report. This appears to be working as intended. Avoid manually calling start, and only use one Python context at a time:

```py
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    # your code here
    browser = p.chromium.launch()
    page = browser.new_page()
    page.goto("http://playwright.dev")
    print(page.title())
    browser.close()
```

If you want to launch multiple browsers simultaneously and have them doing things in parallel, please use the async API like so:

```py
import asyncio
from playwright.async_api import async_playwright

async def do_work(playwright):
    browser = await playwright.chromium.launch()
    page = await browser.new_page()
    await page.goto("http://playwright.dev")
    print(await page.title())
    await browser.close()

async def main():
    async with async_playwright() as p:
        # run many at the same time
        await asyncio.gather(do_work(p), do_work(p), do_work(p))

asyncio.run(main())
``` 

Further examples: https://playwright.dev/python/docs/intro#usage

**Comment by hkfsc** [comment]
With Python context? you will wrote everything in it rather than have some place which can control it welly?
I don't want to user asyncio at all, it will need to write `await` in code for many times...

**Comment by rwoll** [comment]
Can you explain what you are trying to do? Either with code or pseudo code?

Are you trying to run multiple browsers in parallel from one Python script? Or something else? I'm not sure I follow your original snippet/question.

Thanks!

**Comment by hkfsc** [comment]
I do want to launch multiple browsers simultaneously, but I do don't want to use async API.

**Comment by rwoll** [comment]
Using async is the recommended way for using multiple browsers at once and taking actions simultaneously in them. Without async, you'd have to take alternate taking actions on each browser since sync is blocking by definition:

```
with sync_playwright() as p:
    browser = p.chromium.launch()
    browser_2 = p.chromium.launch()
    page = browser.new_page()
    page.goto("http://playwright.dev")
    print(page.title())

    page_2 = browser_2.new_page()
    page_2.goto("http://playwright.dev")
    print(page_2.title())

    browser.close()
    browser_2.close()
```

If the async example in https://github.com/microsoft/playwright-python/issues/1391#issuecomment-1171793456 is not suitable, my only other suggestion would be to run two different scripts.

If you can include more sample code of what you're trying to do, maybe there as another suggestion other than https://github.com/microsoft/playwright-python/issues/1391#issuecomment-1171793456, but without more details we are unable to assist further.

**Comment by hkfsc** [comment]
@rwoll
Are you really want to write `await` in each line of all the playwright related code?

**Comment by openSourceBugs** [comment]
It seems like the async aspect of the playwright python project is extremely poorly implemented.  Why use the await keyword as a line separator to get async?

**Comment by D1abol1cal** [comment]
what I am trying to accomplish is very competitive and needs to be done very quickly and on the same page. I need to perform multiple actions on the same page concurrently using playright, I tried using normal pseudo python threads but I got greenlet errors and I found out that playright isn't thread safe, what would be the best approach to this?
