### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright-python#1395]
Blocked by https://github.com/python-greenlet/greenlet/issues/305

Python 3.11 is currently in development and going to be released on October 3, 2022.

**Comment by kumaraditya303** [comment]
The upstream issue [^1] is not a blocker for playwright as it does not uses C API of `greenlet`. There are pre-release wheels available for 3.11 [^2] which works on 3.11+, all that is needed is to update the requirement to allow for `>=` in playwright.

[^1]: https://github.com/python-greenlet/greenlet/issues/305

[^2]: https://pypi.org/project/greenlet/2.0.0a2/#files

**Comment by mxschmitt** [comment]
Good catch! But I think would be nice to wait for the official release of 2.0 instead of relying on pre-releasees.
