### ISSUE TITLE
[BUG] Frame is emitted on Page events domcontentloaded/load

### ISSUE THREAD

**Issue by YusukeIwaki** [microsoft/playwright-python#1399]
**Context:**
- Playwright Version: 1.23
- Operating System: macOS
- Python version: 3.9
- Browser: Chromium

**Code Snippet**

```python
from playwright.sync_api import sync_playwright, Page

with sync_playwright() as playwright:
    with playwright.chromium.launch(channel='chrome') as browser:
        page = browser.new_page()
        with page.expect_event('domcontentloaded') as event:
            page.goto('https://github.com/YusukeIwaki')
        print(event.value)
```

**Describe the bug**

The code above prints `Frame` in 1.23, which was `Page` in 1.22.
The JS version of Playwright still prints Page with the similar code, so I think this is an unexpected change.
The change would be made here: https://github.com/microsoft/playwright-python/pull/1374/files#diff-532b443f553121e300cafcb5964712250d091576e944af3b880ba143e1413c28R103

**Comment by rwoll** [comment]
Oops! Thanks for pointing this out. Let me update and add test coverage here.

**Comment by rwoll** [comment]
Once https://github.com/microsoft/playwright-python/pull/1400, we'll put it into a patch release of the Python 1.23 version. Thanks!
