### ISSUE TITLE
[Feature]Hope Playwright support android as soon as possible

### ISSUE THREAD

**Issue by zhonghai9967** [microsoft/playwright-python#1401]
It took 2 months from 1.22 to 1.23, 
which is the largest time span for version updates,
but few functions have been added.
If there is a plan, can you support the android system as soon as possible?
Thank you for your hard work!

**Comment by zhonghai9967** [comment]
@mxschmitt Once mentioned:
[Feature] Expose Android classes #1281
https://github.com/microsoft/playwright-python/issues/1281

**Comment by mxschmitt** [comment]
The android API gets ported once its stable, its not yet stable upstream, hence we don't port it.

Folding into https://github.com/microsoft/playwright-python/issues/1281
