### ISSUE TITLE
[Question]: Is there a way to use a browser that was not opened with playwright?

### ISSUE THREAD

**Issue by victoriafinzi** [microsoft/playwright-python#1406]
### Your question

Hi! I'm building an automation and I need that the browser have been opened using pyautogui. I was wondering if there is a way to make playwright recognize and use this already open browser.
I have already used the channel and it is not fulfilling what I need.

Thank you very much for your attention!

**Comment by zhonghai9967** [comment]
I have a same problem

**Comment by rwoll** [comment]
For Chromium, yes: https://playwright.dev/python/docs/next/api/class-browsertype#browser-type-connect-over-cdp
