### ISSUE TITLE
[Question]: How to drag and drop a file ?

### ISSUE THREAD

**Issue by vivekvasu95** [microsoft/playwright-python#1410]
### Your question

**Any example for drag and drop a file ?**

**Comment by rwoll** [comment]
Do you have an example of a site/page you're trying to test? When you say "Any example for drag and drop a file ?" do you mean dragging and dropping within the page, or dragging a file from outside of the browser onto the page?

If the former, it's like: [`page.drag_and_drop("#source", "#target")`](https://playwright.dev/python/docs/next/api/class-page#page-drag-and-drop) (but you can replace `#source` and `#target` with other selectors).

Thanks!

**Comment by vivekvasu95** [comment]
I have to drag a file stored in system to the html upload section. In this scenario, there is only target. Source is a file or stored in system.

**Comment by rwoll** [comment]
In this case you can use https://playwright.dev/python/docs/input#upload-files

**Comment by vivekvasu95** [comment]
Still... anyway that i can perform the actual drag and drop with file ? Like what we do the same with mouse
