### ISSUE TITLE
[BUG] (🐞) `typing.Pattern` used in type hints are not supplied type parameters

### ISSUE THREAD

**Issue by KotlinIsland** [microsoft/playwright-python#1415]
https://github.com/microsoft/playwright-python/blob/c8d8f4a6859ac210fa6b6f01eb636fc11065abb9/playwright/sync_api/_generated.py#L3060-L3066
```py
page.expect_navigation(
  re.compile("abc")  # error: expression contains Any
)
```
`typing.Pattern` expects one type parameter, usually `AnyStr`.

**Comment by Zeckie** [comment]
Shouldn't it be `typing.Pattern[str]` (if it is to be a pattern matching a string)? https://docs.python.org/3/library/typing.html#typing.Pattern  https://docs.python.org/3/library/typing.html#typing.AnyStr
