### ISSUE TITLE
[BUG] Save Page Video of Test in Report

### ISSUE THREAD

**Issue by 000xiaoxiao000** [microsoft/playwright-python#1417]
combine playwright with pytest,

 with sync_playwright() as playwright:
           browser = playwright.chromium.launch(headless=False) 
           page = context.new_page()

@pytest.mark.hookwrapper
def pytest_runtest_makereport(item, call):
       page.video.path()... ...Inaccessible

**Comment by rwoll** [comment]
Hi, @000xiaoxiao000! Can you elaborate on what you're trying to do so I make sure I answer the correct question?

Is your goal: save a video of the page that was used in the test into a report?

Thanks!

**Comment by rwoll** [comment]
(I've added a title, but please correct if it does not reflect your goal.)

**Comment by 000xiaoxiao000** [comment]
The use of "with sync_playwright() as playwright:
                           browser = playwright.chromium.launch(headless=False)
                           page = context.new_page()"
                           ... ...page operation
                           When making "page.video.path()"
                           Failed to obtain path.

> Hi, @000xiaoxiao000! Can you elaborate on what you're trying to do so I make sure I answer the correct question?
> 
> Is your goal: save a video of the page that was used in the test into a report?
> 
> Thanks!

The use of "with sync_playwright() as playwright:
                           browser = playwright.chromium.launch(headless=False)
                           page = context.new_page()"
                           ... ...page operation
                           When making "page.video.path()"
                           Failed to obtain path.

**Comment by rwoll** [comment]
I'm not following the code snippet still. What are you trying to achieve?

**Comment by 000xiaoxiao000** [comment]
> I'm not following the code snippet still. What are you trying to achieve?

screen recording.

**Comment by rwoll** [comment]
You'll need to set the record video options on the context when you create it. By default, video's are not enabled unless you opt the context in. See some code samples here: https://playwright.dev/python/docs/videos

**Comment by 000xiaoxiao000** [comment]
> "with sync_playwright() as playwright:
> browser = playwright.chromium.launch(headless=False)
> page = context.new_page()"
> ... ...page operation
> When making "page.video.path()"
> Failed to obtain path.

"with sync_playwright() as playwright:
browser = playwright.chromium.launch(headless=False)
page = context.new_page()"
... ...page operation
When making "page.video.path()"
Failed to obtain path,
An error in the.

**Comment by mxschmitt** [comment]
It looks like you are combining manual using Playwright and pytest-playwright. You should pick one or the other, otherwise you'll run into such issues. If you using the playwright pytest plugin, the page parameter will be created for you. There should be no need to manually call chromium.launch etc.

If you are using pytest-playwright, it will record video out of the box, see here: https://playwright.dev/python/docs/next/test-runners#cli-arguments

**Comment by 000xiaoxiao000** [comment]
> 看起来您正在使用 Playwright 和 pytest-playwright 组合手册。你应该选择一个或另一个，否则你会遇到这样的问题。如果您使用 playwright pytest 插件，将为您创建页面参数。应该不需要手动调用 chromium.launch 等。
> 
> 如果您使用的是 pytest-playwright，它将开箱即用地录制视频，请参见此处：[https ://playwright.dev/python/docs/next/test-runners#cli-arguments](https://playwright.dev/python/docs/next/test-runners#cli-arguments)

Is there a combination of login and subsequent operations?

**Comment by rwoll** [comment]
> Is there a combination of login and subsequent operations?

Can you file a new issue explaining what you are trying to do? 

If you want to perform authentication manually before your tests run, you can run:

```
npx playwright open --save-storage "authState.json" https://example.com
```

Log in, then close the browser.

Then, in later use authState.json with https://playwright.dev/python/docs/api/class-browser#browser-new-context-option-storage-state
