### ISSUE TITLE
[Question] How to keep Playwright headless browser alive permanently?

### ISSUE THREAD

**Issue by el3mentry** [microsoft/playwright-python#1418]
I want to run headless chromium using Playwright (using python libraries) on a virtual private server for some scraping work - for this I am required to execute some instructions in 'browser contexts'. The issue is that I do not want to re-open browser instance again & again. I want to open a browser instance once and then open and close contexts INSIDE of that one instance.

I am running the following code in which I am trying to store the browser's reference in the 'BROWSER' variable.

```
from flask import Flask
import json
from login import login_and_scrape
from playwright.sync_api import sync_playwright


APP = Flask(__name__)
BROWSER = None


@APP.route("/scrape/<shortcode>")
def scrape(shortcode: str = "") -> str:

    url = f"https://www.instagram.com/p/{shortcode}/?__a=1&__d=dis"

    credentials = {
        "username": "username",
        "password": "password"
    }

    loaded_json: json = login_and_scrape(BROWSER, url, credentials)

    if loaded_json:
        return loaded_json, 200
    
    return {}, 404


if __name__ == "__main__":

    with sync_playwright() as playwright:
        BROWSER = playwright.chromium.launch(headless=True)
        APP.run(debug=True)
```

On running the program on localhost:5000 I get a greenlet error shown in the screenshot attached.
![Greenlet Error](https://user-images.githubusercontent.com/50634942/177826041-b020e277-88f6-4784-b0c3-685bd6b5714d.png)

**Comment by rwoll** [comment]
The error (`greenlet.error: cannot switch to a different thread`) alludes to Flask's architecture (running main in a thread and each of the handlers/requests in other threads) conflicting with Playwright's default assumption of how it's used (single-threaded).

If you add `import threading` to the top of your file, and then put `print(">>>>> IN HANDLER", threading.get_ident())` in your handler and `print(">>>>> IN MAIN", threading.get_ident())` in your main, you'll see the differing thread identities.

Playwright is mostly focused on testing, and therefore assumes single-threaded operation. (It supports parallel processing via our `async` API, but that is is also restricted to one-thread.)

To workaround this, you could try:

1. disabling threading in Flask (and only allowing one request at a time)
2. look into Flask async API and see if it's architected in a way that's compatible with Playwright's assumptions out of the box (I'm not sure)
3. Have your handler post a task/job to a shared instance that does all Playwright operations on a single thread.

**Comment by rwoll** [comment]
Closing per above as part of triage
