### ISSUE TITLE
[Question]: How to get all the selected items from a select list in Python Playwright

### ISSUE THREAD

**Issue by soumya-kar** [microsoft/playwright-python#1421]
### Your question

Is there any method like getSelectedOption() or getAllSelectedOption()?

**Comment by zhonghai9967** [comment]
No get_selected_option()  method.
locat =page.locator('td:has-text("txt") >select >option**[selected="selected"]**')
locat.count()
locat..inner_text()

**Comment by rwoll** [comment]
If you're looking to assert that a `<select>` has multiple values selected, there is the new (v1.23) built-in https://playwright.dev/python/docs/test-assertions#locator-assertions-not-to-have-values

However, if you're looking to just return values, there's no built in at the moment, but you can use [`HTMLSelectElement.selectedOptions`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/selectedOptions) like:

```python
page.locator("#my-select-element").evaluate("node => node.selectedOptions")
```

(which is what the Web-First assertion variant is using internally)

**Comment by jcyrss** [comment]
Try with css pseudo-class 'checked', like this

```py
page.locator('#select-element option:checked').all_inner_texts()
```
