### ISSUE TITLE
[BUG] greenlet.error: cannot switch to a different thread

### ISSUE THREAD

**Issue by hkfsc** [microsoft/playwright-python#1422]
**Context:**
- Playwright Version: [what Playwright 1.23.0
- Operating System: Windows
- Python version: 3.8.10
- Browser: All

**Code Snippet**
```python
p = sync_playwright().start()

def do_work():
    browser = p.chromium.launch()
    page = browser.new_page()
    page.goto("http://playwright.dev")
    print(page.title())
    browser.close()
 
threading.Thread(target=do_work).start()
threading.Thread(target=do_work).start()
```

**Describe the bug**
```
Exception ignored in thread started by: <function do_work at 0x0000017D638D3700>
Traceback (most recent call last):
  File "D:\test\main.py", line 11, in do_work
    browser = p.chromium.launch()
  File "D:\python\lib\site-packages\playwright\sync_api\_generated.py", line 11755, in connect_over_cdp
    self._sync(
  File "D:\python\lib\site-packages\playwright\_impl\_sync_base.py", line 87, in _sync
    self._dispatcher_fiber.switch()
greenlet.error: cannot switch to a different thread
```

**Comment by rwoll** [comment]
Playwright Python is not thread safe (https://playwright.dev/python/docs/intro#threading). However, you can start a playwright instance per thread like: https://github.com/microsoft/playwright-python/issues/623#issuecomment-821113328

Alternatively, you can use the async API to avoid needing multiple playwright instances: https://github.com/microsoft/playwright-python/issues/1391#issuecomment-1171793456

**Comment by D1abol1cal** [comment]
what I am trying to accomplish is very competitive and needs to be done very quickly and on the same page. I need to perform multiple actions on the same page concurrently using playright, I tried using normal pseudo python threads but I got greenlet errors and I found out that playright isn't thread safe, what would be the best approach to this?
