### ISSUE TITLE
[Feature] More `Exception` types

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright-python#1425]
Currently playwright says `playwright._impl._api_types.TimeoutError` or `playwright._impl._api_types.Error`, could you please add a lot more errors such as `NavigationError`, `SelectorNotFoundError` etc.

Use case is that I want to handle specific errors in `try`/`except` statements like so:

```py
try:
    page.click("asdf")
except SelectorNotFoundError:
    print("selector not found")
```

**Comment by rwoll** [comment]
As a work around for now, you can convert the thrown exception to a string and match based on its contents.

**Comment by mxschmitt** [comment]
Closing for now since this is not planned in the near future.
