### ISSUE TITLE
[Question]: Documentation is not clear about how to "right click" using the following snippet: await button.click() using python.

### ISSUE THREAD

**Issue by JoanEsquivel** [microsoft/playwright-python#1426]
### Your question

Hello team, 

First of all thanks for this amazing framework.

I am trying to perform a right click to an element using the following syntax:
```
button = page.locator("text=Click Me").nth(1)
await button.click(button="right")
```

I have tested the element and it is working correctly. However, I am getting an error:
```
Traceback (most recent call last):
  File "D:\repo\playwright-python-test-framework\inputs\clicks.py", line 34, in <module>
    asyncio.run(main())
  File "C:\Users\JoanPC\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\JoanPC\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "D:\repo\playwright-python-test-framework\inputs\clicks.py", line 27, in main
    await button.click(button="right")
```

Probably this is "newbie" issue. However, the [documentation](https://playwright.dev/python/docs/api/class-locator#locator-click-option-button) does not tell me what type of parameter/data type the function is expecting. It is just saying:
"button <"left"|"right"|"middle"> Defaults to left

Note: I saw the reference at the input guide [here](https://playwright.dev/python/docs/input#mouse-click)

Could you please help with this question? How I can perform a right click using that code format(without the page reference)?

I'd appreciate your help with this minor question.

Thanks again!

Joan.

**Comment by rwoll** [comment]
I tried to repro, but was unable. Can you share a repro? Ideally, a self-contained script we can run and see the same error you're seeing. Thanks!

**Comment by rwoll** [comment]
Oops…forgot the link: https://playwright.dev/python/docs/debug

**Comment by JoanEsquivel** [comment]
Appreciate your feedback, thanks!

**Comment by rwoll** [comment]
Happy to help! I've amended our docs which we had been meaning to do for a while: https://github.com/microsoft/playwright/pull/15823

The `nth` thing has tripped me (and others) on more than one occasion!
