### ISSUE TITLE
[Question]how to detect keyboard input?

### ISSUE THREAD

**Issue by yunlongYoung** [microsoft/playwright-python#1427]
Sometimes I want to detect keyboard inputs to choose which function to excute in playwright python version.
```python
if ctrl +1:
    function_1()
elif ctrl +2:
    function_2()
```
If I pressed ctrl +1 during playwright script running, it will activate function_1. Is there any way to achieve this?

**Comment by yury-s** [comment]
I assume you want to send those key strokes from terminal, if so you should look at the python documentation at how to handle user input (something like [this guide](https://www.w3schools.com/python/python_user_input.asp)).

**Comment by yunlongYoung** [comment]
@yury-s 
I want to fill some webpage forms. In sutuation 1, I will press ctrl + 1, to fill something in form. In sutuation 2, I will press ctrl + 2, to fill something else.

And I will press those keys in browser, not in the terminal. It's kind of like to use Autohotkey to fill forms in webpage.
