### ISSUE TITLE
[BUG] has_text and cyrillic symbols error

### ISSUE THREAD

**Issue by AnastasiiaPetrochenkova** [microsoft/playwright-python#1434]
**Context:**
- Playwright Version: 1.23.0
- Operating System:  Mac
- Python version: 3.8
- Browser: Chromium

We have html:
`<div class="_1TyNu" data-testid="SPECIALIZATION_SPECIALTIES_ITEM"><div color="black" class="Hqhed _1et8a _2Xtfq">Педиатр</div></div>`

Our code:
`page.locator("//div").filter(has_text="Педиатр").click()`

Error:
<img width="834" alt="Снимок экрана 2022-07-14 в 12 31 14" src="https://user-images.githubusercontent.com/94826843/178951456-7669a91d-efb0-46e9-9ab5-ce435e501684.png">

When we fill "has_text" with english letters - driver works with no problem.

When  driver can't find english text, error don't have unicode text:

`patient_choose_clinic_modal.clinic_name.filter(has_text="QA DepartmentA").click()`

<img width="851" alt="Снимок экрана 2022-07-14 в 12 44 41" src="https://user-images.githubusercontent.com/94826843/178954267-89ef218b-0710-4f03-93a2-53d52e005c19.png">

**Comment by rwoll** [comment]
Thanks for the report! That looks like an oversight on Playwright's part. We will take a look at making that error more readable
