### ISSUE TITLE
[Question]: I want to install the flash plug-in on the chorme kernel. Does playwright support this? If yes, can you tell me how to do it

### ISSUE THREAD

**Issue by zfp19961018** [microsoft/playwright-python#1438]
### Your question

I want to install the flash plug-in on the chorme kernel. Does playwright support this? If yes, can you tell me how to do it？Thank you！

**Comment by rwoll** [comment]
This is not possible. Flash was removed from Chromium, and it's no longer a setting that can be toggled.
