### ISSUE TITLE
[Question]: How to call another function before retrying click action

### ISSUE THREAD

**Issue by GTP95** [microsoft/playwright-python#1441]
### Your question

Greetings,

I'm using the synchronous version of Playwright. My script tries to execute a click action, but sometimes it fails because the elements that have to click end up being "behind" a popup that the website sometimes opens. By default, if the `click()` method fails it keeps trying to click for a certain number of times and then gives up, but without throwing an exception that I can handle. I already have a function that closes such popup, but how do I execute another function before retrying the click action?
I saw in the documentation that you have an option to check if an element can be clicked without clicking it, but the docs don't say if and what the `click()` method returns when using that option so it's not clear to me if that parameter could solve my problem and how to use it.
Thank you for the clarification,

GTP

**Comment by rwoll** [comment]
> I'm using the synchronous version of Playwright. My script tries to execute a click action, but sometimes it fails because the elements that have to click end up being "behind" a popup that the website sometimes opens. By default, if the click() method fails it keeps trying to click for a certain number of times and then gives up, but without throwing an exception that I can handle. I already have a function that closes such popup, but how do I execute another function before retrying the click action?

If you don't know whether or not the modal will suddenly appear, you can do some of your own retrying and dismiss the modal in the exception case:

```py
retries_left = 10
clicked = False
while retries_left:
  retries_left -= 1
  try:
    page.locator("text=save button").click(timeout=1000)
    print("clicked save")
    clicked = True
    break
  except Exception as e:
    page.locator("text=dismiss overlay").click()
if not clicked:
  raise Exception("failed to click target even after trying to dismiss overlay")

```

In otherwords, use Playwright's built-in autoawaiting and actionability checks with **short timeout**, if they timeout.

> I saw in the documentation that you have an option to check if an element can be clicked without clicking it, but the docs don't say if and what the click() method returns when using that option so it's not clear to me if that parameter could solve my problem and how to use it.

Are you referring to the `trial` option (https://playwright.dev/python/docs/api/class-locator#locator-click-option-trial)? If so, I don't think it's needed—just go for the click with a short timeout. If you want to use trial, use a short timeout and it will throw an error if the checks don't pass. It does not return anything based on the docs.

**Comment by rwoll** [comment]
Closing as part of triage—if the above doesn't help, please feel free to re-file/re-open. Thanks!
