### ISSUE TITLE
[docs] add refer to running in parallel

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright-python#1442]
- refer to either pytest-xdist or pytest-parallel
- make sure we work with both of them
- add docs for them

**Comment by rwoll** [comment]
Work to do:

- add some tests that ensure we work with these popular libs
- add documentation

**Comment by rwoll** [comment]
this should remain open until the docs change (https://github.com/microsoft/playwright/pull/16231) lands, too.
