### ISSUE TITLE
How can in click on a svg rect element ( a bar chart)

### ISSUE THREAD

**Issue by vivekvasu95** [microsoft/playwright-python#1450]
### Your question

How can in click on a svg rect element ( a bar chart)

**Comment by vivekvasu95** [comment]
<img width="681" alt="image" src="https://user-images.githubusercontent.com/102962308/180596813-d39c2133-189d-48aa-a523-9c3d4fb2357d.png">

**Comment by rwoll** [comment]
https://playwright.dev/python/docs/api/class-locator#locator-click should work (assuming you use a [selector](https://playwright.dev/python/docs/selectors) that points to your rectangle):

```python
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()
    page.set_content("""
    <svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
      <circle cx="100" cy="100" r="100" onclick="console.log('clicked')" />
    </svg>
    """)
    with page.expect_console_message() as msg:
      page.locator("circle").click()

    browser.close()
```

If it's no working when you expect it to, set the `PWDEBUG=1` env var and step through the test, or include the errors you are seeing here.

**Comment by rwoll** [comment]
Closing as part of triage. If the above doesn't work for you, please re-file with a repro. Thanks!
