### ISSUE TITLE
[Question]: How to handle `playwright._impl._api_types.Error: Unable to retrieve content because the page is navigating and changing the content.` ?

### ISSUE THREAD

**Issue by joe733** [microsoft/playwright-python#1454]
### Your question

Even with this check:

![image](https://user-images.githubusercontent.com/38415384/181001265-73f2af7d-cbe1-4188-8955-4d0b705cc407.png)
![image](https://user-images.githubusercontent.com/38415384/181000333-089d2f5b-eb55-4f0e-b3a6-97bdf43098f1.png)

Error happens:

![image](https://user-images.githubusercontent.com/38415384/181000897-44e0fb20-ded1-45d0-845c-29cf47524a4a.png)

Code:

https://github.com/joe733/link_finder/blob/main/scraper_js/goosebumps/spiders/larvae.py

**Comment by rwoll** [comment]
It looks like you are using a third-party lib. Please file an issue that reproduces it with Playwright code only. Thanks!

**Comment by Mattwmaster58** [comment]
@joe733 was running into the same thing, will see if I can repro here and produce a proper bug report

**Comment by joe733** [comment]
I was able to "handle" this.

[`Failure`](https://docs.twistedmatrix.com/en/stable/api/twisted.python.failure.Failure.html) is a Twisted object. It as a method called [`.check()`](https://docs.twistedmatrix.com/en/stable/api/twisted.python.failure.Failure.html#check) to which you can pass `playwright._impl._api_types.Error`, and it will return a boolean.

I'm not sure why this error is raised, but I know it happens when crawling [`https://demo.testfire.net/`](https://demo.testfire.net/)
