### ISSUE TITLE
[BUG] Don't use `implicit-optional` for type hints

### ISSUE THREAD

**Issue by KotlinIsland** [microsoft/playwright-python#1460]
**Context:**
- Playwright Version: [what Playwright version do you use?] 1.24.0
- Operating System: [e.g. Windows, Linux or Mac] N/A
- Python version: [e.g. 3.7, 3.9] 3.10
- Browser: [e.g. All, Chromium, Firefox, WebKit] N/A
- Extra: [any specific details about your environment] N/A

**Code Snippet**
```py
browser.launch(proxy=None)  # mypy error: expected "ProxySettings" found "None"
```

**Describe the bug**
```py
proxy: ProxySettings = None,
```
This should be typed as:
```py
proxy: Optional[ProxySettings] = None,
```
implicit optional is deprecated(dead in the water 💀🌊)

**Comment by rwoll** [comment]
Reference: https://github.com/python/mypy/issues/9091

**Comment by KotlinIsland** [comment]
@rwoll are emojis deprecated?

**Comment by rwoll** [comment]
In titles, yes. The title was standardized with the rest of the titles. The emoji is redundant to the `[BUG]` bit.

Thanks!

**Comment by KotlinIsland** [comment]
I like the emojis, every time I see them it puts a smile on my dial 😄
