### ISSUE TITLE
Login button is still disabled after entering credentials and does not work even when forced in playwright instance

### ISSUE THREAD

**Issue by prudhvi-liveaction** [microsoft/playwright-python#1463]
**Context:**
- Playwright Version: [1.24.0]
- Operating System: [Mac]
- Python version: [3.9]
- Browser: [All]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally.

Example: page.locator("button:has-text(\"Login\")").click()

**Describe the bug**

We have Login Button for our login page, Login button must be enabled after entering username and password and clicking it will  be logged in. But in playwright-python automation, after entering credentials the button never enables. The above code must work but it does not and above code is generated by codegen where login works but in automated running it does not.

Is it because of some security policy? blocking automated drivers? incognito mode? or something else?
Tried same thing in selenium, in there it works it work if we give driver.execute_script("argument[0].click()", login_element).

**Comment by rwoll** [comment]
Thanks for the report. Unfortunately, we'll need more information about the implementation of your login to help understand. Can you share a link to the login page and the Playwright code you are using to attempt to perform the login?

Thanks!

**Comment by prudhvi-liveaction** [comment]
Can't post link and log in credentials as it is company's IP.
I am copying and inspect element implementation of login thing here.
![Screen Shot 2022-07-29 at 12 19 39 PM](https://user-images.githubusercontent.com/34893751/181829897-dd5cd762-42bd-4169-b500-d1af648e50c1.png)

**Comment by rwoll** [comment]
Can you share a link, no login credentials? If it's just about the button becoming enabled upon entering any creds that should be sufficient

**Comment by prudhvi-liveaction** [comment]
Pasting here. but i will be deleting soon. Thanks.
https://dev.ux-dev.threateye.io/login

**Comment by rwoll** [comment]
Can you also include the snippet of Playwright code you are using to fill the form in?

**Comment by prudhvi-liveaction** [comment]
def threat():
    with sync_playwright() as initial:
        browser = initial.chromium.launch(headless=False)
        context = browser.new_context(ignore_https_errors=True, viewport={'width': 1080, 'height': 720}, bypass_csp=True)
        threat = context.new_page()
        threat.on("console", lambda msg: print(f"error: {msg.text}") if msg.type == "error" else None)
        threat.goto(URL)
        threat.wait_for_timeout(5000)
        threat.click("svg.wm-ignore-css-reset")
        threat.fill("input[placeholder=Username]", USER)
        threat.fill("input[placeholder=Password]", PASS)
        threat.wait_for_timeout(2000)
        # threat.evaluate("document.querySelector('button').disabled = false")
        # threat.pause()
        # pdb.set_trace()
        # threat.evaluate("document.querySelector('button').click()")
        # pdb.set_trace()
        threat.click(".form-wrapper")
        threat.locator("button:has-text(\"Login\")").click()
        # threat.wait_for_url("https://dev.ux-dev.threateye.io/")
        yield threat

**Comment by rwoll** [comment]
This looks like a quirk in the implementation of your login form. Since `fill` (which is like pasting) does not work, but the following does:

```python
    page.locator("input[type=\"text\"]").click()
    page.keyboard.type("u")

    page.locator("input[type=\"password\"]").click()
    page.keyboard.type("p")

    page.locator("button:has-text(\"Login\")").click()
```

I suspect your form is doing something funky with event listeners (either not registering them, registering them too late, or something else).

I recommend testing your login form in isolation and ensuring it works with `fill`.

**Comment by rwoll** [comment]
`fill` won't fire `keyup/keypress/keydown`, so if your forms logic to enable the login button is based on those events, it will not work, and that may cause issues for users using password managers or other methods of filling in the form.

**Comment by prudhvi-liveaction** [comment]
Thanks man, page.keyboard.type works!!. I will talk to dev team about forms. 

Appreciate your help!

**Comment by rwoll** [comment]
Sounds good. Closing per above
