### ISSUE TITLE
[Question]: How to make screenshot more sharp?

### ISSUE THREAD

**Issue by dlnufox** [microsoft/playwright-python#1468]
### Your question

I got a screenshot as png, while it isn't sharp as I need.

**Comment by rwoll** [comment]
You can adjust the viewport size and device scale factor before taking a screenshot (https://playwright.dev/python/docs/emulation#viewport) or picking a specific device to emulate (https://playwright.dev/python/docs/emulation#devices).

**Comment by rwoll** [comment]
Closing as part of triage and per-above advice. Please re-file if your issue is not resolved.
