### ISSUE TITLE
[Question]: How to find an element by name?

### ISSUE THREAD

**Issue by 0clickjacking0** [microsoft/playwright-python#1469]
### Your question

Encountered a scene, as follows, in the official document: https://playwright.dev/python/docs/selectors, I did not find how to locate according to the element name, in this case, how do I choose the first name is Test1 Select, xpath and css are not considered here, because there is an input to control the number, if I enter 1, then there is only one Test1; if I enter 3, then there are Test1, Test2, Test3
```
<select name="Test1">
	<option selected="selected" value="">hello</option>
</select>
```
```
<select name="Test2">
	<option selected="selected" value="">hello2</option>
</select>
```

**Comment by rwoll** [comment]
You can do:

```
page.locator("[name=Test1]").select_option("foo") # replace foo with the `value` of what you want to select
```

**Comment by 0clickjacking0** [comment]
@rwoll thanks
