### ISSUE TITLE
[BUG] Chinese garbled

### ISSUE THREAD

**Issue by DancingSnow0517** [microsoft/playwright-python#1470]
**Context:**
- Playwright Version: 1.24.0
- Operating System: Linux 
- Python version: 3.9
- Browser: All
- Extra: CentOS Linux release 7.9.2009 (Core)

**Describe the bug**

On the Chinese web page, all Chinese are displayed as garbled

![calendar](https://user-images.githubusercontent.com/60736156/182145336-1329c76e-144f-4484-b228-e78956e239e5.png)

**Comment by mxschmitt** [comment]
Most likely not all the fonts are installed, we recommend using our official Docker container: https://playwright.dev/docs/docker

or Ubuntu 18/20/22 with `npx playwright install --with-deps`

**Comment by DancingSnow0517** [comment]
How to use this docker with python？thanks

**Comment by mxschmitt** [comment]
It contains Python: https://playwright.dev/python/docs/docker
