### ISSUE TITLE
[BUG] Error bad request captcha in solicity, i don't have any response of captcha for resolve

### ISSUE THREAD

**Issue by F4KEexe** [microsoft/playwright-python#1476]
**Context:**
- Playwright Version: 1.23.0
- Operating System: Windowns
- Python version: 3.10.5
- Browser:  Chromium

```python
import asyncio
from playwright.async_api import async_playwright

async def handle_route(route):
    await route.continue_()

async def run(playwright):
    chromium = playwright.chromium
    browser = await chromium.launch(headless=False)
    page = await browser.new_page()
    await page.route("**/**", handle_route)
    await page.goto("https://accounts.hcaptcha.com/demo?sitekey=4c672d35-0701-42b2-88c3-78380b0db560")
    input()

async def main():
    async with async_playwright() as playwright:
        await run(playwright)
        
asyncio.run(main())
```

**Describe the bug**

captcha is not loading for resolve on the browser page.

![unknown](https://user-images.githubusercontent.com/93842250/182504215-311ae513-0930-4fbe-83d1-c9f3deef2b8e.png)

**Comment by rwoll** [comment]
`input()` call is blocking the event loop, so it's preventing from Playwright asyncio Tasks from completing in the background (like the routes being fulfilled).

You can replace the built-in input with an async variant like:

```py
await aioconsole.ainput("What's the code?")
```

from the third-party [aioconsole](https://github.com/vxgmichel/aioconsole) pkg.

Does this work for you?

**Comment by rwoll** [comment]
👍 closing per above

**Comment by F4KEexe** [comment]
Hi I have a question, would this work normally in an async routine as I would in a sync routine? (Input doesn't work, it hangs requests)
