### ISSUE TITLE
[Question]: How to use "playwright" in Cloud Functions on Google Cloud Platform?

### ISSUE THREAD

**Issue by taiseiyo** [microsoft/playwright-python#1491]
### Your question

When I use "playwright" in **Cloud Functions**, I get the following error: How should I deal with this? (Using **HTTP** for the trigger in **Cloud Funtions** )
```
playwright._impl._api_types.Error: Executable doesn't exist at /root/.cache/ms-playwright/chromium-1015/chrome-linux/chrome 
```

The location where the error occurs is the following part.
```
browser = playwright.chromium.launch(headless=True)
```

I changed the code as below and got an error.
```
browser = playwright.chromium.launch({channel: 'chrome'}, headless = True)
```

The requirements.txt I'm using looks like this:

```
greenlet==1.1.2
playwright==1.24.1
pyee==8.1.0
websockets==10.1
```

Also it works fine in the local environment. I am using python3.10 for both Cloud Functions and local environment.

**Comment by rwoll** [comment]
The browsers need to be installed via Playwright CLI or using a Docker container that has them pre-baked in. See https://playwright.dev/python/docs/ci#github-actions for some pointers on the commands you'd run in a CI environment to install Playwright.

However, Google Cloud Functions—if anything like AWS Serverless Functions—may have additional runtime constraints imposed by Google requiring you to use 3rd-party browser builds. See https://github.com/microsoft/playwright/issues/2404 for some pointers.

I recommend asking for help with GCP Cloud Functions in the [Community Slack](https://aka.ms/playwright-slack). Please comment here with what you find out!

Thanks!

**Comment by mcm-gr** [comment]
Did anyone find a solution here? I ran into the same issue?

**Comment by blikblum** [comment]
https://github.com/Sparticuz/chromium#usage-with-playwright

> Did anyone find a solution here? I ran into the same issue?

**Comment by AnuragHalder** [comment]
I was also facing the same issue but resolved with some iteration. You can follow these steps:

Having added the playwright and version into requirements.txt, in the main script use the subprocess module

import subprocess
subprocess.run(["playwright", "install"])

This will help install the browsers 


import subprocess
