### ISSUE TITLE
[Feature] expose `PlaywrightContextManager` explicitly in the public api

### ISSUE THREAD

**Issue by symonk** [microsoft/playwright-python#1492]
I think `PlaywrightContextManager` should be exposed in the public api rather than just the `sync_playwright` function for example, it would allow third party code to properly type their code without complaints about the type `PlaywrightContextManager` being not public.

The problem right now is that IDE/analysis tools will complain when trying to use `PlaywrightContextManager` as a type or inherit from it etc.

I'm not sure if you want the context manager to be officially exported in the public API, if not feel free to close this

**Comment by symonk** [comment]
`async` api probably needs the same treatment, happy to add if you want something like this included

**Comment by rwoll** [comment]
Can you elaborate more on your use case? Is this a hypothetical or do you have code this fixes?

**Comment by symonk** [comment]
hypothetical @rwoll but shouldn't the type of `sync_playwright` be officially public API? I think it should be defined in `__all__` explicitly for analysis tools / IDE's to not complain about importing it.

e.g:

```
'PlaywrightContextManager' is not declared in __all__
```

warnings in the ide, it's perfectly normal for client code to import that

**Comment by rwoll** [comment]
> hypothetical @rwoll but shouldn't the type of sync_playwright be officially public API? I think it should be defined in __all__ explicitly for analysis tools / IDE's to not complain about importing it.

Thanks for the clarification!

>  it's perfectly normal for client code to import that,

I haven't seen code that needs to import that type to date.

1. Many folks come in through pytest-playwright so the whole notion of the Python Context Manager is totally hidden (e.g. https://playwright.dev/python/docs/intro)
2. If using the library, it looks like https://playwright.dev/python/docs/library#usage and there is no need to import the typing

We'll collect upvotes/comments and if it comes up in non-hypothetical code, we can address

**Comment by symonk** [comment]
no worries, it is very minor right now, the above examples only target those consuming the library as-is and overlooking those maybe looking to _extend_ it, but it seems reasonable to leave it open, I am happy to implement if others want it, please tag me if you feel its worthy of exposing publically properly at some point in the future and I will look at implementing it, I am looking at building something on top of playwright and from studying the API thought it might be useful

**Comment by rwoll** [comment]
Sounds good!

> I am looking at building something on top of playwright and from studying the API thought it might be useful

Once you begin this, if exporting this type becomes are requirement, we can re-open your PR.

Thanks!
