### ISSUE TITLE
[Question]: How to tell if an element exists

### ISSUE THREAD

**Issue by zhangmingyuu** [microsoft/playwright-python#1513]
### Your question

Dear developers:
    I have a question: how to tell if an element exists, use "element_handle.is_enabled()" or "element_handle.count()"?
    I use these two methods in the following scenarios, and the situation is not ideal: when I enter a page and perform an operation, the element will disappear. At this time, I use "page.reload()" and then I want to determine whether the element has disappeared. so i use "is_enabled()" or "count()", But both methods return the error that the lookup element timed out.
Thank you.

**Comment by KotlinIsland** [comment]
Element handles aren't that great, use locators 🚀🚀🚀
```py
page.locator("AMOGNUS").is_visible()
```

**Comment by zhangmingyuu** [comment]
Thanks for your reply, I will try this method, thank you.
By the way, another question:
Is there a separate method to provide waiting, such as time.sleep(), because sometimes, I need to pause for a second to wait for an element to appear
Thank you again~

**Comment by KotlinIsland** [comment]
pausing for a second to wait for an element to appear is the worst thing you could possibly do:
```py
page.wait_for_timeout(1000)  # NEVER DO THIS!
```

Playwright has stability checks, so even if the element doesn't exist yet, attempting to click it will be fine
```py
element = page.query_selector("AMONGUS")  # capture the element handle when it exists
page.reload()
element.wait_for_element_state("detached")  # determine that the element has become detached
page.click("AMONGUS")  # playwright will wait until the element has appeared and is clickable
```

**Comment by mxschmitt** [comment]
Closing as per above. Thanks @KotlinIsland!

**Comment by abubelinha** [comment]
I am not yet familiar with playwright-python or async methods.
@mykhailo-kobylianskyi would you mind to complete a little bit your example?
Is that Python code?

I tried like this:
```
async isSelectorExists(selector: string) {
  return await this._page.$(selector).catch(() => null) !== null;
}
# ... some more code ...
str_element = 'id='+e
if not isSelectorExists(str_element):
    print("- '{}' DOES NOT EXIST in page".format(str_element))
```
 but it throws an error:
```
    async isSelectorExists(selector: string) {
          ^
SyntaxError: invalid syntax
```

**Comment by abubelinha** [comment]
My issue is perfectly described by this issue's title, but I think my scenario is a little bit different of @zhangmingyuu 's one.

What if the element I am looking for has never existed in the page yet?
Figure out a database-driven webpage, where there is a list of articles which user can edit (or add new ones). These are input elements, named like this:

```html
<textarea id="eml.description[1]">This is a test paragraph.</textarea>
<textarea id="eml.description[2]">Users could add more paragraphs.</textarea>
<textarea id="eml.description[3]">But they didn't want any more.</textarea>
```
My Python script would try to update this page grabbing paragraphs from a Python list, which could have more or fewer elements than those currently present in the page:
- `mylist1 = ["Simon","Garfunkel"]`
- `mylist2 = []`
- `mylist3 = ["John","Paul","George","Ringo"]`

In 1st and 2nd 3rd examples, the script will find all necessary elements (and remove those unnecessary ... which is a different issue).
But in the 3rd case, when it tries to find `eml.description[4]` **it wouldn't exist**.
So my script needs to detect that (and then add a new element ... but that's a different issue).

So I guess this solution wouldn't work here:
```Python
element = page.query_selector("AMONGUS") # capture the element handle when it exists 
```

@KotlinIsland do you know how to adapt it to my problem?
Thanks a lot

**Comment by KotlinIsland** [comment]
@abubelinha You aren't wrong to question @mykhailo-kobylianskyi answer, it's written in Javascript, not Python.

I might make a few stylistic changes to your function, but basically it looks solid.
```py
from playwright.sync_api import ElementHandle, Frame, Page, TimeoutError as PlaywrightTimeoutError

def selector_exists(page: Page | Frame, selector: str, timeout=500) -> ElementHandle | None:
    """Returns an ``ElementReference`` if the ``selector`` can be found within the specified ``timeout``, otherwise ``None``.
    """
    try:
        return page.wait_for_selector(selector, timeout=timeout, state='attached')
    except PlaywrightTimeoutError:
        return None

# then I am calling it like this:
elements_to_find = map(str, elem.description)
elements_present = []
elements_missing = []
for selector in elements_to_find:
    if selector_exists(page, selector=selector):
        elements_present.append(selector)
    else:
        elements_missing.append(selector)
print("\nELEMENTS PRESENT:\n", elements_present)
print("\nELEMENTS MISSING:\n", elements_missing)
```

Although in your case, if you don't need to wait the 500ms for the element to appear, then you can just write something like:
```py
# then I am calling it like this:
elements_to_find = map(str, elem.description)
elements_present = []
elements_missing = []
for selector in elements_to_find:
    if page.query_selector(selector):
        elements_present.append(selector)
    else:
        elements_missing.append(selector)
print("\nELEMENTS PRESENT:\n", elements_present)
print("\nELEMENTS MISSING:\n", elements_missing)
```

This will not wait at all for the selector though.

**Comment by abubelinha** [comment]
Thanks a lot for your answer @KotlinIsland 
I actually used `wait_for_selector` because I was getting timeout errors when using `query_selector` (after reading you above).
I thought those errors meant it was not possible to query a selector which did not exist. But probably using try-catch would have been enough (just like I later did with `wait_for_selector`).

Anyway, now that you ask if I need to wait 500 ms ... I think I could have misunderstood that timeout.
I thought that was the time I was allowing Playwright browser for loading the page (a time which I can't predict, as it depends on server load, network traffic and whatever).

Perhaps I was wrong, and Playwright always waits for the full page to load, before trying to access elements with `query_selector`?
So the intended `wait_for_selector` use is for the case when -_after_ page load- we dynamically call for _new_ elements to load? (so we must give them a certain timeout to load).

**Comment by KotlinIsland** [comment]
Playwright can wait for page loads automatically in some situations, but if you need it explicitly you can use:
https://playwright.dev/python/docs/api/class-page#page-wait-for-load-state
```py
page.wait_for_load_state("load")
```
