### ISSUE TITLE
[Question]: How to send an proper HTTP POST request?

### ISSUE THREAD

**Issue by joe733** [microsoft/playwright-python#1517]
**Code snippet**:

```python
# Script #
from playwright import sync_api

url = 'http://localhost/DVWA/vulnerabilities/exec/#'

with sync_api.sync_playwright() as spw:
    brw = spw.chromium.launch()
    cxt = brw.new_context(ignore_https_errors=True, storage_state='login.json') # session restoration IS working
    resp = cxt.request.post(url, data={'ip': 'duck.com; uname -o', 'Submit': 'Submit'}) # do I need to url_quote?
    print('GNU/Linux' in resp.text())

# Actual Output #
False

# Expected Output #
True
```

**Context & Question**

<details>

<summary>Screenshot</summary>

![Screenshot_2022-08-19_16-39-56](https://user-images.githubusercontent.com/38415384/185606174-8599dfa4-618d-40e9-a5dc-8f34144fb3e7.png)

</details>

My target is [DVWA](https://github.com/digininja/DVWA) on `localhost`. I'm aware that I can use locators to submit form, but my particular use case requires me to send a HTTP POST request. Where am I going wrong?

---

> Related:  #1009

**Comment by rwoll** [comment]
Looks like your snippet is close! Try using `form` parameter instead of `data` depending on what Content Type your backend expects. See notes on content-type throughout the various options here: https://playwright.dev/docs/api/class-apirequestcontext#api-request-context-post-option-form

**Comment by joe733** [comment]
Ooh I read past it! Keyword parameter [`form`](https://playwright.dev/python/docs/api/class-apirequestcontext#api-request-context-delete-option-form) worked! Thanks!
