### ISSUE TITLE
[BUG] Jammy images not available in advertised location

### ISSUE THREAD

**Issue by retrry** [microsoft/playwright-python#1518]
**Context:**
- Playwright Version: 1.25.0
- Operating System: macOS, Linux

**Code Snippet**

``` shell
$ docker pull mcr.microsoft.com/playwright/python:v1.25.0-jammy                                                                                                                                               
Trying to pull mcr.microsoft.com/playwright/python:v1.25.0-jammy...
Error: initializing source docker://mcr.microsoft.com/playwright/python:v1.25.0-jammy: reading manifest v1.25.0-jammy in mcr.microsoft.com/playwright/python: manifest unknown: manifest tagged by "v1.25.0-jammy" is not found
```

**Describe the bug**

Docker image should be available in advertised location, but it is not found.

**Comment by aslushnikov** [comment]
(I can repro)

**Comment by retrry** [comment]
Thanks for the fix, are you planning a release of new version, where Docker images would be available?

**Comment by mxschmitt** [comment]
We published a new version with the fix: `docker pull mcr.microsoft.com/playwright/python:v1.25.2-jammy`

**Comment by retrry** [comment]
@mxschmitt thanks!
