### ISSUE TITLE
[Question]: how to keep the browser running after the programme ends or catch an exception?

### ISSUE THREAD

**Issue by sontiq** [microsoft/playwright-python#1522]
### Your question

a  browser would be closed  after the programme ends or catch an exception;  however, i want to keep the browser running .   how?

**Comment by rwoll** [comment]
Can you elaborate on your use case? Are you running your code in pytest or a generic script?

Either way, to prevent your script from crashing, you can put your code that may throw in a `try`/`except` block like other Python programs.

To prevent the script from exiting and the browser closing, you can add:

```py
while True:
    page.wait_for_timeout(10000)
```

to effectively hang your script before calling `browser.close`. To get out of the loop you can look into interrupt handlers in Python.
