### ISSUE TITLE
[BUG] Browser started by playwright is blocking dropboxcaptcha.com and prevents login to dropbox

### ISSUE THREAD

**Issue by florinb-cyberhaven** [microsoft/playwright-python#1525]
**Context:**
- Playwright Version: 1.25.0
- Operating System: Win 10
- Python version: 3.10
- Browser: Chromium and Chrome

**Code Snippet**

Reproduces both ways (new_context/launch_persistent_context)

```python
self._playwright = sync_playwright().start()

self._browser = self._playwright.chromium.launch(headless=False)
self._browser_context = self._browser.new_context(storage_state=STATE_FILE)
or 
self._browser_context = self._playwright.chromium.launch_persistent_context(user_data_dir="user_data", headless=False)
```

Only way that the issue doesn't reproduce is if I pass ignore_default_args=True to launch_persistent_context, but I get other errors in that case so it's not a solution.

**Describe the bug**

`Your browser appears to be blocking dropboxcaptcha.com, which is required for authentication. To resolve this issue, please update any anti-virus or ad-blocking software settings to allow connections to dropboxcaptcha.com`

![image](https://user-images.githubusercontent.com/103565209/186099237-31ec78b8-605d-466e-b145-4c53654b4439.png)

**Comment by rwoll** [comment]
Playwright is focused on testing, and it's assumed you control the sites you test and they do not block Playwright. 

A site may choose to detect and block Playwright and we respect that.
