### ISSUE TITLE
[Question]: How can i grab a spesific network event and assign it to a variable?

### ISSUE THREAD

**Issue by oktayozkan0** [microsoft/playwright-python#1526]
### Your question

Hello. I want to grab a spesific url from network events and assign to a variable the url's response.
In documentation there is a solution like this:
`page.on("response", lambda response: print("<<", response.status, response.url))`
but this is not enough for me. 
Can you help me?

**Comment by rwoll** [comment]
Thanks for the question. Can you elaborate on your context?

1. Are you doing this in a pytest or a generic script?
2. async or sync version of Playwright? 

The snippet here shows using expect_reponse and assigning it to a variable: https://playwright.dev/python/docs/api/class-page#page-wait-for-response

**Comment by oktayozkan0** [comment]
> Thanks for the question. Can you elaborate on your context?
> 
> 1. Are you doing this in a pytest or a generic script?
> 2. async or sync version of Playwright?
> 
> The snippet here shows using expect_reponse and assigning it to a variable: https://playwright.dev/python/docs/api/class-page#page-wait-for-response

hello rwoll. thanks for the answer. 
im doing this in a generic script.
sync version of playwright.

i want to scrape a website. the website has api but hard to access it (too many tokens and session-ids) for this reason im navigating to website with playwright and listening the responses. 
https://playwright.dev/python/docs/api/class-page#page-wait-for-response
this link would help me i guess. thank you so much.
