### ISSUE TITLE
[Feature] Websockets requirement is too strict

### ISSUE THREAD

**Issue by Uninen** [microsoft/playwright-python#1535]
Playwright currently depends on `websockets==10.1` which is now already two minor versions behind and several other packages require fresher versions which causes head aches when trying to install Playwright. Could this requirement be loosened to allow easier installs?

**Comment by mxschmitt** [comment]
Sounds like also fixed by https://github.com/microsoft/playwright-python/issues/1177.

**Comment by Uninen** [comment]
Um, in which way is this completed? The linked ticket is open and labelled "P3-collecting-feedback", and the root issue still exists.

Is there a workaround where I could install playwright-python in a project that has newer websockets requirement?
