### ISSUE TITLE
Can't register custom selectors using sync API

### ISSUE THREAD

**Issue by fj201314** [microsoft/playwright-python#1537]
### Your question

Official case selectors The synchronization API of register (name, * * kwargs) reports an error

**Comment by fj201314** [comment]
Traceback (most recent call last):
  File "C:/pycharm/project/pythonProject/playwrightDemo/SerialCase/vpc/Case.py", line 32, in <module>
    run(playwright)
  File "C:/pycharm/project/pythonProject/playwrightDemo/SerialCase/vpc/Case.py", line 17, in run
    playwright.selectors.register("tag", tag_selector)
  File "C:\pycharm\project\pythonProject\playwrightDemo\venv\lib\site-packages\playwright\sync_api\_generated.py", line 11939, in selectors
    return mapping.from_impl(self._impl_obj.selectors)
  File "C:\pycharm\project\pythonProject\playwrightDemo\venv\lib\site-packages\playwright\_impl\_impl_to_api_mapping.py", line 73, in from_impl
    result = self.from_maybe_impl(obj)
  File "C:\pycharm\project\pythonProject\playwrightDemo\venv\lib\site-packages\playwright\_impl\_impl_to_api_mapping.py", line 65, in from_maybe_impl
    api_instance = api_class(obj)
  File "C:\pycharm\project\pythonProject\playwrightDemo\venv\lib\site-packages\playwright\_impl\_sync_base.py", line 72, in __init__
    self._dispatcher_fiber = impl_obj._dispatcher_fiber
AttributeError: 'Selectors' object has no attribute '_dispatcher_fiber'

**Comment by fj201314** [comment]
selectors.register(name, **kwargs)

mine:
Playwright Version: 1.22.0
Operating System: Windows 11
Python version: 3.8.10
Browser: Chromium

**Comment by mxschmitt** [comment]
could you share a repro script with us? Since our tests are passing for us.

**Comment by fj201314** [comment]
from playwright.sync_api import sync_playwright

def run(playwright):
    tag_selector = """
      {
          // Returns the first element matching given selector in the root's subtree.
          query(root, selector) {
              return root.querySelector(selector);
          },
          // Returns all elements matching given selector in the root's subtree.
          queryAll(root, selector) {
              return Array.from(root.querySelectorAll(selector));
          }
      }"""

    # Register the engine. Selectors will be prefixed with "tag=".
    playwright.selectors.register("tag", tag_selector)
    browser = playwright.chromium.launch()
    page = browser.new_page()
    page.set_content('<div><button>Click me</button></div>')

    # Use the selector prefixed with its name.
    button = page.locator('tag=button')
    # Combine it with other selector engines.
    page.locator('tag=div >> text="Click me"').click()
    # Can use it in any methods supporting selectors.
    button_count = page.locator('tag=button').count()
    print(button_count)
    browser.close()

with sync_playwright() as playwright:
    run(playwright)

**Comment by mxschmitt** [comment]
I tried to run it but it works fine for me, are you sure that you are using 1.25?

Could you try: `python -c "from playwright._repo_version import version; print(version)"` which will log the version.

**Comment by fj201314** [comment]
yes playwright's verison=1.22.0

**Comment by fj201314** [comment]
Playwright Version: 1.22.0
Operating System: Windows 11
Python version: 3.8.10
Browser: Chromium

**Comment by mxschmitt** [comment]
can you update to 1.25? The issue was fixed in 1.23.

**Comment by fj201314** [comment]
OK, no problem. I'll try

**Comment by fj201314** [comment]
Yes, the version problem has been solved. I thought the version after 1.8 would be OK

**Comment by fj201314** [comment]
thank you
