### ISSUE TITLE
[Question]: Modifying Request Form Data

### ISSUE THREAD

**Issue by Vinyzu** [microsoft/playwright-python#1538]
### Your question

Code:
```py
async def mock_json(route, request):
            test = list(request.post_data_json.items())
            print(test == urllib.parse.parse_qsl(request.post_data)) # True
            encoded = urllib.parse.urlencode(test)
            print(encoded == request.post_data) # False
            await route.continue_(post_data=str(encoded)) # Invalid Form Data

await page.route("https://example.com/*", mock_json)
```
Basicly i want to modify the request post data by modifying its json equivalent (request.post_data_json).
However, i cant figure out how to encode a Dictionary in such way that it is equal to the request.post_data equivalent, and therefore a valid form data.
As you can see in my Code example, im decoding the `request.post_data` with parse_qsl, and it is the equivalent to the `request.post_data_json.items()`.
When i urlencode the dict, it is not the same with the `request.post_data` anymore.
So im wondering how i should encode my dict.

**Comment by Vinyzu** [comment]
Note: Im using Firefox

**Comment by Vinyzu** [comment]
Update:
even passing data=request.post_data
Gives me a forbidden request error

**Comment by mxschmitt** [comment]
Is your request payload now json or query string form data?

I recommend to set e.g. a `breakpoint()` statement or a breakpoint in your IDE to debug that further!

**Comment by Vinyzu** [comment]
Its form data. (at least thats what the browser request logger says)

**Comment by mxschmitt** [comment]
Then you can use `parse.parse_qsl` and [`urllib.urlencode`](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlencode) like you already do.

Lets maybe log `encoded` and `request.post_data` to compare them manually?

Try to add a `breakpoint()` which will give you a handy repl: https://docs.python.org/3/library/functions.html#breakpoint

**Comment by Vinyzu** [comment]
Code:
```py
async def mock_json(route, request):
    print(request.post_data)
    print(urllib.parse.urlencode(urllib.parse.parse_qsl(request.post_data)))
    await route.continue_()
```
PostData:
v=1f7dc62&sitekey=4c672d35-0701-42b2-88c3-78380b0db560&host=accounts.hcaptcha.com&hl=en&motionData=%7B%22st%22%3A1662372394281%2C%22mm%22%3A%5B%5B34%2C40%2C1662372396208%5D%5D%2C%22mm-mp%22%3A0%2C%22md%22%3A%5B%5B34%2C40%2C1662372396209%5D%5D%2C%22md-mp%22%3A0%2C%22mu%22%3A%5B%5B34%2C40%2C1662372396285%5D%5D%2C%22mu-mp%22%3A0%2C%22v%22%3A1%2C%22topLevel%22%3A%7B%22inv%22%3Afalse%2C%22st%22%3A1662372394059%2C%22sc%22%3A%7B%22availWidth%22%3A1295%2C%22availHeight%22%3A830%2C%22width%22%3A1295%2C%22height%22%3A830%2C%22colorDepth%22%3A24%2C%22pixelDepth%22%3A24%2C%22top%22%3A0%2C%22left%22%3A0%2C%22availTop%22%3A0%2C%22availLeft%22%3A0%2C%22mozOrientation%22%3A%22landscape-primary%22%2C%22onmozorientationchange%22%3Anull%7D%2C%22nv%22%3A%7B%22permissions%22%3A%7B%7D%2C%22pdfViewerEnabled%22%3Afalse%2C%22doNotTrack%22%3A%22unspecified%22%2C%22maxTouchPoints%22%3A0%2C%22mediaCapabilities%22%3A%7B%7D%2C%22oscpu%22%3A%22Windows%20NT%2010.0%3B%20Win64%3B%20x64%22%2C%22vendor%22%3A%22%22%2C%22vendorSub%22%3A%22%22%2C%22productSub%22%3A%2220100101%22%2C%22cookieEnabled%22%3Atrue%2C%22buildID%22%3A%2220181001000000%22%2C%22serviceWorker%22%3A%7B%7D%2C%22credentials%22%3A%7B%7D%2C%22clipboard%22%3A%7B%7D%2C%22mediaSession%22%3A%7B%7D%2C%22hardwareConcurrency%22%3A12%2C%22geolocation%22%3A%7B%7D%2C%22appCodeName%22%3A%22Mozilla%22%2C%22appName%22%3A%22Netscape%22%2C%22appVersion%22%3A%225.0%20(Windows)%22%2C%22platform%22%3A%22Win32%22%2C%22userAgent%22%3A%22Mozilla%2F5.0%20(Windows%20NT%2010.0%3B%20Win64%3B%20x64%3B%20rv%3A103.0)%20Gecko%2F20100101%20Firefox%2F103.0%22%2C%22product%22%3A%22Gecko%22%2C%22language%22%3A%22en-US%22%2C%22languages%22%3A%5B%22en-US%22%5D%2C%22locks%22%3A%7B%7D%2C%22onLine%22%3Atrue%2C%22storage%22%3A%7B%7D%2C%22plugins%22%3A%5B%22internal-pdf-viewer%22%2C%22mhjfbmdgcfjbbpaeojofohoefgiehjai%22%2C%22internal-nacl-plugin%22%5D%7D%2C%22dr%22%3A%22%22%2C%22exec%22%3Afalse%2C%22wn%22%3A%5B%5B1295%2C830%2C1%2C1662372394059%5D%5D%2C%22wn-mp%22%3A0%2C%22xy%22%3A%5B%5B0%2C0%2C1%2C1662372394059%5D%5D%2C%22xy-mp%22%3A0%2C%22mu%22%3A%5B%5B672%2C395%2C1662372394062%5D%5D%2C%22mu-mp%22%3A0%2C%22mm%22%3A%5B%5B673%2C394%2C1662372394077%5D%2C%5B674%2C394%2C1662372394169%5D%5D%2C%22mm-mp%22%3A92%7D%2C%22session%22%3A%5B%5D%2C%22widgetList%22%3A%5B%220e8s9m6i2lvg%22%5D%2C%22widgetId%22%3A%220e8s9m6i2lvg%22%2C%22href%22%3A%22https%3A%2F%2Faccounts.hcaptcha.com%2Fdemo%3Fsitekey%3D4c672d35-0701-42b2-88c3-78380b0db560%22%2C%22prev%22%3A%7B%22escaped%22%3Afalse%2C%22passed%22%3Afalse%2C%22expiredChallenge%22%3Afalse%2C%22expiredResponse%22%3Afalse%7D%7D&n=dd98e8391d4fe388694f29db6eec8775f52d30348040b5d8aa0402a2420722a9fb134190af1fb46e09e0e3a062b77fdf26c67109faeefdd3196ed09d0839909caaefc21964a24b7711b1530f6fb40e916a1906a14390a7695b004651f0c6f23e73686515906f0cd3b168b3a19f654674dac3b087d884e7016c3ec6c9b08142d1ef92cce612ac255cd5fe0801d144417fa5aed4262b6ef5820bccab63b125507ef6a8a9121f96d6990a51ef05f26768457387ec1b191c285a32abf8cba3d40802aa9cf93f0518efeddbec6276e25fc4cdc5ab311d16f2867c6981a69c9d1f70befc6c75bad465d93f0d938e330910021bdf4313383be3ff7e67667798bb3b1711bf0f3a494affe5a6849a06988eba2391c48ea5d4e33817dd33fba3d8a2620fd659c21a552ded4ced9a05a5f2108177015b1bdf7fff6f013425e562dec09de83833d3e64a71104fb1a66c52d510833be62092fae796e77e6edceb5e5f56cf8a0b416ebfa2ceac6a512873e07b3c6aa248ece31e7812dfcbc66c4da53b2616a78217d0e28aab033e03166c0506cc899e445a105bb8a0041bf50e2333e5130a528f7cfa60f2a9c10e9f415a15b4dbe5cbca29d47012c161a8baa19a613562d43f6c8812720f2d973d4ffe8205a74a3b582cdddab3fac68b7fb96fcce423c4cfaf714d2596c9359ddc5b9e63af6560d544628d0ea9b4b4e7ba8aebb12504d128c9dc42e48a8d10b0dd3246676b89e16d4a45211b73b27fd2cc0b4ad475a7e10dd1c30ee7fd7b3eecdf97cc00b23e68b7564c998e1a432cd3a2750dcdc47a35ad60696c708b3f30a573602c0e479e546cca00ce2b098f0e6149bdc08a7eae0ee1070094ee936e759b8c5ba805a640657ce3fa1e81fa776eb63e6184af20d854c2a53bb929482a297043de6b7bf75879270999bfe7e7cdc55c7b209ffada6a95fbee86fd8397c78c93d6ec4b8e015b4bc41b842bee1c25910f9396bedf135cadabf5e56e74e08e7f8b22f612b32cb5951670485feef4445da83a03860d44777cabce20eecb008c23041f03bc98c501176b119df5bd85959fcde700ac6a0c633a2e82a7cc12216d973b14004eaac352127888637bac9cbc1e20ef3a50c5cf3b8a9aa1cbc1827c0f236f18f0ad75f02838881d574529606e95a83aeab93685add3006699d0c71cd814c3ef5679029bae00a01bed741f2ee2c8beb77c66e2039fd9e3348e95553c60d4d3c3a5f831acf72b1c9c52113b3aa1ba6b5c7ee9040f38efb1b9ce7df00a084d1fcc3db184b60b6bed653bbdf5cdec061835b70f7e8f74dbcc178fc81d018984bcfd31d5deac7ebb77dc2ead66d298312bd7b6294a97b0e995c25a4b606c3f667888a2910f7a792a44403d63e17376c4eab3c7ffb90e6e350267c59ff79b0a14ea934fd0c5b4966335b5e1be5529abe70a71a875a8a49a672aac31bad1b25145d59dfb87f21df9674b3a82e8edbbee888a1a7b70846b755cc0dc30efa7ff47f615309a26f28847840b0340356a9f709fc934476b1e851a24b1c9bd51ca8bbe075bc016746108436d245faa686861aabacaed65113d2642e6b2401715b214a4e8789e5512fa83e5d4144bde7d555cd0ca928fa11b7ffdd1b196d6622091e791f0547847e4d4a95671c9c25086f28105268584b5ff11902c149433ca2e69863e1d675bb4b61e4efea9a26d2555c566cb02597bcd7e6b1dcf478b9c772805eff571b6d4e4ba967670b7fe9d0fd665fe7d67b58c20b7d45bf796776127bbb968662d3629b8fc74950d53159ff69892316b8839e702840b649722eba6e4b46d4fe32fd72345ef96013c162a719ca5f2dc5b66a7fc5297db01e7f1f334af37ac69e596393d63fa0f499d0f080379bdc1ae0de781da3e1d70d6b18eee7b97a1cd119eb81837bf6f5dfc34a9dd0fde0cc1d324cbc6d3fe44edf126966b051e71b7792a847f97cef88f605cbcb4bd1c3fbd3c1861aba472ef8cd7a99c703e555169b248ec25f8bfe47fd604036152c26d6f42f70644b372d46c50bf307f4b524d531c18613b59433a977be2b46db6bc406587f06577cbbf647bf3434e2523a184a7844080b953d02b35d5f37618bec5469e281a021fca32009e796ddd29f7709b50c110905583f312d3e01f83c3b211709e1650ba2182a382803f47bdc44659c8fdb14630b56514b5d507f9ecbf3c134deb5f09c29692f49956735a58b04a252e852601e5ed3074049d46cf2f5e76ec89e97c8e0654e59016a89fee1fc12a1c1bb3b81256ab1315a80d882261e7a65982bc7907aad4289806c60a2ab0bcea44231b828cee32cfa6106e1d7c58a670055605ee0ef09cf2a0debac621f973f654babd0c6472efc193501cf22460c3c999e504c732060d425a2bf2b0d6db317fe6d61b5bef38dba01c248bef44b7c1edf35559bf177367b0d2a93ad15a74a41caca0164b816ed5f636b9733e675c41e6ffb5951f8001a392778b3b63e0ff651d4b72d668da4ec7146b44b6e7f0916ed445ad7e6d8d6b45671fafead9a70a2d4f7e3a55e96ff24da1f35d4c34b29a3d599c9884f18cc736382a7ed4d2f29fb9b8010bda31d4c5549c45cce28942e52166dcbfff76f7e91672afc4459ec352adf8b67e939378b4854734174831091522e6de247a417f850243f1f43cd5bf351982dc9efaf0971dc5b0776d7833803b9c1b94f383d878d4bef7375bdd7460584d5ba9868525bd706507c9ecf52679c01f492052b1e02ddaf7280ef3039a21c9ac7caed7cd17ab214fa1784b7a4ee3260258f3692069613407e3a37fa61bd931697f818703279e7c4ab55687c3f46ab285364b3c2c508aa5c175c8f97bc9c6c87c00817b27b7b6d17f8881846ac01d1f8361eb49e44b044e4f95573120da51c85d7eb5cbd7a88d2622b80b0c04c04b7652170147a63d8ad271cdf9870c0d1ea212d78bd400a490ece9b9cc4dce87967ea2a7bfd3e02f356ea75ebff0e28955724cf21f072c238d47dbc1bb4d05edb904e3bded692d479f1df874ad7462b6fbeef227e2f948595409d79983e6774dc2ca46da726a6d07ee165686fb2625b3e69f32eaf99b1e89223ad94ed9735fc29d5e38de8720943f7ca2827d487ca2323cdf66c0c3adf91b68fb3371bb7fcae1a86dd54c9259ab7cd71ae9c7405948b2986b8d7b849f1cf7ec6c5152e12f681520f2d2b943fc6b6a69f09f2476ec01eb2b810c9bc53dfc51a95b327ef86dee5d86def5a1ea64c31bc772a8125d8238eb84b58c3b2a919acdd35a0c5df07cbe4c72e42627f757bff0c9840e9394e326c3b1fb8567361468d47f20cea6814a8361b73da30201b1d3b34ea2f2fb9e35acac996810d0c0fe9f646963c2463f9d0bcf46a66180e40b202f8439b1c28f643cb96a0e2ec1e232f49f269605cc941bbb94962e75074e5f9b1f4173b3afeb8d0ce59bfcff813ce6604f8ac943cdfe6dce91b592eb416de86471028586f678f703cc100e891b0cc4cea24e333a6f0850ff096400eb8ea713579eab4005a33822de40aa229c93ec2c37029f4a554629f9de91aa06f4809c169d6f6239ffcfd9ddd34e5138d86e0cc73a6ac9871520454251bbb8ff7787fed3cb8ca0ad27f4eb26c8f18ca9b79ae238fdb6211f9849bde989edb4a06e1e1a4c35057b6abe42ea2344eca19f2e4deb476efc1a20ddd3f7e64219f10fd658994ed18d652bf92a591ebfe04f1bd960ed47270d120ca5b7dc6e2c627bb32e9b336c619d6bbb548eee65a69183aefb50244eaceec50003ef3dc4df3464cf3a10933e74101a9a37bba3d5a1ea3863a512e5a7b3e1fea757a56bdfd5ec411cd6748d027442d82bc98afc97cf9da435e20d4d6ca2308cfd1daa716437fd936c34c632fa1b929e2a91bbdcb7cd53177b6f1842881dcdc8b220531298a56e6d35e3132f8e5245945aa0ab7c6f4a28dd2133d25e23eb5095996571056e0b5e4bf73c2967031ab9464ccf7c1c7eaf2ab510ba34547538c1124db37a74a8a0f337c54aceb90a07dca232f0ddfcc8b8870e6a7a1c2c017146f1ee39eb82f5cbfbf171a32b31076c7de055083d4215d72b4c6a90e872d9ed561b20fa4d2db3a9c775ee7a7068ca497d8ab119b29852b599279b457e2a0e9172b6f1b83bd29f3cda06739f16ee4b390bc42cfc309f32edebb2d7b7476c83780a52244f2e2da31da96d154bb2dc47a15f10ca597fe992dfffb613111eea754c5d0f3a0a89db973f7c46943071acdb4833da648ae522c09605aa6dc5b58cd60bd4adb815333abff11c8a3b22c3cf76d4c3e6905fc1a7d235201974e50338a292cd7fc3327fb672065d53a02f1820bf7e1807cec7eeae1f8e53dbda9a8adccbc7d2e51cbb6472bacbfc7d1cbf8c5bf59dcafece6d6db754be17c2f764921b3aaa2417d4ee51fb7bf9ad984273ae36ef074cb71da64ec83853c9b199c5e43b145d4a02448d337f16ba0f83d8cf7c510222cebc8f70e900deade9011e1263ee38322a4051467c95ef0c1e7876137b25c0bf4b111f909a80470f3649dcd2a0c0d8aab9ad4d46c8f1b2f3f50e65e5f118f74af3b9854b97ab8a80b24909e853a2c82d855495e385019f56bd53cc9efa90450a32d0c64ced20277ec6f86c8f64d2383829c4a8719e45619e67631a2bf06e68e181b32c04697b80242e55c51b8b0b7170531dc9abc68d6f449d839bc8943585bca42ed800403e474a708ced765c9c54dad782303e010f9b692602200ece611d8063f460d5c36700&c=%7B%22type%22%3A%22hsw%22%2C%22req%22%3A%22eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmIjowLCJzIjoyLCJ0IjoidyIsImQiOiIzaG5Cb25acEs4QVAwMmNZR1U2Wi9QVkFaZ2NObGd2djNnQ2RlaTBEaTdsTG1BeTZEN0tPN1lYUWkwVURhY0xMTnViY0tqYWxSTGxaR1RtSXpKK3Fuc29lRnUybE53YjVFWkRtN0ExSHp3ek1pRjdmRGZRR0RGd1RMaWtRcThpVGV2Rk9FQ2t3OU9rNWtTTUpmTVBzMUlweHI4NlhvRW9nOERzd0huM3NUM1hIVjlnR1p0aHQ3bmhZUlE9PU05Q3NURjZUUmRzK1FEVzIiLCJsIjoiaHR0cHM6Ly9uZXdhc3NldHMuaGNhcHRjaGEuY29tL2MvOGRjMTU4N2QiLCJlIjoxNjYyMzcyNjM0LCJuIjoiaHN3In0.Lu--lyOUGo5AA6L5sino5DP90sp8E7MYpssu5DPkf9A%22%7D

urllib.parse.urlencode:
v=1f7dc62&sitekey=4c672d35-0701-42b2-88c3-78380b0db560&host=accounts.hcaptcha.com&hl=en&motionData=%7B%22st%22%3A1662372394281%2C%22mm%22%3A%5B%5B34%2C40%2C1662372396208%5D%5D%2C%22mm-mp%22%3A0%2C%22md%22%3A%5B%5B34%2C40%2C1662372396209%5D%5D%2C%22md-mp%22%3A0%2C%22mu%22%3A%5B%5B34%2C40%2C1662372396285%5D%5D%2C%22mu-mp%22%3A0%2C%22v%22%3A1%2C%22topLevel%22%3A%7B%22inv%22%3Afalse%2C%22st%22%3A1662372394059%2C%22sc%22%3A%7B%22availWidth%22%3A1295%2C%22availHeight%22%3A830%2C%22width%22%3A1295%2C%22height%22%3A830%2C%22colorDepth%22%3A24%2C%22pixelDepth%22%3A24%2C%22top%22%3A0%2C%22left%22%3A0%2C%22availTop%22%3A0%2C%22availLeft%22%3A0%2C%22mozOrientation%22%3A%22landscape-primary%22%2C%22onmozorientationchange%22%3Anull%7D%2C%22nv%22%3A%7B%22permissions%22%3A%7B%7D%2C%22pdfViewerEnabled%22%3Afalse%2C%22doNotTrack%22%3A%22unspecified%22%2C%22maxTouchPoints%22%3A0%2C%22mediaCapabilities%22%3A%7B%7D%2C%22oscpu%22%3A%22Windows+NT+10.0%3B+Win64%3B+x64%22%2C%22vendor%22%3A%22%22%2C%22vendorSub%22%3A%22%22%2C%22productSub%22%3A%2220100101%22%2C%22cookieEnabled%22%3Atrue%2C%22buildID%22%3A%2220181001000000%22%2C%22serviceWorker%22%3A%7B%7D%2C%22credentials%22%3A%7B%7D%2C%22clipboard%22%3A%7B%7D%2C%22mediaSession%22%3A%7B%7D%2C%22hardwareConcurrency%22%3A12%2C%22geolocation%22%3A%7B%7D%2C%22appCodeName%22%3A%22Mozilla%22%2C%22appName%22%3A%22Netscape%22%2C%22appVersion%22%3A%225.0+%28Windows%29%22%2C%22platform%22%3A%22Win32%22%2C%22userAgent%22%3A%22Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%3B+rv%3A103.0%29+Gecko%2F20100101+Firefox%2F103.0%22%2C%22product%22%3A%22Gecko%22%2C%22language%22%3A%22en-US%22%2C%22languages%22%3A%5B%22en-US%22%5D%2C%22locks%22%3A%7B%7D%2C%22onLine%22%3Atrue%2C%22storage%22%3A%7B%7D%2C%22plugins%22%3A%5B%22internal-pdf-viewer%22%2C%22mhjfbmdgcfjbbpaeojofohoefgiehjai%22%2C%22internal-nacl-plugin%22%5D%7D%2C%22dr%22%3A%22%22%2C%22exec%22%3Afalse%2C%22wn%22%3A%5B%5B1295%2C830%2C1%2C1662372394059%5D%5D%2C%22wn-mp%22%3A0%2C%22xy%22%3A%5B%5B0%2C0%2C1%2C1662372394059%5D%5D%2C%22xy-mp%22%3A0%2C%22mu%22%3A%5B%5B672%2C395%2C1662372394062%5D%5D%2C%22mu-mp%22%3A0%2C%22mm%22%3A%5B%5B673%2C394%2C1662372394077%5D%2C%5B674%2C394%2C1662372394169%5D%5D%2C%22mm-mp%22%3A92%7D%2C%22session%22%3A%5B%5D%2C%22widgetList%22%3A%5B%220e8s9m6i2lvg%22%5D%2C%22widgetId%22%3A%220e8s9m6i2lvg%22%2C%22href%22%3A%22https%3A%2F%2Faccounts.hcaptcha.com%2Fdemo%3Fsitekey%3D4c672d35-0701-42b2-88c3-78380b0db560%22%2C%22prev%22%3A%7B%22escaped%22%3Afalse%2C%22passed%22%3Afalse%2C%22expiredChallenge%22%3Afalse%2C%22expiredResponse%22%3Afalse%7D%7D&n=dd98e8391d4fe388694f29db6eec8775f52d30348040b5d8aa0402a2420722a9fb134190af1fb46e09e0e3a062b77fdf26c67109faeefdd3196ed09d0839909caaefc21964a24b7711b1530f6fb40e916a1906a14390a7695b004651f0c6f23e73686515906f0cd3b168b3a19f654674dac3b087d884e7016c3ec6c9b08142d1ef92cce612ac255cd5fe0801d144417fa5aed4262b6ef5820bccab63b125507ef6a8a9121f96d6990a51ef05f26768457387ec1b191c285a32abf8cba3d40802aa9cf93f0518efeddbec6276e25fc4cdc5ab311d16f2867c6981a69c9d1f70befc6c75bad465d93f0d938e330910021bdf4313383be3ff7e67667798bb3b1711bf0f3a494affe5a6849a06988eba2391c48ea5d4e33817dd33fba3d8a2620fd659c21a552ded4ced9a05a5f2108177015b1bdf7fff6f013425e562dec09de83833d3e64a71104fb1a66c52d510833be62092fae796e77e6edceb5e5f56cf8a0b416ebfa2ceac6a512873e07b3c6aa248ece31e7812dfcbc66c4da53b2616a78217d0e28aab033e03166c0506cc899e445a105bb8a0041bf50e2333e5130a528f7cfa60f2a9c10e9f415a15b4dbe5cbca29d47012c161a8baa19a613562d43f6c8812720f2d973d4ffe8205a74a3b582cdddab3fac68b7fb96fcce423c4cfaf714d2596c9359ddc5b9e63af6560d544628d0ea9b4b4e7ba8aebb12504d128c9dc42e48a8d10b0dd3246676b89e16d4a45211b73b27fd2cc0b4ad475a7e10dd1c30ee7fd7b3eecdf97cc00b23e68b7564c998e1a432cd3a2750dcdc47a35ad60696c708b3f30a573602c0e479e546cca00ce2b098f0e6149bdc08a7eae0ee1070094ee936e759b8c5ba805a640657ce3fa1e81fa776eb63e6184af20d854c2a53bb929482a297043de6b7bf75879270999bfe7e7cdc55c7b209ffada6a95fbee86fd8397c78c93d6ec4b8e015b4bc41b842bee1c25910f9396bedf135cadabf5e56e74e08e7f8b22f612b32cb5951670485feef4445da83a03860d44777cabce20eecb008c23041f03bc98c501176b119df5bd85959fcde700ac6a0c633a2e82a7cc12216d973b14004eaac352127888637bac9cbc1e20ef3a50c5cf3b8a9aa1cbc1827c0f236f18f0ad75f02838881d574529606e95a83aeab93685add3006699d0c71cd814c3ef5679029bae00a01bed741f2ee2c8beb77c66e2039fd9e3348e95553c60d4d3c3a5f831acf72b1c9c52113b3aa1ba6b5c7ee9040f38efb1b9ce7df00a084d1fcc3db184b60b6bed653bbdf5cdec061835b70f7e8f74dbcc178fc81d018984bcfd31d5deac7ebb77dc2ead66d298312bd7b6294a97b0e995c25a4b606c3f667888a2910f7a792a44403d63e17376c4eab3c7ffb90e6e350267c59ff79b0a14ea934fd0c5b4966335b5e1be5529abe70a71a875a8a49a672aac31bad1b25145d59dfb87f21df9674b3a82e8edbbee888a1a7b70846b755cc0dc30efa7ff47f615309a26f28847840b0340356a9f709fc934476b1e851a24b1c9bd51ca8bbe075bc016746108436d245faa686861aabacaed65113d2642e6b2401715b214a4e8789e5512fa83e5d4144bde7d555cd0ca928fa11b7ffdd1b196d6622091e791f0547847e4d4a95671c9c25086f28105268584b5ff11902c149433ca2e69863e1d675bb4b61e4efea9a26d2555c566cb02597bcd7e6b1dcf478b9c772805eff571b6d4e4ba967670b7fe9d0fd665fe7d67b58c20b7d45bf796776127bbb968662d3629b8fc74950d53159ff69892316b8839e702840b649722eba6e4b46d4fe32fd72345ef96013c162a719ca5f2dc5b66a7fc5297db01e7f1f334af37ac69e596393d63fa0f499d0f080379bdc1ae0de781da3e1d70d6b18eee7b97a1cd119eb81837bf6f5dfc34a9dd0fde0cc1d324cbc6d3fe44edf126966b051e71b7792a847f97cef88f605cbcb4bd1c3fbd3c1861aba472ef8cd7a99c703e555169b248ec25f8bfe47fd604036152c26d6f42f70644b372d46c50bf307f4b524d531c18613b59433a977be2b46db6bc406587f06577cbbf647bf3434e2523a184a7844080b953d02b35d5f37618bec5469e281a021fca32009e796ddd29f7709b50c110905583f312d3e01f83c3b211709e1650ba2182a382803f47bdc44659c8fdb14630b56514b5d507f9ecbf3c134deb5f09c29692f49956735a58b04a252e852601e5ed3074049d46cf2f5e76ec89e97c8e0654e59016a89fee1fc12a1c1bb3b81256ab1315a80d882261e7a65982bc7907aad4289806c60a2ab0bcea44231b828cee32cfa6106e1d7c58a670055605ee0ef09cf2a0debac621f973f654babd0c6472efc193501cf22460c3c999e504c732060d425a2bf2b0d6db317fe6d61b5bef38dba01c248bef44b7c1edf35559bf177367b0d2a93ad15a74a41caca0164b816ed5f636b9733e675c41e6ffb5951f8001a392778b3b63e0ff651d4b72d668da4ec7146b44b6e7f0916ed445ad7e6d8d6b45671fafead9a70a2d4f7e3a55e96ff24da1f35d4c34b29a3d599c9884f18cc736382a7ed4d2f29fb9b8010bda31d4c5549c45cce28942e52166dcbfff76f7e91672afc4459ec352adf8b67e939378b4854734174831091522e6de247a417f850243f1f43cd5bf351982dc9efaf0971dc5b0776d7833803b9c1b94f383d878d4bef7375bdd7460584d5ba9868525bd706507c9ecf52679c01f492052b1e02ddaf7280ef3039a21c9ac7caed7cd17ab214fa1784b7a4ee3260258f3692069613407e3a37fa61bd931697f818703279e7c4ab55687c3f46ab285364b3c2c508aa5c175c8f97bc9c6c87c00817b27b7b6d17f8881846ac01d1f8361eb49e44b044e4f95573120da51c85d7eb5cbd7a88d2622b80b0c04c04b7652170147a63d8ad271cdf9870c0d1ea212d78bd400a490ece9b9cc4dce87967ea2a7bfd3e02f356ea75ebff0e28955724cf21f072c238d47dbc1bb4d05edb904e3bded692d479f1df874ad7462b6fbeef227e2f948595409d79983e6774dc2ca46da726a6d07ee165686fb2625b3e69f32eaf99b1e89223ad94ed9735fc29d5e38de8720943f7ca2827d487ca2323cdf66c0c3adf91b68fb3371bb7fcae1a86dd54c9259ab7cd71ae9c7405948b2986b8d7b849f1cf7ec6c5152e12f681520f2d2b943fc6b6a69f09f2476ec01eb2b810c9bc53dfc51a95b327ef86dee5d86def5a1ea64c31bc772a8125d8238eb84b58c3b2a919acdd35a0c5df07cbe4c72e42627f757bff0c9840e9394e326c3b1fb8567361468d47f20cea6814a8361b73da30201b1d3b34ea2f2fb9e35acac996810d0c0fe9f646963c2463f9d0bcf46a66180e40b202f8439b1c28f643cb96a0e2ec1e232f49f269605cc941bbb94962e75074e5f9b1f4173b3afeb8d0ce59bfcff813ce6604f8ac943cdfe6dce91b592eb416de86471028586f678f703cc100e891b0cc4cea24e333a6f0850ff096400eb8ea713579eab4005a33822de40aa229c93ec2c37029f4a554629f9de91aa06f4809c169d6f6239ffcfd9ddd34e5138d86e0cc73a6ac9871520454251bbb8ff7787fed3cb8ca0ad27f4eb26c8f18ca9b79ae238fdb6211f9849bde989edb4a06e1e1a4c35057b6abe42ea2344eca19f2e4deb476efc1a20ddd3f7e64219f10fd658994ed18d652bf92a591ebfe04f1bd960ed47270d120ca5b7dc6e2c627bb32e9b336c619d6bbb548eee65a69183aefb50244eaceec50003ef3dc4df3464cf3a10933e74101a9a37bba3d5a1ea3863a512e5a7b3e1fea757a56bdfd5ec411cd6748d027442d82bc98afc97cf9da435e20d4d6ca2308cfd1daa716437fd936c34c632fa1b929e2a91bbdcb7cd53177b6f1842881dcdc8b220531298a56e6d35e3132f8e5245945aa0ab7c6f4a28dd2133d25e23eb5095996571056e0b5e4bf73c2967031ab9464ccf7c1c7eaf2ab510ba34547538c1124db37a74a8a0f337c54aceb90a07dca232f0ddfcc8b8870e6a7a1c2c017146f1ee39eb82f5cbfbf171a32b31076c7de055083d4215d72b4c6a90e872d9ed561b20fa4d2db3a9c775ee7a7068ca497d8ab119b29852b599279b457e2a0e9172b6f1b83bd29f3cda06739f16ee4b390bc42cfc309f32edebb2d7b7476c83780a52244f2e2da31da96d154bb2dc47a15f10ca597fe992dfffb613111eea754c5d0f3a0a89db973f7c46943071acdb4833da648ae522c09605aa6dc5b58cd60bd4adb815333abff11c8a3b22c3cf76d4c3e6905fc1a7d235201974e50338a292cd7fc3327fb672065d53a02f1820bf7e1807cec7eeae1f8e53dbda9a8adccbc7d2e51cbb6472bacbfc7d1cbf8c5bf59dcafece6d6db754be17c2f764921b3aaa2417d4ee51fb7bf9ad984273ae36ef074cb71da64ec83853c9b199c5e43b145d4a02448d337f16ba0f83d8cf7c510222cebc8f70e900deade9011e1263ee38322a4051467c95ef0c1e7876137b25c0bf4b111f909a80470f3649dcd2a0c0d8aab9ad4d46c8f1b2f3f50e65e5f118f74af3b9854b97ab8a80b24909e853a2c82d855495e385019f56bd53cc9efa90450a32d0c64ced20277ec6f86c8f64d2383829c4a8719e45619e67631a2bf06e68e181b32c04697b80242e55c51b8b0b7170531dc9abc68d6f449d839bc8943585bca42ed800403e474a708ced765c9c54dad782303e010f9b692602200ece611d8063f460d5c36700&c=%7B%22type%22%3A%22hsw%22%2C%22req%22%3A%22eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmIjowLCJzIjoyLCJ0IjoidyIsImQiOiIzaG5Cb25acEs4QVAwMmNZR1U2Wi9QVkFaZ2NObGd2djNnQ2RlaTBEaTdsTG1BeTZEN0tPN1lYUWkwVURhY0xMTnViY0tqYWxSTGxaR1RtSXpKK3Fuc29lRnUybE53YjVFWkRtN0ExSHp3ek1pRjdmRGZRR0RGd1RMaWtRcThpVGV2Rk9FQ2t3OU9rNWtTTUpmTVBzMUlweHI4NlhvRW9nOERzd0huM3NUM1hIVjlnR1p0aHQ3bmhZUlE9PU05Q3NURjZUUmRzK1FEVzIiLCJsIjoiaHR0cHM6Ly9uZXdhc3NldHMuaGNhcHRjaGEuY29tL2MvOGRjMTU4N2QiLCJlIjoxNjYyMzcyNjM0LCJuIjoiaHN3In0.Lu--lyOUGo5AA6L5sino5DP90sp8E7MYpssu5DPkf9A%22%7D

Browser Request Log:
Same as request.post_data
Note that when i parse await route.continue_(post_data=request.post_data), the browser doesnt encoded it right (The Request Logger doesnt show the payload in json format and the request yields 403 forbidden
```

**Comment by Vinyzu** [comment]
Update: When i modify the post_data, the browser shows the passed string as "request payload".
When i dont, it shows it as "form data".
Hope this helps

**Comment by Vinyzu** [comment]
OK, i got it after like 5 hours of trial an error:
```py
async def mock_json(route, request):
            payload = {**request.post_data_json,
                       "modded": "example"}
            example = await self.page.request.post(request.url, form=payload, headers=request.headers)
            await route.fulfill(response=example)

await page.route("https://example.com/*", mock_json)
```
General Solution:
```py
async def mock_form_data(route, request):
            payload = {**request.post_data_json}
            request = await self.page.request.fetch(request.url, method=request.method, form=payload, headers=request.headers)
            await route.fulfill(response=request)
```
This was a pain in the ass ngl
