### ISSUE TITLE
how do i get the current url of a page?

### ISSUE THREAD

**Issue by FreugdFred** [microsoft/playwright-python#1540]
### Your question

```
from playwright.sync_api import sync_playwright
import time


with sync_playwright() as plays:
    browser = plays.chromium.launch(headless=False, slow_mo=50)
    page = browser.new_page()
    page.goto('https://www.google.nl/maps')
    print(page.url())
```

gets me error:

`TypeError: 'str' object is not callable`

How do i get the current url of the page i am on?

**Comment by shtlrs** [comment]
@FreugdFred  That means that page.url is already a string, and is not a function ( although not only functions are callable) that you can execute/ call.

If you also look at the [docs](https://playwright.dev/python/docs/api/class-page#page-url), you'll see that `page.url` returns a string.

So to fix your problem, just remove the parenthesis.

**Comment by FreugdFred** [comment]
Thanks, it does work but it gives me the previous url instead the of the current url.
How do i get the current url?


```
from playwright.sync_api import sync_playwright
import time


with sync_playwright() as plays:
    browser = plays.chromium.launch(headless=False, slow_mo=50)
    page = browser.new_page()
    page.goto('https://www.google.nl/maps')
    page.fill('input#searchboxinput', 'demo')
    page.locator('#searchbox-searchbutton').click()
    time.sleep(5)
    print(page.url)
```

output:
`https://www.google.nl/maps`

**Comment by shtlrs** [comment]
Reloading the page works. 
But you're correct, getting the url even after navigation returns the old one.

Maybe this is an issue, I'll let @mxschmitt confirm.

**Comment by shtlrs** [comment]
And also, I wouldn't use `time.sleep` if I were you.
One of the greatest features of playwright is the different provided apis to wait for particular events / selectors, etc...
So I'd suggest you'd have a read at those.

**Comment by mxschmitt** [comment]
See here: https://playwright.dev/python/docs/library#timesleep-leads-to-outdated-state

Never use time.sleep()

Also you can use page.wait_for_url(..) or to_have_url instead: https://playwright.dev/python/docs/test-assertions#page-assertions-to-have-url
