### ISSUE TITLE
[Question]:How to automate the local Firefox and Safari browser ?

### ISSUE THREAD

**Issue by sourabhsrawat** [microsoft/playwright-python#1542]
### Your question

Hi, 
I am trying the code to automate the local firefox and safari browser I tried the below 2 options but it is not working.

1.browser = p.firefox.launch(executable_path="/Applications/Firefox.app/Contents/MacOS/firefox",headless=False)
2.browser = p.firefox.launch(channel="firefox",headless=False).

**Comment by mxschmitt** [comment]
It's not possible to use the official Firefox or Safari, since Playwright adds custom apis to automate them.

See here: https://playwright.dev/docs/browsers#firefox
