### ISSUE TITLE
[BUG] page.goto() triggers a timeout in Firefox (but works in Chromium) when navigating to Workday page

### ISSUE THREAD

**Issue by FelixSchwarz** [microsoft/playwright-python#1546]
**Context:**
- Playwright Version: 1.25.2
- Operating System: Fedora Linux 36
- Python version: 3.10
- Browser: Firefox

**Code Snippet**

```python
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    browser = p.firefox.launch()
    page = browser.new_page()
    # if this URL does not work, I can update the URL
    url = 'https://wd3.myworkdaysite.com/recruiting/iubh/IUBH_WD_Jobboard/job/Mnchen/Dozent-Bauingenieurwesen--m-w-d--im-dualen-Studium_R006697/apply'
    # this trigges an TimeoutError with Firefox (but not with Chromium)
    page.goto(url)
    browser.close()
```

**Describe the bug**

I suspect this might be a Firefox bug related to the specific URL but I hope to get some more details to follow up with upstream in that case.

**Comment by mxschmitt** [comment]
I was able to reproduce it on 1.25 but not on our new upcoming version which gets released soon, I'd recommend waiting until 1.26 got released and retrying there!

**Comment by FelixSchwarz** [comment]
Thank you for the quick feedback - looking forward to the new version then :-)

**Comment by mxschmitt** [comment]
Closing in the meantime, please reopen / file a new bug if its still happening in 1.26 then!

**Comment by FelixSchwarz** [comment]
Just checked with 1.26 and I can confirm that it works now.
