### ISSUE TITLE
[Question]: What is depreciated in locator.is_visible() : the method or the argument to take timeout?

### ISSUE THREAD

**Issue by shivangijha** [microsoft/playwright-python#1558]
### Your question

While using locator.is_visible(), I get the true and false value, but in docs it says to be depreciated. I am confused if its just the time option in argument. 
`return self.driver.locator("mat-icon[id='delete']").is_visible()`

The conflict is in another usage, I have to wait for the page to download completely before I start searching for the slider to expand. Here slider is expanded before dom is rendered completely. 

Sorry if this is stupid to ask

**Comment by shivangijha** [comment]
Thank you, this helped.

**Comment by cmacdonnacha** [comment]
But how about when using the Playwright API, and not Playwright test where you won't have assertions?
