### ISSUE TITLE
[Question]: 'c:\Users\ASUS' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by amuza2** [microsoft/playwright-python#1561]
### Your question

Peace, hi
1- created a virualenv
2- installed successfully playwright by "pip install playwright"
3- try to install playwright driver by "playwright install"

it gives me this output:
'""c:\Users\ASUS' is not recognized as an internal or external command,
operable program or batch file.

python version 3.10.6

**Comment by amuza2** [comment]
> This looks like the same issue from [#1355 (comment)](https://github.com/microsoft/playwright-python/issues/1355#issuecomment-1155046595). If so, can you try the suggested fix there?

unfortunately, it doesn't work.

**Comment by amuza2** [comment]
> pytest --help

installing other python packages work
==> python -m playwright install
the above installation doesn't work

but I found something weird
I uninstalled playwright and then wrote "playwright install" the output was:
'playwright' is not recognized as an internal or external command,
operable program or batch file.
-----------------------------
then I installed it and run "pip install playwright" then "playwright install" I got this output:
'""c:\Users\ASUS' is not recognized as an internal or external command,
operable program or batch file.

it looks it's searching for "c:\Users\ASUS" instead of "playwright"
any idea

**Comment by amuza2** [comment]
> I'm not sure. Are there any spaces in the directory names along the path to your virtual env? Rather, what's the full path to your venv?

**I found the solution**
I noticed this "'""c:\Users\ASUS'" it stopped at ASUS and my user folder name were "ASUS VIVOBOOK 17"
so right after ASUS there is a space, may be the space caused the problem and I did change the user name folder and it worked.
**steps to solve this problem:**
1- Change user folder name using a youtube video, it has several steps:
How To Change User Folder Name in Windows 10
https://www.youtube.com/watch?v=Y5_Q2BmTx3Y

2- Go change the python path, change the user folder name from the old to the new one.
you can enter this in your cmd as a shortcut
`rundll32.exe sysdm.cpl,EditEnvironmentVariables`

3- now you need just to use "python -m playwright install"

**Comment by amuza2** [comment]
I think changing the user folder name will have some new issues because a lot of tools or softwares that are set to the old user folder name. like for example changing export to some tools to the new.

**Comment by funnydevdotvn** [comment]
> **I found the solution** I noticed this "'""c:\Users\ASUS'" it stopped at ASUS and my user folder name were "ASUS VIVOBOOK 17" so right after ASUS there is a space, may be the space caused the problem and I did change the user name folder and it worked. **steps to solve this problem:** 1- Change user folder name using a youtube video, it has several steps: How To Change User Folder Name in Windows 10 https://www.youtube.com/watch?v=Y5_Q2BmTx3Y

But in the case you installed your Python 3.10.x for all users, will you change the Program Files to ProgramFiles (with out space) ???

**Comment by funnydevdotvn** [comment]
Even putting "playwright" only on the terminal command will get something like this
> '""C:\Program' is not recognized as an internal or external command, operable program or batch file.
I think this because of the playwright's working directory is missing the "space" character.

**Comment by funnydevdotvn** [comment]
The problem starts from compute_driver_executable function, but when I try to double quotes the path it makes subprocess function got error like this
`compute_driver_executable return: C:\Program Files\Python310\lib\site-packages\playwright\driver\playwright.cmd
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python310\Scripts\playwright.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python310\lib\site-packages\playwright\__main__.py", line 24, in main
    completed_process = subprocess.run(
  File "C:\Program Files\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] Access is denied`

**Comment by funnydevdotvn** [comment]
Okay now I found the right solution is edit the playwright.cmd in a path which as the same as "C:\Program Files\Python310\Lib\site-packages\playwright\driver\playwright.cmd" with this content:

`@ECHO OFF
SETLOCAL
IF %PLAYWRIGHT_NODEJS_PATH%x == x SET PLAYWRIGHT_NODEJS_PATH="%~dp0\node.exe"
""%PLAYWRIGHT_NODEJS_PATH%"" "%~dp0\package\lib\cli\cli.js" %*`

Which I did is double quotes again the PLAYWRIGHT_NODEJS_PATH to fix the space error.

> The problem starts from compute_driver_executable function, but when I try to double quotes the path it makes subprocess function got error like this

**Comment by amuza2** [comment]
> > **I found the solution** I noticed this "'""c:\Users\ASUS'" it stopped at ASUS and my user folder name were "ASUS VIVOBOOK 17" so right after ASUS there is a space, may be the space caused the problem and I did change the user name folder and it worked. **steps to solve this problem:** 1- Change user folder name using a youtube video, it has several steps: How To Change User Folder Name in Windows 10 https://www.youtube.com/watch?v=Y5_Q2BmTx3Y
> 
> But in the case you installed your Python 3.10.x for all users, will you change the Program Files to ProgramFiles (with out space) ???

I tried to uninstall then install, it didn't work
maybe but my path is not in "program files" it's in "AppData" folder, this is my path:
"C:\Users\REALMAN\AppData\Local\Programs\Python\Python310\python.exe"
so there is no space

**Comment by funnydevdotvn** [comment]
> C:\Users\REALMAN\AppData\Local\Programs\Python\Python310\python.exe

Try to change "C:\Users\REALMAN\AppData\Local\Programs\Python\Python310\Lib\site-packages\playwright\driver\playwright.cmd" as I write above and show some result?

**Comment by amuza2** [comment]
> Okay now I found the end of problem is from playwright driver. So the right solution is edit the playwright.cmd in a path which as the same as "C:\Program Files\Python310\Lib\site-packages\playwright\driver\playwright.cmd" with this content:

> @echo OFF
> SETLOCAL
> IF %PLAYWRIGHT_NODEJS_PATH%x == x SET PLAYWRIGHT_NODEJS_PATH="%~dp0\node.exe"
> ""%PLAYWRIGHT_NODEJS_PATH%"" "%~dp0\package\lib\cli\cli.js" %*
> 
> Which I did is double quotes again the PLAYWRIGHT_NODEJS_PATH to fix the space error.

I saw that file but I didn't open it, I wouldn't even know what to do if I opened it anyway.
Congratulation

**Comment by amuza2** [comment]
> "C:\Users\REALMAN\AppData\Local\Programs\Python\Python310\Lib\site-packages\playwright\driver\playwright.cmd"

I already solved the problem when I changed the user folder name from "asus vivobook 17" to "realman"
I am not going to touch anything, if it's working don't touch it :)

**Comment by funnydevdotvn** [comment]
> I think changing the user folder name will have some new issues because a lot of tools or softwares that are set to the old user folder name. like for example changing export to some tools to the new.

As you said here I think the best choice is do as my solution. If you changed the folder name in a wrong way (because it relates to some information on computer like OS Username, SID, User path...) could make some other software crash.

**Comment by hylkepostma** [comment]
Using Playwright (1.29.0, Python 3.10.2 on Windows 11) from `C:\Program Files (x86)\My App Name With Spaces\` raises the following error:
```log
AttributeError: 'PlaywrightContextManager' object has no attribute '_playwright'
```

I have changed the `[...]Lib\site-packages\playwright\driver\playwright.cmd` file so that it contains the following:

```bat
@echo off
setlocal
if not defined PLAYWRIGHT_NODEJS_PATH (
  set PLAYWRIGHT_NODEJS_PATH="%~dp0\node.exe"
)
""%PLAYWRIGHT_NODEJS_PATH%"" "%~dp0\package\lib\cli\cli.js" %*
```

After that, the error went away, so I can confirm that @funnydevdotvn's solution works for me. Thanks! 🎉
