### ISSUE TITLE
[Feature] As an user, I want to locate the select_options by the text instead of value

### ISSUE THREAD

**Issue by yandong01** [microsoft/playwright-python#1572]
1. There is a select dropdown list like this:
`<select class="product_sort_container" data-test="product_sort_container"><option value="az">Name (A to Z)</option><option value="za">Name (Z to A)</option><option value="lohi">Price (low to high)</option><option value="hilo">Price (high to low)</option></select>`

2. Currently, playwright supports to locate the option by value:      **element.select_option(value="az")**
3. I want to locate the select option by text:   **element.select_option(text="Name (A to Z)")**, can we do the location like this?

**Comment by mxschmitt** [comment]
you can also select by label: `page.locator("...").select_option("select", label="Indigo")`
