### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by InLoveWithMesh** [microsoft/playwright-python#1590]
Is it possible to make a onefile .eye (with pyknstaller) of a playwright Firefox script? Because if I do it normal and start the .eye even with geckodriver in the path, it still doesn‘t work and says it needs to do „install playwright“ even tho I have it installed

**Comment by yury-s** [comment]
The question should be asked on pyknstaller forum I believe. Please open a new issue in this repository if there is a particular functionality that is broken / missing in Playwright.

**Comment by mxschmitt** [comment]
Does this help you? https://playwright.dev/python/docs/library#pyinstaller
