### ISSUE TITLE
Why the code USES the p = await async_playwright ().   The start (), There is still a cmd window after pyinstaller -F-w.py is packaged

### ISSUE THREAD

**Issue by dzmgithub** [microsoft/playwright-python#1597]
Why the code USES the p = await async_playwright ().   The start (), There is still a cmd window after pyinstaller -F -w .py is packaged

code：
p = await async_playwright().start()
browser = await p.chromium.connect_over_cdp(r"http://localhost:9527")

When I run the exe program, the following window will appear.
![1666235331351](https://user-images.githubusercontent.com/45427740/196847253-85af0833-0b8b-4cf7-a2a3-a7aaf785c469.jpg)

**Comment by treb00** [comment]
Any solution? I start with 
`with sync_playwright() as p:`
and multiple cmds are popping up with --onefile
