### ISSUE TITLE
[Question]: Why the code USES the p = await async_playwright (). The start (), There is still a cmd window after pyinstaller -F -w .py is packaged

### ISSUE THREAD

**Issue by dzmgithub** [microsoft/playwright-python#1598]
### Your question

Why the code USES the p = await async_playwright (). The start (), There is still a cmd window after pyinstaller -F -w .py is packaged

code：
p = await async_playwright().start()
browser = await p.chromium.connect_over_cdp(r"http://localhost:9527/")

When I run the exe program, the following window will appear.
![1666253024256](https://user-images.githubusercontent.com/45427740/196891837-997f928a-8340-4694-afa5-9cd4859bf446.jpg)

**Comment by mxschmitt** [comment]
Most likely we want to have the nowindow without a condition, can you test removing the check for "if sys.stdout is None" in [this](https://github.com/microsoft/playwright-python/blob/main/playwright/_impl/_transport.py#L112)  file to see if it works?

It was added here: https://github.com/microsoft/playwright-python/pull/729

**Comment by dzmgithub** [comment]
> Most likely we want to have the nowindow without a condition, can you test removing the check for "if sys.stdout is None" in [this](https://github.com/microsoft/playwright-python/blob/main/playwright/_impl/_transport.py#L112) file to see if it works?
> 
> It was added here: #729

It worked, thank you
