### ISSUE TITLE
[BUG] Execution context was destroyed

### ISSUE THREAD

**Issue by Stefan-Blandin** [microsoft/playwright-python#1600]
**Context:**
- Playwright Version: 1.27.1
- Operating System: Linux
- Python version: 3.8.13
- Browser: All
- Extra: Docker container, running with pytest-playwright

**Code Snippet**

```python
        page.wait_for_load_state()
        page.fill(self.EMAIL_INPUT, email)
        page.fill(self.PASSWORD_INPUT, password)
        page.keyboard.press("Enter")
        print(page.title())
```

**Describe the bug**

I get an error saying that the system is navigating when I attempt to print the page content before page.title(). when page.title() is called, I get an error message "Execution context was destroyed, most likely because of a navigation"

I've also tried different methods to submit my login form such as clicking the login box, but those cause the system to take +30 seconds and timeout, which is unlikely to be driven by anything in the docker container.

**Comment by mxschmitt** [comment]
Can you share a full code example for us which we can execute?

**Comment by Stefan-Blandin** [comment]
Thank you for the quick response. I realize here that I probably haven't given you much information, and it probably works on your system. Unfortunately I cannot give you more info as we have a ~10gb codebase we'd have to ship you. 

However, I can tell you what we've tried. If it's possible to give us more info on what we can use to diagnose why it isn't working, that would be extremely helpful to us.

**Comment by mxschmitt** [comment]
Unfortunately hard to support without having access to the website you are testing against. You could start providing us some more logs, where the exception gets thrown etc. and provide us debug logs by setting first the `DEBUG=pw:api` env var and then if not helpful the `DEBUG=pw:protocol` env var.
