### ISSUE TITLE
[Question]:  How to modify value or attribute in the html dom?

### ISSUE THREAD

**Issue by youyuge34** [microsoft/playwright-python#1605]
### Your question

How to change the original value of the html dom? I have such page html dom like
```
<span class="rax-text-v2" id="111" style="-webkit-line-clamp: 2;">text111</span>
```

and I want to change its value or style to:
```
<span class="rax-text-v3" id="111" style="-webkit-line-clamp: 2;">text222</span>
```

Do I have to ues page.evaluate() and how?

**Comment by mxschmitt** [comment]
`page.locator("#111").evaluate("e => e.style.border = '2px solid green'")`

e is in this case the HTMLElement on the page. See https://playwright.dev/docs/evaluating for more information.
