### ISSUE TITLE
[BUG] Tracing produces "Action was interrupted" error

### ISSUE THREAD

**Issue by ppena-LiveData** [microsoft/playwright-python#1616]
**Context:**
- Playwright Version: [what Playwright version do you use?]
1.27.1
- Operating System: [e.g. Windows, Linux or Mac]
Windows
- Python version: [e.g. 3.7, 3.9]
3.9.12
- Browser: [e.g. All, Chromium, Firefox, WebKit]
All
- Extra: [any specific details about your environment]

**Code Snippet**

```python
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    browser = p.chromium.launch()
    context = browser.new_context()
    context.tracing.start(screenshots=True, snapshots=True, sources=True)
    page = browser.new_page()
    page.goto('https://playwright.dev')
    context.tracing.stop(path='trace.zip')
    browser.close()
```

**Describe the bug**

The above Python script successfully creates a `trace.zip` file, but the `trace.trace` file within it does not have any actions and instead has `{"error":{"name":"Error","message":"Action was interrupted"}}`

Here are the whole contents of the file:
```json
{"version":3,"type":"context-options","browserName":"firefox","options":{"acceptDownloads":true,"viewport":{"width":1280,"height":720}},"platform":"win32","wallTime":1667251183725}
{"type":"action","metadata":{"id":"call@9","stack":[{"file":"C:\\git\\playwright-test\\trace_test_for_github.py","line":12,"function":"<module>"}],"apiName":"Tracing.stop","objectId":"tracing@8bbf248e7acb5569a898907a48e547c2","wallTime":1667251184809,"startTime":31761823.357,"endTime":0,"type":"Tracing","method":"tracingStopChunk","params":{"mode":"compressTraceAndSources"},"log":[],"snapshots":[],"afterSnapshot":"after@call@9","error":{"error":{"name":"Error","message":"Action was interrupted"}}}}
```

**Comment by mxschmitt** [comment]
You are creating two contexts:

a) browser.new_context
b) browser.new_page which creates a context and a page

And you enable tracing only on the first, but use the page of the second (b). To fix this, you need to remove browser.new_page, see here:

```diff
diff --git a/test.py b/test.py
index cb0be4e4a..135061dec 100644
--- a/test.py
+++ b/test.py
@@ -2,8 +2,8 @@ from playwright.sync_api import sync_playwright
 with sync_playwright() as p:
     browser = p.chromium.launch()
     context = browser.new_context()
+    page = context.new_page()
     context.tracing.start(screenshots=True, snapshots=True, sources=True)
-    page = browser.new_page()
     page.goto('https://playwright.dev')
     context.tracing.stop(path='trace.zip')
     browser.close()
\ No newline at end of file
```

**Comment by ppena-LiveData** [comment]
Can you please update [your documentation](https://playwright.dev/python/docs/trace-viewer-intro)? It currently shows a `page` variable that comes out of nowhere. Since it clearly needs to come from `context.new_page()` (and not from `browser.new_page()`), then the documentation should show that.

**Comment by mxschmitt** [comment]
Fair point, I'll update it.
