### ISSUE TITLE
[Question]: How can i wait for a Frame to be reloaded ?

### ISSUE THREAD

**Issue by GunjanSheth** [microsoft/playwright-python#1633]
### Your question

I have a Frame that opens up before adding a new component on AUT.
In the Frame I have a Form with few TextBoxes, Dropdown etc.

The moment I select a value from the Dropdown, the entire Frame gets reloaded

![image](https://user-images.githubusercontent.com/110458975/200497318-81f5121f-a2e5-4745-a886-dd480bb649be.png).

Referring the screenshot.
The moment I select a value from the Top most dropdown, the frame loads after a brief second. 

But during execution what happens is.

1. Select a value from the Top most dropdown
2. Enter a value in the Number field
3. Select a value from the Country dropdown
some where around here, the frame reloads, and the Fields of Number and Country are reset to their original values (i.e. Becomes Blank)

So I want to write a piece of code that waits for the frame to be ready after Step1 (in face after every step where I select values in dropdown).

I tried the following ways, but it did not work.

1.  Found the Frame object the moment the Frame appears. and used
`get_add_frame().wait_for_load_state()` # used different parameters like domcontentloaded, networkstateidle but none worked

2. I thought the frame might be detaching for a few seconds, but it always returned False
e.g. (dummy code)

```
first_dropdown.select_option("valid_option")
for i in range(0, 10):
    print(get_add_frame().is_detached())
    time.sleep(0.25)
```
it returns False each time, so i cannot use that

Can someone pls guide me how to wait for the frame load each time ?

**Comment by mxschmitt** [comment]
Can you provide us a repro which we can run locally? If you use FrameLocators and Locators it should all just work out of the box.

See here for FrameLocators: https://playwright.dev/python/docs/api/class-framelocator
And here for Locators: https://playwright.dev/python/docs/locators

**Comment by GunjanSheth** [comment]
Unfortunately i cannot share the exact use case as it is having client data & site, but I can try to explain the exact working.

`
class MyPageClass:
	
	def __init__(self):
		self.my_frame: FrameLocator = TestBase.get_page().frame_locator("xpath=//iframe[@class='valid-frame-class']")
		self.field_1_lst: Locator = self.my_frame.locator("xpath=//select[@id='field_1']")
		self.field_2_txt: Locator = self.my_frame.locator("xpath=//input[@id='field_2']")
		self.field_3_lst: Locator = self.my_frame.locator("xpath=//select[@id='field_3']")
		self.field_4_txt: Locator = self.my_frame.locator("xpath=//input[@id='field_4']")
		self.field_5_lst: Locator = self.my_frame.locator("xpath=//select[@id='field_5']")
		self.field_6_txt: Locator = self.my_frame.locator("xpath=//input[@id='field_6']")
		
    def get_frame() -> Frame :
        return TestBase.get_page().frame(url=re.compile(".*valid-frame-url.*"))
    
	def my_function() -> None:
		self.field_1_lst.select_option("Valid Value")
		# the Frame reloads at this point
        
        # I used these waits but that does not wait for the loading of Frame
        TestBase.get_page().wait_for_load_state("domcontentloaded")
        TestBase.get_page().wait_for_load_state("networkidle")
        TestBase.get_page().wait_for_load_state("load")
        
        # also i tried the fllowing approach for wait but that also does not wait
        self.get_number_frame().wait_for_load_state("domcontentloaded")
        self.get_number_frame().wait_for_load_state("networkidle")
        self.get_number_frame().wait_for_load_state("load")
        
        self.field_2_txt.fill("1234567890")
        self.field_4_txt.fill("valid data")
        
        # some where around this the reloading of the frame is completed, 
        # and as a result it resets the value of the above field2 and field4
`

**Comment by mxschmitt** [comment]
We need unfortunately a repro to act on it, with whats expected and actual results. Screenshots and code which we can't run is not enough.

**Comment by GunjanSheth** [comment]
i confirmed, i cannot share the application. 
But can you tell me how would you wait for a Frame till the contents of the frame is loaded ?

**Comment by mxschmitt** [comment]
Usually you never need to do this, Playwright's action methods, aka. click, fill, etc. will automatically wait for all of that.

**Comment by GunjanSheth** [comment]
Okay.
But its not the case for sure for my application, but for the moment am closing this, and if I can find some other open source applications to replicate this issue, will reopen this.
Thanks @mxschmitt
