### ISSUE TITLE
[BUG] AttributeError: 'PlaywrightContextManager' object has no attribute 'chromium'

### ISSUE THREAD

**Issue by LeilaSchooley** [microsoft/playwright-python#1634]
Playwright version

latest
Operating system

Windows
What browsers are you seeing the problem on?

Chromium
Other information

No response
What happened? / Describe the bug

AttributeError: 'PlaywrightContextManager' object has no attribute 'chromium'

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally.

```python
from playwright.sync_api import sync_playwright


p = sync_playwright()
browser = p.chromium.launch(headless=False)
page = browser.new_page()


```

**Describe the bug**

I dont want to use the with statement nor do I want to use pytest as this is a multi threaded project- I want to modulize the code to launch the browser in some projects and using the with statement forces me to put all of the code in one function. 

Thank you

**Comment by mxschmitt** [comment]
You are missing a .start() see here: https://playwright.dev/python/docs/library#interactive-mode-repl

**Comment by GaleHuang** [comment]
> I believe there is a documentation snag:
> 
> The documentation in the first example here is wrong: https://playwright.dev/python/docs/api/class-playwright
> 
> and has two issues:
> 
> 1. It's being imported as `import sync_playwright` or `import async_playwright`, but being accessed as `playwright`
> 2. It's not calling `.start()`
> 
> If you copy and paste the example, you'll run into these two issues.

`with sync_playwright() as p:` will call `.__enter__()`, which does the same thing as `start()`

```
    def start(self) -> SyncPlaywright:
        return self.__enter__()
```
