### ISSUE TITLE
[Question]: How to write custom web-first assertions with Playwright-python?

### ISSUE THREAD

**Issue by alexspurling** [microsoft/playwright-python#1640]
Playwright Javascript provides an API that allows you to write custom assertions:

https://playwright.dev/docs/test-advanced#add-custom-matchers-using-expectextend

Is there such a feature in Playwright Python? If not, what is the recommended way to make more complex assertions?

My use-case is a table with a sort button. I would like to click the sort button, and then ensure the items in the table are sorted. Since there is no function `expect(Locator).to_be_sorted()`, I would like to write my own type of assertion.

Alternatively, I can manually query for all the elements like so:

```
page.locator("#sort-asc").click()
# Need to wait for API requests to complete
items = page.query_selector_all("#itemtable")
values = []
for item in items:
    values.append(item.inner_text())
# Copy the array
sorted_values = values[:]
sorted_values.sort()
correct = values == sorted_values
assert_true(correct, msg="Table not sorted correctly")
```

But this will fail if there was not sufficient time between line 1 and line 2. I can of course insert a delay, but I would like to take advantage of Playwright's advertised "zero delay assertions". Is what I want to do possible?

**Comment by mxschmitt** [comment]
This is not possible as of today. What about using `to_have_text` and pass an array into it?

This will assert the order, see the examples on the following link, if you scroll a bit down: https://playwright.dev/python/docs/test-assertions#locator-assertions-to-have-text
