### ISSUE TITLE
[Question] I'm learning pytset+playwright framework recently, I want to know how to implement "Reuse signed in state" in pytest framework

### ISSUE THREAD

**Issue by tarzanfan** [microsoft/playwright-python#1643]
```python
# Save storage state into the file.
storage = context.storage_state(path="state.json")

# Create a new context with the saved storage state.
context = browser.new_context(storage_state="state.json")
```
I think it should be configured in `conftest.py`,but I don't know how to proceed
```python
@pytest.fixture(scope="session")
def browser_context_args(browser_context_args):

    return {
        **browser_context_args,
        "viewport": {
            "width": 1920,
            "height": 1080,
        },
    }
```

**Comment by mxschmitt** [comment]
You can create a custom new fixture which has scope [`session`](https://docs.pytest.org/en/6.2.x/fixture.html#fixture-scopes) so it only runs a single time per pytest test execution with auto=True, so it runs by default. This is basically then the global setup.

Inside this session scoped fixture you do your login, and save the storage state. 

The counter part which you already created above is `browser_context_args` where you reference `"storage_state": "yourStorageState.json"` (this gets used to create a new context per each test.

Let us know if that helps!
