### ISSUE TITLE
[Question]: what causes playwright error - ValueError('The future belongs to a different loop than the one specified as the loop argument')>

### ISSUE THREAD

**Issue by jnjgomez10** [microsoft/playwright-python#1645]
### Your question

In my pytest test case, I call an async function to get backend data using REST API.  I then use the data in REST response to compare the data on UI pages.  I get this error when calling playwright async API,

self       = <playwright._impl._connection.Connection object at 0x7f1d8974a250>
        st         = [FrameInfo(frame=<frame at 0x7f1d892f0cf0, file '/usr/local/lib/python3.9/site-packages/playwright/_impl/_sync_base.py...o/tasks.py', lineno=256, function='__step', code_context=['                result = coro.send(None)\n'], index=0), ...]
        task       = <Task finished name='Task-195' coro=<Locator.click() done, defined at /usr/local/lib/python3.9/site-packages/playwrigh...tor.py:136> exception=**ValueError('The future belongs to a different loop than the one specified as the loop argument')>**
/usr/local/lib/python3.9/site-packages/playwright/_impl/_connection.py:69: in inner_send
    done, _ = await asyncio.wait(
        callback   = <playwright._impl._connection.ProtocolCallback object at 0x7f1d88912c70>
        method     = 'click'
        params     = {'selector': 'role=button[name="Overview"i]', 'strict': True}
        return_as_dict = False
        self       = <playwright._impl._connection.Channel object at 0x7f1d88c5faf0>  
        
  Do you have similar sample code I can learn from?

**Comment by mxschmitt** [comment]
Can you provide a minimal repro which we can run locally to reproduce this issue?

**Comment by mxschmitt** [comment]
Please re-file with a repro!
