### ISSUE TITLE
[BUG]     self._request: APIRequestContext = from_channel(initializer["requestContext"])

### ISSUE THREAD

**Issue by carminati-marco** [microsoft/playwright-python#1649]
**Context:**
- Playwright Version: playwright==1.27.1
- Operating System: Mac
- Python version: Python 3.9.6 (default, Sep 26 2022, 11:37:49) 
- Browser: Chromium
- Extra: [any specific details about your environment]

**Code Snippet**

https://github.com/microsoft/playwright-python/blob/main/playwright/_impl/_browser_context.py#L103

when I try to connect to an endpoint and I create a new context

```python
from playwright.sync_api import sync_playwright
async with async_playwright() as p:
    ....
    browser_endpoint = "ws://0.0.0.0:3000"
    browser = await p.chromium.connect(browser_endpoint)
   ....
    context = await browser.new_context(user_agent=headers['User-Agent'], http_credentials=http_credentials,
                                        extra_http_headers=headers)
```

**Describe the bug**

the exception is 
```
    self._request: APIRequestContext = from_channel(initializer["requestContext"])
KeyError: 'requestContext'
```
as the function receives `APIRequestContext` instead of `requestContext` (requestContext exists with the launch command, like `p.chromium.launch()` )

**Note**

the exception has been created using the following docker image https://github.com/pixelfactoryio/playwright-server.
using a container with the last version
```
FROM mcr.microsoft.com/playwright:v1.27.1-focal
RUN npx -y playwright install
CMD npx playwright run-server --port 3000
```
we dont have any exception

**Comment by mxschmitt** [comment]
The Playwright Server and Client version has to match (on the Minor level at least), otherwise it will end up in such issues.

**Comment by carminati-marco** [comment]
Thanks for the explanation
