### ISSUE TITLE
[Feature] add return for failed attempts in docs

### ISSUE THREAD

**Issue by Sammeeey** [microsoft/playwright-python#1653]
It's great that the methods are documented along with their expected return values.

I am just trying to figure what [page.locator()](https://playwright.dev/python/docs/api/class-page#page-locator) return if it doesn't find the specified element successfully.

I think I need to look it up in the source code.

Therefore the docs could be improved by adding the the return values for *failed attempts* for all methods.
Does this make sense?

**Comment by mxschmitt** [comment]
A Playwright Locator **always** return a _Locator_, it never looks for the element on the page. Only if you perform a certain action (like click, fill etc.), it will make the actual visibility and actionability checks etc.

See here: https://playwright.dev/docs/locators

If these don't find your element due e.g. an 'element not found' error, then they throw an error.

**Comment by Sammeeey** [comment]
You are right.
I think this makes the feature request superfluous.
