### ISSUE TITLE
[Question]: Can Playwright launch a Chromium which has cookie of last time?

### ISSUE THREAD

**Issue by bk111** [microsoft/playwright-python#1655]
### Your question

Is it possible chromium use the cookie of last time? I mean the Chromium will remember and use the cookie of last time automatically.

**Comment by mxschmitt** [comment]
We have something which we call _storage state_ for it. It contains cookies and local storage. See [here](https://playwright.dev/python/docs/auth#session-storage).

If you want to set cookies manually, you can do context.add_cookies().
