### ISSUE TITLE
[Question]: Is it possible to get the response of a specific request ?

### ISSUE THREAD

**Issue by therealmarius** [microsoft/playwright-python#1656]
### Your question

**Hey guys!** 

I wanna get the response of a specfic request. 
I've seen this [Questions](https://github.com/microsoft/playwright-python/issues/358) before. 
It explain how to log all response and request but I only want the response of a specified request. I don't know if it's possible.

I hope you'd help. A code snippet would be appreciated :)
Thanks.
Have a good day.

**Comment by mxschmitt** [comment]
Usually you use expect_request and put it around your action, e.g. click.

See here: https://playwright.dev/python/docs/api/class-page#page-wait-for-request

Let us know if that works for you!

If not, let us know when your request gets triggered, is it after an action, after a navigation etc.

**Comment by therealmarius** [comment]
Hi @mxschmitt and thanks for your answer. I already tried that. And I get somthing like this: 

`<Request url='https://example.com/s/spaceapi/getSpaceMemberListOrderByFunction2?spaceId=1891&withInvited=false' method='GET'>` 

But this URL is returning a JSON file.
(And btw to get this file I need to be logged in, I automate the login process using Playwright) 

I wanna get this response to put it into a JSON file and then use it with another script that I made:

![image](https://user-images.githubusercontent.com/70507259/202696569-2f763b9b-7cc7-4814-be7f-a979a53b8226.png)

I get the response when I click on a specific button of the page.

Have a good day.

**Comment by therealmarius** [comment]
Hello guys! 

I finnaly found my answer! (Using the amzing GitHub Copilot)
For those who want to know how, here's the code snnipet:
```
with page.expect_request("http://example.com/resource") as first:
    page.click('button')
    first_request = first.value
    print(first_request.response().json())
```

Thanks everyone! Have an amazing day!
