### ISSUE TITLE
[Question]: How to stop loading page in handle function

### ISSUE THREAD

**Issue by MorPo** [microsoft/playwright-python#1662]
### Your question

Hello all :)

Details:
1. Python 3.7
2. Chromium 108.0.5359.29
3. playwright version 1.28

I'm trying to stop running requests to a site after a condition is met.
I tried looking through your documentation and in StackOverflow but to no avail.

Below is code similar to what I'm trying to achieve:
```
with sync_playwright() as p:
    def handle_response(response):
        if "some_text" in response.url:
            <extract json code>
            <Here I want to stop getting new requests>

    browser = p.chromium.launch()
    page = browser.new_page()

    page.on("response", handle_response)
    page.goto(url, wait_until="networkidle")
    page.context.close()
    browser.close()
```

I thought to handle this problem by closing the page and the browser but then I get an error from `page.goto` or to abort all next requests, but that doesn't solve the problem Because requests that have already triggered `page.route` will not trigger it again and this is a problem for me.

Thank you very much!

**Comment by mxschmitt** [comment]
Canceling requests is not supported, what you can do is either navigate to e.g. `about:blank` or you create a new page. To be safe create a new browser context, which is isolated from the other browser contexts. So e.g. no Service Workers do leak with other instances.
