### ISSUE TITLE
[Question]: use proxy to open specify page, not all pages

### ISSUE THREAD

**Issue by viponedream** [microsoft/playwright-python#1663]
### Your question

Some page need the proxy, but some dont, 
if i launch the browser with proxy parameter, it will use the proxy on all pages,
how to open only some specify page by proxy?
thank you.

**Comment by mxschmitt** [comment]
Proxies can be only specified on two levels. Either for the entire browser or for the browser context. Having it per page is not supported.

See here: https://playwright.dev/docs/network#http-proxy
