### ISSUE TITLE
[Feature] Support waitForRequest

### ISSUE THREAD

**Issue by AndrewGuenther** [microsoft/playwright-python#1665]
The Javascript library has `waitForRequest` and `waitForResponse` APIs, but these aren't present in the Python version. It would be helpful to have these added.

https://playwright.dev/docs/api/class-page#page-wait-for-request

**Comment by mxschmitt** [comment]
In Python we have wait_for_request and wait_for_response, which are a replacement for that see here: https://playwright.dev/python/docs/api/class-page#page-wait-for-request and
