### ISSUE TITLE
[Question]: Why is my POST requests seem stuck ?

### ISSUE THREAD

**Issue by therealmarius** [microsoft/playwright-python#1669]
### Hello guys!

I'm trying to make a POST request to add a certain song a specific playlist in Apple Music. Don't say: "You should use the API offered by Apple, it's easier" I GOD DAMN KNOW, but it's not free, and I'm a stingy guy. Moreover I tried in my browser and it works, so here I am.

As said, I wanna make a POST request to: `https://amp-api.music.apple.com/v1/me/library/playlists/<YOUR PLAYLIST ID>/tracks` with data like this: `{"data":[{"id":”<AM ID OF THE SONG>”,"type":"songs"}]}`

So, to reproduce the steps I made into my browser, I automated the login, and then sent POST requests with the data inside. But every time I try, the request is like stuck. Nothing happens. No timeout, nothing. So, I don’t know if it’s a bug or something like that. 

For the moment my code looks like this:
```
import time
from playwright.sync_api import sync_playwright

with sync_playwright() as playwright:
    browser = playwright.firefox.launch(headless=False)
    context = browser.new_context(base_url="https://amp-api.music.apple.com/v1/me/library/playlists")
    api_request_context = context.request
    context.storage_state(path="storage.json")
    page = context.new_page()
    page.goto("https://music.apple.com/fr/login")
    print("\nPlease log in using the browser interface.")
    time.sleep(20)
    input("Have you logged in? Press Enter to continue...")
    with open('itunes.csv') as itunes_identifiers_file:
        for line in itunes_identifiers_file:
            itunes_identifier = int(line)
            print(f"\nAdding song with iTunes identifier {itunes_identifier}...")
            data = {"data":[{"id":f'{itunes_identifier}',"type":"songs"}]}
            headers = {<YOUR HEADERS>}
            headers_options = {<YOUR HEADERS FOR THE OPTION REQUEST>}
            options = api_request_context.post.options("/<YOUR PLAYLIST ID>/tracks", headers=headers_options)
            print(options.status)
            response = api_request_context.post("/<YOUR PLAYLIST ID>/tracks", data=data, headers=headers)
            print(response.status)
            print(f"Added {itunes_identifier} to playlist.")
            time.sleep(5)
```
I'll really appreciate any help... Feel free to ask any questions, I'll be glad to answer to them.
Thanks, have a good day!

**Comment by mxschmitt** [comment]
Due the fact that this repro is not runnable and is not about end-to-end testing, we can't act on it. Closing for now.
