### ISSUE TITLE
[Question]: Does api_request_context.fetch use the browser itself to perform the API rquest?

### ISSUE THREAD

**Issue by sla-te** [microsoft/playwright-python#1673]
### Your question

```python
async def handler(self, route: Route, request: Request):

	response = await self.page.request.fetch(request)

	try:
		r = await response.json()
	except Exception:
		r = await response.text()

	print(response.status, r)
	await route.fulfill(response=response)
```

If I added a route and attached the above handler to it, which underlying implementation will actually perform the request?

**Comment by mxschmitt** [comment]
The request does not get executed by the browser, it gets executed by the Playwright driver. It will use tho all the cookies from the browser and update the cookies if some cookies were modified or set.

**Comment by mxschmitt** [comment]
Yes, Playwright driver is Node.js under the hood.

**Comment by mxschmitt** [comment]
https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/fetch.ts
