### ISSUE TITLE
[BUG] Playwright 1.28.0 dont close browser

### ISSUE THREAD

**Issue by 66696e656c696665** [microsoft/playwright-python#1677]
**Context:**
- 1.28.0
- windows 10
- 3.8
- Chromium 
- Before update playwright was work

**Code Snippet**

```python
self.context.close()
self.browser.close()
if self.playwright:
    self.playwright.stop()
```

**Describe the bug**

before the update everything worked fine

**Comment by mxschmitt** [comment]
Can you provide us the output when you set the following environment variables? `DEBUG=pw:api,pw:browser DEBUGP=1`

Does it reproduce with this minimal example?

```python
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    for browser_type in [p.chromium, p.firefox, p.webkit]:
        browser = browser_type.launch()
        page = browser.new_page()
        page.goto('http://whatsmyuseragent.org/')
        page.screenshot(path=f'example-{browser_type.name}.png')
        browser.close()
```

**Comment by mxschmitt** [comment]
Closing since its stale, please re-file with more information.
