### ISSUE TITLE
[BUG] The error: playwright._impl._api_types.Error: Executable doesn't exist at /webkit-1735/pw_run.sh

### ISSUE THREAD

**Issue by iam-luci** [microsoft/playwright-python#1679]
**Context:**
- Playwright Version: 1.28.0
- Operating System: MacOS Ventura 13.0.1 
- Python version: 3.11
- Browser: All
- Extra: [any specific details about your environment]

**Code Snippet**

```python
from playwright.sync_api import sync_playwright
        with sync_playwright() as playwright:
            browser = playwright.firefox.launch()
            page = browser.new_page()
            page.goto(url)
```

**Describe the bug**

When I run my script, it keeps asking me to run the command `playwright install`. Which I did. 
And when I look into folders and logs: I found that it installs well browsers, but it seems like playwright tries to start a browser that doesn't exists in the wanted version. 
The error: `playwright._impl._api_types.Error: Executable doesn't exist at /Users/username/Library/Caches/ms-playwright/webkit-1735/pw_run.sh`
And when I enter `ls` into ms-playwright folder: `chromium-1000 ffmpeg-1007   firefox-1322  webkit-1630`.

I don't know how playwright really works, but it works without any bug while using `codegen`.

Thanks in advance.

**Comment by mxschmitt** [comment]
Looks like you have multiple versions of Playwright installed, and another Playwright version gets picked up when installing the browsers.

You can try `python -m playwright install` which uses the same version as when running a normal python script.

**Comment by mxschmitt** [comment]
Closing since its stale and per above. Please re-file if you still encounter issues.
