### ISSUE TITLE
[CLI] Option to install specific version of browsers

### ISSUE THREAD

**Issue by Granitosaurus** [microsoft/playwright-python#168]
Right now the only way to change browser version is to manually edit the `site-packages/playwright/drivers/browsers.json`. Would be great if that version could be supplied to `install` command as a flag. 

e.g.
```
$ python -m playwright install --chromium-version=798026
or through environment variable
$ export PLAYWRIGHT_CHROMIUM_VERSION=798026
$ python -m playwright install
```

**Comment by mxschmitt** [comment]
Probably related to #47

Unfortunately it's not possible to specify the revision since WebKit or Firefox are tight to the specific Playwright release, but we will allow in the future to only install a single browser. (For Chromium its not that bound but we still support only the given version).

Why do you want to install a specific version?

**Comment by Granitosaurus** [comment]
> Why do you want to install a specific version?

Different versions behave differently and newer versions have many performance improvements. The current chromium version for example is a bit dated 😬

**Comment by mxschmitt** [comment]
> > Why do you want to install a specific version?
> 
> Different versions behave differently and newer versions have many performance improvements. The current chromium version for example is a bit dated 😬

Playwright does only support one of the latest versions of Chromium since we rely on features in the Chrome DevTools Protocol which were added especially because of Playwrights needs.

To use a different version which is a few weeks behind would probably work but does not make much sense then.

**Comment by Granitosaurus** [comment]
> Playwright does only support one of the latest versions of Chromium

I think you misunderstood me. The current version that comes installed right now is `792639` where the newest one at the time of writing is:
```
$ curl https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2FLAST_CHANGE?alt=media                                                                                                                      
798041
```

Nevertheless it would be nice to have control over which version of the browser playwright automates. I've tried changing `browsers.json` but seems like it's only being picked up by `install` command and playwright's code is not picking up the change.

**Comment by pavelfeldman** [comment]
You can pass `executablePath` into `launch` and use any browser at your own risk!

**Comment by mxschmitt** [comment]
You can as Pavel outlined the executablePath. There are no plans to support custom versions and using executablePath is at your own risk.

**Comment by yejimeiming** [comment]
> Unfortunately it's not possible to specify the revision since WebKit or Firefox are tight to the specific Playwright release, but we will allow in the future to only install a single browser. (For Chromium its not that bound but we still support only the given version).

Thanks for your answer, I think if I want to specify the version of `chromium`, maybe I can indirectly control the `chromium` version by specifying the `playwright` version.

```sh
npx playwright@1.48.1 install chromium
```
