### ISSUE TITLE
[Question]: Python Playwright Authentication

### ISSUE THREAD

**Issue by 0xanonymous-eth** [microsoft/playwright-python#1680]
### Your question

I'm trying to make a script that logs in on shopify account and save that session. I'm using 'storage = context.storage_state(path='my_path')' but it's returning empty cookies. The result is '{"cookies": [], "origins": []}'. The site don't have a pop up to accept cookies. Is this because of third party cookies if so is there a way for playwright to accept all that in settings?
<img width="294" alt="Screen Shot 2022-12-12 at 5 55 32 PM" src="https://user-images.githubusercontent.com/119305831/207207994-ec0277e2-cfcd-4213-a0f7-c267b740b8a5.png">

**Comment by mxschmitt** [comment]
Third party cookies _should_ be included in the session storage. Maybe you have a different context where you try to save the storage state from? Can you share some code about how you save the storage state?

**Comment by 0xanonymous-eth** [comment]
i log in then solve captcha then check if it's logged in. I don't have any problems with other sites like nike and yahoo. just getting this with shopify.

here's a snippet

try:
      page.wait_for_selector('text=Log Out', timeout=20000)
      print(strftime("%Y-%m-%d %H:%M:%S", localtime()) + ' - ' + f'Logged in {email}')
      logging.info(f'Logged in {email}')
      page.wait_for_timeout(randrange(10000, 15000))
      storage = context.storage_state(path='my_path')
     #some_code

except TimeoutError:
      #do something

**Comment by mxschmitt** [comment]
This looks like a scraping use-case and Playwright targets end-to-end testing. Thereby this is not actionable for us.
