### ISSUE TITLE
[BUG] Storage state type does not match the documentation

### ISSUE THREAD

**Issue by sueskind** [microsoft/playwright-python#1681]
**Context:**
- Playwright Version: 1.28.0
- Operating System: Linux 6.0.12-arch1-1
- Python version: 3.10.8
- Browser: All
- Extra: -

**Code Snippet**

```python
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    browser = p.chromium.launch()

    storage_state = {
        # something
    }
    context = browser.new_context(storage_state=storage_state)

    browser.close()
```

**Describe the bug**

The storage state of a context is usually set during creation from the "parent" browser instance via a path to a JSON file or directly from a dict. My report is concerned with the second case.

The type (without the obvious `Optional`) of the `storage_state` argument [is documented as `Union[str, pathlib.Path]|Dict`](https://playwright.dev/python/docs/api/class-browser#browser-new-context-option-storage-state) which is also my desired type. However, [it is implemented as `Union[StorageState, str, pathlib.Path]`](https://github.com/microsoft/playwright-python/blob/main/playwright/sync_api/_generated.py#L13349) which puts off type checkers such as mypy.

I think the type in the implementation should be changed to `Optional[Union[Dict, StorageState, str, pathlib.Path]]` and the documentation should match the implementation.

**Comment by mxschmitt** [comment]
Is the issue that we on playwright.dev mention `dict` instead of the more specific dict called `StorageState`?

You can as of today import the `StorageState` type and cast it or use it directly when creating the storage_state variable.

**Comment by sueskind** [comment]
Thank you. I think my issue was that PyCharm did not find the StorageState class in the sync API, and importing it from `playwright._impl._api_structures` seemed like a hack to me.

With casting you mean only while type checking, right? So the above example would look like this:

```python
from playwright.sync_api import sync_playwright, StorageState

with sync_playwright() as p:
    browser = p.chromium.launch()

    storage_state: StorageState = {
        # something
    }
    context = browser.new_context(storage_state=storage_state)

    browser.close()
```

This eliminates type checking errors by Mypy. Still, it is a bit unintuitive that the documented `dict` type is not usable by default. But I think the code above is a fine solution, so I will close this issue, thank you for your advise.
