### ISSUE TITLE
[Question]: How to get the text from shadow-root?

### ISSUE THREAD

**Issue by Jakyhack** [microsoft/playwright-python#1683]
With this example:

```
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    browser = p.firefox.launch(args=["--disable-gpu"], headless=False)
    page = browser.new_page()
    page.goto("https://googlechromelabs.github.io/shadow-selection-polyfill/demo.html")
    print(page.locator('#host1').inner_text())
```

Is there any way of getting this text?
![Screenshot from 2022-12-14 12-53-54](https://user-images.githubusercontent.com/47178010/207588707-40a05deb-aeee-4721-a26c-1b4f88ce228c.png)

If I run my code I get only this one: `I'm some content in the DOM`

**Comment by Jimmy-L99** [comment]
Did you find the solution? I want to get the content below the shadow-root(close).
