### ISSUE TITLE
Windows driver: "driver-win.exe install returned non-zero exit status 1."

### ISSUE THREAD

**Issue by WSUmlaut** [microsoft/playwright-python#169]
## Issue description:
Python version of playwright is installed inside a python venv. Running 'python -m playwright install' commands ends in 'driver-win.exe install returned non-zero exit status 1' error.

## Versions used:
1. Win 10
2. Python 3.8.1
3. playwright-python 0.7.1

## Steps to recreate:
1. Create python venv with command: 'python -m venv playwright_test'.
2. Activate venv.
3. Install playwright-python with command 'pip install playwright'.
4. Issue command 'python -m playwright install'.
5. Observe and error: 'subprocess.CalledProcessError: Command '<path>\driver-win.exe install' returned non-zero exit status 1.

## Problem description:
File 'driver-win.exe' is nowhere to be found and playwright installer does not download it. Searched the repo, can't see it there.

**Comment by mxschmitt** [comment]
Thanks for filing the bug repot, we have identified the issue and will be fixed during the day.

As a workaround you can install `wheel` first and then `playwright` which should work.

```
pip install wheel
pip install playwright
python -m playwright install
```

**Comment by WSUmlaut** [comment]
Hi, thanks for the tip - but it does not work. Or by 'wheel' you meant a *.whl file -> where would I get it?

Anyway:

(playwright_test) wjo@A0025153 C:\_PROJECT\playwright_test
**$ pip install wheel**
Collecting wheel
  Using cached wheel-0.35.1-py2.py3-none-any.whl (33 kB)
Installing collected packages: wheel
Successfully installed wheel-0.35.1

(playwright_test) wjo@A0025153 C:\_PROJECT\playwright_test
**$ pip install playwright**
Collecting playwright
  Using cached playwright-0.7.1.tar.gz (457 kB)
Collecting greenlet
  Using cached greenlet-0.4.16-cp38-cp38-win32.whl (17 kB)
Collecting pyee
  Using cached pyee-7.0.2-py2.py3-none-any.whl (12 kB)
Collecting typing-extensions
  Using cached typing_extensions-3.7.4.2-py3-none-any.whl (22 kB)
Building wheels for collected packages: playwright
  Building wheel for playwright (setup.py) ... done
  Created wheel for playwright: filename=playwright-0.7.1-py3-none-any.whl size=135116 sha256=a845984cc3e9ba02a742ddc8d44e9f01f327ac1bc9b919726a21fc1599b31b53
  Stored in directory: c:\users\wjo\appdata\local\pip\cache\wheels\64\2a\fc\ce0889ec4604e2675f3f3852e4e287a93593f4d4984096a636
Successfully built playwright
Installing collected packages: greenlet, pyee, typing-extensions, playwright
Successfully installed greenlet-0.4.16 playwright-0.7.1 pyee-7.0.2 typing-extensions-3.7.4.2

(playwright_test) wjo@A0025153 C:\_PROJECT\playwright_test
**$ python -m playwright install**
Installing the browsers...
'C:\_PROJECT\playwright_test\lib\site-packages\playwright\drivers\driver-win.exe' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\_PROJECT\playwright_test\lib\site-packages\playwright\__main__.py", line 17, in <module>
    main()
  File "C:\_PROJECT\playwright_test\lib\site-packages\playwright\main.py", line 131, in main
    subprocess.check_call(f"{driver_executable} install", shell=True)
  File "C:\Python38\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
**_subprocess.CalledProcessError: Command 'C:\_PROJECT\playwright_test\lib\site-packages\playwright\drivers\driver-win.exe install' returned non-zero exit status 1._**

(playwright_test) wjo@A0025153 C:\_PROJECT\playwright_test

Am I missing something here?

**Comment by mxschmitt** [comment]
The executed commands look fine, probably its a caching issue. Let's try `pip install playwright --no-cache-dir`. We somehow have to archive that Pip will use the Wheel package instead of the tar.gz file.

**Comment by WSUmlaut** [comment]
No, same thing.
```
(playwright_test) wjo@A0025153 C:\_PROJECT\playwright_test
**$ pip install wheel**
Collecting wheel
  Using cached https://files.pythonhosted.org/packages/a7/00/3df031b3ecd5444d572141321537080b40c1c25e1caa3d86cdd12e5e919c/wheel-0.35.1-py2.py3-none-any.whl
Installing collected packages: wheel
Successfully installed wheel-0.35.1

(playwright_test) wjo@A0025153 C:\_PROJECT\playwright_test
**$ pip install playwright --no-cache-dir**
Collecting playwright
  Downloading playwright-0.7.1.tar.gz (457 kB)
     |████████████████████████████████| 457 kB 1.1 MB/s
Collecting greenlet
  Downloading greenlet-0.4.16-cp38-cp38-win32.whl (17 kB)
Collecting pyee
  Downloading pyee-7.0.2-py2.py3-none-any.whl (12 kB)
Collecting typing-extensions
  Downloading typing_extensions-3.7.4.2-py3-none-any.whl (22 kB)
Building wheels for collected packages: playwright
  Building wheel for playwright (setup.py) ... done
  Created wheel for playwright: filename=playwright-0.7.1-py3-none-any.whl size=135116 sha256=1a5c46aa6a91dcec482142471e2237a4044131f36cedc1afd09aecb42e22c5f0
  Stored in directory: C:\Users\wjo\AppData\Local\Temp\pip-ephem-wheel-cache-tjepl2ar\wheels\64\2a\fc\ce0889ec4604e2675f3f3852e4e287a93593f4d4984096a636
Successfully built playwright
Installing collected packages: greenlet, pyee, typing-extensions, playwright
Successfully installed greenlet-0.4.16 playwright-0.7.1 pyee-7.0.2 typing-extensions-3.7.4.2

(playwright_test) wjo@A0025153 C:\_PROJECT\playwright_test
**$ python -m playwright install**
Installing the browsers...
'C:\_PROJECT\playwright_test\lib\site-packages\playwright\drivers\driver-win.exe' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\_PROJECT\playwright_test\lib\site-packages\playwright\__main__.py", line 17, in <module>
    main()
  File "C:\_PROJECT\playwright_test\lib\site-packages\playwright\main.py", line 131, in main
    subprocess.check_call(f"{driver_executable} install", shell=True)
  File "C:\Python38\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\_PROJECT\playwright_test\lib\site-packages\playwright\drivers\driver-win.exe install' returned non-zero exit status 1.
```

Maybe I should get the 'driver-win.exe' file manually somehow? It is not present in the directory:
```
$ dir C:\_PROJECT\playwright_test\lib\site-packages\playwright\drivers\
 Volume in drive C is Windows
 Volume Serial Number is 8609-E2F1

 Directory of C:\_PROJECT\playwright_test\lib\site-packages\playwright\drivers

17-Aug-20  13:38    <DIR>          .
17-Aug-20  13:38    <DIR>          ..
17-Aug-20  13:38               350 browsers.json
               1 File(s)            350 bytes
               2 Dir(s)  158,895,030,272 bytes free
```

**Comment by mxschmitt** [comment]
Thats probably a better workaround which should work (Windows only this link):
```
pip install https://files.pythonhosted.org/packages/7b/80/360183196f6463330f1e0cc2a7d0181f18f58a30a1b506cc397310398eef/playwright-0.7.1-py3-none-manylinux1_x86_64.whl
```

(obtained the URL from here: https://pypi.org/project/playwright/#files)

The `.exe` will be downloaded automatically normally.

**Comment by WSUmlaut** [comment]
No luck.
```
$ pip install playwright-0.7.1-py3-none-win_amd64.whl
ERROR: playwright-0.7.1-py3-none-win_amd64.whl is not a supported wheel on this platform.
```
Can't tell why. Something went wrong building WHL file?

**Comment by mxschmitt** [comment]
Hmm, are you using Windows 10 64 or 32 bit?

(could be, but we want to get rid of adding the driver into the wheel / source distribution file and download it e.g. from GitHub.)

**Comment by WSUmlaut** [comment]
It is Win 10 64 bit.
```
(playwright_test) wjo@A0025153 C:\_PROJECT\playwright_test
$ set pro
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=8e0a
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=(playwright_test) $E[m$E[32m$E]9;8;"USERNAME"$E\@$E]9;8;"COMPUTERNAME"$E\$S$E[92m$P$E[90m$_$E[90m$$$E[m$S$E]9;12$E\
```

On an optimistic note - it does work on Linux machine. Only Windows does not cooperate. Unfortunately, Windows is what I need at this time.

**Comment by mxschmitt** [comment]
@WSUmlaut it seems that our wheel is broken, I try it fix it and test it on my VM.

**Comment by WSUmlaut** [comment]
If you need me to re-test something and provide results/additional info, just let me know. Won't guarantee real-time answers, but will help ASAPA (_"as soon as project-time allows"_). Thanks!

**Comment by mxschmitt** [comment]
Probably you have a 32 bit version Python installed? (Try to use a x64 one from here: https://www.python.org/downloads/windows/)

**Comment by WSUmlaut** [comment]
Using 64bit Python 3.8.5:
```
Playwright is now ready for use
```

How could I miss that? In my defense - Linux machine by default uses 64 version, so I most likely blindsided myself. Thanks for your help. Not a bug after all.
