### ISSUE TITLE
PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS=1 warns to stdout and breaks transport protocol

### ISSUE THREAD

**Issue by kalekseev** [microsoft/playwright-python#1699]
**Context:**
- Playwright Version: 1.29.0

**Describe the bug**

playwright writes to stdout when `PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS=1` is set https://github.com/microsoft/playwright/blob/7508c574e12e31c774668b717f3c2449a82565b1/packages/playwright-core/src/server/registry/index.ts#L657
and that breaks transport protocol that expects 4 bytes length + json on stdout https://github.com/microsoft/playwright-python/blob/eb4b88af72aa6757c95f5a74f11ad6503bf16038/playwright/_impl/_transport.py#L140-L160

**Comment by mxschmitt** [comment]
Fix will go live in 1.30.
