### ISSUE TITLE
[Question]: About getting picture

### ISSUE THREAD

**Issue by FuckAnyProblem** [microsoft/playwright-python#1708]
### Your question

How can I get the image directly from the loaded page instead of requesting again after getting the link through the element?

**Comment by sueskind** [comment]
I don't think there is a dedicated way for what you want to achieve, maybe a dev can correct me on that. However, I have a couple of workarounds which should work depending on your use case:

- Intercepting the browser's initial request for the image with `page.expect_request()` or `page.on("request")`
- Screenshotting the element with `locator.screenshot()`
- Accessing the image bytes in JavaScript with `page.evaluate()`

**Comment by mxschmitt** [comment]
Closing as per above!
