### ISSUE TITLE
[Question]: argument ignoring in pytest and selenium hub

### ISSUE THREAD

**Issue by ParingerGH** [microsoft/playwright-python#1718]
### Your question

I'm trying to launch my tests in headed mode with video recording. But where is a grey line at the bottom of the out videos

I'm using this fixture to disable the "automation notification"

```
@pytest.fixture(scope="session")
def browser_type_launch_args(browser_type_launch_args):
    return {
        **browser_type_launch_args,
        "handle_sigint":True,
        "ignore_default_args":["--enable-automation"],
        "channel":"chrome",
    }
```

but notification appears anyway

if i close notification manually the the grey line disappears on the video and page can be seen fully

**Comment by mxschmitt** [comment]
For that you can override the `browser_type_launch_args` fixture, see here: https://playwright.dev/python/docs/test-runners#fixtures

Closing by that.
