### ISSUE TITLE
[Docs] Fix "REPL support without context managers" section code example

### ISSUE THREAD

**Issue by Igur007** [microsoft/playwright-python#173]
Fix "REPL support without context managers" section code example

```
from playwright import sync_playwright
playwright = sync_playwright().start()
```

sync_playwright() returns SyncPlaywrightContextManager that has no start() method

**Comment by mxschmitt** [comment]
I just released a new version 0.8.0. Should be available in a few minutes: https://github.com/microsoft/playwright-python/releases/tag/v0.8.0
