### ISSUE TITLE
[Question]: Error to run py script from php

### ISSUE THREAD

**Issue by gosha99** [microsoft/playwright-python#1731]
### Your question

I'm trying to start this python script from php
```
#!/usr/bin/ python
# -*- coding: utf-8 -*-
import asyncio
from playwright.async_api import async_playwright

async def main():
    async with async_playwright() as p:
        browser = p.firefox
        browser = await browser.launch()
        page = await browser.new_page()
        await page.goto('https://google.de')
        print (await page.content())
        await browser.close()

asyncio.run(main())
```
I'm getting this error
```
Traceback (most recent call last):
  File "/var/www/html/crawler2.py", line 20, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/var/www/html/crawler2.py", line 14, in main
    browser = await browser.launch()
  File "/usr/local/lib/python3.9/dist-packages/playwright/async_api/_generated.py", line 14007, in launch
    await self._impl_obj.launch(
  File "/usr/local/lib/python3.9/dist-packages/playwright/_impl/_browser_type.py", line 93, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "/usr/local/lib/python3.9/dist-packages/playwright/_impl/_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "/usr/local/lib/python3.9/dist-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
    return await cb()
  File "/usr/local/lib/python3.9/dist-packages/playwright/_impl/_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Executable doesn't exist at /var/www/.cache/ms-playwright/firefox-1369/firefox/firefox
```
When i'm trying to run via terminal, everything is working fine. The issue seems to be with this /var/www/.cache/ms-playwright/firefox-1369/firefox/firefox .

The firefox browser is installed here /.cache/ms-playwright/firefox-1369/firefox/firefox.

Where this /var/www/ is comming from?

This is my php code to start crawler2.py

```
<?php 
$command = escapeshellcmd('python /var/www/html/crawler2.py');
$output = shell_exec($command);
echo $output;
?>
```
How to fix it? Thanks.

**Comment by mxschmitt** [comment]
This is mostly because `www` is its own user and browsers are installed per user with Playwright. To fix this there are two solutions:

a) hardcode the Playwright browser path, see [here](https://playwright.dev/python/docs/browsers#managing-browser-binaries).
b) install the Playwright browsers with the `www` user, switch to the `www` user and execute `python -m playwright install`.

a) is the most straightforward for your scenario most likely.

**Comment by gosha99** [comment]
Thanks for the answer!
I have tried to change the browser path in my php code:
`$command = escapeshellcmd('PLAYWRIGHT_BROWSERS_PATH=/root/.cache/ms-playwright python /var/www/html/crawler2.py');`

Now the path looks ok, but it is still not executable
`Executable doesn't exist at /root/.cache/ms-playwright/firefox-1369/firefox/firefox`

Is that, because Playwright must be installed withe the `www` user?

**Comment by mxschmitt** [comment]
now you need to execute python -m playwright install with the root user.
