### ISSUE TITLE
[BUG] Error generating PDF (blank or format error)

### ISSUE THREAD

**Issue by PedroPessuto** [microsoft/playwright-python#1732]
**Context:**
- **Playwright Version:** 1.29.1
- **Operating System:** Windows
- **Python version:** 3.8.2
- **Browser:** Chromium

**Describe the bug**

This error happens in some specific situations, usually when directly or indirectly opening a pdf preview page.

```
def test():

  from playwright.sync_api import sync_playwright
  with sync_playwright() as p:
    browser = p.chromium.launch(headless=False)  _**#In this situation, with headless set to False, the blank pdf is issued, but when set to True, it is not possible to send it. Any suggestion?**_
    context = browser.new_context()
    page = context.new_page()
    page.goto('https://nyc3.digitaloceanspaces.com/midia/wp-content/uploads/2023/01/4tmrioel-sample.pdf')
    page.pdf(path='Test.pdf', format='A4')
test()
```

For example, in the code snippet below, the pdf is generated empty, blank (the screenshots are black with no content). I noticed that this error happened because of the speed, so I used
the sleep library, as wait_for_load_state() does not work in this case.
However, the new generated pdfs come out with the wrong formatting (here is an attached image showing a print, I hid the content, but the layout is the same withou the black)

![demo](https://user-images.githubusercontent.com/116746646/213877507-79607e04-7203-40b3-a914-d4009fa9f434.png)

My theory is that the page generates like this because of the chromium pdf viewer summary. So, I tried to disable it in this code:

```
def test():

  from playwright.sync_api import sync_playwright
  from time import sleep

  with sync_playwright() as p:
    # browser = p.chromium.launch(headless=False)
    browser = p.chromium.launch_persistent_context(user_data_dir=r'C:\Users\pedro\AppData\Local\Temp\playwright_chromiumdev_profile-AidV4Q\Default', args=['--print-to-pdf', '--disable-extensions', '--print-to-pdf-no-header'], headless=False)
    page = browser.new_page()
    page.goto('https://nyc3.digitaloceanspaces.com/midia/wp-content/uploads/2023/01/4tmrioel-sample.pdf')
    sleep(5)
    page.pdf(path='test.pdf', format='A4')
    input()

test()
```

Still, I couldn't solve the problem.
Details: Unable to run these codes in Headless mode, chromium appears to be being automated (making detection easier). So, does anyone have a solution to my problem?

I also tried downloading with CTRL + S, but that didn't work either. The keyboard doesn't seem to work on mine... do yours work? This was the code I used:

```
def test():

  from playwright.sync_api import sync_playwright
  from time import sleep

  with sync_playwright() as p:
    browser = p.chromium.launch(headless=False)
    page = browser.new_page()
    page.goto('https://nyc3.digitaloceanspaces.com/midia/wp-content/uploads/2023/01/4tmrioel-sample.pdf')
    sleep(3)
    with page.expect_download() as info:
      page.keyboard.press('Control+S')
      page.keyboard.press('Enter')
    download = info.value
    download.save_as(path='teste.pdf')
    input()

test()
```

**Comment by PedroPessuto** [comment]
The screenshots also come out with nothing, they are completely black. Does anyone have any alternatives?

**Comment by mxschmitt** [comment]
Why do you want to create a PDF out of a PDF file? Just download the PDF directly, e.g. using our REST client: https://playwright.dev/python/docs/api/class-apirequestcontext#api-request-context-get

**Comment by PedroPessuto** [comment]
Thank you for the tips! I am learning.
How would you download the pdf file from a pdf page using the REST client?

**Comment by mxschmitt** [comment]
```python
response = page.request.get(page.url)
with open("output.pdf", "wb") as f:
    f.write(response.body())
```

Something like that should work.

**Comment by mxschmitt** [comment]
Closing as per above. Please file new issues for more questions.
