### ISSUE TITLE
[Question]: Path to the playwright driver

### ISSUE THREAD

**Issue by jean-edouard-boulanger** [microsoft/playwright-python#1735]
### Your question

Hello 👋 

I am currently looking into running the playwright driver as a different user, or in a different network namespace (`ip netns exec`) than the Python process using Playwright.

I currently achieve this by replacing the Playwright driver script with a shell script that calls the real playwright driver script after initializing a bunch of things.

```
+------------------------------------+       +-----------------------------+             +-----------------------------+
| Script running Playwright (user 1) |  ==>  | Fake driver script (user 1) | == sudo ==> | Real driver script (user 2) |
+------------------------------------+       +-----------------------------+             +-----------------------------+ 
```

Sadly, I have not found any documented way to specify a custom Playwright driver path, and I have relied on this internal API to find / replace the existing Playwright driver by a "fake" (wrapper) one (which feels quite hacky):

```python
from playwright._impl._driver import compute_driver_executable
```

My question is the following:

1. Is there a way to find this path using a public/stable API? (this seems to be made available for other Playwright clients - I found some issues pointing to that for Java/.net/ruby clients).
2. If not, would you consider making this path public in future playwright-python releases?

Many thanks

**Comment by mxschmitt** [comment]
This is unfortunately out of the scope for the Playwright project. We recommend doing the initialization in the parent process rather than inside Playwright itself since this is very specific to your use-case. Alternatively you can fork Playwright so it fulfills your needs.
