### ISSUE TITLE
[Question]: Get response after clicking on a link

### ISSUE THREAD

**Issue by Umzario** [microsoft/playwright-python#1747]
### Your question

Hey guys, is there any way to get the response after clicking on a link on a page without knowing the link URL? Example: On www.example.com, there's a link to click on called under `More information...`, is there a way to click that link and get the response details for that (status code, text etc). I know of `page.expect_response`, but it seems that you need to know the link URL for that (I might be mistaken). I hope this made sense

**Comment by Umzario** [comment]
Thanks for the reply. I thought `page.expect_navigation` was depreciated as seen in the [docs](https://playwright.dev/python/docs/api/class-page#page-wait-for-navigation). 

I received an error also while using with with `page.expect_navigation() as navigation_info`:
`AttributeError: __enter__`

Here's what I'm trying to achieve:
```
        browser = await p.chromium.launch()
        page = await browser.new_page()
        await page.goto("https://www.example.com")

        with page.expect_navigation() as navigation_info:
            await page.get_by_text("More information").click()
        response = navigation_info.value
        print(response.status)

        await browser.close()
```

**Comment by mxschmitt** [comment]
You are using async, then you need to do:

```python
import asyncio
from playwright.async_api import async_playwright

async def main():
    async with async_playwright() as p:
        browser = await p.chromium.launch()
        page = await browser.new_page()
        await page.goto("https://www.example.com")

        async with page.expect_navigation() as navigation_info:
            await page.get_by_text("More information").click()
        response = await navigation_info.value
        print(response.status)

        await browser.close()

asyncio.run(main())
```

**Comment by mxschmitt** [comment]
(Regarding why wait_for_navigation is not recommended, usually you never need it, except for such rare use-cases. We used to have it for every click with a asyncio.gather but click is also waiting for navigations to happen, so it was unnecessary.)
