### ISSUE TITLE
[BUG] Browser is not saved in the correct folder

### ISSUE THREAD

**Issue by Walterwhite233** [microsoft/playwright-python#1751]
Hello, I had found the error here before, but the issue was not fully resolved (last comment).... 
https://github.com/microsoft/playwright-python/issues/494

**Context:**
- Playwright Version: 1.27.1
- Operating System: Windows
- Python version: 3.10.9
- Browser: All
- Extra: -

**Describe the bug**
I am trying in vain to create an exe with PyInstaller...

Method:
1. virtualenv venv
2. venv/Scripts/activate
3. set PLAYWRIGHT_BROWSERS_PATH=0
4. pip install playwright
5. playwright install firefox

I've just tried everything.. any python versions and old Playwrith versions... **the folder ".local-browsers/" is not created**... I managed it once with a lot of luck.. but that was an exception.. does something not work on windows?? I would appreciate an answer <3

Walter

**Comment by mxschmitt** [comment]
You are inside PowerShell, if you are inside PowerShell you need to set environment variables by doing the following:

```powershell
$Env:PLAYWRIGHT_BROWSERS_PATH=0
```

then it works for me.

**Comment by Walterwhite233** [comment]
the missing "$Env:" was it :D Thank you!!
