### ISSUE TITLE
[Question]: linux issue when run 

### ISSUE THREAD

**Issue by garyzhang21** [microsoft/playwright-python#1759]
### Your question

       ╔══════════════════════════════════════════════════════╗
E       ║ Host system is missing dependencies to run browsers. ║
E       ║ Missing libraries:                                   ║
E       ║     libatk-bridge-2.0.so.0                           ║
E       ║     libdrm.so.2                                      ║
E       ║     libatspi.so.0                                    ║
E       ║     libgbm.so.1                                      ║
E       ╚══════════════════════════════════════════════════════╝

what should i do ? 
i tried playwright install chromium --with-deps but it not works.

**Comment by mxschmitt** [comment]
Which Linux distribution are you using?

**Comment by garyzhang21** [comment]
Linux version 3.10.0-1160.49.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Tue Nov 30 15:51:32 UTC 2021

**Comment by mxschmitt** [comment]
That's not supported
