### ISSUE TITLE
[Question]: Playwright uses asyncio instead of sync mode

### ISSUE THREAD

**Issue by NeONRAcE** [microsoft/playwright-python#1760]
### Your question

Hi, guys! Could you help me with the sync mode, please?

I start 2 specs in a worker (one by one), the first spec passes successfully, the second one always fails with error: 
`It looks like you are using Playwright Sync API inside the asyncio loop. Please use the Async API instead.`

Conftest file:
```
@pytest.fixture(scope='function')
def page_context():
    pw = sync_playwright().start()
    browser = pw.chromium.launch(headless=False)
    context = browser.new_context(
        viewport={"width": 1920, "height": 1080}
    )
    context.tracing.start(screenshots=True, snapshots=True, sources=True)
    page = context.new_page()
    yield page
    context.tracing.stop(path=f'{current_dir}/reports/trace.zip')
    context.close()
    browser.close()
```

Specs are simple as possible, first one is:
```
def test1(page_context):
    page_context.goto('https://google.com')
```
the other one is (in another file):
```
def test2(page_context):
    page_context.goto('https://google.com')
```
Could you advise me what to do to exclude using asyncio? It's not necessary for such simple specs according to official docs. 

PS: with "scope=session" some mystery things happen. Code looks to run action by action, but there aren't any logs. It seems like all actions are doing synchronously in a time
PPS Session doesn't reset after each spec, the next test starts from the last step of a previous test

**Comment by mxschmitt** [comment]
You don’t stop Playwright. I recommend to just start it once via pw = sync_playwright().start() and move it to the global scope. (Outside the fixture) Alternatively you can call pw.stop() over and over again which should work.

**Comment by aslushnikov** [comment]
Closing this as per Max's answer. Please do not hesitate to file a new issue if you think we still can be helpful!
