### ISSUE TITLE
[Question]: The count method doesn't return the count of the locator being used

### ISSUE THREAD

**Issue by farhan528** [microsoft/playwright-python#1763]
### Your question

I have a page object class in python and the driver reference that we are using is like < 'self.driver.locator(self.webelement).count' > I am trying to get the count of an element on the webpage but instead of returning the count of the web element of the 'int' type it is returning the web element reference itself.
Not sure why is this happening and what is the correct way of using it.

Using playwright python integrated with pytest.

**Comment by aslushnikov** [comment]
@farhan528 can you share some code snippets of what you do and what you expect it to do?
