### ISSUE TITLE
[Question]: how to check browser has been started and connect to existing instance

### ISSUE THREAD

**Issue by procolost** [microsoft/playwright-python#1764]
### Your question

How to check browser has been started and connect to existing instance?
I develop in jupyter and i have a lot lot run browser instance

**Comment by aslushnikov** [comment]
@procolost I'm not sure I follow the question. What exactly are you trying to achieve?

**Comment by procolost** [comment]
> @procolost I'm not sure I follow the question. What exactly are you trying to achieve?

i try this library in jupyter
and i restart the cell, this spawns a new browser
Need like this 
```
async def launchorconnect(*args):
    p=await aapi.async_playwright().start()
    if browserisexist():

        return await p.chromium.connect()
    else:
        return  await p.chromium.launch(channel="chrome",proxy=proxyd,headless=False )
```

**Comment by mxschmitt** [comment]
This is outside of the scope of Playwright and can be done in the user-land. Starting the browser with the --remote-debugging-port argument and then future users can connect to it.
