### ISSUE TITLE
[Question]:trace.json performance testing profile python

### ISSUE THREAD

**Issue by jannostudio** [microsoft/playwright-python#1765]
### Your question

```
import time
from playwright.sync_api import Playwright, sync_playwright, expect
import json

def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False, devtools=True)
    context = browser.new_context()
    page = context.new_page()
    session = context.new_cdp_session(page)
    session.send('Performance.enable')
    context.tracing.start(screenshots=True, snapshots=True, sources=True)
    page.goto("url")
    page.wait_for_load_state("networkidle")
    page.get_by_role("link", name="Reserve", exact=True).click()
    time.sleep(3)
    page.get_by_placeholder("Email").click()
    session.send('Performance.getMetrics')
    context.tracing.stop(path='./trace.zip')


    session.detach()

    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
```

I am trying to get a performance trace like this guy in this [video ](https://www.youtube.com/watch?v=IrK-XDH72bw&t=1872s)in python.

I understand that the trace created can be viewed in the trace viewer, but i doesnt contain the performance details.

I also cannot import the created trace.zip in chrome devtools, because its no valid json. How on earth does this work?

In essence how do i greate a profile.json with playwright in python for chromium programatically?

**Comment by aslushnikov** [comment]
@jannostudio There are two kinds of tracing:
- Chromium tracing, that could be created with [`browser.start_tracing`](https://playwright.dev/python/docs/api/class-browser#browser-start-tracing)
- Playwright tracing: https://playwright.dev/python/docs/next/api/class-tracing

In the video you're referring two, Chromium tracing is used, so you should use the `browser.start_tracing` API:

```py
browser.start_tracing(page, path="trace.json")
page.goto("https://www.google.com")
browser.stop_tracing()
```

Hope this helps!
