### ISSUE TITLE
[Question] How Start multiple browser in parallel with threading?

### ISSUE THREAD

**Issue by mrthevinh** [microsoft/playwright-python#177]
```py
from playwright import sync_playwright
import threading

def start_browser(browser_type):
    browser = browser_type.launch(headless=False)
    page = browser.newPage()
    page.goto('http://whatsmyuseragent.org/')
    page.screenshot(path=f'example-{browser_type.name}.png')
    browser.close()
    
def main():
    with sync_playwright() as p:
        threads = []
        for browser_type in [p.chromium, p.firefox, p.webkit]:
            t = threading.Thread(target=start_browser, args=(browser_type,))
            t.start()
            threads.append(t)
        for t in threads:
            t.join()    

if __name__ == '__main__':
    main()
```
greenlet.error: cannot switch to a different thread

**Comment by mxschmitt** [comment]
Thanks for the detailed issue. With the current implementation on our side its unfortunately not possible to use threads. What are you trying to implement? Maybe you can use the asyncio variant and use e.g. asyncio.gather to do things in parallel. We are curious in what your use case is, thanks!

**Comment by mrthevinh** [comment]
> Thanks for the detailed issue. With the current implementation on our side its unfortunately not possible to use threads. What are you trying to implement? Maybe you can use the asyncio variant and use e.g. asyncio.gather to do things in parallel. We are curious in what your use case is, thanks!

Thank for reply! Now I used the asyncio for it! So I like playwright so much! Thank  playwright team

**Comment by mxschmitt** [comment]
Cool thanks for letting us know!
