### ISSUE TITLE
[Question]: is a slim/Alpine build worth it?

### ISSUE THREAD

**Issue by robertlagrant** [microsoft/playwright-python#1770]
### Your question

Is it worth adding slimmer builds? The image is quite heavy due to the unavoidable browser install sizes; I wondered if some space could be shaved off if the base images were a little lighter.

**Comment by mxschmitt** [comment]
Alpine Linux is not supported, only Debian and Ubuntu. If you want a smaller image, you can install just the deps / browsers for a single browser via `python -m playwright install chromium --with-deps` and use a Debian 11 image directly.
