### ISSUE TITLE
[Question]: I run playwright failed.My program block at sync_playwright()

### ISSUE THREAD

**Issue by rggaoxin** [microsoft/playwright-python#1773]
### Your question

Hi, I'm trying to run an example as follows.
```

from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    for browser_type in [p.chromium, p.firefox, p.webkit]:
        browser = browser_type.launch()
        page = browser.new_page()
        page.goto('http://whatsmyuseragent.org/')
        page.screenshot(path=f'example-{browser_type.name}.png')
        browser.close()
```

the program blocked at 'with sync_playwright() as playwright:'.

and when I stop the program, the ternimal print the information as follows:

```
C:\Users\H458951\AppData\Local\Programs\Python\Python311\python.exe C:\code\playwright-test\test.py 
Traceback (most recent call last):
  File "C:\code\playwright-test\test.py", line 3, in <module>
    with sync_playwright() as p:
  File "C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\sync_api\_context_manager.py", line 88, in __enter__
    dispatcher_fiber.switch()
  File "C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\sync_api\_context_manager.py", line 67, in greenlet_main
    self._loop.run_until_complete(self._connection.run_as_sync())
  File "C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
^C  File "C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1884, in _run_once
    event_list = self._selector.select(timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
  File "C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 817, in _poll
    status = _overlapped.GetQueuedCompletionStatus(self._iocp, ms)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<Connection.run.<locals>.init() running at C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_connection.py:245> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[ProtocolCallback.__init__.<locals>.cb() at C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_connection.py:168]>
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x0000000003024D60>
Traceback (most recent call last):
  File "C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_subprocess.py", line 126, in __del__
  File "C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_subprocess.py", line 104, in close
  File "C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py", line 109, in close
  File "C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 761, in call_soon
  File "C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 519, in _check_closed
RuntimeError: Event loop is closed
The process tried to write to a nonexistent pipe.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000000003026480>
Traceback (most recent call last):
  File "C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py", line 80, in __repr__
  File "C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_utils.py", line 102, in fileno
ValueError: I/O operation on closed pipe

Process finished with exit code -1073741510 (0xC000013A: interrupted by Ctrl+C)

```
Playwright Version: 1.30
Operating System: Windows 10
Python: 3.11/3.9/3.10
Browser: All

What's wrong with my computer?
Thanks.

**Comment by mohanrajreese** [comment]
@rggaoxin 
you have to install playwright properly on your computer.
checkout this [docs](https://playwright.dev/python/docs/library) and [this](https://playwright.dev/python/docs/intro)

then you can use headless = False parameter to view the browser actions

```
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    for browser_type in [p.chromium, p.firefox, p.webkit]:
        browser = browser_type.launch(headless=False)
        page = browser.new_page()
        page.goto('http://whatsmyuseragent.org/')
        page.screenshot(path=f'example-{browser_type.name}.png')
        browser.close()
```

**Comment by rggaoxin** [comment]
> @rggaoxin you have to install playwright properly on your computer. checkout this [docs](https://playwright.dev/python/docs/library) and [this](https://playwright.dev/python/docs/intro)
> 
> then you can use headless = False parameter to view the browser actions
> 
> ```
> from playwright.sync_api import sync_playwright
> with sync_playwright() as p:
>     for browser_type in [p.chromium, p.firefox, p.webkit]:
>         browser = browser_type.launch(headless=False)
>         page = browser.new_page()
>         page.goto('http://whatsmyuseragent.org/')
>         page.screenshot(path=f'example-{browser_type.name}.png')
>         browser.close()
> ```

I have install playwright and I run python code failed.
I run same codes in my mac and win11 successfully.
I donot know the reason.

**Comment by rggaoxin** [comment]
I run it in the cmd.It donot repsonde.I click "ctrl" + "z",it report：
```
Active code page: 65001
 
C:\Users\H458951>python
Python 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from playwright.sync_api import sync_playwright
>>> p = sync_playwright().start()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\sync_api\_context_manager.py", line 95, in start
    return self.__enter__()
           ^^^^^^^^^^^^^^^^
  File "C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\sync_api\_context_manager.py", line 88, in __enter__
    dispatcher_fiber.switch()
  File "C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\sync_api\_context_manager.py", line 67, in greenlet_main
    self._loop.run_until_complete(self._connection.run_as_sync())
  File "C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1884, in _run_once
^C    event_list = self._selector.select(timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
  File "C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 817, in _poll
    status = _overlapped.GetQueuedCompletionStatus(self._iocp, ms)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
>>> p = sync_playwright().start()
^CTraceback (most recent call last):
```

**Comment by mohanrajreese** [comment]
> I run it in the cmd.It donot repsonde.I click "ctrl" + "z",it report：
> ```
> Active code page: 65001
>  
> C:\Users\H458951>python
> Python 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from playwright.sync_api import sync_playwright
> >>> p = sync_playwright().start()
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\sync_api\_context_manager.py", line 95, in start
>     return self.__enter__()
>            ^^^^^^^^^^^^^^^^
>   File "C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\sync_api\_context_manager.py", line 88, in __enter__
>     dispatcher_fiber.switch()
>   File "C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\sync_api\_context_manager.py", line 67, in greenlet_main
>     self._loop.run_until_complete(self._connection.run_as_sync())
>   File "C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
>     self.run_forever()
>   File "C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
>     super().run_forever()
>   File "C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
>     self._run_once()
>   File "C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1884, in _run_once
> ^C    event_list = self._selector.select(timeout)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 444, in select
>     self._poll(timeout)
>   File "C:\Users\H458951\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 817, in _poll
>     status = _overlapped.GetQueuedCompletionStatus(self._iocp, ms)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> KeyboardInterrupt
> >>> p = sync_playwright().start()
> ^CTraceback (most recent call last):
> ```
> 

@rggaoxin 
If you want to run playwright using cmd. lt you have to install playwright globally. 
Why do you want to use cmd.lt for playwright when there are many IDEs available as open source

**Comment by mxschmitt** [comment]
Looks like the driver is not able to start, could you try `python -m playwright --help` to see if that works?

**Comment by rggaoxin** [comment]
> python -m playwright --help

I donot want to run it in cmd.Because I run it in python code failed.

**Comment by rggaoxin** [comment]
> Looks like the driver is not able to start, could you try `python -m playwright --help` to see if that works?

I think it work normal.

```
C:\Users\H458951>python -m playwright --help
Active code page: 65001
Usage: playwright [options] [command]

Options:
  -V, --version                          output the version number
  -h, --help                             display help for command

Commands:
  open [options] [url]                   open page in browser specified via -b, --browser
  codegen [options] [url]                open page and generate code for user actions
  install [options] [browser...]         ensure browsers necessary for this version of Playwright are installed
  install-deps [options] [browser...]    install dependencies necessary to run browsers (will ask for sudo permissions)
  cr [options] [url]                     open page in Chromium
  ff [options] [url]                     open page in Firefox
  wk [options] [url]                     open page in WebKit
  screenshot [options] <url> <filename>  capture a page screenshot
  pdf [options] <url> <filename>         save page as pdf
  show-trace [options] [trace...]        show trace viewer
  help [command]                         display help for command

C:\Users\H458951>

```

**Comment by mohanrajreese** [comment]
have you installed browser dependencies?.
if not use `playwright install` to install those and

**Comment by rggaoxin** [comment]
> have you installed browser dependencies?. if not use `playwright install` to install those and

I donot install any dependencies.I create a new venv and install dependencies.

**Comment by mxschmitt** [comment]
Maybe the issue is that its printing the "Active code page", looks like you can disable it via the registry: microsoft command processor autorun

**Comment by mxschmitt** [comment]
Could you try to run the basic script and set the `DEBUGP=1` environment variable? This should give some more debug information.

**Comment by mxschmitt** [comment]
Closing for now since this issue seems stale. Please re-file the issue with DEBUGP=1 env var.

**Comment by rggaoxin** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by nian0099** [comment]
I also encountered the same problem, hope you can get help
Playwright：1.30
Windows Server2022
Python：3.11/3.9/3.10

**Comment by rggaoxin** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
