### ISSUE TITLE
[Question]: send message in the websocket connectin

### ISSUE THREAD

**Issue by viponedream** [microsoft/playwright-python#1776]
### Your question

there's some ws connection on some page, can we use that connection to send something? or just only print the message?
```
     self.page.on("websocket", self.filter_websocket)
    async def filter_websocket(self, websocket):
        print(f'websocket:{websocket.url}')
        websocket.on("framesent",  self.handler_websocket_sent)
        websocket.on("framereceived", self.handler_websocket_received)
```

**Comment by mxschmitt** [comment]
As of today only sniffing is possible, here is a feature request for full interception: https://github.com/microsoft/playwright/issues/4488
