### ISSUE TITLE
[BUG] - Can't record video when mounting test-results folder in Docker

### ISSUE THREAD

**Issue by lucasmello** [microsoft/playwright-python#1781]
**Context:**
- Playwright Version: 1.30.0
- Operating System: Linux
- Python version: 3.8
- Browser: All
- Extra: 
    - Docker image: mcr.microsoft.com/playwright/python:v1.30.0-focal
    - Pytest
    - pytest-playwright==0.3.0

**Code Snippet**

My Dockerfile:

```bash
FROM mcr.microsoft.com/playwright/python:v1.30.0-focal
ARG PROJECT_PATH=.
ARG PIP_INDEX_URL
ARG PIP_TRUSTED_HOST
ENV PATH /usr/local/bin:/usr/bin:$PATH

WORKDIR /src
COPY $PROJECT_PATH/requirements.txt /src
RUN pip install -r /src/requirements.txt
RUN playwright install

COPY $PROJECT_PATH/ /src
```

How I mount volumes:
```bash
docker run --rm -it -v $(pwd)/data:/src/test-results e2e-tests bash
```

**Describe the bug**

When I run:

```bash
pytest --video on
```
I got the following error:

```bash
OSError: [Errno 16] Device or resource busy: 'test-results'
```

**Comment by mxschmitt** [comment]
Sounds like a Docker issue to me, what about instead mounting the whole src folder?

**Comment by lucasmello** [comment]
@mxschmitt thanks for the answer. That would work, but it wouldn't be ideal. I searched for this error and the node version of Playwright [had this same issue](https://github.com/microsoft/playwright/issues/12106). The error happened when deleting the folder, and they were treating errors in this process as fatal, so they changed this behavior. I wonder if we could have the same in Python.

**Comment by mxschmitt** [comment]
You are absolutely right! I created https://github.com/microsoft/playwright-pytest/pull/151 which applies our best-effort test-results removal logic and instead of deleting the whole folder, we then just delete the files which are inside.
