### ISSUE TITLE
[BUG] Couldn't connect to existing browser

### ISSUE THREAD

**Issue by x-mass** [microsoft/playwright-python#1784]
**Context:**
- Playwright Version: [what Playwright version do you use?]
- Operating System: macOS Monterey 12.4 (21F79)
- Python version: 3.10
- Browser: Chromium, Firefox
- Extra: None

**Code Snippet**

```python
from playwright.async_api import async_playwright
with async_playwright() as playwright_async:
    browser = await playwright_async.chromium.connect('ws://localhost:21022/devtools/browser/ad669491-07d7-45e5-9bcb-1234abcd5678')
```

**Describe the bug**

Open a browser with ```~/Library/Caches/ms-playwright/chromium-1048/chrome-mac/Chromium.app/Contents/MacOS/Chromium --remote-debugging-port=21022 --remote-debugging-address=0.0.0.0 --headless```. Copy connection string appeared in terminal and insert it into ```connect()``` function.
When trying to connect to an already running browser, connection fails. Also error parsing fails here, but it's not under the current discussion (expand for details).
<details><summary>Details about error parsing</summary>
<p>
In case of ```ECONNREFUSED``` error occurs in a following structure:

```
{
    'id': 2,
    'error': {
        'error': {
            'message': {some_message},
            'stack': {some_traceback},
            'name': 'Error'
        }
    }
}
```
but the error caused current issue has a structure of:
```
{
    'id': 1,
    'error': {
        'code': -32600,
        'message': "Message has property other than 'id', 'method', 'sessionId', 'params'"
    }
}
```
Could be fixed [here](https://github.com/microsoft/playwright-python/blob/92bb1d04132406fc5e2f0e086abbe1d1d1fe89c5/playwright/_impl/_connection.py#L305)
</p>
</details>

Error ```Message has property other than 'id', 'method', 'sessionId', 'params'``` occurs. Message is built [here](https://github.com/microsoft/playwright-python/blob/92bb1d04132406fc5e2f0e086abbe1d1d1fe89c5/playwright/_impl/_connection.py#L286), and contains, at least, extra `guid` and `metadata` fields. However, if one of these fields is commented out, the connection also fails (seems like they are necessary too).

If I try the same with Firefox, it don’t work either, but an error is different: `Invalid method format: 'initialize'`.

The only way to connect to an already launched browser I've found is `chromium.connect_over_cdp()` function.

**Comment by x-mass** [comment]
Also, I can't find the docs about tests usage. I think, looking at [test_browsertype_connect.py](https://github.com/microsoft/playwright-python/blob/main/tests/async/test_browsertype_connect.py) could help, but don't know how to launch it

**Comment by mxschmitt** [comment]
You need to use connect_over_cdp 

https://playwright.dev/python/docs/api/class-browsertype#browser-type-connect-over-cdp

**Comment by mxschmitt** [comment]
Why does connect_over_cdp not work for you? Thats the intended way of connecting to a Chromium CDP endpoint.

connect() is a different protocol, its Playwright's own protocol which works across all 3 browsers rather just with one browser.

[See here for the connect_over_cdp tests.](https://github.com/microsoft/playwright-python/blob/main/tests/async/test_browsertype_connect_cdp.py)

**Comment by x-mass** [comment]
@mxschmitt, how do I run such tests? Just `pytest ${filename}`?

> Why does connect_over_cdp not work for you?
It works for me, but it would be better if tests were able to be launched across different browsers without extra code.

> its Playwright's own protocol which works across all 3 browsers rather just with one browser. Thats why its not working.
Strange, that it works for 3 browsers, therefore works almost (I haven't checked WebKit) nowhere :D

**Comment by mxschmitt** [comment]
neither connect nor connect_over_cdp is supported by the pytest plugin. So you'd have to modify the fixtures yourself if this is the question you are asking.

See [here](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-server) how to launch a Playwright server which is only possible via JS directly.

**Comment by x-mass** [comment]
> See [here](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-server) how to launch a Playwright server which is only possible via JS directly.

So, `connect()` method is intended to be used only with browsers launched with `launchServer()`? [Doc](https://playwright.dev/python/docs/api/class-browsertype#browser-type-connect) says Playwright can be attached to an existing browser instance.

The question about tests is how anything from [playwright-python/tests](https://github.com/microsoft/playwright-python/tests) can be launched? As I see, documentation doesn't include this aspect.

**Comment by mxschmitt** [comment]
Yes, launchServer is only available from JS, but you can connect via any language port to it. Its correct that you can attach to existing browser instances, see and use its pages etc.

You need to manually create the Pytest test fixtures for it, so  manually connect to it etc. Its not a common scenario to connect to remote browsers to launch the tests, hence we don't have it, we recommend launching it on the same host as you are running your tests.

**Comment by x-mass** [comment]
> Its correct that you can attach to existing browser instances, see and use its pages etc.

Then it doesn't work as it should. For Chromium it could be done with `connect_over_cdp`, but what about Firefox?

> You need to manually create the Pytest test fixtures for it.

I think, either I misspoken or you misunderstood. How can playwright-python package tests be run? Not ones testing my app, but those testing the playwright package itself ([playwright-python/tests](https://github.com/microsoft/playwright-python/tree/main/tests) dir). I'm asking this, because it looks like there are test for a `connect` method. May be its successful launch will help to debug current connection issue

**Comment by mxschmitt** [comment]
Okay let me elaborate. So BrowserType.connect and BrowserType.launchServer work together. BrowserType.connect does only work with BrowserType.launchServer, not with CDP, etc. since it uses a custom protocol, hence the message error which got initially.

> Then it doesn't work as it should. For Chromium it could be done with connect_over_cdp, but what about Firefox?

You can launch a server, connect, disconnect, connect again and the pages are still there etc. This and being able to connect remotely is what this feature is about. 

CDP on the other hand, only works with chromium.connect_over_cdp. This uses the official CDP protocol under the hood and has similar functionalities, that you can re-connect to remote browers.

Note, that this only works with Chromium. Firefox CDP is no real CDP, hence its not supported, it does not support all the CDP features.

Regarding how to run the tests, see [here](https://github.com/microsoft/playwright-python/blob/main/CONTRIBUTING.md). You can pass a file name to pytest to run a single test.

Let me know if something is not clear.

**Comment by mxschmitt** [comment]
Closing as per above, for further questions please re-file.

**Comment by limenote** [comment]
我終於知道為什麽無法使用 connect()
