### ISSUE TITLE
[BUG] Browser does not close when `BrowserContext` object is released

### ISSUE THREAD

**Issue by SuperKenVery** [microsoft/playwright-python#1787]
**Context:**
- Playwright Version: 1.30.0
- Operating System: Linux `Linux asahi-ken 6.1.0-asahi-2-2-edge-ARCH #2 SMP PREEMPT_DYNAMIC Fri, 16 Dec 2022 05:04:23 +0000 aarch64 GNU/Linux`
- Python version: 3.10.8
- Browser: Firefox
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally.

```python
from playwright.sync_api import sync_playwright

def launch_browser():
    play=sync_playwright().start()
    browser=play.firefox
    context=browser.launch_persistent_context(user_data_dir="/tmp/a",headless=False)

launch_browser()
while True:
    input("Waiting keyboard interrupt...")

```

**Browser not closed**

The `play` (as well as `browser` and `context`) is released, but the browser is not closed.

**Comment by mxschmitt** [comment]
This sounds expected, you need to manually perform the following actions:

```python
context.close()
```

which will close the persistent context in your case

```python
play.stop()
```

which will close the playwright session.

Generally speaking we recommend using the context manager instead, since it will do the stuff for you: 

```python
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()
    page.goto("http://playwright.dev")
    print(page.title())
    browser.close()
```

**Comment by SuperKenVery** [comment]
Please have a look at [this](https://stackoverflow.com/questions/1834556/does-a-file-object-automatically-close-when-its-reference-count-hits-zero)

> Garbage collector will close file when it destroys file object

So, the same, garbage collector should automatically call the close?

**Comment by mxschmitt** [comment]
Playwright architecture requires you to call close since launching a browser is not a trivial operation. It requires launching processes which need to be closed gracefully. You basically want to control when it closes.

Closing as per above.
