### ISSUE TITLE
[Improvement] "Unresolved attribute reference 'stop' for classes SyncPlaywrightContextManager/ AsyncPlaywrightContextManager appears in IDE

### ISSUE THREAD

**Issue by Igur007** [microsoft/playwright-python#179]
When to use "REPL support without context managers", IDE shows inspection warning "Unresolved attribute reference 'stop' for classes SyncPlaywrightContextManager (for Async too).
It's because stop is registered not obviously, e.g. in line 96: _playwright.stop = self.__exit___  # type: ignore
It's better to implement the same solution for _stop()_ as with _start()_
**OR**
if to change e.g. in SyncPlaywrightContextManager:
1. delete def start(self)
2. delete playwright.stop = self.__exit__  # type: ignore (line 97)
3. in the end of the class after __exit__ add:
```
start = __enter__
stop = __exit__
```
4. line 96 playwright = self._playwright also seems not needed and can be deleted.

the 'Unresolved attribute reference' inspection in IDE will be fixed and everything will work as expected.
The same changes may be applied for Async for start/stop.

**Comment by mxschmitt** [comment]
Could you share with us the exact snippet which is causing that error? And which IDE are you using?

**Comment by Igur007** [comment]
PyCharm
when to use as:
```
from playwright import sync_playwright

sync_plw = sync_playwright()
sync_plw.start()
```
when later is needed to use sync_plw.stop() ---> stop method is not listed by IDE among available methods.

**Comment by mxschmitt** [comment]
The usage is a bit different, see this example:

```py
from playwright import sync_playwright

playwright = sync_playwright().start()
for browser_type in [playwright.chromium, playwright.firefox, playwright.webkit]:
    browser = browser_type.launch()
    page = browser.newPage()
    page.goto("http://whatsmyuseragent.org/")
    page.screenshot(path=f"example-{browser_type.name}.png")
    browser.close()

playwright.stop()

```

**Comment by Igur007** [comment]
thanks, I saw it before creation of this improvement ).

**Comment by mxschmitt** [comment]
Then I close it okay?

**Comment by Igur007** [comment]
of course, you can. My purpose was if I can control an instance of a context manager with the start method, why I need to use __exit__ or not obviously defined "stop". Everything works with or without this change.

**Comment by mxschmitt** [comment]
So we internally start a driver which is basically the upstream github.com/microsoft/playwright project under the hood. In the upstream package the magic happens and in the Python world we only call the Node.js methods internally with a custom JSON based protocol over stdin/stdout.
Thats why we have to start and stop it. Stop is probably not that important but start is needed to use it.
