### ISSUE TITLE
[Question]: How to handle a popup window with chrome headless ?

### ISSUE THREAD

**Issue by KostasSampsonas** [microsoft/playwright-python#1793]
### Your question

After searching a bit I still don't understand if this is a bug of Chrome or of Playwright or something else. I don't really understand how to test sign in with Google in headless mode. I have defined a function that simply clicks on sign in with google iframe, fills in the username and password and tests if the users is signed in. When it runs headed everything works like it should. When it runs headless the test exceeds the timeout and throws a timeout error saying "waiting for event popup". Somehow the test simply stops..

###  def login_with_google(self):
        with self.page.expect_popup() as popup_info:
            self.page.click(self.GOOGLE_IFRAME)
            popup = popup_info.value
            popup.fill(self.GOOGLE_EMAIL_FIELD, Config.get("EMAIL_GOOGLE"))
            popup.click(self.GOOGLE_NEXT_BTN)
            popup.wait_for_selector(self.GOOGLE_PASS_FIELD)
            popup.fill(self.GOOGLE_PASS_FIELD, Config.get("PASS_GOOGLE"))
            popup.click(self.GOOGLE_NEXT_BTN)

Any help would be greatly appreciated! Also if there is another / better way of testing such a thing please let me know. Thanks in advance.

**Comment by mxschmitt** [comment]
I recommend using Trace Viewer to see why it happens, most likely the site does behaves differently when you run it l headed: https://playwright.dev/python/docs/trace-viewer-intro

**Comment by KostasSampsonas** [comment]
Hello @mxschmitt, I have already tried that. No luck. The test executes up until the popup command and then freezes. Somehow to my understanding the browser doesn't understand how to handle the popup when headless. The same happens with firefox too.
Is there another way to approach that? I am assuming people test such features all the time. Looking forward to your reply.

**Chrome HEADLESS**
![popup_headless](https://user-images.githubusercontent.com/85338575/222436002-eefe0e70-4b53-4897-8fa2-6c4d6baa83bc.png)



**Chrome HEADED**
![popup_headed](https://user-images.githubusercontent.com/85338575/222436190-23ed4b3b-8999-436f-8b74-8dea989d91b2.png)

**Comment by mxschmitt** [comment]
Popups are working in headless and headed manner in all the browsers.

You could try setting a fixed user-agent when creating the context, since this is different in headless and headed and sometimes sites are blocking headless user agents.

**Comment by KostasSampsonas** [comment]
Thank you @mxschmitt  for your suggestion. It is unclear to me still where and how can I set my fixed agent though. I run my tests using pytest. I have configure a conftest file where all my fixtures are defined. For example one of them is the one from the documentation about the viewport size: 
```
# Fixture to use custom viewport size
@pytest.fixture(scope="session")
def browser_context_args(browser_context_args):
    return {
        **browser_context_args,
        "viewport": {
            "width": 1920,
            "height": 1080,
        },
    }
```

I have to pass it like that.. Can I somehow pass it inside this or should I define another function in my conftest.py for this purpose? 
```
context = browser.new_context(
  user_agent='My user agent'
)
```
Where my user agent is: "[Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36](https://explore.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes)"

But then somehow I have to define the new_context which according to the documentation is 

> https://playwright.dev/python/docs/api/class-browser#browser-new-context)

I also tried to pass all this inside my function like that:
```
def login_with_google(self, playwright):
        with self.page.expect_popup() as popup_info:
            browser = playwright.chrome.launch()
            context = browser.new_context(
                user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36')
            self.page = browser.new_page()
            self.page.click(self.GOOGLE_IFRAME)
            popup = popup_info.value
            popup.fill(self.GOOGLE_EMAIL_FIELD, Config.get("EMAIL_GOOGLE"))
            popup.click(self.GOOGLE_NEXT_BTN)
            popup.wait_for_selector(self.GOOGLE_PASS_FIELD)
            popup.fill(self.GOOGLE_PASS_FIELD, Config.get("PASS_GOOGLE"))
            popup.click(self.GOOGLE_NEXT_BTN)
            context.close()
            browser.close()
```
with the same outcome as above even on headed mode now. The test throws a timeout error because it's waiting for event "popup".

I am clearly missing something here..  Looking forward to your reply.

**Comment by mxschmitt** [comment]
If you use the pytest fixtures, then yes you need to put it into `browser_context_args `. If you create the context yourself, then inside new_context (or browser.new_page).

Seems like you are launching your browser manually, so new_context is the right place.

You are btw. creating two context's, one which you don't use and then browser.new_page which creates one internally for you. So change it to the following and then the user agent will be used:

<img width="304" alt="image" src="https://user-images.githubusercontent.com/17984549/222557555-2f30c553-ff0c-4eb3-867b-8e2ffd439f97.png">

(this change about the user-agent is btw. just an assumption which often creates such issues, it might be a different issue).

**Comment by KostasSampsonas** [comment]
Hello @mxschmitt I followed your advice and created a fixed user-agent. I also wrote the whole test as one function without conftest.py or pytest.ini to simplify things in order for me to understand better the whole procedure. Unfortunately I get the same outcome. My test runs headed and passes but headless stucks and throws "waiting for event "popup" error. This is the new file. For any other suggestions I would be really thankful !

```
import pytest
from playwright.sync_api import sync_playwright


USER_BTN = "//button[@data-test='profile-menu-button']"
YOUR_PROFILE_BTN = "(//a[@data-test='menu-item'])[1]"
GOOGLE_IFRAME = "//iframe"
GOOGLE_EMAIL_FIELD = "//input[@id='identifierId']"
GOOGLE_PASS_FIELD = "//input[@name='Passwd']"
GOOGLE_NEXT_BTN = "(//div[@class='VfPpkd-Jh9lGc'])[2]"


def test_login_with_google(playwright):
    chromium = playwright.chromium
    browser = chromium.launch(headless=True) # If changed (headless=True) the test freezes 
    context = browser.new_context(
        user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36')
    page = context.new_page()  # Changed here as per your suggestion
    with page.expect_popup() as popup_info:
        page.goto('localhost:8000/auth/login')
        page.click(GOOGLE_IFRAME)
        popup = popup_info.value
        popup.fill(GOOGLE_EMAIL_FIELD, "*************@gmail.com")
        popup.click(GOOGLE_NEXT_BTN)
        popup.wait_for_selector(GOOGLE_PASS_FIELD)
        popup.fill(GOOGLE_PASS_FIELD, "**************")
        popup.click(GOOGLE_NEXT_BTN)

        page.wait_for_selector(USER_BTN)
        page.click(USER_BTN)
        page.click(YOUR_PROFILE_BTN)
        print('successful!')
        context.close()
        browser.close()


with sync_playwright() as playwright:
    test_login_with_google(playwright)
```

**Comment by mxschmitt** [comment]
Unfortunately I'm running out of ideas, feel free to send me a message on discord with a full repro, that I can run locally, maybe I'll spot something quickly.

**Comment by mxschmitt** [comment]
Actually Google does not like to be automated and prevents you often doing it, see [here](https://support.google.com/accounts/answer/7675428?hl=en#:~:text=Are%20being%20controlled%20through%20software%20automation%20rather%20than%20a%20human).

Closing since this is not a Playwright issue then.

**Comment by Andrey-Pivtorak** [comment]
I faced a similar problem in my test (pytest + playwright + vs code). Maybe my code will help someone:

from playwright.sync_api import expect, Page
import pages
import data


class TestContactUs:

     # home_page - is a @fixture
    def test_contact_us_form(self, home_page: Page, page: Page):
        home_page.locator(pages.home_page.contactUsBtn).click()
        expect(page.locator('//h2[contains(text(),"Get In Touch")]')).to_be_visible()
        page.fill(pages.contact_us_page.nameInput, data.user_data.name)
        page.fill(pages.contact_us_page.emailInput, data.user_data.email)
        page.fill(pages.contact_us_page.subjectInput, 'Testing the "Contact us" form')
        page.fill(pages.contact_us_page.messageInput, 'Testing the "Contact us" form. If you have any suggestion areas or improvements, do let us know. We will definitely work on it.')
        page.set_input_files(pages.contact_us_page.uploadFileBtn, 'data/fileForUpload.txt')

        # I succeeded with this code to handle pop-up window
        page.on("dialog", lambda dialog: dialog.accept())
        page.click(pages.contact_us_page.submitBtn)

        expect(page.locator('h2 ~ div.alert-success')).to_be_visible()
