### ISSUE TITLE
[Feature] New headless chrome (`--headless=new` launch argument)

### ISSUE THREAD

**Issue by punksnotbread** [microsoft/playwright-python#1796]
Related to https://github.com/microsoft/playwright/issues/21194 -> is it possible to see this in `playwright-python` as well? 

When trying to launch with 
```py
        browser = await p.chromium.launch(
            ignore_default_args=["--headless"],
            args=["--headless=new"],
        )
```
I can see that the new headless is not used. 

Are there plans to implement it as in the base playwright repository?

**Comment by mxschmitt** [comment]
You can use it as of today with the code above, I was able to run it via:

```python
from playwright.sync_api import sync_playwright

with sync_playwright() as playwright:
    browser = playwright.chromium.launch(
        ignore_default_args=["--headless"],
        args=["--headless=new"],
    )
    page = browser.new_page()
    page.goto("http://whatsmyuseragent.org/")
    page.screenshot(path=f"example.png")
    browser.close()
```

When running it with `DEBUG=pw:browser python test.py` I saw that the right headless parameter was passed over. How did you see that it was not used?

Are you maybe using the Pytest plugin and want to use it there?

See also https://github.com/microsoft/playwright/issues/21216#issuecomment-1446678795 that the new headless mode is much slower than the old one.

**Comment by punksnotbread** [comment]
Ah, you're right, my bad. 

With newest playwright version (1.31.1), it's OK, as seen with this test -> Headless string is not included in UA, meaning the new headless mode is working:
```py
from playwright.sync_api import sync_playwright
from importlib.metadata import version


with sync_playwright() as playwright:
    browser = playwright.chromium.launch(
        ignore_default_args=["--headless"],
        args=["--headless=new"],
    )
    page = browser.new_page()
    page.goto("http://whatsmyuseragent.org/")
    user_agent = page.locator("xpath=.//div[@class='user-agent']/p").inner_text()

    print(f"Browser version: {browser.version}")
    print(f"Playwright version: {version('playwright')}")
    print(f"Parsed UA: {user_agent}")

    browser.close()
```

"Headless" not in UA:
```
Browser version: 111.0.5563.19
Playwright version: 1.31.1
Parsed UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
```

"Headless" in UA:
```
Browser version: 108.0.5359.29
Playwright version: 1.28.0
Parsed UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/108.0.5359.29 Safari/537.36
```

Seems that I had an older Chromium binary used, as it also worked with a custom channel to a locally updated Chrome.
