### ISSUE TITLE
[Question]: Could not find a version that satisfies the requirement playwright (from versions: none)

### ISSUE THREAD

**Issue by jerryxnqiu** [microsoft/playwright-python#1797]
### Your question

ERROR: Could not find a version that satisfies the requirement playwright (from versions: none)
ERROR: No matching distribution found for playwright

Hi, 

I try to install playwright on my Windows 10 Home, 64-bit operating system, x64-based processor. But it got below issue and seems not able to download the files to start the installation.

- pip install playwright
  
_ERROR: Could not find a version that satisfies the requirement playwright (from versions: none)
ERROR: No matching distribution found for playwright_

I also try to do below but also failed and it seems back to issue 1. Could you please help to let me know why? Thanks.

- pip install pytest-playwright

_Collecting pytest-playwright
  Using cached pytest_playwright-0.3.1-py3-none-any.whl (10 kB)
Collecting python-slugify<7.0.0,>=6.0.0
  Using cached python_slugify-6.1.2-py2.py3-none-any.whl (9.4 kB)
Collecting pytest-base-url<3.0.0,>=1.0.0
  Using cached pytest_base_url-2.0.0-py3-none-any.whl (4.6 kB)
Collecting pytest-playwright
  Using cached pytest_playwright-0.3.0-py3-none-any.whl (10 kB)
  Using cached pytest_playwright-0.2.3-py3-none-any.whl (10.0 kB)
Collecting pytest
  Using cached pytest-7.2.2-py3-none-any.whl (317 kB)
Collecting python-slugify
  Using cached python_slugify-8.0.1-py2.py3-none-any.whl (9.7 kB)
Collecting pytest-playwright
  Using cached pytest_playwright-0.2.2-py3-none-any.whl (9.8 kB)
  Using cached pytest_playwright-0.2.1-py3-none-any.whl (9.8 kB)
  Using cached pytest_playwright-0.2.0-py3-none-any.whl (9.8 kB)
  Using cached pytest_playwright-0.1.2-py3-none-any.whl (11 kB)
  Using cached pytest_playwright-0.1.1-py3-none-any.whl (10 kB)
  Using cached pytest_playwright-0.1.0-py3-none-any.whl (10 kB)
  Using cached pytest_playwright-0.0.12-py3-none-any.whl (10 kB)
  Using cached pytest_playwright-0.0.11-py3-none-any.whl (10 kB)
  Using cached pytest_playwright-0.0.10-py3-none-any.whl (10 kB)
  Using cached pytest_playwright-0.0.9-py3-none-any.whl (10 kB)
  Using cached pytest_playwright-0.0.8-py3-none-any.whl (10 kB)
  Using cached pytest_playwright-0.0.7-py3-none-any.whl (9.9 kB)
  Using cached pytest_playwright-0.0.6-py3-none-any.whl (10 kB)
  Using cached pytest_playwright-0.0.5-py3-none-any.whl (9.8 kB)
  Using cached pytest_playwright-0.0.4.1-py3-none-any.whl (5.6 kB)
  Using cached pytest_playwright-0.0.4-py3-none-any.whl (5.1 kB)
  Using cached pytest_playwright-0.0.3-py3-none-any.whl (3.7 kB)
  Using cached pytest_playwright-0.0.2-py3-none-any.whl (3.3 kB)
ERROR: Cannot install pytest-playwright==0.0.10, pytest-playwright==0.0.11, pytest-playwright==0.0.12, pytest-playwright==0.0.2, pytest-playwright==0.0.3, pytest-playwright==0.0.4, pytest-playwright==0.0.4.1, pytest-playwright==0.0.5, pytest-playwright==0.0.6, pytest-playwright==0.0.7, pytest-playwright==0.0.8, pytest-playwright==0.0.9, pytest-playwright==0.1.0, pytest-playwright==0.1.1, pytest-playwright==0.1.2, pytest-playwright==0.2.0, pytest-playwright==0.2.1, pytest-playwright==0.2.2, pytest-playwright==0.2.3, pytest-playwright==0.3.0 and pytest-playwright==0.3.1 because these package versions have conflicting dependencies._

_The conflict is caused by:
    pytest-playwright 0.3.1 depends on playwright>=1.18
    pytest-playwright 0.3.0 depends on playwright>=1.18
    pytest-playwright 0.2.3 depends on playwright>=1.13
    pytest-playwright 0.2.2 depends on playwright>=1.13
    pytest-playwright 0.2.1 depends on playwright>=1.13
    pytest-playwright 0.2.0 depends on playwright>=1.13
    pytest-playwright 0.1.2 depends on playwright>=1.10.0
    pytest-playwright 0.1.1 depends on playwright>=1.10.0
    pytest-playwright 0.1.0 depends on playwright>=1.10.0
    pytest-playwright 0.0.12 depends on playwright>=1.9.0
    pytest-playwright 0.0.11 depends on playwright==1.8.0a1
    pytest-playwright 0.0.10 depends on playwright>=0.170.0
    pytest-playwright 0.0.9 depends on playwright>=0.0.4
    pytest-playwright 0.0.8 depends on playwright>=0.0.4
    pytest-playwright 0.0.7 depends on playwright>=0.0.4
    pytest-playwright 0.0.6 depends on playwright>=0.0.4
    pytest-playwright 0.0.5 depends on playwright>=0.0.4
    pytest-playwright 0.0.4.1 depends on playwright==0.0.4
    pytest-playwright 0.0.4 depends on playwright
    pytest-playwright 0.0.3 depends on playwright
    pytest-playwright 0.0.2 depends on playwright_

_To fix this you could try to:_
_1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict_

_ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts_

**Comment by jerryxnqiu** [comment]
Just add a workaround, I can install "pip install pytest-playwright" outside of the virtual environment. 
After this, enter into the virtual environment, can do the "playwright install" to setup the respective browsers

**Comment by mxschmitt** [comment]
Can you execute `pip debug` and show us your ouput? This should give us hints why it does not want to install Playwright.

**Comment by jerryxnqiu** [comment]
Thanks for the quick response. I sort of overcome the issue again by changing the interpreter, stepping back from a Python 3.10.x to 3.9.7. The Python 3.10.x interpreter (inside my virtual environment) is actually coming from msys/mingw-w64 installation (at least the path says), which also stopped me installing pandas. Therefore I think that might not be the right one to use. So I changed it back to the one from normal Python39 installation. It seems all solved after the interpreter change. 

I have changed my environment so sorry can't be replicated again. Will share when face again. Thanks very much.

**Comment by gregorias** [comment]
I have this exact issue on macOS (using pyenv). The output of `pip debug` is

```
pip version: pip 23.1.1 from /Users/grzesiek/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pip (python 3.11)
sys.version: 3.11.3 (main, Apr 23 2023, 18:04:42) [Clang 12.0.1 ]
sys.executable: /Users/grzesiek/.pyenv/versions/3.11.3/bin/python3.11
sys.getdefaultencoding: utf-8
sys.getfilesystemencoding: utf-8
locale.getpreferredencoding: UTF-8
sys.platform: darwin
sys.implementation:
  name: cpython
'cert' config value: Not specified
REQUESTS_CA_BUNDLE: None
CURL_CA_BUNDLE: None
pip._vendor.certifi.where(): /Users/grzesiek/.pyenv/versions/3.11.3/lib/python3.11/site-packages/pip/_vendor/certifi/cacert.pem
pip._vendor.DEBUNDLED: False
vendored library versions:
  CacheControl==0.12.11
  colorama==0.4.6
  distlib==0.3.6
  distro==1.8.0
  msgpack==1.0.5
  packaging==21.3
  platformdirs==3.2.0
  pyparsing==3.0.9
  pyproject-hooks==1.0.0
  requests==2.28.2
  certifi==2022.12.07
  chardet==5.1.0
  idna==3.4
  urllib3==1.26.15
  rich==13.3.3 (Unable to locate actual module version, using vendor.txt specified version)
  pygments==2.14.0
  typing_extensions==4.5.0 (Unable to locate actual module version, using vendor.txt specified version)
  resolvelib==1.0.1
  setuptools==65.6.3 (Unable to locate actual module version, using vendor.txt specified version)
  six==1.16.0
  tenacity==8.2.2 (Unable to locate actual module version, using vendor.txt specified version)
  tomli==2.0.1
  webencodings==0.5.1 (Unable to locate actual module version, using vendor.txt specified version)
Compatible tags: 864
  cp311-cp311-macosx_10_16_arm64
  cp311-cp311-macosx_10_16_universal2
  cp311-cp311-macosx_10_15_arm64
  cp311-cp311-macosx_10_15_universal2
  cp311-cp311-macosx_10_14_arm64
  cp311-cp311-macosx_10_14_universal2
  cp311-cp311-macosx_10_13_arm64
  cp311-cp311-macosx_10_13_universal2
  cp311-cp311-macosx_10_12_arm64
  cp311-cp311-macosx_10_12_universal2
  ...
  [First 10 tags shown. Pass --verbose to show all.]
```

**Comment by gregorias** [comment]
I fixed the issue by removing llvm@12 from my system.

* Pip was not detecting a compatible Playwright version, because there were no compatibility tags common between my system and [Playwright's releases](https://pypi.org/project/playwright/#files).  
  `pip debug` was saying that I have macos 10 compatibility, which seemed way to old.
* [Pip on macOS uses Clang's version to determine my platform](https://github.com/pyenv/pyenv/issues/2491#issuecomment-1287269998).
* I had an old instance of LLVM installed that provided the spurious old Clang.

**Comment by AlexanderMortimer** [comment]
in a short way, you maybe just update your pip library to last one. this did solve my problem in installing playwright in mac
pip install --upgrade pip
