### ISSUE TITLE
[Question]: fail to run playwright command and got with GLIBC_2.28 error in ubuntu 18.04

### ISSUE THREAD

**Issue by wolf51983** [microsoft/playwright-python#1802]
### Your question

Context:

Playwright Version: 1.31.1
Operating System: Ubuntu 18.04 LTSC
Python version: 3.10
Browser: chromium

After installed playwright with "pip", I got failure when executing "playwright". Then failure message was mentioned with version of GLIBC. Version 2.28 is required but only got 2.27

<img width="904" alt="image" src="https://user-images.githubusercontent.com/6613571/223671722-10b8b513-cca4-46a8-a97b-d572843e0097.png">

<img width="553" alt="image" src="https://user-images.githubusercontent.com/6613571/223671809-513d9146-c66e-445d-8bc6-4f29bf2e98a3.png">

And i found one playwright docker image  with ubuntu 18.04 (bionic).
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/6613571/223672064-3a05c5b0-6526-4d01-82c5-40757f48d445.png">

So what should I do next to run correctly?
Thanks.

**Comment by mxschmitt** [comment]
This is not the official docs site, it's a mirror ran by third-party.

Ubuntu 18 is not supported anymore, for up2date docs see here: https://playwright.dev/python/docs/docker

**Comment by wolf51983** [comment]
So does that mean it's impossible to run python files using playwright in ubuntu 18.04?

**Comment by mxschmitt** [comment]
> So does that mean it's impossible to run python files using playwright in ubuntu 18.04?

You can use an old Playwright version but we strongly discourage doing that.

**Comment by wolf51983** [comment]
> > So does that mean it's impossible to run python files using playwright in ubuntu 18.04?
> 
> You can use an old Playwright version but we strongly discourage doing that. Or use Docker to run a more recent Ubuntu version.

Thanks for reply. I will try with Docker.
