### ISSUE TITLE
[Question]: How to correct debugging into PyCharm?

### ISSUE THREAD

**Issue by az2rt** [microsoft/playwright-python#1803]
### Your question

Hi, 
I got error:
```
self = <selectors.KqueueSelector object at 0x10f25f760>, fileobj = 14
events = 1, data = (<Handle BaseSelectorEventLoop._read_from_self()>, None)

    def register(self, fileobj, events, data=None):
        key = super().register(fileobj, events, data)
        try:
            if events & EVENT_READ:
                kev = select.kevent(key.fd, select.KQ_FILTER_READ,
                                    select.KQ_EV_ADD)
>               self._selector.control([kev], 0, 0)
E               TypeError: changelist must be an iterable of select.kevent objects
```
If trying to debug tests into PyCharm. 
However, if just running test - works perfectly.

Connected to pydev debugger (build 212.5712.39)
Launching pytest with arguments --alluredir=~/test/results /Users/.../tests/language/test_change_language_for_website.py --no-header --no-summary -q in /Users/.../tests/language

PyCharm 2021.2.4 (Professional Edition)
Build #PY-212.5712.39, built on December 21, 2021
Runtime version: 11.0.13+8-b1504.49 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 750M
Cores: 12

**Comment by mxschmitt** [comment]
Looks like a bug in PyCharm debugger, I recommend reaching out to their support.

https://youtrack.jetbrains.com/issue/PY-51495/PyCharm-debug-fails-upon-import-asyncio looks like its explaining a workaround.

**Comment by az2rt** [comment]
Thanks!
