### ISSUE TITLE
[Question]: pytest to run several cases, but the first case works and others failed

### ISSUE THREAD

**Issue by garyzhang21** [microsoft/playwright-python#1804]
### Your question

![image](https://user-images.githubusercontent.com/32188719/224278556-5c270cc1-2ff8-4086-80df-b675dad5c744.png)
what should i do ?

**Comment by garyzhang21** [comment]
if i use pytest, i think it will run all the test_file.py in the folder, right? 
but when i finished one case, others will be failed.

**Comment by mxschmitt** [comment]
Yes it will run Python files `test_*.py` as per [Pytest documentation](https://docs.pytest.org/en/7.1.x/contents.html).

We need more information on what is failing and how its failing to act on this.

**Comment by garyzhang21** [comment]
fixed and closed
