### ISSUE TITLE
[BUG] page.content() does not fully output, it was interrupted

### ISSUE THREAD

**Issue by cyboca** [microsoft/playwright-python#1805]
**Context:**

- Playwright Version: [1.31.1]
- Operating System: [Windows]
- Python version: [3.9.7]
- Browser: [Chromium]

**Code Snippet**

```python
from playwright.sync_api import sync_playwright

url="http://emweb.securities.eastmoney.com/PC_HSF10/NewFinanceAnalysis/Index?type=web&code=sz001201"

with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()
    page.goto(url,timeout=5000)
    print(page.content())
    browser.close()
```

**Describe the bug**

I'm trying to grab some finance data from the url above and I use the page.content() to get the full page but the output seems interrupted.
It displayed all good when I use headless=False in the browser.
<img width="667" alt="s1" src="https://user-images.githubusercontent.com/38181964/224599574-4ef782ca-ab3a-44d4-b9ae-f21a4c0cc2c9.png">

**Comment by mxschmitt** [comment]
I tried to reproduce on Python 3.11 Windows & macOS but was unfortunately not able to. In both scenarios it printed the full DOM until the `</html>` tag.

**Comment by cyboca** [comment]
> I tried to reproduce on Python 3.11 Windows & macOS but was unfortunately not able to. In both scenarios it printed the full DOM until the `</html>` tag.

Thanks.
It looks like that my python command is to blame. When I use `python test.py` it runs good but interrupted when I use `python -u test.py`.
