### ISSUE TITLE
[BUG] Getting "'Page.overrideUserPreference' was not found" with webkit browser.

### ISSUE THREAD

**Issue by RevTyler** [microsoft/playwright-python#1809]
**Context:**
- Playwright Version: 1.30
- Operating System: Linux
- Python version: 3.8
- Browser: WebKit
- Extra:

This is my fixture for creating a page that I'm using and it works fine with chromium, firefox and msedge, but when I try to use webkit I get this error.

'Page.overrideUserPreference' was not found [{"code":-32601,"message":"'Page.overrideUserPreference' was not found"}]

**Code Snippet**

```python
def get_page(playwright: Playwright,
             config: Config) -> Generator[Page, None, None]:
    """Creates and returns a playwright page."""
    is_headless = config.get(HEADLESS)
    browser_name = config.get(BROWSER)

    if browser_name == "msedge":
        browser = playwright.chromium.launch(channel=browser_name, headless=is_headless)
    else:
        browser_type: BrowserType = getattr(playwright, browser_name)
        browser = browser_type.launch(headless=is_headless)

    page = browser.new_page()

    if not is_headless:
        page.set_viewport_size({"width": 1700, "height": 900})

    return page
```

**Comment by mxschmitt** [comment]
Which linux distribution are you using?

**Comment by RevTyler** [comment]
> Which linux distribution are you using? Make sure to only use a supported one: https://playwright.dev/python/docs/troubleshooting#linux

Ubuntu 18. That's probably part of the problem, then.

**Comment by mxschmitt** [comment]
Yup not supported anymore, closing then.
