### ISSUE TITLE
[Question]: How do we verify the downloaded file?

### ISSUE THREAD

**Issue by DalebCoper** [microsoft/playwright-python#1823]
### Your question

[Question]: Have issue to assert downloaded file.

So i handle file downloading using docs(https://playwright.dev/python/docs/downloads), but cant find solution to assert that we downloaded correct file using expect.
https://github.com/microsoft/playwright/issues/16402 - got this, but for js, can we have for python?

**Comment by mxschmitt** [comment]
Did you try the following?

```python
# Start waiting for the download
with page.expect_download() as download_info:
    # Perform the action that initiates download
    page.get_by_text("Download file").click()
download = download_info.value
assert "foo" === download.suggested_filename
```

With this you could assert the file name, see here: https://playwright.dev/python/docs/api/class-download#download-suggested-filename

**Comment by DalebCoper** [comment]
> ```python
> foo
> ```

Ah, missed that part.
That's help, thanks!
