### ISSUE TITLE
Is it possible to add slowmo to a specific test, and not to every test?

### ISSUE THREAD

**Issue by snackattas** [microsoft/playwright-python#1829]
I have 1 test which uses a specific part of our site that has an aggressive rate limit, that playwright scripts normally hit...but with just a small slowmo of 1, we avoid the rate limit...but is there a way to configure JUST that test to use the slowmo, and not the whole suite?

**Comment by mxschmitt** [comment]
Slowmo is as of today only configurable on the browser level, not context level. So its not possible.

We strongly recommend not using slowmo, since if a test is only passing with slomo, then its flaky by design.

Relates to https://github.com/microsoft/playwright/issues/5900.

**Comment by balazs-ita-epam** [comment]
What has become the solution for this issue? It seems to be a global problem how to handle it.

**Comment by balazs-ita-epam** [comment]
@mxschmitt 
What do you recommend instead of slowmo then?
