### ISSUE TITLE
BrowserType.connect(wsEndpoint) method is not working

### ISSUE THREAD

**Issue by kesavkolla** [microsoft/playwright-python#183]
If I've websocket endpoint of chrome page is it possible to connect to that page directly via playwright?

Eg:

I've websocket endpoint for page as ws://localhost:9222/devtools/page/DAB7FB6187B554E10B0BD18821265734
I would like to connect to that via playwright.

**Comment by mxschmitt** [comment]
Playwright does only allow to connect to a Playwright based connection. It seems like its related to https://github.com/microsoft/playwright/issues/1985

**Comment by kesavkolla** [comment]
I do see document from browserless (https://docs.browserless.io/docs/playwright.html) which says it works with playwright and they connect using browserWSEndpoint. I was thinking such a similar thing for page.

**Comment by mxschmitt** [comment]
@kesavkolla good catch. I tried to reproduce it and the BrowserType.connect method is currently not working. We'll try to fix this soon so you can use browserless.io for example.

Example launch server script:

```js
const { chromium } = require('playwright');

(async () => {
  const browserServer = await chromium.launchServer();
  const wsEndpoint = browserServer.wsEndpoint();
  console.log(wsEndpoint)
  await new Promise(() => null)
})();
```

Example Python script:

```py
from playwright import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.connect(
        "ws://127.0.0.1:60148/c6ac94cd902cfb32213399acb97f4e62"
    )
    page = browser.newPage()
    page.goto("http://whatsmyuseragent.org/")
    page.screenshot(path=f"example.png")
    browser.close()
```

**Comment by pavelfeldman** [comment]
Starting with v1.4 it won't work again as Playwright is switching to its own RPC.

**Comment by pavelfeldman** [comment]
Switching to tracking it upstream.

**Comment by lucky-blues** [comment]
but new , How do I use the connect method, Is there a way to record the status of the previous page and how I want to switch page @Max Schmitt

**Comment by mxschmitt** [comment]
Blocked by https://github.com/microsoft/playwright/issues/4687

**Comment by 3dprogramin** [comment]
Any news ?
Looking forward to have the **connect(wsEndpoint)** method working too.

**Comment by mxschmitt** [comment]
The feature get's released in version 1.11 which should be out in a few days.

**Comment by sourav-kundu** [comment]
@mxschmitt great thanks for the reply! Will be waiting for the release.

**Comment by innovation-scriple** [comment]
> The feature get's released in version 1.11 which should be out in a few days.

Please let us know exact date. Its very urgent !

**Comment by innovation-scriple** [comment]
> The feature get's released in version 1.11 which should be out in a few days.

Please let us know if there is any beta version for 1.11 ?Also I am unable to find **Browsertype.connect()** method in C# and Python as well.

**Comment by mxschmitt** [comment]
`pip install git+https://github.com/microsoft/playwright-python` should make it possible to test.

See here for the Python docs: https://playwright.dev/python/docs/next/api/class-browsertype#browser_typeconnectws_endpoint-kwargs

C# does not have it implemented yet.

**Comment by vthakare-xpanxion** [comment]
> `pip install git+https://github.com/microsoft/playwright-python` should make it possible to test.
> 
> See here for the Python docs: https://playwright.dev/python/docs/next/api/class-browsertype#browser_typeconnectws_endpoint-kwargs
> 
> C# does not have it implemented yet.

thanks...waiting for next release

**Comment by lilo1382** [comment]
Does Browsertype.connect() work for Javascript/Typescript?

**Comment by mxschmitt** [comment]
@lilo1382 it's now available: https://playwright.dev/python/docs/next/api/class-browsertype/#browser-type-connect
