### ISSUE TITLE
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded

### ISSUE THREAD

**Issue by tieyongjie** [microsoft/playwright-python#1831]
### Your question

I set a timeout,but still get an error of playwright._impl._api_types.TimeoutError
![image](https://user-images.githubusercontent.com/57651075/227848207-c73d991b-2bbe-45fc-9989-53ae10e4ab17.png)

**Comment by tris-tan** [comment]
This is what timeout's do. If your action is not possible within the timeout you set then playwright raises a `TimeoutError`.

**Comment by mxschmitt** [comment]
We need more information to act on it. This usually means that the website you are navigating does not load and the timeout exceeds.

Closing as per above. If you thinks its a Playwright bug, please re-file with a repro.
