### ISSUE TITLE
[Feature][Load Page] Want to request option to disable "waiting until "load""

### ISSUE THREAD

**Issue by nguyenquangtay** [microsoft/playwright-python#1845]
Dear Playwright!
Thank you for the great tool, 
May I request support for this feature:

**Context:**
The method ''goto(URL)" checks the load condition  by default
**Desired:**
I want to request an option to disable it by parameter. is that possible?

**Use case:**
1. Acces the directly downloadable link
sample code
`        self.page.goto(url='https://mirror.nforce.com/pub/speedtests/100mb.bin')
`
2. Load a page that block by the current network(after blocking time is over the new option for private access is shown for user select)
3. ...
all of those above cases are blocked by default wait 'until load' of Playwright, detail log can be found here.
[blocking_log.txt](https://github.com/microsoft/playwright-python/files/11145112/blocking_log.txt)

Thank you all and have a great day!

**Comment by mxschmitt** [comment]
This is expected from our side. If you navigate to a site which triggers a download, no new navigation happens, hence the navigation gets aborted. You can still handle the download like that:

```python
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    for browser_type in [p.webkit, p.firefox, p.chromium]:
        browser = browser_type.launch(
            headless=False,
        )
        page = browser.new_page(
            accept_downloads=True,
        )
        with page.expect_download() as download_info:
            try:
                page.goto('https://mirror.nforce.com/pub/speedtests/100mb.bin')
            except:
                pass
        download = download_info.value
        print(download.suggested_filename)
        browser.close()
```

Note above the try/catch between the goto. Would that work for you?

**Comment by nguyenquangtay** [comment]
Hello Max, thank you for your responses!
yes, I know that is expected as normal behavior, almost all of them needed, haha!
but on my side, some scenarios would need that:
- a directly downloadable link is just an example.
- there is another example in the picture below ( mainly accessing the page that blocking for some reason... there is an option to retry with other methods like Tor, VPN, and so on...)

![image](https://user-images.githubusercontent.com/49488470/229957565-add4f049-09dd-4960-9132-b7cce0a9bb9f.png)

the current behavior blocks me to interact with the current content of the page :P 
btw, if it takes a lot of your effort so I think I  can consider another workaround solution like merging with Appium, pywinauto ...
Thank you a lot!

**Comment by mxschmitt** [comment]
This is unfortunately outside of the scope for Playwright. So I recommend trying out other approaches with other tools.
