### ISSUE TITLE
[Question]: Since playwright-python uses  a single `node` via UNIX pipes, can multiple `sync_playwright()` use a single `node` process?

### ISSUE THREAD

**Issue by dgtlmoon** [microsoft/playwright-python#1850]
### Your question

So under the bonnet, playwright-python spins up `node`, and uses greenlets to drive STDIN/STDOUT to that `node` process interface which intern is driving chrome/playwright etc

In my case I have many python scripts that need to run at sort of unpredictable times, this results in each python script having yet another `node` process running 

Which results in super high CPU and memory usage

Is it possible to have one `node` process running

```
1574120 ?        Ssl    0:13  \_ python ./my-website-check.py -d /datastore
1607388 ?        S      0:00      \_ /bin/sh /usr/local/playwright/driver/playwright.sh run-driver
1607396 ?        Sl     0:01          \_ /usr/local/playwright/driver/node /usr/local/playwright/driver/package/lib/cli/cli.js run-driver
1582652 ?        Ssl    0:16  \_ python ./my-website-check.py -d /datastore
1605932 ?        S      0:00      \_ /bin/sh /usr/local/playwright/driver/playwright.sh run-driver
1605945 ?        Sl     0:02          \_ /usr/local/playwright/driver/node /usr/local/playwright/driver/package/lib/cli/cli.js run-driver
1583171 ?        Ssl    0:29  \_ python ./my-website-check.py -d /datastore
1607154 ?        S      0:00      \_ /bin/sh /usr/local/playwright/driver/playwright.sh run-driver
1607158 ?        Sl     0:00          \_ /usr/local/playwright/driver/node /usr/local/playwright/driver/package/lib/cli/cli.js run-driver
1599
```

I'm doing basically this in the script..

```
        with sync_playwright() as p:
            browser = chromium.connect_over_cdp(self.command_executor, timeout=60000)
            
```

Do you have any suggestions on how to make (for example) `sync_playwright()` use an existing `node` process? Or can I multiplex(?) the IO from `node` so that many `sync_playwright()`'s can use the same process?

(Maybe the solution is to use redis/celery to make a worker queue, but if I could avoid that, that's cool also :-) )

thanks for any tips, and thanks for the amazing work!

**Comment by mxschmitt** [comment]
One Playwright instance is coupled to a single Playwright driver instance. We recommend creating multiple instances per thread as of today. redis/celery sounds also good as a solution. Since this won't change in the near future, closing it for now.

**Comment by dgtlmoon** [comment]
@mxschmitt ok super thanks for the clarification :)

> One Playwright instance is coupled to a single Playwright driver instance.

Yes, so its basically one:one relationship, wasn't sure if I understood it correctly


> Since this won't change in the near future, closing it for now.

Understood, no problems.

> We recommend creating multiple instances per thread as of today.

Multiple instances of playwright? (multiple `node` processes?) per thread?

thanks :)

**Comment by mxschmitt** [comment]
> Multiple instances of playwright? (multiple node processes?) per thread?

Sorry was writing too quickly, meant one Playwright instance per thread. 🙂

**Comment by dgtlmoon** [comment]
Related to #623 I think

**Comment by dgtlmoon** [comment]
@mxschmitt What about `await`ing on multiple contexts/pages using await and `.add_done_callback(callback)` ?

As an idea to parallelise the page loading and other events

Does the thread limitation impact here? Sorry for the obtuse question!

```


def screenshot_and_close(task):
    # report a message
    print('Page was loaded')

async def run(playwright):
    webkit = playwright.webkit
    browser = await webkit.launch()

    context1 = browser.new_context()
    page1 = context1.new_page()
    page1.goto("https://example.com")
    page1.add_done_callback(callback)

    context2 = browser.new_context()
    page2 = context2.new_page()
    page2.goto("https://example.com")
    page2.add_done_callback(callback)

    all_tasks = asyncio.all_tasks()
    await asyncio.wait(all_tasks)

    await browser.close()

async def main():
    async with async_playwright() as playwright:
        await run(playwright)
        
```
