### ISSUE TITLE
[BUG] AttributeError: 'PlaywrightContextManager' object has no attribute '_playwright' when using gunicorn

### ISSUE THREAD

**Issue by Rezenhorn** [microsoft/playwright-python#1851]
**Context:**

- Playwright Version: 1.30.0/1.32.1
- Operating System: Linux
- Python version: 3.7.4
- Browser: Chromium
- Extra: run application with venv + gunicorn 20.1.0 with multiple workers

**Code Snippet**

```python
>>> from playwright.sync_api import sync_playwright
>>> with sync_playwright() as p:
>>>    browser = p.chromium.launch()
```

**Describe the bug**

When running application without gunicorn everything works fine, but when I try to run it together with gunicorn, the following error appears:

```python
AttributeError: 'PlaywrightContextManager' object has no attribute '_playwright'
```

I managed to find the reason: system couldn't find the path in the file `venv/lib/python3.7/site-packages/playwright/driver/playwright.sh` written in the second line:

```sh
SCRIPT_PATH="$(cd "$(dirname "$0")" ; pwd -P)"
```

The error disappears if you change this line to the following:

```sh
SCRIPT_PATH="path_to_app/venv/lib/python3/site-packages/playwright/driver"
```

**Comment by Rezenhorn** [comment]
I am running my Flask application with Gunicorn and Nginx on Linux. The steps are almost the same with this instruction: <https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-gunicorn-and-nginx-on-ubuntu-18-04>.
Gunicorn configs are written in two files:
`gunicorn.conf.py`
```python
import multiprocessing

bind = ["0.0.0.0:5050", "unix:my_app.sock"]
workers = multiprocessing.cpu_count() * 2 + 1

enable_stdio_inheritance = True
limit_request_line = 0
timeout = 90

umask = 0o007
preload = True
```
`myapp.service`
```service
[Unit]
Description=Gunicorn instance to serve myapp
After=network.target

[Service]
User=admin
Group=admin
WorkingDirectory=/opt/myapp
Environment="PATH=/opt/myapp/venv/bin"
ExecStart=/opt/myapp/venv/bin/gunicorn -c /opt/myapp/gunicorn.conf.py app:app
Restart=on-failure
RestartSec=10s

[Install]
WantedBy=multi-user.target
```

**Comment by CosmoFox** [comment]
Yeah! Got same problem with GU + Nginx + flask app with playwright.
And yes. at this time changing `SCRIPT_PATH="$(cd "$(dirname "$0")" ; pwd -P)"` to direct path fixing that problem.

**Comment by mxschmitt** [comment]
I tried to reproduce it with flask and gunicorn, but wasn't able to. Maybe because I'm on macOS, will try on Linux aka. Ubuntu later.

**Comment by mxschmitt** [comment]
Works for me on Linux as well. Does someone mind creating a reproduction in form of a docker image inside a Git repository?

We'd be more than happy to fix it but without being able to reproduce it, we unfortunately can't act on it.

**Comment by CosmoFox** [comment]
i`ll try to do

**Comment by mxschmitt** [comment]
This issue looks stale, due to our triaging process I'll close it for now. If you are able to share a reproduction, please re-file and then we'll continue to take a look.

Thanks for your understanding.

**Comment by mxschmitt** [comment]
Python 3.7 is not supported, make sure to use a recent Python version, e.g. 3.11.

**Comment by psklb** [comment]
same behavior here.  same workaround. Thank you
My config : 

```
Linux GH 6.1.0-17-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30) x86_64 GNU/Linux

Package           Version
----------------- -------
blinker           1.7.0
click             8.1.7
Flask             3.0.0
gevent            23.9.1
greenlet          3.0.3
gunicorn          21.2.0
itsdangerous      2.1.2
Jinja2            3.1.3
MarkupSafe        2.1.3
packaging         23.2
pillow            10.2.0
pip               24.0
playwright        1.41.2
pyee              11.0.1
python-pip        1.1.1
setuptools        66.1.1
typing_extensions 4.9.0
Werkzeug          3.0.1
zope.event        5.0
zope.interface    6.1
```
