### ISSUE TITLE
Running docker container with python 3.11

### ISSUE THREAD

**Issue by lewisevansio** [microsoft/playwright-python#1858]
### Your question

I have started a Playwright project using Python 3.11, however I am running into some trouble with the current Playwright Python docker image as it uses Python 3.8. Is there a recommended way to upgrade the python version in the docker image? I appreciate any information that can be provided as I am new to using Playwright with Docker.

**Comment by mxschmitt** [comment]
You can use the jammy image which will use Python3.10 - would that work for you?

https://playwright.dev/python/docs/docker

    docker pull mcr.microsoft.com/playwright/python:v1.32.0-jammy

**Comment by lewisevansio** [comment]
Yes that's very helpful and is working as I had hoped, thank you!

**Comment by gerzha** [comment]
Does exists docker image with python 3.11 and playwright? More older version isn't actual
