### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by brittabeta** [microsoft/playwright-python#1872]
**Context:**
- Playwright Version: playwright-1.32.1
- Operating System: Windows
- Python version: 3.9.16
- Browser: Chrome
- Extra: Google Colab

```python
with TikTokApi() as api:
    for trending_video in api.trending.videos(count=50):
        # Prints the author's username of the trending video.
        print(trending_video.author.username)
```
RuntimeError: This event loop is already running

```python
from TikTokApi import TikTokApi as api
for trending_video in api.trending.videos(count = 100000):
  print(trending_video.author.username)
Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally.
```
AttributeError: 'TikTokApi' object has no attribute '_width'

**Comment by mxschmitt** [comment]
Looks not related to Playwright, closing by that.

**Comment by brittabeta** [comment]
Sorry was trying to report to tiktokapi
