### ISSUE TITLE
[Question]: Need to help to understand why Playwright is not loading a URL.

### ISSUE THREAD

**Issue by nitin-g2** [microsoft/playwright-python#1873]
### Your question

[http://www.stanleyblackanddecker.com/](http://www.stanleyblackanddecker.com) URL is redirecting to [https://www.stanleyblackanddecker.com/](https://www.stanleyblackanddecker.com/) (301) . If I try to load this URL with "http" scheme then Playwright is throwing a timeout error.
Playwright is able to load other URLs with "http" scheme successfully, For this URL I am not able to find any reason why it is failing.

**Comment by mxschmitt** [comment]
The website has some WAF in place which blocks requests based on some user agents. In this case e.g. because it contains that its Headless Chrome.

```py
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    for browser_type in [p.chromium]:
        browser = browser_type.launch()
        page = browser.new_page(user_agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36")
        page.goto('http://www.stanleyblackanddecker.com/')
        page.screenshot(path=f'example-{browser_type.name}.png')
        browser.close()
```

To fix it, just pass a static UA.
