### ISSUE TITLE
[Question]: Pytest starts throwing errors half way through a test with parallel tests

### ISSUE THREAD

**Issue by RevTyler** [microsoft/playwright-python#1879]
### Your question

Preamble:
Ubuntu 22
Playwright 1.32.1
Pytest 7.3.1
Pytest-xdist 3.2.1
Browser: Chrome

Issue:
I've got my tests running fine when they're run one at a time, but when I start using pytest-xdist and -n auto, the test starts just fine, but after 50-70% of the tests, one or more of the workers just start throwing the same error:

They're all the same error: 
playwright._impl._api_types.Error: 
E       ╔════════════════════════════════════════════════════════════════════════════════════════════════╗
E       ║ Looks like you launched a headed browser without having a XServer running.                     ║
E       ║ Set either 'headless: true' or use 'xvfb-run <your-playwright-app>' before running Playwright. ║
E       ║                                                                                                ║
E       ║ <3 Playwright Team                                                                             ║
E       ╚════════════════════════════════════════════════════════════════════════════════════════════════╝

I'm running headed on my local machine. The worker starts fine and the rest of the workers are fine.

The only think that I can think of is an issue with the way I'm making my own page fixture?

I have a get_page() function that serves two purposes, a) configure the browser based on a yaml config file instead of CLI arguments and b) reduces some code re-use so that I can call it from 3 differently scoped fixtures. The module/session scoped fixtures are never used in this test suite. Only function scope.

The whole suite runs fine in headless mode, but I'd prefer to run it headed on my local machine.

```
def get_page(playwright: Playwright,
             config: Config) -> Generator[Page, None, None]:
    """Creates and returns a playwright page."""
    # Overwrite the pytest CLI arguments with run config
    is_headless = config.get(HEADLESS)
    browser_name = config.get(BROWSER)

    if browser_name == "msedge":
        browser = playwright.chromium.launch(
            channel=browser_name, headless=is_headless)
    else:
        browser_type: BrowserType = getattr(playwright, browser_name)
        browser = browser_type.launch(headless=is_headless)

    page = browser.new_page()

    if not is_headless:
        page.set_viewport_size({"width": 1700, "height": 900})

    return page
```

This is the function scoped fixture.

```
@pytest.fixture(name="function_page", scope="function")
def function_page_fixture(playwright: Playwright,
                          config: Config) -> Generator[Page, None, None]:
    """Returns a function-scoped page."""
    page = get_page(playwright, config)

    yield page

    page.close()
```

**Comment by mxschmitt** [comment]
What I can see is that your page is leaking browser instances, since you never close your browser instance after a test has finished. To fix that I'd recommend to create your own browser fixture which has the session scope, then after the yield you can close the browser.

Also one thing to optimise is that you can move the page.set_viewport_size into the browser.new_page constructor. It accepts a viewport parameter.

Why are you running your tests headed? This requires much more CPU/RAM than running them headless.

See here for how we do this in our Pytest plugin: https://github.com/microsoft/playwright-pytest/blob/main/pytest_playwright/pytest_playwright.py#L215

**Comment by RevTyler** [comment]
Ah, I suppose that makes sense. I definitely falsely assumed that closing the page would close everything beneath it.

I'll have a look through that source and improve my fixture.

As for why I'm running headed, I'm pretty new to UI testing and to be honest it's an irrational security feeling that I can see something happening, haha. Especially during test development. Once they're good to go the suite gets tossed on Jenkins and runs headless. But if I'm running it manually it feels better to see things moving on the screen.

**Comment by RevTyler** [comment]
Update:

You were exactly right. It was due to leaking browsers. The session scoped browser fixture did the trick. I'm also actively closing the context as well.
