### ISSUE TITLE
[BUG] Fail to close context when running inside a larger loop

### ISSUE THREAD

**Issue by AlmogBaku** [microsoft/playwright-python#1886]
**Context:**
- Playwright Version: 1.32.1
- Operating System: macos
- Python version: [e.g. 3.7, 3.9]
- Browser: all

**Describe the bug**

I'm running a gRPC server using a loop, and then using playwright to fetch some URL: https://github.com/hwchase17/langchain/blob/e3b7a20454cea592fc6d0a0d91c36206e8ad6790/langchain/document_loaders/url_playwright.py#L62

when the context is exiting, this error is thrown
```RuntimeError: Set changed size during iteration```

this is happening due to an old upstream bug in cpython https://github.com/python/cpython/issues/80788

we need to refactor the context manager to close itself differently
https://github.com/microsoft/playwright-python/blob/b9b8fed2454bcfb0d5ae6571e22ef657862f7ac5/playwright/sync_api/_context_manager.py#L106

TBH, I don't know why we even do that :O

**Comment by mxschmitt** [comment]
Playwright is only supported in a single thread and does not allow any thread-sharing operations. Is this maybe the reason why this comes up?

It was added as part of https://github.com/microsoft/playwright-python/pull/1430. Would have to dig deeper to understand the reason behind this change.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.
