### ISSUE TITLE
[Feature] Remove overly strict dependency on old version of greenlet

### ISSUE THREAD

**Issue by cyberw** [microsoft/playwright-python#1915]
greenlet 2.0.1 has issues with debugging in vscode (https://github.com/microsoft/debugpy/issues/1126)

Can we relax the dependency to `~=2.0.1`, or at least just bump it to 2.0.2?

**Comment by mxschmitt** [comment]
Happy to bump! The last time the blocker was that conda had no v2.0.2: https://anaconda.org/anaconda/greenlet

**Comment by mxschmitt** [comment]
Looks like because this pipeline failed: https://github.com/conda-forge/greenlet-feedstock/commit/8deb30e52ac98f97f3eef98e9b28411576b1f44e

**Comment by cyberw** [comment]
Nice! Thanks!

**Comment by jace** [comment]
Greenlet 3.0 has been released as of last month, and [as per the release notes, retains a compatible API](https://greenlet.readthedocs.io/en/latest/changes.html) while also adding Python 3.12 support. It'll help if Playwright does not pin exact dependencies – my test requirements now conflict with my main requirements (Greenlet is also a dependency for SQLAlchemy).
