### ISSUE TITLE
Long term support of this library

### ISSUE THREAD

**Issue by Mattwmaster58** [microsoft/playwright-python#192]
Hi, I'm considering endorsing this library, but was wondering what the long term support plans for this library are. I wasn't able to find a roadmap either, but other than that this looks like a promising effort for controlling browsers with Python! Keep up the good work!

**Comment by pavelfeldman** [comment]
Playwright team here at Microsoft is committed to supporting this library along with the Node version and other language bindings for Playwright.

We are still looking for early adopters to validate the Python API and ensure both sync and async versions of APIs match their exepectations. Once we cross the 1.* boundary, it'll get on the shared release train with the Node version.
