### ISSUE TITLE
Unable to install the browsers using  "playwright install"

### ISSUE THREAD

**Issue by Kumaravel09** [microsoft/playwright-python#1922]
**### Unable to install the browsers**
- Playwright Version: [1.33.0]
- Operating System: [Windows]
- Python version: [3.11]
- pip: [23.1.2]
- PY Charm editor
![image](https://github.com/microsoft/playwright-python/assets/53257563/6dc3b245-3974-4844-90ab-b204ef17c918)

**Problem description:**
After installing playwrigth. I'm not able to run "playwright install" command to install browsers tried in multiple cmd terminals and editors. 
Nothing I got after "playwright install". It just show the another command line to write. Please find the attachment:
![image](https://github.com/microsoft/playwright-python/assets/53257563/27dc454f-67d4-4d88-bd14-f8c49b3bb019)

**Comment by mxschmitt** [comment]
Most likely the browsers are already installed, then we don't print any output. You can try `playwright install --dry-run` to see if the CLI works. Also you can try `python -m playwright install`.
