### ISSUE TITLE
[Feature] Please implement Electron as soon as possible. 

### ISSUE THREAD

**Issue by jintao-ng** [microsoft/playwright-python#1923]
[Let us know what functionality you'd like to see in Playwright and what your use case is.]

We want Playwright-python to be connected to Electron as soon as possible. Playwright-Node.js is already connected, but our test engineer's automation project uses python, and we can't use Playwright-python for desktop applications because it's not connected to Electron. Testing

[Do you think others might benefit from this as well?]

There are a lot of desktops applications on the market now, and they should all have similar requirements to us

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright-python/issues/379
