### ISSUE TITLE
page.content() Unable to obtain comprehensive webpage content

### ISSUE THREAD

**Issue by zhonghai9967** [microsoft/playwright-python#1932]
**Context:**
-1.33.0
- Operating System:  Windows
- Python version:3.10.11 on win32
- Browser: [ Chromium, Firefox]

**Code Snippet**
```python
from playwright.sync_api import sync_playwright
from pyquery import PyQuery as pq

def test_run(browser):
    # ...
   res=page.goto(...)
  dd = pq(page.content())
```
"input type="text" id="generalTw" value"
the “value”  can be seen, It can also be obtained through "page.locator('input#generalTw').input_value()",
but, Do not display the value  in page.content()。
This doesn't seem like an issue with playwright, as it can be obtained normally on other websites.
why?thank you！

**Comment by mxschmitt** [comment]
Would it be possible to share a full reproduce which we can run locally?

**Comment by zhonghai9967** [comment]
Internal website of the enterprise, inconvenient to provide. I'm sorry
