### ISSUE TITLE
[Question]: case mismatch between API and actual package?

### ISSUE THREAD

**Issue by miguel-qdm** [microsoft/playwright-python#1933]
### Your question

I am using Playwright 1.33 via python 3.9.4.

I noticed that the modules within Playwright are using snake_case. However, the API documentation uses camelCase.

For instance: https://playwright.dev/docs/api/class-locator#locator-get-by-label
The code snippet uses 'getByLabel' which at runtime produces the following error
`AttributeError: 'Page' object has no attribute 'getByLabel'`

Changing this module to 'get_by_label' allows it to be interpreted for me.

This seems to be lacking documentation. I found an [Git Issue](https://github.com/microsoft/playwright-python/issues/276) regarding a camel --> snake transition in playwright 1.8 but it is unclear.

So is the API out of date entirely, and any instance of camelCase needs to be rewritten as snake_case?

**Comment by mxschmitt** [comment]
Python has dedicated docs, you can switch to them at the navbar at the top and select Python.

See e.g. https://playwright.dev/python/docs/api/class-locator#locator-get-by-label
