### ISSUE TITLE
[Question]: stuck with page.getByLabel

### ISSUE THREAD

**Issue by wanghaisheng** [microsoft/playwright-python#1936]
### Your question

    <yt-img-shadow height="32" width="32" class="style-scope ytd-topbar-menu-button-renderer no-transition" style="background-color: transparent;" loaded=""><img id="img" draggable="false" class="style-scope yt-img-shadow" alt="头像图片" src="https://yt3.ggpht.com/YvuhXqXSx8HrsX-_rburuBeGUSHGfohcQceSUdVqW32XfAfXo4U7hdJc3_aTGCFGNlGv-ehNU2I=s88-c-k-c0x00ffffff-no-rj-mo" width="32" height="32"></yt-img-shadow>
  

await localPage.get_by_label("Account menu").wait_for()

could not find the element  am I wrong

**Comment by mxschmitt** [comment]
We need a full reproducible to be able to act on this. If your selector is not working, we recommend using Codegen to generate a locator: https://playwright.dev/python/docs/codegen-intro#running-codegen

You can also trigger it via `page.pause()`.

Please re-file with more information.

**Comment by wanghaisheng** [comment]
can you add this hint to document where you explain locator method support xpath,css selector. that would be helpful.
these days I always confused about best practise to get the right selector to point at 
@mxschmitt
