### ISSUE TITLE
[BUG] Playwright can't access iframe content in Firefox browser

### ISSUE THREAD

**Issue by deivydaslipskis** [microsoft/playwright-python#1947]
**Context:**
- Playwright Version: 1.34.0
- Operating System: Ubuntu 22.04
- Python version: 3.10.4
- Browser: Firefox
- Using FrameLocator - https://playwright.dev/python/docs/api/class-framelocator

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally.

```python
from playwright.sync_api import sync_playwright
from time import sleep

def main():
    with sync_playwright() as playwright:
        # Select browser type
        browser_type = playwright.firefox
        browser = browser_type.launch(headless=False)
        context = browser.new_context()
        page = context.new_page()

        # Navigate to the webpage containing the iframe
        page.goto('https://www.google.com')


        # Switch to the iframe
        iframe_locator = page.frame_locator('[title="Widget containing checkbox test"]')
        
        # Perform actions within the iframe
        checkbox = iframe_locator.locator('input[type="checkbox"]')
        sleep(10)
        checkbox.click()

        print(f"Page content - {page.content()}")
        # Close the browser
        browser.close()

if __name__ == '__main__':
    main()
```

**Describe the bug**

When using Firefox as the browser Playwright can't locate iframe content. The iframe is located and the embedded document is the same, but the click() fails with the timeout since it can't find the locator, while it instantly works with Chromium and Webkit.

Here is an example of the iframe:
`<iframe src="./tst_files/normal.html" allow="cross-origin-isolated" id="tst-chl-widget-3stgj" tabindex="0" title="Widget containing checkbox test" style="border: none; overflow: hidden; width: 300px; height: 65px;"></iframe>`

And here is a part of the embedded HTML document inside the iframe above:
`<label class="ctp-checkbox-label"><input type="checkbox"><span class="mark"></span><span class="ctp-label">Click Here</span></label>`

I have tried having larger waiting times but to no avail.

It seems that iframes inside Firefox should be accessed in a different manner.

**Comment by mxschmitt** [comment]
Can you provide us a self contained reproduction which we can run locally? Also make sure to never use sleep and use `page.wait_for_timeout(1000)` instead see [here](https://playwright.dev/python/docs/library#timesleep-leads-to-outdated-state).
