### ISSUE TITLE
[Question]: how do you access the __pw_recorder* stuff from python?

### ISSUE THREAD

**Issue by grahamannett** [microsoft/playwright-python#1948]
### Your question

If you start a browser from python, the window/browser console has a bunch of the injected scripts/Recorder class and it seems like it should be possible to access these from python the same way you can from the js server for instance where it gives you the actionInContext object in the server/recorder.ts file

```
actionInContext {
  frame: {
    pageAlias: 'page',
    isMainFrame: true,
    url: 'https://www.google.com/?gws_rd=ssl'
  },
  action: {
    name: 'click',
    selector: 'internal:role=combobox[name="Search"i]',
    position: undefined,
    signals: [],
    button: 'left',
    modifiers: 0,
    clickCount: 1
  }
}
```

I understand this is not supported, but is it possible?  I need something similar to what generateSelector in selectorGenerator.ts does and tried to write my own (to go from element to a similar way to later find this element) and realized it is insanely complicated.

**Comment by mxschmitt** [comment]
What is your use-case for it? These are internals which we don't plan to expose, they are also not exposed as part of our public API (also not for JS).

Yes writing a generator is not a trivial task, maybe file a feature request for it or what are you trying to achieve?

**Comment by grahamannett** [comment]
i am trying to record actions and aspects of the page/browser in a more customized way and without having to copy the generated code from the playwright inspector.  

i'm sure you know more than me about playwright, and many of these are available via js console upon calling page.pause() (for instance playwright.getByText) so I get that while its not supported, it seems like its already possible to hook into the channels or however this communication is happening

**Comment by mxschmitt** [comment]
This is not supported, I recommend starting with a feature requests and/or forking Playwright if your use-case is too specific.
