### ISSUE TITLE
[Feature] ability group outputs in the trace viewer

### ISSUE THREAD

**Issue by scott-au** [microsoft/playwright-python#1949]
the [show steps/fixtures in the trace](https://youtu.be/JeFD6rqDbBo?t=94) is certainly a nice feature released in 1.34 - grouping all the associated actions makes a trace file easier to go through.

is there any chance we could also have some sort of mechanism that allows us to group actions together in a similar fashion for users not using playwright test.

**Comment by DetachHead** [comment]
i looked into this and would like to have a go at implementing it. it seems straightforward, looks like trace events just need the `parentId` field in the metadata.

i will probably make a `step` context manager that works the same as the `test.step` method in `@playwright/test`

**Comment by EldoradoEU** [comment]
Any update ? I also looking for similar feature

**Comment by DetachHead** [comment]
unfortunately it turned out to be more difficult than i thought, so i went with a very hacky solution that's tied to my own project which i can't really share.

@mxschmitt would you happen to have some insight on how i could go about implementing this? do i need to expose `TestInfo._addStep` to python? if so, how?

**Comment by danielmhair** [comment]
Yes, grouping outputs is important to what I'm doing but I'm in Python, not typescript. I would love this feature!

**Comment by scott-au** [comment]
> unfortunately it turned out to be more difficult than i thought, so i went with a very hacky solution that's tied to my own project which i can't really share.
> 
> @mxschmitt would you happen to have some insight on how i could go about implementing this? do i need to expose `TestInfo._addStep` to python? if so, how?

@mxschmitt any guidance here ? sounds like @DetachHead is keen to submit a PR

**Comment by Snooz82** [comment]
this feature should be possible when https://github.com/microsoft/playwright/pull/33081 is merged into Playwright NodeJS.

it introduces a grouping possibility for `context.tracing`

**Comment by Snooz82** [comment]
FYI: this feature has just been merged to core!🎊

Hi Dmitry (@dgozman),

is that already automatically added to Playwright-Python?

if so, i think this issue can also be closed.

Thanks
René

**Comment by DetachHead** [comment]
they have a bot that automatically creates issues for porting changes from the main playwright repo. since your PR is mentioned in #2606 i guess this issue can now be closed

thanks for your work on this! i can finally delete a bunch of hacky patches from my project
