### ISSUE TITLE
[BUG] newPage() got an unexpected keyword argument 'defaultBrowserType'

### ISSUE THREAD

**Issue by arjun27** [microsoft/playwright-python#195]
Repro steps for repl

```
>>> from playwright import sync_playwright
>>> playwright = sync_playwright().start()
>>> browser = playwright.webkit.launch(headless=False)
>>> iPhone11 = playwright.devices['iPhone 11']
>>> context = browser.newContext(**iPhone11)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: newContext() got an unexpected keyword argument 'defaultBrowserType'
```

[Relevant source](https://github.com/microsoft/playwright-python/blob/26ac810f44e88dbade3364f850a06b7b97340a7f/playwright/browser.py#L67).

**Comment by arjun27** [comment]
I believe this same fix also needs to be applied to the `browser.newPage` API. Re-opening the issue.

**Comment by xsoft7** [comment]
I've got similar issue and got the same error -  python 3.12, macos, playwright 1.39.

This is my fixture in conftest:

```
@pytest.fixture(scope="function")
def pw(browser_type: BrowserType, browser_type_launch_args: Dict, browser_context_args: Dict) -> (Page, Browser):
    browser = browser_type.launch(headless=True,
                                  args=["--start-maximized"],
                                  )
    context = browser.new_context(viewport={"width": 1920, "height": 1080},
                                  record_video_dir="./debug/videos/",
                                  record_video_size={"width": 1920, "height": 1080},
                                  **browser_type_launch_args,
                                  **browser_context_args, )
    context.tracing.start(screenshots=True, snapshots=True, sources=True)
    page_object = context.new_page()
    yield page_object, browser
    context.tracing.stop(path=f'./debug/traces/trace{str(datetime.now()).replace(' ','_')}.zip')
    context.close()
    page_object.close()
```

this is the command i run from terminal:


python -m pytest --headed


the output error i receive:

ERROR tests/generic_test.py::TestGeneric::test_generic1[chromium] - TypeError: Browser.new_context() got an unexpected keyword argument 'headless'

>

**Comment by mxschmitt** [comment]
You are passing `browser_type_launch_args` to `new_context` which is not supported. You need to pass it to `launch` instead.

**Comment by xsoft7** [comment]
Hey, thanks for the quick reply.

I changed as you suggested. e.g.:

`@pytest.fixture(scope="function")
def pw(browser_type: BrowserType, browser_type_launch_args: Dict, browser_context_args: Dict) -> (Page, Browser):
    browser = browser_type.launch(headless=True,
                                  args=["--start-maximized"],
                                  **browser_type_launch_args,
                                  **browser_context_args,
                                  )
    context = browser.new_context(viewport={"width": 1920, "height": 1080},
                                  record_video_dir="./debug/videos/",
                                  record_video_size={"width": 1920, "height": 1080},
                                )
    context.tracing.start(screenshots=True, snapshots=True, sources=True)
    page_object = context.new_page()
    yield page_object, browser
    context.tracing.stop(path=f'./debug/traces/trace{str(datetime.now()).replace(' ','_')}.zip')
    context.close()
    page_object.close()`
    
    
    And i still receive the same error.
    
    
   Regarding your question (if i understood it correctly):
   
   I did a custom fixture, for those browser launches, as i need those things (traces, videos..) i dont want to repeat it in the tests
