### ISSUE TITLE
[BUG] Chromium not installing in Debian 11 (docker python:3.9)

### ISSUE THREAD

**Issue by Fluder-Paradyne** [microsoft/playwright-python#1959]
**Context:**
- Playwright Version: 1.18.1
- Operating System: debian 11 ( docker image of python:3.9 )
- Python version: 3.9
- Browser: Chromium
- Extra: in python:3.9 docker image

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally.

```python
import asyncio
from playwright.async_api import async_playwright


async def main():
    async with async_playwright() as p:
        browser = await p.chromium.launch()
        context = await browser.new_context()
        page = await context.new_page()
        await page.goto('https://example.com')
        print(await page.title())
        await browser.close()


asyncio.run(main())
```

```docker file
FROM python:3.9
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN playwright install --with-deps  chromium
COPY . .
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh 

CMD ["/entrypoint.sh"]
```

pip is installing properly 

**Describe the bug**

![image](https://github.com/microsoft/playwright-python/assets/121793617/ce307b64-ea60-4a09-bf42-c2d33c66f927)

if I do run the command

![image](https://github.com/microsoft/playwright-python/assets/121793617/631bee30-25b0-47d2-9e87-166bc80ac2f8)

I am getting this

am I doing something wrong

thank you for looking into this

**Comment by mxschmitt** [comment]
Your Playwright version is too old, if you upgrade to the latest version, it should work!

**Comment by Fluder-Paradyne** [comment]
![image](https://github.com/microsoft/playwright-python/assets/121793617/b46f67a5-0332-4de2-a682-399a3a3d9618)
