### ISSUE TITLE
[BUG] use  screenshot(full_page=True) Browser automatic refresh

### ISSUE THREAD

**Issue by litebin** [microsoft/playwright-python#1972]
**Context:**
- Playwright Version: 1.33
- Operating System: Windows
- Python version: 3.9
- Browser: Chromium
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally.

```python
        from playwright.sync_api import sync_playwright

        play = sync_playwright().start()
        # play.chromium.launch() firefox
        browser = play.chromium.launch(headless=False, args=['--start-maximized'])
        context = browser.new_context(no_viewport=True)
        page = context.new_page()
allure.attach(page .screenshot(full_page=True), '成功截图', allure.attachment_type.PNG)
```

**Describe the bug**

Use allare. attach (ddt. web. screenshot(full_page=True)), 'Successful screenshot', allare. attachment_ Type. PNG), the page will automatically refresh, causing the left menu to automatically collapse and the page cannot be found

**Comment by mxschmitt** [comment]
Can you share a full reproducible with us With expected and actual outcomes? 

Without that we are unfortunately not able to assist here, thanks for your understanding,.d

**Comment by mxschmitt** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
