### ISSUE TITLE
[BUG] Docker images don't appear to come with playwright installed.

### ISSUE THREAD

**Issue by bwinter** [microsoft/playwright-python#1978]
**Context:**
- Playwright Version: 1.33.0 (trying to use 1.34.0/1.35.0)
- Operating System: Linux
- Python version: 3.10.6 (comes with mcr.microsoft.com images)
- Browser: N/A to this bug
- Extra: 

**Code Snippet**

Build images and compare the container's `pip list` output:
```
FROM mcr.microsoft.com/playwright/python:v1.33.0

COPY . .
```

```
FROM mcr.microsoft.com/playwright/python:v1.34.0

COPY . .
```

**Describe the bug**

More recent Docker images don't appear to come with playwright properly installed. Or the intended usage has changed, but is not properly documented in release notes. (It seems impossible I am the first to notice this but I couldn't find any obvious open / closed issues on the web describing what I am seeing.)

e.g. 

1.33.0 (similar in 1.32.1)
```
root@a850b1bfbf75:/# pip list
Package           Version
----------------- -------
greenlet          2.0.1
pip               23.1.2
playwright        1.33.0
pyee              9.0.4
setuptools        67.7.2
typing_extensions 4.5.0
wheel             0.40.0
```

1.34.0 (similar in 1.35.0)
```
root@9a74fe4c7348:/# pip list
Package      Version
------------ -------
distlib      0.3.6
filelock     3.12.0
pip          23.1.2
platformdirs 3.5.1
setuptools   67.8.0
virtualenv   20.23.0
wheel        0.40.0
```

**Comment by mxschmitt** [comment]
It got actually intentionally removed in https://github.com/microsoft/playwright-python/pull/1921. The Docker image as per [our docs](https://playwright.dev/docs/docker) don't have Playwright installed. They have the browsers and browser dependencies installed. Its up to the user to install Playwright with his package manager of choice.

We didn't add it to the release-notes, since we thought it might not break many people (it has no pytest-playwright anyways). Sorry for the inconvenience!

**Comment by bwinter** [comment]
Gotcha. Thanks for the quick feedback!

Seems like getting playwright installed should be pretty simple in our existing setup.

Since it was a breaking change it might be worth putting a footnote in the release notes. Though given I didn't see anyone else running into the issue, you may be right that we are a bit of an outlier. 😅

I am fine to close this. Thanks again. 👍

**Comment by andreaslongo** [comment]
Given the following:

We pin the container image to a specific version as noted here: https://playwright.dev/python/docs/docker#image-tags

e.g. we run `mcr.microsoft.com/playwright/python:v1.34.0`

Then we install Playwright inside the container as suggested in the introduction here: https://playwright.dev/python/docs/ci#introduction

e.g. we run `python -m pip install playwright` inside the container.

Is it a problem if the Playwright version does not match the container image version?

```
python -m pip list
Package           Version
----------------- -------
<snip>
playwright        1.35.0
<snip>
```

**Comment by FANGOD** [comment]
I've been looking for this for a long time, so what's written in the documentation is wrong.  https://playwright.dev/python/docs/docker

**Comment by varac** [comment]
Yes, please update the documentation accordingly. In the "docker" docs there's no trace of the need to install Playwright at runtime.
 I also wasted a fair bit of time trying to understand what I'm doing wrong. Thanks!
