### ISSUE TITLE
[Question]: Capture all console log messages then save to list for using later

### ISSUE THREAD

**Issue by waterpep** [microsoft/playwright-python#1979]
### Your question

Hello Playwright team!
Could you please  help me on this:
I'm testing a site which emit a list of logs on console after using for a while
**Desired:** Capture **ALL** those logs then save to a variable(list) for using later

Use case looks like: Open browser then open the console log then access the page : https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_console_log 
,  then click the Run btn, each time got 'Hello World!" on the console --> I would like to save all that logs to variable.

![image](https://github.com/microsoft/playwright-python/assets/136793767/8ddf33cf-aafd-41b5-94e9-052de6a38e19)

Here is the code snippet, that result print out is : [None] for me.
```
def test_1():
    def run(playwright: Playwright) -> None:
        browser = playwright.chromium.launch(headless=False)
        context = browser.new_context()
        page = context.new_page()

        logs = list()

        logs.append(
            page.on("console", lambda msg: msg.text)
        )
        page.goto(
            "https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_console_log"
        )
        sleep(5)  # Sleep for manually click btn Run
        print(logs)

        context.close()
        browser.close()

    with sync_playwright() as playwright:
        run(playwright)

```
Note: can see this: https://github.com/microsoft/playwright/issues/15281#issuecomment-1171729319 but cant able to convert to python world :( 
I'm on pytest and sync.
PS: I'm not a fancy python dev, so the working code snippet is very welcome👍 
Thank you all!

**Comment by mxschmitt** [comment]
You can do the following which will work:

```python
from playwright.sync_api import sync_playwright

with sync_playwright() as playwright:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()

    logs = list()

    page.on("console", lambda msg: logs.append(msg.text))
    page.goto("https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_console_log")
    page.wait_for_timeout(5_000)  # Sleep for manually click btn Run
    print(logs)

    context.close()
    browser.close()
```

**Comment by waterpep** [comment]
Whoa whoa, it works, so magical, 
thank you a lot @mxschmitt!
