### ISSUE TITLE
Is v0.140.0 a correct version?

### ISSUE THREAD

**Issue by ninoseki** [microsoft/playwright-python#199]
Just a question, is v0.140.0 a correct version?
Maybe v1.4.0 is the correct version for [this release](https://github.com/microsoft/playwright-python/releases/tag/v0.140.0)?

**Comment by mxschmitt** [comment]
Hi, no. We intentionally used this version to be below v1 but still refer somehow to the upstream version. We probably won't continue that and use normal semver after an offline discussion.

**Comment by ninoseki** [comment]
@mxschmitt Thanks, I understand that.
