### ISSUE TITLE
How Can I Get Information From Event That I Have From Web Socket?

### ISSUE THREAD

**Issue by Mikhail94** [microsoft/playwright-python#2007]
### Your question

Help me please. After an action, I have an even (It looks like this: {"event":"account_balance.updated","channel":"presence-organization.6533","data":"{\"account_balance\":1116,\"account_credits\":1125,\"trial_credits\":23}"})

I need to wait this event and get information about "account_balance" and write it to variable.

When I use ".wait_for_event" method I can't find event.

Pyton language

**Comment by mxschmitt** [comment]
wait_for_event is only designed for Playwright specific events, see here: https://playwright.dev/python/docs/api/class-page#events

You can wait for some JavaScript inside your browser via [`wait_for_function`](https://playwright.dev/python/docs/api/class-page#page-wait-for-function).

Where do you get this event? We need more information to be able to act on this issue.

**Comment by mxschmitt** [comment]
Oh its a WebSocket, then you can do something like this:

```python
 async with page.expect_event("websocket") as ws_info:
        # your websocket connection opens here
    ws = await ws_info.value
    event = await ws.wait_for_event("framereceived", predicate message: print(message))
```

in the predicate you can return true or false if its the right event or not, only then the wait_for_event will return.

**Comment by Mikhail94** [comment]
Great! .expect_event() works. 
But as I can see I can't get information from event and write to an variable? I can have answer only(true/false)?

**Comment by mxschmitt** [comment]
event holds your message and you can use the optional predicate to decide how long it should wait or not.

**Comment by Mikhail94** [comment]
ok. I got it
