### ISSUE TITLE
[Question]: Best practices for using page-objects as pytest fixtures and for implementing async methods

### ISSUE THREAD

**Issue by avielKogan1** [microsoft/playwright-python#2008]
### Your question

Hi!
I'm practicing playwright/pytest.
I wonder what would be the best practices for:
1. Implementing page-objects as PyTest fixtures?
2. Implementing async methods within page objects files.
3. Using the page object fixures in the test files themselves.

This is the high-level structure of my project: 

PROJECT
│   README.md
│
└───src
    │
    ├───infra
    │   │   __init__.py
    │   │
    │   └───page_objects
    │       └───login
    │           │   login_page.py
    │
    └───tests
        └───sanity_tests
                        │   test_login.py

**Comment by mxschmitt** [comment]
You can create custom Pytest fixtures with your POMs like that:

```python
@pytest.fixture
def my_page(page: Page):
    return MyPage(page)
```

See here: https://docs.pytest.org/en/6.2.x/fixture.html#back-to-fixtures

Playwright has no best practises in this regard for Python yet, so it totally depends on your project. If you feel comfortable with your setup, understand it and provides you all the flexibility, then its good enough!

**Comment by avielKogan1** [comment]
Yes, but when I want to use methods I've defined in the page object class, in the scope of the test, it doesn't recognize the methods and the attributes.

**Comment by mxschmitt** [comment]
You mean typing wise? Are you annotating it with types?

```python
def test_foo(my_page: MyPage) -> None:
    my_page.foo()
```

**Comment by avielKogan1** [comment]
this way?

`@pytest.fixture
async def login_page(browser):
    page = await browser.new_page()
    login_page = LoginPage(page)
    return login_page


@pytest.mark.asyncio
async def test_login_with_valid_credentials(login_page: LoginPage):
    await login_page.goto()
    await login_page.verify_page_loaded()

**Comment by mxschmitt** [comment]
Oh I see, you are not using our pytest-playwright plugin since you want to leverage the async version of Playwright.

Yes you could do it like that. You can modify your fixture to this and then it should work:

```python
@pytest.fixture
async def login_page(browser):
    page = await browser.new_page()
    login_page = LoginPage(page)
    yield login_page
```

see e.g. [here](https://tonybaloney.github.io/posts/async-test-patterns-for-pytest-and-unittest.html).

**Comment by avielKogan1** [comment]
@mxschmitt do you mean like this:

```
import pytest
import logging
from src.infra.page_objects.login.login_page import LoginPage
from src.infra.page_objects.platform.dashboard.dashboard_page import DashboardPage
from src.tests.test_data.test_data import User
from playwright.async_api import async_playwright


def pytest_configure(config):
    logging.basicConfig(level=logging.INFO)
    root = logging.getLogger()
    root.setLevel(logging.INFO)

@pytest.fixture
async def login_page(browser):
    page = await browser.new_page()
    login_page = LoginPage(page)
    yield login_page

@pytest.mark.asyncio
async def test_login_with_valid_credentials(login_page):
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()
        # Initializing user object
        user = User()
       
        # Go to login page
        await login_page.goto()

        # Verify Login Page loaded
        await login_page.verify_page_loaded()
        

        # Fill in user name
        await login_page.fill_username(user.username)

        # Fill in password
        await login_page.fill_password(user.password)

        # Click Login button
        await login_page.click_login_button()
 
```

             
I tried to run it this way and encoutered the following error:


> self = <_UnixSelectorEventLoop running=False closed=False debug=False>
> 
>     def _check_running(self):
>         if self.is_running():
>             raise RuntimeError('This event loop is already running')
>         if events._get_running_loop() is not None:
> >           raise RuntimeError(
>                 'Cannot run the event loop while another loop is running')
> E           RuntimeError: Cannot run the event loop while another loop is running
> 
> /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py:590: RuntimeError
> ================================================================================= short test summary info =================================================================================
> FAILED test_login.py::test_login_with_valid_credentials[chromium] - RuntimeError: Cannot run the event loop while another loop is running
> ==================================================================================== 1 failed in 0.79s ====================================================================================
> Task was destroyed but it is pending!
> task: <Task pending name='Task-5' coro=<test_login_with_valid_credentials() running at /Users/user1/Documents/GitHub/OrangeHRM_Automation/src/tests/sanity_tests/test_login.py:20>>
> sys:1: RuntimeWarning: coroutine 'test_login_with_valid_credentials' was never awaited
> RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**Comment by mxschmitt** [comment]
Why are you using async in the first place and not our pytest plugin? It provides a lot of things already out of the box: https://playwright.dev/python/docs/test-runners

You need to manually create a browser fixture, otherwise your login_page fixture doesn't know how to get the browser.

Something like this:

```python
@pytest.mark.asyncio
async def browser():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        yield browser
```

and then you can change your test to e.g. this:

```python
@pytest.mark.asyncio
async def test_login_with_valid_credentials(login_page):   
      # Go to login page
      await login_page.goto()

      # Verify Login Page loaded
      await login_page.verify_page_loaded()
      

      # Fill in user name
      await login_page.fill_username(user.username)

      # Fill in password
      await login_page.fill_password(user.password)

      # Click Login button
      await login_page.click_login_button()
 
```

**Comment by mxschmitt** [comment]
Closing as per above.

When creating own async pytest fixtures (not using pytest-playwright) we can't provide any official support. See [here](https://github.com/microsoft/playwright-pytest/blob/main/pytest_playwright/pytest_playwright.py) for our sync implementation, which should be very similar for async. And see https://github.com/microsoft/playwright-pytest/issues/74
