### ISSUE TITLE
Browser (Firefox/Chromium) not supported on current platform (Big Sur)

### ISSUE THREAD

**Issue by maxhumber** [microsoft/playwright-python#201]
Code:

```python
#test.py
from playwright import sync_playwright

playwright = sync_playwright().start()
browser = playwright.firefox.launch()

page = browser.newPage()
page.goto("http://whatsmyuseragent.org/")
page.screenshot(path=f"example-{browser_type.name}.png")

browser.close()
playwright.stop()
```

Run:

```sh
python test.py
```

Error:

> (node:4084) UnhandledPromiseRejectionWarning: Error: Browser is not supported on current platform

Details:

macOS (Big Sur - build 11.0 Beta 20A5374i)

**Comment by mxschmitt** [comment]
Closing in favor of https://github.com/microsoft/playwright/issues/2789

TL;DR: Playwright supports currently no Big Sur. We add it as soon its released as stable and bots are available for our tests.
