### ISSUE TITLE
[Question]: CLI arguments

### ISSUE THREAD

**Issue by Mortsadok10** [microsoft/playwright-python#2010]
### Your question

As for the Pytest Plugin Reference, I tried to add CLI arguments to the pytest.ini file, but it doesn't seem to be working.
For example, I add: addopts = **--tracing="on"**.
Expected: A new test files will created at **test-result/** but nothing happen.
It doesn't seem to refer to the pytest.ini file.
Any suggestions?

**Comment by israfilov-smartmicro** [comment]
Hello. The same for me. I'm trying to put  --tracing=on to command line and expect trace (it was working 1-2 months ago) but no trace is created.

**Comment by israfilov-smartmicro** [comment]
@mxschmitt I have the same versions of packages but my Python version is 3.9.

**Comment by mxschmitt** [comment]
What does `pytest` say when you run your tests? It should say something like:

```
plugins: xdist-2.5.0, base-url-2.0.0, forked-1.6.0, cov-3.0.0, playwright-0.3.3.post1+gcd35b83
```

Maybe the plugin is not installed. Do you mind sharing reproduction steps which work inside Docker like I did above? Since I'd have to be able to reproduce it in order to act on it, thanks!

**Comment by israfilov-smartmicro** [comment]
I run tests from pipenv. I don't know if this is important.
```
pipenv run pytest -m=run --headed --env={env} --slowmo=100 --alluredir=allurelogs --tracing=on

platform win32 -- Python 3.9.13, pytest-7.4.0, pluggy-1.2.0
rootdir: {path}
configfile: pytest.ini
plugins: allure-pytest-2.13.2, base-url-2.0.0, html-3.2.0, metadata-3.0.0, playwright-0.3.3, rerunfailures-12.0
collected 30 items / 29 deselected / 1 selected
``` 

>Maybe the plugin is not installed.

Which plugin do you mean?

**Comment by israfilov-smartmicro** [comment]
Could it be that the trace archive is saved not in the project directory, but somewhere else?

**Comment by mxschmitt** [comment]
test-results should be relative to your current working directory.

**Comment by Mortgotech** [comment]
Maybe it happened because I created a context that way:

`class TestContext:
    __test__ = False

    def __init__(self):
        self._context_holders = dict[str, ContextHolder]()
        self._browser: Optional[Browser] = None
        self._api_request: Optional[APIRequest] = None

    async def _get_browser(self) -> Browser:
        if self._browser is None:
            playwright = await async_playwright().start()
            self._browser = await playwright[config_provider.BROWSER].launch(headless=False)
        return self._browser
        
        async def _get_context(self, context_key: str) -> ContextHolder:
        if context_key not in self._context_holders:
            self._context_holders[context_key] = ContextHolder(self._get_browser, self._get_api_request)
        return self._context_holders[context_key]

    async def get_page(
            self, page_type: Type[TPageBase], context_key: str = "default", should_navigate: bool = False
    ) -> TPageBase:
        context_holder = await self._get_context(context_key=context_key)
        page = await context_holder.get_page()
        typed_page = page_type(page)
        if should_navigate:
            await typed_page.navigate()
        await typed_page.init_page()
        return typed_page`

Any suggestion?

**Comment by mxschmitt** [comment]
Creating an own context is not supported (yet).

Folding into https://github.com/microsoft/playwright-pytest/issues/111.
