### ISSUE TITLE
[Question]: How to open multiple pages with different contexts in one browser window instead of multiple browser window?

### ISSUE THREAD

**Issue by ukenmisneru** [microsoft/playwright-python#2013]
### How to open multiple pages with different contexts instead of multiple browser window?

Hi.. 
I got a question.
I need to post a lot of different queries for the same website and using different proxies.
Is it possible to open multiple pages with different contexts instead of multiple browser window?
It will consumes a lot of system resources if different contexts opened in multiple Browser windows.
Thanks

my code like below.  But it always open Multiple Browser.
![屏幕截图 2023-07-14 140506](https://github.com/microsoft/playwright-python/assets/121696122/656542dd-c7e5-49dd-a733-7730d53807d0)

`
async def main(queryList: list):
    async with async_playwright() as p:
        ff = p.firefox
        browser = await ff.launch(headless=False)
        context = await browser.new_context()
        tastList = [run(context, queryList[i]) for i in range(len(queryList))]
        results = await asyncio.gather(*tastList)

async def run(context : BrowserContext , query :str):
    try:
        page = await context.new_page()
        await page.goto("https://target.com/checker")
        #some code ...
    except Exception as e:
        print(e)`

**Comment by mxschmitt** [comment]
This is working as intended. A new_page call acts like a new Window. Also the pages on a new Context will be different Windows.
