### ISSUE TITLE
[BUG] Windows VM ERROR:main_dll_loader_win.cc(109)] Failed to load Chrome DLL

### ISSUE THREAD

**Issue by flowercoder** [microsoft/playwright-python#2016]
**Context:**

I think i have the same issue like this https://github.com/microsoft/playwright/issues/21490.

I try to figure out this，I try to use python -m playwright codegen -b firefox or python -m playwright codegen -b webkit.

All the result is same, I post it as blow:

`
C:\Users\Administrator\Documents\baidubce>python -m playwright codegen -b firefo
x
[Error: Browser closed.
==================== Browser output: ====================
<launching> C:\Users\Administrator\AppData\Local\ms-playwright\chromium-1071\chr
ome-win\chrome.exe --disable-field-trial-config --disable-background-networking
--enable-features=NetworkService,NetworkServiceInProcess --disable-background-ti
mer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-c
ache --disable-breakpad --disable-client-side-phishing-detection --disable-compo
nent-extensions-with-background-pages --disable-component-update --no-default-br
owser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions
--disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,D
estroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,Aut
oExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBe
foreUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --
disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-rep
ost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-record
ing-only --no-first-run --password-store=basic --use-mock-keychain --no-service-
autorun --export-tagged-pdf --no-sandbox --app=data:text/html, --window-size=600
,600 --window-position=1020,10 --test-type= --user-data-dir=C:\Users\ADMINI~1\Ap
pData\Local\Temp\2\playwright_chromiumdev_profile-xlf6zI --remote-debugging-pipe
 about:blank
<launched> pid=3456
[pid=3456][err] [0718/175224.644:ERROR:main_dll_loader_win.cc(109)] Failed to lo
ad Chrome DLL from C:\Users\Administrator\AppData\Local\ms-playwright\chromium-1
071\chrome-win\chrome.dll:  (0x7F)]
`

- Playwright Version: [what Playwright version do you use?] the latest (1.3.6)
- Operating System: [e.g. Windows, Linux or Mac] window server 12
- Python version: [e.g. 3.8, 3.9] 3.8
- Browser: [e.g. All, Chromium, Firefox, WebKit] All
- Extra: [any specific details about your environment]

**Comment by mxschmitt** [comment]
You need to have at least Windows Server 2016, see here: https://playwright.dev/python/docs/intro#system-requirements

**Comment by flowercoder** [comment]
> You need to have at least Windows Server 2016, see here: https://playwright.dev/python/docs/intro#system-requirements

OK，Thank you.
I got it, I missed the system requirement.

**Comment by mxschmitt** [comment]
Closing by that!
