### ISSUE TITLE
[Feature] A way to control where the browser is installed to and run from

### ISSUE THREAD

**Issue by binoche9** [microsoft/playwright-python#2026]
I'm looking to see if there's a way to control where `playwright install` installs the browsers and where it's run from. If it's not possible, I was wondering if it would be possible to make it possible.

The context here is that I'm trying to run the Python Playwright in Heroku, and `playwright install` is installing it to the `/app/.cache/` directory that gets cleared on every server restart so I have to reinstall the browser on each server restart.

I've looked through the issues here and see mentions of the `PLAYWRIGHT_BROWSERS_PATH` variable, but all the issues mention setting it to `0` which doesn't make much sense to me, and I haven't been able to find documentation for it so I haven't been able to make it work for my use case.

**Comment by mxschmitt** [comment]
setting it to `0` will put it next to your directory where the PIP module is installed. We recommend instead passing a path e.g. `PLAYWRIGHT_BROWSERS_PATH=$HOME/pw-browsers` see [here](https://playwright.dev/python/docs/browsers#managing-browser-binaries).

**Comment by binoche9** [comment]
Can confirm that it works so closing this out. Thanks!

**Comment by binoche9** [comment]
> To which value did you change it?

Unfortunately I haven't figured out that part yet - no matter what I set it to it seems to get wiped out on a restart. But I have confirmed that setting the value does change where the browser gets installed.

I'm still working on finding a path / finding out how to persist the browser installation - other buildpacks do it so I figure there must be a way
