### ISSUE TITLE
Incompatible: playwright and pyinstaller

### ISSUE THREAD

**Issue by MkrV** [microsoft/playwright-python#204]
I tried to compile a few Python scripts, where I use Playwright (0.142.1):
`pyinstaller -F myapp.py`
Pyinstaller (4.0) working correctly with each of my Selenium scripts.
but here each time I'm receiving the same error during execution:
$ ./myapp.exe
```
Traceback (most recent call last):
  File "myapp.py", line 3, in <module>
  File "playwright\__init__.py", line 34, in sync_playwright
  File "playwright\main.py", line 83, in __init__
  File "playwright\main.py", line 78, in run_driver
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "playwright\main.py", line 45, in run_driver_async
  File "playwright\path_utils.py", line 9, in get_file_dirname
AssertionError
[13500] Failed to execute script myapp
```
"myapp.py", line 3:
`playwright = sync_playwright().start() # usual sync / sync REPL`
at async version getting error at:
`asyncio.get_event_loop().run_until_complete(main())`

I tried to comment out
"playwright\path_utils.py", line 9: `# assert module` ,
remove cache from previous compilation, and compile from scratch, but no success.
how to get correct exe file?

how to bundle exe with playwright:
[playwright-python + playwright driver + chromium browser] ?

at PyInstaller autocreated myapp.spec file I changed bool value of "exclude_binaries" param (True >> False),
but still getting the same error.

**Comment by pavelfeldman** [comment]
Could you share more about the way you use those binaries? Pyinstaller needs to be configured to include the underlying driver and browsers.json config file from Playwright module. It is easy to do, but depending on your use case it might make more sense to place the driver in a shared location and point to it. Without sharing, your binaries will include 40Mb driver each...

**Comment by MkrV** [comment]
Scenario: Automate a website and then let the user complete something. 
Usually it's 1-2 scripts with up to 600 lines of code in total.

**Comment by tumregels** [comment]
@MkrV - a solution is proposed at [342](https://github.com/microsoft/playwright-python/issues/342)

**Comment by pavelfeldman** [comment]
Merging into  #342
