### ISSUE TITLE
When pycharm executes the test case, it will occasionally report an error, as shown in the following figure:

### ISSUE THREAD

**Issue by yangbiao93521** [microsoft/playwright-python#2052]
[gw0] FAILED test_contract_renewal_proportion_statistics.py::Test_Renewal_Proportion::test_renewal_proportion_1[data0] 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Users\yangbiao\AppData\Roaming\Python\Python310\site-packages\_pytest\main.py", line 270, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "C:\Users\yangbiao\AppData\Roaming\Python\Python310\site-packages\_pytest\main.py", line 324, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "C:\Users\yangbiao\AppData\Roaming\Python\Python310\site-packages\pluggy\_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "C:\Users\yangbiao\AppData\Roaming\Python\Python310\site-packages\pluggy\_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "C:\Users\yangbiao\AppData\Roaming\Python\Python310\site-packages\pluggy\_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\Users\yangbiao\AppData\Roaming\Python\Python310\site-packages\pluggy\_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Users\yangbiao\AppData\Roaming\Python\Python310\site-packages\pluggy\_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "D:\Python310\Python310\lib\site-packages\xdist\dsession.py", line 117, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "D:\Python310\Python310\lib\site-packages\xdist\dsession.py", line 140, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "D:\Python310\Python310\lib\site-packages\xdist\dsession.py", line 276, in worker_testreport
INTERNALERROR>     self.config.hook.pytest_runtest_logreport(report=rep)
INTERNALERROR>   File "C:\Users\yangbiao\AppData\Roaming\Python\Python310\site-packages\pluggy\_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "C:\Users\yangbiao\AppData\Roaming\Python\Python310\site-packages\pluggy\_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "C:\Users\yangbiao\AppData\Roaming\Python\Python310\site-packages\pluggy\_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\Users\yangbiao\AppData\Roaming\Python\Python310\site-packages\pluggy\_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Users\yangbiao\AppData\Roaming\Python\Python310\site-packages\pluggy\_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "D:\pycharm1\PyCharm 2022.3\plugins\python\helpers\pycharm\teamcity\pytest_plugin.py", line 310, in pytest_runtest_logreport
INTERNALERROR>     self.report_test_failure(test_id, report)
INTERNALERROR>   File "D:\pycharm1\PyCharm 2022.3\plugins\python\helpers\pycharm\teamcity\pytest_plugin.py", line 265, in report_test_failure
INTERNALERROR>     self.teamcity.testFailed(test_id, message, str(report.longrepr), flowId=test_id)
INTERNALERROR>   File "D:\pycharm1\PyCharm 2022.3\plugins\python\helpers\pycharm\_jb_runner_tools.py", line 188, in testFailed
INTERNALERROR>     _old_service_messages.testFailed(self, testName, message, details, comparison_failure=comparison_failure)
INTERNALERROR>   File "D:\pycharm1\PyCharm 2022.3\plugins\python\helpers\pycharm\teamcity\messages.py", line 174, in testFailed
INTERNALERROR>     self.message('testFailed', name=testName, message=message, details=details, flowId=flowId)
INTERNALERROR>   File "D:\pycharm1\PyCharm 2022.3\plugins\python\helpers\pycharm\_jb_runner_tools.py", line 117, in message
INTERNALERROR>     _old_service_messages.message(self, messageName, **properties)
INTERNALERROR>   File "D:\pycharm1\PyCharm 2022.3\plugins\python\helpers\pycharm\teamcity\messages.py", line 101, in message
INTERNALERROR>     retry_on_EAGAIN(self.output.write)(self.encode(message))
INTERNALERROR>   File "D:\pycharm1\PyCharm 2022.3\plugins\python\helpers\pycharm\teamcity\messages.py", line 68, in encode
INTERNALERROR>     value = value.encode(self.encoding)
### INTERNALERROR> UnicodeEncodeError: 'gbk' codec can't encode character '\u21b5' in position 3190: illegal multibyte sequence

======================== 1 failed in 86.61s (0:01:26) =========================

**Comment by yangbiao93521** [comment]
I can see that the error is due to the coding method, but I am not sure how to solve it
Hope to get guidance！

**Comment by mxschmitt** [comment]
Your stacktrace has no Playwright in it, so its unlikely an issue related to Playwright.

I recommend filing it at the PyCharm issue tracker.
