### ISSUE TITLE
[Feature] UI Mode for playwright-python

### ISSUE THREAD

**Issue by kennysong** [microsoft/playwright-python#2055]
Hi, great library! We're wondering if there are any plans to bring [Playwright JS' UI Mode](https://playwright.dev/docs/test-ui-mode) into playwright-python as well?

**Comment by mxschmitt** [comment]
UI Mode is a JavaScript exclusive feature since it is heavily connected to the underlying test-runner, which we in the case for Node.js wrote ourselves (@playwright/python). There are as of today no plans to bring it to Python.
