### ISSUE TITLE
msedge browser not found while using the script

### ISSUE THREAD

**Issue by SivaKumarDodda** [microsoft/playwright-python#2056]
### System info
- Playwright Version: [v1.XX]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Test file (self-contained)**

import pytest
from playwright.sync_api import sync_playwright

# Define the browsers and viewports you want to use
browsers = ["msedge", "firefox", "chromium"]
viewports = [
    {"width": 1024, "height": 768},
    {"width": 1280, "height": 800},
    {"width": 1440, "height": 900},
    {"width": 1920, "height": 1080},
]

# Fixture to set up the Playwright context
@pytest.fixture(scope="function", params=browsers)
def browser_context(request):
    # Initialize Playwright
    with sync_playwright() as p:
        browser_type = getattr(p, request.param)
        browser = browser_type.launch(headless=False)
        context = browser.new_context()
        yield context
        context.close()
        browser.close()

# Fixture to set up different viewports
@pytest.fixture(scope="function", params=viewports)
def set_viewport(request):
    return request.param

**Expected**
msedge browser to be opened
[Describe expected behavior]

**Actual**
test setup failed
request = <SubRequest 'browser_context' for <Function test_example[msedge-set_viewport0]>>

    @pytest.fixture(scope="function", params=browsers)
    def browser_context(request):
        # Initialize Playwright
        with sync_playwright() as p:
>           browser_type = getattr(p, request.param)
E           AttributeError: 'Playwright' object has no attribute 'msedge'

[Describe actual behavior]

**Comment by mxschmitt** [comment]
msedge is no attribute of Playwright which is correct. You can use Edge and Chrome instead when using the chromium browser and passing the channel attribute:

```py
browser = playwright.chromium.launch(
    channel="msedge",
)
```

See [here](https://playwright.dev/python/docs/api/class-browsertype#browser-type-launch-option-channel).

**Comment by SivaKumarDodda** [comment]
Tried this too:
PLEASE SUGGEST THE CODE TO USE MSEDGE IN PLAYWRIGHT WITH PYTHON

from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch(channel="msedge", headless=False)
    context = browser.new_context()

    page = context.new_page()

    page.goto("https://www.google.com/")
    page.wait_for_timeout(4000)

    page.close()
    context.close()

    browser.close()


============================= test session starts =============================
collecting ... 
test_edge.py:None (test_edge.py)
test_edge.py:11: in <module>
    page = context.new_page()
ase_ui_venv\Lib\site-packages\playwright\sync_api\_generated.py:12906: in new_page
    return mapping.from_impl(self._sync(self._impl_obj.new_page()))
ase_ui_venv\Lib\site-packages\playwright\_impl\_browser_context.py:250: in new_page
    return from_channel(await self._channel.send("newPage"))
ase_ui_venv\Lib\site-packages\playwright\_impl\_connection.py:61: in send
    return await self._connection.wrap_api_call(
ase_ui_venv\Lib\site-packages\playwright\_impl\_connection.py:461: in wrap_api_call
    return await cb()
ase_ui_venv\Lib\site-packages\playwright\_impl\_connection.py:96: in inner_send
    result = next(iter(done)).result()
E   playwright._impl._api_types.Error: Browser closed.
E   ==================== Browser output: ====================
E   <launching> C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --no-sandbox --user-data-dir=C:\Users\SIVAKU~1.D\AppData\Local\Temp\playwright_chromiumdev_profile-BXA8U2 --remote-debugging-pipe --no-startup-window
E   <launched> pid=18440
E   [pid=18440][err] [18440:3060:0905/140143.030:ERROR:chrome_browser_cloud_management_controller.cc(163)] Cloud management controller initialization aborted as CBCM is not enabled.
E   [pid=18440][err] [18440:3060:0905/140143.053:ERROR:assistance_home_client.cc(32)] File path C:\Users\SIVAKU~1.D\AppData\Local\Temp\playwright_chromiumdev_profile-BXA8U2\Default
E   [pid=18440][err] [18440:3060:0905/140143.148:ERROR:device_event_log_impl.cc(222)] [14:01:43.147] USB: usb_service_win.cc:415 Could not read device interface GUIDs: The system cannot find the file specified. (0x2)
collected 0 items / 1 error

**Comment by mxschmitt** [comment]
Closing as per above, please re-file with more information. Thanks.
