### ISSUE TITLE
[BUG] Tracing doesn't work and test-result doesn't performed if add  storage_state to browser fixture

### ISSUE THREAD

**Issue by smolkin895** [microsoft/playwright-python#2062]
### System info
- Playwright Version: [v1.37.0]
- Operating System: [ Windows 10]
- Browser: [Chrome]
- Other info:
- --browser-channel chrome  --tracing on 

### Source code

```python
import os

import pytest
from playwright.sync_api import Browser, Page, expect, sync_playwright

from config import Config
from helper.general import auth_path, get_logged_page
from pages.campaigns_edit import CampaignsEdit


@pytest.fixture(scope='function')
def context(browser: Browser, browser_context_args: dict):
    context = browser.new_context(
        storage_state=os.path.join(auth_path, "auth.json"), **browser_context_args
    )
    yield context
    context.close()

@pytest.fixture(scope="function")
def campaigns_edit(page: Page):
    page.set_viewport_size({"width": 1920, "height": 1080})
    page.context.storage_state(path=os.path.join(auth_path, "auth.json"))
    campaigns_edit = CampaignsEdit(page=page)
    yield campaigns_edit
    try:
        if campaigns_edit.name_of_ads:
            campaigns_edit.del_ads()
    except Exception:
        print("РО уже удалено!")
```

**Steps**
Hello everyone. I want to throw authorization into all tests with this fixture. Tracking falls off and test-result is not formed
**Expected**
I have test-result
**Actual**
I haven't test-result
![image](https://github.com/microsoft/playwright/assets/75039804/790f78b3-79a4-44b0-a7cf-c3cdce4b84a4)
[Describe actual behavior]
If you comment out the fixture, then the report works

```[tasklist]
### Tasks
```

**Comment by mxschmitt** [comment]
Closing as per above, please re-file if you have more questions, thanks!

**Comment by smolkin895** [comment]
@mxschmitt I'm sorry, but I need a few contexts. How can I implement this if the scope of browser_context_args is equal to session
