### ISSUE TITLE
[BUG]Using close() does not release memory

### ISSUE THREAD

**Issue by wangzimeiyingtao** [microsoft/playwright-python#2066]
### System info
- Playwright Version: [v1.35]
- Operating System: [Windows 10]
- Browser: [Chromium]
- Other info: For some reason, opening the browser through Selenium

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Test file**

```python
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    # This is not a loop creation in a production environment, just for demonstration.
    # Because it needs to be mixed with Selenium's test script, 
    # keeping the connection open will cause Selenium to not navigate correctly after clicking to open the window.
    for _ in range(100)
        browser = p.chromium.connect_over_cdp("http://localhost:9222")
        # ...
        browser.close()
```

**Steps**
- Open browser
- Run the test

**Expected**
Call `browser.close()` to release memory.
**Actual**
Browser memory usage is increasing.

**Comment by wangzimeiyingtao** [comment]
Chromium process

**Comment by mxschmitt** [comment]
This looks then like a Chromium bug to us, where we recommend filing an issue at crbug.com. Thats outside of the scope of our Project. They prefer pptr reproducibles, so I recommend you to try reproducing in pptr with [pptr.connect](https://pptr.dev/api/puppeteer.puppeteer.connect).
