### ISSUE TITLE
[BUG] VSCode Intellisense not giving suggestions for Playwright

### ISSUE THREAD

**Issue by firozzer** [microsoft/playwright-python#2071]
### System info
- Playwright Version: [v1.37.0]
- Operating System: [Windows 10]
- Browser: [All]
- Other info:

### Source code
```
from playwright.sync_api import sync_playwright

def run(playwright):
    chromium = playwright.chromium # or "firefox" or "webkit".
    browser = chromium.launch(headless=True)
    page = browser.new_page()


with sync_playwright() as playwright:
    run(playwright)
```
- [ YES ] I provided exact source code that allows reproducing the issue locally.

I installed Playwright inside a venv. Now when I try to get suggestions on variables like `browser` or `page` inside VSCode, no suggestions come up. Suggestions only come up for the `playwright` variable.

Can someone please guide what I'm doing wrong here? Thanks.

**Comment by mxschmitt** [comment]
You need to give your function a type hint, otherwise Python does not know which type playwright is inside the run function. Like this:

```python
from playwright.sync_api import sync_playwright, Playwright

def run(playwright: Playwright):
    chromium = playwright.chromium # or "firefox" or "webkit".
    browser = chromium.launch(headless=True)
    page = browser.new_page()


with sync_playwright() as playwright:
    run(playwright)
```

Let me take this as an opportunity to fix our snippets.

**Comment by firozzer** [comment]
Thank you sir, you are a scholar & a genius! Highly appreciate your amazing good work. 🙏
