### ISSUE TITLE
[BUG] Playwright is not installed in image  mcr.microsoft.com/playwright/python:v1.37.0-focal

### ISSUE THREAD

**Issue by mcmasty** [microsoft/playwright-python#2072]
### System info
- Playwright Version: [v1.37.0]
- Operating System: [macOS 13.5.1,]
- Browser: [All]
- Other info:  Docker

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

```
docker run -it mcr.microsoft.com/playwright/python:v1.37.0-focal /bin/bash
```

**Steps**
- Inside the docker image run `pip list` 

**Expected**
`playwright  1.37.0`  should be installed in the image.

**Actual**

No Playwright installed. 

<img width="820" alt="Screenshot 2023-09-13 at 15 27 54" src="https://github.com/microsoft/playwright-python/assets/6108038/3817cd6c-87b5-4fe4-9d9d-c57a132e6eca">

**Comment by mxschmitt** [comment]
This is expected. The playwright docker image only contains the browsers and browser dependencies. It's up to the user to install playwright with his package manager of choice.
