### ISSUE TITLE
Help needed: Keep browser open & attach new pages into it asynchronously

### ISSUE THREAD

**Issue by 411A** [microsoft/playwright-python#2077]
Hi, I'm trying to handle multiple users requests for my scraping projects asynchronously through 3 different Python files, the problem is that when the browser is opened through `file1.py` and another user requests (`file2.py` executes), I don't want to open the browser again & I just need to attach the new page (new request from the user) to the current browser (through memory!?). I don't know if it's possible doing so, `async_playwright` uses context manager and it closes the browser as soon as the code execution ends. I need to keep the browser open for 1 minute after the last page's scraping done, and if no new requests made, close the browser; otherwise attach the new page and scrape it.
I know it may not appear as a feature request, but I didn't find any information on this.

**Comment by mxschmitt** [comment]
You can also use the REPL way of starting a Playwright session, this should make it possible for you to pass the Playwright instance around: https://playwright.dev/python/docs/library#interactive-mode-repl (available for sync and async)
