### ISSUE TITLE
[Feature] Support win32 compatible wheel

### ISSUE THREAD

**Issue by andersonbrands** [microsoft/playwright-python#208]
On Windows 10 (after running `pip install playwright`) `python -m playwright install` raises the error:

> subprocess.CalledProcessError: Command '<path_to_my_venv>\lib\site-packages\playwright\drivers\driver-win.exe install' returned non-zero exit status 1

I verified that **driver-win.exe** doe not exist in **playwright/drivers** folder. Is there any step I'm missing?

I managed to get it working by building the `playwright-0.142.1.tar.gz` from pypi.org, by installing local requirements and running `python build_driver.py` and `python build_package.py` which generated the driver-win.exe file.

Just wondering if that's how it should be done.

**Comment by arjun27** [comment]
Thanks for reporting this, @andersonbrands. `pip install playwright` should install the driver for you. Can you tell us more about your OS? Is this Win 10 64-bit?

**Comment by andersonbrands** [comment]
Hi, please, check system info:
> Manufacturer: Acer
> Model: Nitro AN515-51
> Processor: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz 2.81 GHz
> Installed memory (RAM): 16.0 GB (15.9 GB usable)
> System type: 64-bit Operating System, x64-based processor)

**Comment by pavelfeldman** [comment]
Just a wild guess, maybe there is an antivirus that prevents wheel from extracting .exe ?

**Comment by andersonbrands** [comment]
I have no antivirus installed, just the Windows Security which I disabled Real-time protection to try `pip install playwright` again... still no driver-win.exe file

**Comment by arjun27** [comment]
Thanks for checking @andersonbrands. I tried a few things on my Windows box, and I think I know what's happening. The wheel we ship right now is for win_amd64 which requires both Win 64 bit and a 64 bit installation of Python. When I install Python x86 on Windows, I'm able to repro this issue.

To fix this right now, you could install Python x86-64 on your machine. We are adding wheel support for 32-bit so this does not happen again. Thanks again for reporting this!

**Comment by arjun27** [comment]
Also: to ensure that this is the issue, you can run `pip debug -v`. The list of compatible tags would only show win32 (and not win_amd64)

**Comment by pavelfeldman** [comment]
Should be fixed in 0.142.2!

**Comment by andersonbrands** [comment]
@arjun27, just to confirm... I checked here and `pip debug -v` lists only win32
