### ISSUE TITLE
[Feature] Enhance Handling of x-www-form-urlencoded Data in HTTP Requests

### ISSUE THREAD

**Issue by dron4ik86** [microsoft/playwright-python#2088]
**Current Behavior:**
When making HTTP POST requests with form data using Playwright's request context, the payload data needs to be explicitly URL-encoded using methods like urllib.parse.urlencode. This adds an extra step and can be a point of confusion, especially for users transitioning from libraries like requests in Python which handle this encoding automatically.

**Expected Behavior:**
It would be more intuitive if Playwright could automatically handle the URL-encoding for form data, similar to how the requests library does.

**Example:**
Using `requests`:
```
import requests

payload = {
    "grant_type": "client_credentials",
    "client_id": "example-client-id",
    "client_secret": "example-secret",
    "scope": "example.scope"
}

response = requests.post(url, data=payload)
```

Using Playwright:
```
from playwright.sync_api import sync_playwright
import urllib.parse

payload = {
    "grant_type": "client_credentials",
    "client_id": "example-client-id",
    "client_secret": "example-secret",
    "scope": "example.scope"
}

with sync_playwright() as p:
    response = api_request_context.post(url, data=urllib.parse.urlencode(payload))
```

**Suggestion**:
It would enhance the user experience if Playwright's request context could detect when data should be URL-encoded (based on the Content-Type header, for instance) and handle the encoding automatically.

**Environment**:
Playwright version: 1.38.0
OS: MacOS

**Comment by yury-s** [comment]
It's already supported, you need to pass the data as [`form`](https://playwright.dev/python/docs/api/class-apirequestcontext#api-request-context-get-option-form) parameter instead of `data`.

**Comment by pr-coder-kaya** [comment]
I was also looking to same for .NET. Not sure, how the implementation looks like.
