### ISSUE TITLE
[Feature] launch_persistent_context does not allow setting firefox_user_prefs. Is that by design?

### ISSUE THREAD

**Issue by rprimet** [microsoft/playwright-python#2089]
I have a use case for launching a persistent context (I need caching) with some firefox preferences tweaks (no json rendering -- by default firefox wraps json replies in some html scaffolding and I would like to get the raw json value -- unfortunately using `browser.request.get()` will fail with a server error for some reason while `page.goto()` works). Is that feasible?

**Comment by yury-s** [comment]
This is not supported for _persistent_ context by design. When you are using persistent profile, you already can configure all the preferences there.

**Comment by rprimet** [comment]
Could you expand a little bit? How do you set the configuration for a persistent context? Thanks !

**Comment by yury-s** [comment]
Firefox saves all the settings in the user profile directory that you pass when creating a persistent context. If you change some prefs that will be stored in the profile and loaded on the next run.
