### ISSUE TITLE
[BUG] - Test steps involving a new browser pop up does not get captured in video

### ISSUE THREAD

**Issue by sundar-ds** [microsoft/playwright-python#2092]
### System info
- Playwright Version: 1.37.0
- Operating System: Windows 11
- Browser: Chromium
- Other info:

### Source code

It cannot be reproduced locally. Here's the scrshot of the code which if possible can be tried on other websites

![image](https://github.com/microsoft/playwright-python/assets/146530679/2ebb8237-3132-46ab-8205-8b50ffb58404)

**Expected**
The recorded video after the test closes should have the pop up browser with the actions done on it.

**Actual**
The recorded video does not include the pop up window but only shows the parent window

**Comment by mxschmitt** [comment]
Its expected, that its not contained in the same video, if thats what this issue is about. I tried to reproduce it with this code and it was working for me as expected:

```python
from playwright.sync_api import Page


def test_dx_page(page: Page):
    page.goto("https://example.com")
    page.set_content('<button onclick="window.open(\'/foobar\', \'_blank\')">Click me</button>')
    with page.expect_popup() as popup_info:
        page.click('button')
    popup = popup_info.value
    page.wait_for_timeout(2000)
```

```
pytest --video=on
```

General recommendation, if you are trying to debug your tests, we highly recommend tracing: https://playwright.dev/python/docs/trace-viewer which is a much better way to debug failing tests.

**Comment by sundar-ds** [comment]
Thank you for the response! I realized only now after executing your code that the pop up window will be on a separate video. Is there any way to combine it on the same video?

**Comment by mxschmitt** [comment]
This is unfortunately not possible and working as designed, you can manually merge using e.g. ffmpeg. Closing for now, we recommend [Tracing](https://playwright.dev/python/docs/trace-viewer-intro) for debugging.

**Comment by mxschmitt** [comment]
1.
