### ISSUE TITLE
[BUG]Cannot locate element through 'frame.locator'

### ISSUE THREAD

**Issue by lixijia** [microsoft/playwright-python#2093]
### System info
- Playwright Version: V1.38.0
- Operating System: Windows 11
- Browser: Chromium
- Other info:

### Source code
        frame2=page.frame(name="ifrm",url=frame_url)
        frame2.wait_for_load_state("networkidle")
        print(frame2.locator("div[role='alert']").inner_text())
        print(page.frame_locator("iframe[name=\"ifrm\"] >> nth=1").locator("div[role='alert']").
              inner_text())

### Summary
use:  print(frame2.locator("div[role='alert']").inner_text()) 
cannot print the right text.
================
E       playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
E       =========================== logs ===========================
E       waiting for locator("div[role='alert']")
E       ============================================================
================
but
frame2.wait_for_load_state("networkidle") 
it can works
and
use:  print(page.frame_locator("iframe[name=\"ifrm\"] >> nth=1").locator("div[role='alert']").inner_text())
can print the right text.

**Comment by mxschmitt** [comment]
We recommend [codegen](https://playwright.dev/python/docs/codegen-intro to generate selectors and [web-first assertions](https://playwright.dev/python/docs/test-assertions) to assert elements.

Can you share reproduction steps?

**Comment by mxschmitt** [comment]
Closing as per above. Please re-file with more details, thanks!
