### ISSUE TITLE
I'm trying to extract data in one of site when i open it in local browser it shows access denied

### ISSUE THREAD

**Issue by ramprakashyadav** [microsoft/playwright-python#2095]
### System info
- Playwright Version: [v1.XX]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Test file (self-contained)**

```python
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()
    # ...
    browser.close()
```

**Steps**
- [Run the test]
- [...]

**Expected**

[Describe expected behavior]

**Actual**

[Describe actual behavior]

**Comment by mxschmitt** [comment]
This is most likely caused by a WAF / bot protection. We cannot act on this, since we expect users to test sites they own.
