### ISSUE TITLE
[BUG] No module named greenlet._greenlet using python 3.11.5 on Docker

### ISSUE THREAD

**Issue by mathew-jithin** [microsoft/playwright-python#2098]
### System info
- Playwright Version: 1.38.0
- Operating System: Ubuntu
- Browser: NA
- Other info: Official Python Docker Image 3.11.5

Lambda function throwing the following error inside the container. Deployed using serverless. Issue is due to playwright, as no other modules that I use, uses greenlet:

[ERROR] Runtime.ImportModuleError: Unable to import module <lambda_function_file_name>: No module named 'greenlet._greenlet'Traceback (most recent call last):

Best part is, in my macbook on latest MacOS, this works fine. So feels like this in an OS specific issue. I tried with multiple Playwright versions (after 1.28) and issue seems to exist everywhere.

**Comment by mathew-jithin** [comment]
I think there is a fix that was tried for this in greenlet. Will playwright be updating greenlet to 3.0.0 soon?

Ref: https://github.com/python-greenlet/greenlet/issues/346

**Comment by mxschmitt** [comment]
Looks not like a Playwright issue and more like a greenlet issue caused by the environment to me. Yes, we'll upgrade to v3 soon as part of https://github.com/microsoft/playwright-python/issues/2096. Folding into it by that.

**Comment by mathew-jithin** [comment]
@mxschmitt 

Is there any workaround for this issue till the release is done?
