### ISSUE TITLE
[BUG] Webkit PWDEBUG and headed modes impossible due to browser page closing immediately after launch

### ISSUE THREAD

**Issue by RomanLeca** [microsoft/playwright-python#2106]
### System info
- Playwright Version: [**v1.38**]
- Operating System: [macOS 13.5.2]
- Browser: [**WebKit**]
- Other info: Mac M1

I'm running playwright tests on a pytest framework and after the update to 1.38 I have a lot of flakiness on CICD. When trying to debug locally or run in headed mode, webkit opens the browser page and closes it immediately after the first action in the script.
I can reproduce this even on a brand new project with minimum required libraries, both with pip and poetry. 

Nothing is generated in the console. After page crash, the test **doesn't stop but hangs instead**. I have to keyboard kill it manually.

I had to roll back to **1.37**. 

Can you please advise?

**Comment by mxschmitt** [comment]
Can you provide us a (minimal) reproducible which surfaces the unexpected behaviour?

**Comment by RomanLeca** [comment]
I retried a clean setup and it worked. 
It seems there is a problem somewhere in my project. Closing.
