### ISSUE TITLE
Can't install on macOS 11.0 Beta (Big Sur)

### ISSUE THREAD

**Issue by imWildCat** [microsoft/playwright-python#211]
```bash
$ python3 -m playwright install

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/site-packages/playwright/__main__.py", line 17, in <module>
    main()
  File "/usr/local/lib/python3.8/site-packages/playwright/main.py", line 145, in main
    st = os.stat(driver_executable)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/site-packages/playwright/drivers/driver-darwin'
```

System information:

- Python: `Python 3.8.5`
- System: `macOS 11.0 Beta (20A5374i)`

**Comment by pavelfeldman** [comment]
We need to tag our binary as compatible with Big Sur, should be doable.

**Comment by imWildCat** [comment]
Great, thanks!

**Comment by mxschmitt** [comment]
Blocked by upstream change which is required: https://github.com/microsoft/playwright/issues/2789

**Comment by HeikKerimov** [comment]
Couldn't install playwright.  MacOS Catalina. @pavelfeldman @mxschmitt 


`(venv) heyk@MacBook-Pro-Heyk cloud-api-server % pip install playwright
Collecting playwright
  Using cached playwright-0.150.0-py3-none-macosx_10_13_x86_64.whl (57.9 MB)
Requirement already satisfied: pyee>=8.0.1 in ./venv/lib/python3.8/site-packages (from playwright) (8.1.0)
Requirement already satisfied: typing-extensions in ./venv/lib/python3.8/site-packages (from playwright) (3.7.4.3)
Collecting greenlet>=0.4.17
  Using cached greenlet-0.4.17.tar.gz (61 kB)
Using legacy 'setup.py install' for greenlet, since package 'wheel' is not installed.
Installing collected packages: greenlet, playwright
    Running setup.py install for greenlet ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/heyk/PycharmProjects/cloud-api-server/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/w_/x_q97_j92qn830gy0f43_97m0000gn/T/pip-install-p57lj7h6/greenlet/setup.py'"'"'; __file__='"'"'/private/var/folders/w_/x_q97_j92qn830gy0f43_97m0000gn/T/pip-install-p57lj7h6/greenlet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/w_/x_q97_j92qn830gy0f43_97m0000gn/T/pip-record-e27c1p10/install-record.txt --single-version-externally-managed --compile --install-headers /Users/heyk/PycharmProjects/cloud-api-server/venv/include/site/python3.8/greenlet
         cwd: /private/var/folders/w_/x_q97_j92qn830gy0f43_97m0000gn/T/pip-install-p57lj7h6/greenlet/
    Complete output (112 lines):
    running install
    running build
    running build_ext
    building 'greenlet' extension
    creating build
    creating build/temp.macosx-10.14.6-x86_64-3.8
    xcrun -sdk macosx clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -I/Users/heyk/PycharmProjects/cloud-api-server/venv/include -I/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c greenlet.c -o build/temp.macosx-10.14.6-x86_64-3.8/greenlet.o
    In file included from greenlet.c:5:
    In file included from ./greenlet.h:8:
    In file included from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/Python.h:11:
    In file included from /Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include/limits.h:21:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/limits.h:63:
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:807:2: error: Unsupported architecture
    #error Unsupported architecture
     ^
    In file included from greenlet.c:5:
    In file included from ./greenlet.h:8:
    In file included from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/Python.h:11:
    In file included from /Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include/limits.h:21:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/limits.h:64:
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/machine/limits.h:8:2: error: architecture not supported
    #error architecture not supported
     ^
    In file included from greenlet.c:5:
    In file included from ./greenlet.h:8:
    In file included from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/Python.h:25:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:64:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_stdio.h:71:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_types.h:27:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:33:
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/machine/_types.h:34:2: error: architecture not supported
    #error architecture not supported
     ^
    In file included from greenlet.c:5:
    In file included from ./greenlet.h:8:
    In file included from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/Python.h:25:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:64:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_stdio.h:71:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_types.h:27:
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:55:9: error: unknown type name '__int64_t'
    typedef __int64_t       __darwin_blkcnt_t;      /* total blocks */
            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:56:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
    typedef __int32_t       __darwin_blksize_t;     /* preferred block size */
            ^
    note: '__int128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:57:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
    typedef __int32_t       __darwin_dev_t;         /* dev_t */
            ^
    note: '__int128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:60:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
    typedef __uint32_t      __darwin_gid_t;         /* [???] process and group IDs */
            ^
    note: '__uint128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:61:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
    typedef __uint32_t      __darwin_id_t;          /* [XSI] pid_t, uid_t, or gid_t*/
            ^
    note: '__uint128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:62:9: error: unknown type name '__uint64_t'
    typedef __uint64_t      __darwin_ino64_t;       /* [???] Used for 64 bit inodes */
            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:68:9: error: unknown type name '__darwin_natural_t'
    typedef __darwin_natural_t __darwin_mach_port_name_t; /* Used by mach */
            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:70:9: error: unknown type name '__uint16_t'; did you mean '__uint128_t'?
    typedef __uint16_t      __darwin_mode_t;        /* [???] Some file attributes */
            ^
    note: '__uint128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:71:9: error: unknown type name '__int64_t'
    typedef __int64_t       __darwin_off_t;         /* [???] Used for file sizes */
            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:72:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
    typedef __int32_t       __darwin_pid_t;         /* [???] process and group IDs */
            ^
    note: '__int128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:73:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
    typedef __uint32_t      __darwin_sigset_t;      /* [???] signal set */
            ^
    note: '__uint128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:74:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
    typedef __int32_t       __darwin_suseconds_t;   /* [???] microseconds */
            ^
    note: '__int128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:75:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
    typedef __uint32_t      __darwin_uid_t;         /* [???] user IDs */
            ^
    note: '__uint128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:76:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
    typedef __uint32_t      __darwin_useconds_t;    /* [???] microseconds */
            ^
    note: '__uint128_t' declared here
    In file included from greenlet.c:5:
    In file included from ./greenlet.h:8:
    In file included from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/Python.h:25:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:64:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_stdio.h:71:
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_types.h:43:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
    typedef __uint32_t      __darwin_wctype_t;
            ^
    note: '__uint128_t' declared here
    In file included from greenlet.c:5:
    In file included from ./greenlet.h:8:
    In file included from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/Python.h:25:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:64:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_stdio.h:75:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types/_va_list.h:31:
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/machine/types.h:37:2: error: architecture not supported
    #error architecture not supported
     ^
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    20 errors generated.
    error: command 'xcrun' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/heyk/PycharmProjects/cloud-api-server/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/w_/x_q97_j92qn830gy0f43_97m0000gn/T/pip-install-p57lj7h6/greenlet/setup.py'"'"'; __file__='"'"'/private/var/folders/w_/x_q97_j92qn830gy0f43_97m0000gn/T/pip-install-p57lj7h6/greenlet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/w_/x_q97_j92qn830gy0f43_97m0000gn/T/pip-record-e27c1p10/install-record.txt --single-version-externally-managed --compile --install-headers /Users/heyk/PycharmProjects/cloud-api-server/venv/include/site/python3.8/greenlet Check the logs for full command output.
`

**Comment by imWildCat** [comment]
Hi @mxschmitt, https://github.com/microsoft/playwright/pull/4149 has been merged. Can we move on?

**Comment by pavelfeldman** [comment]
Latest Playwright v0.162.1 should work for you.

**Comment by imWildCat** [comment]
Hi @pavelfeldman, I tested it on my Big Sur laptop, but it does not work:
```
Using legacy setup.py install for playwright, since package 'wheel' is not installed.
```

```zsh
(venv) ➜  pwright-demo pip3 install -U playwright
Collecting playwright
  Using cached playwright-0.162.1.tar.gz (413 kB)
Processing /Users/[big_sur_user]/Library/Caches/pip/wheels/8b/b2/a0/90e194b9006a050b5f342dccea2082b753410a8c3d509c2843/greenlet-0.4.17-cp38-cp38-macosx_11_0_x86_64.whl
Collecting pyee>=8.0.1
  Using cached pyee-8.1.0-py2.py3-none-any.whl (12 kB)
Collecting typing-extensions
  Using cached typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Using legacy setup.py install for playwright, since package 'wheel' is not installed.
Installing collected packages: greenlet, pyee, typing-extensions, playwright
    Running setup.py install for playwright ... done
Successfully installed greenlet-0.4.17 playwright-0.162.1 pyee-8.1.0 typing-extensions-3.7.4.3
WARNING: You are using pip version 20.1.1; however, version 20.2.4 is available.
You should consider upgrading via the '/Users/[big_sur_user]/Downloads/202011/temp/pwright-demo/venv/bin/python3.8 -m pip install --upgrade pip' command.
(venv) ➜  pwright-demo python3.8 -m venv ./venv
(venv) ➜  pwright-demo python -m playwright install

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/[big_sur_user]/Downloads/202011/temp/pwright-demo/venv/lib/python3.8/site-packages/playwright/__main__.py", line 17, in <module>
    main()
  File "/Users/[big_sur_user]/Downloads/202011/temp/pwright-demo/venv/lib/python3.8/site-packages/playwright/main.py", line 135, in main
    subprocess.run([str(driver_executable), *sys.argv[1:]], env=my_env)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/[big_sur_user]/Downloads/202011/temp/pwright-demo/venv/lib/python3.8/site-packages/playwright/driver/playwright-cli'
(venv) ➜  pwright-demo

```

On Catalina, it works
```zsh
(venv) ➜  playwright-demo pip install -U playwright
Collecting playwright
  Downloading playwright-0.162.1-py3-none-macosx_10_13_x86_64.whl (58.2 MB)
     |████████████████████████████████| 58.2 MB 8.3 MB/s
Collecting pyee>=8.0.1
  Downloading pyee-8.1.0-py2.py3-none-any.whl (12 kB)
Collecting greenlet>=0.4.17
  Downloading greenlet-0.4.17.tar.gz (61 kB)
     |████████████████████████████████| 61 kB 7.8 MB/s
Collecting typing-extensions
  Using cached typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Building wheels for collected packages: greenlet
  Building wheel for greenlet (setup.py) ... done
  Created wheel for greenlet: filename=greenlet-0.4.17-cp38-cp38-macosx_10_15_x86_64.whl size=17654 sha256=7f177f0c5bc37b4a28932c29a54adae7cb00a5a7f9f1db7cf6c0d879b458bb5d
  Stored in directory: /Users/[catalina_user]/Library/Caches/pip/wheels/8b/b2/a0/90e194b9006a050b5f342dccea2082b753410a8c3d509c2843
Successfully built greenlet
Installing collected packages: pyee, greenlet, typing-extensions, playwright
Successfully installed greenlet-0.4.17 playwright-0.162.1 pyee-8.1.0 typing-extensions-3.7.4.3
(venv) ➜  playwright-demo python -m playwright install
Downloading chromium v827102 - 121.3 Mb [====================] 100% 0.0s
chromium v827102 downloaded to /Users/[catalina_user]/Library/Caches/ms-playwright/chromium-827102
Downloading firefox v1205 - 74.1 Mb [====================] 100% 0.0s
firefox v1205 downloaded to /Users/[catalina_user]/Library/Caches/ms-playwright/firefox-1205
Downloading webkit v1383 - 49.8 Mb [====================] 100% 0.0s
webkit v1383 downloaded to /Users/[catalina_user]/Library/Caches/ms-playwright/webkit-1383
(venv) ➜  playwright-demo
```

**Comment by Denbox** [comment]
Sorry, I know this has been closed but I'm still getting the same error - just on a different ARM device. (raspberry pi 4)

```
pip3 install -U playwright
Requirement already up-to-date: playwright in /home/ubuntu/.local/lib/python3.9/site-packages (0.162.2)
```

```
python3 -m playwright install
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/playwright/__main__.py", line 17, in <module>
    main()
  File "/home/ubuntu/.local/lib/python3.9/site-packages/playwright/main.py", line 135, in main
    subprocess.run([str(driver_executable), *sys.argv[1:]], env=my_env)
  File "/usr/lib/python3.9/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/.local/lib/python3.9/site-packages/playwright/driver/playwright-cli'```

**Comment by mxschmitt** [comment]
> Sorry, I know this has been closed but I'm still getting the same error - just on a different ARM device. (raspberry pi 4)
> 
> ```
> pip3 install -U playwright
> Requirement already up-to-date: playwright in /home/ubuntu/.local/lib/python3.9/site-packages (0.162.2)
> ```
> 
> ```
> python3 -m playwright install
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/home/ubuntu/.local/lib/python3.9/site-packages/playwright/__main__.py", line 17, in <module>
>     main()
>   File "/home/ubuntu/.local/lib/python3.9/site-packages/playwright/main.py", line 135, in main
>     subprocess.run([str(driver_executable), *sys.argv[1:]], env=my_env)
>   File "/usr/lib/python3.9/subprocess.py", line 501, in run
>     with Popen(*popenargs, **kwargs) as process:
>   File "/usr/lib/python3.9/subprocess.py", line 947, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/usr/lib/python3.9/subprocess.py", line 1819, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/.local/lib/python3.9/site-packages/playwright/driver/playwright-cli'```

Hi, Raspberry PIs are not yet supported.

**Comment by Denbox** [comment]
Thanks for the response - if possible, can you point to a place in the source where I may try to add this support?

**Comment by mxschmitt** [comment]
Probably good to upvote that https://github.com/microsoft/playwright/issues/4984 otherwise hard to self implement it since it need to compile browsers, which take a few hours and store them onto a CDN.
