### ISSUE TITLE
[BUG] - Playwright doesn't wait for the page to be fully loaded

### ISSUE THREAD

**Issue by sundar-ds** [microsoft/playwright-python#2114]
### System info
Playwright Version: 1.37.0
Operating System: Windows 11
Browser: Chromium
Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.
Below is the scrshot of the code. It basically signs in, navigates to the page where the user can punch in and submits. 

![image](https://github.com/microsoft/playwright-python/assets/146530679/6fbfec87-1b3a-4960-8074-704c797bf475)

Issue happens right before clicking on the clock in button. The current time of the system should be loaded before the clock in button gets clicked. However, the 'Clock In' button gets clicked right after entering the page before the time gets loaded because of which it results in an java nullpointer error. I have tried to add slow motion,  'page.wait_for_timeout()' as well as 'time.sleep()' but with no success.

![image](https://github.com/microsoft/playwright-python/assets/146530679/0f6e0022-0c98-4f47-9202-08cf56b7d23d)

When I try to debug putting a breakpoint at the clock-in button, the time gets loaded. However, I don't think it realizes the wait added because of which the button gets clicked right away. 

**Expected**

The current time should be successfully loaded in the application before the clock in button is clicked.

**Actual**

The clock in button gets clicked immediately after the page is loaded. Slowmotion, page.wait and time.sleep do not help.

**Comment by mxschmitt** [comment]
It's technically not possible to wait until a page is fully loaded, we wait until the load event got dispatched, but pages might load more stuff via XHR/Fetch, etc. This is outside of our control.

You should also never use `time.sleep` as per [here](https://playwright.dev/python/docs/library#timesleep-leads-to-outdated-state). Either use wait_for_timeout or don't use these at all. click / assertions will always wait until the element is on the page / clickable etc.

Can you provide us a script which we can run locally?

**Comment by mxschmitt** [comment]
Closing as per above. Please re-file for further questions, since we don't monitor closed issues, thanks!

**Comment by sundar-ds** [comment]
Sorry, I missed to update! I was able to resolve this issue by using the delay option during the click. By the time the click finished, the time got loaded and it went through fine.
