### ISSUE TITLE
[BUG] Chromium headless does not render images

### ISSUE THREAD

**Issue by nefrob** [microsoft/playwright-python#2120]
### System info
- Playwright Version: v1.38.0
- Operating System: macOS 13.5.2, also via docker using `debian:bookworm-slim`
- Browser: Chromium
- Other info: pytest-playwright `0.4.2`

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

Tried both with and without the below code in `conftest.py` (per docs https://playwright.dev/python/docs/chrome-extensions#testing):
```python
from __future__ import annotations

from collections.abc import Generator

import playwright
import pytest
from playwright.sync_api import BrowserContext


@pytest.fixture()
def context(playwright: playwright.Playwright) -> Generator[BrowserContext, None, None]:
    context = playwright.chromium.launch_persistent_context(
        "", headless=False, args=["--headless=new"]
    )
    yield context
    context.close()
```

The test attempting to check the size of an image on the page:
```python
def test_image_bounding_box_headless(page: Page):
    # navigate to desired page and login
    ...

    # debugging waits to make sure everything should have loaded
    page.wait_for_load_state("networkidle")
    page.wait_for_timeout(5000)
  
    # grab the image to validate the size of
    logo = page.get_by_test_id("logo-image")
    assert logo.is_visible()
    assert logo.get_attribute("title") == "Automation logo"
    assert round(logo.bounding_box()["width"]) == 75 # FAIL!
```

**Steps**
- Run the test in headless mode via pytest, i.e. `pytest tests/test_image.py::test_image_bounding_box_headless --video retain-on-failure --screenshot only-on-failure --browser chromium`

**Expected**
- When run in headed mode via Chromium the image loads and the bounding box check succeeds
<img width="157" alt="Screenshot 2023-10-16 at 11 46 08 AM" src="https://github.com/microsoft/playwright-python/assets/25070989/78980750-277a-4e23-8265-7108246d186d">

**Actual**

- When run in headless default or headless=new mode via Chromum the image fails to load, instead the alt text plus empty image is shown. As a consequence, the bounding box check fails
<img width="204" alt="Screenshot 2023-10-16 at 11 38 52 AM" src="https://github.com/microsoft/playwright-python/assets/25070989/a0968c4f-91bc-4efd-b9fc-f682967c5b05">

Additional notes:
- When run in headed mode via Chromium the image loads and the test passes
- When run in headed or headless mode via Firefox the test passes. I am not sure if this means there is some Chromium config causing this to fail or something else
- On failure using the `context` fixture  no screenshot or video is saved despite use of the retain on failure test flags

**Comment by mxschmitt** [comment]
Most likely the website which you are testing is blocking the requests, then they fail and the browser will show the `alt` text. The reason why they are getting blocked is most likely around bot protection, might be based on the user agent (pure guessing), so I'd try to change it to a different value. If this does not work, I'd try to use Playwright's request/response API or Tracing to find out more details about each of the individual image requests and their response.

Using a different User Agent would look like this:

```py
    context = playwright.chromium.launch_persistent_context(
        "", headless=False, args=["--headless=new"],
       user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.6045.21 Safari/537.36"
    )
```

Note: You most likely only need to set this User Agent for Chromium. Make sure to not set it for Firefox or WebKit.
