### ISSUE TITLE
[BUG] 1.39.0 is not on pypi

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright-python#2121]
### System info
n/a

### Source code
n/a

**Steps**
n/a

**Expected**
1.39.0 should be on pypi

**Actual**
1.39.0 was released 5 hours ago: https://github.com/microsoft/playwright-python/releases/tag/v1.39.0

but it does not seem to be on pypi: https://pypi.org/project/playwright/

![image](https://github.com/microsoft/playwright-python/assets/57028336/94d6fa7c-fc0e-4337-8003-ab5912b2ceca)

**Comment by mxschmitt** [comment]
Thanks for filing it, we are actively looking into it.

**Comment by mxschmitt** [comment]
This is fixed now: https://pypi.org/project/playwright/
