### ISSUE TITLE
[Feature] custom expect matchers

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright-python#2126]
playwright 1.39.0 added custom expect matchers for node: https://playwright.dev/docs/test-configuration#add-custom-matchers-using-expectextend

it would be nice if this functionality was also available in python

**Comment by mxschmitt** [comment]
Why does a normal `assert` not work for you or moving custom assertions out into custom functions?

See also [here](https://docs.pytest.org/en/7.1.x/example/simple.html#writing-well-integrated-assertion-helpers) about having good error messages reported.

See also [here](https://docs.pytest.org/en/latest/how-to/assert.html) about assertions in Pytest.

**Comment by DetachHead** [comment]
@mxschmitt `assert` statements don't wait for a timeout until the condition is true unlike playwright assertions

**Comment by mxschmitt** [comment]
Playwright custom expect matchers also don’t, they are just functions and have no retries etc. implemented out of the box.

**Comment by DetachHead** [comment]
fair enugh, i guess there wouldn't be much of a benefit porting them to python then when pytest assertions exist
