### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dafogary** [microsoft/playwright-python#2128]
### System info
- Playwright Version: [v1.39.0]
- Operating System: [Ubuntu 22]
- Browser: [All, Chromium]
- Other info:

### Source code

**Test file (self-contained)**

```python
import re
from playwright.sync import sync_playwright

# Specify your source and output directories
source_directory = '/var/www/html/archives/cheekyfactor/html/cheekyfactor.external'
output_directory = '/var/www/html/archives/cheekyfactor/pdfprint_tmp/external'

# Initialize Playwright
with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()

    for file_name in os.listdir(source_directory):
        if file_name.endswith('.html'):
            file_path = os.path.join(source_directory, file_name)
            output_path = os.path.join(output_directory, file_name.replace('.html', '.pdf'))

            # Load the HTML file
            page.goto(f'file://{file_path}')

            # Generate a PDF from the HTML
            page.pdf(path=output_path, format='A4')
            print(f'Converted {file_name} to PDF.')

    browser.close()
```

**Steps**
- [python3 web2pdfExternal.py] 
- [...]

**Expected**

I would expect it to run and convert all the HTML files in the given directory to PDF in the specified directory.

**Actual**

I get the error

Traceback (most recent call last):
  File "/var/www/html/archives/shellscripts/CheekyArchive/web2pdfExternal.py", line 2, in <module>
    from playwright.sync import sync_playwright
ModuleNotFoundError: No module named 'playwright.sync'

I have noticed others report the same issue, but no resolution found.

I am able to get the help page

$ python3 -m playwright --help
Usage: playwright [options] [command]

Options:
  -V, --version                          output the version number
  -h, --help                             display help for command

Commands:
  open [options] [url]                   open page in browser specified via -b, --browser
  codegen [options] [url]                open page and generate code for user actions
  install [options] [browser...]         ensure browsers necessary for this version of Playwright are installed
  uninstall [options]                    Removes browsers used by this installation of Playwright from the system (chromium, firefox, webkit, ffmpeg). This does not include branded channels.
  install-deps [options] [browser...]    install dependencies necessary to run browsers (will ask for sudo permissions)
  cr [options] [url]                     open page in Chromium
  ff [options] [url]                     open page in Firefox
  wk [options] [url]                     open page in WebKit
  screenshot [options] <url> <filename>  capture a page screenshot
  pdf [options] <url> <filename>         save page as pdf
  show-trace [options] [trace...]        show trace viewer
  test                                   Run tests with Playwright Test. Available in @playwright/test package.
  show-report                            Show Playwright Test HTML report. Available in @playwright/test package.
  merge-reports                          Merge Playwright Test Blob reports Available in @playwright/test package.
  help [command]

**Comment by mxschmitt** [comment]
Your code looks like its LLM generated, which often produce errors like this (wrong import is used). We recommend sticking with official documentation: https://playwright.dev/python/docs/library

https://playwright.dev/python/docs/api/class-playwright

Please re-file for any more specific questions, thanks!
