### ISSUE TITLE
[BUG] Intermittent navigation Error: net::ERR_ABORTED in Playwright

### ISSUE THREAD

**Issue by mathew-jithin** [microsoft/playwright-python#2131]
Hi Guys,

I've been using Playwright for Python, and it's been a great tool. I am reaching out because I've encountered a sporadic issue while using Playwright for Python. When attempting to navigate to a specific URL, **_intermittently_**, the process unexpectedly aborts, throwing a `net::ERR_ABORTED` error. Interestingly, this error surfaces before the "goto" operation can be completed.

This issue has been consistent across multiple versions, from 1.37 to the latest 1.39. It's unclear if this issue has been present for a longer duration.

The issue remains unresolved despite thorough code reviews and various attempts at error handling. For your information, I am using the **default Playwright Docker image, Chromium Headless, launch_persistent_context along with user_data_dir, viewport={'width': 1366, 'height': 768} and java_script_enabled=True**

PW Logs:
```
2023-10-22T18:27:30.261Z pw:api   scrolling into view if needed
2023-10-22T18:27:30.261Z pw:api   done scrolling
2023-10-22T18:27:30.262Z pw:api   performing click action
2023-10-22T18:27:30.270Z pw:api   click action done
2023-10-22T18:27:30.270Z pw:api   waiting for scheduled navigations to finish
2023-10-22T18:27:30.270Z pw:api   navigations have finished
2023-10-22T18:27:30.272Z pw:api   not waiting, "load" event already fired
2023-10-22T18:27:30.281Z pw:api navigating to "[MASKED_URL]", waiting until "load"
```

Logs:
```
2023-10-22 23:57:30,273 [INFO] __main__: Trying to navigate to the given URL: <URL>
2023-10-22 23:57:30,598 [ERROR] __main__: Error while navigating to the given URL: <URL> : net::ERR_ABORTED at <URL>
=========================== logs ===========================
navigating to "<URL>", waiting until "load"
============================================================
Traceback (most recent call last):
  File "<directory_path>", line 349, in _navigate_to_url
    await self._page.goto(url=url, timeout=NavigationTimeouts.LONG.value)
  File "<directory_path>", line 9251, in goto
    await self._impl_obj.goto(
  File "<directory_path>", line 473, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<directory_path>", line 138, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "<directory_path>", line 61, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<directory_path>", line 490, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "<directory_path>", line 99, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._api_types.Error: net::ERR_ABORTED at <URL>
```

Here are the Chrome options I am currently using:
```
['--no-sandbox',
 '--disable-gpu',
 '--disable-dev-shm-usage',
 '--disable-infobars',
 '--disable-notifications',
 '--disable-extensions',
 '--single-process',
 '--enable-automation',
 '--disable-session-crashed-bubble',
]
```

The `--single-process` option is included because the code is executed in **AWS Lambda**, which seems to fail without it. **But issue persists even when I am running this from my local.**

Any assistance or guidance on this issue would be greatly appreciated. Thank you in advance for your time and help!

### System info
- Playwright Version: v1.39
- Operating System: Default Playwright Docker Container - v1.39 on AWS Lambda
- Browser: Chromium Headless
- Other info: -

**Comment by mxschmitt** [comment]
Would it be possible to share a repro with us? Otherwise we are unfortunately not able to act on this.

**Comment by MentalGear** [comment]
I had a similar issue trying to run tests in serial mode, and turned out the custom fixture was closing context prematurely.

**Comment by Pipul-Pant** [comment]
how did you fix this @MentalGear

**Comment by MentalGear** [comment]
Not sure any more what project it was, but if you use custom fixtures, try searching there.

**Comment by emokimet** [comment]
Have you fixed the bug?

**Comment by Gennadiii** [comment]
Also have this issue. Just opening url first thing in a test. The url is under nda so can't provide it

**Comment by chinchang** [comment]
facing the same issue

**Comment by davisaints** [comment]
facing the same issue
