### ISSUE TITLE
[BUG] AsyncEventContextManager cannot early exit through return or exception

### ISSUE THREAD

**Issue by Yomguithereal** [microsoft/playwright-python#2132]
### System info
- Playwright Version: [v1.35.0]
- Operating System: [Ubuntu 22]
- Browser: [All]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```python
import asyncio
from playwright.async_api import async_playwright, Page


async def expect_whatever(page: Page):
    async with page.expect_response("/will-never-happen") as response_info:
        # NOTE: this will raise a TimeoutError
        await page.get_by_text("IDONTEXIST").click(timeout=10)
        # NOTE: an early return in the context manager will not work either


async def main():
    async with async_playwright() as playwright:
        async with await playwright.chromium.launch(headless=True) as browser:
            async with await browser.new_page() as page:
                await page.goto("https://www.lemonde.fr")
                print("We are on page")
                await expect_whatever(page)
                print("Exception will never be raised")


asyncio.run(main())

```

**Steps**
- [Run the test]
- [...]

**Expected**

The exception is raised, the context manager early exits and stop blocking for something that will never happen.

**Actual**

The program hangs because the `__aexit__` of the context manager awaits the result of the event, which will never happen.

The issue is the same in case of early return within the context manager. In case of an error I think `playwright` can handle it better. In case of early return, I am not sure we can understand whether we should stop waiting or not.

Sure, you can use some conservative timeouts but it feels like race-conditionny ducktape.

The wider question is basically how do you break out of a waiter.

**Comment by mxschmitt** [comment]
Sounds like a bug. (will assign it for the next release to look into it. If you are interested in looking into it, let us know!)

**Comment by Yomguithereal** [comment]
It feels like a bug, but it might be more of a design issue. What I mean is that if the wrapped code in the context manager raises or early returns, hence not executing the necessary actions that could trigger the waited event this will result in a deadlock. What I am doing here is basically sniffing some response that may arise if some button exists and can be clicked. It might not be here and trigger a timeout, which is fine, but doing so I have the guarantee the waited event will **never** arrive.

The deadlock occurs here: https://github.com/microsoft/playwright-python/blob/main/playwright/_impl/_async_base.py#L53 because we are awaiting the event to happen even if some exception was raised. I am not sure I can look very efficiently into the problem because I do not know how you would unbind the event listener from here in case an exception was raised. And it does not solve the early return problem. This is why I feel there is fuzzy limit between bug and design/docs here.

To circumvent the problem on my end I have helper functions relying on an `asyncio.Event` and I bind/unbind the listeners on my own when the action raises etc. but I am not sure either this is the way to go.

**Comment by Yomguithereal** [comment]
Here is a variant of helper I use to mitigate the issue on my end:

```python
async def try_expect_response(
    page: Page,
    action: Callable[[], Awaitable[None]],
    response_predicate: Callable[[Response], bool],
) -> Response:
    selected_response = None
    event = asyncio.Event()

    def release() -> None:
        page.remove_listener("response", listener)
        event.set()

    def listener(response: Response) -> None:
        nonlocal selected_response

        if not response_predicate(response):
            return

        selected_response = response

        release()

    async def guarded_action() -> None:
        try:
            await action()
        except Exception:
            release()
            raise

    page.on("response", listener)

    await asyncio.gather(guarded_action(), event.wait())

    assert selected_response is not None

    return selected_response
```
