### ISSUE TITLE
[BUG] Playwright gets stuck on `playwright.stop()` forever.

### ISSUE THREAD

**Issue by fabioz** [microsoft/playwright-python#2135]
Hello, I've a use case where calling `playwright.stop()` blocks forever.

Note that this error is non-deterministic (so, it doesn't always happen, but happens with a high frequency in the related use case -- maybe around 50% of the cases).

Although I can't share the full code, the playwright usage is something as:

```
pw = sync_playwright().start()
... # Create browser and interact with it / close it
pw.stop()  # <-- this will block forever.
```

I've done some tests here and the `chrome` subprocess is properly stopped when `pw.stop()` is called (so, the process no longer has any active subprocesses when it gets stuck, so, the connection is properly closed), but after closing it it just gets stuck.

The thread dump below shows that it gets stuck inside of asyncio (note that the async io loop is completely managed by playwright and no other API is using it at the same time).

```
================================= Thread Dump =================================

 Thread asyncio_0  (daemon: False)

 File "C:\ProgramData\robocorp\ht\a270cf9_5a1fac3_9fcd2534\lib\threading.py", line 937, in _bootstrap
   self._bootstrap_inner()
 File "C:\ProgramData\robocorp\ht\a270cf9_5a1fac3_9fcd2534\lib\threading.py", line 980, in _bootstrap_inner
   self.run()
 File "C:\ProgramData\robocorp\ht\a270cf9_5a1fac3_9fcd2534\lib\threading.py", line 917, in run
   self._target(*self._args, **self._kwargs)
 File "C:\ProgramData\robocorp\ht\a270cf9_5a1fac3_9fcd2534\lib\concurrent\futures\thread.py", line 81, in _worker
   work_item = work_queue.get(block=True)

-------------------------------------------------------------------------------
 Thread MainThread  (daemon: False)

 File "C:\ProgramData\robocorp\ht\a270cf9_5a1fac3_9fcd2534\lib\site-packages\playwright\sync_api\_context_manager.py", line 56, in greenlet_main
   self._loop.run_until_complete(self._connection.run_as_sync())
 File "C:\ProgramData\robocorp\ht\a270cf9_5a1fac3_9fcd2534\lib\asyncio\base_events.py", line 634, in run_until_complete
   self.run_forever()
 File "C:\ProgramData\robocorp\ht\a270cf9_5a1fac3_9fcd2534\lib\asyncio\windows_events.py", line 321, in run_forever
   super().run_forever()
 File "C:\ProgramData\robocorp\ht\a270cf9_5a1fac3_9fcd2534\lib\asyncio\base_events.py", line 601, in run_forever
   self._run_once()
 File "C:\ProgramData\robocorp\ht\a270cf9_5a1fac3_9fcd2534\lib\asyncio\base_events.py", line 1869, in _run_once
   event_list = self._selector.select(timeout)
 File "C:\ProgramData\robocorp\ht\a270cf9_5a1fac3_9fcd2534\lib\asyncio\windows_events.py", line 439, in select
   self._poll(timeout)
 File "C:\ProgramData\robocorp\ht\a270cf9_5a1fac3_9fcd2534\lib\asyncio\windows_events.py", line 788, in _poll
   status = _overlapped.GetQueuedCompletionStatus(self._iocp, ms)

=============================== END Thread Dump ===============================
```

A `Ctrl+C` seems to show a bit more information (as it seems to show things before greenlet switches, although the basic seems to be the same):

![image](https://github.com/microsoft/playwright-python/assets/117621/bfe81715-49db-439b-8a7f-201a1a15dd2a)

**Comment by mxschmitt** [comment]
We unfortunately need a minimal reproducible in order for us to act on it. If you cannot share that, I recommend you to self debug it for now. Or can you share repro steps? Since this looks like some custom setup.

**Comment by fabioz** [comment]
I got a reproduction, but it seems some issue with `asyncio` and COM on Windows, not sure if it can be fixed in playwright (the problem only manifested when `pywinauto` was also imported (when it loaded UIAutomationCore.dll and got the root element). 

Also, I can only reproduce it in Windows Server 2022, not Windows 11 (so, maybe some bug in Microsoft Windows).

Out of curiosity, the repro is:

```
from playwright.sync_api import sync_playwright

# This is from pywinauto
import comtypes.client
UIA_dll = comtypes.client.GetModule('UIAutomationCore.dll')
ui_automation_client = comtypes.gen.UIAutomationClient
iuia = comtypes.CoCreateInstance(
        ui_automation_client.CUIAutomation().IPersist_GetClassID(),
        interface=ui_automation_client.IUIAutomation,
        clsctx=comtypes.CLSCTX_INPROC_SERVER
        )
true_condition = iuia.CreateTrueCondition()
root = iuia.GetRootElement()

if __name__ == '__main__':
    print('start pw')
    pw = sync_playwright().start()
    print('stop pw')
    pw.stop()
    print('stopped pw')
```

So, not sure, feel free to close if you think there's nothing to do in playwright.

**Comment by fabioz** [comment]
Or since it's a MS project you can get help from someone internally -- as the bug seems to be related to UIAutomation messing things for asyncio when used in Windows Server 2022 ;)

Note: I also reported this to CPython itself explaining a bit more where inside of asyncio things go haywire: https://github.com/python/cpython/issues/111604

**Comment by mxschmitt** [comment]
Doesn't sound like a Playwright bug as per https://github.com/python/cpython/issues/111604#issuecomment-1795718186.

I recommend to file it in their bug tracker instead, to understand why they are changing good defaults etc. Thanks for your understanding since we are not familiar with UIAutomation.
