### ISSUE TITLE
[BUG] Conda releases for v1.39.0 are all for Python <3.12

### ISSUE THREAD

**Issue by dangotbanned** [microsoft/playwright-python#2142]
### System info
- Playwright Version: [v1.39]
- Operating System: [All]
- Browser: [N/A]
- Other info: [Playwright conda repo](https://anaconda.org/Microsoft/playwright/files?version=1.39.0) seems to support only py38-py311

### Source code

- [X] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```python
C:\Users\...>micromamba create -n playw_repro "python>=3.12.0" "playwright>=1.39.0" -c conda-forge -c microsoft
```

**Steps**
- Try to create environment with conda/mamba/micromamba and specs above

**Expected**

That this installation would be possible since #2116.
I've been able to update to v1.39.0 on my py3.11 env and expected support for py3.12 given that it is the only feature listed in the v1.39.0 release

**Actual**

```python
conda-forge/win-64                                          Using cache
conda-forge/noarch                                          Using cache
microsoft/win-64                                              No change
microsoft/noarch                                              No change
error    libmamba Could not solve for environment specs
    The following packages are incompatible
    ├─ playwright >=1.39.0  is installable with the potential options
    │  ├─ playwright 1.39.0 would require
    │  │  └─ python_abi 3.10.* *_cp310, which can be installed;
    │  ├─ playwright 1.39.0 would require
    │  │  └─ python_abi 3.9.* *_cp39, which can be installed;
    │  ├─ playwright 1.39.0 would require
    │  │  └─ python_abi 3.8.* *_cp38, which can be installed;
    │  └─ playwright 1.39.0 would require
    │     └─ python_abi 3.11.* *_cp311, which can be installed;
    └─ python >=3.12.0  is not installable because it requires
       └─ python_abi 3.12.* *_cp312, which conflicts with any installable versions previously reported.
critical libmamba Could not solve for environment specs
```

**Comment by dangotbanned** [comment]
@mxschmitt appreciate the quick fix. 

Should I expect this to be part of v1.39.1/v1.40? 

Fyi, there haven't been any new [conda builds](https://anaconda.org/Microsoft/playwright/files?sort=time&sort_order=desc) uploaded as a result of #2143. 
Apologies if this is expected.

**Comment by mxschmitt** [comment]
This will be part of 1.40.
