### ISSUE TITLE
[BUG] add_cookie() not working as expected ?

### ISSUE THREAD

**Issue by harmin-parra** [microsoft/playwright-python#2146]
### System info

- Playwright Version: [v1.39.0]
- Operating System: [Linux]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

from playwright.sync_api import Page

```
def test_3(page: Page):
    page.goto("https://example.cypress.io/commands/cookies")
    page.context.clear_cookies()
    assert len(page.context.cookies()) == 0
    page.context.add_cookies([{
        "name": "token",
        "value": "",
        "domain": "example.cypress.io",
        "path": "/",
        "expires": -1,
        "httpOnly": False,
        "secure": False,
        "sameSite": "None"
    }])
    assert len(page.context.cookies()) == 1
```

**Steps**
- [Run the test] `pytest <file.py>`

**Expected**

Test passes

**Actual**

Test failure

```
0 != 1

Expected :1
Actual   :0
```

**Comment by mxschmitt** [comment]
You need to set secure: True, since you are setting a cookie for a secure website.

**Comment by harmin-parra** [comment]
Thank you !
It works :)

I have a question:

Why can't I set a simple cookie with just 2 properties? like `{ 'name': 'token', 'value': 'abc'}`

I am forced to set the other properties (`domain`, `path`, etc.)
