### ISSUE TITLE
[BUG] Not full support for CSS selectors

### ISSUE THREAD

**Issue by harmin-parra** [microsoft/playwright-python#2147]
### System info
- Playwright Version: [v1.39.0]
- Operating System: [Linux]
- Browser: [Chromium]
- Other info:

Playwright doesn't recognize complex valid selectors and fails with the error message `Failed to execute 'querySelectorAll' on 'Document': 'button:first' is not a valid selector.`

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```python
from playwright.sync_api import Playwright, sync_playwright, expect

def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://example.cypress.io/commands/querying")
    page.locator('#querying .well>button:first').click()

with sync_playwright() as playwright:
    run(playwright)
```

**Steps**

Run the test

**Expected**

HTML element detected and clicked

**Actual**

```
playwright._impl._api_types.Error: DOMException: Failed to execute 'querySelectorAll' on 'Document': 'button:first' is not a valid selector.
    at query (<anonymous>:3272:41)
    at <anonymous>:3282:7
    at SelectorEvaluatorImpl._cached (<anonymous>:3059:20)
    at SelectorEvaluatorImpl._queryCSS (<anonymous>:3269:17)
    at SelectorEvaluatorImpl._querySimple (<anonymous>:3149:19)
    at <anonymous>:3097:29
    at SelectorEvaluatorImpl._cached (<anonymous>:3059:20)
    at SelectorEvaluatorImpl.query (<anonymous>:3090:19)
    at Object.query (<anonymous>:3304:44)
    at <anonymous>:3262:21
=========================== logs ===========================
waiting for locator("#querying .well>button:first")
============================================================
```

**Comment by mxschmitt** [comment]
:first is a jQuery selector and not a web-standard. See here:

<img width="1064" alt="image" src="https://github.com/microsoft/playwright-python/assets/17984549/825f8844-34ef-4e1c-b4af-d1fe90b513ae">

You can use e.g. first-child or [Locator.first](https://playwright.dev/docs/api/class-locator#locator-first).

Folding into https://github.com/microsoft/playwright/issues/27958#issuecomment-1793083399.
