### ISSUE TITLE
[BUG] Can't sign in to Microsoft account using Webkit browser and recommended built in locators like page.get_by_role

### ISSUE THREAD

**Issue by sqanatoliy** [microsoft/playwright-python#2155]
### System info
- Playwright Version: [v1.39]
- Operating System: [Ubuntu 22.04]
- Browser: [WebKit]

### Source code

- [x ] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```python
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright):
    browser = playwright.webkit.launch(headless=False)
    page = browser.new_page()
    page.goto("https://login.microsoftonline.com/")
    email_field = page.get_by_placeholder("Email, phone, or Skype")
    expect(email_field).to_be_visible()
    email_field.fill("example@gmail.com")
    page.get_by_role("button", name="Next").click()
    page.get_by_placeholder("Password").fill("VeryStrongPassword!")
    page.get_by_role("button", name="Sign in")


if __name__ == "__main__":
    with sync_playwright() as p:
        run(p)
```

**Steps**
- [Run the test]

**Expected**

This script should successfully log into the Microsoft account (on chrome it is successful)

**Actual**

I got an error
*AssertionError: Locator expected to be visible
Actual value: None 
Call log:
LocatorAssertions.to_be_visible with timeout 5000ms
waiting for get_by_placeholder("Email, phone, or Skype")*

**Comment by mxschmitt** [comment]
You don't need to use expect here, since fill will already wait until the element appears. The login page of Microsoft seems to use different DOM elements if you do it in WebKit compared to Chromium. Also the placeholder texts change sometimes. This worked for me in WebKit:

```
    email_field = page.get_by_label("Enter your email address, phone number or Skype.")
```

**Comment by sqanatoliy** [comment]
> You don't need to use expect here, since fill will already wait until the element appears. The login page of Microsoft seems to use different DOM elements if you do it in WebKit compared to Chromium. Also the placeholder texts change sometimes. This worked for me in WebKit:
> 
> ```
>     email_field = page.get_by_label("Enter your email address, phone number or Skype.")
> ```

Thanks for the answer.
Did you use real Ubuntu to test?
Using `expect` had no effect on this problem. 
I fill in the placeholder text exactly as it appears on the screen.
I know that the text of the placeholder can be different, but changing the text does not solve anything.
Ok, I'll just use `page.locator` in this case.
My app uses Microsoft authorization and there is even more strange behavior.
For example, when using firefox, I get a share my screen dialog when logging in
A single test behaves very differently in different browsers...

**Comment by mxschmitt** [comment]
Microsoft/Google authentication sites don't like to be automated, usually for testing there is a dedicated way of logging in, with e.g. a token.

Since this is about a website which behaves differently based on the browser, this seems not actionable for us, closing by that, thanks for your understanding!
