### ISSUE TITLE
[BUG] get_by_label().click() does not work on the Ant Design Radio component

### ISSUE THREAD

**Issue by smallis-2018** [microsoft/playwright-python#2159]
### System info
- Playwright Version: [v1.38.0]
- Operating System: [Windows 10]
- Browser: [Chromium]
- Other info:

### Source code

**Steps**

In the [Ant Design Radio component](https://ant.design/components/radio), the implementation of a button-style radio (see optionType="button") looks like this:
```html
<label>
  <input style="height: 0px;width: 0px;border: initial;margin: 0px;padding: 0px;"></input>
  <span>Radio Name</span>
</label>
```
This causes an issue because the input is not visible, when using 
```python
page.get_by_label("Radio Name").click()
```
the click() function does not work.

**Expected**

Can correctly click the label named 'Radio Name'.

**Comment by mxschmitt** [comment]
I tried the following which was working for me:

```html
  await page.goto('https://ant.design/~demos/components-radio-demo-radiogroup-options');
  await page.locator('label').filter({ hasText: 'Pear' }).nth(2).click();
  await page.locator('label').filter({ hasText: 'Orange' }).nth(2).click();
  await page.locator('label').filter({ hasText: 'Pear' }).nth(3).click();
  await page.pause()
```

What do I do differently?

**Comment by smallis-2018** [comment]
My mistake, I overlooked some things. 
get_by_label()  is used to locate "input".
