### ISSUE TITLE
[BUG]Remote debug on chrome always crash 

### ISSUE THREAD

**Issue by grayguest** [microsoft/playwright-python#2160]
### System info
- Playwright Version: [v1.39.0]
- Operating System: [Windows 10 Enterprise LTSC]
- Browser: [Chromium] 119.0.6045.124 (Official Build) (64-bit) (cohort: Stable) 
- Other info: The Chrome and playwright should be the newest version

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

The code is very simple, but always crash when I run the code below, 

```python
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.connect_over_cdp('http://127.0.0.1:11111')
    context = browser.contexts[0]
    # context.tracing.start(screenshots=True, snapshots=True, sources=True)
    page = context.pages[0]

    page.goto("https://www.baidu.com/")

    # context.tracing.stop(path = "trace.zip")

with sync_playwright() as playwright:
    run(playwright)

```

**Steps**
- Run the chrome with remote debug command: `"C:\Program Files\Google\Chrome\Application\chrome.exe" --remote-debugging-address=0.0.0.0 --remote-debugging-port=11111  --new-window https://www.google.com`
- Run the code above
- Then the chrome will crash with all extension
![1](https://github.com/microsoft/playwright-python/assets/10668340/a2b272f7-db67-4e38-9730-9c95482559ce)

**Expected**

chrome will not crash and the code end with normally.

**Actual**

chrome crash

**Comment by mxschmitt** [comment]
When you launch the Chromium process it should yield more output about why its crashing etc. Do you launch Chrome in the background? You can also try to close all running Chrome instances and specify a `--user-data-dir=foo`.

Have you tried to disable the extensions? Since Tampermonkey reports that it crashed. Maybe this is related.

**Comment by grayguest** [comment]
> When you launch the Chromium process it should yield more output about why its crashing etc. Do you launch Chrome in the background? You can also try to close all running Chrome instances and specify a `--user-data-dir=foo`.
> 
> Have you tried to disable the extensions? Since Tampermonkey reports that it crashed. Maybe this is related.

Hello, Sir, Thank you for your reply. I don’t know how to find the cause of the chrome process crash. Through debugging, I found that if you add page.close() at the end of the code, chrome will not crash, but the chrome page will be closed. Is there any way to return the control of the page from playwright to chrome? I don't want the page to be closed.
![image](https://github.com/microsoft/playwright-python/assets/10668340/f6c679ea-1c71-4756-a6f3-8e60ba37a2f0)
![image](https://github.com/microsoft/playwright-python/assets/10668340/e1214911-f62a-466d-a17e-0a8ef296b1de)


Yes, I have tried to remove all extensions or add another extension, I don't think that has anything relation with the extension, since I'm not calling the extension either.

**Comment by mxschmitt** [comment]
>  I don’t know how to find the cause of the chrome process crash

It will get printed to the stderr when you launch chromium. Also "chrome://crashes" should contain an entry, could you try navigating to this site and see if there is any entry? If so, upload the crash there.

**Comment by grayguest** [comment]
> > I don’t know how to find the cause of the chrome process crash
> 
> It will get printed to the stderr when you launch chromium. Also "chrome://crashes" should contain an entry, could you try navigating to this site and see if there is any entry? If so, upload the crash there.

I ran the chrome program from the desktop shortcut instead of the command line. There should be no stderr-related error prompts. Chrome's crash log is very simple. I feel that there is no effective information that can be used to locate the problem.
![image](https://github.com/microsoft/playwright-python/assets/10668340/915df3dd-256a-463f-8b71-d45d9bab04d7)

Is there any other function that can replace `page.close()` but will not close the window?

**Comment by grayguest** [comment]
I have a little guess. Is it possible that the handle resource of the relevant page is not released? Because as long as I call page.close() at the end of code, neither the program nor chrome will error or crash.

**Comment by grayguest** [comment]
Sir, can you reproduce this? Is it because of related driver issues? Is there something that needs to be updated? When I use selenium I don't have this problem.

**Comment by grayguest** [comment]
Even after installing the latest version of chrome, it still causes crashes.

```
PS E:\python\playwr> playwright.exe install --force chrome
Downloading Google Chrome
Installing Google Chrome

ProductVersion   FileVersion      FileName
--------------   -----------      --------
119.0.6045.124   119.0.6045.124   C:\Program Files\Google\Chrome\Application\chrome.exe
```

**Comment by grayguest** [comment]
Sorry, It seems to be my problem. The chrome version is too new. If I switch to version 118, the crash problem will not occur.
