### ISSUE TITLE
 [BUG] Can't click 2FA DUO button

### ISSUE THREAD

**Issue by Harry-Jing** [microsoft/playwright-python#2162]
### System info
- Playwright Version: 1.39.0
- Operating System: macOS 14.1
- Browser: All
- Other info: python 12.0

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```python
import asyncio
from playwright.async_api import async_playwright, Page

async def main():
    async with async_playwright() as playwright:
        browser = await playwright.chromium.launch(headless=False)
        context = await browser.new_context()
        page = await context.new_page()

        # Open the page
        await page.goto("https://my.uw.edu/")

        # then will jump to login page
        await page.fill("#weblogin_netid", ACCOUNT)
        await page.fill("#weblogin_password", PASSWORD)
        await page.click("#submit_button")

        button = page.locator("#passcode")
        await button.wait_for() # playwirght cant find the button
        await button.click() 

        await browser.close()


if __name__ == "__main__":
    ACCOUNT: str = "xxx"
    PASSWORD: str = "xxxxx!"
    asyncio.run(main())

```

**Steps**
- Just run it

**Expected**

- The playwright can't located the button
```cli
 playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator("#passcode") to be visible
============================================================
```

**Actual**

It should to be to click that button, but it cant find it

**Related link**

similar issue: https://github.com/microsoft/playwright/issues/2573
DUO website: https://duo.com

**Comment by Harry-Jing** [comment]
<img width="1282" alt="image" src="https://github.com/microsoft/playwright-python/assets/69247286/67fa53aa-c339-4d84-9c92-3689f4010272">

**Comment by mxschmitt** [comment]
This looks not look like an end-to-end testing use-case and more like to trick a bot protection mechanism where we can't act on it. Thanks for your understanding.
