### ISSUE TITLE
[Feature] Add functionality for splitting video recording of a page

### ISSUE THREAD

**Issue by ShameemAkhtar111** [microsoft/playwright-python#2165]
Add some methods to start, stop and save page video in between the execution. So that a single page object can have multiple recordings and not only one big video file.
We have methods like page.video.path(), video.delete() and video.save_as(path).
We should be having additional methods like page.video.start(), page.video.stop(filename).

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/28183.
