### ISSUE TITLE
[Feature] Selective SSL Error Handling in Web Automation

### ISSUE THREAD

**Issue by GabrielOctavianPopa** [microsoft/playwright-python#2166]
I have a dictionary with multiple URLs, in some of them I want to ignore the ssl certificate errors and in others I do not. 

The way Playwright works at the moment, what I should do is create a new context and add "ignore_https_errors=True" to test the URLs with self-signed certificates and another one for the rest.

Would it be a good idea to add the ability to ignore a list of URLs?

What I mean is, given an url_list, check if the URL is in an excluded_urls_list, here is an example:

```python
import asyncio
from typing import List

from playwright.async_api import async_playwright


async def main(url_list: List[str] = None):
    excluded_urls_list: List[str] = [
        "https://self-signed.badssl.com/",
        "https://expired.badssl.com/",
        "https://wrong.host.badssl.com/",
        "https://self-signed-tool.com/",
    ]

    async with async_playwright() as playwright:
        browser = await playwright.chromium.launch()
        context = await browser.new_context()
        page = None

        for url in url_list:
            if url in excluded_urls_list:
                page = await context.new_page(ignore_https_errors=True)
            else:
                page = await context.new_page()

        page.goto(url)


asyncio.run(main())
```

**Comment by mxschmitt** [comment]
This is outside of the scope for Playwright. We recommend ignore_https_errors=true on the context itself.

**Comment by GabrielOctavianPopa** [comment]
Thanks for the feedback.
