### ISSUE TITLE
[BUG] Download event not fired on headless=new mode

### ISSUE THREAD

**Issue by elacuesta** [microsoft/playwright-python#2169]
### System info
- Playwright Version: 1.39.0
- Operating System: Linux Mint 21.1 (based on Ubuntu 22.04 LTS)
- Browser: Chromium
- Python 3.10.0

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```python
import asyncio
from playwright.async_api import async_playwright

download_event = asyncio.Event()

async def handle_download(download):
    download_bytes = (await download.path()).read_bytes()
    print("url:", download.url)
    print("suggested_filename:", download.suggested_filename)
    print("bytes:")
    print(download_bytes[:200])
    download_event.set()

async def main():
    async with async_playwright() as p:
        browser = await p.chromium.launch(
            # args=["--headless=new"],
            # ignore_default_args=["--headless"],
        )
        page = await browser.new_page()
        page.on("download", handle_download)
        try:
            response = await page.goto(
                "https://defret.in/assets/certificates/attestation_secnumacademie.pdf"
            )
        except Exception:
            print("Caught expected exception, waiting on download")
            await download_event.wait()
        else:
            print(await page.title())
            print(await page.content())
            print(await response.body())
        await browser.close()

asyncio.run(main())
```

**Steps**
- Run the test file: `python pdf.py`
- Run again enabling the commented lines (launch kwargs)

**Expected**

Page navigation fails when trying to get a PDF but we're able to get the file content's with the Download API as explained in [this comment](https://github.com/microsoft/playwright/issues/21841#issuecomment-1479124898).

**Actual**

Download event is fired when using the current headless mode and the file is retried correctly, however the event is NOT fired when using the new headless mode (as explained in [this comment](https://github.com/microsoft/playwright/issues/21194#issuecomment-1444276676)). Instead the `goto` call success but the page & response contents do not contain the actual PDF bytes.

**Result with current headless mode (launch kwargs are commented)**

```
$ python pdf.py
Caught expected exception, waiting on download
url: https://defret.in/assets/certificates/attestation_secnumacademie.pdf
suggested_filename: attestation_secnumacademie.pdf
bytes:
b"%PDF-1.3\n%\xe2\xe3\xcf\xd3\n9 0 obj\n<< /Type /Page /Parent 1 0 R /LastModified (D:20200619180943+02'00') /Resources 2 0 R /MediaBox [0.000000 0.000000 841.890000 595.276000] /CropBox [0.000000 0.000000 841.890000 "
```

**Result with new headless mode (launch kwargs are enabled)

```
$ python pdf.py

<!DOCTYPE html><html><head></head><body style="height: 100%; width: 100%; overflow: hidden; margin:0px; background-color: rgb(38, 38, 38);"><embed name="06674CC1AA5E00108D4FE24992E2062B" style="position:absolute; left: 0; top: 0;" width="100%" height="100%" src="about:blank" type="application/pdf" internalid="06674CC1AA5E00108D4FE24992E2062B"></body></html>
b"<!doctype html><html><body style='height: 100%; width: 100%; overflow: hidden; margin:0px; background-color: rgb(38, 38, 38);'><embed name='06674CC1AA5E00108D4FE24992E2062B' style='position:absolute; left: 0; top: 0;'width='100%' height='100%' src='about:blank' type='application/pdf' internalid='06674CC1AA5E00108D4FE24992E2062B'></body></html>"
```

PD: This looks like more of a general Playwright problem, not only on the Python version, and it's even likely that it's actually a Chromium issue. Thanks in advance for your time.

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/7822
