### ISSUE TITLE
[OUTDATED] Outdated and/or Unmaintained Tests

### ISSUE THREAD

**Issue by Vinyzu** [microsoft/playwright-python#2174]
### System info
- Playwright Version: [v1.40]
- Operating System: All
- Browser: All
### Source code

There some tests that are outdated.
As an example see the un-awaited `(await) page.pause` in [test_page.py](https://github.com/microsoft/playwright-python/blob/main/tests/async/test_page.py#L1321).
Ive generally seen many instances where a linter should solve some issues, as some basic pep8 guidelines are not met.
This is not urgent, but proper (maintained) tests are definitely a must-have for a testing library.

**Comment by mxschmitt** [comment]
Investigation notes: pyright linter does currently not lint tests/async directory.

Action item: We should fix that and let pyright lint this directory as well.

Thanks for filing!

**Comment by Vinyzu** [comment]
Btw a quick hint for another thing i found whilst seting up my own tests:
[test_page.py](https://github.com/microsoft/playwright-python/blob/main/tests/async/test_page.py#L147)

I feel like the `return messages` is a debug or wrong statement.
