### ISSUE TITLE
[INQUIRY] Reliable way to know where Playwright installs browser

### ISSUE THREAD

**Issue by KevinRodriguez777** [microsoft/playwright-python#2192]
I'm trying to add support for Playwright over at 
https://github.com/Nuitka/Nuitka/
However, we haven't been able to find a reliable way to know where the browsers are install to, we could force it to within the playwright site-package folder, but that's not really portable because users might be using an env variable changing the install path, or they might not
i was thinking of using
https://github.com/microsoft/playwright-python/blob/main/playwright/_impl/_driver.py
https://github.com/microsoft/playwright-python/blob/main/playwright/__main__.py
```py
        return package_path / "driver" / "playwright.cmd"
        return package_path / "driver" / "playwright.sh"
``` 
but i can't find those files, are they generated somehow? if so i'm not seeing the code where that happens.

**Comment by mxschmitt** [comment]
Yes these files are generated [inside the setup.py](https://github.com/microsoft/playwright-python/blob/main/setup.py#L45) and put into the wheels during build time of the playwright PIP package.

Browsers are manually installed using the CLI and then placed/managed here: https://playwright.dev/docs/browsers#managing-browser-binaries

**Comment by KevinRodriguez777** [comment]
thank you, so by default (without any set enviroment variables) it installs to the the paths listed in https://playwright.dev/docs/browsers#managing-browser-binaries
if not we can just grab the env variable `PLAYWRIGHT_BROWSERS_PATH` for the path requested by the user

**Comment by mxschmitt** [comment]
yes exactly.

**Comment by KevinRodriguez777** [comment]
I really appreciate your help thank you!
