### ISSUE TITLE
Issue while Uploading a File into UI

### ISSUE THREAD

**Issue by yeswanth-ds** [microsoft/playwright-python#2199]
### System info
- Playwright Version: [v1.XX]
- Operating System: [Windows 10 pro]
- Browser: [Chromium]
- Other info:

### Source code

  ```python
   page.get_by_role("link", name="Navigator").click()
    page.get_by_title("Tools", exact=True).click()
    page.get_by_role("link", name="File Import and Export").click()
    page.get_by_role("button", name="Upload").click()

    with page.expect_file_chooser() as fc_info:
        page.locator('//input[@type="file"]').click()
        page.wait_for_timeout(5000)
        file_chooser = fc_info.value
        file_chooser.set_files("Attachments.txt")


        page.wait_for_timeout(5000)
        page.get_by_role("cell", name="Upload File Close *File *").get_by_label("Account").select_option("11")
        page.get_by_role("button", name="Save and Close").click()
        page.wait_for_timeout(2000)
        page.pause()
        ora_Signout(page) ] I provided exact source code that allows reproducing the issue locally.
```

**Steps**
- [Run the test]
1)Login and Navigate to the particular screen where we will Find "Choose File" option to upload the file to UI
<img width="939" alt="Choose File DOM" src="https://github.com/microsoft/playwright-python/assets/152980946/9c4461a2-8580-495b-98d8-4bd228ac96fe">
<img width="926" alt="Choose File upload" src="https://github.com/microsoft/playwright-python/assets/152980946/efc64f24-eeb2-489d-a830-a8b1e8108c24">

**Expected**

My file need to get uploaded to UI and click save and close. 

**Actual**

After File got attached the mouse cursor is keep on loading and if I save and close it is not getting save and the cursor symbol changed to loading symbol

**Comment by mxschmitt** [comment]
This bug report does unfortunately not contain a self contained reproducible which we can run locally. In order for us to look into it / debug it, we need something which we can run locally. In the meantime we recommend the following resources:

- https://playwright.dev/python/docs/input#upload-files
