### ISSUE TITLE
Selecting a table row in playwright

### ISSUE THREAD

**Issue by sundar-ds** [microsoft/playwright-python#2201]
I have a scenario where I need to select multiple table rows and perform a mass action on the selected rows. I can do this manually online by clicking on the rows, however, when I try to do it using locators, the moment I do the first click it gets into the details rather than just selecting it. Below is the code I use:

    _for row in page.get_by_role("cell", name=" - ").all():
        row.click()_

Is there a locator method that can just select it rather than clicking on it to get inside? Or is there an alternate method to handle this?

**Comment by mxschmitt** [comment]
We unfortunately need a clear self-contained reproducible in order to address bugs like this. Please re-file with something we can run locally, thank you!

**Comment by sundar-ds** [comment]
Here's the fully reproducible code that can be executed to check the query:

from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://fa-etaq-dev8-saasfademo1.ds-fa.oraclepdemos.com/fscmUI/faces/AtkHomePageWelcome")
    page.get_by_placeholder("User ID").click()
    page.get_by_placeholder("User ID").fill("Robert.Jackman")
    page.get_by_placeholder("Password").click()
    page.get_by_placeholder("Password").fill("c%4Pwh%2")
    page.get_by_role("link", name="Home", exact=True).click()
    page.get_by_role("link", name="My Client Groups").click()
    page.get_by_role("link", name="Time Management").click()
    page.get_by_role("link", name="Team Time Cards Team Time").click()
    page.get_by_label("From Date").fill("01/01/23")
    page.get_by_role("combobox", name="Status").click()
    page.locator("[id=\"__af_Z_window\"]").get_by_text("Submitted").click()
    page.get_by_role("button", name="Search", exact=True).click()
    page.pause()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)

The search results page where I have paused the execution is where I need to select those multiple result rows to perform further actions on it. Is there a locator method or an alternate approach to achieve this?
