### ISSUE TITLE
How to Pass a Value present in my Datadict to an Xpath Attribute = Value

### ISSUE THREAD

**Issue by yeswanth-ds** [microsoft/playwright-python#2202]
### System info
- Playwright Version: [v1.XX]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code
Here inside this ''title Attribute' the value is hard coded - @title='Manual Bank Statement 01'
page.locator("//div[@title='Manual Bank Statement 01']//preceding::a[@title='Expand']").click()

I have the same value stored in my datadict, In order make this title attribute value as dynamic I want to pass the value from my datadict, How to do that ? if I pass in the below mentioned manner getting error
page.locator("//div[@title=datadict["StatementID"]]//preceding::a[@title='Expand']").click()

**Comment by mxschmitt** [comment]
Looks like this is about string formatting in Python, you can do e.g. this:

    datadict = {'StatementID': 'Statement 1'}
    page.locator(f"//div[@title={datadict['StatementID']}]//preceding::a[@title='Expand']").click()

See here: https://docs.python.org/3/tutorial/inputoutput.html#formatted-string-literals

**Comment by yeswanth-ds** [comment]
<img width="902" alt="Failed" src="https://github.com/microsoft/playwright-python/assets/152980946/8ce15270-6bf4-49ac-9857-76704dc8f557">
I tired the same but it got failed

**Comment by mxschmitt** [comment]
Could you share the full error message or some code which we can run locally? This would help us a ton in order to debug this issue more efficiently.

**Comment by mxschmitt** [comment]
I'll close it in the meantime. Please re-file if something still isn't work for you, thanks.
