### ISSUE TITLE
[BUG] No matching distribution found for playwright

### ISSUE THREAD

**Issue by FANGOD** [microsoft/playwright-python#2207]
pip install playwright
ERROR: Could not find a version that satisfies the requirement playwright (from versions: none)
ERROR: No matching distribution found for playwright

docker alpine
I did not directly use playwright in Docker. I connected to my playwright cluster through it, but there was no package available.

**Comment by mxschmitt** [comment]
Alpine Linux is not supported as per https://playwright.dev/python/docs/intro#system-requirements

**Comment by FANGOD** [comment]
> Alpine Linux is not supported as per https://playwright.dev/python/docs/intro#system-requirements

Yes, but I just need the basic code for client functionality to connect to external Chrome.

**Comment by darkguy2008** [comment]
> Alpine Linux is not supported as per https://playwright.dev/python/docs/intro#system-requirements

Ok but this answer does not solve the problem. As usual with Microsoft stuff... Is there a way/flag/etc. to force the install? It's common knowledge that Alpine is widely used in Docker containers so...
