### ISSUE TITLE
[BUG]Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1007)')))

### ISSUE THREAD

**Issue by Bc-Aqr** [microsoft/playwright-python#2208]
### **issue：**
I am using McR.microsoft.com/playwright/python:v1.40.0-jammy deployment time appear a mistake, I am wrapped requests sent a HTTPS requests, but were rejected by SSL unsafe and disable link, However, the https request was issued on my local mac sonoma 14.2 system without any problems. After reviewing a lot of materials, the problem was finally located in Ubuntu 22.04 version, which reinforced insecure https links. How can I solve this problem? I are now trying to attempt to HTTPS certificate to import into the container with the certificate, or reduce use McR.microsoft.com/playwright/python:v1.40.0-focal Ubuntu version, I need your help, thank you!

<img width="1322" alt="image" src="https://github.com/microsoft/playwright-python/assets/71823708/eac35de8-f115-4e0e-be88-88699dda4310">

### help
It is the only information that I believe is currently accurate in locating the problem, linked to:
https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/1963834

**Comment by mxschmitt** [comment]
This does not look Playwright related - could you give us exact steps on how to repro? Maybe you need to ignore certificate errors in your http client?

**Comment by mxschmitt** [comment]
Feel free to re-file with a repro, thanks!

**Comment by Bc-Aqr** [comment]
I sent an https request using python package requests and disabled the certificate validation configuration. It worked fine on my mac system, but the problem was reported in Ubuntu. Now I have put the mirror replaced McR.microsoft.com/playwright/python:v1.40.0-focal, which version of ubuntu is lower, less strict for SSL some related authentication mechanism, thank you
