### ISSUE TITLE
Running playwright raises PermissionError on Linux

### ISSUE THREAD

**Issue by ycd** [microsoft/playwright-python#221]
### Reproducing the error

- Created a virtual environment 
- Installed playwright with `python -m pip install playwright`

Tried to run some code

```python
from playwright import sync_playwright

with sync_playwright() as p:
    for browser_type in [p.chromium, p.firefox, p.webkit]:
        browser = browser_type.launch()
        page = browser.newPage()
        page.goto('http://whatsmyuseragent.org/')
        page.screenshot(path=f'example-{browser_type.name}.png')
        browser.close()
```

Then it raised this error

```python
PermissionError: [Errno 13] Permission denied: '/home/leno/Desktop/open-source/pwright/env/lib/python3.8/site-packages/playwright/drivers/driver-linux
```

I think this is not a normal behavior since running Python under sudo is a terrible idea.

**OS**: Ubuntu 20.04
**Python Version**: 3.8.2
**Playwright Version**:  0.142.3

**Comment by mxschmitt** [comment]
Hi, could you try

```
chmod +x /home/leno/Desktop/open-source/pwright/env/lib/python3.8/site-packages/playwright/drivers/driver-linux
```

and run your script afterwards. If that works, we would implement that in our codebase.

**Comment by ycd** [comment]
Hi @mxschmitt, I can confirm it solved my issue. I'd like to help with a PR.
