### ISSUE TITLE
[BUG]the click on the upload button is not effective.

### ISSUE THREAD

**Issue by Fengyuchen163** [microsoft/playwright-python#2212]
### System info
- Playwright Version: [v1.40.0]
- Operating System: [ Windows 11]
- Browser: [Chromium]
- Other info:
- python version: [3.10]

When using the file_chooser, the click on the upload button is not effective.
But it works fine when I click on it manually.
I'm sorry, but I cannot provide a reproducible example as the corresponding device can only be accessed locally.
But I captured logs using Trace Viewer.

My invocation method is as follows:
```python
        def upload():
            if file_path is not None:
                if os.path.isfile(file_path):
                    with self.page.expect_file_chooser() as fc:
                        locator.click()
                    file_chooser = fc.value
                    file_chooser.set_files(file_path)
                    self.log.info(f'Device {self.model} upload {file_path} file Successful')
                else:
                    locator.click()
                    self.log.info(f'{file_path} is not file, but click upload file button')

```
**Expected**
  Click the button and invoke the file chooser

**Actual**
Nothing happened

![pc_1](https://github.com/microsoft/playwright-python/assets/39661524/cd6b2a8a-5aa2-48b6-8363-3cb776c34d37)

![pc_2](https://github.com/microsoft/playwright-python/assets/39661524/a086fa3d-756d-4d0c-b9a9-3c18041d31dd)

**Comment by god-pane** [comment]
This elements is an input.
html  Like <input type="button" id="third_conf_import" value="Import">.
