### ISSUE TITLE
[Feature] v1.40.1 in python

### ISSUE THREAD

**Issue by golankopi** [microsoft/playwright-python#2213]
Hi!
the v1.40.1 exists in https://github.com/microsoft/playwright/releases
is not here on playwright-python, any particular reason?

the need from my end is the fix for https://github.com/microsoft/playwright/issues/28319 
cause currently we have corrupted traces when working with v1.40.0

thanks!

**Comment by mxschmitt** [comment]
We'll release 1.41.0 soon, which will contain that fix. Sorry for the inconvenience.
