### ISSUE TITLE
[BUG] Found a bug, page.query_selector_all execution error.

### ISSUE THREAD

**Issue by 010101fff** [microsoft/playwright-python#2214]
### System info
- Playwright Version: v1.40.0
- Operating System: Windows 11
- Browser: Chromium v120
- Other info: python310

### Source code
```
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch(executable_path="C:\Program Files\chrome-win\chrome.exe",headless=False)
    page = browser.new_page()
    page.goto("http://www.qq.com")
    print(page.title())
    page.query_selector_all("*")
    browser.close()
```

**Steps**
- run python

![image](https://github.com/microsoft/playwright-python/assets/96037240/36c2a573-a703-40a1-a1be-7a3695f556c8)

 `page.query_selector_all` execution error.

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/28086

This should be fixed with the next release.
