### ISSUE TITLE
[BUG]/opt/conda/envs/py38/lib/python3.8/site-packages/playwright/driver/node: /usr/lib/libstdc++.so.6: no version information available

### ISSUE THREAD

**Issue by 2424004764** [microsoft/playwright-python#2218]
已搜索现有issues，且包含已关闭的，暂无解决方案，且使用的是最新的playwright。

### System info
- Playwright Version: Latest
- Operating System: apline
- Browser: apline
- Other info:

### Source code

我在apline中可以安装playwright，但是执行playwright就报错了

i input command:
playwright

**Comment by mxschmitt** [comment]
Alpine Linux is not supported as per [here](https://playwright.dev/python/docs/intro). We recommend using our [Docker image](https://playwright.dev/python/docs/docker) or using a supported OS.
