### ISSUE TITLE
playwright dom.js TypeError: log is not iterable

### ISSUE THREAD

**Issue by lgl8023** [microsoft/playwright-python#2224]
### System info
- Playwright Version:  v1.28.0
- Operating System: Windows 11
- Browser: Chromium
- Other info:

### Source code

E:\Anaconda\envs\tracker\Lib\site-packages\playwright\driver\package\lib\server\dom.js:850
      for (const entry of log) this._progress.logEntry(entry);
                          ^

TypeError: log is not iterable
    at InjectedScriptPollHandler._streamLogs (E:\Anaconda\envs\crime_tracker_env\Lib\site-packages\playwright\driver\package\lib\server\dom.js:850:27)

**Comment by mxschmitt** [comment]
Please re-file following the issue template. Also you are using a very old Playwright version, so we recommend updating.
