### ISSUE TITLE
[Feature] Option to provide slowmo argument as a part of browsercontext rather at browser launch

### ISSUE THREAD

**Issue by sundar-ds** [microsoft/playwright-python#2229]
When we use pytest the way of creating tests, the slowmo argument has to be specified at the CLI level when invoking the pytest argument. Would like to have it when creating a new context once the browser is launched.

The ask is because when i have a series of tests that involves the pytest way, I have to use the python way for launching browser to set a slowmo just for that test. And when this is done, the python method executes at the very last after all the pytest methods are complete.
 
E.g.,
![image](https://github.com/microsoft/playwright-python/assets/146530679/9d60c509-6dc3-4097-bc22-cb2812c0204f)

Note in the above way of running of pytest methods, the method 'test_ESSEnrollinBenefits' runs only at the end after all other tests are complete.

**Comment by mxschmitt** [comment]
```python
import pytest

@pytest.fixture(scope="session")
def browser_type_launch_args(browser_type_launch_args):
    return {
        **browser_type_launch_args,
        "slow_mo": 123,
    }
```

slow_mo is [already a launch arg](https://playwright.dev/python/docs/api/class-browsertype#browser-type-launch-option-slow-mo). Would that work for you?

**Comment by sundar-ds** [comment]
So, with this fixture, everytime a new context is created, will it apply this arg? I want slow_mo only for specific tests and not for all. Is there a way to bring it down only to a few tests that require this?

**Comment by mxschmitt** [comment]
Yeah so you want it on the context level. Do you mind sharing your use-case why you want to use slow_mo in the first place?

**Comment by sundar-ds** [comment]
My use case is, there are some test cases in our application that just wouldn't run if I don't do intermediate waits. I know its not recommended but it has been working well so far. Since there is no option to set this at the context level, I have to launch a new browser which is deviating from the way we create our tests and also the pushes the execution of such cases to the very last in the sequence of tests. Would be great to have this set at the context level.

**Comment by mxschmitt** [comment]
We recommend waiting for [something specific](https://playwright.dev/python/docs/events#waiting-for-event), like text or elements to appear. As a fallback you could also wait for specific requests. Slowmo is not reliable, hence we are not recommending it. -> results in flaky tests.

Closing as per above.
