### ISSUE TITLE
specifying viewport in browser.newContext + screenshot sizing

### ISSUE THREAD

**Issue by ckang244** [microsoft/playwright-python#223]
I'm trying to take a large screenshot by using a tall viewport, similar to what I was doing in the node version of playwright. Everything else has translated over to python easily, but I'm not getting the same screenshots using the same parameters between node/python. For example, whatever values I put for the `viewport` parameter in `browser.newContext`, I still get the same default screenshot size it seems. If I set `fullPage=True` in the `page.screenshot` call, I get a full page, but the size depends on the content, not the specified viewport. Not sure if this is a bug, or if I'm using this incorrectly. Would appreciate any insight here.

Also, I expected to just be able to pass a dict with the viewport width/height, similar to node. Instead, to avoid errors I had to use an instance of the imported `IntSize` class here, which is a bit counterintuitive and undocumented. 
```
context = await browser.newContext(viewport=IntSize(width=1280, height=2080))
```

**Comment by pavelfeldman** [comment]
> Also, I expected to just be able to pass a dict with the viewport width/height, similar to node. Instead, to avoid errors I had to use an instance of the imported IntSize class here, which is a bit counterintuitive and undocumented.

IntSize is just a name for the typed dict, you can see viewport [typed](https://microsoft.github.io/playwright-python/sync_api.html#playwright.sync_api.Browser.newContext) as a dictionary. So the following should work, does it not?

```py
browser.newContext(viewport={'width': 100, 'height': 100})
```

**Comment by ckang244** [comment]
@pavelfeldman I'm able to use just a dict without errors, yes, as you specified. But the result doesn't match the desired viewport height.

Essentially, I'm trying to compare this in node:
```
const context = await browser.newContext({
    viewport: { width: 1280, height: 4080 },
    deviceScaleFactor: 2,
  });
```
to this in python:
```
context = await browser.newContext(
    viewport={'width': 1280, 'height': 4080},
    deviceScaleFactor=2,
)
```
In the node version of playwright, I get an image which is 2560x8160 as expected. In python, it's 1280x 720.

**Comment by Evilran** [comment]
> @pavelfeldman I'm able to use just a dict without errors, yes, as you specified. But the result doesn't match the desired viewport height.
> 
> Essentially, I'm trying to compare this in node:
> 
> ```
> const context = await browser.newContext({
>     viewport: { width: 1280, height: 4080 },
>     deviceScaleFactor: 2,
>   });
> ```
> 
> to this in python:
> 
> ```
> context = await browser.newContext(
>     viewport={'width': 1280, 'height': 4080},
>     deviceScaleFactor=2,
> )
> ```
> 
> In the node version of playwright, I get an image which is 2560x8160 as expected. In python, it's 1280x 720.

```
async def main():
    async with async_playwright() as play:
        browser = await play.chromium.launch()
        context = await browser.newContext(
            viewport={'width': 1280, 'height': 4080},
            deviceScaleFactor=2,
        )
        page = await context.newPage()
        await page.goto('http://example.com')
        await page.screenshot(path='example.png')
        await browser.close()

asyncio.get_event_loop().run_until_complete(main())

```
The code above works for me, I got an image which is 2560x8160 as expected.
1280x720 is the default view port of playwright.
I suspect that you write the code like this:
`page = await  browser.newPage()`
If you define a specific view port for `context`, you're supposed to use `context` to visit pages.
`page = await context.newPage()`

**Comment by ckang244** [comment]
@Evilran Thanks for your help. It was indeed a bug in that I should've used `context`. Now everything works as expected.
