### ISSUE TITLE
[BUG] missing traces with the command --tracing=retain-on-failure --output=output 

### ISSUE THREAD

**Issue by amitba-savvy** [microsoft/playwright-python#2232]
### System info
- Playwright Version: 1.39.0
- Operating System:   mcr.microsoft.com/playwright:focal
- Browser: All, Chromium
- Other info:

run with playwright plugin for traces 

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Test file (self-contained)**

```python
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()
    # ...
    browser.close()
```

**Steps**
- [Run the test]
- [...]

**Expected**

[Describe expected behavior]

**Actual**

[Describe actual behavior]

**Comment by mxschmitt** [comment]
Closing since this bug is not following the issue template. Feel free to re-file.
