### ISSUE TITLE
[BUG] page.wait_for_url() not working with glob exclude pattern

### ISSUE THREAD

**Issue by masonkrause1** [microsoft/playwright-python#2243]
Hi- I'm trying to run a test that waits for the url to change after clicking button to any value but to old url (https://www.oldurl.com). This should be very simple, but it's not working with page.wait_for_url(). 

page.locator('#my-button').click()
page.wait_for_url('!https://www.oldurl.com')

Expected behavior is that it stops waiting after navigating away from the old url, but it's just waiting forever (until timeout). I also tried page.expect_navigation() but it's deprecated and finicky.  

### System info
- Playwright Version: v1.40.0
- Operating System: Debian 12, Ubuntu 22
- Browser: All
- 
**Expected**

stops waiting after navigating away from the old url

**Actual**

waiting indefinitely (until timeout)

**Comment by mxschmitt** [comment]
`!` is not part of the glob semantics. You can either create a regular expression instead or use a callback, which fits probably for your use-case the best.

     page.wait_for_url(lambda url: url != "https://www.oldurl.com/")

**Comment by masonkrause1** [comment]
Thanks for the information- that makes sense and this is super helpful!
