### ISSUE TITLE
[BUG] version 1.41.0 is not on pypi

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright-python#2245]
https://pypi.org/project/playwright/#history

![image](https://github.com/microsoft/playwright-python/assets/57028336/eeac8a13-49f3-41a9-88fa-96eaa5e19a65)

**Comment by mxschmitt** [comment]
Thanks for reporting, we are working on it.

**Comment by pmareke** [comment]
I think the latest image is broken until this is fixed

![image](https://github.com/microsoft/playwright-python/assets/3502075/2590f6c0-f7ba-419a-a99b-da2c2de8adfb)

**Comment by mxschmitt** [comment]
In general we strongly recommend pinning the Docker image: https://playwright.dev/python/docs/docker by providing a specific Docker image tag.

**Comment by pmareke** [comment]
Thanks @mxschmitt but in our case we prefer to keep our dependencies up to date.

Knowing that we'll pinned the version.

**Comment by mxschmitt** [comment]
Should be live now!
