### ISSUE TITLE
[QUESTION] - add more than 30 second timeout to the test duration globally

### ISSUE THREAD

**Issue by Romarionijim** [microsoft/playwright-python#2247]
Hi, I'm using playwright with Python, I was going and searching through the documentation and I don't see a way to handle global timeouts for test duration, in typescript I have the option to specify both timeouts and global timeouts in the playwright.config.file E.G =>   timeout: 150000, globalTimeout: 150000.
I don't see anywhere in the documentation that addresses this issue and as a result my tests keep failing in the CI due to timeout of 30 seconds have been exceeded even when running in parallel, matter of fact I don't see any timeout options such as command line flag --timeout or something in the doc, it keeps pointing me to nodejs documentation but I need it for python.

as of my project i have a pytest.ini file which has the following:

[pytest]

addopts =
 --clean-alluredir
 --alluredir=./allure-results
 --slowmo=500
 --screenshot=on
 --video=on

my question is does playwright python have a feature that I can set timeouts globally for all of the tests? if there is, I would.  love if you could point me to the relevant resource in the docs to solve the timeout issue, thanks.

**Comment by mxschmitt** [comment]
We don't offer this functionality, this is something Pytest plugins can offer e.g. this one: https://pypi.org/project/pytest-timeout/ which might fit for your use-case. 

We at Playwright for our internal tests in the Python project use e.g. `--timeout 90` when running Pytest and we have on the CI side, in GitHub Actions [timeout-minutes](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes): 45 in place.

**Comment by Romarionijim** [comment]
@mxschmitt so in terms of Playwright - I understand that there is no limit for the test duration when using python? oppose to TS 30 seconds default timeout?

**Comment by mxschmitt** [comment]
On the test level this is correct. In Python only the specific action timeout applies which is for click/fill by default 30 and for expect() its 5 seconds.
