### ISSUE TITLE
[BUG] Request mocking doesn't work on Chromium/WebKit

### ISSUE THREAD

**Issue by VladimirPodolian** [microsoft/playwright-python#2248]
### System info
- Playwright Version: v1.40.0
- Operating System: MacOS 13.5.1 (22G90)
- Browser: Chromium/WebKit
- Other info: On firefox exact code works well, but on my desired site all mocked requests aborted with `NS_BINDING_ABORTED` error

`pip3 list` output:
```sh
Package            Version
------------------ ----------
certifi            2023.11.17
charset-normalizer 3.3.2
exceptiongroup     1.2.0
greenlet           3.0.1
idna               3.6
iniconfig          2.0.0
packaging          23.2
pip                22.3.1
playwright         1.40.0
pluggy             1.3.0
pyee               11.0.1
pytest             7.4.4
pytest-base-url    2.0.0
pytest-playwright  0.4.3
python-slugify     8.0.1
requests           2.31.0
setuptools         65.5.1
text-unidecode     1.3
tomli              2.0.1
typing_extensions  4.9.0
urllib3            2.1.0
wheel              0.38.4
```

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```python
from playwright.sync_api import Page, Route


def test_mock_the_fruit_api(page: Page):
    def handle(route: Route):
        json = [{"name": "playwright", "id": 21}]
        # fulfill the route with the mock data
        route.fulfill(json=json)

    # Intercept the route to the fruit API
    page.route("*/**/api/v1/fruits", handle)

    # Go to the page
    page.goto("https://demo.playwright.dev/api-mocking")

    # Assert that the Strawberry fruit is visible
    # page.get_by_text("Strawberry").to_be_visible()
    breakpoint()
```

**Steps**
- Install pytest, playwright, playwright-pytest
- pytest -k test_mock_the_fruit_api --headed --browser chromium

**Expected**
The `api/v1/fruits` request response mocked with `strawberry` data

**Actual**
The `api/v1/fruits` request stuck on infinite pending state
<img width="1280" alt="image" src="https://github.com/microsoft/playwright-python/assets/36446855/aff098c2-1b07-43bb-887d-4a9921c116cb">

**Comment by mxschmitt** [comment]
The reason why the request is still pending is because you are using `breakpoint()` which will halt Python's event loop, so requests from the browsers can't get intercepted on the Python side (no callbacks can get executed).

Have you tried using e.g. `page.wait_for_timeout(100000)` instead? Then the requests should successfully get executed and shown inside DevTools. time.sleep will also not work, see [here](https://playwright.dev/python/docs/library#timesleep-leads-to-outdated-state).

**Comment by VladimirPodolian** [comment]
Omg it works, thanks!
