### ISSUE TITLE
[Feature] `__enter__`/`__exit__` on `Browser`

### ISSUE THREAD

**Issue by jamesbraza** [microsoft/playwright-python#2254]
I have `python-playwright` with version 1.41.0, and the below code:

```python
from playwright.sync_api import sync_playwright


with sync_playwright() as p:
    browser = p.chromium.launch()
    ...  # Use browser
    browser.close()
```

Ideally, one can use a context manager to automate the `close()` call:

```python
from playwright.sync_api import sync_playwright


with sync_playwright() as p, p.chromium.launch() as browser:
    ...  # Use browser
```

Thank you for your consideration

**Comment by jamesbraza** [comment]
One can get pretty close with [`contextlib.closing`](https://docs.python.org/3/library/contextlib.html#contextlib.closing):

```python
import contextlib

from playwright.sync_api import sync_playwright


with sync_playwright() as p, contextlib.closing(p.chromium.launch()) as browser:
    ...  # Use browser
```

However, it would be nice if this was upstreamed to `Browser` itself

**Comment by mxschmitt** [comment]
I'll close it for now since this feature didn't get enough interest the past year. There is a workaround which seems working fine so we recommend that for now.
