### ISSUE TITLE
[BUG] Failing step is not highlighted in red in actions panel for versions after 1.39.0

### ISSUE THREAD

**Issue by jfp1992** [microsoft/playwright-python#2258]
### System info
- Playwright Version: [v1.40.0, 1.41.0]
- Operating System: [Windows 11]
- Browser: [Chromium]
- Other info:

**Steps**
- Run a failing pytest test
- Open trace

**Expected**

Failing step in the actions panel should be highlighted in red

**Actual**

Failing step not highlighted in red

**Additional info**
This is working on version 1.39.0

All traces opened in trace.playwright.dev

**Comment by mxschmitt** [comment]
Can you provide us a introductions on how to reproduce this? This would help us a ton in order to triage and prioritise this!

**Comment by jfp1992** [comment]
create a new project with the latest playwright:
pip install playwright
pip install pytest
pip install pytest-playwright

main.py:
```
from playwright.sync_api import Page, expect


def test_red_step(page: Page):
    page.goto("https://playwright.dev")
    expect(page.locator("body")).to_be_hidden()
```

pytest.ini:
```
[pytest]
addopts =
    --headed
    --tracing retain-on-failure
```

run the test with playwright 1.39.0: red assertion step
run the test with playwright 1.40.0: white assertion step
run the test with playwright 1.41.0: white assertion step

**Comment by mxschmitt** [comment]
I can reproduce:

1.39.0: good
1.40.0: bad

**Comment by mxschmitt** [comment]
This should be fixed in https://github.com/microsoft/playwright-python/releases/tag/v1.41.2.

**Comment by HermanBide** [comment]
I am looking for issues or bugs to fix. i would like to contribute
