### ISSUE TITLE
[BUG] Playwright does not load the page when passing the pattern to page.route

### ISSUE THREAD

**Issue by smolkin895** [microsoft/playwright-python#2265]
### System info
- Playwright Version: [v1.40]
- Operating System: [Windows 10.]
- Browser: [Chrome]
- Other info:
Hi! The issue is related to the use of Pattern in page.route. When I pass the Pattern to page.route, the page stops loading. There is an assumption that playwright fails to handle this regular expression and stops the entire network. If I use a string, the code works normally. It looks like a bug, please help me figure it out
### Source code
        def handler(route: Route):
            response = route.fetch()
            status = response.status
            if status not in [200, 201, 202, 203, 204, 401]:
                failed_handlers.append(response.text())
                logger.info(response.text())
        campaigns_edit.page.route(url=re.compile('[A-Za-z0-9]*(cms|documents)[A-Za-z0-9]*'), handler=handler)

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**
**Steps**
Run the test and catch all endpoints that have "cms" or "documents" in their names

**Expected**
I caught all the endpoints and checked them in the handler
[Describe expected behavior]

**Actual**
The page is not loading. I guess this happens when route catches the response of the first handle and compares it to the Pattern
[Describe actual behavior]

**Comment by mxschmitt** [comment]
When you intercept the requests, you also need to "act" on them by calling e.g [`route.continue`](https://playwright.dev/python/docs/api/class-route#route-continue), [`route.fulfill`](https://playwright.dev/python/docs/api/class-route#route-fulfill) or [`route.abort`](https://playwright.dev/python/docs/api/class-route#route-abort).

If you just want to "sniff" at them, we recommend just adding a request/response event listener: https://playwright.dev/python/docs/network#network-events

**Comment by smolkin895** [comment]
https://github.com/
