### ISSUE TITLE
[BUG] page.expect_request() is ending up in a timeout since Playwright version 1.41.0 for Python

### ISSUE THREAD

**Issue by dharveyqa** [microsoft/playwright-python#2268]
### System info
- Playwright Version: v1.41.0
- Operating System: tested in Windows 11
- Browser: tested with Chromium
- Other info: -

### Source code
```
with page.expect_request("http://example.com/resource") as first:
    page.get_by_text("trigger request").click()
first_request = first.value
```

taken from documentation https://playwright.dev/python/docs/api/class-page#page-wait-for-request

**Steps**
- Run the test

**Expected**
var "first_request" will be filled with the value for the first request

**Actual**
script ends up in a timeout
-> Timeout 30000ms exceeded while waiting for event "request"

(when I change the Playwright to v1.40.0 the script works as expected)

**Comment by mxschmitt** [comment]
The following is working for me:

```python
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()
    page.goto("http://example.com")
    with page.expect_request("https://www.iana.org/help/example-domains") as first:
        page.get_by_text("More information...").click()
    first_request = first.value
    print(first_request.url)
    browser.close()
```

Could you provide us a full self-contained reproduction?

**Comment by dharveyqa** [comment]
Thanks for your answer!
Your code is also working for me.
Will check where the differences are between your snippet and my code and will update this ticket.

**Comment by dharveyqa** [comment]
Hello @mxschmitt,

modified your script now slightly.
Uploaded also a test-website where the problem occurs (link inside an iframe, triggered by onclick)
http://playwright.bplaced.net/

My result with the modified script and the test-website is:
- Playwright 1.40.0: working fine
- Playwright 1.41.1: script ends up in a timeout.

Modified script:

```
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()
    page.goto("http://playwright.bplaced.net/")
    with page.expect_request("*https://www.iana.org*") as first:
        page.frame_locator("#iframe1").frame_locator("#iframe2").get_by_text("mylink").click()
    first_request = first.value
    print(first_request.url)
    browser.close()
```

Hope you can reproduce it 

Best regards
Dylan

**Comment by mxschmitt** [comment]
Thanks for the repro. As of 1.41 we are using the same glob parser in Python as we use upstream in Node.js. This fixed a bunch of bugs users reported e.g. https://github.com/microsoft/playwright-python/issues/2193 and in your issue results in not matching the request. It should be this instead: `https://www.iana.org/**`. One `*` does not go beyond the slash in glob.

I apologise that this resulted in a regression on your side while we consider it as a bugfix. Thanks for your understanding.

**Comment by AraCoders** [comment]
Hi,
I am on latest version of Playwright for Python. The issue is still there and the request isn't matched even tho it's still there.
