### ISSUE TITLE
[Bug]: Playwright video does not get created after context is closed until all tests are run

### ISSUE THREAD

**Issue by sundar-ds** [microsoft/playwright-python#2291]
### Version

1.40.0

### Steps to reproduce

Create 2 or 3 playwright test .py files
Enable video creation by creating the context
close the context after the test is done so the video is created 
Run them together as a pytest class
when a test fails, video's length is up until all the tests are over. The failure screen is the last screen on the video

Looks like the video doesn't get created upon failure of a test until all tests are done. The same doesn't happen for successful tests

### Expected behavior

Videos should be fully created as soon as the context is closed for that test

### Actual behavior

When a test fails, video doesn't get created upon failure of a test until all tests are done when run together as a class

### Environment

```Text
Windows 11
Chromium
Python 3.11
Pytest 7.4.2
```

**Comment by mxschmitt** [comment]
This bug report does not contain a self-contained reproduction. Please re-file following the bug template, thanks for your undreestanding!
