### ISSUE TITLE
[Question] Any good first issues ?

### ISSUE THREAD

**Issue by ukarroum** [microsoft/playwright-python#231]
Hello,

I am new to the repo, and would love to contribute.

Can you guys recommend me any first issues that i can work on ? 

I am a Software developer with around 2-3 years of professional python experience.

Thank you and have a great day !

**Comment by arjunattam** [comment]
Thanks @ukarroum! We will start using the appropriate labels when such issues come up. For now, the list of issues is the best place to start if you're keen on contributing.
