### ISSUE TITLE
[Docs]: How to modify firefoxPrefs with python / pytest.ini

### ISSUE THREAD

**Issue by lfoppiano** [microsoft/playwright-python#2336]
### Page(s)

https://playwright.dev/python/docs/browsers

### Description

I understood that the pdfjs render is disabled by default when running on firefox. I would like to enable it from the pytest.ini if possible, or anywhere where it does not require writing custom handler for each browser. 

Most of the way i saw were done by using javascript, e.g. https://github.com/microsoft/playwright/issues/23926#issuecomment-1618223153 however it would be nice to know how to do it in python. 

The page talks only about how to run on specific browsers but it does not indicate any more information that that.

**Comment by mxschmitt** [comment]
Doing the following should work:

```python
import pytest

@pytest.fixture(scope="session")
def browser_type_launch_args(browser_type_launch_args):
    return {
        **browser_type_launch_args,
        "firefox_user_prefs": {
            "pdfjs.disabled": False,
        }
    }
```

Have you tried that? (if you are using the pytest plugin's page/context/browser fixtures)

**Comment by lfoppiano** [comment]
@mxschmitt sorry, my bad. This solution works fine.
