### ISSUE TITLE
[Bug]:  Playwright Sync API Usage Issue: Error Encountered When Running Multiple Test Files

### ISSUE THREAD

**Issue by aamirbhat** [microsoft/playwright-python#2343]
### Version

1.41.1

### Steps to reproduce

When executing individual test suites created with a page model architecture and using sync API, each file runs successfully.

 pytest  suits/*

 However, when attempting to run them together, an error is encountered. See details belowAPIbelow API
<img width="1400" alt="Screenshot 2024-03-06 at 10 38 17 AM" src="https://github.com/microsoft/playwright/assets/4963798/b678880b-8a5d-4a8f-bdc0-18a320a8d49b">

### Expected behavior

it should not raise any error

### Actual behavior

it should be able to run smoothly and close the PlaywrightContextManager context

### Environment

```shell
OS: Linux 6.2 Ubuntu 22
Binaries:
  Python 3.12
  playwright 1.41.1
```

**Comment by mxschmitt** [comment]
Could you provide us some code which allows us to reproduce this issue? are you using pytest-playwright?

**Comment by mxschmitt** [comment]
Closing as per above. Feel free to re-file with a repro.
