### ISSUE TITLE
[Bug]: Website reached from Docker behaves differently

### ISSUE THREAD

**Issue by tatoalo** [microsoft/playwright-python#2356]
### Version

1.42.0

### Steps to reproduce

Using the following script:
```python
  p = sync_playwright().start()
  browser = p.chromium.launch(headless=HEADLESS, timeout=TIMEOUT)

  ua = (
      custom_user_agent
  )
  
  context = browser.new_context(user_agent=ua, locale="en-US")

  page = context.new_page()

  stealth_sync(page)

  page.goto("https://vm.tiktok.com/any_ID")

  page.wait_for_load_state("domcontentloaded")

  element = page.wait_for_selector('valid_XPATH')
```

The `element` is not found when running inside any Docker container.

### Expected behavior

I would expect the `element` to be found, as per running the same code locally with the same dependencies and same `playwright` version.

### Actual behavior

Inside any docker container (custom or `mcr.microsoft.com/playwright/python:v1.42.0-jammy`) the website seems to receive a different request.

I have inspected network requests from local run vs Docker runs and see no difference in request bodies 🤔 

The official `playwright` container was spawned as
```
docker run -it --rm --ipc=host mcr.microsoft.com/playwright/python:v1.42.0-jammy /bin/bash
```

### Additional context

I also tried with `Firefox` and noticed the same behaviour.

### Environment

```Text
- Operating System: [Ubuntu 22.04]
- Browser: [Chromium, Firefox]
- Python Version: [3.10.12]
```

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. (contains third-party dependencies and is not self-contained). Thanks for your understanding!
