### ISSUE TITLE
Installation behind company firewall possible, when unfiltered internet access is not available?

### ISSUE THREAD

**Issue by mborus** [microsoft/playwright-python#236]
To install playwright behind a very restrictive company firewall, I need to do

`    pip download playwright`

on an internet connected PC and move the downloaded files onto the computer behind the firewall.

Here I can install playwright 

`    pip install playwright --no-index --find-links <folder name>`

Output

```
(venv) D:\install\python>python -m pip install playwright --find-links . --no-index

    Looking in links: .
    Processing d:\install\python\playwright-0.150.0-py3-none-win_amd64.whl
    Processing d:\install\python\greenlet-0.4.17-cp38-cp38-win_amd64.whl
    Processing d:\install\python\typing_extensions-3.7.4.3-py3-none-any.whl
    Processing d:\install\python\pyee-8.1.0-py2.py3-none-any.whl
    Installing collected packages: greenlet, typing-extensions, pyee, playwright
    Successfully installed greenlet-0.4.17 playwright-0.150.0 pyee-8.1.0 typing-extensions-3.7.4.3

```
Performing the actual installation "python -m playwright install" fails

```
    (venv) D:\install\python>python -m playwright install
    (node:4552) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 13.107.246.10:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
(node:4552) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4552) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

Is there a way to do this manually?

---

UPDATE: Yes, there is (partially, tested on Windows 10).

After letting the installation fail, I can go to an internet connected PC and get the three browsers from

    c:\Users\<user name>\AppData\Local\ms-playwright\chromium-815036\
    c:\Users\<user name>\AppData\Local\ms-playwright\firefox-1188\
    c:\Users\<user name>\AppData\Local\ms-playwright\webkit-1347\

And then move them into the firewalled PC into the same directory structure.

If I now retry the installation  "python -m playwright install" it completes and works, partially.
I can now use chromium. Firefox & Webkit don't work yet...

**Comment by mxschmitt** [comment]
Hi,

are you using proxies in your company which needs to be respected?

In general the following two things are required to use Playwright for Python:
- driver - gets installed with PyPi
- browsers (`python -m playwright install`) - gets installed with the driver - should use the proxy but needs to be confirmed

**Comment by mborus** [comment]
@mxschmitt - there's two problems:

1. there is a proxy with a username/password login (so playwright scripts need to use that proxy whenever the page automated uses ressources that are not on the proxy whitelist)

2. that proxy is filtering the internet access and blocks a lot of things, like executables (the browsers) - this is why I can't install playwright from pip using the "pip install" command directly. The usual work-around is moving required files onto a USB stick and install from USB (I have local admin rights, so I have the permissions necessary to get files onto my local machine via USB)

This also means that "python -m playwright install" fails. It doesn't ask for a proxy login and even if it did, the proxy would still not deliver the browsers. So instead I'm looking for a "python -m playwright download" command that would download the browsers to a directory and a "python -m playwright install --offline" command that would install the downloaded browsers without a need for internet access during the installation. A behaviour similar to pip. 

Alternatively a list of manual steps needed to install the browsers would help people that are trying to use playwright in secured environments.

Some more info: I manually installed node on the machine and run into this proxy problem a lot. Thanksfully pip's download features work great, so this problem only appears when an installation relies on something other than pip.

**Comment by pavelfeldman** [comment]
Some hints for those installing from behind the firewall:
https://playwright.dev/python/docs/installation#install-behind-the-firewall-or-proxy

**Comment by stmax82** [comment]
@pavelfeldman that link is 404.. I'm currently running into the same problem with dotnet playwright install..

**Comment by stephprobst** [comment]
I believe the new URL is https://playwright.dev/python/docs/browsers#install-behind-a-firewall-or-a-proxy
