### ISSUE TITLE
Python Playwright doesn't work in my computer

### ISSUE THREAD

**Issue by PyScriptZenith** [microsoft/playwright-python#2364]
Good afternoon! I have a very strange situation - the playwright library does not work for me. I run the script with an example from the documentation and nothing happens, the script does not complete. I tried adding print(), but it also doesn't output anything to the console. I wrote to my friend and sent my script - everything works for him. Please help me, I don't understand at all what the problem might be, because obviously there are no errors? The process does not complete and the console output remains in the same state as in the screenshot. Tell me, please, how can I try to fix this?

Playwright Version 1.42.0 | Python 3.11.4 | Windows 10

app.py

  ```
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch(headless=False)
    print(browser)
    page = browser.new_page()
    print(page)
    page.goto("https://playwright.dev/python/docs/input")
    browser.close()
  ```

![playwright_error](https://github.com/microsoft/playwright-python/assets/134920106/46fc4afe-3ff9-463c-bbb4-3cf8e1698748)

**Comment by mxschmitt** [comment]
Maybe its related to this? https://github.com/microsoft/playwright-python/issues/2228#issuecomment-1894955437

Could you check if you have a registry key like this configured?
