### ISSUE TITLE
Why does executing pytest --tracing on in some code not produce the trace.zip file and also delete the existing test-results directory

### ISSUE THREAD

**Issue by aiyisuizhongqi** [microsoft/playwright-python#2365]
### Please do not submit this issue.

- [ ] I understand

**Comment by aiyisuizhongqi** [comment]
import base64
from playwright.sync_api import sync_playwright

def test_download():
    with sync_playwright() as p:
        browser = p.chromium.launch()
        context = browser.new_context()
        page = context.new_page()
        page.goto("https://www.baidu.com")

        screenshot_bytes = page.screenshot()
        print(base64.b64encode(screenshot_bytes))

        context.close()  # 上下文关闭时保存录屏
        browser.close()

**Comment by aiyisuizhongqi** [comment]
import base64
from playwright.sync_api import sync_playwright

def test_download():
    with sync_playwright() as p:
        browser = p.chromium.launch()
        context = browser.new_context()
        page = context.new_page()
        page.goto("https://www.baidu.com")

        screenshot_bytes = page.screenshot()
        print(base64.b64encode(screenshot_bytes))

        context.close()  
        browser.close()

**Comment by aiyisuizhongqi** [comment]
no

**Comment by aiyisuizhongqi** [comment]
What should I do in the above code when I just want to track the use cases that failed

**Comment by aiyisuizhongqi** [comment]
ok

**Comment by aiyisuizhongqi** [comment]
I still not understand

**Comment by mxschmitt** [comment]
--tracing does only affect the context which pytest-playwright provides you.

Folding into https://github.com/microsoft/playwright-pytest/issues/209
