### ISSUE TITLE
[Docs]: How to run demo code step by step?

### ISSUE THREAD

**Issue by givingwu** [microsoft/playwright-python#2386]
### Page(s)

https://github.com/microsoft/playwright-python/tree/main/examples/todomvc

### Description

Could you guys add a README to run this demo?

**Comment by mxschmitt** [comment]
Examples follow best-practises, which means that the [normal getting-started](https://playwright.dev/python/docs/intro) works for them.

Since these examples are not referenced from somewhere in our official documentation as today, we will refrain from (verbose) documentation as of today.
