### ISSUE TITLE
playwright1.42,chrome is being controlled by automated testing software

### ISSUE THREAD

**Issue by chenpengyu1990** [microsoft/playwright-python#2388]
### Please do not submit this issue.

- [ ] I understand

**Comment by chenpengyu1990** [comment]
<img width="811" alt="2222" src="https://github.com/microsoft/playwright-python/assets/46602065/ad23d6ad-2bf7-4f8d-8ef1-1930523ad96d">
![111](https://github.com/microsoft/playwright-python/assets/46602065/3c8b1ed0-5ba4-4046-b5c9-b60eb9fa8be4)
请求各位帮助，怎么隐藏chrome正受到自动测试软件的控制？

**Comment by chenpengyu1990** [comment]
<img width="811" alt="1111" src="https://github.com/microsoft/playwright-python/assets/46602065/acd80392-beba-470d-81ae-a6347e1f0e9b">
<img width="811" alt="2222" src="https://github.com/microsoft/playwright-python/assets/46602065/f89001b0-e578-4f32-b8d2-2cebb12a1f5e">
请教各位大师如何隐藏或去除chrome正受到自动测试软件的控制？

**Comment by mxschmitt** [comment]
This does not look like either a feature request or a bug report. It's intentional that this info-bar is being shown.
