### ISSUE TITLE
Unable to pass Dynamic values inside a Locator picked using Playwright Inspector

### ISSUE THREAD

**Issue by yeswanth-ds** [microsoft/playwright-python#2394]
### Version

1.41

### Steps to reproduce

Example steps (replace with your own):
1. I Captured a Locator using Playwright inspector 
2. I need to pass values inside that locator so that I can use that locator for dynamic values
3.I'm not able to do that
This is the locator captured using Playwright Inspector-
locator("tbody").filter(has_text=re.compile(r"^AU Health Insurance$")).get_by_role("cell")

### Expected behavior

I need to pass values inside this locator how to do that ? the one which I tried is not working
page.locator("tr").filter(has_text=re.compile(r"^datadictvalue["C_PLAN_TYPE"]")).get_by_role("cell")

### Actual behavior

page.locator("tr").filter(has_text=re.compile(r"^datadictvalue["C_PLAN_TYPE"]")).get_by_role("cell") - not sure how to pass value inside this locator

### Environment

```Text
OS - Windows
```

**Comment by mxschmitt** [comment]
You can do something like this:

```python
import re
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()
    page.goto('http://example.com')
    page.set_content("<table><tr><td>C_PLAN_TYPE</td></tr><tr><td>foobar</td></tr></table>")
    
    datadictvalue = {
       "C_PLAN_TYPE": "foobar",
    }
    page.locator("tr").filter(has_text=re.compile(rf"^{datadictvalue['C_PLAN_TYPE']}")).get_by_role("cell")
    
    browser.close()
```

See here for more information: https://stackoverflow.com/questions/6930982/how-to-use-a-variable-inside-a-regular-expression/55810892#55810892
