### ISSUE TITLE
[Bug]: Zombie thread problem

### ISSUE THREAD

**Issue by simonli866** [microsoft/playwright-python#2397]
### Version

1.33.0

### Steps to reproduce

There is a parent process in the container that starts the playwright script, exits or throws an exception, resulting in a zombie script

### Expected behavior

No zombie thread is generated

### Actual behavior

![图片](https://github.com/microsoft/playwright-python/assets/22612182/7ab9b383-8540-479f-81bd-cfc7f43932ab)

### Environment

```Text
- Operating System: [Ubuntu 20.04.3 LTS]
- CPU: [x86_64]
- Browser: [Chromium, Firefox]
- Python Version: [Python 3.8.10]
- Other info: The script is hosted on an automation platform to run the playwright script through a startup subprocess
```

**Comment by simonli866** [comment]
![图片](https://github.com/microsoft/playwright-python/assets/22612182/06f026d5-8069-43ee-919c-459f1862f582)

**Comment by mxschmitt** [comment]
Are you running inside a Docker container? You need to pass [`--init`](https://docs.docker.com/reference/cli/docker/container/run/#init) there: https://playwright.dev/docs/ci#docker

**Comment by mxschmitt** [comment]
Closing as per above.
