### ISSUE TITLE
How to get the error type Console in the browser?

### ISSUE THREAD

**Issue by rainbol** [microsoft/playwright-python#2399]
### Please do not submit this issue.

- [X] I understand

**Comment by rainbol** [comment]
I want to get the error type in the browser by playwright, the type is this: Uncaught TypeError.
<img width="590" alt="image" src="https://github.com/microsoft/playwright-python/assets/35483055/c32a6b38-93d6-485e-9e39-9820a2459396"
<img width="590" alt="_76562598-ed2e-4831-aeb7-7b2facfc176d" src="https://github.com/microsoft/playwright-python/assets/35483055/7fda60a5-ffa7-4912-a5ee-660661810aef">

**Comment by mxschmitt** [comment]
```python
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()
    page.goto('http://playwright.dev')
    page.on("pageerror", lambda error: print("Page error: ", error.name, ",", error.message, ",",  error.stack))
    page.evaluate("""
        setTimeout(() => {
            const error = new Error('error message');
            error.name = 'CustomError';
            throw error;
        }, 0);
    """)
    page.wait_for_timeout(1000)
    browser.close()
```

**Comment by rainbol** [comment]
Thank you very much, it has been solved.
