### ISSUE TITLE
playwright-python's autocomplete support in vscode

### ISSUE THREAD

**Issue by b3wsh** [microsoft/playwright-python#240]
I use the examplel code of the project, but vscode can not list the autocomplete hints.
**Env**
*python*: 3.8
*vscode*:September 2020 (version 1.50)

```
import asyncio
from playwright import async_playwright
import time


async def main():
    async with async_playwright() as p:
        browser_type = p.chromium
        browser = await browser_type.launch(headless=False, args=['--start-maximized'])
        page = await browser.newPage()

        await page.goto('http://whatsmyuseragent.org/')
        await page.screenshot(path=f'example-{browser_type.name}.png')

        await asyncio.sleep(100)
        await browser.close()

asyncio.get_event_loop().run_until_complete(main())

```
And I see the launch method's return type hints is a specific string, is it be supported by vscode?

![image](https://user-images.githubusercontent.com/15774806/96423370-d4527700-122b-11eb-872f-64da9a65a9b8.png)

**Comment by mxschmitt** [comment]
Could you check if auto completion is available when you hover over it? Its probably an upstream issue if the hints get showed when you hover over it but not shown when you use normal auto completion: https://github.com/microsoft/vscode-python/issues/13185

**Comment by b3wsh** [comment]
Thank you @mxschmitt , I have rechecked, this problem may be caused by vscode plugins.
Only when I use **Pylance** as Python Language Server, autocomplete will work ok, and others failed.
![image](https://user-images.githubusercontent.com/15774806/96428096-f64ef800-1231-11eb-8cef-38216051c2a8.png)
