### ISSUE TITLE
[Bug]: set_checked() doesn't work on checkbox element of a slider

### ISSUE THREAD

**Issue by mandras73** [microsoft/playwright-python#2400]
### Version

1.40,0

### Steps to reproduce

1. Have a slider html element with the following structure:
```
<label class="ui-switch">
   <input type="checkbox" id=":chb" tabindex="0" class="form-control">
   ::before
   </input>
   <span class="slider round">
      <div>
      ::before
      </div>
   </span>
</label>
```

2. Locate the element like
`my_checkbox = self.page.locator("[id=':chb']")`

3. Execute code
`my_checkbox.set_checked(False)`

### Expected behavior

Slider state set to False

### Actual behavior

```
self = <playwright._impl._connection.Channel object at 0x0000017B44150090>
method = 'uncheck'
params = {'selector': "[id=':chb']", 'strict': True}
return_as_dict = False

    async def inner_send(
        self, method: str, params: Optional[Dict], return_as_dict: bool
    ) -> Any:
        if params is None:
            params = {}
        callback = self._connection._send_message_to_server(
            self._object, method, params
        )
        if self._connection._error:
            error = self._connection._error
            self._connection._error = None
            raise error
        done, _ = await asyncio.wait(
            {
                self._connection._transport.on_error_future,
                callback.future,
            },
            return_when=asyncio.FIRST_COMPLETED,
        )
        if not callback.future.done():
            callback.future.cancel()
>       result = next(iter(done)).result()
E       playwright._impl._errors.TimeoutError: Timeout 30000ms exceeded.
```

### Additional context

set_checked() only works when I'm adding the span after the id for the locator, like
`my_checkbox = self.page.locator("[id=':chb'] + span")`

### Environment

```Text
- Operating System: [Windows11]
- Browser: [Chromium]
- Python Version: [3.11.2]
```

**Comment by mxschmitt** [comment]
I tried the following which works for me:

```python
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()
    page.goto('http://example.com')
    page.set_content("""
        <label class="ui-switch">
            <input type="checkbox" id=":chb" tabindex="0" class="form-control">
            <span class="slider round">
                <div>
                ::before
                </div>
            </span>
        </label>
    """)
    my_checkbox = page.locator("[id=':chb']")
    my_checkbox.set_checked(False)
    browser.close()
```

**Comment by mandras73** [comment]
Thank you Max, yes, this is strange... when setting the content it's working.
But when I'm using my live page, it doesn't...
Do you have any idea how could I debugging the root cause?
My slider is visible, enabled and nothing blocks it on the page

**Comment by mandras73** [comment]
Here is another example with the bug, please execute and check the results:

`from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()
    page.goto('https://codepen.io/kanpeki/pen/RLboWN')
    my_checkbox = page.frame_locator("iframe[name='CodePen']").locator("[id='slideThree']")
    my_checkbox.highlight()
    my_checkbox.set_checked(True)
    browser.close()`

**Comment by mxschmitt** [comment]
Have you tried using [Codegen](https://playwright.dev/python/docs/codegen-intro#running-codegen) to generate a locator? A user does not click in this scenario on the `input` element itself, the user instead clicks on the label. The `input` element itself is not visible in this case. So you can do something like this (generated by [Codegen](https://playwright.dev/python/docs/codegen-intro#running-codegen)):

```python
import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://codepen.io/kanpeki/pen/RLboWN")
    page.frame_locator("iframe[name=\"CodePen\"]").get_by_title("Slide 3").locator("label").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)

```

**Comment by mandras73** [comment]
I would say, the fact that set_checked() cannot be used on hidden (or display: none) input, is an unexpected limitation.
Is it possible to remove the verification of the element visibility from playwright?
As you can see, we have scenarios like this, when input field is not visible but would like to control over the set_checked()

**Comment by mxschmitt** [comment]
Its possible! You can set `force=True`:

```python
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch(headless=False)
    page = browser.new_page()
    page.goto('https://codepen.io/kanpeki/pen/RLboWN')
    my_checkbox = page.frame_locator("iframe[name='CodePen']").locator("[id='slideThree']")
    my_checkbox.highlight()
    my_checkbox.set_checked(True, force=True)
    browser.close()
```

See here: https://playwright.dev/docs/actionability#forcing-actions

**Comment by mandras73** [comment]
Thank you!
