### ISSUE TITLE
How to locate the chromewebstore's confirm dialog?

### ISSUE THREAD

**Issue by grayguest** [microsoft/playwright-python#2404]
Hello, very thank to your effort on playwright, I recently want to auto-setup the chrome extension from the chromewebstore, but I found the chromewebstore's confirm dialog can not be located
![image](https://github.com/microsoft/playwright-python/assets/10668340/c6fd06ac-5ea1-4a0b-addd-6a895a3327d3)

I use below code
```python
def handle_dialog(dialog):
    print(f"Dialog message: {dialog.message}")
    if "Add extension" in dialog.message or "添加扩展程序" in dialog.message:
        dialog.accept()  # 如果对话框是添加扩展，选择接受

def handle_popup(popup):
    popup.wait_for_load_state()
    print(popup.title())

if __name__ == "__main__":
   with sync_playwright() as playwright:
        browser = playwright.chromium.connect_over_cdp(debug_url, slow_mo=10000)
        context = browser.contexts[0]
        context.on("dialog", handle_dialog)
        context.on("popup", handle_popup)
        context.on("page", lambda page: print(f"Page: {page.url}"))
        new_page = context.new_page()
        new_page.on("dialog", handle_dialog)
        new_page.on("popup", handle_popup)
        new_page.on("page", lambda page: print(f"Page: {page.url}"))
        new_page.goto('https://chromewebstore.google.com/detail/camppjleccjaphfdbohjdohecfnoikec')
        new_page.get_by_text("Add to Chrome").click()
        # then I can not find the page include "Add extension" button, although I try traverse the whole pages in context, still not find it.
```

Neither of  function handle_dialog and handle_popup are triggered.

By the way, I don't want to install chrome extension use chrome startup cli command, because I want to persist the storage of this extension and related data, and automatic updates.

**Comment by mxschmitt** [comment]
This is not possible and outside of the scope for the project.

What you can do instead is installing the unpacked version: https://playwright.dev/python/docs/chrome-extensions
