### ISSUE TITLE
Can't install in Python 3.9.0 on Win 8.1 Pro

### ISSUE THREAD

**Issue by RussellJQA** [microsoft/playwright-python#242]
I tried to install Playwright in CPython 3.9.0 on Microsoft Windows 8.1 Professional.

I did this by typing:
• pip install playwright
in a new Python virtual environment (in a terminal within VS Code 1.50.1).

Doing so gave me a fatal error:
	c:\python39\include\pyconfig.h(201): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit code 2

The installation is apparently looking for some Visual Studio 14.0 (VS 2015) files.

On Playwright's PyPi.org page (https://pypi.org/project/playwright/):
• The Meta section says:
	Requires: Python >= 3.7
• The 'Programming Language' section says:
	Python::3
	Python::3.7
	Python::3.8
	
So it seems that maybe PyPi hasn't yet been updated with the binaries needed to install Playwright in Python 3.9.

I've attached the full [output from 'pip install playwright'.txt](https://github.com/microsoft/playwright-python/files/5405098/Output.from.pip.install.playwright.txt)

**Comment by mxschmitt** [comment]
Hi, can you try to install wheel before you install Playwright for Python?

```
pip install wheel
pip install playwright
```

**Comment by RussellJQA** [comment]
Thanks for your help. I just tried:
```
pip install wheel
pip install playwright
```
but I still got:
```
c:\python39\include\pyconfig.h(201): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit code 2
```

Again, I've attached the full [Output from pip install playwright (after first pip-installing wheel).txt](https://github.com/microsoft/playwright-python/files/5433513/Output.from.pip.install.playwright.after.first.pip-installing.wheel.txt)

**Comment by mxschmitt** [comment]
Hi, it has something to do with your Python installation. Maybe these help you:
- https://stackoverflow.com/questions/23691564/running-cython-in-windows-x64-fatal-error-c1083-cannot-open-include-file-ba
- https://stackoverflow.com/questions/44437357/fatal-error-c1083-cannot-open-include-file-basetsd-h

**Comment by RussellJQA** [comment]
Thanks, @mxschmitt.

I hadn't realized, but the problem is not with playwright itself, but with greenlet (1 of playwright's dependencies). Playwright doesn't directly use any native Windows code, but greenlet does. So it's actually greenlet that needs the Visual Studio build files.

I checked the available download files for greenlet on PyPi (https://pypi.org/project/greenlet/#files). There I can see that they have a Linux wheel for Python 3.9, but their latest Windows wheels are for Python 3.8.

So, I opened a greenelet issue "PyPi needs Windows wheels for Python 3.9" (https://github.com/python-greenlet/greenlet/issues/200).

And I would think this issue can be closed.

**Comment by pavelfeldman** [comment]
Looks like 1.0a has binaries published via https://github.com/python-greenlet/greenlet/issues/200#issuecomment-731123526. So we can try rolling to it.

**Comment by RussellJQA** [comment]
Great! Thanks!

**Comment by mxschmitt** [comment]
@RussellJQA since we don't pin the greenlet version you should be able to try it out with:

```
pip install playwright
pip install greenlet==1.0a1
```

Would be great if you could test it and confirm if its working or not. (they released it as a pre-version)

**Comment by RussellJQA** [comment]
I just tried:
``` python
    pip install playwright  # That gave me the same error as before
    pip install greenlet==1.0a1 # That worked
    pip install playwright # That worked
```

Here's the output from 'pip install playwright':
```
Collecting playwright
  Using cached playwright-0.162.1-py3-none-win_amd64.whl (54.5 MB)
Requirement already satisfied: typing-extensions in c:\users\rljohnson\documents\gith
site-packages (from playwright) (3.7.4.3)
Requirement already satisfied: pyee>=8.0.1 in c:\users\rljohnson\documents\github\pyt
ackages (from playwright) (8.1.0)
Requirement already satisfied: greenlet>=0.4.17 in c:\users\rljohnson\documents\githu
ite-packages (from playwright) (1.0a1)
Installing collected packages: playwright
Successfully installed playwright-0.162.1
```
