### ISSUE TITLE
[Feature]: allow reuse of JavaScript functions

### ISSUE THREAD

**Issue by fasiha** [microsoft/playwright-python#2434]
### 🚀 Feature Request

I'd love to be able to reuse Playwright functions and modules we've written in JavaScript (i.e., using `Page` and `expect`) in playwright-python

### Example

I have a bunch of JavaScript functions that we use in JavaScript Playwright, e.g., `myTests.js`:
```js
import { test, expect } from '@playwright/test';

export async function clickTest(page => {
  await page.getByRole('link', { name: 'Get started' }).click();
  await expect(page.getByRole('heading', { name: 'Installation' })).toBeVisible();
});
```

It'd wonderful to be able to reuse those functions in playwright-python somehow. Maybe something like:
```py
from playwright.sync_api import sync_playwright, nonexistentImportJavaScriptModule

my_tests = nonexistentImportJavaScriptModule('path/to/myTests.js')

with sync_playwright() as p:
    for browser_type in [p.chromium, p.firefox, p.webkit]:
        browser = browser_type.launch()
        page = browser.new_page()
        page.goto('http://playwright.dev')
        my_tests.clickTest(page)  # ←----------------------------------- new
        page.screenshot(path=f'example-{browser_type.name}.png')
        browser.close()
```
using a completely random example API that could "import" JavaScript code and execute it.

### Motivation

Being able to leverage pre-existing JavaScript Playwright code could make it easier for polyglot teams to adopt playwright-python, enabling code reuse as well as enabling Python devs to leverage tests written by JavaScript devs.

I suggest this also because Robot Browser allows you to import CommonJS modules via `jesextension` and use them in tests written in the Robot language (see [docs](https://marketsquare.github.io/robotframework-browser/Browser.html#Extending%20Browser%20library%20with%20a%20JavaScript%20module)). This works because Robot uses Node.js Playwright, but I can totally see that, if there's *no* JavaScript runtime present in playwright-python, this is a no-go, so please feel free to close this.

**Comment by mxschmitt** [comment]
This seems outside of the scope for Playwright for Python. If you want to use JavaScript, we recommend using our Node.js version: https://playwright.dev/docs/intro
