### ISSUE TITLE
[Question]The content.pages method cannot retrieve all pages

### ISSUE THREAD

**Issue by Liu-boyu** [microsoft/playwright-python#2446]
### Please do not submit this issue.

- [X] I understand

**Comment by Liu-boyu** [comment]
When I open the browser using playwright.chromium. launch_persistent_context, I use page. go to open a URL for example https://111.html To manually open a URL for the tag page https://222.html The tag page does not have a URL when calling context. pages https://222.html What is the reason for the page, and how can I obtain the second page?

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
