### ISSUE TITLE
[Bug]: Apple App store link is not opening in a new tab while clicking a link [mobile: iPhone 13]

### ISSUE THREAD

**Issue by sureshbexpleo** [microsoft/playwright-python#2447]
### Version

1.43.0

### Steps to reproduce

    from playwright.sync_api import Page, Playwright, sync_playwright
    playwright = sync_playwright().start()    
    browser = playwright.chromium.launch(headless=False)
    iphone_13 = playwright.devices['iPhone 13']
    default_context = browser.new_context(
        **iphone_13,
    )
    page = default_context.new_page()
    page.goto("https://zerodha.com/products/")
    ele=page.locator("//*[@id='kite']/div/div/div[2]/div[2]/a[2]")
    ele.click()
    page.wait_for_timeout(5000)

### Expected behavior

![image](https://github.com/microsoft/playwright-python/assets/125460291/b53b84f3-7e44-4523-b09e-5b06358ecdc4)
App store url should be opened with new tab after clicking the link

### Actual behavior

![image](https://github.com/microsoft/playwright-python/assets/125460291/32208ea9-ff2b-4297-b065-ca1233e0e75f)
blank new tab opened after clicking the link

### Additional context

this is working fine in chromium desktop, issue only on mobile emulation.
device: iPhone 13

### Environment

```Text
- Operating System: Windows 10
- CPU: x64
- Browser: Chromium(Mobile)
- Python Version: 3.10
- Other info: Mobile - iPhone 13
```

**Comment by mxschmitt** [comment]
This is about an external url handler: `itms-appss://apps.apple.com/in/app/kite-zerodha/id1449453802`. Folding into https://github.com/microsoft/playwright/issues/11014.
