### ISSUE TITLE
[Bug]: Running with the synchronization method reports an error

### ISSUE THREAD

**Issue by qingdaoqin** [microsoft/playwright-python#2450]
### Version

1.35.0

### Steps to reproduce

An exception occurs when running a test using the synchronization method，But the console outputs this exception during the run:ERROR    asyncio:base_events.py:1591 Task exception was never retrieved
future: <Task finished coro=<WaitHelper.reject_on_timeout.<locals>.reject() done, defined at D:\sync\venv\lib\site-packages\playwright\_impl\_wait_helper.py:83> exception=CancelledError()>
concurrent.futures._base.CancelledError

### Expected behavior

testcase is pass or flase

### Actual behavior

ERROR    asyncio:base_events.py:1591 Task exception was never retrieved
future: <Task finished coro=<WaitHelper.reject_on_timeout.<locals>.reject() done, defined at D:\sync\venv\lib\site-packages\playwright\_impl\_wait_helper.py:83> exception=CancelledError()>
concurrent.futures._base.CancelledError

### Environment

```Text
- Operating System: [Windows 22H2]
- CPU: [i5 7300HQ]
- Browser: [Chromium]
- Python Version: [3.9]
- Other info:
```

**Comment by mxschmitt** [comment]
Would it be possible to share a minimal reproduction with us?

Also I recommend to try out latest Playwright.

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
