### ISSUE TITLE
[Bug]: Images do not print when performing print-to-pdf

### ISSUE THREAD

**Issue by mitchchristow** [microsoft/playwright-python#2456]
### Version

1.44.0

### Steps to reproduce

Wrote a python script to print web pages to pdf. Used the following script below to generate the pdf:

```
from playwright.async_api import async_playwright
import asyncio
import re

targeturl = '' #add the web site that you want to print

async def main():
async with async_playwright() as p:
browser = await p.chromium.launch(headless=True)
context = await browser.new_context(
viewport={"width": 2550, "height": 3300},
device_scale_factor=1,
)
page = await context.browser.new_page()
await page.goto(targeturl)
title = await page.title()
saveTitle = re.match("^[^|]*", title).group(0)
pdfPath = "./" + saveTitle + ".pdf"
await page.emulate_media(media="screen")
await page.wait_for_load_state("networkidle")
await page.pdf(path=pdfPath, format="Letter", landscape=False, print_background=True)
await browser.close()

asyncio.run(main())
```

### Expected behavior

I expected to see all artifacts in the pdf document, including images. 

### Actual behavior

No images were included in the pdf. Where the images were supposed to be, there were only blank areas. 

### Environment

Operating system: Windows 10
Python 3.11.8
playwright 1.44.0
Chromium 125.0.6422.26 (playwright build v1117)

**Comment by yury-s** [comment]
This is the same as https://github.com/microsoft/playwright-java/issues/469. There seems to be a bug here indeed, but printing to pdf is not a priority for Playwright project at this point, so I'm closing this request as we are not planning to work on this.
