### ISSUE TITLE
Element location is not happening in the microsoft bookings page.

### ISSUE THREAD

**Issue by Aiswarya1794** [microsoft/playwright-python#2471]
### Please do not submit this issue.

- [X] I understand
```[tasklist]
### Tasks
```

**Comment by Aiswarya1794** [comment]
When clicking a button in chat section of ms teams it is navigating to the ms bookings page and need to enter details in bookings page , even from user side user is able to see the ms bookings page playwright locator is still in the chat section not on the bookings page , so unable to locate the elements in bookings page. Is it possible to resolve this issue with playwright python?

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!

**Comment by Aiswarya1794** [comment]
We have a adaptive card in the ms-teams chat section and on clicking the adaptive card it is redirecting to the microsoft bookings page and do the operations in the bookings page. But what happening now is the bookings page is opening and user is able to see that page, but the program is searching for the element in chat section instead of bookings page in the nearest tab.
