### ISSUE TITLE
[Bug]: Edge case `Locator.click + Page.wait_for_url` results in Timeout error. 

### ISSUE THREAD

**Issue by dhsh-checkmk** [microsoft/playwright-python#2481]
### Version

1.44

### Steps to reproduce

Hi,

I am using playwright with the following configuration
* headed mode
* chromium browser
* default viewport size

Attached is an image corresponding to the issue. 
![18094](https://github.com/microsoft/playwright-python/assets/156444493/22e1e490-e45f-43f4-a44a-0ab907891f65)

Describing the image a bit
* Red box - signifies the viewport
* Red ovals - signifies web-elements/Locators, accessible using Page.get_by_role(role="link", name="name")
* Each red-oval corresponds to a web-element, which is present inside of a column of a table-row
```
<table>
      <tbody>
            <tr><td><a href="relative-url">name</a></td><td>...</td>...</tr>
            ...
```
* There are other web-elements/Locators which are completely outside of the viewport and NOT visible to the naked eye.
* **Please note** - a red oval corresponding to Locator: `Page.get_by_role(role="link", name="#16750")`. It is special because the **row** corresponding to the web-element is **partially visible** but the **locator** is **NOT**.

Commands executed

```
...
page = context.new_page()
page.go("url-of-screenshot")
loc = page.get_by_role(role="link", name="#16750")  # web-element's row is partially visible in the viewport.
loc.focus()
loc.click()
page.wait_for_url("relative-url", wait_until="load")
```

### Expected behavior

I expect the following

* `loc.focus()` should lead to a scrolling of the page so that the `loc` is within the viewport and visible to naked eye. 
* `loc.click()` should lead to a navigation event, which leads to a new web-page.

### Actual behavior

I observed the following for the **partially visible** web-element
* `loc.focus()` did not lead to any scrolling. Contents of the viewport remain the same, `loc` is still partially visibile to viewport.
* `loc.click() + page.wait_for_url()` lead to a `playwright.sync_api.Timeout` exception. `loc.click()` did not lead to new page.

Also observed for web-elements **outside of viewport** and **inside of viewport**
* `loc.click() + page.wait_for_url(...)` navigates to a new page without a `Timeout` error, as expected

### Environment

```Text
- Operating System: [Ubuntu 22.04]
- CPU: [amd64]
- Browser: [Chromium]
- Python Version: [3.12]
```

**Comment by dhsh-checkmk** [comment]
Any help here would be appreciated, looking forward to hearing from you.

**Comment by mxschmitt** [comment]
We unfortunately need clear reproduction steps, with something we can run locally - we can't debug screenshots. I'll close it in the meantime - feel free to re-file with something we can `git clone`. Thank you for your understanding.
