### ISSUE TITLE
[Feature]: Add install.sh script for Unix based

### ISSUE THREAD

**Issue by BornSaint** [microsoft/playwright-python#2489]
### 🚀 Feature Request

```sh
git clone https://github.com/kaliiiiiiiiii/undetected-playwright-python &&\
cd undetected-playwright-python &&\
python -m pip install -r local-requirements.txt &&\
python build_patched.py
```

### Example

chmod +x ./install.sh
./install.sh
### Motivation

Make install great again

**Comment by mxschmitt** [comment]
Looks like you filed the issue in the wrong repository and it should be https://github.com/kaliiiiiiiiii/undetected-playwright-python instead.
