### ISSUE TITLE
I cannot run playwright with the codegen option for python

### ISSUE THREAD

**Issue by alexfilothodoros** [microsoft/playwright-python#250]
Hello,

I want to be able to use the codegen option for python.
I have done the following steps. 

pip install playwright
python -m playwright install
python -m playwright codegen
And then I get the warning " Run "python -m playwright install" to complete installation".

I would expect that after the command ```python -m playwright codegen``` I should be able to record my actions on a browser and not be asked again to run ```python -m playwright install``` because that leads to an infinite loop where i will just be running these two commands.

Catalina 10.15.7
Python 3.7.3
Is this some issue or am I doing something wrong?
Thanks
Alex

This is from my terminal.

```
alex> pip install playwright

Requirement already satisfied: playwright in ./anaconda3/lib/python3.7/site-packages (0.142.3)
Requirement already satisfied: pyee>=8.0.1 in ./anaconda3/lib/python3.7/site-packages (from playwright) (8.0.1)
Requirement already satisfied: greenlet>=0.4.17 in ./anaconda3/lib/python3.7/site-packages (from playwright) (0.4.17)
Requirement already satisfied: typing-extensions in ./anaconda3/lib/python3.7/site-packages (from playwright) (3.7.4.3)
alex> python -m playwright install

Installing the browsers...
Playwright is now ready for use
alex> python -m playwright codegen

Run "python -m playwright install" to complete installation
alex> python -m playwright install

Installing the browsers...
Playwright is now ready for use
alex> python -m playwright codegen
Run "python -m playwright install" to complete installation```

**Comment by arjunattam** [comment]
Thanks for the report, @alexfilothodoros. Codegen was added in playwright==0.150, and it seems that you have v0.142.3. I would recommend forcing an upgrade:

```
pip install playwright --no-cache-dir --force-reinstall
```

I'll close this for now but feel free to comment and tell us if it worked for you.
