### ISSUE TITLE
[Bug]: Codegen stuck due to security settings

### ISSUE THREAD

**Issue by balazs-ita-epam** [microsoft/playwright-python#2503]
### Version

Playwright 1.39, Python 3.12, pytest

### Steps to reproduce

Hi,

we changed our application in a way that it only works in Chrome / chromium when 

`chrome://flags/#block-insecure-private-network-requests`

is disabled. 

In our Python - Playwright test automation framework, programmatically disabling this browser option work fine, tests are running, but does NOT work when starting `codegen chromium `manually from PyCharm IDE.

The problem is whenever 
1. I start "playwright codegen" in PyCharm terminal,
2. then I DISABLE this feature in the appearing chromium,
3. then selecting Restart option will restart chromium (as restart is needed for changes)
4. When I start again manually with "playwright codegen" in terminal, codegen chromium starts again with this setting enabled by default.

**So essentially user is being locked out of the great codegen feature of playwright.**

I do know there is a solution that works in the framework programmatically, but how to make it work manually from PyCharm terminal?

Command

`playwright codegen --browser=chromium --args="--disable-features=BlockInsecurePrivateNetworkRequests"`

does NOT work, constantly getting CORS errors. 

### Expected behavior

I can start codegen playwright with cli arguments

### Actual behavior

Not possible to use codegen playwright because of errors.

### Environment

```Text
macOS Sonoma, MBP
```

**Comment by mxschmitt** [comment]
> When I start again manually with "playwright codegen" in terminal

This is expected, every time you run codegen, its a new browser profile. So the changes do not persist.

> playwright codegen --browser=chromium --args="--disable-features=BlockInsecurePrivateNetworkRequests"

This CLI flag is not supported.

---

For your use-case it seems the most reasonable to run ["Codegen with a custom setup"](https://playwright.dev/python/docs/codegen#record-using-custom-setup), e.g. the following should work for you:

```py
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    # Make sure to run headed.
    context = p.chromium.launch_persistent_context("./profile", headless=False)

    # Pause the page, and start recording manually.
    page = context.pages[0]
    page.pause()
```

This will persist the profile. You can also always get a fresh one and pass args:

```py
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    # Make sure to run headed.
    browser = p.chromium.launch(headless=False, args=["--disable-features=BlockInsecurePrivateNetworkRequests"])

    # Pause the page, and start recording manually.
    page = browser.new_page()
    page.pause()
```

**Comment by balazs-ita-epam** [comment]
Thanks, by the end of the day I found the codegen with custom setup in the manual and it works fine starting from console.
