### ISSUE TITLE
[Confusion]: the page.click has misnamed argument, ie delay.

### ISSUE THREAD

**Issue by jedinik** [microsoft/playwright-python#2509]
### Version

all

### Steps to reproduce

Example steps (replace with your own):
1. Clone my repo at https://github.com/<myuser>/example
2. pip install -r requirements.txt
3. python test.py
4. You should see the error come up

### Expected behavior

This should be renamed to duration instead of delay. and any time waited before onmousedown should be calculated as delay.

### Actual behavior

![image](https://github.com/user-attachments/assets/030361a9-854c-4151-8431-8c76925a86de)

### Additional context

https://github.com/microsoft/playwright-python/blob/86c0191b6705ac387be7e1b9a161ab325e4865e8/playwright/_impl/_page.py#L763-L777

### Environment

```Text
- Operating System: [Ubuntu 22.04]
- CPU: [arm64]
- Browser: [All, Chromium, Firefox, WebKit]
- Python Version: [3.12]
- Other info:
```

**Comment by mxschmitt** [comment]
Thank you for the feedback. Its the time to wait between `mousedown` and `mouseup` in milliseconds. While the name could be improved, we are not comfortable with changing it, due to causing a breaking change to our customers. I'll close it for now since we don't plan to take action on it.
