### ISSUE TITLE
[Bug]:  playwright must  has no attribute '_playwright'  error  which playwright version >= 1.31.0

### ISSUE THREAD

**Issue by ENothing** [microsoft/playwright-python#2510]
### Version

>=1.31.0

### Steps to reproduce

When I run Playwright (1.45.1) on Win10, there won't be any errors. But when I switched to Ubuntu 18.04 and used Playwright (1.45.1), there would be a 'has no attribute' _playwright 'error. I want to find a higher version and lower it to 1.30.0. Ubuntu can run normally, and previous versions have reported this error

### Expected behavior

run normal

### Actual behavior

has no attribute '_playwright' 

### Environment

```Text
- Operating System: [Ubuntu 18.04]
- Python Version: [3.11]
- Other info:playwright>=1.31.0
```

**Comment by mxschmitt** [comment]
Ubuntu 18.04 is not supported anymore see [here](https://playwright.dev/docs/intro#system-requirements). We recommend 24.04.
