### ISSUE TITLE
[Bug]: Memory leak with any browsers and contexts used once

### ISSUE THREAD

**Issue by clemlesne** [microsoft/playwright-python#2511]
### Version

1.45.1

### Steps to reproduce

Reproduction steps:

1. Create a new browser
2. For each page we want to browse
    1. Create a context
    2. Open a page
    3. Go to the page
    4. Get a few properties (content, selectors, ...)
    5. Close the context

Code extract:

```python
async with async_playwright() as p:
    browser = await browser_type.launch()
    # iterate over links
    for link in [...]:
      # new context
      context = await browser.new_context(...)
      # new page
      page = await context.new_page()
      # abort requests for images, media, fonts, stylesheets
      await page.route(
          "**/*",
          lambda route: (
              route.abort()
              if route.request.resource_type in {"image", "media", "font", "stylesheet"}
              else route.continue_()
          ),
      )
      # go to link
      res = await page.goto(link)
      # skip if status is not 200
      if res.status != 200:
          return
      # get title, html, redirect, content, a_selectors
      title = await page.title()
      html = await (
          await page.wait_for_selector("html")
      ).inner_html()
      redirect = res.url
      content = await page.content()
      a_selectors = await page.get_by_role(
          "link",
          include_hidden=True,
      ).all()
      # close context
      await context.close()
```

### Expected behavior

RAM should be at constant usage all the time.

### Actual behavior

RAM increases at a high rate. Every 100 pages loaded (3-4 mins), the RAM used doubles. Up to more than 100 GiB of RAM on my development machine.

### Environment

```Text
Tested on:

- macOS
    - Operating System: macOS 15.0 Beta (24A5298h)
    - CPU: Apple Silicon
    - Browser: All
    - Python Version: 3.11
- Linux
    - Operating System: Ubuntu 24.04 LTS (Noble Numbat)
    - CPU: Intel x64
    - Browser: All
    - Python Version: 3.11
```

**Comment by mxschmitt** [comment]
Your reproduction is not self-contained and relies on external variables. Would it be possible to provide something which we can run locally? Looking at e.g. `links` or `new_context` options. That would help us a ton in order to figure out what is happening in your case.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.
