### ISSUE TITLE
[Docs]: The basic examples do not work

### ISSUE THREAD

**Issue by AceMurphy** [microsoft/playwright-python#2542]
### Page(s)

https://playwright.dev/python/docs/api/class-playwright
https://github.com/microsoft/playwright-python

### Description

The examples from these pages do not work ...

Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.

When I use the async, I get the following
RuntimeError: asyncio.run() cannot be called from a running event loop

Hard to try it if the basic steps don't work

**Comment by mxschmitt** [comment]
I put both of the snippets into a `test.py` file and they were running successful for me. How do you execute them? Maybe like the error suggests there is already a loop running?
