### ISSUE TITLE
[Bug]: about page.frame

### ISSUE THREAD

**Issue by jolly-xw** [microsoft/playwright-python#2566]
### Version

1.46.0

### description
After I executed `page.goto()` and `page.wait_for_load_state()`, I printed `page.main_frame.child_frames` once each, and the results from the two prints were different. I discovered this unintentionally, and it's not a sporadic occurrence. My code is below, and this time I provided testable URLs. I suspect it's because after `page.goto()` visits the URLs, the page is fixed in a certain state, in which not all iframe information can be obtained, and a specific action is needed to break this state, such as using `page.wait_for_load_state()` or `page.screenshot()`.
### code
```python
from playwright.sync_api import sync_playwright
playwright = sync_playwright().start()
browser = playwright["chromium"].launch(headless=False)
context = browser.new_context(viewport={'width': 1920, 'height': 1080})
page = context.new_page()
url = "https://mail.163.com/"
try:
    page.goto(url=url)
    print(page.main_frame.child_frames)
    page.wait_for_load_state('networkidle')
    print(page.main_frame.child_frames)
except Exception as err:
    print("goto err:", err)
page.close()
browser.close()
```

### Expected behavior

After executing `page.goto`, I can obtain all the iframe information through `page.main_frame.child_frames`.

### Actual behavior

Unexpected. Screenshots of the two printouts are as follows:
![image](https://github.com/user-attachments/assets/b5d2332e-edb5-41ed-8b15-9a260a1d73f8)

### Environment

```Text
- Operating System: [Windows 10]
- CPU: [intel]
- Browser: [Chromium]
- Python Version: [3.11]
- Other info:
```

**Comment by mxschmitt** [comment]
We strongly discourage using wait_for_load_state and `page.frame` API and recommend the use of [FrameLocators](https://playwright.dev/docs/api/class-framelocator) instead, have you considered using them? 

With them its easier to locate frames, use them inside `expect` calls and evaluate actions like click/fill. They will automatically retry if the element is not there etc.

**Comment by jolly-xw** [comment]
I have provided you with a reproducible code snippet, and I would like to know the reasons why it is not recommended to use `wait_for_load_state`.

**Comment by mxschmitt** [comment]
See from the [docs](https://playwright.dev/python/docs/api/class-page#page-wait-for-load-state):

> wait_for_load_state: Most of the time, this method is not needed because Playwright [auto-waits before every action](https://playwright.dev/python/docs/actionability).

> networkidle: DISCOURAGED wait until there are no network connections for at least 500 ms. Don't use this method for testing, rely on web assertions to assess readiness instead.

**Comment by jolly-xw** [comment]
How do you use web assertions in Python? Can you show me an example?

**Comment by mxschmitt** [comment]
See here: https://playwright.dev/python/docs/test-assertions

**Comment by jolly-xw** [comment]
Thanks
