### ISSUE TITLE
[Bug] `connect_over_cdp` unable to access pages in session

### ISSUE THREAD

**Issue by Ayan-Bandyopadhyay** [microsoft/playwright-python#2570]
In the Python library, `launch_persistent_context` automatically creates a page, but it's not accessible through the CDP connection, which shows 0 pages. The issue happens in both v1.46.0 and v1.47.0

Here is the script that shows the error

```
import os
import requests
from playwright.async_api import async_playwright
import asyncio


async def main():
    async with async_playwright() as pw:
        context_path = os.path.dirname(os.path.realpath(__file__)) + "/chrome_data"
        if os.path.exists(context_path):
            os.system(f"rm -rf {context_path}")
        context = await pw.chromium.launch_persistent_context(
            user_data_dir=context_path,
            args=["--remote-debugging-port=9222"],
            headless=False,
        )

        # Prints out 1
        print("Number of pages in context:", len(context.pages))
        info = requests.get("http://localhost:9222/json/list").json()
        ws_url = info[0]["webSocketDebuggerUrl"]

        browser2 = await pw.chromium.connect_over_cdp(ws_url)

        # Prints out 1
        print("Number of contexts: ", browser2.contexts)

        # Prints out 0
        print("Number of pages: ", len(browser2.contexts[0].pages))

        # This line throws an error
        page2 = await browser2.contexts[0].new_page()


asyncio.run(main())
```

_Originally posted by @Ayan-Bandyopadhyay in https://github.com/microsoft/playwright/issues/11442#issuecomment-2375151136_

**Comment by mxschmitt** [comment]
You need to do `/json/version` instead of `/json/list`. Doing like this works for me:

        info = requests.get("http://localhost:9222/json/version").json()
        ws_url = info["webSocketDebuggerUrl"]

Note: You can simplify it doing the following, we do it internally for you!

        browser2 = await pw.chromium.connect_over_cdp("http://localhost:9222")

I'll close it by that.
