### ISSUE TITLE
[Bug]: Please use the `--enable-chrome-browser-cloud-management` command line flag to enable it if you are not using the official Google Chrome build.

### ISSUE THREAD

**Issue by wm475390847** [microsoft/playwright-python#2571]
### Version

1.38.0

### Steps to reproduce

1. pip install -r requirements.txt
2. pytest --headed  test.py::A

### Expected behavior

open chrome 

### Actual behavior

  playwright._impl._errors.TargetClosedError: Target page, context or browser has been closed
E       Browser logs:
E       
E       <launching> /Users/wangmin/Library/Caches/ms-playwright/chromium-1097/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades,PaintHolding --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --enable-use-zoom-for-dsf=false --no-sandbox --user-data-dir=/var/folders/7y/0wz78v157rl9p8_k3k521w7c0000gn/T/playwright_chromiumdev_profile-ZjoJ5U --remote-debugging-pipe about:blank
E       <launched> pid=83955
E       [pid=83955][err] [83955:259:0926/100901.826116:ERROR:policy_logger.cc(156)] :components/enterprise/browser/controller/chrome_browser_cloud_management_controller.cc(161) Cloud management controller initialization aborted as CBCM is not enabled. Please use the `--enable-chrome-browser-cloud-management` command line flag to enable it if you are not using the official Google Chrome build.
E       [pid=83955][err] Received signal 11 SEGV_ACCERR 000100000008
E       [pid=83955][err]  [0x00012833e4c4]
E       [pid=83955][err]  [0x000128332cc4]
E       [pid=83955][err]  [0x00012833e414]
E       [pid=83955][err]  [0x000194d30184]
E       [pid=83955][err]  [0x0001a5cb99e0]
E       [pid=83955][err]  [0x0001a5b40634]
E       [pid=83955][err]  [0x0001a5cdba10]
E       [pid=83955][err]  [0x0001a5cdca64]
E       [pid=83955][err]  [0x0001962eeefc]
E       [pid=83955][err]  [0x00019637c394]
E       [pid=83955][err]  [0x00019653a234]
E       [pid=83955][err]  [0x00019653a0f8]
E       [pid=83955][err]  [0x00019653dfa4]
E       [pid=83955][err]  [0x000196478524]
E       [pid=83955][err]  [0x000194daefc4]
E       [pid=83955][err]  [0x000195260660]
E       [pid=83955][err]  [0x000195260070]
E       [pid=83955][err]  [0x00019525d7dc]
E       [pid=83955][err]  [0x00019b65229c]
E       [pid=83955][err]  [0x00019b650ad0]
E       [pid=83955][err]  [0x000199645f9c]
E       [pid=83955][err]  [0x000199646c94]
E       [pid=83955][err]  [0x000199646af8]
E       [pid=83955][err]  [0x0001996491e4]
E       [pid=83955][err]  [0x0001988f102c]
E       [pid=83955][err]  [0x0001988eee80]
E       [pid=83955][err]  [0x0001988ee9b4]
E       [pid=83955][err]  [0x000128347568]
E       [pid=83955][err]  [0x0001282a880c]
E       [pid=83955][err]  [0x0001283042b4]
E       [pid=83955][err]  [0x0001273709c8]
E       [pid=83955][err]  [0x000127784eb4]
E       [pid=83955][err]  [0x000127785c1c]
E       [pid=83955][err]  [0x00012778424c]
E       [pid=83955][err]  [0x000127784640]
E       [pid=83955][err]  [0x000124204df0]
E       [pid=83955][err]  [0x000100ca8aac]
E       [pid=83955][err]  [0x000194978274]
E       [pid=83955][err] [end of stack trace]
E       [pid=83955][err] [0926/100902.428339:WARNING:crash_report_exception_handler.cc(235)] UniversalExceptionRaise: (os/kern) failure (5)

### Environment

```Text
- Operating System: macos15.0
- CPU: [arm64]
- Browser: Chromium
- Python Version: [3.12]
- Other info:
```

**Comment by mxschmitt** [comment]
Before debugging this further, could you try it on latest Playwright? `v1.47.0`.

Also please try it with `channel = "chrome"` when launching the browser if it still reproduces and we need a reproduction script for that to triage this issue further. Ideally your `test.py`. Does it happen every time etc.

**Comment by kalibetre** [comment]
I faced a similar issue (with the exact error message), the same OS and hardware, but running via node.js. Updating to `v1.47.0` fixed the issue for me.

**Comment by mxschmitt** [comment]
Closing as per above.
