### ISSUE TITLE
[Feature]: Support for arm32 

### ISSUE THREAD

**Issue by 0jc1** [microsoft/playwright-python#2577]
### 🚀 Feature Request

Currently, pytest-playwright cannot not installed on 32 bit ARM. This feature would add support for this architecture. 

Related issue: https://github.com/microsoft/playwright/issues/20014

### Motivation

This will allow support for ARM32 machines like the Raspberry pi 4

**Comment by mxschmitt** [comment]
Playwright support Raspberrys with arm64 architecture, this includes Raspberry Pi 4, make sure to download the 64 bit version [here](https://www.raspberrypi.com/software/operating-systems/). arm32 is outside of the scope for Playwright.
