### ISSUE TITLE
Is it possible to install & run python-playwright in aws lambda?

### ISSUE THREAD

**Issue by burritoIand** [microsoft/playwright-python#258]
I'm curious if it's possible to install and run python-playwright in an aws lambda function?

I want to experiment with using playwright to render html in place of an existing solution and I'm not sure how to install the browser binaries since they are system level dependencies? Just curious if anyone had any pointers.

It would be really cool to be able to render html w/playwright in a lambda function (I also use python starlette).

**Comment by pavelfeldman** [comment]
It looks like https://www.npmjs.com/package/playwright-aws-lambda installs at least Chromium on AWS lambda and you could use launch(executablePath=) to use the browser it installs.

**Comment by pavelfeldman** [comment]
Closing as a part of triage, we need more details in order to be able to help, please feel free to open a new issue!
