### ISSUE TITLE
How to wait for navigation or detect navigation is performing?

### ISSUE THREAD

**Issue by agn-7** [microsoft/playwright-python#2585]
After clicking or typing with submit, most of the time we are witnessing navigation. Is there any method to detect that or such a method like `page.wait_for_navigation()`?

I have written the following code (this is a piece of my code):

```python
def click(self, node: DOMNode):
    try:
        with self.page.expect_navigation(timeout=5000):
            self.page.mouse.click(*node.center)
    except TimeoutError:
        log.warning("Navigation timeout: Expected navigation after clicking!")

    self.wait_for_idle()  # executes a JS code to wait for DOM to be idle
```

I could perform something for waiting till the navigation is finished by `with self.page.expect_navigation(timeout=5000):`, however, sometimes, there is no navigation after clicking like accepting the consent cookie pop up. In this way, I had to add a `try-except` and wait for that 5 secs static timeout which is not preferred.

**Comment by mxschmitt** [comment]
Since you seem to know when you want to wait for a navigation to happen or not, why don't you e.g. add a parameter to your `click` method which says if it should wait for the navigation or not?

Usually if you are using Playwright's Locator actions e.g `page.locator(...).click() you never need to wait for idle or navigation, we do it for you internally including retries.

**Comment by mxschmitt** [comment]
> But if after a click it results in a navigation to another page, I would need to wait for DOM to be idle to have the possibility of scrapping the new page content.

Waiting for navigation is not a clear sign that the website has been fully loaded. It might do asynchronous http requests etc. In such cases we recommend waiting for a specific element:

    page.locator("....").wait_for()

Closing as per above.

**Comment by agn-7** [comment]
@mxschmitt I already said the pages are dynamic so there is no any specific element in advance. 

> Waiting for navigation is not a clear sign that the website has been fully loaded.

I never said I wanted to use a navigation_wait() to load the page completely! I have my own implemented method to check whether the DOM is idle or not for waiting to load the page. As I mentioned the issue is a conflict between the `with self.page.expect_navigation(timeout=5000)` and `self.wait_for_idle()` so I had to add exception casing to wait for timeout. if there would be an approach or a method for detecting the navigation or **waiting** for it the issue will be resolved.
