### ISSUE TITLE
[Bug]: Set Up a Virtual Environment with playwright install

### ISSUE THREAD

**Issue by mpf772** [microsoft/playwright-python#2587]
### Version

1.47.0

### Steps to reproduce

My desktop create a folder name call Python 
In the Python folder has a tested and working python file name as main.py 
python -m venv myenv
myenv\Scripts\activate
pip install playwright
playwright install
pip install pyinstaller
pyinstaller --onefile main.py
Go to the dist folder and run main.exe

### Expected behavior

Go to the dist folder and run main.exe 
And run the python file successfully

### Actual behavior

Traceback (most recent call last):
  File "C:\Users\username\Desktop\Python\main.py", line 34, in <module>
    run(playwright)
  File "C:\Users\username\Desktop\Python\main.py", line 8, in run  
    browser = playwright.chromium.launch(headless=False)        
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^        
  File "playwright\sync_api\_generated.py", line 14153, in launch
  File "playwright\_impl\_sync_base.py", line 115, in _sync     
  File "playwright\_impl\_browser_type.py", line 95, in launch  
  File "playwright\_impl\_connection.py", line 59, in send      
  File "playwright\_impl\_connection.py", line 514, in wrap_api_call
playwright._impl._errors.Error: BrowserType.launch: Executable doesn't exist at C:\Users\username\AppData\Local\Temp\_MEI354362\playwright\driver\package\.local-browsers\chromium-1134\chrome-win\chrome.exe
╔════════════════════════════════════════════════════════════╗  
║ Looks like Playwright was just installed or updated.       ║  
║ Please run the following command to download new browsers: ║  
║                                                            ║  
║     playwright install                                     ║  
║                                                            ║  
║ <3 Playwright Team                                         ║  
╚════════════════════════════════════════════════════════════╝  
[PYI-19580:ERROR] Failed to execute script 'main' due to unhandled exception!

### Environment

```Text
- Operating System: Wins 11
- CPU: 12th Gen Intel(R) Core(TM) i5-12500   3.00 GHz
- Browser: Chromium
- Python Version: [3.12.6]
```

**Comment by mxschmitt** [comment]
Looks like you are interested in this guide: https://playwright.dev/python/docs/library#pyinstaller

Make sure to install the browsers before - otherwise Pyinstaller won't find the browsers.

**Comment by mpf772** [comment]
import re
from playwright.sync_api import Playwright, sync_playwright, expect



def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto(
        "https://xxxxxxxxx")
    page.wait_for_load_state("networkidle")
    page.get_by_placeholder("Email").click()
    xxxxxxxxxxx
    xxxxxxxxxxx



    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)

**Comment by mpf772** [comment]
Add on 

PS C:\Users\username\desktop\python> $env:PLAYWRIGHT_BROWSERS_PATH="0"
PS C:\Users\username\desktop\python> playwright install chromium
Downloading Chromium 129.0.6668.29 (playwright build v1134) from https://playwright.azureedge.net/builds/chromium/1134/chromium-win64.zip
139 MiB [====================] 100% 0.0s
Chromium 129.0.6668.29 (playwright build v1134) downloaded to C:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\driver\package\.local-browsers\chromium-1134
Downloading FFMPEG playwright build v1010 from https://playwright.azureedge.net/builds/ffmpeg/1010/ffmpeg-win64.zip
1.3 MiB [====================] 100% 0.0s
FFMPEG playwright build v1010 downloaded to C:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\driver\package\.local-browsers\ffmpeg-1010
PS C:\Users\username\desktop\python> pyinstaller -F main.py
215 INFO: PyInstaller: 6.10.0, contrib hooks: 2024.8
215 INFO: Python: 3.12.6
243 INFO: Platform: Windows-11-10.0.22631-SP0
243 INFO: Python environment: C:\Users\username\AppData\Local\Programs\Python\Python312
249 INFO: wrote C:\Users\username\desktop\python\main.spec
252 INFO: Module search paths (PYTHONPATH):
['C:\\Users\\username\\AppData\\Local\\Programs\\Python\\Python312\\Scripts\\pyinstaller.exe',
 'C:\\Users\\username\\AppData\\Local\\Programs\\Python\\Python312\\python312.zip',
 'C:\\Users\\username\\AppData\\Local\\Programs\\Python\\Python312\\DLLs',
 'C:\\Users\\username\\AppData\\Local\\Programs\\Python\\Python312\\Lib',
 'C:\\Users\\username\\AppData\\Local\\Programs\\Python\\Python312',
 'C:\\Users\\username\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages',
 'C:\\Users\\username\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\setuptools\\_vendor',
 'C:\\Users\\username\\desktop\\python']
509 INFO: checking Analysis
560 INFO: checking PYZ
599 INFO: checking PKG
625 INFO: Bootloader C:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\PyInstaller\bootloader\Windows-64bit-intel\run.exe
626 INFO: checking EXE
PS C:\Users\username\desktop\python> .\dist\\main.exe  
Traceback (most recent call last):
  File "C:\Users\username\Desktop\Python\main.py", line 34, in <module>
    run(playwright)
  File "C:\Users\username\Desktop\Python\main.py", line 8, in run
    browser = playwright.chromium.launch(headless=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "playwright\sync_api\_generated.py", line 14153, in launch
  File "playwright\_impl\_sync_base.py", line 115, in _sync
  File "playwright\_impl\_browser_type.py", line 95, in launch
  File "playwright\_impl\_connection.py", line 59, in send
  File "playwright\_impl\_connection.py", line 514, in wrap_api_call
playwright._impl._errors.Error: BrowserType.launch: Executable doesn't exist at C:\Users\username\AppData\Local\Temp\_MEI43922\playwright\driver\package\.local-browsers\chromium-1134\chrome-win\chrome.exe       
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                   
         ║
║     playwright install                            
         ║
║                                                   
         ║
║ <3 Playwright Team                                
         ║
╚════════════════════════════════════════════════════════════╝
[PYI-38440:ERROR] Failed to execute script 'main' due to unhandled exception!

**Comment by mxschmitt** [comment]
I was following these steps and it was working for me:

```
virtualenv env
.\env\Scripts\activate  
$env:PLAYWRIGHT_BROWSERS_PATH="0"
pip install playwright pyinstaller
playwright install chromium
pyinstaller -F main.py
```

See here for docs: https://playwright.dev/python/docs/library#pyinstaller

**Comment by mxschmitt** [comment]
Closing as per above.
