### ISSUE TITLE
Make exceptions not protected

### ISSUE THREAD

**Issue by newearthmartin** [microsoft/playwright-python#2590]
### 🚀 Feature Request

Currently if I want to catch an exception such as `TargetClosedError` I need to import it from `playwright._impl._errors` which is inside two protected packages. 

Exceptions should be public. They should be part of the declared interface, not part of the "implementation" as the package name suggests.

### Motivation

This is basic coding practice.

**Comment by mxschmitt** [comment]
Closing as per above.

**Comment by newearthmartin** [comment]
> We recommend matching by str() then as a workout if you want to match specific errors.

Thanks but no thanks. Matching by `str()` is a bad coding practice. I'd rather import a protected class, and if you guys change the implementation, at least I will realize at import time. On the contrary, if I'm matching by `str()` you may change the text and I will never realize.

I don't see why you don't want to include the errorsin the api declaration. Errors thrown are as much part of the api as the method signature. This doesn't mean you can't change it in the future, same way you can change the methods.

**Comment by newearthmartin** [comment]
To give a bit of context why I want to catch `TargetClosedError` specifically. I run my app in a shared hosting with low memory and when I exceed it, some of my processes get killed automatically. So I want to know if the browser was killed and catch that separately from other errors and try again in that case.

**Comment by karolinepauls** [comment]
```
In [9]: TargetClosedError.mro()
Out[9]:
[playwright._impl._errors.TargetClosedError,
 playwright._impl._errors.Error,
 Exception,
 BaseException,
 object]
```

There's nothing reasonable to catch. At least make `playwright._impl._errors.Error` exported.

**Comment by SamStephens** [comment]
This is really disappointing, and I likewise will be relying on the protected classes despite the official advice, because if they change, my code will fail to run, whereas if the string messages change, I only find out when my code doesn't respond to TargetClosedError correctly.

I urge a rethink of the decision to not expose the specific exceptions publicly.
