### ISSUE TITLE
[Docs]: Missing slow/skip/timeout functions at the 'test' level

### ISSUE THREAD

**Issue by kegsay** [microsoft/playwright-python#2592]
### Page(s)

https://playwright.dev/python/docs/test-assertions#setting-a-custom-timeout

### Description

Playwright [for JS](https://playwright.dev/docs/test-annotations) has test annotations which include useful functions which are missing from the Python bindings. In particular, there is no way to specify a _per-test_ timeout. [In JS](https://playwright.dev/docs/test-timeouts) you can write `test.setTimeout(60 * 1000)` to make that particular test timeout after 1 minute (replacing the default). 

A similar question was asked before but [the answer](https://github.com/microsoft/playwright-python/issues/2187#issuecomment-1846063053) specifically excludes the ability to set a per-test timeout. As far as I can tell this either means:
 - this API was missed when porting to python,
 - this API was specifically designed out in python, but there's no documentation to state why and alternatives to implement the same functionality.

Please can there be some documentation to detail this, or if there already is, please point me at it! Thanks.

**Comment by mxschmitt** [comment]
In JS we have these annotations because we built a test-runner from scratch. In Python we are limited by the test-runner we are recommending: Pytest

The documentation is only about the library methods, clicks, fills, assertions etc. For Pytest specific timeouts we recommend this: https://pypi.org/project/pytest-timeout/

**Comment by kegsay** [comment]
That makes sense, thanks. I didn't realise pytest-timeout even existed. It might be worthwhile adding a note to that effect on https://playwright.dev/python/docs/test-assertions#setting-a-custom-timeout given it seems like missing functionality otherwise.
