### ISSUE TITLE
[Bug]: Can't install playwright 1.47.0 with Python 3.13 due to dependency problem

### ISSUE THREAD

**Issue by joeg3** [microsoft/playwright-python#2594]
### Version

1.47.0

### Steps to reproduce

1. Use Python 3.13
2. Try to install playwright 1.47.0 using pip

I also posted [here](https://stackoverflow.com/questions/79078718/python-dependency-error-for-playwright-and-greenlet) on StackOverflow, but the short version is:
- playwright 1.47.0 requires greenlet 3.0.3, incompatible with greenlet 3.1
- Python 3.13 requires greenlet 3.1, incompatible with 3.0

Is my only option to downgrade to Python 3.12 which uses greenlet 3.0 to satisfy the playwright dependency?

### Expected behavior

Expect pip to be able to install playwright when using latest version of Python.

### Actual behavior

Specifying dependency of greenlet module to be 3.1 so it works with Python 3.13 prevents pip install of playwright 1.47.0
```
ERROR: Cannot install -r requirements.txt (line 2) and greenlet~=3.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested greenlet~=3.1
    playwright 1.47.0 depends on greenlet==3.0.3
```

### Environment

- Operating System: macOS Sequoia
- CPU: M1
- Browser: N/A
- Python Version: [3.13]
- Other info:

**Comment by mxschmitt** [comment]
This seems fixed already and is awaiting a new release.

Fixed by https://github.com/microsoft/playwright-python/pull/2565.
