### ISSUE TITLE
[Bug]:KeyError: 'error' error occurred when using the connect method.

### ISSUE THREAD

**Issue by tcyxhw** [microsoft/playwright-python#2596]
### Version

1.47.0

### Steps to reproduce

import asyncio
from playwright.async_api import async_playwright

async def main():
    try:
        async with async_playwright() as p:
            browser =await p.chromium.connect("ws://localhost:9222/devtools/browser/027b4ec3-035b-4fff-9417-3debf6ddfd17")
            page = await browser.new_page()
            await page.goto("https://www.example.com")
            await browser.close()
    except Exception as e:
        print(f"错误: {e}")

asyncio.run(main())

### Expected behavior

I wish to connect to an open browser instance

### Actual behavior

The following error occurs until timeout
Error occurred in event listener
Traceback (most recent call last):
  File "C:\Users\TCY\OneDrive\桌面\非作业文件\b站\Text\venv\Lib\site-packages\pyee\asyncio.py", line 51, in _emit_run
    coro: Any = f(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\TCY\OneDrive\桌面\非作业文件\b站\Text\venv\Lib\site-packages\playwright\_impl\_json_pipe.py", line 65, in <lambda>
    lambda params: handle_message(params["message"]),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TCY\OneDrive\桌面\非作业文件\b站\Text\venv\Lib\site-packages\playwright\_impl\_json_pipe.py", line 55, in handle_message
    self.on_message(cast(ParsedMessagePayload, message))
  File "C:\Users\TCY\OneDrive\桌面\非作业文件\b站\Text\venv\Lib\site-packages\playwright\_impl\_connection.py", line 233, in <lambda>
    self._transport.on_message = lambda msg: self.dispatch(msg)
                                             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\TCY\OneDrive\桌面\非作业文件\b站\Text\venv\Lib\site-packages\playwright\_impl\_connection.py", line 379, in dispatch
    error["error"], format_call_log(msg.get("log"))  # type: ignore
    ~~~~~^^^^^^^^^
KeyError: 'error'
错误: Connection timed out



### Additional context

Run the ".\chrome.exe --remote-debugging-port=9222" command in the folder where the chrome.exe file is located, and then open the "http://localhost:9222/json/version" URL in the window that opens. browser, and then pass the value of webSocketDebuggerUrl to the ws_endpoint parameter of the connect method

### Environment

- Operating System: window 11
- CPU: arm64
- Browser: Chromium]
- Python Version: 3.11
- Other info:
- chrome Version: 129.0.6668.101

**Comment by mxschmitt** [comment]
While it looks like a bug you want to use `connect_over_cdp` instead, since `connect` is Playwright's protocol while cdp is the one you are looking for.
