### ISSUE TITLE
[Bug]: to_be_visible assertion says "Locator expected to be visible" if visible=False

### ISSUE THREAD

**Issue by MilovanovM** [microsoft/playwright-python#2616]
### Version

latest

### Steps to reproduce

Steps to reproduce:
1. use the assertion `to_be_visible(visible=False)`

### Expected behavior

get `AssertionError: Locator expected to be hidden`

### Actual behavior

get `AssertionError: Locator expected to be visible`

### Environment

- Operating System: [Ubuntu 22.04]
- CPU: [arm64]
- Browser: [All, Chromium, Firefox, WebKit]
- Python Version: [3.12]
- Other info:

**Comment by mxschmitt** [comment]
Looks like we need a condition here: https://github.com/microsoft/playwright-python/blob/3352d85e4493c4b95de8304d6c16df787058cadd/playwright/_impl/_assertions.py#L672

**Comment by MilovanovM** [comment]
Just checked other implementations (Node, Java, donNet), no issue there
