### ISSUE TITLE
[Bug]: How to remove listener

### ISSUE THREAD

**Issue by jolly-xw** [microsoft/playwright-python#2624]
### Version

1.46.0

### Steps to reproduce

I know that with the following approach, I can successfully remove the listener.
```python
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()

    # create listener
    record = dict()
    def handle(response):
        record[response.url] = {
            "status": response.status,
        }
    page.on("response", handle)
    page.goto("http://playwright.dev")
    page.remove_listener("response", handle)
    browser.close()
    print(record)
```

But in my actual scenario, the dictionary used for recording is passed as a parameter to the handle function, so I used an anonymous function. However, in this case, I don't know how to remove the listener.

```python
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()

    # create listener
    tmp = dict()
    def handle(response, record):
        record[response.url] = {
            "status": response.status,
        }
    page.on("response", lambda x: handle(x, tmp))
    page.goto("http://playwright.dev")
    # page.remove_listener("response", lambda x: handle(x, tmp))
    browser.close()
    print(tmp)
```

### Expected behavior

-

### Actual behavior

-

### Environment

- Operating System: [Ubuntu 22.04]
- CPU: [arm64]
- Browser: [All, Chromium, Firefox, WebKit]
- Python Version: [3.12]
- Other info:

**Comment by mxschmitt** [comment]
You can use "remove_listener" without specifying the handler, it will then remove all the handlers which listen on that specific event. See here: https://pyee.readthedocs.io/en/latest/

**Comment by jolly-xw** [comment]
Do you mean [https://pyee.readthedocs.io/en/latest/api/#pyee.EventEmitter.remove_all_listeners](url)？ Playwright has no method named remove_all_listeners, and remove_listeners must specify the handler. I try it.
```python
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()

    # create listener
    tmp = dict()
    def handle(response, record):
        record[response.url] = {
            "status": response.status,
        }
    page.on("response", lambda x: handle(x, tmp))
    page.goto("http://playwright.dev")
    page.remove_listener("response")
    browser.close()
    print(tmp)
```
Error happened:
```
Traceback (most recent call last):
  File "c:\Users\Desktop\proj\proj\1.py", line 15, in <module>
    page.remove_listener("response")
TypeError: SyncBase.remove_listener() missing 1 required positional argument: 'f'
```

**Comment by mxschmitt** [comment]
Looks like they don't support it, so you need to wrap it inside a defined function.

Closing since this is not a Playwright bug/feature request.

**Comment by jolly-xw** [comment]
ok, thanks.
