### ISSUE TITLE
[Bug]: Playwright sync APIs introduces async context

### ISSUE THREAD

**Issue by a6kme** [microsoft/playwright-python#2628]
### Version

1.48.0

### Steps to reproduce

```
import asyncio

from playwright.sync_api import sync_playwright


def main():
    try:
        loops = asyncio.get_running_loop()
        print("Running in an async context", loops)
    except RuntimeError:
        print("Running in a sync context")

    playwright = sync_playwright().start()

    try:
        loops = asyncio.get_running_loop()
        print("Running in an async context", loops)
    except RuntimeError:
        print("Running in a sync context")


if __name__ == "__main__":
    main()
```

Output:

```
Running in a sync context
Running in an async context <_UnixSelectorEventLoop running=True closed=False debug=False>
```

### Expected behavior

Sync APIs of Playwright should not introduce async context.

### Actual behavior

Sync APIs of Playwright is introducing async context. This is causing side effects in my Django + Celery app. Django expects ORM calls to be wrapped in `sync_to_async` if it detects async context. 

### Environment

- Operating System: [MacOS 14.6.1]
- CPU: [Apple M2 Max]
- Browser: [Chromium]
- Python Version: [3.12.7]

**Comment by mxschmitt** [comment]
This sounds working as expected. Playwright uses asyncio internally - If it causes issues for you, I recommend using the asyncio version of Playwright which makes the asyncio usage more clear. This might give a better integration with Django etc. It sounds like a limitation to Celery/Django where we can't do much. Closing for now.
