### ISSUE TITLE
[Feature]: Docker container to run playwright in VNC for use headed mode

### ISSUE THREAD

**Issue by Grommash9** [microsoft/playwright-python#2648]
### 🚀 Feature Request

On Windows + WSL setup there is easy way to record tests or run in headed mode to see you tests in action so if we will run in in docker with VNC we will be able to run commands to run the tests against container and we will be able to see everything using VNC connection. It can make it simplier for people who are familiar with docker

You will also be able to reuse same image in your pipeline and run your tests in headless mode with same dependencies and 100% same setup

### Example

https://github.com/Grommash9/playwright_vnc

### Motivation

I can make it simplier to run for QA people who a familiar with basic python automation but not with complicated set up of packages and controlling the versions of everything, also maybe if somebody want to just check it out it could be faster to set it up in that way, just pulling from docker

I am not sure `playwright-python` is good repository for it to live but maybe we should create another one for it? like `playwright-python-vnc` I am not sure really.

**Comment by mxschmitt** [comment]
Looks great! We are not comfortable maintaining it for now, so I recommend having it under your GitHub handle.

Folding into https://github.com/microsoft/playwright/issues/20954 and let us know there how much value it adds!
