### ISSUE TITLE
[Feature]: Option to Exclude Specific Entries from Trace Report

### ISSUE THREAD

**Issue by DepravityDemo** [microsoft/playwright-python#2664]
### 🚀 Feature Request

While using Playwright for testing, I have noticed that although the issue with ImplToApiMapping.wrapper_func entries has been resolved, the trace report still contains numerous Response.json entries in 1.49. These entries lack meaningful information, making it difficult to focus on the critical actions and events that require analysis.
![Image](https://github.com/user-attachments/assets/72a7297f-71fa-4461-822b-2f303847c292)

[2024-11-23_19-43-42.zip](https://github.com/user-attachments/files/17879551/2024-11-23_19-43-42.zip)

Proposed Feature:
I propose a new feature in Playwright’s trace configuration that allows users to exclude specific types of entries, such as Response.json. This could be implemented as a configurable filtering mechanism, enabling users to specify which methods or event types should be excluded from the trace output.

Benefits:

Improved Readability: By excluding unnecessary entries, users can more easily focus on critical actions and events.
Enhanced Debugging Efficiency: A cleaner trace report will help users identify and resolve issues more quickly.
User Customization: Providing flexible filtering options allows users to tailor the trace output according to their needs.
Reference:
This request is a follow-up to the previous issue discussed here: [GitHub Issue #2650](https://github.com/microsoft/playwright-python/issues/2650). I would like to express my gratitude to mxschmitt for addressing the ImplToApiMapping.wrapper_func issue. Your work has been greatly appreciated and has improved our testing process significantly.

I believe that implementing this feature would further enhance Playwright’s tracing capabilities and assist users in conducting more efficient test analyses. Thank you for considering this request.

### Example

def handle_response(self, response):
        json_data = response.json()
        url = response.url

page.on('response', self.handle_response)

### Motivation

Motivation:
The presence of these extraneous Response.json entries reduces the readability of the trace report and hinders the analysis of important events and responses during testing. Users need clearer trace reports to conduct more effective debugging and analysis.

**Comment by mxschmitt** [comment]
Sounds similar to https://github.com/microsoft/playwright/pull/33620 which we we'll do in v1.50. So we hide Response.* and Request.* events from the trace.

**Comment by mxschmitt** [comment]
I'll close it for now - feel free to re-file if you still run into troubles with v1.50. (we target January for this verison)
