### ISSUE TITLE
"chromium" browser was not found. After successfully running install

### ISSUE THREAD

**Issue by Ambro17** [microsoft/playwright-python#267]
# Steps to reproduce:
1. Open a WSL session in vscode
2. Create venv and install playwright 0.152.0
3. run `python -m playwright install`
4. Run the snippet with `python filename.py`
```
from playwright import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch(headless=False)
    page = browser.newPage()
    page.goto('https://github.com/microsoft')
    page.screenshot(path=f'example.png')
    browser.close()
```
5. See it crashes with 
```
Traceback (most recent call last):
  File "/home/crow/code/x/.env/lib/python3.8/site-packages/playwright/browser_type.py", line 69, in launch
    return from_channel(await self._channel.send("launch", params))
  File "/home/crow/code/x/.env/lib/python3.8/site-packages/playwright/connection.py", line 39, in send
    result = await callback.future
playwright.helper.Error: Protocol error (Browser.getVersion): Target closed.
=========================== logs ===========================
<launching> /home/crow/.cache/ms-playwright/chromium-815036/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies,LazyFrameLoading --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --user-data-dir=/tmp/playwright_chromiumdev_profile-N9z69q --remote-debugging-pipe --no-sandbox --no-startup-window
<launched> pid=2011
[err] [2011:2011:1030/185956.954944:ERROR:browser_main_loop.cc(1434)] Unable to open X display.
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scheduler.py", line 4, in <module>
    browser = p.chromium.launch(headless=False)
  File "/home/crow/code/x/.env/lib/python3.8/site-packages/playwright/sync_api.py", line 6142, in launch
    self._sync(
  File "/home/crow/code/x/.env/lib/python3.8/site-packages/playwright/sync_base.py", line 107, in _sync
    return future.result()
  File "/home/crow/code/x/.env/lib/python3.8/site-packages/playwright/browser_type.py", line 72, in launch
    raise not_installed_error(f'"{self.name}" browser was not found.')
Exception: 
================================================================================
"chromium" browser was not found.
Please complete Playwright installation via running

    "python -m playwright install"

================================================================================
```
## Extra details
Before failing with this error it prompted me to install some os dependencies
which i did with `sudo apt install libnss3 libnspr4`

## Versions
`Playwright Version: 0.152.0`
`Windows Version:`
`WSL: Version 2`
`vscode: 1.50.1`

**Comment by pavelfeldman** [comment]
I'll look into it. Any reason you don't use Windows version?

**Comment by Ambro17** [comment]
Just forgot to update it and it didn't let me edit afterwards. It's windows 10  v2004 build 19041.572

**Comment by pavelfeldman** [comment]
I just tried it on 19042 and it worked for me. WebKit needed additional dependencies, a subset of those mentioned here: https://github.com/microsoft/playwright/blob/master/docs/docker/Dockerfile.bionic

**Comment by pavelfeldman** [comment]
Oh, you can't run headful on WSL - there is no display. `(headless=False)` won't work on headless systems such as WSL.

**Comment by Ambro17** [comment]
I imagined it had to do with that.. do you think it might be possible in the future to add the ability to run on WSL?
I googled a little bit and there are some hacks to get guis running from wsl

**Comment by pavelfeldman** [comment]
Could you share more about your set up? You would typically run headless under WSL. If you need UI, you typically run natively on the OS.

**Comment by Ambro17** [comment]
Of course, i only use windows right now because i can't install Linux due to unrelated problems.
When I want to open an html file i use wslview and it works, when i fire a docker container that's listening on local host, clicking the url just works.  (Whether it's flask, gunicorn or uvicorn)

I don't fully grasp the complexity of opening a headfull browser within wsl, and perhaps it's just not possible. 
I just opened the issue to know if that's the case or it may be planned to get better compatibility, given vscode and wsl popularity, and the fact that both are ms products, as playwright is

**Comment by pavelfeldman** [comment]
I see what you are saying. So you'd like a mode where your project along with the tooling is in WSL, but the browser opens in the host system. Let us collect more feedback on it.

**Comment by pavelfeldman** [comment]
Checking back on this after three months, it looks like you set up of using WSL did not gain enough upvotes or additional comments. We appreciate your feedback, but since we are not focusing on addressing this issue, we are closing it. With the limited resource, we are prioritizing most requested bugs / features atm.

**Comment by Ambro17** [comment]
While I agree on principle, closing the issue will reduce its visibility and avoid gaining traction.
I see no problem in issues tagged as gathering feedback, but closing them seems counter productive

**Comment by obnoxiousnerd** [comment]
Had the same issue, but with playwright-python, it got solved by running the following command:
`npx playwright install-deps`
