### ISSUE TITLE
[Bug]: Warning: Validation of the RECORD file of playwright-1.49.0-py3-none-manylinux1_x86_64.whl failed

### ISSUE THREAD

**Issue by f4rk4sh** [microsoft/playwright-python#2679]
### Version

1.49.0

### Steps to reproduce

Environment: poetry = "1.8.4".

Run `poetry add playwright==1.49.0`.

### Expected behavior

No warnings.

### Actual behavior

[playwright.log](https://github.com/user-attachments/files/17983804/playwright.log)

### Additional context

Downgrading the playwright to 1.48.0 solves the problem.

### Environment

```Text
- Operating System: Ubuntu 24.04.1 LTS
- CPU: amd64
- Browser: All
- Python Version: 3.12
```

**Comment by mxschmitt** [comment]
Should be fixed in v1.49.1
