### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by yairivix** [microsoft/playwright-python#2691]
### Version

1.43.0

### Steps to reproduce

When using page.goto in playwright sync for some websites, giving it a timeout of (60,000 or 30,000 for example) doesn't result in kill when timeout is reached.
In addition, wrapping it with a timeout like 'signal' and using context.kill doesn't work either. looks like the whole context \ communication with the playwright process is completely frozen.

I'm using the route function to filter out specific request types for media (font, image, media) but aside from that nothing out of the ordinary.
Website for example: "https://bcbg.com/cart" (though it happened with a couple of more websites - rarely).
My code:
```python
def abort_resource_requests(self, route: Route, request: Request) -> None:
    if request.resource_type in ['font', 'image', 'media']:
        route.abort()
    else:
        route.continue_()

page.goto(url, timeout=timeout)
page.route("**/*", self.abort_resource_requests)
``` 

Any idea what might cause this?

### Expected behavior

timeout should kill the goto action

### Actual behavior

runtime is frozen, i am guessing to wait for the eventloop to signal that the async action will stop (because playwright sync is using async.run async functions right?). Wrapping it with signal alarm releases the python code from the freeze but still context is frozen and cannot be closed.

### Environment

```Text
- Operating System: Both on python slim bookworm docker and on mac
- CPU: [arm64]
- Browser: [Chromium]
- Python Version: [3.11]
```

**Comment by mxschmitt** [comment]
Do you mind providing us exact reproduction steps and a self-contained reproduction?  Your script didn't run for me.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.
