### ISSUE TITLE
[Feature]: handle WSGI/ASGI applications

### ISSUE THREAD

**Issue by azmeuk** [microsoft/playwright-python#2692]
### 🚀 Feature Request

I usually develop web applications with Flask/Quart.
Playwright `goto` methods takes a full URL, implying that a webserver must be launched with my application. This makes the whole process cumbersome where I think this could be simpler if playwright would handle WSGI/ASGI applications.
In a unit test context (but actually in *any* context) this makes things slower due to the webserver launch, and the network requests management.

### Example

Instead of:

```python
import threading
import wsgiref.simple_server

from flask import Flask
from playwright.sync_api import sync_playwright

app = Flask(__name__)

@app.route("/")
def index():
    return "<html><title>Hello world!</title><body></body></html>"


httpd = wsgiref.simple_server.make_server("localhost", 5050, app)
server_thread = threading.Thread(target=httpd.serve_forever)
server_thread.start()

with sync_playwright() as p:
    browser = p.firefox.launch()
    page = browser.new_page()
    page.goto("http://localhost:5050")
    print(page.title())
    browser.close()

httpd.shutdown()
server_thread.join()
```

it would be a bliss to be able to use:

```python
from flask import Flask
from playwright.sync_api import sync_playwright

app = Flask(__name__)

@app.route("/")
def index():
    return "<html><title>Hello world!</title><body></body></html>"


with sync_playwright() as p:
    browser = p.firefox.launch()
    page = browser.new_page()
    page.goto("/", app=app)
    print(page.title())
    browser.close()
```

The [werkzeug TestClient](https://werkzeug.palletsprojects.com/en/stable/test/) could be a building block for this, as it provides an API similar to most request libraries (httpx, requests etc.) but directly passes requests to a WSGI instead of sending them through the network.

### Motivation

This would help speed-up unit tests relying on playwright, and could also be used to help screenshot generation in documentation with tools such as [sphinxcontrib-screenshot](https://github.com/tushuhei/sphinxcontrib-screenshot).

Another major improvement is that, using tools such as werkzeug TestClient, the server code is actually executed by the client. This is *hugely* useful for web development application, since the server exceptions are directly catched by the test runner, allowing PDB sessions etc.

Mildly related ticket: https://github.com/microsoft/playwright-python/issues/390

**Comment by mxschmitt** [comment]
How do you imagine this to work? Is this a web server which is in-memory so its not using an actual port?

**Comment by azmeuk** [comment]
Ok I might have been mistaken here. Obviously, if browsers perform their own network requests without involving playwright, this suggestion cannot be achieved.

**Comment by mxschmitt** [comment]
I'll close it for now. Browsers do real network requests with their own network stack, hence doing this is not possible. You can [intercept](https://playwright.dev/python/docs/network) them as of today, but that has its own limitations.
