### ISSUE TITLE
[Feature]: Dependency Updates

### ISSUE THREAD

**Issue by Houbein** [microsoft/playwright-python#2693]
### 🚀 Feature Request

Update Python Dependencies. 
Currently Playwright Python requires as a dependency pyee 12.0.0. This is now 4 months old and pyee 12.1.1 is the newest available version, please update this. 
Even better, please be less strict. Playwright currently demand pyee 12.0.0 down to the minor version, this is really not good practise and this version lock should be restricted to major versions only. 

### Motivation

Locking down even the minor version is really not good practise for bug and security reasons.

**Comment by mxschmitt** [comment]
Thank you for filing this issue. We are aware on the issue and trying to solve it as part of https://github.com/microsoft/playwright-python/issues/2666.
