### ISSUE TITLE
[Bug]: Playwright NotImplementedError (Version 1.49.1, Win 11)

### ISSUE THREAD

**Issue by Mirajul-Mohin** [microsoft/playwright-python#2696]
> I can confirm, on Win11 the issue is also there.
> 
> For the lines:
> `async with async_playwright() as p:`
> or
> `p = await async_playwright().start()`
> I get the error:
> 
> ```
> ...\Python312\Lib\asyncio\base_events.py", line 523, in _make_subprocess_transport
>     raise NotImplementedError
> NotImplementedError
> ```
> I am using it under Starlette.
> 
> Is there any fix for this? 

 _Originally posted by @stevstrong in [#462](https://github.com/microsoft/playwright-python/issues/462#issuecomment-2519869308)_

**Comment by Mirajul-Mohin** [comment]
> Hello @pavelfeldman. This should probably be reopened. As shown on #480, even using async functionality will trigger issues - at least on Windows - due to asyncio.
> 
> Copy-pasted from [asheshstha](https://github.com/microsoft/playwright-python/issues/480#issuecomment-1368193989) back in 2022 (the issue persists):
> 
> ```
> Task exception was never retrieved
> future: <Task finished name='Task-8' coro=<Connection.run() done, defined at C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py:240> exception=NotImplementedError()>
> Traceback (most recent call last):
>   File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_connection.py", line 247, in run
>     await self._transport.connect()
>   File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_transport.py", line 132, in connect
>     raise exc
>   File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\playwright\_impl\_transport.py", line 120, in connect
>     self._proc = await asyncio.create_subprocess_exec(
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
>     transport, protocol = await loop.subprocess_exec(
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 1675, in subprocess_exec
>     transport = await self._make_subprocess_transport(
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport
>     raise NotImplementedError
> NotImplementedError
> ``` 

 _Originally posted by @BramVanroy in [#462](https://github.com/microsoft/playwright-python/issues/462#issuecomment-2474238829)_

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!

**Comment by IanTaiAhn** [comment]
Environment details:
- Windows 11
- Using Jupyter Notebook in VScode
- Running Jupyter notebook using a Conda environment

The only thing that got rid of this error:
![Image](https://github.com/user-attachments/assets/7955aad3-73d5-4e6e-bb9d-25858e5e687d)

Was to not use jupyter notebooks (*.ipynb) and use a regular old python (*.py) file.
Not really a workaround for using Jupyter notebooks, but at least I can use ascynio playwright

**Comment by zilongfeng** [comment]
im still facing this issue on Win 11 Py 3.13. But im confused how it is closed?

**Comment by jj-github-jj** [comment]
This worked for me for running it within jupyter notebook. AI generated solutions such as using nest_asyncio etc did not work. 
```
import asyncio
import threading
from functools import wraps


def async_runner(coro_func):
    """Decorator to run async functions safely from Jupyter with Playwright
    This decorator allows you to run asynchronous functions in a synchronous context, such as Jupyter notebooks, by executing the async function in a separate thread and waiting for its completion. It handles exceptions raised in the async function and returns the result.
    usage: 
    first define your async function, then decorate it with @async_runner, and call it like a normal function.
    
    """

    @wraps(coro_func)
    def wrapper(*args, **kwargs):
        result_container = []
        exception_container = []

        def run_in_thread():
            try:
                loop = asyncio.new_event_loop()
                asyncio.set_event_loop(loop)
                try:
                    result = loop.run_until_complete(coro_func(*args, **kwargs))
                    result_container.append(result)
                finally:
                    loop.close()
            except Exception as e:
                exception_container.append(e)

        thread = threading.Thread(target=run_in_thread, daemon=False)
        thread.start()
        thread.join()

        if exception_container:
            raise exception_container[0]
        return result_container[0]
    
    return wrapper

# Usage:
@async_runner
async def my_playwright_func(page):
    await page.goto("https://example.com")
    return await page.title()

#result = my_playwright_func(page)
