### ISSUE TITLE
[Bug]: STATUS_BREAKPOINT

### ISSUE THREAD

**Issue by q465414859** [microsoft/playwright-python#2700]
### Version

1.49

### Steps to reproduce

Example steps (replace with your own):
1. Clone my repo at https://github.com/<myuser>/example
2. pip install -r requirements.txt
3. python test.py
4. You should see the error come up

### Expected behavior

Python 3.10.14

### Actual behavior

使用后页面更亏 STATUS_BREAKPOINT ，特别是click操作上。我是使用connect_over_cdp连接浏览器操作

### Environment

```Text
- Operating System: [win10]
- CPU: [E5-2696 v3]
- Browser: [Chromium]
- Python Version: [Python 3.10.14]
- Other info:
```

**Comment by mxschmitt** [comment]
This issue is not following the bug template. Please re-file and provide a self-contained reproduction, which we can run locally to reproduce your issue. Thanks for your understanding!
