### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by GitBib** [microsoft/playwright-python#273]
From the documentation I didn't quite understand how the _evalOnSelectorAll_ function works. I wanted to get all "_tr_" with the _data-key_ attribute from a certain table with xpath.

**Comment by mxschmitt** [comment]
We might should document that in Playwright for Python some methods are different due language reasons. In more detail:

```
      "continue_": "continue",
      "evalOnSelector": "$eval",
      "evalOnSelectorAll": "$$eval",
      "querySelector": "$",
      "querySelectorAll": "$$",
```

So `evalOnSelectorAll` is `$$eval`: https://playwright.dev/#path=docs%2Fapi.md&q=pageevalselector-pagefunction-arg-1

Does this answer your question?

**Comment by GitBib** [comment]
The question here is more about how to use methods. It was not clear from the documentation.

```python
test = self.page.evalOnSelectorAll(
    "tr",
    ""
)

**Comment by mxschmitt** [comment]
Hi, what exactly is not clear for you, would be great if you could elaborate. In general the API signatures and return values are the same as we have in the [upstream JavaScript documentation](https://playwright.dev/#version=v1.5.2&path=docs%2Fapi.md&q=pageevalselector-pagefunction-arg-1) of Playwright.

The first argument is a selector of N elements, which then gets passed to the callback (list of dom nodes) which is a JavaScript function as a string. So you can e.g. use the JavaScript [`Array.prototype.map`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/map) function to iterate in JavaScript over the elements and the return values are getting returned from the `evalOnSelectorAll` function.

**Comment by pavelfeldman** [comment]
Were you looking at these docs:  https://playwright.dev/#version=v1.6.2&path=docs%2Fselectors.md&q= ?

**Comment by pavelfeldman** [comment]
Closing as a part of triage, we need more details in order to be able to help, please feel free to open a new issue!
