### ISSUE TITLE
Video recording during test is not working

### ISSUE THREAD

**Issue by smalldragonvt** [microsoft/playwright-python#284]
Hi,

I'm trying to use video recording feature but seem its not working. A webm file was created with 0 bytes. Can you guy help to check the issue ? 

Sample project for demo:
https://github.com/smalldragonvt/playwright_video_test

File generated after test run:
![image](https://user-images.githubusercontent.com/11205073/98203851-6d40fc00-1f67-11eb-84c0-cb9200c350ef.png)

Thanks

**Comment by mxschmitt** [comment]
Hey, its recommended to use pytest-playwright, an official library to use Playwright with Pytest: https://github.com/microsoft/playwright-pytest

Probably the reason for that was that the browser was not probably closed. I created a Pull Request which works on my environment here: https://github.com/smalldragonvt/playwright_video_test/pull/1

**Comment by smalldragonvt** [comment]
hello,

I've reading the plugin and seem I missed calling to page.close() on the fixture. It would work without using pytest-plugin above. thanks for your help.
