### ISSUE TITLE
Memory leak while reusing BrowserContext

### ISSUE THREAD

**Issue by vsmetansky** [microsoft/playwright-python#286]
I have the following [code](https://github.com/vsmetansky/playwright_memory_test), which depends on playwright version 0.152.0, to model the usage of browser sessions. Each session consists of AsyncPlaywright, Browser and BrowserContext instances. The code also utilizes tracemalloc module to track memory allocations during execution. Here is an example of the logs after doing some page.goto's with 10 sessions and 10 url groups, where each group consists of 10 https://www.google.com urls (100 urls in total):
![Execution started](https://user-images.githubusercontent.com/36275660/98236079-7338dc00-1f6b-11eb-9499-e6c439becb33.png)
![Execution ended](https://user-images.githubusercontent.com/36275660/98236356-e80c1600-1f6b-11eb-95ef-3f4627a65b1f.png)
It is clear from the logs, that some memory leak is present, and, judging by the traceback, something is wrong with dict that is initialized inside Transport._run via json.loads(buffer) (line 59):
![Execution started](https://user-images.githubusercontent.com/36275660/98237545-ba27d100-1f6d-11eb-9290-42382328a395.png)
![Execution ended](https://user-images.githubusercontent.com/36275660/98237553-bd22c180-1f6d-11eb-8b3d-87d1f75c6f1a.png)
Some more investigation led to a conclusion, that ChannelOwner instances (mostly Request and Response instances), that contain partial copies of the aforecited dicts (the dicts acquired via json.loads(buffer)) inside _initializer fields, are accumulated inside Connection._objects. Connection._objects dict is cleared only after closing BrowserContext instance, which makes one unable to reuse BrowserContext instanses a considerable number of times.

**Comment by JoelEinbinder** [comment]
@pavelfeldman this looks real but I am not sure how to debug it in python.

**Comment by pavelfeldman** [comment]
This is expected, resources belong to the contexts and I don't think you are closing those between actions. This is consistent with the browser behavior. You are supposed to create new context for each action (test) - it is instant.

**Comment by pavelfeldman** [comment]
Closing as per above!

**Comment by AIGeneratedUsername** [comment]
For whoever coming here from the web search, here is the related issue: https://github.com/microsoft/playwright/issues/6319
