### ISSUE TITLE
[QUESTION] Is there a way to obtain the file path from a downloaded file while triggering the download event?

### ISSUE THREAD

**Issue by macgeneral** [microsoft/playwright-python#292]
What I've found out so far:
```python
page.waitForEvent('download')
```
called this way from a non async function will result in it being a blocking function - it probably works for download sites which implement some sort of "Your download will start in ... seconds" counter, but it doesn't work automatically if the download has to be user initiated.

```python
page.waitForEvent('download').path()
```
returns the path of the downloaded file (if the user initiated a download in a non headless session).

```python
page.expect_download(page.click('a#download_button'))
```
actually triggers the download event by performing the necessary click when the event listener is up, unfortunately it does not include a `path()` function or property (it returns an [EventContextManager](https://github.com/microsoft/playwright-python/blob/master/playwright/event_context_manager.py) which unfortunately doesn't help me much either).

Is there any way to get the path of a downloaded file (to work with it afterwards) without switching the complete test_case to asyncio (I still have to look deeper into that)?

**Comment by mxschmitt** [comment]
Hi,

would something like that work for your use-case?

```py
with page.expect_download() as download_info:
    page.click("button#delayed-download")
download = download_info.value
path = download.path()
print(path)
```

See here for reference: https://github.com/microsoft/playwright-python#using-context-managers

**Comment by macgeneral** [comment]
Thank you very much for the fast response. I was quite sure that I had tried that but I must have missed something.
