### ISSUE TITLE
how to fill text auto complete

### ISSUE THREAD

**Issue by niemtin6789** [microsoft/playwright-python#303]
![image](https://user-images.githubusercontent.com/23057766/99367378-77121a00-28ec-11eb-8202-515c91ee3907.png)
how to fill text auto complete. 
thanks

**Comment by kumaraditya303** [comment]
> ![image](https://user-images.githubusercontent.com/23057766/99367378-77121a00-28ec-11eb-8202-515c91ee3907.png)
> how to fill text auto complete.
> thanks

You can use `selectOption` method for selecting in select elements. [docs](https://playwright.dev/#version=v1.6.2&path=docs%2Finput.md&q=select-options)

**Comment by pavelfeldman** [comment]
You can use `page.type` or `page.keyboard`. See https://playwright.dev/#version=v1.6.2&path=docs%2Finput.md&q= for more details.
