### ISSUE TITLE
playwright-cli not found on MacOS Big Sur

### ISSUE THREAD

**Issue by cuongnguyen2190** [microsoft/playwright-python#304]
Step to reproduce:
1. Create virtualenv with python 3.8.6: python -m venv .env
2. Activate virtualenv and install playwright: source .env/bin/activate && pip install -r requirements.txt
3. Run playwright install: python -m playwright install

Actual Result:
![image](https://user-images.githubusercontent.com/11205073/99400038-13521600-2919-11eb-9191-d883a0dfe6dd.png)

Playwright data inside virtualenv:
![image](https://user-images.githubusercontent.com/11205073/99400008-08978100-2919-11eb-9ed2-4b8b92056afa.png)

OS: MacOS Big Sur
Python version: 3.8.6 (install via pyenv)

**Comment by mxschmitt** [comment]
I currently don't have a Big Sur device to reproduce it, but the fix might be to make the macOS package name more generic without the version name: https://github.com/microsoft/playwright-python/blob/f1c83447007ef09d4b32d29985a603b5126f83db/build_package.py#L83-L85

**Comment by cuongnguyen2190** [comment]
I attach here more pip verbose log:
`Created temporary directory: /private/var/folders/_4/6n26zkk50r7_qtv20h7c2c240000gn/T/pip-record-tcvmyxyo
    Running command /Users/cuong/Documents/workspace/snapmart/qaa/.env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/_4/6n26zkk50r7_qtv20h7c2c240000gn/T/pip-install-bskah6yc/playwright/setup.py'"'"'; __file__='"'"'/private/var/folders/_4/6n26zkk50r7_qtv20h7c2c240000gn/T/pip-install-bskah6yc/playwright/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/_4/6n26zkk50r7_qtv20h7c2c240000gn/T/pip-record-tcvmyxyo/install-record.txt --single-version-externally-managed --compile --install-headers /Users/cuong/Documents/workspace/snapmart/qaa/.env/include/site/python3.8/playwright
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/playwright
    copying playwright/browser_type.py -> build/lib/playwright
    copying playwright/event_context_manager.py -> build/lib/playwright
    copying playwright/cdp_session.py -> build/lib/playwright
    copying playwright/playwright.py -> build/lib/playwright
    copying playwright/_repo_version.py -> build/lib/playwright
    copying playwright/chromium_browser_context.py -> build/lib/playwright
    copying playwright/dialog.py -> build/lib/playwright
    copying playwright/transport.py -> build/lib/playwright
    copying playwright/download.py -> build/lib/playwright
    copying playwright/__init__.py -> build/lib/playwright
    copying playwright/page.py -> build/lib/playwright
    copying playwright/selectors.py -> build/lib/playwright
    copying playwright/console_message.py -> build/lib/playwright
    copying playwright/file_chooser.py -> build/lib/playwright
    copying playwright/impl_to_api_mapping.py -> build/lib/playwright
    copying playwright/js_handle.py -> build/lib/playwright
    copying playwright/browser.py -> build/lib/playwright
    copying playwright/browser_context.py -> build/lib/playwright
    copying playwright/connection.py -> build/lib/playwright
    copying playwright/input.py -> build/lib/playwright
    copying playwright/frame.py -> build/lib/playwright
    copying playwright/sync_api.py -> build/lib/playwright
    copying playwright/helper.py -> build/lib/playwright
    copying playwright/network.py -> build/lib/playwright
    copying playwright/async_base.py -> build/lib/playwright
    copying playwright/async_api.py -> build/lib/playwright
    copying playwright/accessibility.py -> build/lib/playwright
    copying playwright/object_factory.py -> build/lib/playwright
    copying playwright/main.py -> build/lib/playwright
    copying playwright/video.py -> build/lib/playwright
    copying playwright/element_handle.py -> build/lib/playwright
    copying playwright/__main__.py -> build/lib/playwright
    copying playwright/path_utils.py -> build/lib/playwright
    copying playwright/sync_base.py -> build/lib/playwright
    copying playwright/wait_helper.py -> build/lib/playwright
    running egg_info
    writing playwright.egg-info/PKG-INFO
    writing dependency_links to playwright.egg-info/dependency_links.txt
    writing requirements to playwright.egg-info/requires.txt
    writing top-level names to playwright.egg-info/top_level.txt
    reading manifest file 'playwright.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'playwright/drivers/browsers.json'
    writing manifest file 'playwright.egg-info/SOURCES.txt'
    copying playwright/py.typed -> build/lib/playwright
    running install_lib
    creating /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/browser_type.py -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/event_context_manager.py -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/cdp_session.py -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/playwright.py -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/_repo_version.py -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/chromium_browser_context.py -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/dialog.py -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/transport.py -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/download.py -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/__init__.py -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/page.py -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/selectors.py -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/console_message.py -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/file_chooser.py -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/impl_to_api_mapping.py -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/js_handle.py -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/browser.py -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/browser_context.py -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/connection.py -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/input.py -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/frame.py -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/sync_api.py -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/helper.py -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/network.py -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/async_base.py -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/py.typed -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/async_api.py -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/accessibility.py -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/object_factory.py -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/main.py -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/video.py -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/element_handle.py -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/__main__.py -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/path_utils.py -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/sync_base.py -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    copying build/lib/playwright/wait_helper.py -> /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright
    byte-compiling /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright/browser_type.py to browser_type.cpython-38.pyc
    byte-compiling /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright/event_context_manager.py to event_context_manager.cpython-38.pyc
    byte-compiling /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright/cdp_session.py to cdp_session.cpython-38.pyc
    byte-compiling /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright/playwright.py to playwright.cpython-38.pyc
    byte-compiling /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright/_repo_version.py to _repo_version.cpython-38.pyc
    byte-compiling /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright/chromium_browser_context.py to chromium_browser_context.cpython-38.pyc
    byte-compiling /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright/dialog.py to dialog.cpython-38.pyc
    byte-compiling /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright/transport.py to transport.cpython-38.pyc
    byte-compiling /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright/download.py to download.cpython-38.pyc
    byte-compiling /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright/__init__.py to __init__.cpython-38.pyc
    byte-compiling /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright/page.py to page.cpython-38.pyc
    byte-compiling /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright/selectors.py to selectors.cpython-38.pyc
    byte-compiling /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright/console_message.py to console_message.cpython-38.pyc
    byte-compiling /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright/file_chooser.py to file_chooser.cpython-38.pyc
    byte-compiling /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright/impl_to_api_mapping.py to impl_to_api_mapping.cpython-38.pyc
    byte-compiling /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright/js_handle.py to js_handle.cpython-38.pyc
    byte-compiling /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright/browser.py to browser.cpython-38.pyc
    byte-compiling /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright/browser_context.py to browser_context.cpython-38.pyc
    byte-compiling /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright/connection.py to connection.cpython-38.pyc
    byte-compiling /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright/input.py to input.cpython-38.pyc
    byte-compiling /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright/frame.py to frame.cpython-38.pyc
    byte-compiling /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright/sync_api.py to sync_api.cpython-38.pyc
    byte-compiling /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright/helper.py to helper.cpython-38.pyc
    byte-compiling /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright/network.py to network.cpython-38.pyc
    byte-compiling /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright/async_base.py to async_base.cpython-38.pyc
    byte-compiling /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright/async_api.py to async_api.cpython-38.pyc
    byte-compiling /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright/accessibility.py to accessibility.cpython-38.pyc
    byte-compiling /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright/object_factory.py to object_factory.cpython-38.pyc
    byte-compiling /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright/main.py to main.cpython-38.pyc
    byte-compiling /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright/video.py to video.cpython-38.pyc
    byte-compiling /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright/element_handle.py to element_handle.cpython-38.pyc
    byte-compiling /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright/__main__.py to __main__.cpython-38.pyc
    byte-compiling /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright/path_utils.py to path_utils.cpython-38.pyc
    byte-compiling /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright/sync_base.py to sync_base.cpython-38.pyc
    byte-compiling /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright/wait_helper.py to wait_helper.cpython-38.pyc
    running install_egg_info
    Copying playwright.egg-info to /Users/cuong/Documents/workspace/snapmart/qaa/.env/lib/python3.8/site-packages/playwright-0.162.0-py3.8.egg-info
    running install_scripts
    writing list of installed files to '/private/var/folders/_4/6n26zkk50r7_qtv20h7c2c240000gn/T/pip-record-tcvmyxyo/install-record.txt'
    Running setup.py install for playwright ... done`

**Comment by etishka** [comment]
is there a fix or workaround for it?

**Comment by cuongnguyen2190** [comment]
> is there a fix or workaround for it?

you should compile the module yourself -> grant execute permission for playwright-cli -> copy folder base on platform into virtualenv folder
