### ISSUE TITLE
Playwright does not support chromium on mac11.0

### ISSUE THREAD

**Issue by alexfilothodoros** [microsoft/playwright-python#307]
Hello.

I am using macOS Big Sur 11.0.1.

I tried to reinstall playwright, but there was a problem with installing greenlet. 
The problem was fixed with sudo xcodebuild -license.
Then I reinstalled playwright with **pip install playwright --no-cache-dir --force-reinstall**
and then I am running **python -m playwright install** which gives me this error 

`Failed to process descriptor at /Users/alex/.npm/_npx/10142/lib/node_modules/playwright-cli/node_modules/playwright
Failed to process descriptor at /Users/alex/.npm/_npx/10178/lib/node_modules/playwright-cli/node_modules/playwright
(node:21394) UnhandledPromiseRejectionWarning: Error: ERROR: Playwright does not support chromium on mac11.0
    at Object.assert (/snapshot/playwright-cli/node_modules/playwright/lib/utils/utils.js:58:15)
    at revisionURL (/snapshot/playwright-cli/node_modules/playwright/lib/install/browserFetcher.js:125:13)
    at Object.downloadBrowserWithProgressBar (/snapshot/playwright-cli/node_modules/playwright/lib/install/browserFetcher.js:150:17)
    at async validateCache (/snapshot/playwright-cli/node_modules/playwright/lib/install/installer.js:99:9)
    at async Object.installBrowsersWithProgressBar (/snapshot/playwright-cli/node_modules/playwright/lib/install/installer.js:56:5)
(node:21394) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21394) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.` 

I thought this information could be useful.

Cheers
Alex

**Comment by pavelfeldman** [comment]
Could it be that you are using an old version of Playwright? Current [v0.162.1](https://github.com/microsoft/playwright-python/releases/tag/v0.162.1) that corresponds to Playwright 1.6.1 should work on macOS 11.

**Comment by alexfilothodoros** [comment]
Maybe. I cannot reproduce it now. 
Thanks for the heads up :)
Alex
