### ISSUE TITLE
Playwright on unsupported platforms

### ISSUE THREAD

**Issue by kumaraditya303** [microsoft/playwright-python#312]
On [PyPI](https://pypi.org/project/playwright/#files) the source distribution of the project is uploaded as a result on unsupported platforms, running `pip install playwright` installs the project without playwright-cli and the user does not has access to [build_package.py](https://github.com/microsoft/playwright-python/blob/master/build_package.py). It is better to upload only the wheel of the supported platforms to PyPI so that the unsupported platforms does not download the source code and cause errors.

**Comment by mxschmitt** [comment]
Yup, we are aware of the issue that our source bundle is not usable which gets used when it's a non-supported platform. Is it recommended in your mind to then not publish the source archive so only wheels are published?

**Comment by kumaraditya303** [comment]
> Yup, we are aware of the issue that our source bundle is not usable which gets used when it's a non-supported platform. Is it recommended in your mind to then not publish the source archive so only wheels are published?

Yup, as most of the platform dependent packages on PyPI only upload wheels, not source distribution and they give details about what is supported and building from source instructions in README files and doing so would also reduce the issues with platform incompatibility as pip would not install the package and also not cause platform dependent issues like that of Alpine Linux, etc.

**Comment by mxschmitt** [comment]
@kemurayama cool thanks for confirming, created a patch here #314 and tested it locally. With that we only build now wheels and no source files anymore so they don't get pushed to PyPi.

**Comment by pavelfeldman** [comment]
What platform are you interested in?

**Comment by kumaraditya303** [comment]
Closing as the related PR is already merged!
