### ISSUE TITLE
pytest-cov doesn't work when sync_playwright is active

### ISSUE THREAD

**Issue by dcrowe** [microsoft/playwright-python#313]
Hi. Love the project. Found an oddity, thought I should report it.

`pytest-cov` coverage doesn't appear to be collected when `sync_playwright` is active.

I'm using the following versions:
playwright                0.162.1
pytest                    6.1.2
pytest-cov                2.10.1
Recreated on python 3.9, 3.8, 3.7.

Here's the minimal reproduction:
```
import playwright
import pytest

def test_playwright_breaks_coverage():
    print('coverage works here')

    with playwright.sync_playwright() as p:
        print('but coverage doesnt work here')

        browser = p.chromium.launch(headless=True)
        try:
            page = browser.newPage()
            page.setViewportSize(1024, 768)
            page.goto('https://google.com')
        finally:
            browser.close()

        print('or here')

    print('coverage works here')
```

Run with `python -m pytest test_playwright_breaks_coverage.py --cov-report=html --cov=test_playwright_breaks_coverage`

**Comment by pavelfeldman** [comment]
Could you share more what coverage you are measuring? The core runs in the browser anyways, so it is unclear what the intended result is.

**Comment by dcrowe** [comment]
Hi Pavel,

I'm using pytest-cov to track line coverage of our python code by our tests. I agree that I shouldn't expect coverage data for the playwright binaries or library code. 

The intended result is that pytest-cov should correctly report which lines of the example test were executed. Given that all lines of the test were executed, then the coverage report should indicate the same.

The screenshot below shows the coverage report which incorrectly indicates that a number of lines in the test were not executed.

![image](https://user-images.githubusercontent.com/457807/99889847-e3a06680-2ca8-11eb-8fe5-a96c2c9ec182.png)

**Comment by pavelfeldman** [comment]
Thanks for the details! I suspect that pytest-cov is not compatible with the fibers implementation we use.

We use `greenlet` library to implement blocking sync API, same library `gevent` uses. Greenlets allow running cooperatively concurrent tasks on the same thread, but have a native component that probably confuses pytest-cov?

I guess that would be an issue against pytest-cov to support greenlet / other fibers? As a workaround, you could use our async API - it doesn't use any native modules, so I hope pytest-cov has no problem with it.

**Comment by pavelfeldman** [comment]
https://stackoverflow.com/questions/22890779/determining-test-coverage-with-py-test-gevent - looks relevant. Could you try it and see if it helps?

**Comment by dcrowe** [comment]
Hi Pavel,

Thanks for your help. I'll have a dig in that direction and see what I can find.

**Comment by dcrowe** [comment]
Magnificent. It worked like a charm.

Add the following settings to `.coveragerc` in the project directory:
```
[run]
concurrency = greenlet
```

**Comment by dcrowe** [comment]
Thank you for your help.
