### ISSUE TITLE
[BUG] Specifying context with {viewport: None} does not make browser to fit fullscreen

### ISSUE THREAD

**Issue by Treshch1** [microsoft/playwright-python#316]
**Steps to reproduce**:
Run following code
```
from playwright import sync_playwright


playwright = sync_playwright().start()
browser = playwright.chromium.launch(headless=False)
context = browser.newContext(viewport=None)
page = context.newPage()
page.goto(f'{any_site}')
```

**Actual results**:
Browser is not displayed in the fullscreen

**Expected results:**
Browser should be displayed in the fullscreen

**Environment:** Ubuntu 18.04, python 3.7.2

**Comment by pavelfeldman** [comment]
viewport=None does not stand for the full screen, it means that user can resize the browser window in the headful mode. There is an open request for full screen mode in Playwright upstream: https://github.com/microsoft/playwright/issues/1086. Please upvote it there!
