### ISSUE TITLE
Can use socks5 proxy with playwright-python?

### ISSUE THREAD

**Issue by Nattakitt-Tin** [microsoft/playwright-python#324]
I'm want to use socks5 proxy with chromium 
how to setting playwright like setting selenium options 
copts.add_argument("--proxy-server=socks5://id:password@xxx.socks.ipvanish.com:port")
now, i'm try to setting like this but not work
playwright.chromium.launch(headless=False,args =['--proxy-server=socks5://id:password@xxx.socks.ipvanish.com:port'])

**Comment by pavelfeldman** [comment]
Playwright supports global and per-context proxy settings across browsers, no need for browser-specific command line args:

https://playwright.dev/#version=v1.6.2&path=docs%2Fapi.md&q=browsertypelaunchoptions--options-proxy

https://playwright.dev/#version=v1.6.2&path=docs%2Fapi.md&q=browsernewcontextoptions--options-proxy

**Comment by Nattakitt-Tin** [comment]
I'm try to use in python but it's not work. this my code.

```
playwright = sync_playwright().start()
browser = playwright.chromium.launch(headless=False , proxy = { 'server': 'socks5://username:password@servername.socks.ipvanish.com:port' })
page = browser.newPage()
page.goto('https://getfoxyproxy.org/geoip/')
```
then i'm try.
```
playwright = sync_playwright().start()
browser = playwright.chromium.launch(headless=False , proxy ={ 'server': 'socks5://servername.socks.ipvanish.com:port','username' :'username','password':'password'})
page = browser.newPage()
page.goto('https://getfoxyproxy.org/geoip/')
```
I'm got same error 
`net::ERR_SOCKS_CONNECTION_FAILED at https://getfoxyproxy.org/geoip/`

I'm want to use proxy-server from ipvanish server like this socks5://username:password@syd.socks.ipvanish.com:port
,pls let me know how to fix this code.

**Comment by pavelfeldman** [comment]
Your proxy URL contains string `:port` instead of an actual number. You should use the actual proxy port.

**Comment by Nattakitt-Tin** [comment]
> Your proxy URL contains string `:port` instead of an actual number. You should use the actual proxy port.

I'm try to use actual port but not work.

**Comment by pavelfeldman** [comment]
It works for us locally, so we need more details to be able to solve it. Does any other solution work for you? Can you point your regular browser to that proxy?

**Comment by songhao8080** [comment]
> I'm try to use in python but it's not work. this my code.
> 
> ```
> playwright = sync_playwright().start()
> browser = playwright.chromium.launch(headless=False , proxy = { 'server': 'socks5://username:password@servername.socks.ipvanish.com:port' })
> page = browser.newPage()
> page.goto('https://getfoxyproxy.org/geoip/')
> ```
> 
> then i'm try.
> 
> ```
> playwright = sync_playwright().start()
> browser = playwright.chromium.launch(headless=False , proxy ={ 'server': 'socks5://servername.socks.ipvanish.com:port','username' :'username','password':'password'})
> page = browser.newPage()
> page.goto('https://getfoxyproxy.org/geoip/')
> ```
> 
> I'm got same error `net::ERR_SOCKS_CONNECTION_FAILED at https://getfoxyproxy.org/geoip/`
> 
> I'm want to use proxy-server from ipvanish server like this socks5://username:[password@syd.socks.ipvanish.com](mailto:password@syd.socks.ipvanish.com):port ,pls let me know how to fix this code.


Do you solve the problem??

**Comment by zq99299** [comment]
```
browser_context = await browser.new_context(
                viewport={"width": 1920, "height": 1080},
                user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
                locale='en_US',
                timezone_id='America/Chicago',
                proxy={
                    "server": "socks5://user:pwd@123.xxx.ss:5001",
                }
            )
```
This can be done by including the username and password in the connection for SOCKS5.

**Comment by roman-net8** [comment]
Chromium (the browser in Playwright) does not support authorization via SOCKS5 proxy directly - you can't use login and password.
Will this be fixed?
