### ISSUE TITLE
Installation fails on BigSur

### ISSUE THREAD

**Issue by mjmare** [microsoft/playwright-python#325]
I created a new python 3.9 virtual env, activated the vent, pip installed playwright and then tried to do the install command (python -m playwright install). But then I get this error:

```
No such file or directory: '/Users/mjm/Zcratch/venv/lib/python3.9/site-packages/playwright/driver/playwright-cli'
```

Additional info: 

```
>pip freeze
click==7.1.2
greenlet==0.4.17
pip-tools==5.4.0
playwright==0.162.1
pyee==8.1.0
six==1.15.0
typing-extensions==3.7.4.3
```

**Comment by kumaraditya303** [comment]
What is your MacOS version ?

**Comment by mjmare** [comment]
Sorry, should have mentioned that: macOS Big Sur 11.0.1. Brew-installed python (Python 3.9.0 (default, Nov 21 2020, 14:55:42)[Clang 12.0.0 (clang-1200.0.32.27)] on darwin)

**Comment by pavelfeldman** [comment]
Python 3.9 / Pip <20.5 do not yet support BigSur. My understanding is that the fix has landed and now we are waiting for the release:

https://github.com/pypa/packaging/pull/319
https://github.com/pypa/packaging/issues/345

**Comment by pradyunsg** [comment]
> Pip <20.5

To be clear, this isn't `pip < 20.5` (the CLI tool), but `packaging < 20.5` (a library that pip uses) that doesn't support Big Sur yet.

**Comment by kumaraditya303** [comment]
@pavelfeldman  Newer version of pip solves the problem with MacOS Big Sur. https://pip.pypa.io/en/stable/news/#features

**Comment by quidnu** [comment]
Is this confirmed fixed? I have pip 20.3.3 and still get file not found for playwright-cli

Big Sur 11.1 on M1

**Comment by kumaraditya303** [comment]
Run this code and paste the output.
```python
from packaging.tags import sys_tags
print(list(sys_tags()))
```

**Comment by quidnu** [comment]
`>>> from packaging.tags import sys_tags
>>> print(list(sys_tags()))
[<cp39-cp39-macosx_11_0_arm64 @ 4343957568>, <cp39-cp39-macosx_11_0_universal2 @ 4343957696>, <cp39-abi3-macosx_11_0_arm64 @ 4343957888>, <cp39-abi3-macosx_11_0_universal2 @ 4343958080>, <cp39-none-macosx_11_0_arm64 @ 4343958272>, <cp39-none-macosx_11_0_universal2 @ 4343958464>, <cp38-abi3-macosx_11_0_arm64 @ 4340230016>, <cp38-abi3-macosx_11_0_universal2 @ 4343958656>, <cp37-abi3-macosx_11_0_arm64 @ 4343958784>, <cp37-abi3-macosx_11_0_universal2 @ 4343958976>, <cp36-abi3-macosx_11_0_arm64 @ 4340230080>, <cp36-abi3-macosx_11_0_universal2 @ 4343959296>, <cp35-abi3-macosx_11_0_arm64 @ 4343967808>, <cp35-abi3-macosx_11_0_universal2 @ 4343967936>, <cp34-abi3-macosx_11_0_arm64 @ 4343968128>, <cp34-abi3-macosx_11_0_universal2 @ 4343968320>, <cp33-abi3-macosx_11_0_arm64 @ 4343968512>, <cp33-abi3-macosx_11_0_universal2 @ 4343968704>, <cp32-abi3-macosx_11_0_arm64 @ 4343968896>, <cp32-abi3-macosx_11_0_universal2 @ 4343969088>, <py39-none-macosx_11_0_arm64 @ 4343970880>, <py39-none-macosx_11_0_universal2 @ 4343970944>, <py3-none-macosx_11_0_arm64 @ 4343969280>, <py3-none-macosx_11_0_universal2 @ 4343971328>, <py38-none-macosx_11_0_arm64 @ 4343971136>, <py38-none-macosx_11_0_universal2 @ 4343971648>, <py37-none-macosx_11_0_arm64 @ 4343971520>, <py37-none-macosx_11_0_universal2 @ 4343972096>, <py36-none-macosx_11_0_arm64 @ 4343971968>, <py36-none-macosx_11_0_universal2 @ 4343972480>, <py35-none-macosx_11_0_arm64 @ 4343972352>, <py35-none-macosx_11_0_universal2 @ 4343972864>, <py34-none-macosx_11_0_arm64 @ 4343972736>, <py34-none-macosx_11_0_universal2 @ 4343973248>, <py33-none-macosx_11_0_arm64 @ 4343973120>, <py33-none-macosx_11_0_universal2 @ 4343973632>, <py32-none-macosx_11_0_arm64 @ 4343973504>, <py32-none-macosx_11_0_universal2 @ 4343974016>, <py31-none-macosx_11_0_arm64 @ 4343973888>, <py31-none-macosx_11_0_universal2 @ 4343974400>, <py30-none-macosx_11_0_arm64 @ 4343974272>, <py30-none-macosx_11_0_universal2 @ 4343974784>, <py39-none-any @ 4343974656>, <py3-none-any @ 4343975040>, <py38-none-any @ 4343975296>, <py37-none-any @ 4343975552>, <py36-none-any @ 4343975808>, <py35-none-any @ 4343988416>, <py34-none-any @ 4343988672>, <py33-none-any @ 4343988928>, <py32-none-any @ 4343989184>, <py31-none-any @ 4343989440>, <py30-none-any @ 4343989696>]
`

**Comment by kumaraditya303** [comment]
Curious to know if your python is running natively using arm binary or it is emulated for x86_64 ?

**Comment by quidnu** [comment]
`% file =python =python3
/opt/local/bin/python:  Mach-O 64-bit executable arm64
/opt/local/bin/python3: Mach-O 64-bit executable arm64
`
`
>>> platform.mac_ver()
('11.1', ('', '', ''), 'arm64')
`

**Comment by kumaraditya303** [comment]
@pavelfeldman Are the browsers compatible for Apple M1 as there is a mac11 arm build on https://devops.aslushnikov.com/

**Comment by kumaraditya303** [comment]
[playwright-0.152.0.post56+g8dba1ff-py3-none-macosx_11_0_universal2.zip](https://github.com/microsoft/playwright-python/files/5768664/playwright-0.152.0.post56%2Bg8dba1ff-py3-none-macosx_11_0_universal2.zip)

Extract the zip file and try to install it with `pip install <filename>`

**Comment by quidnu** [comment]
With that file I now get a permission error, even though I'm running as sudo, not sure why yet.

`PermissionError: [Errno 13] Permission denied: '/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playwright/driver/playwright-cli'`

`-rw-r--r--  1 root  wheel  59774356  5 Jan 16:32 /opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/playwright/driver/playwright-cli`
