### ISSUE TITLE
playwright.helper.Error: geolocation.latitude: precondition -90 <= LATITUDE <= 90 failed

### ISSUE THREAD

**Issue by mrthevinh** [microsoft/playwright-python#333]
I take latitude on google map but dont work in playwright
`playwright.helper.Error: geolocation.latitude: precondition -90 <= LATITUDE <= 90 failed`
````
from playwright import sync_playwright

with sync_playwright() as p:
    iphone_11 = p.devices['iPhone 11 Pro']
    browser = p.webkit.launch(headless=False)
    context = browser.newContext(
        **iphone_11,
        locale='en-US',
        geolocation={'longitude': 21.0066227, 'latitude': 107.2596527},
        permissions=['geolocation']
    )
    page = context.newPage()
    page.goto('https://maps.google.com')
    page.click('text="Your location"')
    page.screenshot(path='colosseum-iphone.png')
    browser.close()
````

**Comment by kumaraditya303** [comment]
> ```
> from playwright import sync_playwright
> 
> with sync_playwright() as p:
>     iphone_11 = p.devices['iPhone 11 Pro']
>     browser = p.webkit.launch(headless=False)
>     context = browser.newContext(
>         **iphone_11,
>         locale='en-US',
>         geolocation={'longitude': 21.0066227, 'latitude': 107.2596527},
>         permissions=['geolocation']
>     )
>     page = context.newPage()
>     page.goto('https://maps.google.com')
>     page.click('text="Your location"')
>     page.screenshot(path='colosseum-iphone.png')
>     browser.close()
> ```

Latitude values can range from -90 to 90 not more than 90 as in your script which is 107.2596527.

**Comment by mrthevinh** [comment]
> 
> 
> > ```
> > from playwright import sync_playwright
> > 
> > with sync_playwright() as p:
> >     iphone_11 = p.devices['iPhone 11 Pro']
> >     browser = p.webkit.launch(headless=False)
> >     context = browser.newContext(
> >         **iphone_11,
> >         locale='en-US',
> >         geolocation={'longitude': 21.0066227, 'latitude': 107.2596527},
> >         permissions=['geolocation']
> >     )
> >     page = context.newPage()
> >     page.goto('https://maps.google.com')
> >     page.click('text="Your location"')
> >     page.screenshot(path='colosseum-iphone.png')
> >     browser.close()
> > ```
> 
> Latitude values can range from -90 to 90 not more than 90 as in your script which is 107.2596527.
Thank you!
I take latitude on google map! How to convert it to playwright Latitude

**Comment by pavelfeldman** [comment]
You probably want to swap those numbers, your lat is 21 and long is 107.25, that puts you somewhere in Cẩm Trung.
