### ISSUE TITLE
Add docs and make MCR image public

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright-python#338]
Follow up on #290. The status is that the image is now getting pushed but it can't get pulled yet publicly, example:

```
docker pull mcr.microsoft.com/playwright-python:next-focal
```

Also there are some docs needed, probably in the readme to reference to it so that people can use it.

**Comment by arjunattam** [comment]
Thanks @mxschmitt! To make it public, we will need to add the playwright-python image to MCR config which is located in these (private) repos: https://github.com/microsoft/mcrdocs and https://github.com/microsoft/mcr
