### ISSUE TITLE
unable to install playwright on ubuntu 18.04

### ISSUE THREAD

**Issue by ranahaani** [microsoft/playwright-python#339]
I am trying to install playwright via this command ```pip3 install playwright```

 Could not find a version that satisfies the requirement playwright (from versions: )
No matching distribution found for playwright

```
Collecting playwright
  Could not find a version that satisfies the requirement playwright (from versions: )
No matching distribution found for playwright

```

**Comment by mxschmitt** [comment]
Hi, could you provide us the output of `pip debug`?

Playwright Python requires Python 3.7+

**Comment by ranahaani** [comment]
yeah, it works with Python 3.8, I was using Python 3.6. 
Thank you
