### ISSUE TITLE
Playwright open 2 tabs when I used launchPersistentContext

### ISSUE THREAD

**Issue by mrthevinh** [microsoft/playwright-python#341]
![image](https://user-images.githubusercontent.com/6493768/101152231-56b8be00-3655-11eb-9515-e6594a06c2a7.png)
````
from playwright import sync_playwright
with sync_playwright() as p:
    iphone_11 = p.devices['iPhone 11 Pro']
    del iphone_11['defaultBrowserType']
    x = 21.0287747
    y = 105.850176
    print(iphone_11)
    browser = p.chromium.launchPersistentContext(headless=False, userDataDir='testfb', **iphone_11,
                                                 locale='en-US',
                                                 geolocation={'longitude': y, 'latitude': x},
                                                 permissions=['geolocation'])
    page = browser.newPage()
    page.goto('https://map.google.com')
    page.click('text="Your location"')
    page.screenshot(path='colosseum-iphone.png')
    input('check tabs')
    browser.close()
````

**Comment by pavelfeldman** [comment]
`launchPersistentContext` gives you a context with a page, not a browser. So you should do something like:

```
context = launchPersistentContext(...)
page = context.pages[0]
```

It is almost always better to use non-persistent `launcBrowser+newContext` combo though.

**Comment by mrthevinh** [comment]
> 
> 
> `launchPersistentContext` gives you a context with a page, not a browser. So you should do something like:
> 
> ```
> context = launchPersistentContext(...)
> page = context.pages[0]
> ```
> 
> It is almost always better to use non-persistent `launcBrowser+newContext` combo though.

Thank you so much!

**Comment by testtolearn1** [comment]
in my case 2 tabs are opening with same url (chrome extension) and one is idle another is active , the active tab is executing testcases, but how to get rid of the idle one
