### ISSUE TITLE
playwright.helper.Error: net::ERR_CERT_AUTHORITY_INVALID at https://1.2.3.4:5678

### ISSUE THREAD

**Issue by BreezyTsan** [microsoft/playwright-python#346]
How to bypass the certificate warning check? How to implement the parameter '--ignore-certificate-errors' in playwright? Thx.

"D:\Program Files\Python38\python.exe" D:/Users/MyName/OneDrive/Python/SpiderWebPage/trx_list.py
Traceback (most recent call last):
  File "D:/Users/MyName/OneDrive/Python/SpiderWebPage/trx_list.py", line 57, in <module>
    run(playwright)
  File "D:/Users/MyName/OneDrive/Python/SpiderWebPage/trx_list.py", line 16, in run
    page.goto("https://1.2.3.4:5678/")
  File "D:\Program Files\Python38\lib\site-packages\playwright\sync_api.py", line 4197, in goto
    self._sync(
  File "D:\Program Files\Python38\lib\site-packages\playwright\sync_base.py", line 107, in _sync
    return future.result()
  File "D:\Program Files\Python38\lib\site-packages\playwright\page.py", line 451, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "D:\Program Files\Python38\lib\site-packages\playwright\frame.py", line 116, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "D:\Program Files\Python38\lib\site-packages\playwright\connection.py", line 39, in send
    result = await callback.future
playwright.helper.Error: net::ERR_CERT_AUTHORITY_INVALID at https://1.2.3.4:5678/
=========================== logs ===========================
navigating to "https://1.2.3.4:5678/", waiting until "load"
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.

Process finished with exit code 1

**Comment by kumaraditya303** [comment]
@BreezyTsan, For ignoring HTTPS warnings you can set `ignoreHTTPSErrors` to `True` while creating the page. Here is the minimal example. [Docs](https://playwright.dev/#version=v1.6.2&path=docs%2Fapi.md&q=browsernewpageoptions--options-ignorehttpserrors)
```py
from playwright import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.newPage(ignoreHTTPSErrors=True)
    page.goto("https://example.com")
    page.close()
```

**Comment by BreezyTsan** [comment]
> @BreezyTsan, For ignoring HTTPS warnings you can set `ignoreHTTPSErrors` to `True` while creating the page. Here is the minimal example. [Docs](https://playwright.dev/#version=v1.6.2&path=docs%2Fapi.md&q=browsernewpageoptions--options-ignorehttpserrors)
> 
> ```python
> from playwright import sync_playwright
> 
> with sync_playwright() as p:
>     browser = p.chromium.launch()
>     page = browser.newPage(ignoreHTTPSErrors=True)
>     page.goto("https://example.com")
>     page.close()
> ```

    browser = playwright.chromium.launch(headless=False)
    context = browser.newContext(ignoreHTTPSErrors=True)

    # Open new page
    page = context.newPage()
Ah! That's in .newContext :-) Thk U

**Comment by kumaraditya303** [comment]
> > @BreezyTsan, For ignoring HTTPS warnings you can set `ignoreHTTPSErrors` to `True` while creating the page. Here is the minimal example. [Docs](https://playwright.dev/#version=v1.6.2&path=docs%2Fapi.md&q=browsernewpageoptions--options-ignorehttpserrors)
> > ```python
> > from playwright import sync_playwright
> > 
> > with sync_playwright() as p:
> >     browser = p.chromium.launch()
> >     page = browser.newPage(ignoreHTTPSErrors=True)
> >     page.goto("https://example.com")
> >     page.close()
> > ```
> 
> ```
> browser = playwright.chromium.launch(headless=False)
> context = browser.newContext(ignoreHTTPSErrors=True)
> 
> # Open new page
> page = context.newPage()
> ```
> 
> Ah! That's in .newContext :-) Thk U

Yup! You can use it in per page or as a whole in a context 🎉

**Comment by pavelfeldman** [comment]
@kumaraditya303 

> Yup! You can use it in per page or as a whole in a context 🎉

FYI, that's not entirely accurate, `browser.newPage` is just creating a context with a page in it already, all the options span across the context.
