### ISSUE TITLE
Ifrmae failed to load when accessing the page with iframe when using page.route function

### ISSUE THREAD

**Issue by oldlwhite** [microsoft/playwright-python#347]
```python
from playwright import async_playwright
import time,asyncio,httpx
async def nn(route,request):
	await route.continue_()
async def main():
	playwright=await async_playwright().start()
	browser=await playwright.chromium.launch(headless=False)
	browser=await browser.newContext()
	page = await browser.newPage()
	await page.route('*', lambda route, request:asyncio.create_task(nn(route,request)))
	await page.goto('https://qycg.enjoy5191.com/platform/entp-purchase/combine/v1/entp-view.html?project_id=387300092060766208&utype=guest&type=%E9%87%87%E8%B4%AD%E5%85%AC%E5%91%8A&method=91010103')
	await browser.close()
	await playwright.stop()
asyncio.get_event_loop().run_until_complete(main())



![image](https://user-images.githubusercontent.com/35679142/101238931-a3b49700-371e-11eb-893f-eb6cacd8d297.png)

**Comment by oldlwhite** [comment]
> '''蟒
> 从剧作家进口async_playwright
> 导入时间，ASYNCIO，httpx
> 异步DEFン（路线，请求）：
> AWAIT route.continue_（）
> 异步DEF主（）：
> 。剧作家= AWAIT async_playwright（）开始（）
> 浏览器= AWAIT剧作家。 chrome.launch （headless = False）
> browser = await browser.newContext（）
> page = await browser.newPage（）
> await page.route（'*'，lambda route，request：asyncio.create_task（nn（route，request）））
> 等待page.goto（' [https://qycg.enjoy5191.com/platform/entp-purchase/combine/v1/entp-view.html?project_id=387300092060766208&utype=guest&type=%E9%87%87%E8%B4%AD ％E5％85％AC％E5％91％8A＆method = 91010103](https://qycg.enjoy5191.com/platform/entp-purchase/combine/v1/entp-view.html?project_id=387300092060766208&utype=guest&type=%E9%87%87%E8%B4%AD%E5%85%AC%E5%91%8A&method=91010103) '）
> 等待browser.close（）
> 等待playwright.stop（）
> asyncio.get_event_loop（）。run_until_complete（main（））'''

**Comment by oldlwhite** [comment]
I use python3.7.6 and playwright0.162.2.

**Comment by pavelfeldman** [comment]
The page looks the same with and without routing, what should I be looking for?
