### ISSUE TITLE
Is is possible to run playwright-codegen command with chrome browser?

### ISSUE THREAD

**Issue by hobin2017** [microsoft/playwright-python#348]
The version of chrome browser is 86.0.4240.198. 
The command below does not have the browser-related option.
```
py -3.7 -m playwright codegen -h
```

**Comment by kumaraditya303** [comment]
@hobin2017 You can use the browser option to set browser. Use `-b` flag followed by the browser name `firefox` for firefox otr `webkit` for webkit

Here a minimal example -
```sh
$ python -m playwright codegen -b firefox 
```
Similarly for webkit it would be -
```sh
$ python -m playwright codegen -b webkit
```

**Comment by hobin2017** [comment]
@kumaraditya303 Can it be configuired to use the `executablePath` option of  `playwright.sync_playwright().chromium.launch` method?

**Comment by pavelfeldman** [comment]
This is not currently supported. Could you share why you need it? Media codecs or something like that?

**Comment by hobin2017** [comment]
The work about `codegen` is amazing. However, there is no matched browser in my computer. It would be nicer if running the demo-code succssfully after `pip install playwright`.

**Comment by kumaraditya303** [comment]
@hobin2017 You can install the browsers using `python -m playwright install`

**Comment by quidnu** [comment]
Is it possible to change the device to mobile?

**Comment by mxschmitt** [comment]
@quidnu yes, you can specify it with the `--device` parameter, see here for examples: https://github.com/microsoft/playwright-cli#emulate-devices

**Comment by pavelfeldman** [comment]
Looks like the issue was resolved, please open new bugs if there are still problems!

**Comment by Louis24** [comment]
> This is not currently supported. Could you share why you need it? Media codecs or something like that?

cuz, some cookies and plugins have install on that google chrome.
