### ISSUE TITLE
Why can't I open the official documentation？

### ISSUE THREAD

**Issue by aquichita** [microsoft/playwright-python#351]
Doesn't my region support browsing official documents?
![image](https://user-images.githubusercontent.com/53226580/101279708-01b8ab80-37ff-11eb-847d-846049222251.png)

**Comment by mxschmitt** [comment]
Looks like issues in your local network that the host `raw.githubusercontent.com` can't get resolved. Try to change your DNS server on your machine to e.g. 8.8.8.8/8.8.4.4 or 1.1.1.1/1.0.0.1

**Comment by pavelfeldman** [comment]
Looks unrelated to Playwright...
