### ISSUE TITLE
如何离线完整安装playwright？

### ISSUE THREAD

**Issue by ZalmonZhang** [microsoft/playwright-python#356]
由于办公电脑受到网络限制，我无法在线安装playwright。
已经下载并安装了playwright-0.162.2-py3-none-win32.whl。
后续的Python -m playwright install 由于网络限制，执行失败。
请问，我该如何做才能正常使用playwright，谢谢。

**Comment by ninjagang** [comment]
Python -m playwright install是用来下载 Chromium、Firefox、WebKit浏览器驱动到本地的，
你把在线电脑的
c:\用户\用户名\appdata\local\ms-playwright下的目录复制到离线电脑上相同的位置就行了

**Comment by pavelfeldman** [comment]
https://playwright.dev/#version=v1.6.2&path=docs%2Finstallation.md&q=managing-browser-binaries has more details for you.
