### ISSUE TITLE
Is it possible to get all requests and responses from network tab? I wanna log all requests and their responses.

### ISSUE THREAD

**Issue by HeikKerimov** [microsoft/playwright-python#358]
It would be cool if you gave me some code snippet) Thx!

**Comment by pavelfeldman** [comment]
```python
from playwright import sync_playwright

with sync_playwright() as playwright:
    browser = playwright.chromium.launch()
    page = browser.newPage()
    page.on("request", lambda request: print("Request: " + request.url))
    page.on("response", lambda response: print("Response: " + response.request.url))
    page.goto("http://webkit.org/")
    browser.close()
```

or

```python
from playwright import sync_playwright

with sync_playwright() as playwright:
    browser = playwright.chromium.launch()
    page = browser.newPage(recordHar={"path": "file.har"})
    page.goto("http://webkit.org/")
    page.close()
    browser.close()
```

for HAR file with all requests and data.

**Comment by HeikKerimov** [comment]
@pavelfeldman Thx for your answer! I did it like this (take a look at the screenshot). It works, but I get warning:
`(node:66575) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Page]. Use emitter.setMaxListeners() to increase limit
`
<img width="541" alt="Снимок экрана 2020-12-15 в 17 03 08" src="https://user-images.githubusercontent.com/19889745/102224759-6955b180-3ef7-11eb-9060-64e75d262e3f.png">

**Comment by mxschmitt** [comment]
> @pavelfeldman Thx for your answer! I did it like this (take a look at the screenshot). It works, but I get warning:
> `(node:66575) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Page]. Use emitter.setMaxListeners() to increase limit `
> <img alt="Снимок экрана 2020-12-15 в 17 03 08" width="541" src="https://user-images.githubusercontent.com/19889745/102224759-6955b180-3ef7-11eb-9060-64e75d262e3f.png">

Thats probably already fixed upstream (https://github.com/microsoft/playwright/issues/4670) and should be soon also released here in the Python project. Since its only a warning it should not result in issues.

**Comment by Duplexes** [comment]
> For anyone that stumbles on this issue when looking for a basic page response, this will help:
> 
> ```python
> page = context.new_page()
> response = page.goto(url)
> print(response.status)  # -> 200
> ```

You are a legend. Thank you!

**Comment by AIGeneratedUsername** [comment]
> response = page.goto(url)
print(response.status)  # -> 200

This must be documented in the first place!

**Comment by jamesbraza** [comment]
I believe as of https://github.com/microsoft/playwright-python/releases/tag/v1.23.0 from June 2022, the keyword arg to use is `record_har_path`:

```diff
---    page = browser.newPage(recordHar={"path": "file.har"})
+++    page = browser.new_page(record_har_path="file.har")
```
