### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir '/root/.cache/ms-playwright'

### ISSUE THREAD

**Issue by andy0andy** [microsoft/playwright-python#364]
A nodejs error was reported when I installed the driver interrupt and then installed. Is this related to the nodejs version? Where can you modify it and install it normally? I'm not familiar with nodejs.

**Comment by mxschmitt** [comment]
Under which user and how do you run it?

It seems like it does not have write write permissions to `$PWD/.cache/ms-playwright`, so maybe the `/root` directory has the wrong permissions or are you using sudo?

**Comment by andy0andy** [comment]
> Under which user and how do you run it?
> 
> It seems like it does not have write write permissions to `$PWD/.cache/ms-playwright`, so maybe the `/root` directory has the wrong permissions or are you using sudo?

(node:6030) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir '/root/.cache/ms-playwright'
(node:6030) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6030) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by andy0andy** [comment]
> Under which user and how do you run it?
> 
> It seems like it does not have write write permissions to `$PWD/.cache/ms-playwright`, so maybe the `/root` directory has the wrong permissions or are you using sudo?

There are two mistakes. I don't understand why nodejs is wrong？

**Comment by Helloyanxuan** [comment]
python -m playwright install
(node:25900) UnhandledPromiseRejectionWarning: Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)
(node:25900) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:25900) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I don't konw what happen

**Comment by mxschmitt** [comment]
Closed since it seems to be an issue of miss-configured permissions. For the last comment the issue seems either a firewall issue or a temporary network issue. Feel free to file it again if its reproducible.
