### ISSUE TITLE
how to open parallel browser to speed up

### ISSUE THREAD

**Issue by tahseen2k8** [microsoft/playwright-python#368]
I have tried with multi-threading and its not working . then i have tried with multiprocessing but its still seems very slow .
how can i make parallel calls using sync or async . any lead please .

**Comment by pavelfeldman** [comment]
Check out our tests - we are using pytest to parallelize. These are playwright fixtures: https://github.com/microsoft/playwright-pytest

**Comment by kumaraditya303** [comment]
@tahseen2k8 You can speed up the testing using [pytest-xdist](https://github.com/pytest-dev/pytest-xdist) by increasing worker count. See it in action in my project https://github.com/kumaraditya303/Fantastic-Django-Blog/blob/e1254d765ec336d6075dffd465002970dde4f532/setup.cfg#L13 as by using the option `-n` for worker count.

**Comment by pavelfeldman** [comment]
Please feel free to open new issue with more questions!
