### ISSUE TITLE
Support string-like objects for urls etc

### ISSUE THREAD

**Issue by strozzapreti** [microsoft/playwright-python#369]
It would be convenient if all areas of the Playwright API were able to support string-like objects which are not necessarily JSON-serializable. It sounds like Path() support for things like `videosPath` is already planned, but another nice-to-have would be the url argument for Page.goto(). 

For instance, I could pass an instance of the following example class as a url argument for session.get() using Requests, but not Playwright:

```
class FormattedUrl:
    def __init__(self, host, page, protocol='https', **params):
        self.host = host
        self.page = page
        self.protocol = protocol
        self.parameters = params
    
    def __str__(self):
        return self._format()
    
    def _format(self):
        if self.parameters:
            return f'{self.protocol}://{self.host}/{self.page}?{urlencode(self.parameters)}'
        return f'{self.protocol}://{self.host}/{self.page}'
```

If I try to pass an instance of that class to Page.goto(), I get a `Object is not JSON serializable` error. 

The stack trace for the error appears to point to the Transport.send() method in transport.py

At the moment, I have to wrap all of my objects in `str()` before passing them to any Playwright API method

**Comment by pavelfeldman** [comment]
I was looking into doing that, but since Playwright is typed, it would make be relax the types for the URL, etc. So I'd probably say `str()` is the way to go...

**Comment by strozzapreti** [comment]
Even with the typing, I think subclasses of str would still be allowed, e.g.:
```
class FormattedUrl(str):
    ...
```
For now I'm ok converting to str, since it's relatively rare that we want to navigate directly to a URL with `gogo` anyway.
