### ISSUE TITLE
What are some ways that I can stop the page from doing something, and then I want the page to not close, but I can close the page manually

### ISSUE THREAD

**Issue by lucky-blues** [microsoft/playwright-python#372]
for example
`from playwright import sync_playwright
def first_start():
    with sync_playwright() as playwright:
        browser_server = playwright.chromium.launchServer(headless=False, port=8848)  # browser_server_obj
        print(browser_server)
        endpoint = browser_server.wsEndpoint
        print(endpoint)
        browser = playwright.chromium.connect(
            endpoint
        )
        context = browser.newContext()
        page = context.newPage()
        page.goto(url='http://www.baidu.com', waitUntil='networkidle')
        page.content()
        print(page.isClosed())
        page.close(runBeforeUnload=True)  
        print(page.isClosed())
if __name__ == '__main__':
    first_start()`
I used the playwright=0.8

**Comment by pavelfeldman** [comment]
Could you share more about your use case?

**Comment by pavelfeldman** [comment]
for now, you can say `page.waitForTimeout(100000000)`
