### ISSUE TITLE
ModuleNotFoundError: No module named 'playwright.main'

### ISSUE THREAD

**Issue by pzelnip** [microsoft/playwright-python#373]
Created a file test_playwright.py that contained:

```
def test_django_admin_login(page):
    page.goto("http://127.0.0.1:5001/admin/")
    page.type("input[name=username", "admin")
    page.type("input[name=password", "admin")
    page.click("input[type=submit")
```

Tried running by:

```
python -m pytest --headful
```

and get:

```Traceback (most recent call last):
  File "/Users/pzelnip/.pyenv/versions/3.9.0/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,

...many lines...

  File "/Users/pzelnip/.virtualenvs/onboardingdjango2py39/lib/python3.9/site-packages/pytest_playwright/pytest_playwright.py", line 23, in <module>
    from playwright.main import SyncPlaywright
ModuleNotFoundError: No module named 'playwright.main'
```

I have playwright and pytest-playwright installed:

```
$ pip list | grep playwright
playwright            0.170.0
pytest-playwright     0.0.9
```

What am I missing?

**Comment by mxschmitt** [comment]
Hi thanks for reporting! https://github.com/microsoft/playwright-pytest/pull/32 fixes it.

**Comment by pzelnip** [comment]
Awesome, was this a regression introduced in 0.170.0?  Ie if I install a prior version would the issue also be resolved?

**Comment by mxschmitt** [comment]
> Awesome, was this a regression introduced in 0.170.0? Ie if I install a prior version of the pytest plugin would the issue also be resolved?

It's an internal change which was introduced in the latest version of Playwright for Python since it uses an internal API.

**Comment by pzelnip** [comment]
Looks like yeah, I downgraded back to 0.162.2 and it worked as expected.  Thanks, will close this off since this issue is being tracked on the pytest-playwright repo.

**Comment by mxschmitt** [comment]
@pzelnip version 0.0.10 of pytest-playwright got released which fixes that issue. Thanks for reporting!
