### ISSUE TITLE
Troubleshoot timeout errors

### ISSUE THREAD

**Issue by kbreit** [microsoft/playwright-python#391]
I have Playwright deployed within containers on Kubernetes. Starting this weekend I've been receiving timeout errors for sites that use Playwright for connectivity. Are there suggestions on how to troubleshoot this and see what it's querying?

My suspicion is it has to do with new IPv6 connectivity. On my desktop these sites are all using IPv4 and I wonder if it's trying IPv6 first and timing out before it can try IPv4.

**Comment by Mattwmaster58** [comment]
`DEBUG=pw:api` would be a good place to start I would think

**Comment by pavelfeldman** [comment]
Since you are bringing up the IPv6 vs IPv4, it looks like your problem is lower level than Playwright. Not sure we can offer anything on top of the pw:api mentioend above.
