### ISSUE TITLE
page.waitForEvent('dialog') not work, click() hangs on alert box

### ISSUE THREAD

**Issue by ducalpha** [microsoft/playwright-python#396]
I want to accept an alert dialog after the popup box was invoked by clicking a button.

Expected result: `page.waitForEvent('dialog')` returns after the dialog appeared.
Actual result: `playwright` hangs at `button.click()`

Reproduction of the issue:
```
with sync_playwright() as p:
    browser = p.chromium.launch(headless=False, slowMo=1000)
    page = browser.newPage()
    page.goto("https://cdpn.io/nishanc/fullpage/NWWPdZE", waitUntil='networkidle')
    frame = page.frames[1]

    print('Waiting for selector')
    button = frame.waitForSelector('xpath=/html/body/button[1]')

    print('Clicking ...')
    button.click()  # Hangs here. noWaitAfter=True did not work neither.
    print('Clicked')

    page.waitForEvent('dialog')  # Wanted to accept the dialog here.

    browser.close()
```

**Comment by dld8888** [comment]
I have the same problem: unable to confirm or cancel the dialog

**Comment by mxschmitt** [comment]
You can do that which should work, does this fit for your use case?

```py
from playwright import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch(headless=False, slowMo=1000)
    page = browser.newPage()
    page.setContent("""
        <button onclick="alert()">foobar</button>
    """)
    page.on("dialog", lambda dialog: dialog.dismiss())

    page.click("button")

    browser.close()
```

**Comment by ducalpha** [comment]
> ```python
> from playwright import sync_playwright
> 
> with sync_playwright() as p:
>     browser = p.chromium.launch(headless=False, slowMo=1000)
>     page = browser.newPage()
>     page.setContent("""
>         <button onclick="alert()">foobar</button>
>     """)
>     page.on("dialog", lambda dialog: dialog.dismiss())
> 
>     page.click("button")
> 
>     browser.close()
> ```

Thanks, this code does work and I am using a similar `page.on()` in my code. However, the documentation [https://microsoft.github.io/playwright-python/sync_api/](https://microsoft.github.io/playwright-python/sync_api/) does not have any description for `page.on()` so I did not expect it is an official API. Furthermore, `page.waitForEvent('dialog')` API seems more natural for me.

**Comment by zhonghai9967** [comment]
page.on("dialog", lambda dialog: dialog.dismiss())
It is recommended to write in the document.

**Comment by pavelfeldman** [comment]
This will be in the 1.8 docs.

**Comment by buddemat** [comment]
I have been trying this as well, but for me it did not work for a browser dialog, i.e. a dialog opened by firefox (in this case) to ask whether to open or save a file. Do these dialogs not trigger a `dialog` event? How can I accept or dismiss such a dialog?
