### ISSUE TITLE
specific URL cannot be opened in the browser

### ISSUE THREAD

**Issue by zxzhuty** [microsoft/playwright-python#397]
specific url : http://43.248.49.97 (I can access it through my browser)

code:
```
browser = playwright.chromium.launch(headless=False)
context = browser.newContext()
page = context.newPage()
page.goto(url)

```
The browser will prompt you with a 400 error

but,If I change browser type

`browser = playwright.firefox.launch(headless=False)`

Everything will be fine.

error have to do with browser types

**Comment by mxschmitt** [comment]
I investigated a bit, seems like they some advanced bot detection logic on the JavaScript land to determine if you are automated or not. I tried to change the User-Agent but wasn't successful with that.

**Comment by pavelfeldman** [comment]
Closing as per comment above.

**Comment by punkpeye** [comment]
You could use https://github.com/apify/crawlee, which is a wrapper around Playwright that bypasses such checks
