### ISSUE TITLE
Unable to catch download error

### ISSUE THREAD

**Issue by zxzhuty** [microsoft/playwright-python#398]
I'm using the Firefox browser

```
 browser = playwright.firefox.launch(headless=False,downloadsPath=os.getcwd())
 context = browser.newContext(acceptDownloads=True)
```

related code:

```
with page.expect_download(timeout=120000) as download_info:
       page.click("text=\"xxxx\"")
download = download_info.value
download.saveAs(path)
```
In case of transient network failure(just a millisecond)
(You can try to unplug the network cable while downloading large files(http://speed.hetzner.de/). ^◡^)

The browser will prompt me:

![image](https://user-images.githubusercontent.com/202441/103112233-026e9000-468f-11eb-806d-a4d4f255faf0.png)

playwright can't continue,At the same time, unable to catch error until the application completes.

In the automatic test, we can not get the expected results.

**Comment by JoelEinbinder** [comment]
This looks like an issue with our firefox support. I moved it to the main playwright repo.
