### ISSUE TITLE
firefox error

### ISSUE THREAD

**Issue by ywlfff** [microsoft/playwright-python#408]
when i use this code ,it is error.
from playwright import sync_playwright

with sync_playwright() as p:
    # for browser_type in [p.chromium, p.firefox, p.webkit]:
    browser_type = p.firefox
    browser = browser_type.launch(
        headless=False,
        executablePath=r"C:\Program Files (x86)\Mozilla Firefox\firefox.exe"
        # executablePath=r"C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe"
        # executablePath=r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
    )
    page = browser.newPage()
    page.goto('http://whatsmyuseragent.org/')
    page.waitForTimeout(100000)
    browser.close()

error---------------------------------------
����: û���ҵ����� "3512"��
Traceback (most recent call last):
  File "F:/MyCodes/nk_monitor/test.py", line 8, in <module>
    executablePath=r"C:\Program Files (x86)\Mozilla Firefox\firefox.exe"
  File "C:\Users\Administrator\.virtualenvs\nk_monitor\lib\site-packages\playwright\sync_api.py", line 6990, in launch
    firefoxUserPrefs=mapping.to_impl(firefoxUserPrefs),
  File "C:\Users\Administrator\.virtualenvs\nk_monitor\lib\site-packages\playwright\_sync_base.py", line 97, in _sync
    return future.result()
  File "C:\Users\Administrator\.virtualenvs\nk_monitor\lib\site-packages\playwright\_browser_type.py", line 78, in launch
    raise e
  File "C:\Users\Administrator\.virtualenvs\nk_monitor\lib\site-packages\playwright\_browser_type.py", line 74, in launch
    return from_channel(await self._channel.send("launch", params))
  File "C:\Users\Administrator\.virtualenvs\nk_monitor\lib\site-packages\playwright\_connection.py", line 36, in send
    return await self.inner_send(method, params, False)
  File "C:\Users\Administrator\.virtualenvs\nk_monitor\lib\site-packages\playwright\_connection.py", line 47, in inner_send
    result = await callback.future
playwright._types.Error: Protocol error (Browser.enable): Browser closed.
==================== Browser output: ====================
<launching> C:\Program Files (x86)\Mozilla Firefox\firefox.exe -no-remote -wait-for-browser -foreground -profile C:\Users\ADMINI~1\AppData\Local\Temp\playwright_firefoxdev_profile-42kvVM -juggler-pipe -silent
<launched> pid=3512
[err] Can't find symbol 'eglSwapBuffersWithDamageEXT'.
[err] 
[err] ###!!! [Child][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost
[err] 
[err] 
[err] ###!!! [Child][MessageChannel::SendAndWait] Error: Channel error: cannot send/recv
[err] 
=========================== logs ===========================
<launching> C:\Program Files (x86)\Mozilla Firefox\firefox.exe -no-remote -wait-for-browser -foreground -profile C:\Users\ADMINI~1\AppData\Local\Temp\playwright_firefoxdev_profile-42kvVM -juggler-pipe -silent
<launched> pid=3512
[err] Can't find symbol 'eglSwapBuffersWithDamageEXT'.
[err] 
[err] ###!!! [Child][RunMessage] Error: Channel closing: too late to send/recv, messages will be lost
[err] 
[err] 
[err] ###!!! [Child][MessageChannel::SendAndWait] Error: Channel error: cannot send/recv
[err] 
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.

进程已结束，退出代码 1

**Comment by mxschmitt** [comment]
Hi, using the `executablePath` only works with Firefox and WebKit with the bundled browsers, since they are slightly modified to provide the APIs to interact and communicate with Playwright. Using the normal Firefox won't work.

For Chromium you can as I saw use e.g. Microsoft Edge or Google Chrome which works if they are up to date.

**Comment by ywlfff** [comment]
> Hi, using the `executablePath` only works with Firefox and WebKit with the bundled browsers, since they are slightly modified to provide the APIs to interact and communicate with Playwright. Using the normal Firefox won't work.
> 
> For Chromium you can as I saw use e.g. Microsoft Edge or Google Chrome which works if they are up to date.

Thank you!where can i download this firefox?

**Comment by hkfsc** [comment]
> Hi, using the `executablePath` only works with Firefox and WebKit with the bundled browsers, since they are slightly modified to provide the APIs to interact and communicate with Playwright. Using the normal Firefox won't work.
> 
> For Chromium you can as I saw use e.g. Microsoft Edge or Google Chrome which works if they are up to date.

I hope playwright can work correctly with normal firefox like chromium browsers...
Might can check:
https://github.com/mozilla/gecko-dev/
https://github.com/jpramosi/geckordp
