### ISSUE TITLE
How to judge whether an element visble or not? ？

### ISSUE THREAD

**Issue by zhonghai9967** [microsoft/playwright-python#409]
page.querySelector('tbody>tr:nth-child(2)>input')
If it is not found, an error occurs, causing the script to break

Something like that：
How can I tell if a selection box has been selected?
thank you

**Comment by pavelfeldman** [comment]
`page.querySelector('tbody>tr:nth-child(2)>input')` should not throw an error, it will return Null. If you are waiting for the element, you should use `waitForSelector`.

What do you mean selection box selected? Is that <select> or <input> checkbox?

**Comment by pavelfeldman** [comment]
Please feel free to file another issue if it this still does not work for you.
