### ISSUE TITLE
how to run playwright-python without interface

### ISSUE THREAD

**Issue by Fanchengyan** [microsoft/playwright-python#410]
I find  `playwright-python` can't run without interface... 

1. when I run it in vscode ,it will raise `Error: Can only run one Playwright at a time.`
2. when I run it via ssh, it can't find chomeium... and ask me to install it via `python -m playwright install`. As a result, **I can't run it via crontab on linux...**

**Comment by pavelfeldman** [comment]
You mean in terminal? How do you run it in vscode? How did you install it? That's how everyone uses it, so it should work!

**Comment by Fanchengyan** [comment]
> You mean in terminal? How do you run it in vscode? How did you install it? That's how everyone uses it, so it should work!

No, not in the terminal. It's a jupyter environment? I just need press the `Shift + Enter` in a cell, and code will be send to **Interactive window** which just like running in spyder.

![截图录屏_选择区域_20210115110250](https://user-images.githubusercontent.com/24694181/104675906-582fd880-5721-11eb-8c26-ef33d76067f4.png)

**Comment by mborus** [comment]
@Fanchengyan: There is a open issue running Playwright in Jupyter:
[https://github.com/microsoft/playwright-python/issues/178](https://github.com/microsoft/playwright-python/issues/178)
with workarounds discussed at the end of the thread.

If this is too much trouble to get to work: FYI: I do my interactive playwright in PyCharm's debugger session and am slowly moving to IPython's ipdb, which allows notebook-like exploration with autocompletion.

**Comment by pavelfeldman** [comment]
Another option would be to use async API while in Jupyter!

**Comment by pavelfeldman** [comment]
Looks like the issue was resolved, please open new bugs if there are still problems!
