### ISSUE TITLE
Please give an example of Sync  dialog, thank you

### ISSUE THREAD

**Issue by dld8888** [microsoft/playwright-python#411]
**After clicking a button, a dialog box pops up. What should I do?**

papg.click('text="save"')
dialog.accept()  //From the error message, it didn't run here

Thank you very much. Can anyone provide help or guidance?

**Comment by mxschmitt** [comment]
Hi, I posted an solution here: https://github.com/microsoft/playwright-python/issues/396#issuecomment-753890258

Please close this issue, since its a duplicate.

**Comment by dld8888** [comment]
@mxschmitt
thank you!
The last problem of using playwright is solved.

**Comment by dld8888** [comment]
It is strongly recommended to write the solution into the document
