### ISSUE TITLE
playwright  Unable to click the drop-down box

### ISSUE THREAD

**Issue by 554159290** [microsoft/playwright-python#412]
when I click the drop-down box can't not pop down selection

**Comment by JoelEinbinder** [comment]
I think you need to select the option directly instead of clicking: https://playwright.dev/docs/api/class-elementhandle?_highlight=.select#elementhandleselectoptionvalues-options

**Comment by July-20** [comment]
![image](https://user-images.githubusercontent.com/56582712/103993198-3211b200-51d0-11eb-832e-502218bce596.png)
when I click the drop-down box can't not pop down selection

**Comment by pavelfeldman** [comment]
You should use `page.selectOption()` instead!
