### ISSUE TITLE
How to modify element attributes?

### ISSUE THREAD

**Issue by zhonghai9967** [microsoft/playwright-python#416]
I have an element that contains the readonly attribute. How can I delete this attribute? For example:
\<input>datainput readonly="readonly"\</input>
Is it similar to  set_ Attrib()  method？

**Comment by mxschmitt** [comment]
Can be done like `page.evalOnSelector(".myelement", "el => el.removeAttribute('readonly'))"`. Keep it mind, evalOnSelector does not wait for the element, so you might have to add page.waitForSelector first.

**Comment by zhonghai9967** [comment]
Thank you very much

**Comment by mhersim** [comment]
> page.evalOnSelector(".myelement", "el => el.removeAttribute('readonly'))"

Thank you for answer:
but as I see it is for JS, so for Python answer will be following:
page.eval_on_selector(".myelement", "el => el.removeAttribute('readonly')")
