### ISSUE TITLE
how to use this  property 

### ISSUE THREAD

**Issue by xueneymar** [microsoft/playwright-python#422]
![image](https://user-images.githubusercontent.com/13958555/104314130-f1899f80-5513-11eb-939d-a864d23befa8.png)

i wanna use this property in red circle to excute click action, how cai i make that possiable

**Comment by mxschmitt** [comment]
What do you mean with use? You want to get the inner text of the element? `page.innerText(".tree-title")` should work.

**Comment by kumaraditya303** [comment]
You can use `page.click(".tree-title")`

**Comment by xueneymar** [comment]
> You can use `page.click(".tree-title")`

![image](https://user-images.githubusercontent.com/13958555/104401034-5a156280-558e-11eb-8fd4-d368d4959366.png)
i hava this issue  ，though tree-title‘s name chose box to click

**Comment by xueneymar** [comment]
> What do you mean with use? You want to get the inner text of the element? `page.innerText(".tree-title")` should work.

i wanna  chose box to click though tree-title‘s name
![image](https://user-images.githubusercontent.com/13958555/104401328-ee7fc500-558e-11eb-888a-202964517347.png)
