### ISSUE TITLE
[Question] playwright do not install chromium when deploy

### ISSUE THREAD

**Issue by niemtin6789** [microsoft/playwright-python#429]
i deploy with Pyinstaller (i run very well in my computer) but when i run at another computer, chromium not download to another computer. how i can fix this.

thanks

**Comment by yury-s** [comment]
I guess playwright installer doesn't pick up browsers cache (which is expected), you need to run `python -m playwright install` on the new machine to download the browsers there.

**Comment by niemtin6789** [comment]
Thanks you. do it not download auto when run playwright?

**Comment by yury-s** [comment]
No, this is in particular why you need to run the second line from the [usage guide](https://github.com/microsoft/playwright-python#usage).
