### ISSUE TITLE
[Question] how does chromium download file

### ISSUE THREAD

**Issue by zhaoyi126** [microsoft/playwright-python#434]
from playwright import sync_playwright

def run(playwright):
    browser = playwright.chromium.launch(headless=False)
    context = browser.newContext()

    # Open new page
    page = context.newPage()

    # Go to https://www.python.org/
    page.goto("https://www.python.org/")

    # Click text="Documentation"
    page.click("text=\"Documentation\"")
    # assert page.url == "https://www.python.org/downloads/"

    # Go to https://www.python.org/doc/
    page.goto("https://www.python.org/doc/")

    # Click text="Documentation"
    page.click("text=\"Documentation\"")

    # Click text="Downloads"
    page.click("text=\"Downloads\"")
    # assert page.url == "https://www.python.org/downloads/"

    # Click section[role="main"] >> text=/.*Download.*/
    page.click("section[role=\"main\"] >> text=/.*Download.*/")
    # assert page.url == "https://www.python.org/downloads/release/python-387/"

    # Click text=/.*Windows embeddable package \(32.*/
    with page.expect_download() as download_info:
        page.click("text=/.*Windows embeddable package \(32.*/")
    download = download_info.value

    # Click text=/.*Windows embeddable package \(32.*/
    with page.expect_download() as download_info:
        page.click("text=/.*Windows embeddable package \(32.*/")
    download = download_info.value

    # Close page
    page.close()

    # ---------------------
    context.close()
    browser.close()

with sync_playwright() as playwright:
    run(playwright)

**Comment by zhaoyi126** [comment]
python3.7.9
playwright 0.171.1

win x64

**Comment by pavelfeldman** [comment]
Is this a question or a bug report? Please clarify!

**Comment by kumaraditya303** [comment]
@zhaoyi126 For downloading file you need to specify `downloads_path` while launching the browsers https://playwright.dev/python/docs/api/class-browsertype/#browser_typelaunchoptions else the downloaded file would be deleted after the browser closes.

**Comment by pavelfeldman** [comment]
Looks like this was answered ^^

**Comment by Toetoise** [comment]
@zhaoyi126 After adding the `download_paths` parameter when you create the browser, you also need to add the `accept_downloads` parameter when you create the page
