### ISSUE TITLE
how to use playwright-python save web page to html or docx, txt, etc

### ISSUE THREAD

**Issue by loveJasmine** [microsoft/playwright-python#435]

**Comment by mxschmitt** [comment]
Is your goal to download a specific file or save the whole page like in Chrome with the "Save as" feature?

![image](https://user-images.githubusercontent.com/17984549/104949854-ea550c80-59bf-11eb-9fc5-e363ebe39b4b.png)

**Comment by loveJasmine** [comment]
how to use 
playwright-python
 to save web page to html or docx, txt, etc

**Comment by pavelfeldman** [comment]
You can get HTML markup using `page.content()`, but that would only be the main html file, not resources. You can also do `page.pdf()`, but there is no saving the complete web page as a folder.

**Comment by loveJasmine** [comment]
@pavelfeldman ， 
so , playwright , 
an open source project which provide by Microsoft, 
can save web page to PDF, but not MS words? 
a little funny

**Comment by pavelfeldman** [comment]
I am glad you had some fun over it :) Closing as it has been answered, please feel free to open bugs if there are other issues!

**Comment by mxschmitt** [comment]
@b3wsh it's not possible to do that programmatically yet. What is your exact use-case for that? then we can open a feature request for it.

**Comment by jeremyheiler** [comment]
@mxschmitt My use-case is to provide a test suite for automations without hitting a live site.

**Comment by BotHire** [comment]
Parse it into google docs 😝😝

**Comment by mezhgano** [comment]
Facing the same objective and found this issue:
https://github.com/microsoft/playwright/issues/18645

Although it for original playwright framework, seems like playwright-python had the same ability:
https://playwright.dev/python/docs/api/class-cdpsession

Don't tried it yet, but maybe this links will help somebody found additional solution

**Comment by fawazahmed0** [comment]
Thanks @mezhgano, your gist is very helpful.

**Comment by lzy37ld** [comment]
@mxschmitt, Hi do we have this feature now?
My use case is to save the files just like clicking "Save As" and then edit the html resources accordingly. I know mhtml could save the snapshots but the public tools only could parse mhtml into html while ignoring more other resources. I want to keep all resources there
