### ISSUE TITLE
[Question] Check if element exists fails 

### ISSUE THREAD

**Issue by chwba** [microsoft/playwright-python#437]
https://patrickhlauke.github.io/recaptcha/ Im trying to determine whether or not the recaptcha container exists.

I tried:

`page.waitForSelector(text="I'm not a robot")`
and
`x_frame = page.frame(name="name_of_frame");  x_frame.waitForSelector("text=I'm not a robot")`
`page.waitForSelector("css=.g-recaptcha", timeout=1, state="attached")` also fails

Ultimately solved it by:

```python
is_captcha_required = False
for frame in self.page.frames:
    if 'not a robot' in frame.content():
        is_captcha_required = True
        break
```
but i dont consider that clean

**Comment by pavelfeldman** [comment]
The iframe is not named, it does not have id, does not have URL, so you can't identify it really. Traversing iframes is the only way to find the one that has captcha...

**Comment by chwba** [comment]
Hmm yeah, after looking at the regex again, if I used *google* for url it does find the iframe but the iteration should work in most cases and is maybe even a fair solution for now.
