### ISSUE TITLE
[Question] How to find an element by class name?

### ISSUE THREAD

**Issue by chwba** [microsoft/playwright-python#438]

**Comment by mxschmitt** [comment]
Hi, you can use CSS selectors with Playwright, so something like this will work in e.g. `click`, `fill`, `querySelector` etc.

`.fooobar`

See here for more information: https://playwright.dev/docs/api/working-with-selectors?_highlight=select

**Comment by chwba** [comment]
Thanks for the quick response. So if the class is named .foobar I can do for instance page.querySelector(".foobar"), do I get that correctly?

**Comment by pavelfeldman** [comment]
Yes, although typically you would say `page.waitForSelector(.foobar)` for an element with `class=foobar`.
