### ISSUE TITLE
Using logger with playwright-python

### ISSUE THREAD

**Issue by amittendulkar** [microsoft/playwright-python#440]
I can currently get logger output on screen using `DEBUG=pw:api` environment variable.

However, it is possible to get the output to a file specified by the caller using the logging module?

For e.g., I am building a custom RobotFramework library and want the Playwright logging to get merged into RobotFramework HTML log output.

**Comment by kumaraditya303** [comment]
@amittendulkar There is a feature request on the main repo, you can upvote that https://github.com/microsoft/playwright/issues/6465

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/6465
