### ISSUE TITLE
[Question|Suggestion] Trouble understanding the selector syntax

### ISSUE THREAD

**Issue by chwba** [microsoft/playwright-python#449]
So for instance I have this piece of HTML:
```html
<input type="text" name="vb_login_username" id="navbar_username" size="15" accesskey="u" tabindex="96" value="User Name" onfocus="if (this.value == 'User Name') this.value = '';">
```
(from: https://www.elitepvpers.com)

I tried:
`page.click('css=[name=vb_login_username]', timeout=1)`, `page.click('css=[id=navbar_username]', timeout=1)`, `page.click('xpath=//*[@id="navbar_username"]', timeout=1)`, `page.click('#navbar_username', timeout=1)`
What am I doing wrong? As far as I had understood https://playwright.dev/docs/selectors/ thats the way I should do it.

And I wonder why inside the playwright browser there is no option to copy the full xpath, see here:
![1359-777-max](https://user-images.githubusercontent.com/22568014/105188556-4f317380-5b34-11eb-917d-1f3ff50a22e7.png)
-> EDIT: I checked in the regular firefox apparently the option to copy the full XPATH does not exist there, only in chrome it exists.

**Comment by pavelfeldman** [comment]
run `python -m playwright codegen` and hover over the input!

**Comment by chwba** [comment]
> run `python -m playwright codegen` and hover over the input!

Not sure how I made that work, im using PyCharm, anyway the full xpath option is the smaller problem im having, the actual problem is the syntax of the selectors, can you hint me what I am doing wrong there?

**Comment by pavelfeldman** [comment]
Ah, sorry, I did not understand your question. I guess timeout of 1 millisecond is not enough!

**Comment by chwba** [comment]
Even If I set the timeout to 30 seconds it does not find this element.

**Comment by dgozman** [comment]
I just tried `page.click('css=[name=vb_login_username]')` and it works for me. Could you please share your script, or run with `DEBUG=pw:api` environment variable and share the logs here?

**Comment by pavelfeldman** [comment]
Closing as stale! Please feel free to file a new issue with additional details.
