### ISSUE TITLE
pypi plw 0.171.1. but not v1.8.0a1 & AttributeError: 'Page' object has no attribute 'query_selector'

### ISSUE THREAD

**Issue by osmenia** [microsoft/playwright-python#452]
Hi Team,

I want to test how works Plw with Py.

```
def run(playwright):
    browser = playwright.chromium.launch(headless=False)
    context = browser.newContext(acceptDownloads=True)

    page = context.newPage()

    page.goto(
        "https://file-examples.com/index.php/sample-documents-download/sample-xls-download/")

    handles = page.query_selector_all("#table-files .file-link")
    print(handles)
```

AttributeError: 'Page' object has no attribute 'query_selector_all'

maybe here is problem with version i am using: playwright 0.171.1

**Screenshot made today**

can you pls update pypi plw v1.8.0a1

![image](https://user-images.githubusercontent.com/39949324/105363179-0cd36980-5bfc-11eb-8cca-d98b505c7156.png)

**Comment by mxschmitt** [comment]
Yesterday a pre-release was published for 1.8.0a1: https://pypi.org/project/playwright/1.8.0a1/

You can install it with `pip install playwright==1.8.0a1`. It gets published as a normal version soon afaik.
