### ISSUE TITLE
Cannot get playwright example to work on macOS BigSur (Intel CPU)

### ISSUE THREAD

**Issue by DaBrondo** [microsoft/playwright-python#453]
I receive this error when running the sync example code:

**ImportError: cannot import name 'sync_playwright' from 'playwright.sync_api'**

I've used venv to create a Python3 virtual environment and playwright installed via pip into that environment.

**Comment by basic-ph** [comment]
First time with playwright for me and I've received the same error:
```(venv) acid@who-knows:~/dev/play$ python simple.py
Traceback (most recent call last):
  File "simple.py", line 1, in <module>
    from playwright.sync_api import sync_playwright
ImportError: cannot import name 'sync_playwright' from 'playwright.sync_api' (/home/acid/dev/play/venv
/lib/python3.8/site-packages/playwright/sync_api.py)
```
I'm using Ubuntu 20.04 through WSL (version 2) and I installed playwright inside a virtualenv using:
```
$ pip install playwright
$ python -m playwright install
```

**Comment by pavelfeldman** [comment]
Please make sure you are using playwright==1.8.0a1 since the docs were all updated to match our v1 offering.

**Comment by pavelfeldman** [comment]
I'll make sure our samples for installation suggest that explicitly. Sorry for inconvenience!

**Comment by basic-ph** [comment]
Thank you for help @pavelfeldman
May be useful to tell explicitly also that the are also some dependencies not installed using:
```
$ pip install playwright
$ python -m playwright install
```
I don't know if this is a situation related only to WSL or not but I got this message:
```
playwright._impl._api_types.Error: Host system is missing dependencies!

Install missing packages with:
sudo apt-get install libnss3\
  libnspr4\
  libatk1.0-0\
  libatk-bridge2.0-0\
  libcups2\
  libxkbcommon0\
  libgbm1\
  libgtk-3-0\
  libpango-1.0-0\
  libcairo2\
  libgdk-pixbuf2.0-0\
  libatspi2.0-0
  ```
  PS: I think the suggested command (`apt-get install ...`) needs whitespaces after each package name to work

**Comment by pavelfeldman** [comment]
It looks like the original issue has been resolved and a new one filed for dependencies. Closing.

**Comment by AnaKuzina** [comment]
Hi, I'm unsuccessfully  trying to use playwright. I've got this error:
`ImportError: cannot import name 'sync_playwright' from 'playwright' (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/playwright/__init__.py)`

though I've installed playwright using this command:
`pip install playwright==1.8.0a1`

Please help me solve the issue. Thank!

**Comment by Matoo125** [comment]
I have the same issue. When I run
```
from playwright import sync_playwright
```
I'll get

```
ImportError: cannot import name 'sync_playwright' from 'playwright' (/home/matej/.pyenv/versions/metaculus/lib/python3.8/site-packages/playwright/__init__.py)
```

**Comment by vitorbferna** [comment]
I am having this same problem, what should I do?

**Comment by Galaxyjia** [comment]
cannot import name 'sync_playwright' from 'playwright.sync_api' 

I can run it somedays ago,but when i update mac os to the latest.It is wrong

**Comment by nileshpandey3** [comment]
I am still facing the same issue with the below import statement 
`from playwright.sync_api import sync_playwright` but when I change it to `from playwright import sync_playwright` i don't get the import error

**Comment by josh-ashkinaze** [comment]
Hi, bumping this. One issue I have is that it does not look like there is a `playwright==1.8.0a1` version anymore

**Comment by tonmoyazad** [comment]
<img width="729" alt="Screen Shot 2021-11-15 at 12 37 15 PM" src="https://user-images.githubusercontent.com/56891044/141733981-ca6f1c91-aef7-4beb-99bb-d740fe902e16.png">

**Comment by benjaminjames** [comment]
Same issue
```
    from playwright.sync_api import sync_playwright
ModuleNotFoundError: No module named 'playwright.sync_api'; 'playwright' is not a package
```
Installed without issue. Tried everything I've found online. Odd that playwright's own example isn't working.. ??

**Comment by ShawnJorge** [comment]
Error not resolved, I've tried all suggestions in this thread. Please help
![pLAYWRIGHT ERROR](https://user-images.githubusercontent.com/83574956/218093898-a5386ded-64dd-4284-8ce7-788e74ac7ce3.png)


CODE:
import re
#from playwright.sync_api import Playwright, expect
#from playwright.sync_api import Playwright, sync_playwright, expect
#from playwright import sync_playwright
#from playwright.sync_api import sync_playwright
import playwright

from playwright import sync_playwright
def run(playwright: sync_playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://www.edinburghlive.co.uk/newsletter-preference-centre/?utm_source=newslettersignupheader")
    page.get_by_role("heading", name="News", exact=True).click()
    page.get_by_role("button", name="Subscribe").first.click()
    page.get_by_role("button", name="close-icon").click()
    page.close()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)



ERROR:
Traceback (most recent call last):
  File "d:\Python\PlayWright\example2.py", line 7, in <module>
    from playwright.sync_api import sync_playwright
  File "C:\Users\User2\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\sync_api\__init__.py", line 25, 
in <module>
    import playwright.sync_api._generated
  File "C:\Users\User2\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\sync_api\_generated.py", line 25, in <module>
    from playwright._impl._accessibility import Accessibility as AccessibilityImpl
  File "C:\Users\User2\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_accessibility.py", line 17, in <module>
    from playwright._impl._connection import Channel
  File "C:\Users\User2\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_connection.py", line 23, 
in <module>
    from greenlet import greenlet
  File "C:\Users\User2\AppData\Local\Programs\Python\Python311\Lib\site-packages\greenlet\__init__.py", line 29, in <module>    from ._greenlet import _C_API # pylint:disable=no-name-in-module
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: DLL load failed while importing _greenlet: The specified module could not be found.

**Comment by mxschmitt** [comment]
@ShawnJorge try the following: https://github.com/python-greenlet/greenlet/issues/346#issuecomment-1416918053
