### ISSUE TITLE
page.on not working for download dialogs?

### ISSUE THREAD

**Issue by buddemat** [microsoft/playwright-python#460]
I was trying to handle a browser dialog in (in this case) firefox, i.e. a dialog opened by firefox to ask whether to open or save a file. The dialog pops up after I click a button.

I thought I found the solution in https://github.com/microsoft/playwright-python/issues/396. However, the following did not work:

```
page.on("dialog", lambda dialog: dialog.accept())
page.click("button")
```

Do these kinds of dialog not trigger a "dialog" event? How can I accept or dismiss such a dialog?

**Comment by pavelfeldman** [comment]
Check out https://playwright.dev/python/docs/downloads for docs on how to manage downloads. Dialog even is for alert, confirm, prompt and onbeforeunload.

**Comment by buddemat** [comment]
Thank you for your quick reply! Unfortunately, there doesn't seem to be a download event triggered either. I've added a full example that triggers the mentioned dialog for a pdf download:
```
with sync_playwright() as p:
    b = p.firefox.launch(headless=False,downloadsPath=os.getcwd())
    p = b.newPage(acceptDownloads=True)
    p.on("download", lambda download: print("Download event!"))
    p.goto('https://www.w3docs.com/uploads/media/default/0001/01/540cb75550adf33f281f29132dddd14fded85bfc.pdf')
    p.querySelector('button[id=\"download\"]').click()
```

**Comment by dgozman** [comment]
There are multiple issues here:
- Scripts goes directly to the pdf page. In this case, pdf is shown (depends on the browser) instead of being downloaded.
- Script does not wait for the actual download to happen (it might start with a delay after clicking).

Here is an example that works for me:
- It has a page with a link that forces a download (it has a `download` attribute).
- It uses `expect_download()` to actually wait for the download to start, as suggested [in the docs](https://playwright.dev/python/docs/downloads/).

```py
from playwright.sync_api import sync_playwright
import os

with sync_playwright() as p:
    b = p.firefox.launch(headless=False,downloads_path=os.getcwd())
    p = b.new_page(accept_downloads=True)
    p.goto('https://www.webfx.com/blog/images/assets/cdn.sixrevisions.com/0435-01_html5_download_attribute_demo/html5download-demo.html')
    with p.expect_download() as download_info:
      p.click('text=DOWNLOAD HTML DOCUMENT')
    download = download_info.value
    print(download.path())
```

Let me know if that does not help.

**Comment by buddemat** [comment]
@dgozman Thank you very much for your answer. And while your example works fine, unfortunately, I don't seem to be able to adapt it to my problem. The thing is that in my case the embedded pdf viewer does not open as a result on a click on a link (`<a>`), but instead opens on a button click. Otherwise I could modify the link to add a `download` attribute. But once the embedded pdf viewer is open, I don't get a download event anymore when I click the button as in my example above. 

Is that normal / expected behavior? As a human, I can click the download button in the embedded PDF viewer and save the file. Shouldn't playwright somehow enable me to do the same? The only workaround I came up with thus far is running in head mode, clicking the button and then sending an <kbd>Enter</kbd> press. But that does not let me modify the filename, etc.

**Comment by pavelfeldman** [comment]
> Is that normal / expected behavior? As a human, I can click the download button in the embedded PDF viewer and save the file. Shouldn't playwright somehow enable me to do the same? 

Embedded PDF viewer is not a part of the web, it is a part of the browser, so we don't automate it.

**Comment by buddemat** [comment]
Ok, thank you for the clarification. I thought since the embedded PDF viewer is based on `pdf.js` this might still be automatable with playwright. But now that I think about it, the dialog is not part of `pdf.js`, so your point is valid. This can be closed then, I guess...

**Comment by Bill-Mendocino** [comment]
If you open Chrome in headless mode, you won't get dialogs!

`browser = playwright_page.chromium.launch(headless=True,downloads_path=os.getcwd())`
