### ISSUE TITLE
broswer always auto close without use broswer.close()

### ISSUE THREAD

**Issue by Liehu** [microsoft/playwright-python#464]
my env:
python:3.8.6
Win10 19042.746

my code:

```
import asyncio
from playwright.async_api import async_playwright



async def main():
    async with async_playwright() as playwright:

        browser = await playwright.chromium.launch(headless=False)
        # Open new page
        page = await browser.new_page()

        await page.goto("https://www.baidu.com")

asyncio.run(main())
```

the broswer auto close after I run this code,and not error raise up. how do I debug this problem?

**Comment by pavelfeldman** [comment]
This is by design, your program simply ends and exits. When you leave the playwright scope everything is closed. You can insert await page.wait_for_timeout(1000000) after goto if you'd like your program to stall there.

**Comment by Liehu** [comment]
> This is by design, your program simply ends and exits. When you leave the playwright scope everything is closed. You can insert await page.wait_for_timeout(1000000) after goto if you'd like your program to stall there.

Thanks.I'll have a try
