### ISSUE TITLE
[Question] Support of browserType.launchServer

### ISSUE THREAD

**Issue by rushter** [microsoft/playwright-python#469]
Hi,

The nodejs package supports `browserType.launchServer`. Are there any plans to add this to Python package?

A lot of examples in Google use nodejs. Ideally, it would be cool to have exactly the same APIs for nodejs and Python.

https://playwright.dev/python/docs/api/class-browsertype/
https://playwright.dev/docs/api/class-browsertype/

**Comment by pavelfeldman** [comment]
Could you share more on your use case? Do you want it exactly the same? Would you be open to run nodejs server with Python client?

**Comment by rushter** [comment]
I want to control one Chrome instance from multiple processes and keep it always running. Ideally, on a remote host.

Nodejs server will work for me too.

**Comment by mxschmitt** [comment]
Closing for now, the current preferred way is to use Node.js to launch a server, see here: https://playwright.dev/docs/api/class-browsertype#browsertypelaunchserveroptions
