### ISSUE TITLE
[CLI] Option to only install a selection of browsers

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright-python#47]
Benefits:
- save bandwidth and storage and by that it's a better developer experience.

Implementation
- Either env based or CLI argument to the driver like in https://github.com/microsoft/playwright/pull/3266 or https://github.com/microsoft/playwright/pull/3197

Requests
- https://playwright.slack.com/archives/C0182HLNSJV/p1598351875001100

Related https://github.com/microsoft/playwright-sharp/issues/890

**Comment by pavelfeldman** [comment]
Do we not inherit environment? It should just work (be configurable using env variables)

**Comment by mxschmitt** [comment]
We do, so these would then work: https://playwright.dev/#version=v1.2.0&path=docs%2Finstallation.md&q=skip-browser-downloads

But I mean if a user only wants to use Chromium. The other browsers will still be installed, because our browsers.json contain all the browsers. And we can only skip the installation of all of them with the current env var implementation in playwright.

**Comment by pavelfeldman** [comment]
We need to add env vars into Playwright then

**Comment by mxschmitt** [comment]
Maybe something like `PLAYWRIGHT_INSTALL_ALLOWLIST=webkit,firefox,chromium` which is a comma-separated list which upstream Playwright will check and then install if persistent?

**Comment by CmdEngineer** [comment]
I need playwright in a docker but I am planning to only use it with chrome and python -m playwright install automatically install all the browsers and it's alot of space...

**Comment by jcushman** [comment]
@CmdEngineer -- until this is fixed, one hack is to add a line to your Dockerfile that overwrites browsers.json in the playwright python package before calling install. Something like this, for example:

```
RUN cp my_browsers.json `python -c 'import playwright, pathlib; print(pathlib.Path(playwright.__file__).parent)'`/driver/browsers.json
```

**Comment by CmdEngineer** [comment]
> @CmdEngineer -- until this is fixed, one hack is to add a line to your Dockerfile that overwrites browsers.json in the playwright python package before calling install. Something like this, for example:
> 
> ```
> RUN cp my_browsers.json `python -c 'import playwright, pathlib; print(pathlib.Path(playwright.__file__).parent)'`/driver/browsers.json
> ```

Thanks

**Comment by pavelfeldman** [comment]
`playwright install chromium` will only install chromium these days.
