### ISSUE TITLE
[QUESTION] Thread-safety of playwright-python's sync_api

### ISSUE THREAD

**Issue by jwiebels** [microsoft/playwright-python#470]
Hello,
I am currently required to run parallel tests using Playwright. To run these tests, I am currently using the following setup:

    OS:          Microsoft Windows Server 2019 Datacenter 10.0.17763 Build 17763
    Python:      3.9.1
    Playwright:  0.171.1

Sample code snippet of how I am setting up a test:

    from playwright.sync_api import sync_playwright
    from concurrent.futures.thread import ThreadPoolExecutor
    
    def sample_func():
        playwright_instance = sync_playwright().start()
        browser = playwright_instance.firefox.launch()
        page = browser.new_page()
        page.goto('http://whatsmyuseragent.org/')
        page.screenshot(path=f'example-{browser_type.name}.png')
        browser.close()

    tpe = ThreadPoolExecutor()
    for _ in range(100):
        tpe.submit(sample_func)
    tpe.shutdown()

Can I generally do something like this using the `ThreadPoolExecutor` and is this usage of Playwright thread-safe?
If not, would something like this be reliable?

    async def work_async():
	    playwright = await async_playwright().start()
	    browser = await playwright.firefox.launch()
	    page = await browser.newPage()
	    await page.goto('http://whatsmyuseragent.org/')
	    await browser.close()
	    await playwright.stop()
    
    def create_async_worker():
	    loop = asyncio.new_event_loop()
	    asyncio.set_event_loop(loop)
	    f = asyncio.ensure_future(work_async())
	    return loop.run_until_complete(f)
    
    tpe = ThreadPoolExecutor(max_workers=10)
    
    for i in range(20):
	    tpe.submit(lambda: create_async_worker())
    tpe.shutdown(wait=True)

Thank you for your time!

**Comment by pavelfeldman** [comment]
Sync API is **not** thread safe. If you'd like to use sync API, parallelization can be achieved with multiprocess setup, like pytest's xdist.

If you are open to using Async API, you can run several tests concurrently on a single event loop, without the additional worker. async/await was designed to achieve cooperative concurrency on a single loop.

Having said that, we still recommend sharding parallelism by means of processes as in xdist. We just pass `-n` to our tests that use `pytest-playwright` and they run in parallel.

**Comment by jwiebels** [comment]
Thank you very much for your reply!
