### ISSUE TITLE
Interactive mode (REPL)  (v 1.8.0a1) Error

### ISSUE THREAD

**Issue by zhonghai9967** [microsoft/playwright-python#471]
**from playwright.sync_api import sync_playwright
playwright = sync_playwright().start()**

Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\playwright\_impl\_transport.py", line 27, in _get_stderr_fileno
    return sys.stderr.fileno()
io.UnsupportedOperation: fileno

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    playwright = sync_playwright().start()
  File "C:\Python37\lib\site-packages\playwright\sync_api\_context_manager.py", line 73, in start
    return self.__enter__()
  File "C:\Python37\lib\site-packages\playwright\sync_api\_context_manager.py", line 67, in __enter__
    dispatcher_fiber.switch()
  File "C:\Python37\lib\site-packages\playwright\sync_api\_context_manager.py", line 48, in greenlet_main
    loop.run_until_complete(self._connection.run_as_sync())
  File "C:\Python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Python37\lib\site-packages\playwright\_impl\_connection.py", line 134, in run_as_sync
    await self.run()
  File "C:\Python37\lib\site-packages\playwright\_impl\_connection.py", line 139, in run
    await self._transport.run()
  File "C:\Python37\lib\site-packages\playwright\_impl\_transport.py", line 62, in run
    stderr=_get_stderr_fileno(),
  File "C:\Python37\lib\site-packages\playwright\_impl\_transport.py", line 34, in _get_stderr_fileno
    return sys.__stderr__.fileno()
AttributeError: 'NoneType' object has no attribute 'fileno'

**Comment by zhonghai9967** [comment]
python:
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] on win32

**Comment by mxschmitt** [comment]
I created a corresponding patch for it to fix it. Would be great if you could modify your `C:\Python37\lib\site-packages\playwright_impl_transport.py` locally and verify if the change in #472 would work for you.

**Comment by kumaraditya303** [comment]
Try to install that fix using pip :
Just run this command and try again in shell and verify.
```bash
pip install git+https://github.com/mxschmitt/playwright-python@bugfix/stderr-forwarding
```

**Comment by pavelfeldman** [comment]
It works for me, is there anything special about your repl setup?

```
(env) ~/tmp/repl1$ python
Python 3.7.9 (default, Aug 18 2020, 02:07:21) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from playwright.sync_api import sync_playwright
>>> playwright = sync_playwright().start()
>>> 
```

**Comment by zhonghai9967** [comment]
(AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> from playwright.sync_api import sync_playwright
>>> playwright = sync_playwright().start()

**Comment by zhonghai9967** [comment]
pip install git+https://github.com/mxschmitt/playwright-python@bugfix/stderr-forwarding
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting git+https://github.com/mxschmitt/playwright-python@bugfix/stderr-forwarding
  Cloning https://github.com/mxschmitt/playwright-python (to revision bugfix/stderr-forwarding) to d:\temp\pip-req-build-0wxxuxtt
  Running command git clone -q https://github.com/mxschmitt/playwright-python 'd:\Temp\pip-req-build-0wxxuxtt'
  fatal: unable to access 'https://github.com/mxschmitt/playwright-python/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
WARNING: Discarding git+https://github.com/mxschmitt/playwright-python@bugfix/stderr-forwarding. Command errored out with exit status 128: git clone -q https://github.com/mxschmitt/playwright-python 'd:\Temp\pip-req-build-0wxxuxtt' Check the logs for full command output.
ERROR: Command errored out with exit status 128: git clone -q https://github.com/mxschmitt/playwright-python 'd:\Temp\pip-req-build-0wxxuxtt' Check the logs for full command output.

**Comment by zhonghai9967** [comment]
Follow the method of  @pavelfeldman 
edit 'Lib\site-packages\playwright\_impl\_transport.py':
line 32:
if not hasattr(sys, "__stderr__"):  ==>
if not hasattr(sys, "__stderr__") or not sys.__stderr__:

Can run repl ！！！but,After the command  playwright = sync_playwright().start(), 
a cmd window pops up.
Thank you all for your help. I really need REPLt function
