### ISSUE TITLE
Fixture 'page' not found

### ISSUE THREAD

**Issue by akarp0v** [microsoft/playwright-python#474]
Created a file test_example.py which contains:

```
def test_example_is_working(page):
    page.goto("https://example.com")
    assert page.inner_text('h1') == 'Example Domain'
    page.click("text=More information")

```
Tried running by:
`pytest`

and get:
```
E       fixture 'page' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.
```

```
$ pip list | grep playwright
playwright        1.8.0a1
pytest-playwright 0.0.11
```

What am I doing wrong?

**Comment by dgozman** [comment]
Did you install [`pytest-playwright`](https://github.com/microsoft/playwright-pytest)?
```sh
$ pip install pytest-playwright
```
It provides default fixtures like `page` or `browser`, otherwise `pytest` does not have built-in fixtures for Playwright. [Learn more](https://github.com/microsoft/playwright-pytest#usage) about `pytest-playwright` usage.

Let me know if this does not help.

**Comment by akarp0v** [comment]
Yes, I did
```
$ pip list | grep playwright
playwright        1.8.0a1
pytest-playwright 0.0.11
```

**Comment by akarp0v** [comment]
Finally, restart helps)

**Comment by dgozman** [comment]
> Yes, I did
> 
> ```
> $ pip list | grep playwright
> playwright        1.8.0a1
> pytest-playwright 0.0.11
> ```
> 
> It didn't help

Oh, now I see that I missed that in the original report. Sorry!

I'm glad that reboot helped. Closing the issue 😄

**Comment by 916525236** [comment]
so, reboot  can be sovled?

**Comment by brysonics** [comment]
I tried rebooting but I am still getting the same issue. I have installed playwright 1.28.0 & pytest 7.2.0

**Comment by brysonics** [comment]
Actually I did the following command and seems it helped for it to work.

playwright install-deps
