### ISSUE TITLE
AttributeError: 'Page' object has no attribute 'selectOption'

### ISSUE THREAD

**Issue by danofun** [microsoft/playwright-python#475]
Clean install of Ubuntu and I'm receiving the following error with both sync and async. Any help would be greatly appreciated.

`page.fill('#firstname1', 'John')`
`# works properly`

`page.selectOption('#state1', 'Arizona')`
`# errors "AttributeError: 'Page' object has no attribute 'selectOption'"`

**Comment by dgozman** [comment]
Starting with v1.8.0.a1, `playwright-python` is using snake case. [More details here](https://github.com/microsoft/playwright-python#migration-from-the-pre-release-versions).

Here are the docs for [`page.select_option`](https://playwright.dev/python/docs/api/class-page/#pageselect_optionselector-kwargs), note the snake case.
