### ISSUE TITLE
I'm want to use socks5 proxy with chromium

### ISSUE THREAD

**Issue by anameshhowwa** [microsoft/playwright-python#476]
I'm want to use socks5 proxy with chromium with playwright , i have list of 

176.9.75.42:1080
106.54.64.26:1080
154.72.204.78:8080

how can i use them each one for every process

**Comment by pavelfeldman** [comment]
You can use `proxy` key in https://playwright.dev/python/docs/api/class-browsertype#browser_typelaunchkwargs

**Comment by pavelfeldman** [comment]
(You can also use it on a per-context basis: https://playwright.dev/python/docs/api/class-browser/#browsernew_contextkwargs)
