### ISSUE TITLE
how to slove 'tls' issues

### ISSUE THREAD

**Issue by xueneymar** [microsoft/playwright-python#479]
![image](https://user-images.githubusercontent.com/13958555/106694609-dcd09100-6613-11eb-873a-b837e47ae73b.png)

**Comment by mxschmitt** [comment]
When creating a new context, you can pass `ignore_https_errors ` to ignore HTTPS errors: https://playwright.dev/python/docs/api/class-browser?_highlight=new_context#browsernew_contextkwargs

**Comment by pavelfeldman** [comment]
Closing as per answer above.
