### ISSUE TITLE
dialog appearing before click completion

### ISSUE THREAD

**Issue by Auzzy** [microsoft/playwright-python#484]
The project I'm automating using JS alert dialogs to inform the user of input errors, so for negative testing I'm using `page.expect_event("dialog")` as a context manager. However, on occasion, the test will hang and eventually fail with a TimeoutError (playwright-pytest is our test runner). Running the tests again with the playwright debug flag and some print statements shows that it's a race condition between page.click registering success and the dialog appearing. It seems the test hangs when page.click doesn't complete before the dialog appears.

Here's the relevant snippet of the debug output for such a failure. The two lines starting with "DIALOG" is a print statement I put in a dialog event handler to emit the dialog's message so I'd know when it appeared.
```
  pw:api => page.click started
  pw:api waiting for selector "text=CREATE" +2ms
  pw:api   selector resolved to visible <span class="MuiButton-label">Create</span> +3ms
  pw:api attempting click action +2ms
  pw:api   waiting for element to be visible, enabled and not moving +0ms
  pw:api   element is visible, enabled and does not move +31ms
  pw:api   scrolling into view if needed +0ms
  pw:api   done scrolling +1ms
  pw:api   checking that element receives pointer events at (799.56,450) +1ms
  pw:api   element does receive pointer events +3ms
  pw:api   performing click action +1ms
  pw:api => route.fulfill started
  pw:api   click action done +28ms
  pw:api <= route.fulfill succeded
  pw:api   waiting for scheduled navigations to finish +0ms
DIALOG: Error: Error encountered in fetch.
account 'name': Missing data for required field., account 'description': Missing data for required field.
  pw:api   "networkidle" event fired +502ms
  pw:api <= page.click failed
```

I can work around this issue by adding `no_wait_after=True` to the relevant click events (at least, I haven't seen the issue again in since adding that argument earlier today). But I'm confused why the click event's completion would be impacted by the appearance of a dialog.

**Comment by Auzzy** [comment]
I realize I didn't ask a clear question/action. I wanted to know why a dialog coming up prevents page.click from properly completing, and bring it to your attention since my guess is this behavior is not desired. At the very least, as a user, it is surprising.

**Comment by dgozman** [comment]
@Auzzy This is a quirk of JS dialogs - they are [blocking](https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop#never_blocking), which means that page freezes while the dialog is open. This in turn means that click does not finish until you close the dialog.

I assume that you want to verify something about the dialog, so you should both expect it and handle it. For example:

```python
with page.expect_event("dialog") as dialog_info:
    # Dismiss (or accept) next dialog
    page.once("dialog", lambda dialog: dialog.dismiss())
    page.click("button")
dialog = dialog_info.value
assert dialog.message == "Message"
```

Does that help?

**Comment by Auzzy** [comment]
Interesting. I knew dialogs are blocking, I'd just assumed the page would be able to finish the click first. But putting more thought into the execution, it makes sense that this is how the browser would work.

Your example made me realize I was going about the expect_event context manager slightly wrong. Let me make sure I understand now: `dialog_info` is acting as a promise, to grant the user access to an event which was raised during the context manager code block execution. So accessing `dialog_info.value` causes the code to block (until the timeoout) waiting for a dialog event to occur.

**Comment by dgozman** [comment]
> Your example made me realize I was going about the expect_event context manager slightly wrong. Let me make sure I understand now: `dialog_info` is acting as a promise, to grant the user access to an event which was raised during the context manager code block execution. So accessing `dialog_info.value` causes the code to block (until the timeoout) waiting for a dialog event to occur.

It is almost like that. If dialog did not open yet, one of the two will block (depending on what's called first): either exiting the context manager or calling `dialog_info.value`.

In your case, though, it's the `click` that blocks even before that, as we discussed above. Let me know if the snippet above works for you, or we should do something to help you.

**Comment by Auzzy** [comment]
Yup, I was talking about in general. My initial assumption was that the expect_event was acting as an event handler, but of course you've shown me I was incorrect. Tried it out with the snippet you showed me (adapted to my situation), and it worked great! Turned on debugging to ensure that even when the click didn't complete until after the dialog event fired, it still worked. So the only issue was on my side.Thanks!

**Comment by dgozman** [comment]
@Auzzy You are welcome!
