### ISSUE TITLE
[INTERNAL] How to use scripts/generate* to generate api

### ISSUE THREAD

**Issue by kumaraditya303** [microsoft/playwright-python#486]
I tried running scripts/generate_async_api and sync and the generated `_generated.py` is not the same. I would like to know how does these scripts work and know if any external work is needed if the scripts are run.

**Comment by mxschmitt** [comment]
Whats the difference? We run them on GitHub Actions to ensure they are always up to date when we push them and also compare them there. Ensure that you have the latest driver installed. As a command reference you can use the GitHub workflow files.
