### ISSUE TITLE
 playwright-python  Firefox does not support 1.8.0a1 ?

### ISSUE THREAD

**Issue by zhonghai9967** [microsoft/playwright-python#488]
tiwen  = jktj.get_attribute('td:has(p:has(:text("tiwen")))+td>div>input','value')

E       playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
E       =========================== logs ===========================
E         retrieving attribute "value" from "td:has(p:has(:text("tiwen")))+td>div>input"
E       ============================================================
E       Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
(jktj is a iframe)
**This sentence runs normally in chromium or  webkit**

**Comment by zhonghai9967** [comment]
pytest d:\script\test_xiaotijian.py -s --browser=firefox
or
pytest d:\script\test_xiaotijian.py -s --browser=firefox --headless
All can't run

**Comment by kumaraditya303** [comment]
There are new playwright releases, upgrade with 
```sh
$ pip install playwright -U 
```
