### ISSUE TITLE
Dockerfile for playwright-python is too large

### ISSUE THREAD

**Issue by joeyfromnijmegen** [microsoft/playwright-python#49]
The Docker image for playwright-python turns out to be really large (above 2 GB). It is due to the fact that pip installing playwright will download the binary for 3 browsers. Any tip on how to create a dockerfile for each individual browser  ?

FROM ubuntu:focal

RUN apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf \
      python3.8 python3.8-dev python3-pip \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
    apt-get -y install xvfb libdbus-glib-1-2 libegl1 libgl1 libgles2 libgudev-1.0 libopus0 libwebp6 \
    libwebp6 libwoff1 libxslt1.1 libxslt1.1 gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 \
    libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 \
    libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 \
    libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 \
    libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget && \
    rm -rf /var/lib/apt/lists/*

# Install production dependencies.
RUN pip3 install playwright

**Comment by mxschmitt** [comment]
Hi,
we'll soon provide an official image. Until now, we recommend to use the dependencies from this [Dockerfile](https://github.com/microsoft/playwright/blob/master/docs/docker/Dockerfile.bionic) on top of the official Python3.8 base image. Playwright browsers are self-contained, so you don't need to install the browser manually. Playwright will install them for you.

Keep in mind, that this package is in a beta currently and we are curious for what you are using it.

**Comment by pavelfeldman** [comment]
What are your docker image size expectations?

**Comment by mxschmitt** [comment]
I've tested it out and for me when I'm using the following Dockerfile, it will result in around 712 MB which seems reasonable.

https://gist.github.com/mxschmitt/900aa310730bfac360717796b62ad072

**Comment by joeyfromnijmegen** [comment]
It looks great and It works great, thanks a lot @mxschmitt. I will close the ticket
