### ISSUE TITLE
Can't recognize sliding button

### ISSUE THREAD

**Issue by HelloJack0** [microsoft/playwright-python#490]
https://passport.umeng.com/login

There is a sliding verification button on this login page. The playwright cannot complete the operation. Who can help me? Thank you

**Comment by HelloJack0** [comment]
![image](https://user-images.githubusercontent.com/47816656/107140521-8938ad00-695d-11eb-8a6c-516b469bcb22.png)

**Comment by oldlwhite** [comment]
Your problem has nothing to do with playwright, you are detected as a bot, you should find the reason from your own
