### ISSUE TITLE
Browser executable not found when PLAYWRIGHT_BROWSERS_PATH is 0

### ISSUE THREAD

**Issue by muffinmad** [microsoft/playwright-python#494]
Steps to reproduce:

1. `mkvirtualenv pyplaywright`
2. `pip install playwright==1.8.0a1`
3. `PLAYWRIGHT_BROWSERS_PATH=0 python -m playwright install chromium`
```
chromium v844399 downloaded to /Users/mad/.virtualenvs/pyplaywright/lib/python3.7/site-packages/playwright/driver/package/.local-browsers/chromium-844399
```
4. `PLAYWRIGHT_BROWSERS_PATH=0 python`
```
>>> from playwright.sync_api import sync_playwright
>>> with sync_playwright() as p:
...     p.chromium.launch()
... 
playwright._impl._api_types.Error: Failed to launch chromium because executable doesn't exist at /Users/mad/.virtualenvs/html2pdf/lib/python3.7/site-packages/playwright/driver/package/lib/cli/.local-browsers/chromium-844399/chrome-mac/Chromium.app/Contents/MacOS/Chromium
```

The search path is differs from the installation path.

**Comment by mxschmitt** [comment]
`PLAYWRIGHT_BROWSERS_PATH` is not supported for Python afaik. What are you trying to achieve? 

The driver is in the Python module directory and the browsers are globally located: https://playwright.dev/docs/installation?_highlight=playwright_browsers_path#managing-browser-binaries maybe that helps you.

**Comment by pavelfeldman** [comment]
It should work. I think we recently fixed it.

**Comment by dgozman** [comment]
This was fixed in https://github.com/microsoft/playwright/pull/5217.

**Comment by muffinmad** [comment]
I was trying to do hermetic install and place binaries under the `site-packages/playwright` folder as noted in this [installation instruction](https://playwright.dev/python/docs/installation#managing-browser-binaries).

I'm unable to `pip install git+https://github.com/microsoft/playwright-python`, I'll wait the next release on pypi.

Thanks!

**Comment by dgozman** [comment]
> I was trying to do hermetic install and place binaries under the `site-packages/playwright` folder as noted in this [installation instruction](https://playwright.dev/python/docs/installation#managing-browser-binaries).

You were doing the right thing, it was broken. Next v1.9 release (coming soon) will have it fixed. Thank you!

**Comment by ebzimny01** [comment]
It's not clear to me. Is this supposed to be resolved for Windows too? Or only Linux?

If I create a virtualenv  in Linux and set the PLAYWRIGHT_BROWSERS_PATH=0, it will place the installed browser in the virtualenv:

1. mkvirtualenv testenv
2. pip install playwright
3. PLAYWRIGHT_BROWSERS_PATH=0 python -m playwright install firefox
`/.virtualenvs/testenv/lib/python3.8/site-packages/playwright/driver/package/.local-browsers/firefox-1234`

4. PLAYWRIGHT_BROWSERS_PATH=0 python
5. Then run the sample code above and it will find the firefox browser in the virtualenv correctly.

But when I attempt this in Win10, it always places the browser in the local user profile in the ms-playwright folder, never within the virtualenv:

1. python -m venv testenv
2. set PLAYWRIGHT_BROWSERS_PATH=0
2. pip install playwright
3. playwright install firefox
`firefox v1234 downloaded to C:\Users\user1\AppData\Local\ms-playwright\firefox-1234`

Any thoughts?

**Comment by mxschmitt** [comment]
You are inside PowerShell, if you are inside PowerShell you need to set environment variables by doing the following:

```powershell
$Env:PLAYWRIGHT_BROWSERS_PATH=0
```
