### ISSUE TITLE
playwright._impl._api_types.Error: Host system is missing dependencies!

### ISSUE THREAD

**Issue by dmf-code** [microsoft/playwright-python#498]
### environment
CentOS Linux release 7.9.2009 (Core)
Python 3.7.3
playwright==1.8.0a1

```
playwright._impl._api_types.Error: Host system is missing dependencies!

  Missing libraries are:
      libatk-1.0.so.0
      libatk-bridge-2.0.so.0
      libxkbcommon.so.0
      libXcomposite.so.1
      libXdamage.so.1
      libXfixes.so.3
      libXrandr.so.2
      libgbm.so.1
      libgtk-3.so.0
      libgdk-3.so.0
      libpango-1.0.so.0
      libcairo.so.2
      libatspi.so.0
      libxshmfence.so.1

Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.

During handling of the above exception, another exception occurred:

```
```
yum -y install libatk-1.0.so.0 libatk-bridge-2.0.so.0 libxkbcommon.so.0 libXcomposite.so.1 libXdamage.so.1 libXfixes.so.3 libXrandr.so.2 libgbm.so.1 libgtk-3.so.0 libgdk-3.so.0 libpango-1.0.so.0 libcairo.so.2 libatspi.so.0 libxshmfence.so.1
```

This problem is still displayed after installing dependencies

**Comment by dmf-code** [comment]
### solution

```
yum -y install libappindicator-gtk3
yum -y install liberation-fonts
```

**Comment by FavorMylikes** [comment]
Does not work
```
  Install missing packages with:
      sudo apt-get install gstreamer1.0-libav

  Missing libraries we didn't find packages for:
      libvpx.so.6
      libwoff2dec.so.1.0.2
      libharfbuzz-icu.so.0
      libjpeg.so.8
      libwebp.so.6
      libenchant.so.1
      libhyphen.so.0
      libicui18n.so.66
      libicuuc.so.66
```

**Comment by nandakumarhavanur** [comment]
Running playwright script in ubuntu 18.04 from windows 1, after getting series of errors for the dependencies and installing all of those, finally getting this error:

Loop <_UnixSelectorEventLoop running=False closed=True debug=False> that handles pid 6583 is closed
ImportError while loading conftest '/home/nandakumar/novasignal/Cloud_Testing/playwright_python/tests/conftest.py'.
tests/conftest.py:2: in <module>
    from utilities.base_class import base_class
utilities/base_class.py:11: in <module>
    class base_class:
utilities/base_class.py:23: in base_class
    browser = p.chromium.launch(headless=False)
.venv/lib/python3.8/site-packages/playwright/sync_api/_generated.py:10174: in launch
    raise e
.venv/lib/python3.8/site-packages/playwright/sync_api/_generated.py:10150: in launch
    self._sync(
.venv/lib/python3.8/site-packages/playwright/_impl/_sync_base.py:90: in _sync
    return future.result()
.venv/lib/python3.8/site-packages/playwright/_impl/_browser_type.py:73: in launch
    raise not_installed_error(f'"{self.name}" browser was not found.')
E   Exception:
E   ================================================================================
E   "chromium" browser was not found.
E   Please complete Playwright installation via running
E
E       "python -m playwright install"
E
E   ================================================================================

Can anyone please help on this @pavelfeldman

**Comment by kumaraditya303** [comment]
https://github.com/microsoft/playwright/issues/6219 :+1: the issue if you want playwright on centos

**Comment by djravine** [comment]
Issue fixed by installing each module (Needed to google search each one seperately)

Docker image using `Debian GNU/Linux 10`

`apt-get install -y gstreamer1.0-libav libnss3-tools libatk-bridge2.0-0 libcups2-dev libxkbcommon-x11-0 libxcomposite-dev libxrandr2 libgbm-dev libgtk-3-0`

**Comment by collinsmarra** [comment]
I have the same issue however for this modules are missing and  it has persisted
![Uploading image.png…]()

**Comment by Ty4ka** [comment]
> Issue fixed by installing each module (Needed to google search each one seperately)
> 
> Docker image using `Debian GNU/Linux 10`
> 
> `apt-get install -y gstreamer1.0-libav libnss3-tools libatk-bridge2.0-0 libcups2-dev libxkbcommon-x11-0 libxcomposite-dev libxrandr2 libgbm-dev libgtk-3-0`

Its work! Thank you!!!

**Comment by SurendraTamang** [comment]
> Issue fixed by installing each module (Needed to google search each one seperately)
> 
> Docker image using `Debian GNU/Linux 10`
> 
> `apt-get install -y gstreamer1.0-libav libnss3-tools libatk-bridge2.0-0 libcups2-dev libxkbcommon-x11-0 libxcomposite-dev libxrandr2 libgbm-dev libgtk-3-0`

This worked for me as well. I was having the issue
playwright._impl._api_types.Error: 
In Ubuntu-> Digital Ocean droplets

**Comment by dmf-code** [comment]
谢谢，邮件已收到。

**Comment by mxschmitt** [comment]
Just do: `python -m playwright install --with-deps` which will work.

**Comment by StefanoGITA** [comment]
With playwright install-deps now i have no more issue on linux lib, but now i got the same error that i have on win10 
```bash
  File "C:\Users\sgiostra\Progetti\PycharmProjects\BigData-Dev\_venv\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='ttwid', domain=None, path=None"
```

**Comment by mxschmitt** [comment]
> With playwright install-deps now i have no more issue on linux lib, but now i got the same error that i have on win10
> 
> ```shell
>   File "C:\Users\sgiostra\Progetti\PycharmProjects\BigData-Dev\_venv\lib\site-packages\requests\cookies.py", line 399, in _find_no_duplicates
>     raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
> KeyError: "name='ttwid', domain=None, path=None"
> ```

This error is coming from the `requests` library, this has nothing to do with Playwright for Python.

**Comment by StefanoGITA** [comment]
> This error is coming from the `requests` library, this has nothing to do with Playwright for Python.

But i'm not directy importing requests i'm tring to use the example of the lib, this is my test_tiktok_api.py:

```python
from TikTokApi import TikTokApi

# Watch https://www.youtube.com/watch?v=-uCt1x8kINQ for a brief setup tutorial
# V4
# api = TikTokApi.get_instance()
# for trending_video in api.by_trending():
#     print(trending_video.author.username)

# V5
with TikTokApi() as api:
    for trending_video in api.trending.videos(count=50):
        # Prints the author's username of the trending video.
        print(trending_video.author.username)
```

**Comment by mxschmitt** [comment]
> > This error is coming from the `requests` library, this has nothing to do with Playwright for Python.
> 
> But i'm not directy importing requests i'm tring to use the example of the lib, this is my test_tiktok_api.py:
> 
> ```python
> from TikTokApi import TikTokApi
> 
> # Watch https://www.youtube.com/watch?v=-uCt1x8kINQ for a brief setup tutorial
> # V4
> # api = TikTokApi.get_instance()
> # for trending_video in api.by_trending():
> #     print(trending_video.author.username)
> 
> # V5
> with TikTokApi() as api:
>     for trending_video in api.trending.videos(count=50):
>         # Prints the author's username of the trending video.
>         print(trending_video.author.username)
> ```

Tiktokapi is using it internally. Please reach out to them.
