### ISSUE TITLE
request.response() doesn't work

### ISSUE THREAD

**Issue by akozyreva** [microsoft/playwright-python#499]
Hi everyone!
While I'm running my test, I'd like to know, do I have any network requests, which failed. The point is, that I can not get any attributes from response() object, so I can't know status of request, text, etc. 
My example is 
```
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()

    def log_and_continue_request(route, request):
        print(request.url)
        print(request.response().ok)
        route.continue_()

    # Log and continue all network requests
    page.route('**', lambda route, request: log_and_continue_request(route, request))

    page.goto('http://todomvc.com')
    browser.close()
 ```
 When I run it, I get the following error 
 ```
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
```

**Comment by mxschmitt** [comment]
Instead of continuing all the requests, you can listen on every response and check if the request was ok (if 2XX status code) like that:

```python
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()

    def handle_response(response):
        if not response.ok:
            print("failed response", response.url, response.status)

    # Log and continue all network requests
    page.on("response", handle_response)

    page.goto("http://todomvc.com")
    browser.close()
```

would that work for your use-case?

**Comment by akozyreva** [comment]
Hi @mxschmitt !
yes, it works for me, thanks! 
What I'm wondering, why I have an access to the request via response (`response.request`), but have no access to response via request (`request.response`)? In documentation both options are available.

**Comment by pavelfeldman** [comment]
The following code is the problem: you block on response() call first. So you never get a chance to call continue_, which actually produces the response.

```py
print(request.response().ok)
route.continue_()
```
