### ISSUE TITLE
page.click() is not working if covered by overlay

### ISSUE THREAD

**Issue by parichay0009** [microsoft/playwright-python#500]
page.click() should close the overlay automatically.

**Comment by mxschmitt** [comment]
which overlay do you mean?

**Comment by parichay0009** [comment]
like some animated element above the main page element.

**Comment by pohlt** [comment]
A real mouse click would also be caught by the overlay and not reach the underlying elements, so you could say that playwright is doing the expected thing.

**Comment by YusukeIwaki** [comment]
I also experienced the issue last week, in a web service using legacy Ext.js file-uploading form.
And this issue can be solved by specifying `force=True` option for click.

**Comment by pavelfeldman** [comment]
Working as intended.
