### ISSUE TITLE
api-review-2

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright-python#501]
- expose_function/binding missing Callback params in docs / docstrings
- route.continue_ vs resume
- consider get_ prefixes. pending async considerations.

**Comment by mxschmitt** [comment]
Also thought about to introduce upstream a new Error called `BrowsersExecutableNotFoundError` as a type which then can be used in Python to better check if the user has to run `python -m playwright  install`. This would give better error reporting as in  #477 was catched as such an error but it was actually a browser launch error.

**Comment by kumaraditya303** [comment]
Also the playwright error should be namespaced with Playwright i.e. `PlaywrightError` and `PlaywrightTimeoutError` which is less confusing than the current `Error` and `TimeoutError` @pavelfeldman

**Comment by kumaraditya303** [comment]
Also #507

**Comment by mxschmitt** [comment]
> Also the playwright error should be namespaced with Playwright i.e. `PlaywrightError` and `PlaywrightTimeoutError` which is less confusing than the current `Error` and `TimeoutError` @pavelfeldman 

I agree there, had that also in mind.

**Comment by kumaraditya303** [comment]
@mxschmitt Is playwright python docker image public now?

**Comment by kumaraditya303** [comment]
@mxschmitt @pavelfeldman In the README for `async` API, Jupyter Notebook is suggested but instead we should recommend python's builtin asyncio repl which can be accessed by `python -m asyncio`:
Example
```sh
$ python -m asyncio
asyncio REPL 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)] on win32
Use "await" directly instead of "asyncio.run()".
Type "help", "copyright", "credits" or "license" for more information.
>>> import asyncio
>>> 
```

**Comment by kumaraditya303** [comment]
@mxschmitt  May be we should change the way sync api works with something like https://github.com/microsoft/playwright-python/issues/439#issuecomment-778788552

**Comment by pavelfeldman** [comment]
This is now done.
