### ISSUE TITLE
How to cancel chromium browser incognito mode to normal mode?

### ISSUE THREAD

**Issue by walin0358** [microsoft/playwright-python#506]
Due to web page validation failed in incognito mode, but it works fine in normal mode. How can I do it? 
Thanks!

**Comment by mxschmitt** [comment]
launch_persistent_context should work for such use-cases and provide you a context which is not in incognito mode: https://playwright.dev/python/docs/api/class-browsertype?_highlight=launch_per#browser_typelaunch_persistent_contextuser_data_dir-kwargs

**Comment by walin0358** [comment]
> launch_persistent_context should work for such use-cases and provide you a context which is not in incognito mode: https://playwright.dev/python/docs/api/class-browsertype?_highlight=launch_per#browser_typelaunch_persistent_contextuser_data_dir-kwargs

Well done! Thanks so much!
