### ISSUE TITLE
[INTERNAL](typings) Use typing.Optional instead of typing.Union[type,NoneType]

### ISSUE THREAD

**Issue by kumaraditya303** [microsoft/playwright-python#507]
Python's typing module has a dedicated `Optional` type for nullable types but in the playwright docs,` typing.Union` is being used and can be confusing for the users.

Solution:
Replace all occurrences of ` typing.Union` with `typing.Optional`. @mxschmitt  @pavelfeldman

**Comment by pavelfeldman** [comment]
I think 3.9 did it for us.
