### ISSUE TITLE
ft request: methods accepting soley single arguments consisting of dictionaries should have expanded definition of that dictionary

### ISSUE THREAD

**Issue by Mattwmaster58** [microsoft/playwright-python#508]
Here's what I mean. Take [`BrowserContext.set_geolocation`](https://playwright.dev/python/docs/api/class-browsercontext?_highlight=geo#browser_contextset_geolocationgeolocation) for example:

> browser_context.set_geolocation(geolocation)
    geolocation <NoneType|Dict>
        latitude <float> Latitude between -90 and 90.
        longitude <float> Longitude between -180 and 180.
        accuracy <float> Non-negative accuracy value. Defaults to 0.
> 
> Sets the context's geolocation. Passing null or undefined emulates position unavailable.

A more ergonomic signature IMO:
```py

def set_geolocation(reset, *, latitude, longitude, accuracy) -> None:
     if reset is None:
         # do reset stuff
     else:
         # do location faking stuff

```

I realize that this may not be possible given how closely the project strives to mirror JS APIs, though. It would be nice to take advantage of the feature python has to offer.

**Comment by pavelfeldman** [comment]
Playwright 1.9 has a stable API now. I agree it looks great, but {"latitude":180} is not that much worse, given how infrequently it is used.
