### ISSUE TITLE
Run playwright-cli (codegen) with ignore_https_errors flag

### ISSUE THREAD

**Issue by nickosh** [microsoft/playwright-python#512]
Hello. I have a small but serious issue - my project have self-signed certificate and because of this prefer to run codegen with ignore_https_errors flag but not saw this option in help. Its real? Maybe some workarounds?

**Comment by mxschmitt** [comment]
Thats a valid use-case I think and it should be added to the playwright-cli. 👍  There is currently no workaround for that I guess, maybe if possible put your application under http locally.

**Comment by nickosh** [comment]
It what I actually need, thanks! When I followed this issues I found "Codegen with custom setup" in NEXT version of documentation. Question resolved, sorry for bother.
