### ISSUE TITLE
[Feature]: Make it compatible with Pyinstaller

### ISSUE THREAD

**Issue by IHateTomLrge** [microsoft/playwright-python#513]
Hi. 
I'm bundling my app using PyInstaller.
But I'm facing an issue.
When I use the arg: --console. it works well, the browser opens itself when I call it....
But when I use the arg: --windowed. I'm not getting error (no timeout, that's why) but so we are sure that it finds the browser, but the "headless" mode to False isn't working. to explains briefly, I open the browser to solve captchas. so I need it to be "headless=False" but even If I use this arg, it doesn't shows up, without getting any error (if I set timeout to 3000 It will raise error of selector not found)

**Comment by nubonics** [comment]
Were you able to get the an executable with playwright? if so, would you mind sharing how you did so?

Try writing the page content to a file right before you are calling this selector [make sure you account for page navigation when doing so if needed], and viewing it in your browser. Chances are, it is not going to the page you expect, and that is why it cannot find the selector. I very well could be wrong though.

**Comment by tomlarge** [comment]
> Were you able to get the an executable with playwright? if so, would you mind sharing how you did so?
> 
> Try writing the page content to a file right before you are calling this selector [make sure you account for page navigation when doing so if needed], and viewing it in your browser. Chances are, it is not going to the page you expect, and that is why it cannot find the selector. I very well could be wrong though.

No, you didn't understand I think. My prob doesn't comes from the page, like, it works fine, it select everything I told the script to fill/click on....
The issue comes from the headless mode, I never shows up, even I set the Headless to False, it will create an headless browser. And I need it to works on non headless browser.

**Comment by nubonics** [comment]
So what your saying is you cant get out of headless mode? 
So your headless flag is not working? As playwright uses headless by default, so it seems you are not passing the correct flag to disable headless mode.
 If this is not the case, what are your reproducible steps? However, if you are passing the paramater correctly, I suggest starting over, create a new virtual environment, copy the code you had before, install playwright and pyinstaller, and try again, however, I think this has more to do with not passing the flags correctly, as this does not happen on my machine(s).

**Comment by tomlarge** [comment]
> So what your saying is you cant get out of headless mode?
> So your headless flag is not working? As playwright uses headless by default, so it seems you are not passing the correct flag to disable headless mode.
> If this is not the case, what are your reproducible steps? However, if you are passing the paramater correctly, I suggest starting over, create a new virtual environment, copy the code you had before, install playwright and pyinstaller, and try again, however, I think this has more to do with not passing the flags correctly, as this does not happen on my machine(s).

No, I pass the right parameter, like it works fine on Pycharm/VS. But when I convert py files to exe or .app, even if I pass False ti headless mode it keeps being in headless

**Comment by tomlarge** [comment]
> I've experienced the same issue as you. However, I have resolved this problem. Due to your neglect of sharing the information I asked for in my first reply, I will not be sharing the solution that I have found.
> Best of luck!

lmao, nice mentality ;)

**Comment by mxschmitt** [comment]
Thanks to @kumaraditya303 we are compatible now! Downloading it over GitHub (`pip install git+https://github.com/microsoft/playwright-python`) should make it work or wait until 1.14.

Docs will follow, some minimal docs are:

```bash
pip install git+https://github.com/microsoft/playwright-python
PLAYWRIGHT_BROWSERS_PATH=0 playwright install chromium
pyinstaller -F test.py
./dist/test
```

(We close this issue when docs are ready)
