### ISSUE TITLE
Playwright fails to fill element that is visible

### ISSUE THREAD

**Issue by cr4shcod3** [microsoft/playwright-python#515]
I was trying to make a script that automates something from Google App / Service and to do this I need to be able to login to Google. That works, but if there's a captcha on the email page, the script fails to fill on an element that is visible after the captcha. Basically I added a stopper on my script, something like "Press enter after solving captcha". Then this error occur:

```
playwright._impl._api_types.Error: Protocol error (Page.insertText): error in channel "content::page": exception while running method "insertText" in namespace "page": Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsITextInputProcessor.commitCompositionWith] _insertText@chrome://juggler/content/content/PageAgent.js:891:32
_onMessage@chrome://juggler/content/SimpleChannel.js:165:37
receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42
 _onMessage@chrome://juggler/content/SimpleChannel.js:149:16
receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42
```

```
=========================== logs ===========================
waiting for selector "//*[@id="password"]/div[1]/div/div[1]/input"
  selector resolved to visible <input dir="ltr" tabindex="0" type="password" jsname="Y…/>
elementHandle.fill("gregG12345")
  waiting for element to be visible, enabled and editable
  element is visible, enabled and editable`
============================================================
```

Browsing the main repo [https://github.com/microsoft/playwright](https://github.com/microsoft/playwright), I found two same issue : [5460](https://github.com/microsoft/playwright/issues/5460) & [5448](https://github.com/microsoft/playwright/issues/5448). Any fix for this?

**Comment by aslushnikov** [comment]
@cr4shcod3 if by any chance you can share a code snippet that I can run locally to reproduce this problem, that'll be of a great help!

**Comment by pavelfeldman** [comment]
@cr4shcod3 we need more details in order to address this issue. Could you please file a new one with the snippet as suggested above?

**Comment by cr4shcod3** [comment]
Sorry for not being responsive. I lost the exact code as mentioned above since I fixed it by implementing pyautogui if the problem occurs (Try Catch). It still happens sometimes on other scenarios. Will update this thread if the issue will arise again.
