### ISSUE TITLE
How to find iframe in async  mode？

### ISSUE THREAD

**Issue by zhonghai9967** [microsoft/playwright-python#521]
In sync, I can find the following(in async mode, the code doesn't work.):
page.click('#teamName')
page.wait_for_selector('iframe[name=“team"]', timeout=5000)
**iframe1 = page.query_selector('iframe[name=“team"]').content_frame()**
iframe1.click("#btnOK")
...
in async mode,the next three lines work:
**iframe1 = page.frames[2]
iframe1 = page.frame(name="left")
iframe1 = page.frame(url='/phs/person/tojktjlist.action')**

iframe2 = await (page.query_selector('iframe[name="left"]')).content_frame()
**E   AttributeError: 'coroutine' object has no attribute 'content_frame'**

The above three codes(iframe1 =...) are sometimes inconvenient to use because the ”name“/ ”url“ is not easy to determine.
I need to use page.query_selector(selector)  Get iframe.
Please give an example, thank you!

**Comment by pavelfeldman** [comment]
content_frame is also async, you are missing second await.

**Comment by pavelfeldman** [comment]
```py
element = await page.query_selector('iframe[name="left"]')
frame = await element.content_frame()
```

**Comment by sandip-bhosale** [comment]
[Protractor-TypeScript-Framework-master.zip](https://github.com/microsoft/playwright-python/files/6032459/Protractor-TypeScript-Framework-master.zip)

**Comment by zhonghai9967** [comment]
@pavelfeldman
Thank you so much for solving my problem perfectly!
