### ISSUE TITLE
Docker images are still unavailable

### ISSUE THREAD

**Issue by selfisekai** [microsoft/playwright-python#526]
[v1.9.0](https://github.com/microsoft/playwright-python/releases/tag/v1.9.0) release notes say that pre-built Docker images are available, but it's linking to the docs on Node.js images. [Python docs URL](https://playwright.dev/python/docs/docker/) have the same contents and point to the Node.js images as well.

Opening a new issue, because #338 and #454 are closed for unknown reasons (are you getting paid per closed issues? 🙄).

```
 laura@iino  ~/haruhi-dl   master  docker pull mcr.microsoft.com/playwright-python:next-focal
Error response from daemon: manifest for mcr.microsoft.com/playwright-python:next-focal not found: manifest unknown: manifest tagged by "next-focal" is not found
```

**Comment by mxschmitt** [comment]
The main Docker image can be used for Python as well, it contains the latest Python version (3.9).

`docker pull mcr.microsoft.com/playwright:focal`

**Comment by kumaraditya303** [comment]
@mxschmitt FYI those images contains Python `3.8`. https://github.com/microsoft/playwright/blob/ca8998b11e94504cf1daf9c9be05c7f6a73aff8f/utils/docker/Dockerfile.focal#L73 Also the image also containers nodejs which further increases the size of container. Also this way the users are limited to python `3.8`

**Comment by kumaraditya303** [comment]
Also there should be images based on Debian buster as the official python docker images are based on it and should be tagged as the official images i.e. It should be of every supported version`3.7-3.9` and thier slim versions respectively. @mxschmitt

**Comment by pavelfeldman** [comment]
Buster requires special WebKit build that we don't produce atm. Could you elaborate on why it is essential for Playwright tests to run against buster?

**Comment by kumaraditya303** [comment]
As far as python docker images are concerned most uses buster and hence the official python images are built on it, also that way users who uses buster python images can just copy paste the required dependencies otherwise currently users are limited to ubuntu and are required to change their base image. It would be worth trying for WebKit on buster. @pavelfeldman

**Comment by pavelfeldman** [comment]
I don't think we are anticipating adding Playwright into the existing images, e2e tests are likely to run in a separate workflow / action, so picking an image that Playwright comes with would be fine. Also, we are providing the browser binaries in the images, it is not just dependencies.
