### ISSUE TITLE
 How to hide navigator.webdriver information

### ISSUE THREAD

**Issue by renkchina** [microsoft/playwright-python#527]
![image](https://user-images.githubusercontent.com/17176354/109005681-2da04a80-76e5-11eb-96bf-752b753b43a6.png)
As shown in the figure above, how to hide fingerprint information such as webdriver when visiting a webpage

**Comment by mxschmitt** [comment]
It seems like Chromium internally has a few checks to decide if it should set `navigator.webdriver` to true.
- If it's a headless instance
- If `--enable-automation` flag is passed
- If `--remote-debugging-port` or `--remote-debugging-pipe` is used, see [here](https://source.chromium.org/chromium/chromium/src/+/master:content/child/runtime_features.cc;l=441-443?q=tent%2Fchild%2Fruntime_features.cc&ss=chromium%2Fchromium%2Fsrc).

One of these needs to be true and the last one is unfortunately always true. Needs to be changed in upstream Chromium.

cc @aslushnikov please transfer to Playwright main repo.

**Comment by renkchina** [comment]
Yes, I have seen this before. However, I want to use the API provided by the Chrome DevTools Protocol to make changes, and call Page.addScriptToEvaluateOnNewDocument through the CDPSession.send() method provided by Playwright, trying to modify navigator.webdriver, but without success. Would you be able to help, I am very grateful. My code looks like this:
     browser = playwright.chromium.launch(headless=False)
     context = browser.newContext()
     page = context.newPage()
    client = page.context.newCDPSession(page)
    client.send("Page.addScriptToEvaluateOnNewDocument", {
        'source': """
            Object.defineProperty(navigator, 'webdriver', {
              get: () => undefined
            })
          """
    })
    page.goto("https://xxxx.com/")

**Comment by pavelfeldman** [comment]
Playwright is a testing library and while you can use it for scraping, we don't give advice on how hide the automation bit from the servers.

**Comment by LztCode** [comment]
> 是的，我以前见过。但是，我想使用Chrome DevTools协议提供的API进行更改，并通过Playwright提供的CDPSession.send（）方法调用Page.addScriptToEvaluateOnNewDocument，试图修改navigator.webdriver，但没有成功。您能提供帮助，我非常感谢。我的代码如下所示：
> browser = playwright.chromium.launch（headless = False）
> context = browser.newContext（）
> page = context.newPage（）
> client = page.context.newCDPSession（page）
> client.send（“ Page.addScriptToEvaluateOnNewDocument “，{
> 'source'：”“”
> Object.defineProperty（navigator，'webdriver'，{
> get：（）=> undefined
> }）
> “”“
> 
> https://xxxx.com/ “）

use it    ->    browser_context.add_init_script(**kwargs)

**Comment by AutomatedTester** [comment]
For context, the `navigator.webdriver` feature was added to prevent people breaching T&Cs of websites. Trying to work around it to scrape suggests people are trying to do things that websites do not want. I am very much in agreement with @pavelfeldman that if you're really wanting to scrape, and you're not breaching T&Cs, then there are ways to get around it and/or don't use browser based automation frameworks for scraping.

**Comment by yahiko-l** [comment]
I find a good way to solve the navigator.webdriver--> ture problems. as follow:
def run(playwright):
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.add_init_script("""
       navigator.webdriver = false
        Object.defineProperty(navigator, 'webdriver', {
          get: () => false
        })
      """
    )
perfrom the init script on the brower, Mandatory return value navigator.webdriver = false
I hope that it can solve your problem.

**Comment by kebinzhi** [comment]
Some bug in the antibot checking websites. It can't read the "navigator.plugins" for some reasons.when you set the plugins param manually, the "webdriver new" would be changed to false.

**Comment by MrElie** [comment]
> ![image](https://user-images.githubusercontent.com/17176354/109005681-2da04a80-76e5-11eb-96bf-752b753b43a6.png) As shown in the figure above, how to hide fingerprint information such as webdriver when visiting a webpage

i know its late to reply here, but i been looking for that website in the image for a while now. can u plz tell me the link where i can check the info in ur image ?

**Comment by LztCode** [comment]
Antibot link:Antibotbot.sannysoft.com发自我的 iPhone在 2023年1月21日，00:05，MrElie ***@***.***> 写道：﻿

 As shown in the figure above, how to hide fingerprint information such as webdriver when visiting a webpage

i know its late to reply here, but i been looking for that website in the image for a while now. can u plz tell me the link where i can check the info in ur image ?

**Comment by jlplenio** [comment]
> I find a good way to solve the navigator.webdriver--> ture problems. as follow: def run(playwright): browser = playwright.chromium.launch(headless=False) context = browser.new_context() page = context.new_page() page.add_init_script(""" navigator.webdriver = false Object.defineProperty(navigator, 'webdriver', { get: () => false }) """ ) perfrom the init script on the brower, Mandatory return value navigator.webdriver = false I hope that it can solve your problem.

On Chrome version 109.0.5414.120, I receive this error with your js:
```
Uncaught TypeError: Cannot redefine property: webdriver
    at Function.defineProperty (<anonymous>)
    at <anonymous>:1:8
```

The js code works in a browser not started through playwright.

**Comment by unhiro** [comment]
> > I find a good way to solve the navigator.webdriver--> ture problems. as follow: def run(playwright): browser = playwright.chromium.launch(headless=False) context = browser.new_context() page = context.new_page() page.add_init_script(""" navigator.webdriver = false Object.defineProperty(navigator, 'webdriver', { get: () => false }) """ ) perfrom the init script on the brower, Mandatory return value navigator.webdriver = false I hope that it can solve your problem.
> 
> On Chrome version 109.0.5414.120, I receive this error with your js:
> 
> ```
> Uncaught TypeError: Cannot redefine property: webdriver
>     at Function.defineProperty (<anonymous>)
>     at <anonymous>:1:8
> ```
> 
> The js code works in a browser not started through playwright.

I'm guessing we might be here for the same reason "Your browser is not currently supported. Please use a recommended browser or learn more here.", I had requested a feature on one of your projects and decided to see if I could make it work. I have all of it working but that one part.

**Comment by breaking153** [comment]
> > ![image](https://user-images.githubusercontent.com/17176354/109005681-2da04a80-76e5-11eb-96bf-752b753b43a6.png) As shown in the figure above, how to hide fingerprint information such as webdriver when visiting a webpage
> 
> i know its late to reply here, but i been looking for that website in the image for a while now. can u plz tell me the link where i can check the info in ur image ?

https://bot.sannysoft.com/

**Comment by breaking153** [comment]
> > > ![image](https://user-images.githubusercontent.com/17176354/109005681-2da04a80-76e5-11eb-96bf-752b753b43a6.png) As shown in the figure above, how to hide fingerprint information such as webdriver when visiting a webpage
> > 
> > 
> > i know its late to reply here, but i been looking for that website in the image for a while now. can u plz tell me the link where i can check the info in ur image ?
> 
> https://bot.sannysoft.com/
and this website use different ways to detect ：
console.log(navigator.webdriver); // false,if you use js script to hook webdriver object
console.log("webdriver" in navigator); //still,return true so you can't bypass the test

**Comment by metinc** [comment]
I use this solution:

```ts
import { test, expect } from "@playwright/test";

test.beforeEach(async ({ context }) => {
  await context.addInitScript(
    `const defaultGetter = Object.getOwnPropertyDescriptor(
      Navigator.prototype,
      "webdriver"
    ).get;
    defaultGetter.apply(navigator);
    defaultGetter.toString();
    Object.defineProperty(Navigator.prototype, "webdriver", {
      set: undefined,
      enumerable: true,
      configurable: true,
      get: new Proxy(defaultGetter, {
        apply: (target, thisArg, args) => {
          Reflect.apply(target, thisArg, args);
          return false;
        },
      }),
    });
    const patchedGetter = Object.getOwnPropertyDescriptor(
      Navigator.prototype,
      "webdriver"
    ).get;
    patchedGetter.apply(navigator);
    patchedGetter.toString();`
  );
});

test("Stealth mode", async ({ page }) => {
  await page.goto("https://bot.sannysoft.com/");
  const webDriverCheckLovator = page.getByRole("row", {
    name: "WebDriver (New)",
  });
  await expect(webDriverCheckLovator).toHaveText(/passed/);
});
```

Found [here](https://stackoverflow.com/questions/53039551/selenium-webdriver-modifying-navigator-webdriver-flag-to-prevent-selenium-detec/69533548#69533548).
