### ISSUE TITLE
download File

### ISSUE THREAD

**Issue by osmenia** [microsoft/playwright-python#528]
Hi Team,

I need help, 
Download works but 10 times is same (first) file downloaded. 

what i am doing wrang in code?

tnx

here is code:

`from playwright.sync_api import sync_playwright
import base64
import sys
import time

def run(playwright):
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context(accept_downloads=True)
    df3 = pd.DataFrame()

    # Open new page
    page = context.new_page()

    page.goto(
        "https://file-examples.com/index.php/sample-documents-download/sample-xls-download/")

    cookies = context.cookies()
    # print("Coockies", cookies)

    handles = page.query_selector_all("#table-files .file-link")

    for x in handles:
        with page.expect_download() as download_info:
            page.click("a.btn")

        download = download_info.value
        print(download)
        path = download.path()
        print(path)

    page.close()

# ---------------------
    context.close()
    browser.close()

with sync_playwright() as playwright:
    run(playwright)
`

**Comment by mxschmitt** [comment]
`page.click("a.btn")` would always click on the first link element with the `btn` class. Instead you have to loop over the file links, what you are already doing and then based on that find the next link element and click on it. A full example you you'll find here:

```py
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page(accept_downloads=True)
    page.goto(
        "https://file-examples.com/index.php/sample-documents-download/sample-xls-download/"
    )

    handles = page.query_selector_all("#table-files .file-link")

    for handle in handles:
        with page.expect_download() as download_info:
            handle.query_selector("a.btn").click()

        download = download_info.value
        path = download.path()
        print(download.url, path)

    page.close()
    browser.close()

```

**Comment by osmenia** [comment]
Tnx a lot Max
