### ISSUE TITLE
make page.is_hidden fail if selector is not matching anything

### ISSUE THREAD

**Issue by pohlt** [microsoft/playwright-python#533]
I could bet that (with an older playwright version) I got an error when I tried to check the visibility of an element using `page.is_hidden` when the selector did not match anything.

I just tried it with 1.9.0 and a `page.is_hidden("#no_match")` gives me a `True` which is tricky because any typo in the selector would lead to a positive check for `page.is_hidden`. If I'm explicitly checking a certain element which cannot be found, I would consider it safer and more helpful to get an exception. I could still catch the exception and proceed if I'm fine with the element missing.

**Comment by zhonghai9967** [comment]
我觉得现在的方法更符合逻辑。
#no_match元素没找到时，True

**Comment by pohlt** [comment]
Hm, you might be right, but I'll never know. My Japanese(?)  is a bit rusty. ;-)

**Comment by pavelfeldman** [comment]
Depending on the framework used, hiding element can be implemented via detaching it from DOM, so as a result it'll also throw in these legit use cases. For now, you can query_selector(selector).is_hidden() in order to force DOM attachment.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to file another issue with additional details.
