### ISSUE TITLE
Either path or source parameter must be specified

### ISSUE THREAD

**Issue by YusukeIwaki** [microsoft/playwright-python#534]
I found a little confusing error message.

```python
from playwright.sync_api import sync_playwright

with sync_playwright() as playwright:
    browser = playwright.chromium.launch()
    try:
        page = browser.new_page()
        page.add_init_script()
    finally:
        browser.close()
```

This code throws an error `Either path or source parameter must be specified`
However page.add_init_script doesn't have `source` parameter.

IMHO, `Either path or script parameter must be specified` would be better.

**Comment by kumaraditya303** [comment]
It has  `source` parameter :
https://github.com/microsoft/playwright-python/blob/246aed8cfed64fca10aa8d5e3c551add30d22b6f/playwright/sync_api/_generated.py#L6071 @YusukeIwaki

**Comment by YusukeIwaki** [comment]
It has 'script' instead of source.

**Comment by kumaraditya303** [comment]
Oh, it should be source instead of script
