### ISSUE TITLE
RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by JLpython-py** [microsoft/playwright-python#550]
After running `pip install playwright` and `playwright install`, I went to the documentation to try some of the features out. Here is the code which I ran:

```python
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    browser = p.chromium.launch()
page = browser.new_page()
```

However, I received an error: `RuntimeError: Event loop is closed`.

I proceeded to try the same process by with `browser=p.firefox.launch()`, but to no avail.

Specifications:

- Python 3.9.2
- Playwright v1.9.1

**Comment by kumaraditya303** [comment]
You are creating new page outside of the playwright context manager,

```python
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
  browser = p.chromium.launch()
  page = browser.new_page()
```

**Comment by JLpython-py** [comment]
So is there a way to use `page` and `browser` outside a `with` statement? I tried this:

```python
p = sync_playwright()
browser = p.chromium.launch()
```

but it does not work either. I have a feeling there is something discussing this later in the documentation, but it would be much appreciated if it were to be pointed out now.

**Comment by kumaraditya303** [comment]
Yes, 
```python
from playwright.sync_api import sync_playwright

p = sync_playwright().start()
browser = p.chromium.launch(
    executable_path=r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
    headless=False,
)
page = browser.new_page()
page.goto("http://www.google.com/")
browser.close()
p.stop()
```

**Comment by JLpython-py** [comment]
Okay, that clarifies quit a bit. Thank you so much!

**Comment by kumaraditya303** [comment]
@pavelfeldman May be discussions for this repo should be enabled for these type of question

**Comment by JLpython-py** [comment]
> Yes, if you want to use without `with` then you need to manually call `start` and `stop` @JLpython-py
> 
> ```python
> from playwright.sync_api import sync_playwright
> 
> p = sync_playwright().start()
> browser = p.chromium.launch(
>     executable_path=r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
>     headless=False,
> )
> page = browser.new_page()
> page.goto("http://www.google.com/")
> browser.close()
> p.stop()
> ```

It took me a while, but I was finally able to implement this into my scripts and I tested it out. However, not I get a warning message:

```
(node:4464) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a pr
omise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.h
tml#cli_unhandled_rejections_mode). (rejection id: 2)
```

Do you know what this means and how I can fix it?

**Comment by pavelfeldman** [comment]
What is your edge browser version?

**Comment by JLpython-py** [comment]
> What is your edge browser version?

Version 89.0.774.57

**Comment by pavelfeldman** [comment]
Sorry for the late reply. Your snippet looks correct, but we need more information to address this. Could you run your snippet with the `DEBUG=pw:browser*` environment variable set? That would help us identifying the issue.

**Comment by JLpython-py** [comment]
I think I was able to solve it, assuming my fix is relevant to the warning. I spent a while debugging and one of my tests didn't call `browser.close()` before calling `p.stop()` (from the above comment). I haven't seen the warning message much after fixing this, so I think this may be the solution to my issue.
