### ISSUE TITLE
No module named 'playwright._repo_version'

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright-python#56]
ImportError while loading conftest '/home/pfeldman/code/playwright-python/tests/conftest.py'.
tests/conftest.py:19: in <module>
    import playwright
playwright/__init__.py:15: in <module>
    from playwright._repo_version import version as __version__  # noqa:F401
E   ModuleNotFoundError: No module named 'playwright._repo_version'

**Comment by pavelfeldman** [comment]
@mxschmitt ^^

**Comment by mxschmitt** [comment]
@pavelfeldman `pip install -e .` will fix it. Is needed when running it locally for development. (-e is a symlink instead of copy).
