### ISSUE TITLE
can't install chrome

### ISSUE THREAD

**Issue by Lee7goal** [microsoft/playwright-python#565]
traceback is 
Error: EPERM: operation not permitted, open 'C:\Users\admin\AppData\Local\ms-playwright\chromium-854489\chrome-win\chrome_elf.dll'
what should i do

**Comment by yury-s** [comment]
Can you check if your have permissions to access that file and whether you can launch chromium from 'C:\Users\admin\AppData\Local\ms-playwright\chromium-854489\chrome-win\chrome.exe' without playwright?

**Comment by Lee7goal** [comment]
i check it , but it can't run

**Comment by yury-s** [comment]
Is the browser there? It may be that the installation failed and you just need to run `playwright install` again to fix it.

**Comment by pavelfeldman** [comment]
Please file a new issue with the additional details if you are still experiencing this.
