### ISSUE TITLE
Wait until on the same page new url is loaded

### ISSUE THREAD

**Issue by akozyreva** [microsoft/playwright-python#567]
Hi!
I have the following situation. I have Internet Page, I make a click and another page at the same tab  with another url must be downloaded. How can I handle this execution? Is there any method like `wait until url is` ?

**Comment by yury-s** [comment]
`page.click` will automatically wait for synchronously triggered navigation. If this is not enough you can use [`page.expect_navigation()`](https://playwright.dev/python/docs/api/class-page?_highlight=expect_navig#pageexpect_navigationkwargs) and filter by url (if need be).
