### ISSUE TITLE
configure for hermetic install does not install/place browsers inside the virtual environment on Windows 10 OS

### ISSUE THREAD

**Issue by ebzimny01** [microsoft/playwright-python#568]
**Environment:**

- Windows 10 (10.0.19042 Build 19042) x64
- Python 3.8.5
- PIP 21.0.1

**Repro:**

1. Environment is a brand new Win10 VM running on hyper-v; the only apps I installed on it were Python 3.8.5 and Github Desktop
2. Created and activated Python virtual environment called "gdr-install"
3. Tried following the hermetic install steps found here: https://playwright.dev/python/docs/installation
`# Windows`
`$ set PLAYWRIGHT_BROWSERS_PATH=0`
`$ pip install playwright`
`$ playwright install`

**Expected Result:**

The Playwright browsers would be installed/placed inside the Python virtual environment:
`C:\Users\User\code\venv\gdr-install\Lib\site-packages\playwright\driver\package\...`

**Actual Result:**
The Playwright browsers are installed/placed in the default location:
`C:\Users\User\AppData\Local\ms-playwright\...`

Screenshot showing steps and output
![image](https://user-images.githubusercontent.com/32172592/110816009-f55a4980-8258-11eb-8f7d-5b5486e5fe6f.png)

Screenshot showing $Env:Path. Only the virtual environment shows on path. No other Python directory is in Path.
![image](https://user-images.githubusercontent.com/32172592/110816351-423e2000-8259-11eb-8938-fb9121afcf2b.png)

**Other Comments:**
I tried the similar steps on a Linux VM and the process does seem to work properly on Linux. It will install/place the browsers inside the Python virtual environment.

**Comment by kumaraditya303** [comment]
You are using powershell but the instruction on docs are for `cmd.exe`
You can do the same with 
```powershell
$env:PLAYWRIGHT_BROWSERS_PATH=0
```
@ebzimny01

**Comment by ebzimny01** [comment]
Very rookie mistake on my part. Should have been able to figure that out.

Thank you!

Closing.
