### ISSUE TITLE
Additionally running python -m playwright install 

### ISSUE THREAD

**Issue by akashdiware** [microsoft/playwright-python#570]
For Python to use playwright we need to install this package first and then we need to install browser drivers to get it work.

To working with playwright in Python we run following commands

pip install playwright
python -m playwright install 

So why we need to run this additional command is it possible to get it done through pip install only?

I have used playwright in java as well there just specifying dependency in pom.xml is enough everything will be done ok the fly.

**Comment by mxschmitt** [comment]
Unfortunately the Python/PIP ecosystem is not designed to allow executing custom processes in the install phase, also no stdout/stderr gets forwarded there. Thats the reason why this additional install step is necessary.

Does it cause any issue in your setup?

**Comment by akashdiware** [comment]
Not specifically!

Now I have to add additional script to get it done in CI/CD pipelines

I thought it will be good to get it done in pip install -r requirements.txt phase only.

Thank you for get it clear.
