### ISSUE TITLE
error while running `playwright install` using Python

### ISSUE THREAD

**Issue by JacobWoolbright** [microsoft/playwright-python#574]
C:\Users\JacobWoolbright>python -m playwright install

Failed to install browsers
Error: Failed to download chromium, caused by
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)

playwright also throws the same error upon doing `playwright install`

Python 3.8.5 on Windows 10

**Comment by pavelfeldman** [comment]
You are either behind a firewall or proxy that blocks Microsoft CDN or your corporate network chose to not trust its certificates.
