### ISSUE TITLE
[BUG] misleading error message "browser was not found" if browser fails to start for other reasons

### ISSUE THREAD

**Issue by mnezh** [microsoft/playwright-python#577]
# Environment
playwright==1.9.2
ubuntu 20.04 in docker
chromium v854489 installed via `python3 -m playwright install`

# Problem description:
Unintentionally, the test attempted to launch headful chromium, launch failed with misleading error message:
```
"chromium" browser was not found.
Please complete Playwright installation via running
    "python -m playwright install"
```
Launching browser as `chromium.launch(headless=True)` was succesful, so the problem clearly was not with browser installation, but browser launch inself (most probably, unavailable X11)

# Expected behavior:
browser stderr captured and displayed

**Comment by mxschmitt** [comment]
Good catch! Fix is on the way in #572
