### ISSUE TITLE
[Feature request] Add uvloop support

### ISSUE THREAD

**Issue by pgtuk** [microsoft/playwright-python#582]
uvloop does not use or support child watchers, so after setting up it's event loop policy `asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())` we get a NonImplementedError in https://github.com/microsoft/playwright-python/blob/695ba5532cbf08bdb194af23647f1abf3d8cf5c4/playwright/_impl/_driver.py#L39

Example for reproduce

    import asyncio
    import uvloop

    asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())

    from playwright.async_api import async_playwright

    async def run(playwright):

        chromium = playwright.chromium
        browser = await chromium.launch()
        page = await browser.new_page()
        await page.goto('http://www.example.com')

        await browser.close()

    async def main():
        async with async_playwright() as playwright:
            await run(playwright)

    asyncio.run(main())

**Comment by kumaraditya303** [comment]
Try it with Python > 3.7
