### ISSUE TITLE
playwright --start-maximized not work

### ISSUE THREAD

**Issue by afishpro** [microsoft/playwright-python#585]
playwright version:1.9.2
Google Chrome (or Microsoft Edge(89.0.774.57(64))) version: 89.0.4389.90(64)
python --version:3.8.8

code show as below：
<code>
    from playwright.sync_api import sync_playwright

    # url = r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
    with sync_playwright() as p:
        brower = p.chromium.launch(executable_path=r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
                                   headless=False, args=["--incognito", "--start-in-incognito",
                                                         "--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36",
                                                         "--log-level=3", '--no-sandbox',
                                                         "--disable-infobars", "--enable-automation=False",
                                                         "--disable-blink-features=AutomationControlled",
                                                         "--window-size = '1920,1080'", "--start-maximized"])
        # "--auto-open-devtools-for-tabs=True","--window-size = "1920,1080"])
        # brower = p.chromium.launch(url)
        page = brower.new_page(viewport={'width': 1920, 'height': 1080})
</code>
as shown below:

![QQ图片20210320182723](https://user-images.githubusercontent.com/11978864/111866664-fc483100-89a9-11eb-9427-8d296994db83.png)

i set the --start-maximized attribute, but it doesn’t work

**Comment by pavelfeldman** [comment]
You are still setting the viewport when creating page. Try passing `no_viewport=True` instead to explicitly tell Playwright to just go with the window size.

**Comment by afishpro** [comment]
> no_viewport
page = brower.new_page(viewport={'width': 1920, 'height': 1080}, no_viewport=True)
thank you very much for your answers, this solved my problem
