### ISSUE TITLE
How do I close "Restore pages" popup?

### ISSUE THREAD

**Issue by etishka** [microsoft/playwright-python#586]
after browser was killed and then restarted, Chrome shows a popup box offering to restore pages. How to I close it with playwright?

**Comment by pavelfeldman** [comment]
Are you using launch_persistent_context with the same user data dir? What is your use case?

**Comment by etishka** [comment]
yes, exactly. launch_persistent_context with the same browser profile - to save auth fingerprint. 
Sometimes the application doesn't perform graceful shutdown, but is killed forcibly. For example it can happen when the cloud instance is shut down.

**Comment by pavelfeldman** [comment]
You should reuse auth state via the corresponding apis: https://playwright.dev/python/docs/auth#reuse-authentication-state. That way you don't depend on corrupt profiles and related errors.

**Comment by etishka** [comment]
thanks, will take a look!

**Comment by pavelfeldman** [comment]
Closing as per above, there isn't much we can do should you choose to reuse profile...
