### ISSUE TITLE
GH Actions: playwright.sh and node: Permission denied

### ISSUE THREAD

**Issue by imWildCat** [microsoft/playwright-python#588]
Repro step:

1. Step a Python project on GitHub using GH Actions to install playwright-python on the CI machine
2. While running `python -m playwright install`, you might see 

```shell
Traceback (most recent call last):
1230
  File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/runpy.py", line 197, in _run_module_as_main
1231
    return _run_code(code, main_globals, None,
1232
  File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/runpy.py", line 87, in _run_code
1233
    exec(code, run_globals)
1234
  File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/site-packages/playwright-1.9.2-py3.9-linux-x86_64.egg/playwright/__main__.py", line 32, in <module>
1235
    main()
1236
  File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/site-packages/playwright-1.9.2-py3.9-linux-x86_64.egg/playwright/__main__.py", line 28, in main
1237
    subprocess.run([str(driver_executable), *sys.argv[1:]], env=my_env)
1238
  File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/subprocess.py", line 505, in run
1239
    with Popen(*popenargs, **kwargs) as process:
1240
  File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/subprocess.py", line 951, in __init__
1241
    self._execute_child(args, executable, preexec_fn, close_fds,
1242
  File "/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/subprocess.py", line 1823, in _execute_child
1243
    raise child_exception_type(errno_num, err_msg, err_filename)
1244
PermissionError: [Errno 13] Permission denied: '/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/site-packages/playwright-1.9.2-py3.9-linux-x86_64.egg/playwright/driver/playwright.sh'
1245
Error: Process completed with exit code 1.
```

Sample GH Actions output: https://github.com/imWildCat/scylla/runs/2159854168?check_suite_focus=true#step:4:1244

I can only install playwright drive by using this workaround:

```shell
sudo chmod +x /opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/site-packages/playwright-1.9.2-py3.9-linux-x86_64.egg/playwright/driver/playwright.sh
python -m playwright install
```

In addition, after working around this issue, I also found another issue where no permission for `node`:

```
---------------------------- Captured stderr setup -----------------------------
/opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/site-packages/playwright-1.9.2-py3.9-linux-x86_64.egg/playwright/driver/playwright.sh: 3: /opt/hostedtoolcache/Python/3.9.2/x64/lib/python3.9/site-packages/playwright-1.9.2-py3.9-linux-x86_64.egg/playwright/driver/node: Permission denied
```
Reference: https://github.com/imWildCat/scylla/pull/137/checks?check_run_id=2159995227#step:6:142

**Comment by kumaraditya303** [comment]
It is permission issue due to the use of `sudo`
Try this config: 
```yaml
name: 'Python package: Scylla'

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [ 3.9 ]

    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/playwright-github-action@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -r tests/requirements-test.txt
        pip install -e.
        python -m playwright install
    - name: Lint with flake8
      run: |
        make style-check
    - name: Test with pytest
      run: |
        pytest --cov=./scylla tests
```

**Comment by imWildCat** [comment]
Thanks @kumaraditya303 but it doesn't feel like working: https://github.com/imWildCat/scylla/runs/2167141823

I wonder whether there's a way to install playwright directly in the shell script rather than use a pre-defined action?

**Comment by kumaraditya303** [comment]
@imWildCat The problem is that running playwright on especially Linux is not as simple as `pip install playwright` but rather it requires many system libraries and dependencies to be installed. Moreover as I can see there are permission error in your case but I don't think that's the real cause as I myself has a web application tested with playwright and it works flawlessly, I would like to ask if the tests you run are working locally by your side and you can try printing the permissions to check?, I have a thought that because your installation wasn't successful because of `pycurl` I guess it created some permission errors during pip installation.

**Comment by kumaraditya303** [comment]
@imWildCat I have updated the earlier yaml config, you may try it again

**Comment by imWildCat** [comment]
@kumaraditya303 Thanks a lot!

It [works](https://github.com/imWildCat/scylla/runs/2171259741)!

Could you share the location of `playwright.sh`? I couldn't find it but would like to take a look.
