### ISSUE TITLE
Incompatible: playwright and pyarmor

### ISSUE THREAD

**Issue by Ocayy** [microsoft/playwright-python#589]
I have tried compiling some python scripts using pyarmor in which I am using Playwright.

Everything went well, but after compiling I get an error:
```
================================================= ===============================
"firefox" browser was not found.
Please complete Playwright installation via running

     "python -m playwright install"

================================================== ==============================
, retrying ... 
```

I read issue #342 and tried this method as well and nothing has changed. I know that maybe it's my fault, anyway, could I ask for help?

### Line of code where error occuring:
- First version - before I read #342 `browser = await playwright.firefox.launch(headless=True)`
- Second version - after I read #342 `browser = await playwright.firefox.launch(headless=True, executable_path=Path(sys.modules['playwright'].__file__).parent / 'driver' / 'package' / '.local-browsers' / 'firefox-1234' / 'firefox')`

Additionally I'd like to add that i manually checked Path from second version of code and browser is in there.

### Context information
- version of python: 3.8.6
- version of playwright-python:  1.9.2
- version of pyarmor: 6.6.2
- platform: Windows 10

**Comment by pavelfeldman** [comment]
We've never considered explicit support for obfuscation, so this is outside of the scope for Playwright project.
