### ISSUE TITLE
[Docs] Provide web_socket example in the documentation

### ISSUE THREAD

**Issue by nandakumarhavanur** [microsoft/playwright-python#595]
I am using playwright with python, and want to automate web_socket integration in my application, your documentation do speak about different events that can be captured for web_socket but there is no info or any example on how to use it, so please provide one example how to use this feature, would be of great help, thanks in advance.

**Comment by mxschmitt** [comment]
In the tests you can obtain the usage for the WebSocket class: https://github.com/microsoft/playwright-python/blob/master/tests/async/test_websocket.py

Keep in mind, that with WebSockets in Playwright you so far can only read and not modify them.

**Comment by pavelfeldman** [comment]
https://playwright.dev/python/docs/network#websockets
