### ISSUE TITLE
Playwright doesn't support all characters

### ISSUE THREAD

**Issue by Asutosh2805** [microsoft/playwright-python#602]
Please let me know whether languages other than English(Odiya in my case) are supported in PDF creation from an HTML page, using 'playwright pdf'.
if not supported then can it be made to support? or any other way that can be suggested will be appreciated.

I am trying to render this website using playwright [http://www.odisha.com/] (url) which contains Odiya language
you can see the output below 

![image](https://user-images.githubusercontent.com/69514536/112495539-fd160400-8da9-11eb-8262-b0fe262a8071.png)

**Comment by mxschmitt** [comment]
A wild guess is that the fonts are not available on the system. Which operating system are you using? For Ubuntu the package [`fonts-orya-extra`](https://ubuntu.pkgs.org/20.04/ubuntu-main-amd64/fonts-orya-extra_2.0-6_all.deb.html) might help.

**Comment by JoelEinbinder** [comment]
We need more details in order to be able to address this issue, namely answer to the above. I'll close this bug as non-actionable, but if this still happens to you, could you please file a new issue with the log dump and link this one?
