### ISSUE TITLE
[help]How can I start the browser without entering the incognito mode

### ISSUE THREAD

**Issue by afishpro** [microsoft/playwright-python#605]
I did not add the parameter --incognito at startup,but the browser automatically enters incognito mode

**Comment by mxschmitt** [comment]
You can use launch_persistent_context which does not use an incognito mode: https://playwright.dev/python/docs/api/class-browsertype#browser_typelaunch_persistent_contextuser_data_dir-kwargs

**Comment by afishpro** [comment]
> 您可以使用不使用隐身模式的launch_persistent_context：[https](https://playwright.dev/python/docs/api/class-browsertype#browser_typelaunch_persistent_contextuser_data_dir-kwargs) ://playwright.dev/python/docs/api/class-browsertype#browser_typelaunch_persistent_contextuser_data_dir-kwargs[](https://playwright.dev/python/docs/api/class-browsertype#browser_typelaunch_persistent_contextuser_data_dir-kwargs)

okay, let me try it, thank you for your answer

**Comment by pavelfeldman** [comment]
We aren't in the incognito mode per se, but we are using off the record profile yes.
