### ISSUE TITLE
i wanna use playwright with playwright,but sth stop me 

### ISSUE THREAD

**Issue by xueneymar** [microsoft/playwright-python#607]
![image](https://user-images.githubusercontent.com/13958555/113283209-8aada280-931a-11eb-80b3-463e18e0b3bf.png)

**Comment by mxschmitt** [comment]
For the CI or environments without an visual interface you have two option available:

a) run tests headed/headful by using `xvfb-run` see here for docs: https://playwright.dev/docs/ci#running-headful
b) run tests headless without the `headless=False` parameter

**Comment by dgozman** [comment]
Closing in favor of upstream documentation issue.
