### ISSUE TITLE
the program crashes after running for a while

### ISSUE THREAD

**Issue by afishpro** [microsoft/playwright-python#610]
python: 3.8.8
sys: windows10
dev: pycharm

error info:
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF62145192F napi_wrap+119119
 2: 00007FF6213F8A26 v8::internal::OrderedHashTable<v8::internal::OrderedHashSet,1>::NextTableOffset+38102
 3: 00007FF6213F9826 node::OnFatalError+438
 4: 00007FF621C3671E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF621C1E8D1 v8::SharedArrayBuffer::Externalize+833
 6: 00007FF621AD00AC v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1436
 7: 00007FF621ADB2F0 v8::internal::Heap::ProtectUnprotectedMemoryChunks+1312
 8: 00007FF621AD7E04 v8::internal::Heap::PageFlagsAreConsistent+3204
 9: 00007FF621ACD603 v8::internal::Heap::CollectGarbage+1283
10: 00007FF621ACBC74 v8::internal::Heap::AddRetainedMap+2500
11: 00007FF621AE6400 v8::internal::Factory::AllocateRawWithAllocationSite+96
12: 00007FF621AF0982 v8::internal::Factory::NewJSObjectFromMap+50
13: 00007FF621A10C87 v8::internal::TimedHistogram::Stop+44455
14: 00007FF621A13F86 v8::internal::TimedHistogram::Stop+57510
15: 00007FF621A12F9A v8::internal::TimedHistogram::Stop+53434
16: 00007FF621BAFA71 v8::internal::Builtins::builtin_handle+83297
17: 00007FF621BB001E v8::internal::Builtins::builtin_handle+84750
18: 00007FF62208B9BD v8::internal::SetupIsolateDelegate::SetupHeap+547181
19: 00007FF62201074C v8::internal::SetupIsolateDelegate::SetupHeap+42748
20: 00007FF62201074C v8::internal::SetupIsolateDelegate::SetupHeap+42748
21: 00007FF62200DC81 v8::internal::SetupIsolateDelegate::SetupHeap+31793
22: 00007FF62200D86C v8::internal::SetupIsolateDelegate::SetupHeap+30748
23: 00007FF621B29B63 v8::internal::Execution::CallWasm+1395
24: 00007FF621B294E6 v8::internal::Execution::Call+182
25: 00007FF621C14EDD v8::Function::Call+605
26: 00007FF62147469C node::CallbackScope::~CallbackScope+1660
27: 00007FF621474AFC node::MakeCallback+204
28: 00007FF62143E4DB napi_wrap+40187
29: 00007FF621498F68 uv_check_init+120
30: 00007FF6214A3739 uv_run+713
31: 00007FF6213ADF01 v8::internal::RegExpMacroAssemblerX64::stack_limit_slack+8033
32: 00007FF621423025 node::Start+293
33: 00007FF621286A9C RC4_options+340380
34: 00007FF6221439A8 v8::internal::SetupIsolateDelegate::SetupHeap+1300824
35: 00007FF953977C24 BaseThreadInitThunk+20
36: 00007FF954A8D721 RtlUserThreadStart+33

i didn't catch anything wrong
after the program runs automatically for a while ，the program crashes directly

**Comment by mxschmitt** [comment]
a few questions to debug this further, what means a while, a day, a week or longer? Is it reproducible? How much RAM has your machine available/free?

**Comment by afishpro** [comment]
> a few questions to debug this further, what means a while, a day, a week or longer? Is it reproducible? How much RAM has your machine available/free?

I ran it for about 6 hours，the computer is configured with 16G memory，i did not capture the detailed error information here, and can only provide the limited error information above，i only know that there is this problem。during my operation, as long as the time is too long, it will crash

**Comment by pavelfeldman** [comment]
We would need more details about the nature of your script to know if this is a leak on our side. For example, is that a single page opened or a bunch of pages you navigate between? Are you using a separate browser context for each scenario? For example, if you create a single context and then crawl the web, all those network requests that belong to the context are retained, which can result in the out of memory situation.

**Comment by afishpro** [comment]
> We would need more details about the nature of your script to know if this is a leak on our side. For example, is that a single page opened or a bunch of pages you navigate between? Are you using a separate browser context for each scenario? For example, if you create a single context and then crawl the web, all those network requests that belong to the context are retained, which can result in the out of memory situation.

OK，I will list my detailed steps
        chrome = pw_start.chromium.launch(executable_path=executable_path, headless=headless, args=self.args,  slow_mo=90)
        page = chrome.new_page(no_viewport=True)
        page.goto("xxx")
do some of my logic below, such as logging in
Immediately afterwards, I am on this page and goto to other pages of this website
            page.goto(url, timeout=40000)
have a loop, after processing the logic, continue goto on the current page to the next page
This website page is a traditional page, not a single page

**Comment by afishpro** [comment]
Will it cause this problem because I have been executing page.goto()?

**Comment by pavelfeldman** [comment]
Playwright will collect payloads belonging to the browser context while that browser context is in use. Typically, you would create a new browser context for each unit of work, in your case for each page you navigate to.

**Comment by afishpro** [comment]
> Playwright will collect payloads belonging to the browser context while that browser context is in use. Typically, you would create a new browser context for each unit of work, in your case for each page you navigate to.

oh,i know,but if I open a new unit, because the two units are independent, I need to reprocess the login status,and i don't think goto should collapse in the same unit all the time

**Comment by afishpro** [comment]
multiple execution page.goto("example") 

code for example：
    page = await play.new_page()
    # page = await play.new_page(viewport={'width': 1920, 'height': 1080})
    for x in range(999999):
        await page.goto("https://www.suning.com/")
        await asyncio.sleep(1.5)

as the task manager can see, memory has been growing
![QQ截图20210407104755](https://user-images.githubusercontent.com/11978864/113803488-3fb6e380-978f-11eb-8ecb-62231809b843.png)
![QQ截图20210407104803](https://user-images.githubusercontent.com/11978864/113803494-4180a700-978f-11eb-9f41-c05fd5ffd369.png)
![QQ截图20210407105050](https://user-images.githubusercontent.com/11978864/113803498-42193d80-978f-11eb-9247-971dfada0733.png)

**Comment by afishpro** [comment]
i think goto method causes memory leak

**Comment by afishpro** [comment]
and i use close

async def main_run():
    play = await browser.start_persistent_browser_async()
    page = await play.new_page()
    for x in range(999999):
        page = await play.new_page()
        await page.goto("https://for example/")
        await page.close()
        await asyncio.sleep(1.5)
    time.sleep(100000)

It seems that the memory will not soar, but the goto method memory continues to overflow, which feels a bit problematic

**Comment by pavelfeldman** [comment]
https://playwright.dev/python/docs/auth#reuse-authentication-state might help to use context per unit of work

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/6319
