### ISSUE TITLE
[Feature] Integration with BDD pattern

### ISSUE THREAD

**Issue by vranky** [microsoft/playwright-python#615]
Is there any option for integration python-playwright with some BDD library like behave (https://behave.readthedocs.io/en/stable/)?

**Comment by afishpro** [comment]
I think this is okay. They are all independent libraries, and the splicing function is just fine.

**Comment by mxschmitt** [comment]
Closed for now since this is something which can be implemented in user-land and there are no plans to adopt external libraries into Playwright.
