### ISSUE TITLE
Chromium "Out of Memory" error results in hang

### ISSUE THREAD

**Issue by Sundwalltanner** [microsoft/playwright-python#616]
OS: Windows 10
Python: 3.8.7
Playwright: v1.10.0
Chromium: 90.0.4430.0

After running a context for a little less than an hour, Chromium redirects to this page:

![chrome_2021-04-08_16-07-11](https://user-images.githubusercontent.com/11891490/114107972-eaf69400-9886-11eb-94a3-8c72cf8a5367.png)

And Playwright itself just sits there doing absolutely nothing, when the `wait_for_selector()` call that my code's sitting on should timeout after the default timeout value of 30 seconds.

Hitting this `Out of Memory` page in Chromium isn't an issue for me, because with the way I've got things set up, any issues like this should cause the current context to be closed and a new one opened to continue from where the previous one ran into an issue.

My biggest problem here is that Playwright becomes unresponsive. If I could get it to raise an exception instead, that'd be preferred.

At first, this happened in headless, so I had no idea what was actually causing the hang. Then I reran it headed and was not only able to screenshot the page it was happening on, but once I manually intervened and clicked the `Learn more` link seen in the image above, Playwright started functioning again and acknowledged that it had timed out after 30 seconds, even though it had been sitting at this Chromium error screen for around 20 minutes.

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright-python/issues/610
