### ISSUE TITLE
[Question] Using typing syntax in automation scripts

### ISSUE THREAD

**Issue by amittendulkar** [microsoft/playwright-python#617]
I am getting better VS Code suggestion/completion support by adding below typing syntax in my functions (using playwright v1.10.1),

```
from playwright._impl._page import Page

def my_func(page: Page):
    page.click('"My text"')
```

I wanted to know whether the package hierarchy (e.g. `playwright._impl._page`) is going to remain intact through all minor versions (I assume it should not change through the new semantic versioning introduced).

**Comment by mxschmitt** [comment]
`_impl` imports are not designed to be consumed. You can use this to get your correct type:

```
from playwright.sync_api import Page
```

They are guaranteed to work in new releases (following SemVer).

**Comment by amittendulkar** [comment]
Thanks, closing...
