### ISSUE TITLE
Help with selectors

### ISSUE THREAD

**Issue by etishka** [microsoft/playwright-python#619]
I'm not sure how to write selector properly. The HTML has array of divs like below
```
<div>
  <div>
    <h2>
      <a>TEXT_TO_CAPTURE</a>
    </h2>
  </div>
  <table>
    <tbody>
      <tr>
        <td>
         <div>KNOWN_TEXT</div>
        </td>
       </tr>
     </tbody>
  </table>
</div>

<div>
  .... // same structure as above
</div>
```

The task is to capture TEXT_TO_CAPTURE, knowing text from a table cell. I did `page.query_selector('*css=tbody >> text="KNOWN_TEXT"')`, but it only returned  `tbody`. I also tried `page.query_selector('css=div:has(tbody >> text="KNOWN_TEXT")')` but it doesn't seem a valid syntax

**Comment by amittendulkar** [comment]
You can get the element handle of parent div using your first call,
```
my_div = page.query_selector('*css=div >> css=table >> text="KNOWN_TEXT"')
my_text = my_div.query_selector('div > h2 > a').inner_text()
# my_text will be TEXT_TO_CAPTURE
```

**Comment by pavelfeldman** [comment]
Try `playwright codegen` and see what it suggests?

**Comment by mxschmitt** [comment]
Closed as part of the triage, please re-open if its still persistent.
