### ISSUE TITLE
Unable to debug with playwright object in browser with Robotframework

### ISSUE THREAD

**Issue by amittendulkar** [microsoft/playwright-python#620]
This issue wasn't present in playwright 0.171.x. But I have started seeing it after upgrading playwright to 1.10.x. 

I have created a custom python library to be used with RobotFramework.  To debug the selectors I put the `breakpoint()` call to a point where I want to debug. 

I set the `$env:PWDEBUG = '1'` in PowerShell. When I start my RobotFramework execution, the Playwright Inspector starts in the background along with the browser and it seems the execution halts at the first statement. 

I can select the browser but however, due to the nature of execution in RobotFramework I can't focus on the Inspector to continue the execution.

Is there a way by which I can get/use the playwright object in the browser console and not open Playwright Inspector?

The below documentation, link explains the above process but it doesn't seem to work without the Inspector getting open.
https://playwright.dev/python/docs/debug#run-in-debug-mode

**Comment by amittendulkar** [comment]
I have found a workaround for the above issue,

- Hover your mouse over the "Playwright Inspector" task bar button to see the preview of inspector window
- Right click on the preview window and select maximize
- Playwright inspector gets maximized and you can now interact with it.

Feel free to close the issue if you don't feel the need to separate out the flag to launch Playwright inspector and the flag to create the playwright object in the browser console.

**Comment by dgozman** [comment]
I think the solution here would be more precise control over various debugging capabilities than just a single `PWDEBUG=1` value. See https://github.com/microsoft/playwright/issues/5693 for upstream issue. Closing this one as a duplicate.
