### ISSUE TITLE
[internal] Maintainers for conda package of playwright

### ISSUE THREAD

**Issue by kumaraditya303** [microsoft/playwright-python#646]
https://github.com/conda-forge/staged-recipes/pull/14387

 Maintainers who want to be added as maintainers for the conda repo comment in this issue stating that you want to be added.

cc: @pavelfeldman @mxschmitt

**Comment by kumaraditya303** [comment]
Update: Mac and Linux builds are fixed only that Windows build is to be fixed as there is some problem in the infra causing `AssertionError`

**Comment by mxschmitt** [comment]
Please use #257 for status updates, thanks!
