### ISSUE TITLE
[API] Rename Error to PlaywrightError

### ISSUE THREAD

**Issue by kumaraditya303** [microsoft/playwright-python#653]
Most of the libraries uses exceptions prefixed with library name to distinguish with others and not to confuse others and I want to propose to rename `Error` to `PlaywrightError` and `TimeoutError` to `PlaywrightTimeoutError`.

It can be done with using getattr of module and we can deprecate the `Error` and `TimeoutError` using the [warnings](https://docs.python.org/3/library/warnings.html?highlight=warnings) module to deprecate them  and then remove them after two releases. This would give users enough time to migrate code to the new Exceptions.

If the maintainers like the idea and the approach then you can assign the issue to me and I will create the required changes.
Consider upvoting :+1: if you like the idea.

cc: @pavelfeldman @mxschmitt

**Comment by pavelfeldman** [comment]
Is there a bug this fixes? User can always import `Error as PlaywrightError`, or does not it help?

**Comment by kumaraditya303** [comment]
There  is a built-in `TimeoutError` which is confusing and `Error` is a very generic name and hence most of the libraries namespace this with their library name and Playwright should too

**Comment by pavelfeldman** [comment]
> Is there a bug this fixes? User can always import Error as PlaywrightError, or does not it help?

Could you comment on this?

**Comment by kumaraditya303** [comment]
It does work, not to be a must, but what about autocompletion for Error ?

**Comment by pavelfeldman** [comment]
If there was a bug filed, I would recommend doing the following instead of fixing the issue:
```py
from playwright.sync_api import TimeoutError as PlaywrightTimeoutError
```

**Comment by mxschmitt** [comment]
Closed as part of the triage and since it's no bug I'm closing it
