### ISSUE TITLE
[Question] How to interact with a input inside a iframe

### ISSUE THREAD

**Issue by CheemaOTB** [microsoft/playwright-python#656]
I'm trying to fill an input that is inside an iframe but I have had no luck. Here is the code. Am I doing something wrong?

`iframe = page.query_selector('xpath=//iframe[@title="payment"]').content_frame()

iframe.fill('//*[@id="cardCvc-input"]', '123')`

**Comment by mxschmitt** [comment]
Duplicate of #654

See an example in #655
