### ISSUE TITLE
Question about using stock Google Chrome

### ISSUE THREAD

**Issue by tcao2** [microsoft/playwright-python#667]
When using the stock Google Chrome browser by specifying the channel as in the [docs](https://playwright.dev/python/docs/browsers?_highlight=brow#google-chrome--microsoft-edge), does Playwright look for the stock Chrome executable currently installed on the system?

**Comment by mxschmitt** [comment]
Exactly, Playwright does look for chrome installed on the system. See here: https://github.com/microsoft/playwright/blob/07fb81a4efdcc4c2169a61a16b513b9d91be6c49/src/server/chromium/findChromiumChannel.ts

**Comment by tcao2** [comment]
Got it. Thank you!
