### ISSUE TITLE
[Question] How to update chromium setting when using playwright to control chromium 

### ISSUE THREAD

**Issue by b3wsh** [microsoft/playwright-python#675]
How to update chromium setting when using playwright to control chromium .

In playwright chromium when click element like `<a href="xxx.pdf">x.pdf</a>`, chromium will open it in pdf view, rather than download it directly.

I want to close the config in chromium setting. how can i close the setting in playwright when launching chromium?

chrome setting location:
Settings->Privacy and security->site settings-> Additional content settings-> PDF documents-> Download PDF files instead of automatically opening them in Chrome

**Comment by mxschmitt** [comment]
See here for a related issue which contains different way how to solve this: https://github.com/microsoft/playwright/issues/3509#issuecomment-675441299

**Comment by b3wsh** [comment]
After some test, I find another way to solve this problem. use click param **modifiers** with *Alt* , just like this `ele.click(modifiers=["Alt", ])`. 

And then I find that chrome will download the resource I clicked.

**Comment by mxschmitt** [comment]
Awesome! Will close it for now, I adjusted the title a bit so others might find this information as well.

**Comment by Serge-N** [comment]
For C# users something like :       

 `await page.GetByRole(AriaRole.Link, new() { Name = title }).ClickAsync(new() { Modifiers = new[] { KeyboardModifier.Alt } });`
