### ISSUE TITLE
[Question] In Playwright how to do the action that "Right click an element and then chose 'save as' options"

### ISSUE THREAD

**Issue by b3wsh** [microsoft/playwright-python#676]
In Platwright how to do the action that "Right click an element and then chose 'save as' options" to save something?
Thanks.

**Comment by mxschmitt** [comment]
Seems a duplicate or related to #435.

**Comment by mxschmitt** [comment]
Closed since this functionality is currently not supported by Playwright. What's the use-case for it? Then we can might consider it to implement it, but since it's browser specific and not all browsers support it, we need a useful use-case for it.

**Comment by Hamza-Bouhelal** [comment]
You could use keyboard shortcuts: First focus the desired element, then send the keys "shift+f10" then send arrow key down until you arrive at save as, then send enter. This might solve the problem.

**Comment by joinow** [comment]
but you can consider hot key after right mouse click :)
