### ISSUE TITLE
[BUG] Cannot find an unordered list element when crawling linkedin

### ISSUE THREAD

**Issue by syntapy** [microsoft/playwright-python#680]
**Context:**
- Playwright Version: [1.11.0]
- Operating System: [Debian 10 Linux]
- Python version: [3.9.2]
- Node version (in the python site-packages): [v12.20.1]
- Browser: [test on: Chromium. Haven't tried webkit]

**Code Snippet**

On [this](https://www.linkedin.com/search/results/people/?keywords=Quantum%20Computing&origin=SWITCH_SEARCH_VERTICAL) search results page on linked in (needs login), I query the following, with result in comments

```python 
result = await page.query_selector("//ul[@class='reusable-search__entity-results-list list-style-none']")
# <class 'NoneType'>

result = await page.query_selector("[class='reusable-search__entity-results-list list-style-none']")
#  <class 'NoneType'>

results = await page.query_selector_all("ul")
# has elements, but does not include class of desired element: 'reusable-search__entity-results-list list-style-none'

results = await page.query_selector_all("li.entity-result__item")
# has no elements
```

**Describe the bug**
The comment line following each result query shows whats contained in the `result` variable

I should be getting an element handle, but I am only getting `None` values. The first `query_selector_all("ul")` results in a list of 4 handles, but does not include the one I am trying to access, which is the search results directly

Not sure if this is a bug or if I am missing something

**Comment by syntapy** [comment]
yes, its working now, thanks

I didn't know about `wait_for_selector` and the `query_selector` [doc](https://playwright.dev/python/docs/api/class-page#pagequery_selectorselector) does not say that it doesn't wait

I think, as a noob, I had assumed that it would automatically wait based on the other aspects where playwright waited, so it might be good to add a clarification in the doc on those methods that don't wait?

I can submit a pr later. I assume that would be best in the main repo, correct?

**Comment by mxschmitt** [comment]
@syntapy sorry I oversaw your comment that you are open for submitting a PR. :/
I went already ahead and created a docs change patch for it: https://github.com/microsoft/playwright/pull/6514
