### ISSUE TITLE
How to slide the browser

### ISSUE THREAD

**Issue by RouPeng** [microsoft/playwright-python#683]
I want to slide to the bottom of the browser, but I don't know how to do it

**Comment by JoelEinbinder** [comment]
I'm not sure what you mean. We don't support moving the browser window. You can scroll the page to the bottom like this:
```py
page.evaluate("""() => {
      window.scrollTo(0, 1000000);
    }""")

```

**Comment by RouPeng** [comment]
> I'm not sure what you mean. We don't support moving the browser window. You can scroll the page to the bottom like this:
> 
> ```python
> page.evaluate("""() => {
>       window.scrollTo(0, 1000000);
>     }""")
> ```

It works! Thank you very much!
