### ISSUE TITLE
[FEATURE] Playwright on PyPy

### ISSUE THREAD

**Issue by kumaraditya303** [microsoft/playwright-python#687]
[PyPy](https://www.pypy.org/) is a fast, compliant alternative implementation of Python, it is much faster as compared to cpython, and is mostly used for pure python code. Since playwright is a pure python library, it can support it too.

Consider upvoting :+1: if you want to use playwright with pypy.

**Comment by mxschmitt** [comment]
What would be required to support it? If I remember correctly I tried it a couple of months ago and it was just working. I expect adding 3 bots for each OS should be enough?

**Comment by mxschmitt** [comment]
Looks like it all just works - I'll close it for now.
