### ISSUE TITLE
[BUG] Playwright Manylinux Compliance

### ISSUE THREAD

**Issue by kumaraditya303** [microsoft/playwright-python#688]
The wheels of playwright on PyPI https://pypi.org/project/playwright/1.10.0/#files  have manylinux compliance of 
[manylinux1](https://www.python.org/dev/peps/pep-0513/) and hence should be usable on distros newer [centos5](https://www.python.org/dev/peps/pep-0513/) as per the policy of the manylinux project but playwright only supports Ubuntu 18.04 & Ubuntu 20.04 https://playwright.dev/docs/intro?_highlight=syste#system-requirements hence playwright should restrict installation of the wheels to the only supported platforms  and operating system. With [PEP 600](https://www.python.org/dev/peps/pep-0600/) playwright can restrict installation to glibc version 2.17 or higher which would restrict its installation to only supported platforms. Also playwright driver requires glibc 2.17 or higher hence older versions wont't event get error as the driver cannot able to dlopen shared libs.

**Comment by pavelfeldman** [comment]
> The wheels of playwright on PyPI https://pypi.org/project/playwright/1.10.0/#files have manylinux compliance of
manylinux1 and hence should be usable on distros newer centos5 as per the policy of the manylinux project

We only support Ubuntu 18 and Ubuntu 20 officially, there is a sections in the docs for this: https://playwright.dev/python/docs/next/intro#linux. We don't expect users to install Playwright on the unsupported systems.

We tried restricting the installation with your patch, but that broke customers that were on the supported Ubuntu 18 system. We prioritize experience of the customers that are on the supported systems, so the patch was reverted.

Overall, even if we restrict the installation, Centos users won't feel better - what they really want is for Playwright to work. With that, I am closing this issue.

**Comment by kumaraditya303** [comment]
> We tried restricting the installation with your patch, but that broke customers that were on the supported Ubuntu 18 system. We prioritize experience of the customers that are on the supported systems, so the patch was reverted.

It didn't broke because of my patch, it broke because the official docker image for ubuntu 18 mcr.microsoft.com/playwright:bionic uses an outdated pip of version 9 which was released in 2016 https://pypi.org/project/pip/9.0.1/

**Comment by kumaraditya303** [comment]
@pavelfeldman What centos version are you talking about ?
