### ISSUE TITLE
Convert None to null when serializing expression arguments

### ISSUE THREAD

**Issue by iocentos** [microsoft/playwright-python#690]
I've spent a good two full days trying to figure why it was not working. 

We have a custom function attached to the window object that I was trying invoke with a deep dictionary object. While debugging I realized that when the framework serializes expression arguments it converts `None` to `undefined` instead of `null`.

In our case we explicitly check for `null` (inside the browser) and that was the reason it was failing.

I understand that you have both options (`undefined` and `null`) in javascript world while there is only `None` in python world. So I guess you had to choose one or another. My question is if it was the right choice here. 

Also, it is a very subtle issue and it is not documented anywhere. 

Below is the code in question.

https://github.com/microsoft/playwright-python/blob/6854c40ad4bdc8e1fbc8016998fdcf179d7120aa/playwright/_impl/_js_handle.py#L101

**Comment by mxschmitt** [comment]
Sounds good to me, sorry for running into this issue, using `null` there is definitely more idiomatic for Python.
