### ISSUE TITLE
[QUESTION] `BlockingIOError` warnings generated during runtime.

### ISSUE THREAD

**Issue by jean-garret** [microsoft/playwright-python#693]
I am testing a Django app using sync playwright.
However, after some time it generates a lot of `BlockingIOError`
```
BlockingIOError: [Errno 11] Resource temporarily unavailable
Exception ignored when trying to write to the signal wakeup fd:
```

They do not cause the tests to fail but make the output hard to read. Is there anything I can do to avoid them? Please let me know if you need more information!

OS: Ubuntu 18.04
Python: 3.7.5
Playwright: 1.10.0

**Comment by mxschmitt** [comment]
Do you have a stack-trace? Which Playwright functionalities are you using, are you using connect()? I remember such odd behavior on Python3.7/ubuntu18, probably updating to Python 3.8/Ubuntu20 might help.

**Comment by jean-garret** [comment]
Unfortunately I don't have any stack-trace. I am using launch(). 
I will try upgrading Python and Ubuntu, thanks!

**Comment by mxschmitt** [comment]
Closing for now, feel free to reopen if the issue is still persistent or create a new issue with a full reproducible script.

**Comment by jean-garret** [comment]
Sure. 
Thanks for the suggestion, upgrading Unbuntu and python has fixed this issue for me!

**Comment by mxschmitt** [comment]
Awesome, thanks for the update!
