### ISSUE TITLE
Stack trace 'trashes' powershell on Windows 10; also writes over current prompt as well.

### ISSUE THREAD

**Issue by ivarsj10s** [microsoft/playwright-python#696]
Whenever there's an error using playwright-python I get a long hard-to-read stack trace coming from what looks like JavaScript code. However, a bad thing about this this stack trace also writes over the normal terminal and I can't clean it via typing `Ctrl + L` (Powershell and some other applications' default shortcut to clear output). I can only clear this stack trace via typing `cls` which is a bit tedious.

Looks like this:
https://imgur.com/a/W3VDw3k

Can it be fixed?

**Comment by mxschmitt** [comment]
A graceful shutdown needs currently be implemented on the user-land. So you could capture using signals when CTRL + C gets pressed see [here](https://stackoverflow.com/a/1112350/6512681) and then execute `browser.close()`.

**Comment by ivarsj10s** [comment]
Thanks; please leave this as 'triaging' for longer for now. I need more time given to me to practically try out the your adviced workaround solution; I just don't have the timeblock yet. When I reach a timeblock to go through this and through your reply on the other ticket, I'll try them out and comment

**Comment by mxschmitt** [comment]
Closing since the issue seemed stale. Please create a new issue if the issue is still persistent.
