### ISSUE TITLE
Seems like more of an issue with playwright.sync_api._context_manager.py

### ISSUE THREAD

**Issue by YeYuDao** [microsoft/playwright-python#699]
**AttributeError: 'PlaywrightContextManager' object has no attribute '_playwright'**
![image](https://user-images.githubusercontent.com/19714317/118459831-b5b74e80-b72e-11eb-8fdf-6e8ce3e32e5d.png)

**Comment by mxschmitt** [comment]
Seems like you are working on the project and I guess the driver is not installed on your system. See [here](https://github.com/microsoft/playwright-python/blob/master/CONTRIBUTING.md) for the contribution.md: where the local setup is described.

**Comment by YeYuDao** [comment]
Thanks! @mxschmitt
