### ISSUE TITLE
Test coverage plan

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright-python#7]
- [x] browser
- [ ] defaultbrowsercontext wip

---
- [x] cookies
- [x] emulation
- [x] dispatchevent
- [x] headful
- [x] dialog
- [x] focus
- [x] geolocation
- [x] accessibility
- [x] add_init_script
- [x] browsercontext
- [x] check
- [x] click
- [x] console
- [x] download
- [x] element_handle
- [x] evaluate
- [x] fill
- [x] frames
- [x] generation
- [x] ignore_https_errors
- [x] input
- [x] interception
- [x] jshandle
- [x] keyboard
- [x] launcher
- [x] navigation
- [x] network
- [x] page
- [x] pdf
- [x] popup
- [x] queryselector
- [x] worker

**Comment by mxschmitt** [comment]
missing tests:

## inputs.spec.js

- should detect mime type
- should respect timeout
- should respect default timeout when there is no custom timeout
- should prioritize exact timeout over default timeout
- should work with no timeout

reason: timeout needs to be implemented and setRoute too on the mockserver.

**Comment by mxschmitt** [comment]
missing tests:
## downloads.spec.js
- should expose stream -> probably we can ignore it? @pavelfeldman
