### ISSUE TITLE
[Question] About user_data_dir parameters

### ISSUE THREAD

**Issue by intrepidbi** [microsoft/playwright-python#701]
Hi,

I want to ask about user_data_dir parameters from browser_type.launch_persistent_context()
I understand from the documentation, it takes parent directory which translated into \Default.

My question:
is there a way to access the others user profile if I have more than 1 user profile?

I have only 2 user profiles:
profile 1: \Default, ('user_data_dir' : r'%USERPROFILE%\AppData\Local\Chromium\User Data\)
profile 2: \Profile 1 ('user_data_dir' : r'%USERPROFILE%\AppData\Local\Chromium\User Data\Profile 1)

I have tried to access \Profile 1 directly but it doesn't work.

Thanks

**Comment by JoelEinbinder** [comment]
Headless chrome doesn't have multiple user profiles, so this isn't something we support. You would have to manually edit the user data dir to make this work.

Thanks for the question! Closing because this is something we aren't going to add support for.
