### ISSUE TITLE
Support a way to capture playwright debug output logs

### ISSUE THREAD

**Issue by KotlinIsland** [microsoft/playwright-python#706]
Currently playwright starts node as a sub process but doesn't capture its output.

My application be like trying to log the playwright logs but guess what, it can't even see them!

I think something like
```py
sync_playwright().start(stdout=open("stdout", "w"), stderr=open("stderr", "w"))
```

The only way I can think of to get the desired behavior is to make a shim that starts the real python process, captures all of pythons output and filters the playwright debug logs.

**Comment by mxschmitt** [comment]
What kind of logs do you want to log? the `DEBUG=pw:api` e.g.?

There is already a related feature request open for that: #440

**Comment by kumaraditya303** [comment]
You can upvote the upstream feature request https://github.com/microsoft/playwright/issues/6465 :+1:

**Comment by mxschmitt** [comment]
Closing in favor of #440
