### ISSUE TITLE
Powershell command for skipping browser during installation.

### ISSUE THREAD

**Issue by jmrnilsson** [microsoft/playwright-python#712]
On Windows 10, as per documentation, Playwright [allows for opting out](https://playwright.dev/python/docs/installation#skip-browser-downloads) from downloading browsers by Playwright.  The command is pretty straight forward:

    set PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1

The end result it downloads browsers if export command set in Powershell or gets caught in a firewall. But for Powershell this translates to:

    $env:PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
    
Perhaps this should be mentioned or there could be a CLI-argument instead so a user doesn't accidentally install unwanted browser due to language differences between shells. 

```pwsh
 $env:PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
(.venv) > playwright install
Skipping browsers download because `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD` env variable is set
```

**Comment by mxschmitt** [comment]
Seems like we should add such examples for powershell to the docs, thanks for reporting!

@aslushnikov can you confirm that `set` does not work under powershell and if there is there an alternative which works on both terminals?

**Comment by kumaraditya303** [comment]
@mxschmitt `set` only works in cmd not in powershell.
