### ISSUE TITLE
Playwright requiring system packages not installed

### ISSUE THREAD

**Issue by Cybergenik** [microsoft/playwright-python#713]
Hi,

I've tried deploying a few applications so far that use playwright into debian9,10 and centos machines. Particularly Heroku, Digital Ocean Apps, Digital Ocean Droplets. It seems that in every one of those systems pip installing playwright and running the playwright install command doesn't install the required system-level package dependencies. 

Can we change this such whatever install script is run will check that these exist and will download them respectively?

It seems to be the same list of packages every time:

libnss3\
libnspr4\
libatk1.0-0\
libatk-bridge2.0-0\
libdrm2\
libxkbcommon0\
libxcomposite1\
libxdamage1\
libxfixes3\
libxrandr2\
libgbm1\
libasound2\
libatspi2.0-0

Not sure if this is even something that playwright maintainers should necessarily have to worry about, but I've never had issues with a pip installed package that then requires I then apt install something after that. At some point in the chain this should be handled by either pip or playwright install.

PS: Great job, playwright is a godsend!

**Comment by kumaraditya303** [comment]
Playwright officially only supports Ubuntu 18 and 20 and can only installs dependencies for it . WebKit does not work on Debian and there are other issues on Debian too. If you want to run on CentOS and only need chromium and Firefox then I have a docker image which you can use https://github.com/kumaraditya303/playwright-centos/blob/master/Dockerfile. Note this does not work for WebKit.

**Comment by Cybergenik** [comment]
Ok cool, thanks for the Image!
