### ISSUE TITLE
Playwright being detected by antibot just recently 

### ISSUE THREAD

**Issue by smartahsan** [microsoft/playwright-python#724]
Hello,

Previously I was able to login to URL's such as https://www.nike.com/ca/, but recently they have ramped up there BP and playwright is now detectable. They prevent you from logging in via sending a prompt that you were unable to connect to there servers when in fact upon manual login it works completely fine. Im not sure what took place but unfortunately seems as if it is being picked up by the BP.

**Comment by mxschmitt** [comment]
Playwright is a testing library, the focus is not on getting not detected.
