### ISSUE TITLE
[BUG] page.screenshot(full_page=True) crops way too little & loses area

### ISSUE THREAD

**Issue by ivarsj10s** [microsoft/playwright-python#726]
## Preword
Hi, Playwright Python! I have a new bug, a new tech issue; details below:

## The problem
I'm getting way too little "full_screenshot" out of my full screenshot command. Instead of getting the whole "full_screenshot" area I want to have, the command saves both too little height and too little width. The image is unnecessarily cropped too short in both height and width.

#### Source code:
```
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    ctx = p.chromium.launch(headless=False)
    page = ctx.new_page()
    page.goto("https://en.wikipedia.org/wiki/Hundred_Years%27_War")
    page.screenshot(path="scs.png", full_page=True)
    ctx.close()

```

#### Illustrative image:
https://imgur.com/a/F3vocO0

## Secondary questions
1. If it's caused by my system's scale factor, can I offset it some way purely using Python code for Playwright-Python rather than via resetting my scale factor?

## OS / setup / notes
- Windows 10
- I have scale factor 1.5x on my Windows 10 system to accomodate my 4k display

**Comment by ivarsj10s** [comment]
UPDATE:

Setting scale factor to 1x fixes the 'width' issue but height is still cropped short, regardless if I `implicit wait` and `scroll down repeatedly` (and see the bottom in my PlayWright headfull) illustrative image. https://imgur.com/a/wo2sSzM

Note: setting scale factor system wide is an unwanted solution, yet, I just confirm that yes, it impacts and at least induces the width being cropped part of the bug.

**Comment by stanleyrey** [comment]
I used context = browser.newContext(viewport={'width': ####, 'height':####}) to set up the browser and then the screenshot saves full screen as I needed. Maybe it will work for the img saving?

**Comment by x0day** [comment]
same question, use the webkit solve the problem.

**Comment by x0day** [comment]
https://github.com/microsoft/playwright/issues/6188

**Comment by mxschmitt** [comment]
Closing since we track it now upstream https://github.com/microsoft/playwright/issues/6188. Please upvote it there to help us to prioritise it.
