### ISSUE TITLE
[FEATURE] Context managers for page and context 

### ISSUE THREAD

**Issue by kumaraditya303** [microsoft/playwright-python#730]
Currently playwright does not provides context manager for page and contexts and if they are not closed, they will cause resource leak or memory leak, however python has context managers for managing resources which would auto close the resource once they are used. Playwright should have context managers for page and contexts.

TBD API:
```python
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    for browser_type in [p.chromium, p.firefox, p.webkit]:
        with browser_type.launch() as browser:
            with browser.new_page() as page:
                page.goto("http://whatsmyuseragent.org/")
                page.screenshot(path=f"example-{browser_type.name}.png")

```

**Comment by pavelfeldman** [comment]
Sure, we can do that. I remember looking into it and I had difficulties making it work for async.
