### ISSUE TITLE
[FEATURE] Get rid of driver in remote based use to save memory and be cross-platform

### ISSUE THREAD

**Issue by kumaraditya303** [microsoft/playwright-python#732]
Currently in playwright if need to connect to a remote browser even then the driver is run for no real use and uses resources for no use.

Playwright  should provide a cross-platform interface for use within this type of remote browser server based usage, and by this one can run the browser on a remote ubuntu server whereas the clients would run on light alpine containers and hence use less resources.

**Comment by mxschmitt** [comment]
Relates https://github.com/microsoft/playwright/issues/4687

**Comment by pavelfeldman** [comment]
This has some open design challenges, so I would not be doing that.
