### ISSUE TITLE
cannot pickle '_thread.lock' object

### ISSUE THREAD

**Issue by simplPart** [microsoft/playwright-python#735]
based on the [documentation](https://playwright.dev/python/docs/core-concepts#browser),
```
Launching a browser instance can be expensive, and Playwright is designed to maximize what a single instance can do through multiple browser contexts.
```
 I want to make 1 browser and a lot of contexts. using sync and async at the start of the process, it writes an error "cannot pickle '_thread.lock' object". is it possible to start the browser first -> pass it to the process and use it as async in the run function?

**sync_playwright**
```
    playwright = sync_playwright().start()
    browser = playwright.firefox.launch(
        headless=False,
        proxy={
            "server": "per-context"
        }
    )

```
 **or async_playwright** 

```
    async with async_playwright() as p:
        browser = await p.firefox.launch(
            headless=False,
            proxy={
                "server": "per-context"
            }
        )
        return browser
```
```
    process = Process(target=run, args=(arg1, arg2, browser))
    process.start()
```

**Comment by mxschmitt** [comment]
Its not in Python to pass complex data-types which are not pickable as thread arguments. You need to create a new playwright instance in each thread via `sync_playwright().start()` which should work.

**Comment by mxschmitt** [comment]
Closing since this issue is not a Playwright issue.
