### ISSUE TITLE
[Question] How to handle on after clicked browser print button

### ISSUE THREAD

**Issue by leochung042** [microsoft/playwright-python#739]
Hi All

I would like to know how to handle on after clicked browser print button.
My case is the web page has print button, after clicked it would show the browser print view.
I would like to click on "Print" button default it is Print to PDF.

I tried many way (page expect_popup, context expect_page, etc), all failed with timeout 

`
from playwright.sync_api import sync_playwright
import os

with sync_playwright() as p:
    b = p.firefox.launch(headless=False,downloads_path=os.getcwd())
    p = b.new_page(accept_downloads=True)
   p.goto('https://www.google.com/maps/dir/40.4515849,-3.6903752/41.380896,2.1228198/@40.9284811,-5.2705186,6z/am=t/data=!3m1!4b1?hl=en')
	p.click('button[aria-label*="Print"]')
	p.waitForSelector('button[jsaction="pane.action.printWithMaps"]', state='visible')
	p.click('button[jsaction="pane.action.printWithMaps"]')
	p.waitForSelector('button[jsaction="print.print"]', state='visible')
	p.click('button[jsaction="print.print"]')
    with p.expect_popup() as popup_info:
      p.click('button[jsaction="print.print"]')
    popup = popup_info.value
    popup.wait_for_load_state()
	print(popup.title())
`

**Comment by mxschmitt** [comment]
Handling the print dialog is not yet supported, please upvote this feature to support that: https://github.com/microsoft/playwright/issues/6543

**Comment by mxschmitt** [comment]
Closed since we will collect upvotes upstream.

**Comment by leochung042** [comment]
Hi All

For all whose use case like me, then you could do as following.

I have found solution. For my case, after click on print button, then the Browser Print preview shows up.
My case is to save Print preview as PDF file.

Just adding args (--kiosk-printing) when launch browser 

Here is what it does
https://peter.sh/experiments/chromium-command-line-switches/#kiosk-printing

Here is a sample.
b = p.firefox.launch(headless=False,downloads_path=os.getcwd(),args=['--kiosk-printing'])

Btw, the file is not saved in the downloads_path location, instead of my Download directory under home directory.
and also it would save two same files, I have no idea to figure it out.

Thank you,
Leo

**Comment by yuhymuk** [comment]
Why does downloads_path not work? A folder is created according to a new path but a file is saved to the default path
