### ISSUE TITLE
[Question]python script running with error in docker

### ISSUE THREAD

**Issue by jonzha9527** [microsoft/playwright-python#744]
The script running in my local PC is well, but there is error happened when I execute it in container by official docker image.
Is anyone tell me why?

```shell
docker run -it --name pw4 -v D:\gitee\pw_test:/opt mcr.microsoft.com/playwright:focal bash
```

![image](https://user-images.githubusercontent.com/43426348/120986958-b1230a80-c7af-11eb-953d-76f5ec5ac0d4.png)
![image](https://user-images.githubusercontent.com/43426348/120987471-31e20680-c7b0-11eb-8f4f-36e4b1cae87c.png)

**Comment by mxschmitt** [comment]
This seems like the Docker networking is not configured properly for your use-case. The Docker container can't resolve your local hostname. Using `--network="host"` in your docker run parameters should probably fix it.

**Comment by mxschmitt** [comment]
Closing since this is not a Playwright issue.
