### ISSUE TITLE
Playwright expect_* awaits on property 

### ISSUE THREAD

**Issue by kumaraditya303** [microsoft/playwright-python#749]
Consider the code below:
```python
from playwright.async_api import async_playwright

import asyncio


async def main():
    async with async_playwright() as playwright:
        messages = []
        browser = await playwright.chromium.launch()
        page = await browser.new_page()
        page.once("console", lambda m: messages.append(m))
        async with page.expect_console_message() as message_info:
            await page.evaluate('() => console.log("hello", 5, {foo: "bar"})')
        message = await message_info.value
        print(message_info)
        print(messages)
        print(message)


asyncio.run(main())

```

There are multiple issues with the current design of the expect_* context managers :
- Users expect `message_info` to be a object of type ConsoleMessage, but it is not the case
- To access the ConsoleMessage object `message_info.value` is awaited but in the python asyncio awaitables should be methods or functions not property and is very confusing in this case 
- There is no point of having an extra `.value` method nor property as the context manager should directly return the ConsoleMessage

**Comment by pavelfeldman** [comment]
We realize this is not entirely idiomatic, but those were the design choices we made and we can't do anything about it.
