### ISSUE TITLE
 Execute multi-line js expression

### ISSUE THREAD

**Issue by fakerbrother** [microsoft/playwright-python#752]
hi, everyone, could u please tell me how to Execute multi-line js expression, and how to create elements and use them? THX!

**Comment by mxschmitt** [comment]
You can execute multi-line JavaScript like that:

```py
await div.evaluate("""() => {
   console.log("foobar")
}""")
```

inside of that you can call in theory also `document.createElement()` or how do you plan to create elements?

**Comment by fakerbrother** [comment]
> You can execute multi-line JavaScript like that:
> 
> ```python
> await div.evaluate("""() => {
>    console.log("foobar")
> }""")
> ```
> 
> inside of that you can call in theory also `document.createElement()` or how do you plan to create elements?


thanks for your response, I want to download a captcha, my javascript code as follows: 
```
() => {
        const el = document.getElementById('captchaImg');
        const canvas = document.createElement('canvas');
        const ctx = canvas.getContext('2d');
        canvas.width = 160;
        canvas.height = 70;
        ctx.drawImage(el, 0, 0, 160, 70);
        const base64 = canvas.toDataURL();
        const a = document.createElement('a');
        a.download='captcha.png';
        a.href = base64;
        c.click()
}
```
But I can't download this captcha, could u help me, THX!

**Comment by mxschmitt** [comment]
Closed since we are a testing library and don't provide solution to bypass Captchas. If you need to disable it during testing, ask your developer team.
