### ISSUE TITLE
browser locale lang

### ISSUE THREAD

**Issue by merlinjk** [microsoft/playwright-python#754]
Hi , idk why but when i set this : context = browser.new_context(locale='en-GB' ) it won't make my browser in english but if i put other thing like fr-FR,es-ES,de-DE it work but it won't work for all en-*

( im using firefox btw )

**Comment by mxschmitt** [comment]
What do you mean with "my browser in english"? The actual UI of the browser? We try to emulate all the JavaScript/http APIs with the locale emulation.

**Comment by merlinjk** [comment]
like when i set browser context to de-DE and goto :https://accounts.google.com/SignUp?service=mail&continue=https://mail.google.com/mail/?pc=topnav-about-n-en

the page will be in german and it work for a lot of language except en

**Comment by mxschmitt** [comment]
Google does afaik geo location / IP based language detection.

**Comment by merlinjk** [comment]
yes i know but im using Russian ip and when i set locale language to de_DE it set the page in german and for en_GB still Russian
