### ISSUE TITLE
reduce firefox cpu load with arguments

### ISSUE THREAD

**Issue by simplPart** [microsoft/playwright-python#760]
Is it possible to somehow reduce the load on the cpu when starting the browser, context and pages using firefox_user_prefs? is it possible to disable css to disable animation and reduce load? perhaps disabling css will help...

I run a couple of browsers, a lot of contexts and pages and it loads the cores by 100%.
![image](https://user-images.githubusercontent.com/85286382/122401025-e6381580-cf84-11eb-86d7-e60cc444de62.png)

**Comment by mxschmitt** [comment]
Firefox is unfortunately the browser which is the most resource heavy compared to the other browsers. How many pages are you running? Usually one browser per CPU is recommended.

**Comment by simplPart** [comment]
1 browser for 1 cpu. from each cpu I start 5 threads in which 10 contexts and 1 page per context, these pages are in async. using another browser does not suit me( sorry what stupid questions are, I don't really understand what to do, can this MOZ_FORCE_DISABLE_E10S parameter help? https://support.mozilla.org/en-US/questions/1264552#answer-1237084

**Comment by simplPart** [comment]
is it possible to put a [proxy on the page](https://github.com/gajus/puppeteer-proxy#usage) like puppeteer was, to use one context and many pages with their proxies? maybe it will at least slightly reduce the load

**Comment by mxschmitt** [comment]
Sorry I meant pages, since browser rendering engines are quite CPU heavy, one page per CPU is recommended.

`MOZ_FORCE_DISABLE_E10S` is an environment variable, you can set it when launching the browser, see [here](https://playwright.dev/python/docs/next/api/class-browsertype#browser-type-launch-option-env). Or you can set it already before in your execution workflow, since it inherits it from the parent process.

A proxy per page is not possible, only on context level.

**Comment by simplPart** [comment]
by the way, there is no way to turn off rendering engines? just to load a blank page with text, can this help reduce the load?

**Comment by mxschmitt** [comment]
For what are you using Playwright? I'm curious to understand more the use-case of it. Since this sounds not like a typical end-to-end testing use-case.

**Comment by simplPart** [comment]
maybe I misunderstood what a rendering engine is. 

the customer ordered testing for the availability of the site from different sources, in a large batch. we are ordinary freelancers, and we were asked to check the site for simultaneous connection of users,  kinda stress test. + we do not use selectors, we use ready-made cookies from developers.

P.S .: we do not use DDoS or anything related to this (if you could think about it), this is outside the scope of our rules.

**Comment by pavelfeldman** [comment]
> 1 browser for 1 cpu. from each cpu I start 5 threads in which 10 contexts and 1 page per context

This is a fine setup, but don't start threads. Use asyncio, 1 browser per cpu, open several contexts in each. Everything should be on one thread.

Puppeteer can't do proxy per page, it can shim it. But luckily, Playwright can. When you create context, you can specify proxy config.

To reduce the load, you can set a small screen size. 1px x 1px. That would being layout and rasterization costs to minimum.

**Comment by simplPart** [comment]
thanks, we will try🙌😉

**Comment by mxschmitt** [comment]
Closed since this issue seems solved. In general Chromium / WebKit should be less resource heavy.
