### ISSUE TITLE
Context Manager for tracing API 

### ISSUE THREAD

**Issue by kumaraditya303** [microsoft/playwright-python#763]
Context Manager for tracing API would be much convenient:

TBD API:

```python
browser = chromium.launch()
context = browser.new_context()
with context.trace(screenshots=True, snapshots=True, path="trace.zip"):
    page.goto("https://playwright.dev")

```

/cc: @pavelfeldman @mxschmitt

**Comment by pavelfeldman** [comment]
Yeah, but that'll fork our api and confuse the docs

**Comment by kumaraditya303** [comment]
@pavelfeldman  What do you mean by fork our api and confuse the docs ?

We should have the API which is most familiar to python users, context managers are the way to go when a stop or close  call is needed afterwards, Also we could in docs illustrate the use with some examples
