### ISSUE TITLE
[BUG] Playwright should run blocking call in threadpool

### ISSUE THREAD

**Issue by kumaraditya303** [microsoft/playwright-python#767]
In Python Asyncio, blocking call should not be called from an async func as it will block the event loop, hence the solution is to run the blocking call in a thread pool. 

https://github.com/microsoft/playwright-python/blob/e05ab0732cbb330892a1cb8a79dd3292a12c2106/playwright/_impl/_stream.py#L28-L34

**Comment by pavelfeldman** [comment]
What do you call asyncio blocking call? Afaik fole i/o in Python is not through asyncio.

**Comment by kumaraditya303** [comment]
I meant that file.write call is blocking the event loop

**Comment by pavelfeldman** [comment]
Makes sense. Something like aiofiles?
