### ISSUE TITLE
[FEATURE] Method for detection, that element is not visible anymore

### ISSUE THREAD

**Issue by akozyreva** [microsoft/playwright-python#774]
Hi!
I faced an issue, when I need to detect that element was completely removed from DOM after the clicking. I implemented in my project something like:
```
def is_element_not_visible_anymore(self, locator, timeout: int = 15):
        is_el_disappeared = False
        actual_timeout_for_disappear = 0
        for _ in range(timeout * 2):
            is_el_visible = self.is_element_visible(locator, timeout=0.5, throw_err=False)
            if is_el_visible:
                actual_timeout_for_disappear += 0.5
                self.sleep(0.5)
            else:
                is_el_disappeared = True
                break
        assert is_el_disappeared is True, \
            f"Expected that element with locator {locator} disappeared on page, but actually is not!"
        print(f"Element finally disappeared within {actual_timeout_for_disappear} secs")
```
Do we have something already in library?

**Comment by mxschmitt** [comment]
Yes, you can use `page.wait_for_selector("#foo", state="hidden")`. See [here](https://playwright.dev/python/docs/api/class-page#page-wait-for-selector) for reference.

This will directly resolve if the element is not on the DOM and if its there it will wait until its detached or not visible anymore.

**Comment by akozyreva** [comment]
Hi @mxschmitt !
Thanks, you are right.
