### ISSUE TITLE
[question] how to do visual comparisons

### ISSUE THREAD

**Issue by TommyXie1990** [microsoft/playwright-python#775]
how to do visual comparisons with playwright-python with python version?

what's the api? I just found the Javascripts version.

**Comment by aslushnikov** [comment]
We don't ship anything specific in playwright-python for this, you'll have to resort to third-party solutions.

**Comment by TommyXie1990** [comment]
> specific
I found the api in the offical doc, it seems like for javascript;  If I want use it with python,  could you suggest some solutions? thanks~
https://playwright.dev/python/docs/test-snapshots/

**Comment by kumaraditya303** [comment]
@TommyXie1990 Do you mean something like https://github.com/microsoft/playwright-pytest/issues/63?

**Comment by TommyXie1990** [comment]
> @TommyXie1990 Do you mean something like [microsoft/playwright-pytest#63](https://github.com/microsoft/playwright-pytest/issues/63)?

yes , that's what I mean. Thanks ~

**Comment by TommyXie1990** [comment]
> @TommyXie1990 Do you mean something like [microsoft/playwright-pytest#63](https://github.com/microsoft/playwright-pytest/issues/63)?

is it suport now? could you provide some samples that how to use it, thanks~

**Comment by kumaraditya303** [comment]
> > @TommyXie1990 Do you mean something like [microsoft/playwright-pytest#63](https://github.com/microsoft/playwright-pytest/issues/63)?
> 
> is it suport now? could you provide some samples that how to use it, thanks~

I will be creating a pytest plugin for it, stay tuned

**Comment by TommyXie1990** [comment]
> > > @TommyXie1990 Do you mean something like [microsoft/playwright-pytest#63](https://github.com/microsoft/playwright-pytest/issues/63)?
> > 
> > 
> > is it suport now? could you provide some samples that how to use it, thanks~
> 
> I will be creating a pytest plugin for it, stay tuned

ok, look forward to it,   when will be available?

**Comment by kumaraditya303** [comment]
Possibly today

**Comment by TommyXie1990** [comment]
> Possibly today

fantastic~

**Comment by kumaraditya303** [comment]
> > Possibly today
> 
> fantastic~

@TommyXie1990 I have pushed the code to github with an example, would be great if you could give it a try https://github.com/kumaraditya303/pytest-playwright-snapshot

**Comment by TommyXie1990** [comment]
> > > Possibly today
> > 
> > 
> > fantastic~
> 
> @TommyXie1990 I have pushed the code to github with an example, would be great if you could give it a try https://github.com/kumaraditya303/pytest-playwright-snapshot

I have try it in my project; it works fine.   I have a new requirement that Is it possible to add a parameter, such as a percentage, to support contrast deviation when comparing images。 Thanks~
