### ISSUE TITLE
[DOCUMENTATION] example code of CDPSession is not correct

### ISSUE THREAD

**Issue by YusukeIwaki** [microsoft/playwright-python#776]
**Context:**

- Playwright Version: 1.12.0
- Operating System: macOS
- Python Version: 3.9

**Code Snippet**

An example code in playwright.dev doesn't work well.
![image](https://user-images.githubusercontent.com/11763113/123367469-f10e2e00-d5b4-11eb-9ce9-60a93aab0d44.png)

I tried the code below to work with CDPsession.

```python
        client = page.context.new_cdp_session(page)
        client.send("Animation.enable")
        client.on("Animation.animationCreated", lambda: print("animation created!"))
        response = client.send("Animation.getPlaybackRate")
        print(f'playback rate is {response["playbackRate"]}')
        client.send("Animation.setPlaybackRate", {
            'playbackRate': response["playbackRate"] / 2
        })
```

**Comment by YusukeIwaki** [comment]
Also I have a question. 
https://github.com/microsoft/playwright-python/blob/master/playwright/_impl/_cdp_session.py

This implementation have `parse_result(params["params"])` and `parse_result(result)`

I understand the method `parse_result` is for deserializing the result of evaluateExpression in JSHandle/ElementHandle, as TypeScript version of CDPSession don't have `parseResult` https://github.com/microsoft/playwright/blob/master/src/client/cdpSession.ts
It would have no effect on the result of CDPSession#send...

**Comment by pavelfeldman** [comment]
Yes and yes, there is a bug in the docs and in the code. Let me fix it. You are obviously the first CDP customer in python version.

**Comment by YusukeIwaki** [comment]
@pavelfeldman Thank you for the quick fix. 

I checked https://github.com/microsoft/playwright/pull/7324 and some fixes are required. Sorry for my insufficient report.
