### ISSUE TITLE
[FEATURE] Generate Event based overloads for event listeners

### ISSUE THREAD

**Issue by kumaraditya303** [microsoft/playwright-python#786]
Like in the ts playwright, playwright generates event based overloads for the methods, the same in the python is possible with `@overload` and would help in type checking and also provide excellent autocompletions , @mxschmitt Already agree with the  proposal.

/cc : @pavelfeldman 

<img width="486" alt="Screenshot (84)" src="https://user-images.githubusercontent.com/59607654/124219358-dc341c00-db19-11eb-92b1-ef34dd3fdaa1.png">

**Comment by pavelfeldman** [comment]
Sounds good to me
