### ISSUE TITLE
[API] Improve typings and reduce runtime casts 

### ISSUE THREAD

**Issue by kumaraditya303** [microsoft/playwright-python#788]
There are multiple occurrences of runtime casts which does not has any real benefit hence we should keep them at minimal. Currently `page.on` accepts `Any` but should be a Callable needs to be fixed.

**Comment by pavelfeldman** [comment]
I did not know there was a difference between `foo: Foo = bar()` and `foo = cast(Foo, bar())` in Python. Could you elaborate why one is better than the other?

**Comment by kumaraditya303** [comment]
`foo: Foo = bar()` will error out if type of bar is not a match of Foo where as `foo = cast(Foo, bar())` is forcing the type checker in interpret the result of `bar()` as Foo without doing any check, the first one is better as it avoids an extra function call and also not force the type checker to cast it at runtime.

**Comment by pavelfeldman** [comment]
Are you sure this is the case? I tried it locally and there was no difference.

**Comment by kumaraditya303** [comment]
Try this :
```python 
# main.py
from typing import cast

a: int = "string"
b = cast(int, "string")
```

```console
mypy main.py
```

**Comment by pavelfeldman** [comment]
I was trying the following real world scenario:

```py
transport: PipeTransport = WebSocketTransport(loop, "")
```

mypy was happy with it. It looks like it only handles this trivial use case.

In either case, this is a good enough justification to make this change. It does not give us much due to the bug above, but it declares the intent well.

**Comment by kumaraditya303** [comment]
```python 
transport: PipeTransport = WebSocketTransport(loop, "")
```
mypy will be happy as both PipeTransport  and WebSocketTransport inherit from the same abc class and mypy has special handling for that.

**Comment by pavelfeldman** [comment]
> mypy will be happy as both PipeTransport and WebSocketTransport inherit from the same abc class and mypy has special handling for that.

This would not make sense though, can you point to a doc that would explain that? Those are not assignable to each other and common base class should not matter here. Type checker should complain.

In fact, when I try:
```py
class A(Base):
    pass


class B(Base):
    pass

a: A = B()
print(a)
```

It rightfully complaints.

**Comment by pavelfeldman** [comment]
It does not look like ABC has anything to do with it either (which makes sense):

```py
class Transport(ABC):
    @abstractmethod
    def foo(self) -> None:
        pass


class A(Transport):
    def foo(self) -> None:
        pass


class B(Transport):
    def foo(self) -> None:
        pass


a: A = B()
print(a)
```

**Comment by kumaraditya303** [comment]
It was a wrong explanation

**Comment by kumaraditya303** [comment]
> I was trying the following real world scenario:
> 
> ```python
> transport: PipeTransport = WebSocketTransport(loop, "")
> ```
> 
> mypy was happy with it. It looks like it only handles this trivial use case.
> 
> In either case, this is a good enough justification to make this change. It does not give us much due to the bug above, but it declares the intent well.

@pavelfeldman The previous explanation was wrong, here mypy is happy because `WebSocketTransport` is inheriting from `AsyncIOEventEmitter` which has no type stubs hence it is `Any` hence it does not complains there because you can assign Any to anything as long as it has same attributes
