### ISSUE TITLE
[Question]: how to recorded head?

### ISSUE THREAD

**Issue by Bingo-Li** [microsoft/playwright-python#797]
### Your question

Sometimes authorization we hard to get, so sometimes need record with headed mode. So playwright support it or not？Thanks！

**Comment by mxschmitt** [comment]
When launching the browser, you can specify `headless=False` which starts the browser in headed/headful.

See here: https://playwright.dev/python/docs/next/api/class-browsertype#browser-type-launch-option-headless

**Comment by Bingo-Li** [comment]
@mxschmitt ,sorry, here  I just want to know how to recorded with log in status. But when I recorded it, it always no trace mode.

**Comment by mxschmitt** [comment]
Sorry I don't know what you mean. What do you mean with trace mode? Are you trying to record the traces? The best would be if you could provide us some code to show us what is not working.

**Comment by mxschmitt** [comment]
Closing as part of the triage process, please create a new issue or reopen if you still face an issue.
