### ISSUE TITLE
Audit Playwright stdio

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright-python#8]
We currently use stdout/stdin for the transport Pipes. Make sure Playwright keeps them silent and does not do `console.err` or `process.stderr` writes in the server mode.

**Comment by mxschmitt** [comment]
I saw a few times already that this case has occurred and was logged to stdout while installing the browsers.

https://github.com/microsoft/playwright/blob/5c4751d5dd7c28804e5d9d76a1cceb7c36521749/src/install/installer.ts#L57-L58

**Comment by pavelfeldman** [comment]
Fixed, upstream tests are making sure it works
