### ISSUE TITLE
[Question]: Better explanation of page.on("load") etc.

### ISSUE THREAD

**Issue by niewiemczego** [microsoft/playwright-python#806]
### Your question

Hello, Could someone explain me better of the use of the function page.on("load"),page.on("close"),page.on("crash") etc...
I have looked into docs/api but only `page.once("load", lambda: print("page loaded!"))` example was clear to me.
I am thinking about catching errors in more detail, where the app will detect whether the browser got a crash was closed or whether it correctly loaded the page. 
So in example when the app crashed then it will return False or break the loop so the other function wont get called/browser wont get futher into written code.

**Comment by mxschmitt** [comment]
Hi, what is exactly not clear for you?

We have a dedicated page about event handlers in Python, see here: https://playwright.dev/python/docs/events

Usually the browser should never crash, it's more like when OOM (out of memory) errors happen or when there is a direct crash in the browser internals.

**Comment by niewiemczego** [comment]
hmm... okay but how can I return False or break the loop so the other function wont get called/browser wont get futher into written code? e.g in page.on('close') or How can I handle different exceptions cuz as I can see there are only TimeoutError and Error Exceptions available

**Comment by mxschmitt** [comment]
I don't know how your code looks like, it's different based on if you are using sync or async. So you want to stop the execution when a page is closing?

**Comment by niewiemczego** [comment]
Yes, Im using async and here's just a simple code on which Im trying to make it 

```
import asyncio
from playwright.async_api import async_playwright

async def run(playwright):
    browser = await playwright.firefox.launch(headless=False)
    page = await browser.new_page()

    async def page_on_close():
        return False

    async def goto_page():
        print("Loading page...")
        if page.once("close", page_on_close):
            print('close event')
        await page.goto(f"https://google.com")
        await page.wait_for_load_state()
        await asyncio.sleep(5)
        return True

    if await goto_page():
        print('Done')
        await browser.close()
    else:
        print('error1')

async def main():
    async with async_playwright() as playwright:
        await run(playwright)
asyncio.run(main())
```

**Comment by mxschmitt** [comment]
I'm curious about the problem you are trying to solve, since normally a page should not close itself. Are you using it for scraping?

There are multiple ways of solving that, either you can write e.g. closed into a variable when you receive the close event or you can leverage asyncio.Future/asyncio.Event. But if you are using it to scrape sites or visit multiple sites, I would recommend creating a new context and page for each for each site to ensure that they are isolated from each-other and fresh.
