### ISSUE TITLE
Question: I don't understand the Keyword Arguments to load Edge browser 

### ISSUE THREAD

**Issue by pvd-dev** [microsoft/playwright-python#808]
I'm attempting to launch a chromium/edge browser for testing in python. In order to spin up the browser I use: 
` 
browser = playwright.chromium.launch(headless=False, slow_mo=slowdown, executable_path= pathtoedge)
`
This works for all other types (Firefox/webkit/Chromium). 

I understand that for Edge to work I need to tell my script where to find the Edge executable (https://playwright.dev/python/docs/api/class-browsertype#browser-type-executable-path ) 

I'm using a Macbook and installed Edge locally so I believe that the pathtoedge variable should be something along the lines of: 
`
pathtoedge = '/../../../../Applications/Microsoft Edge.app/contents/MacOS/Microsoft\ Edge'
`

I'm on my MacBook and in a folder on my desktop, so 4 layers up in my filesystem, and then down to the contents of the Edge package to the executable. 

Anyway, maybe I have tried to long to understand relative file paths, or maybe I'm parsing the arguments wrong. But I will need some help.

**Comment by mxschmitt** [comment]
Playwright has a feature called `channels` which automatically will find the correct executable path from your operating system. See here: https://playwright.dev/python/docs/browsers/#google-chrome--microsoft-edge

In your case you just need to add `channel="msedge"` when launching the browser.

**Comment by pvd-dev** [comment]
Thanks @mxschmitt, I believe that is what I tried before opening the issue. But I'm probably still not doing it right then: 
This is the piece of my code where I open the browser: 
```
browser = playwright.chromium.launch(headless=False, slow_mo=slowdown, channel="msedge")
```
Running that will give me the following error: 
```
TypeError: launch() got an unexpected keyword argument 'channel'
```

**Comment by mxschmitt** [comment]
Which version of Playwright are you using?

**Comment by pvd-dev** [comment]
Version 1.12.2-1623435892000, trough Conda
Installed on MacOS, with latest version of ms Edge

**Comment by mxschmitt** [comment]
Weird, maybe you have an old installation which gets used? I tried to use it and it works for me.

What does this give you?

```
from playwright._repo_version import version
print(version)
```

**Comment by pvd-dev** [comment]
Very strange, It gives me an older version in my IDE, but when running the script straight from the Terminal it gives me the latest version. When running from the Terminal, Edge does work. 

So what I think is that I have some strange mismatch of python versions/packages. I'll look into that myself. Thanks for the help though. Great to confirm I wrote the correct function.
