### ISSUE TITLE
How to get the image, image attributes (size and other information), how to operate the rotation map?  

### ISSUE THREAD

**Issue by 000xiaoxiao000** [microsoft/playwright-python#809]
### Your question

html code: `<img src="/img/xxx.jpg" class="xx" style="xxx">`

How to get the image, image attributes (size and other information), how to operate the rotation map?

**Comment by mxschmitt** [comment]
Are you interested in the width/height of the actual image or the size how big it is being displayed? and in what kind of other information/attributes are you interested?

Probably the best would be to do something like this:

```py
from playwright.sync_api import sync_playwright, Response

with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()
    def handle_response(response: Response):
        if response.request.resource_type != "image":
            return
        image = response.body()
        print(len(image)) # use some library to analyse your image, e.g. EXIF information
    page.on("response", handle_response)
    page.goto('https://microsoft.com')
    browser.close()
```

**Comment by 000xiaoxiao000** [comment]
How do I know the interval between the rotations?

**Comment by mxschmitt** [comment]
What do you mean with that?

**Comment by 000xiaoxiao000** [comment]
> What do you mean with that?

Carousel map on the page, How do I get the interval time?

**Comment by mxschmitt** [comment]
Depends on your application, what are you trying to do and what is the testing use-case for it?

**Comment by 000xiaoxiao000** [comment]
> Depends on your application, what are you trying to do and what is the testing use-case for it?

How long does it take to switch between images?

**Comment by mxschmitt** [comment]
Closing since this is not about Playwright and more about the application which you are testing or scraping against.
