### ISSUE TITLE
[Question]: Playwright with pyinstaller

### ISSUE THREAD

**Issue by dennis8989** [microsoft/playwright-python#811]
### Your question

I follow issue #342 to set up my environment.
The .exe file went will on my computer,
but when I ran the .exe file on pure OS(win10 without python).
It shows  

**"chromium" browser was not found.
Please complete Playwright installation via running
"python -, playwright install"**

How can I fix it?
Thanks

**Comment by mxschmitt** [comment]
You need to execute the CLI command. I will fold it into #513 since this is the tracking issue for providing support for Pyinstaller.
