### ISSUE TITLE
[Question]: MaxListenersExceededWarning

### ISSUE THREAD

**Issue by dennis8989** [microsoft/playwright-python#813]
### Your question

I built a .exe file by pyinstaller.
I ran it on a pure OS win10, but sometimes its shows
MaxListenersExceededWarning: Possible EventEmitter memory leak detected....Use emitter.setMaxListeners() to increase limit
How do I fix this issue? or how to increase maxlisteners limit?
Thanks.

**Comment by mxschmitt** [comment]
How does your script look which which you execute?

**Comment by dennis8989** [comment]
no problem when I execute script directly

**Comment by dennis8989** [comment]
I found this issue came from download.save_as()
If I don't use this function, the warning won't happen.
Maybe this function needs lots of memory .

**Comment by mxschmitt** [comment]
I tried to reproduce with the following but was not able, how big is your file and what functionality of Playwright are using using which might relate to it?

```py
from os import access
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    for browser_type in [p.chromium]:
        browser = browser_type.launch()
        page = browser.new_page(accept_downloads=True)
        page.goto('https://speed.hetzner.de/')
        with page.expect_download() as download_info:
            page.click("text=100MB.bin")
        download = download_info.value
        download.save_as("100MB.bin.download")
        browser.close()
```

**Comment by kumaraditya303** [comment]
Minimal reproducer:

```python
import asyncio

from playwright.async_api import Playwright, async_playwright


async def run(playwright: Playwright):
    browser = await playwright.chromium.launch(headless=False)
    context = await browser.new_context(accept_downloads=True)

    # Open new page
    page = await context.new_page()

    # Go to https://speed.hetzner.de/
    await page.goto("https://speed.hetzner.de/")

    # Click text=1GB.bin
    async with page.expect_download() as download_info:
        await page.click("text=1GB.bin")
    download = await download_info.value
    t1 = asyncio.create_task(download.save_as(path="1GB.bin"))
    t2 = asyncio.create_task(download.save_as(path="1GB1.bin"))
    t3 = asyncio.create_task(download.save_as(path="1GB2.bin"))
    t4 = asyncio.create_task(download.save_as(path="1GB3.bin"))
    await asyncio.sleep(10)
    await asyncio.gather(t1, t2, t3, t4)
    # Close page
    await page.close()

    # ---------------------
    await context.close()
    await browser.close()


async def main():
    async with async_playwright() as playwright:
        await run(playwright)


asyncio.run(main())

```

**Comment by kumaraditya303** [comment]
Minimal reproducer:

Create a 1GB file:
```sh
truncate -s 1G test.bin
```

Start local server:
```sh
python -m http.server
```

Script:

```python
import asyncio

from playwright.async_api import Playwright, async_playwright


async def run(playwright: Playwright):
    browser = await playwright.chromium.launch(headless=False)
    context = await browser.new_context(accept_downloads=True)

    page = await context.new_page()

    await page.goto("http://localhost:8000/")

    async with page.expect_download() as download_info:
        await page.click("text=test.bin")

    download = await download_info.value

    task = asyncio.create_task(download.save_as(path="1GB.bin"))
    await asyncio.sleep(10)
    await task
    await page.close()

    await context.close()
    await browser.close()


async def main():
    async with async_playwright() as playwright:
        await run(playwright)


asyncio.run(main())

```

**Comment by dennis8989** [comment]
I try to don

> Minimal reproducer:
> 
> Create a 1GB file:
> 
> ```shell
> truncate -s 1G test.bin
> ```
> 
> Start local server:
> 
> ```shell
> python -m http.server
> ```
> 
> Script:
> 
> ```python
> import asyncio
> 
> from playwright.async_api import Playwright, async_playwright
> 
> 
> async def run(playwright: Playwright):
>     browser = await playwright.chromium.launch(headless=False)
>     context = await browser.new_context(accept_downloads=True)
> 
>     page = await context.new_page()
> 
>     await page.goto("http://localhost:8000/")
> 
>     async with page.expect_download() as download_info:
>         await page.click("text=test.bin")
> 
>     download = await download_info.value
> 
>     task = asyncio.create_task(download.save_as(path="1GB.bin"))
>     await asyncio.sleep(10)
>     await task
>     await page.close()
> 
>     await context.close()
>     await browser.close()
> 
> 
> async def main():
>     async with async_playwright() as playwright:
>         await run(playwright)
> 
> 
> asyncio.run(main())
> ```

I tried your script, it work well.
but when I download big size(more than 500 MB) from web, the issue happens again.
The issue is easy to copy on my old laptop(3rd Intel CPU with 8 GB memory)
But never seen the issue on my new laptop(9th Intel CPU with 16GB memory)

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.
