### ISSUE TITLE
[Bug]: playwright._impl._api_types.Error: net::ERR_CONNECTION_RESET on ubuntu chromium on GitHub

### ISSUE THREAD

**Issue by ddmee** [microsoft/playwright-python#815]
### Playwright version

1.121

### Operating system

Linux

### What browsers are you seeing the problem on?

Chromium

### Other information

- python 3.9
- ubuntu 20.04.2

Issue only occurs when running on GitHub Actions, does not occur locally (though my desktop is Mac osx rather than linux).

### What happened? / Describe the bug

You can see the bug here: https://github.com/ddmee/playwright_problem/runs/3113778059?check_suite_focus=true

I've created an example git repo that runs a GitHub action that hits the bug. The bug occurs when I run  playwright via it's pytest plugin. The bug only seems to occur when I run the tests via GitHub Actions. I think chromium is crashing when playwright interacts with it.

I've created the code in the repository that reproduces the problem https://github.com/ddmee/playwright_problem 

The issue I'm having is that though the tests pass on my local development machine, when I run the tests on GitHub actions, playwright/chromium crashes. Specially, there is a ERR_CONNECTION_RESET error thrown:

```python
self = <playwright._impl._connection.Channel object at 0x7f77bd2c4a30>
method = 'goto', params = {'url': 'http://localhost:4040/'}
return_as_dict = False

    async def inner_send(
        self, method: str, params: Optional[Dict], return_as_dict: bool
    ) -> Any:
        if params is None:
            params = {}
        callback = self._connection._send_message_to_server(self._guid, method, params)
    
        done, pending = await asyncio.wait(
            {self._connection._transport.on_error_future, callback.future},
            return_when=asyncio.FIRST_COMPLETED,
        )
        if not callback.future.done():
            callback.future.cancel()
>       result = next(iter(done)).result()
E       playwright._impl._api_types.Error: net::ERR_CONNECTION_RESET at http://localhost:4040/
E       =========================== logs ===========================
E       navigating to "http://localhost:4040/", waiting until "load"
E       ============================================================
E       Note: use DEBUG=pw:api environment variable to capture Playwright logs.
```

Though the bug seems to be flakey, sometimes the bug isn't hit https://github.com/ddmee/playwright_problem/runs/3114039814?check_suite_focus=true

### Code snippet to reproduce your bug

```shell
See https://github.com/ddmee/playwright_problem/actions/runs/1048779670
```

**Comment by mxschmitt** [comment]
I think that has nothing to do with the pytest plugin. `ERR_CONNECTION_RESET` means that the connection to the web-server can't get established. The error comes up because the web-server is not yet available. There are multiple ways of fixing that, you can either wait for X seconds after you start the web-server, but I would not recommend that. It's better to use "something" to wait until your web-server is available. In the past I always used the wait-on package and it worked for me, but you can also build something more lightweight using e.g. curl and a loop.

`npx wait-on http://localhost:4040`

ref: https://www.npmjs.com/package/wait-on

**Comment by ddmee** [comment]
Doh! I don't know why I didn't think of that. Thanks for looking at it. Yes that looks exactly like the issue.

I added a wait as a fixture in pytest and that seems to have stopped the issue.  https://github.com/ddmee/playwright_problem/blob/master/tests/conftest.py#L13-L17

Which is this:

```python
@pytest.fixture(scope='session', autouse=True)
def wait_on_server():
    """Server may not be available at first. Wait on it before running tests"""
    polling2.poll(target=lambda: requests.get(server_url()).status_code == 200,
                  step=1, timeout=30, ignore_exceptions=(requests.exceptions.ConnectionError,))
```

Hmm yeah I don't think there's any API change you could make that would cushion someone else hitting the error. It sounds more like my own stupidity/not spotting the race condition.

Think that's the issue closed. Thanks a lot for your help.
