### ISSUE TITLE
[Bug]: page.frame(url=foo) regular expression matching only works with compiled patterns 

### ISSUE THREAD

**Issue by jnns** [microsoft/playwright-python#816]
### Playwright version

1.12.0

### Operating system

Linux

### What browsers are you seeing the problem on?

Firefox

### Other information

Python 3.9.5 on Ubuntu 21.04

### What happened? / Describe the bug

[According to the docs](https://playwright.dev/python/docs/api/class-page/#page-frame), a frame should be retrieved with a regular expression pattern but it doesn't work. 

```python
>>> page.frame(url=r".*stripe.com.*") 
None
```

Glob strings work as documented, but regular expressions need to be compiled first:

```python
>>> page.frame(url="*stripe.com*") 
<Frame url='https://js.stripe.com/[...]'>
>>> page.frame(url=re.compile(".*stripe.com.*")) 
<Frame url='https://js.stripe.com/[...]'>
```

Here's the code example straight from the docs:

> ```python
> frame = page.frame(url=r".*domain.*")
> ```

**Comment by mxschmitt** [comment]
We link in the docs that a `re.Pattern` instance is required, for strings we treat them as globs. When you are using `r".*domain.*"` it internally is still a string in Python, so not possible to detect there a regexp without breaking either the same behaviour across the languages nor the glob support.

![image](https://user-images.githubusercontent.com/17984549/126983428-b8d7bde6-77e2-464e-a0c1-c64a7cc4c2fd.png)

**Comment by jnns** [comment]
> We link in the docs that a re.Pattern instance is required, for strings we treat them as globs.

That's true. But don't you agree that the example shown (`r".*domain.*"`) is a bit misleading as it implies that a simple string containing a regular expression will be compiled and used as such whereas it will just be used as a glob? And due to the dot it will probably not work correctly.

I think replacing that example with the usage of a compiled pattern will be enough. No implementation change needed.

**Comment by dwiyatci** [comment]
@jnns Thanks so much for this enlightenment. I'm pretty new to Playwright (and Python), and would have not known that the regex has to be compiled first if it weren't for this issue. Even worse, reading the example in the docs, since I'm also new to Python, I thought `r` in `r".*domain.*"` represents a regex literal in Python. 😂
