### ISSUE TITLE
[Question]: Further explanation of launching Context based Browser Instances

### ISSUE THREAD

**Issue by jorgegarcia197** [microsoft/playwright-python#817]
### Your question

I am currently building a cloud service that launches a Playwright Instance and does some web-scraping tasks that are given, but due to the fact that the cloud service is based in the US, the web scraping scripts being sent are basically useless because of the geolocation and differences between the webpages. 

My solution was to launch a Context based Instance but I can not manage to make it work. 
This is my current snippet on how I am creating the session:

![image](https://user-images.githubusercontent.com/46676143/126549632-4dbecf7d-629d-4158-ad4d-c0eb34aa19b4.png)

And the declaration of setUpBrowserContext is the following:
![image](https://user-images.githubusercontent.com/46676143/126549787-71a85fd3-a16d-43f1-a827-eb0ae2eebb98.png)

I've already tried both, by creating a new_context with arguments and also by the setter functions built-in within the BrowserContext class. 

Hope you can help me out and thanks in advance.

**Comment by mxschmitt** [comment]
This is probably something where a VPN or proxy is required to change your IP (they do probably IP -> geolocation resolution). I'm closing this issue, since this is about scraping and Playwright is focusing on end-to-end testing.
