### ISSUE TITLE
[Bug]: `future: <Future finished exception=Error('Unknown scheme for Frame.waitForEventInfo')>` after upgrading to 1.13.0

### ISSUE THREAD

**Issue by carlosperezm** [microsoft/playwright-python#820]
### Playwright version

1.13.0

### Operating system

Windows

### What browsers are you seeing the problem on?

Firefox

### Other information

Python 3.9.5

### What happened? / Describe the bug

Before upgrading from 1.12.1 to 1.13.0, I did not get any error.

Now the following error appears.
`future: <Future finished exception=Error('Unknown scheme for Frame.waitForEventInfo')>
 playwright._impl._api_types.Error: Unknown scheme for Frame.waitForEventInfo`

It seems that the responsible command is `await page.wait_for_load_state("networkidle")` before a page loads when you click on a button.

### Code snippet to reproduce your bug

```shell
async def minimal_test():
    async with async_playwright() as p:
        browser = await p.firefox.launch(headless=False,)
        page = await browser.new_page()
        await page.goto("https://www.google.com/")
        await page.click("#gbqfbb")
        await page.wait_for_load_state("networkidle")
        await browser.close()
```

**Comment by rai-gaurav** [comment]
Today morning I also upgrade to 1.13.0 and found a lot of similar errors in logs.
I spent quite a time thinking that I have messed up something before finding this issue :P

**Comment by mxschmitt** [comment]
Closing since cherry-picked to v1.13 branch where we will issue 1.13.1 tomorrowish.
