### ISSUE TITLE
[Question]: unable to catch the TimeoutError of page.goto()

### ISSUE THREAD

**Issue by ntcmp2u** [microsoft/playwright-python#831]
### Your question

I use ``try...except`` code block to detect if ``page.goto`` throws timeout error. The code is like this

```python
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.webkit.launch(headless=False)
    page = browser.new_page()
    try:
        page.goto("https://google.com", timeout=1000)
        print(page.title())
    except TimeoutError as e:
        print(f"catch the error: {e}")
    browser.close()
```

But it still raises error. What error type does it throws? I also wonder if there is a document detail Playwright's all kinds of error type.

**Comment by mxschmitt** [comment]
You need to use the Playwright's Timeout error instead: `from playwright.sync_api import sync_playwright, TimeoutError`

**Comment by kumaraditya303** [comment]
I better solution is to not override the builtin `TimeoutError` instead alias the playwright error as `from playwright.sync_api import sync_playwright, TimeoutError as PlaywrightTimeoutError` and then catch it as `PlaywrightTimeoutError` this way you can even use the builtin one

**Comment by ntcmp2u** [comment]
thanks!
