### ISSUE TITLE
[Question]: Is it possible for us to intercept network requests and then operate them?

### ISSUE THREAD

**Issue by fengnex** [microsoft/playwright-python#834]
### Your question

As mentioned in the above topic, we can record all backend urls and corresponding parameters if we can do that, which I think will allow us to test more cases.

A tutorial with a url if there is already one about this perspective would be greatly appreciated.

**Comment by mxschmitt** [comment]
Yes, see this guide: https://playwright.dev/python/docs/network/#modify-requests

**Comment by fengnex** [comment]
@mxschmitt, thank you very much for your help first.
but I think it (the document of the above URL) is still not clear or intuitionistic enough for developers to find out the underlying URLs and each one's arguments when a web page is being tested.
Again, a real example may be more helpful.

**Comment by mxschmitt** [comment]
In what exactly are you interested in? Getting the full URL / path when you intercept a route?
See here for docs:
- https://playwright.dev/python/docs/api/class-page#page-route
- https://playwright.dev/python/docs/api/class-route
- https://playwright.dev/python/docs/api/class-request#request-url

So you should be able to get the URL by using `route.request.url` inside the page.route(..) callback. Maybe tell me more about your use-case then I'm able to provide you more input. Thanks!

**Comment by Kingslypaul** [comment]
Can you provide me code to get all the url after making a button click ... I m looking to get all the network action after making a button click.

**Comment by roopeshkr** [comment]
I am finding difficulties while dealing with the network like how we manually get all headers by navigating to network tab in developers tool and get all headers associated with it but how to get all headers after loging into any application using playwright including general, request and response headers
