### ISSUE TITLE
[Bug]: Context cannot close when recording har.

### ISSUE THREAD

**Issue by lafftar** [microsoft/playwright-python#843]
### Playwright version

1.12.1

### Operating system

Linux

### What browsers are you seeing the problem on?

Firefox

### Other information

Python = 3.9
Linux uname (username ommitted) = Linux 5.11.0-25-generic #27-Ubuntu SMP Fri Jul 9 23:06:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### What happened? / Describe the bug

Hi guys, i'm working with `playwright` to do some browser automation. I'm trying to record har content to see what's going on behind the scenes. 

I've included a simple line in my context:

```py
            record_har_path='/browser_automation/recordings/har',
```

The issue is, for some reason, the context cannot close.

```py
    async def close_browser(self):
        if self.context:
            self.debug('About to close context')
            await self.context.close()
            self.context = None
            self.debug('Browser (Context) Closed. Remember to close the browser/stop playwright.')
```

This is the fx I use to close the browser, works normally most of the time.

When I try to record the har tho, it doesn't close. It hits `About to close context` and then just sits there. I don't know why. As an added bonus, the har never gets saved to file - trying to record video at least outputs the video (I think it streams?).

Any help is appreciated.

### Relevant log output

```shell
No logs. No errors. Just hang.
```

**Comment by mxschmitt** [comment]
I tried to reproduce it with the following repo but it works as expected for me:

```py
import asyncio
from playwright.async_api import async_playwright

async def main():
    async with async_playwright() as p:
        for browser_type in [p.chromium, p.firefox, p.webkit]:
            browser = await browser_type.launch()
            context = await browser.new_context(
                record_har_path=f"./{browser_type.name}.har"
            )
            page = await context.new_page()
            await page.goto("https://connect.schmitt.mx")
            await context.close()
            await browser.close()

asyncio.run(main())
```

Is your site public? and does it get fixed if you add `record_har_omit_content=True`?

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.
