### ISSUE TITLE
[Bug]: Pyinstaller not working with Firefox

### ISSUE THREAD

**Issue by carlosperezm** [microsoft/playwright-python#844]
### Playwright version

1.13.1

### Operating system

Linux

### What browsers are you seeing the problem on?

Firefox

### Other information

Python: 3.9.6
Linux distribution: "Manjaro Linux" Linux 5.10.56-1-MANJARO x86_64 pgtk

### What happened? / Describe the bug

I am trying to use Playwright with Firefox.
It works correctly with chromium.

Steps to reproduce:
1. Create `test.py file` from the reproducible snippet
2. `PLAYWRIGHT_BROWSERS_PATH=0 playwright install firefox`
3. `pyinstaller -F test.py`
4. ` ./dist/test`

### Code snippet to reproduce your bug

```shell
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.firefox.launch()
    page = browser.new_page()
    page.goto("http://whatsmyuseragent.org/")
    page.screenshot(path="example.png")
    browser.close()
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    browser = p.firefox.launch()
  File "playwright/sync_api/_generated.py", line 9703, in launch
  File "playwright/_impl/_sync_base.py", line 111, in _sync
  File "playwright/_impl/_browser_type.py", line 90, in launch
  File "playwright/_impl/_browser_type.py", line 86, in launch
  File "playwright/_impl/_connection.py", line 36, in send
  File "playwright/_impl/_connection.py", line 54, in inner_send
playwright._impl._api_types.Error: Host system is missing dependencies!

  Missing libraries are:
      libxul.so
      libmozsqlite3.so

[220362] Failed to execute script 'test' due to unhandled exception!
```

**Comment by mxschmitt** [comment]
See here: https://playwright.dev/docs/cli#install-system-dependencies

**Comment by carlosperezm** [comment]
Thank you for your reply

Unfortunately I get:
`Cannot install dependencies for this linux distribution!`

Is there a way to install the dependencies manually?
Playwright with Firefox works fine in my system, is only when I try to package it with Pyinstaller that it fails.

NOTE: I tried it in WIndows and it works fine. It is definitely platform specific

Thanks again for the help!

**Comment by mxschmitt** [comment]
Majaro Linux is not supported, only Ubuntu 18.04 and Ubuntu 20.04 is officially supported, see here: https://playwright.dev/docs/library#system-requirements

For alternative Linux distributions the dependencies to run browsers need to installed manually.

**Comment by carlosperezm** [comment]
Thank you for the pointers. Since Manjaro is not supported, I guess it makes sense to close this :-)
