### ISSUE TITLE
[Question]: Chrome .crx file extension support

### ISSUE THREAD

**Issue by expiated** [microsoft/playwright-python#850]
### Your question

Hello there!
Tried to find out how extension support works via Slack but got no answer, so take my apologies for the repetition.

I'm trying to use headful chrome with our extension which's messaging with native client and with the server. 
Loading packed .crx file I'm getting "Failed to load extension from ** Manifest is missing or unreadable", using unpacked extension everything is Ok. But it's imperative for me to use the packed extension otherwise it won't work with the client app. 

I noticed that nowhere was mentioned that .crx is supported. So, where's the truth? Is it supported or not?

**Comment by mxschmitt** [comment]
You need to unpack the extension to load it. As a reference, you can see [this](https://playwright.dev/python/docs/chrome-extensions/) guide. CRX is the file format which Chromium uses, internally its just Zip. So you can change the file extension to .zip and extract it with your preferred zip extraction tool. See [here](https://superuser.com/questions/139190/how-to-unpack-a-chrome-theme).

**Comment by expiated** [comment]
@mxschmitt yes, as I mentioned before  an unpacked extension works fine, but going this scenario extension loses the connection with my native client cause it has another (unexpected) id. 

Ok, that's all I wanted to clarify - the packed extension usage possibility..  

Is there any plans to implement this in the future?

Looks

**Comment by mxschmitt** [comment]
This is a Chromium limitation, you can create an upstream feature request on https://crbug.com/ and they might give you more details on it.
