### ISSUE TITLE
[API] Mark API classes with @final

### ISSUE THREAD

**Issue by kumaraditya303** [microsoft/playwright-python#852]
Since playwright exported classes are not supposed to be subclassed hence it should be marked with `@final` decorator to force mypy to not allow subclassing it.

See https://www.python.org/dev/peps/pep-0591/#the-final-decorator

**Comment by mxschmitt** [comment]
Sounds good, do you want to add it?

**Comment by kumaraditya303** [comment]
Yes, will create PR for it.
