### ISSUE TITLE
[Question]: Usage of ``TimeoutError`` exception

### ISSUE THREAD

**Issue by carlosperezm** [microsoft/playwright-python#860]
### Your question

Hi,

What is the correct way to use the TimeoutError exception?

I am currently using this
`except playwright._impl._api_types.TimeoutError as e:`
but not sure if it is the idiomatic way.

Unfortunately, I could not find an example in the docs.

Thanks in advance

**Comment by mxschmitt** [comment]
`_impl` is not intended to get imported, the idiomatic way would be the following:

```py
from playwright.sync_api import sync_playwright, TimeoutError as PlaywrightTimeoutError

with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()
    page.goto("http://whatsmyuseragent.org/")
    try:
      page.click("text=Fooo", timeout=1000)
    except PlaywrightTimeoutError:
      print("timeout reached")
    browser.close()
```

**Comment by carlosperezm** [comment]
Thanks a lot for your reply, it works.

I could only find this in the API reference
https://playwright.dev/python/docs/api/class-timeouterror

Since handling this exception is a common case, will it make sense to add an example like the one you shared there or somewhere in the docs?

It was not self evident for a noobie like me, so maybe other people can benefit :)

**Comment by chujian521** [comment]
> 
Hello, mxschmitt !
I used this method to try to catch timeout: 
```python
from playwright.sync_api import sync_playwright, TimeoutError as PlaywrightTimeoutError

with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()
    page.goto("http://whatsmyuseragent.org/")
    try:
      page.click("text=Fooo", timeout=1000)
    except PlaywrightTimeoutError:
      print("timeout reached")
    browser.close()
```
But it does't print "timeout reached" in console. Why does this happen? Thank you for your attention!
