### ISSUE TITLE
[Question]: How to get web page cookies

### ISSUE THREAD

**Issue by djkcyl** [microsoft/playwright-python#863]
### Your question

I want to use playwright to obtain the cookie string for other operations after the login process

**Comment by mxschmitt** [comment]
There is a method on the browser context object called `cookies()` to get the cookies, see here: https://playwright.dev/python/docs/api/class-browsercontext#browser-context-cookies

**Comment by marshzhao** [comment]
def get_cookie1(url):
    with sync_api.sync_playwright() as p:
        browser_type = p.firefox
        browser = browser_type.launch()
        page = browser.new_page()
        page.goto(url)
        cookie_list = page.context.cookies()
        browser.close()
        cookie_str = ""
        for cookie in cookie_list:
            cookie_str += cookie['name'] + "=" + cookie['value'] + "; "
        print(cookie_str)
        return cookie_str

**Comment by djkcyl** [comment]
> def get_cookie1(url):
> with sync_api.sync_playwright() as p:
> browser_type = p.firefox
> browser = browser_type.launch()
> page = browser.new_page()
> page.goto(url)
> cookie_list = page.context.cookies()
> browser.close()
> cookie_str = ""
> for cookie in cookie_list:
> cookie_str += cookie['name'] + "=" + cookie['value'] + "; "
> print(cookie_str)
> return cookie_str

thx
