### ISSUE TITLE
[Question]: How to prevent the browser from closing after executing the code

### ISSUE THREAD

**Issue by marshzhao** [microsoft/playwright-python#866]
### Your question

When using playwright to drive the browser, the browser will automatically close after the code is executed, even if the “with” grammar is not used. How to prevent the browser from guaranty after the code is executed?

**Comment by mxschmitt** [comment]
Do you have a script to reproduce it? Then it easier to help. In general when you call browser.close() or context.close() the window closes. And page.close() the tab closes.

**Comment by marshzhao** [comment]
> Do you have a script to reproduce it? Then it easier to help. In general when you call browser.close() or context.close() the window closes. And page.close() the tab closes.

**Comment by marshzhao** [comment]
> Do you have a script to reproduce it? Then it easier to help. In general when you call browser.close() or context.close() the window closes. And page.close() the tab closes.

thank you, but I don't want to close it

**Comment by Congee** [comment]
Not sure why this issue was closed. According to my experiment, overriding browser.close(), context.close(), and page.close() does not help.

Also, windows and linux behave differently.
