### ISSUE TITLE
[Question]: What is the path for chromium cache?

### ISSUE THREAD

**Issue by playgithub** [microsoft/playwright-python#877]
### Your question

For the chromium which is installed by `playwright install chrome`

**Comment by mxschmitt** [comment]
Chrome does get installed system wide. What are you trying to do?

**Comment by playgithub** [comment]
> Chrome does get installed system wide. What are you trying to do?

playwright installs `chromium` at `~/.cache/ms-playwright`

I have a daily used chromium installed in another folder.

I doubt if the caches for the two will mixed by default.

**Comment by mxschmitt** [comment]
Yes, chromium, WebKit and Firefox get installed in ~/.cache/ms-playwright. It can't mix with other chromium Installations.

For chrome or msedge its different, they get installed globally on your system.

See here: https://playwright.dev/docs/browsers

**Comment by playgithub** [comment]
Will the caches of different versions of chromiums be mixed?

**Comment by mxschmitt** [comment]
No and there are no caches.

**Comment by playgithub** [comment]
> No and there are no caches.

It's `Incognito Mode` by default.
The settings for the two are different, so they don't share settings.
I think if it is not in `Incognito Mode`, the cach root paths for the two are different.
