### ISSUE TITLE
[Question]: How to launch multiple browser instances concurrently --- Python

### ISSUE THREAD

**Issue by alimp5** [microsoft/playwright-python#886]
Scenario: I need to run multiple playwright chrome or chromium browsers (no multiple pages) at same time  via asyncio/await or threading or multiprocessing libraries.

I tried but failed. because playwright just runs one browser instance at same time. I also used `asyncio.sleep(n)` and `time.sleep(n)` but didn't work for me.  Unfortunately  playwright works sequential (i need parallel).

```
# -*- coding: utf-8 -*-
from gevent import monkey, pool; monkey.patch_all()
import gevent
import json, time, threading, random, sys
from time import sleep

import asyncio
from playwright.async_api import async_playwright
from playwright.sync_api import sync_playwright
import playwright


def main2 (i):
        playwright = sync_playwright().start()
        browser =  playwright.chromium.launch(headless=False, channel="chrome")
        page = browser.new_page()
        page.goto("http://google.com")
        print(i, page.title())
        time.sleep(5)
        browser.close()


async def main (i):
    #async with async_playwright() as p:
        playwright = await async_playwright().start()
        browser = await playwright.chromium.launch(headless=False, channel="chrome")
        page = await browser.new_page()
        await page.goto("http://google.com")
        print(i, await page.title())
        await asyncio.sleep(10)
        await browser.close()



for i in range (3):
    #asyncio.run(main(i))
    #jobs.append (my_pool.spawn(main2, i))
    jobs.append (my_pool.spawn(asyncio.run(main(i))))
gevent.wait(jobs)


for i in range (3):
    t = threading.Thread (target=main2, args=[str(i),])
    t.start()
    jobs.append (t)

for t in jobs:
    t.join()
```

**Note:** if you want to test threading method, plz comment out other solutions and vice versa for others ......

**Comment by mxschmitt** [comment]
Why do you need multiple browser instances? Do multiple contexts not work for you? Browser contexts are isolated from each other and cheap to create see here: https://playwright.dev/python/docs/core-concepts#browser-contexts

Instead of using Threads, I would recommend to use multiple browser contexts (browser.new_page()) does create a context for you internally. 

In theory multiple threads in each you call `async_playwright().start()` should work. How much concurrency do you want to have?

**Comment by alimp5** [comment]
@mxschmitt 
Greetings!
I need to run 5 browser instances at same time and login to Example.com simultaneously/concurrency. and do some tasks on each browser instance. 

Note: example.com does not permit to open more than one page on each browser (security mechanism).

https://playwright.dev/python/docs/core-concepts/#browser-contexts
Browser contexts can also be used to emulate **multi-page scenarios** involving mobile devices, permissions, locale and color scheme.

Note: python selenium 3.x and 4.x supports grid feature. i can do it very well by grid. 
but selenium is heavy and bulky. but playwright is lightweight and fast.


https://medium.com/slalom-build/playwright-vs-webdriver-the-future-of-browser-automation-854a7ae63218

**Comment by mxschmitt** [comment]
Yeah I would recommend for that scenario to not use Threads and use asyncio features instead. You can then create multiple browser contexts, they behave like browser instances and are fast. This should work.

https://docs.python.org/3/library/asyncio-task.html#waiting-primitives

**Comment by alimp5** [comment]
@mxschmitt

Hi again.
I implemented a `asyncio` solution by your guides. unfortunately it didn't work.



```
import asyncio
from playwright.async_api import async_playwright
from playwright.sync_api import sync_playwright
import playwright

async def main (i):
    #async with async_playwright() as p:
        playwright = await async_playwright().start()
        browser = await playwright.chromium.launch(headless=False, channel="chrome")
        page = await browser.new_page()
        await page.goto("http://google.com")
        print(i, await page.title())
        await asyncio.sleep(10)
        await browser.close()

for i in range (5):
    asyncio.run(main(i))
```

**Comment by alimp5** [comment]
```
async def foo():
    return 42

task = asyncio.create_task(foo())
done, pending = await asyncio.wait({task})

if task in done:
    # Everything will work as expected now.
```

Error:
```
  File "c:/Users/linux10/Desktop/ea_project/teeeeeeeeeeeeeeemp.py", line 125
    done, pending = await asyncio.wait({task})
                    ^
SyntaxError: 'await' outside function
```

also i removed `await ` but it didn't work..

if you have a sample code to run 5 browser instances, plz share...

Thanks a lot.

**Comment by mxschmitt** [comment]
Something like this:

```py
import asyncio
from playwright.async_api import async_playwright


async def main():
    async with async_playwright() as playwright:
        browser = await playwright.chromium.launch(headless=False, channel="chrome")

        async def worker(i):
            context = await browser.new_context()
            page = await context.new_page()
            await page.goto("http://google.com")
            print(await page.title())
            await context.close()

        await asyncio.wait(
            [asyncio.create_task(worker(i)) for i in range(10)],
            return_when=asyncio.ALL_COMPLETED,
        )
        await browser.close()


asyncio.run(main())

```

**Comment by alimp5** [comment]
@mxschmitt
Tnx :X  ;X

**Comment by mnwdbase** [comment]
> 
> 
> Something like this:
> 
> ```python
> import asyncio
> from playwright.async_api import async_playwright, Browser
> 
> 
> async def worker(browser: Browser, i: int):
>     context = await browser.new_context()
>     page = await context.new_page()
>     await page.goto("http://google.com")
>     print(await page.title())
>     await context.close()
> 
> 
> async def main():
>     async with async_playwright() as playwright:
>         browser = await playwright.chromium.launch(headless=False, channel="chrome")
>         await asyncio.wait(
>             [asyncio.create_task(worker(browser, i)) for i in range(10)],
>             return_when=asyncio.ALL_COMPLETED,
>         )
>         await browser.close()
> 
> 
> asyncio.run(main())
> ```

I tried this to achieve an improvement of the threaded solution (tls and 1 playwright instance per thread) and its not only much slower but doesnt even get to start the browser intstances  (goto() times out).

**Comment by chwba** [comment]
> 
> 
> Something like this:
> 
> ```python
> import asyncio
> from playwright.async_api import async_playwright, Browser
> 
> 
> async def worker(browser: Browser, i: int):
>     context = await browser.new_context()
>     page = await context.new_page()
>     await page.goto("http://google.com")
>     print(await page.title())
>     await context.close()
> 
> 
> async def main():
>     async with async_playwright() as playwright:
>         browser = await playwright.chromium.launch(headless=False, channel="chrome")
>         await asyncio.wait(
>             [asyncio.create_task(worker(browser, i)) for i in range(10)],
>             return_when=asyncio.ALL_COMPLETED,
>         )
>         await browser.close()
> 
> 
> asyncio.run(main())
> ```

@mxschmitt I tried this to achieve an improvement of the threaded solution (tls and 1 playwright instance per thread) and its not only much slower but doesnt even get to start the browser intstances  (goto() times out). - Do you have any idea why that happens and maybe a suggestion regarding how to circumvent it? - To my understanding running playwright async like this should be superior to threading, hmm.

**Comment by AmericanY** [comment]
> Something like this:
> 
> ```python
> import asyncio
> from playwright.async_api import async_playwright, Browser
> 
> 
> async def worker(browser: Browser, i: int):
>     context = await browser.new_context()
>     page = await context.new_page()
>     await page.goto("http://google.com")
>     print(await page.title())
>     await context.close()
> 
> 
> async def main():
>     async with async_playwright() as playwright:
>         browser = await playwright.chromium.launch(headless=False, channel="chrome")
>         await asyncio.wait(
>             [asyncio.create_task(worker(browser, i)) for i in range(10)],
>             return_when=asyncio.ALL_COMPLETED,
>         )
>         await browser.close()
> 
> 
> asyncio.run(main())
> ```

@sla-te 

There's no need of using `await context.close()` and `await browser.close()`

Because by default the context will be closed once the function done the operation and browser itself will be closed once `with` block ended!

**Comment by mezhgano** [comment]
> Something like this:
> 
> ```python
> import asyncio
> from playwright.async_api import async_playwright, Browser
> 
> 
> async def worker(browser: Browser, i: int):
>     context = await browser.new_context()
>     page = await context.new_page()
>     await page.goto("http://google.com")
>     print(await page.title())
>     await context.close()
> 
> 
> async def main():
>     async with async_playwright() as playwright:
>         browser = await playwright.chromium.launch(headless=False, channel="chrome")
>         await asyncio.wait(
>             [asyncio.create_task(worker(browser, i)) for i in range(10)],
>             return_when=asyncio.ALL_COMPLETED,
>         )
>         await browser.close()
> 
> 
> asyncio.run(main())
> ```

Any chance to use concurrency in browser with persistence context?
I need to use Chromium with extension to scrape large amount of pages, i woud like to do it concurrently, for example: each url opens in a separate tab (page). Chromium extensions only works in persistent context. 

So, is it correct statement that: i can't use persistent context with concurrency or i missing something?
