### ISSUE TITLE
[Bug]: CALL_AND_RETRY_LAST Allocation failed - JavaScript out of memory

### ISSUE THREAD

**Issue by ivarsj10s** [microsoft/playwright-python#888]
### Playwright version

playwright @ git+https://github.com/microsoft/playwright-python.git@06a62bb19e90b26981630f836b4d0a5b6c0a7252

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### Other information

Python 3.9.5.

### What happened? / Describe the bug

I use playwright which uses multiple pages, around 8 pages same time. This error doesn't happen, always, but it typically crashes like this at least once a day. So it'd typically run okay for like I dunno 6 hours or 10 hours and then just crash like on this screenshot.

https://imgur.com/a/lskGge0

### Relevant log output

```shell
https://imgur.com/a/lskGge0
```

**Comment by mxschmitt** [comment]
Do you re-create your contexts? Because if you keep them running currently it don't flush the internals and it leads to out of memory errors, see https://github.com/microsoft/playwright/issues/6319

**Comment by ivarsj10s** [comment]
Thx @mxschmitt yeah it gotta be this. I do re-create but rarely, like, less often then 1x per hour so; so gotta be that 1x content accumulating too much stuff in memory in it's >1hr run.

**Comment by ivarsj10s** [comment]
@mxschmitt sorry, but do we have any workouts I could use such as changing some setting (how) or simply buying some extra RAM from ~'NewEgg' to work around this issue and not have my context crash in 1-2-3h of continuous usage?

I just realized I'm a bit too lazy to add code additions to create and destroy those contexts often; I'd rather prefer to only destroy them once 3-4h as previously.

**Comment by mxschmitt** [comment]
There is no other option right now, you can add your feedback to the upstream issue, so it gets prioritised, but so far it did not get that many interest.
