### ISSUE TITLE
[Feature]:  scroll bar for page

### ISSUE THREAD

**Issue by triangle959** [microsoft/playwright-python#902]
### Feature request

In the process of writing a crawler, scrolling down to trigger data loading is a very common operation. But if you want to scroll down the page, it seems that there is no particularly good way. Originally I thought there would be a page.scroll method, but it didn't.

**Comment by mxschmitt** [comment]
You can achieve this in multiple ways, e.g.

```
page.evaluate("window.scrollBy(x, y)")
```
(see [here](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollBy))

```
page.evaluate("window.scrollTo(x, y)")
```

(see [here](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo))

or wait until Playwright 1.15 where `page.mouse.wheel(delta_x: float, delta_y: float)` gets introduced.
