### ISSUE TITLE
[Question]: Source of Dockerfile

### ISSUE THREAD

**Issue by akozyreva** [microsoft/playwright-python#904]
### Your question

Hi everyone!
Just want to know, where I can read source of Dockefile `playwright-python `, it's content?

**Comment by mxschmitt** [comment]
For Python, you can use the official Docker image which includes Python: https://playwright.dev/docs/docker

The source of it is the following: https://github.com/microsoft/playwright/blob/master/utils/docker/Dockerfile.focal

**Comment by akozyreva** [comment]
@mxschmitt thanks for quick answer! I tried to find this url everywhere, but there's no link in docker hub or in documentation. Would be nice to have it somewhere published.

**Comment by akozyreva** [comment]
@mxschmitt thanks for quick answer! I tried to find this url everywhere, but there's no link in docker hub or in documentation. Would be nice to have it somewhere published.

**Comment by mxschmitt** [comment]
Are we looking at the same Docker image? The official one has a bunch of references in it: https://hub.docker.com/_/microsoft-playwright

**Comment by akozyreva** [comment]
Where? There is nothing in Resource tab. Yes, there's reference to ubuntu image, but that's it. 
![Screenshot 2021-09-15 at 15 58 55](https://user-images.githubusercontent.com/40454842/133447285-74c78616-6334-488e-8d39-2edba17fe76f.png)

**Comment by mxschmitt** [comment]
If you go on Documentation you will end up on https://playwright.dev/docs/docker where we reference to the Dockerfile and how you can build it manually.

**Comment by akozyreva** [comment]
Ah, okay, I found it `Dockerfile.focal can be used to run Playwright scripts in Docker environment. ` and `Dockerfile.focal` is the ref. But honestly it's not evident :-)

**Comment by mxschmitt** [comment]
Yeah, since we don't do much magic there, its not that helpful for users. The most interesting part is the `install-deps` command in the CLI: https://playwright.dev/docs/cli#install-system-dependencies
