### ISSUE TITLE
[Feature]: Wheels for arm64 on PyPI to support M1 installs

### ISSUE THREAD

**Issue by alexsands** [microsoft/playwright-python#907]
### Feature request

I'm using `playwright==1.9.1` inside an `ubuntu:20.04` Docker image and it is installing fine, but when I transfer this Dockerfile to another user on an M1 Apple Silicon MacBook, the installation fails with: 
```
#20 7.023 ERROR: Could not find a version that satisfies the requirement playwright==1.9.1 (from -r requirements.txt (line 22)) (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.0.18, 0.7.0, 0.7.1, 0.8.0, 0.140.0, 0.142.0, 0.142.1, 0.142.2, 0.142.3, 0.150.0, 0.151.0, 0.151.1, 0.152.0, 0.162.0, 0.162.1, 0.162.2)

#20 7.053 ERROR: No matching distribution found for playwright==1.9.1 (from -r requirements.txt (line 22))
```
Similar to a previous issue (#791) this appears to be because there are no arm64 wheels pre-built on PyPI. The only versions available are from source (< 0.162.2).

I haven't attempted to build this in other ways (from source, conda-forge, etc.) yet. That's my next plan. But I figured having these wheels on PyPI would be a useful feature as more people adopt Macs with Apple Silicon.

**Comment by mxschmitt** [comment]
Which PIP version are you using? If I remember correctly the last time people ran into this issue, it turned out that they were not using the latest PIP version since I think 20.X has a bug regarding that.

**Comment by kumaraditya303** [comment]
Duplicate https://github.com/microsoft/playwright/issues/7723
