### ISSUE TITLE
[Bug]: video will still record, and page will never close

### ISSUE THREAD

**Issue by kisscelia** [microsoft/playwright-python#908]
### Playwright version

1.14.1

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### Other information

python: 3.9.x

### What happened? / Describe the bug

just use video.save_as() method

page will never close.

I don't know why, please help me.

thank you.

### Code snippet to reproduce your bug

```shell
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch(headless=False, slow_mo=1000)
    context = browser.new_context(record_video_dir="test-results")
    page = context.new_page()

    page.goto("https://example.com")
    assert page.inner_text('h1') == 'Example Domain'
    # page.screenshot(path="example.png")
    page.video.save_as(path="temp-videos/a.webm")

    browser.close()
```
```


### Relevant log output

_No response_

**Comment by mxschmitt** [comment]
See [here](https://playwright.dev/docs/videos) and the documentation about [video.save_as](https://playwright.dev/python/docs/api/class-video/#video-save-as) that you need to close the page before, otherwise it will stall / wait until the page gets closed.
