### ISSUE TITLE
[Discussion] Alpine wheels for remote browser execution

### ISSUE THREAD

**Issue by kumaraditya303** [microsoft/playwright-python#913]
Since now pypi supports alpine wheels to be uploaded https://github.com/pypa/warehouse/pull/9982,
I would like a alpine wheel of playwright which contains statically linked nodejs binary for driver so that it can be used directly on alpine for BrowserType.connect as I would run multiple clients running in a docker network and browsers would run separately on a ubuntu machine.

 
:+1: if you want to use playwright on alpine.

**Comment by pavelfeldman** [comment]
What is the intended user scenario?

**Comment by kumaraditya303** [comment]
Scale tests on python with docker api to create multiple alpine workers processes connecting to a central grid running on ubuntu

**Comment by mxschmitt** [comment]
Merging into https://github.com/microsoft/playwright/issues/4687
