### ISSUE TITLE
[Bug]: dont working inner_text()

### ISSUE THREAD

**Issue by 66696e656c696665** [microsoft/playwright-python#931]
### Playwright version

1.15

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### Other information

Python 3.8

### What happened? / Describe the bug

I am using a query_selector to get the element with the desired text:
```
e = self.page.query_selector('span.side-menu-list__text:text-matches("^.*руб", "i")')
text = e.inner_text()
```
Then I get an empty string, but i know this element contain the text.

when i use inner_html () instead of inner_text () i get the desired text along with the comment
` 0 руб <!---->`

inner_text () does not work when there are nested tags or their similarity... as for me it should receive any text

**Comment by mxschmitt** [comment]
Can you provide us a full repro with a site / DOM elements where we can run the selector against?
