### ISSUE TITLE
[Question]: Playwright python auto close browser

### ISSUE THREAD

**Issue by ptung611** [microsoft/playwright-python#935]
### Your question

Hello,

When i tried python sample code playwright website
```
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()
    page.goto("http://playwright.dev")
    print(page.title())
    #browser.close()
```

Everything is ok but browser auto close when script end. (even without browser.close() ).

Do you know how to fix it. I want the browser close only when I use browser.close().

Regards,

**Comment by mxschmitt** [comment]
See these two links:
- https://book.pythontips.com/en/latest/context_managers.html
- https://playwright.dev/python/docs/intro#interactive-mode-repl
