### ISSUE TITLE
Use Python 3.10 union annotations in docs

### ISSUE THREAD

**Issue by kumaraditya303** [microsoft/playwright-python#938]
Use Python 3.10 union annotations in docs as it is more readable See https://www.python.org/dev/peps/pep-0604/

**Comment by kumaraditya303** [comment]
In the generated code which contains docs too, the previous Union syntax is too verbose so it should be changed first,
see https://github.com/microsoft/playwright-python/blob/master/playwright/async_api/_generated.py

**Comment by kumaraditya303** [comment]
@mxschmitt What's your opinion on this?

**Comment by E-wave112** [comment]
@mxschmitt can i work on this?

**Comment by kumaraditya303** [comment]
IMO it should also be done in the generated classes replace Union with |

**Comment by kumaraditya303** [comment]
Also in later python version `typing.Union` will be removed in favor of `|` syntax so impl package should also be changed to use it

**Comment by kumaraditya303** [comment]
> Is this compatible with Python 3.7?

@mxschmitt Yes see https://docs.python.org/3/library/__future__.html#module-__future__ see annotations

**Comment by kumaraditya303** [comment]
@mxschmitt So are you willing to accept this change ?

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.
