### ISSUE TITLE
How to disable [UnixSelectorEventLoop] warning

### ISSUE THREAD

**Issue by re1oaded** [microsoft/playwright-python#939]
`Loop <_UnixSelectorEventLoop running=False closed=True debug=False> that handles pid 1919221 is closed`
`Loop <_UnixSelectorEventLoop running=False closed=True debug=False> that handles pid 1919232 is closed`
`Loop <_UnixSelectorEventLoop running=False closed=True debug=False> that handles pid 1923783 is closed`
`Loop <_UnixSelectorEventLoop running=False closed=True debug=False> that handles pid 1923796 is closed`
`Loop <_UnixSelectorEventLoop running=False closed=True debug=False> that handles pid 1924099 is closed`

A large number of continuous warnings.
UnixSelectorEventLoop always appears on my console and affects the running log of the program I want to print.

I tried many methods and couldn't disable it.

**Comment by mxschmitt** [comment]
Do you have a reproducible script which demonstrates it?
