### ISSUE TITLE
[Question]: How to disable image loading?

### ISSUE THREAD

**Issue by Konano** [microsoft/playwright-python#955]
### Your question

Hi all, I'm using Playwright to saving the HTML content automatically, so the images on the website are not important to me. I want to disable image loading but I don't know how to do it. Someone can help me?

Appreciate your help!

**Comment by Konano** [comment]
Awesome! My problem was solved perfectly! It's so great!

Thank you!

**Comment by algot** [comment]
@AntoinePaix 
I tried to use 3 types of route syntax. First 2 are mentioned in official documentation:
https://playwright.dev/python/docs/api/class-page#page-route

```` page.route("**/*.{png,jpg,jpeg}", lambda route: route.abort()) ````

````page.route(re.compile(r"(\.png$)|(\.jpg$)"), lambda route: route.abort())````

````page.route("**/*", lambda route: route.abort()````
````           if route.request.resource_type == "image"````
````           else route.continue_()````
````           ) ````

Only 2 last are working.
First one is not applied if I try.
Could you suggest something why 1st syntax could not work?

**Comment by AntoinePaix** [comment]
Hi,

I also had the problem with the first method. I think this is a bug in Playwright's Python API.

This bug is also mentioned in the [zenrows tutorial](https://www.zenrows.com/blog/blocking-resources-in-playwright#block-by-glob-pattern).

**Comment by Dafung** [comment]
Hi,
And how to work in Playwrite's .Net API?

**Comment by Dafung** [comment]
Hi,
And how to work in Playwright's .NET API ?

**Comment by Dedigraz** [comment]
@Dafung it's in their documentation [here](https://playwright.dev/dotnet/docs/api/class-page#page-route)

**Comment by jperezrealini** [comment]
⚠️  Beware of this:

<img width="337" height="109" alt="Image" src="https://github.com/user-attachments/assets/ec53e0ed-bbc1-4992-8e50-0f480b38a507" />

This means that all js bundles and other common resources are downloaded from scratch on each navigation (even within the same context/page).

My solution:
```python
async with async_playwright() as p:
    browser = await p.chromium.launch(args=["--blink-settings=imagesEnabled=false"])
```

This disables image loading, while caching all other resources between page navigation.
