### ISSUE TITLE
[Bug]: TypeError: query_selector() got an unexpected keyword argument 'strict', sync api different to async api

### ISSUE THREAD

**Issue by ddmee** [microsoft/playwright-python#967]
### Playwright version

1.15.2

### Operating system

MacOS

### What browsers are you seeing the problem on?

Chromium

### What happened? / Describe the bug

Documentation says that `strict` keyword is available https://playwright.dev/python/docs/api/class-page/#page-query-selector. Docs says:

```
page.query_selector(selector, **kwargs)#
selector <str> A selector to query for. See working with selectors for more details.#
strict <bool> When true, the call requires selector to resolve to a single element. If given selector resolves to more then one element, the call throws an exception.#
returns: <NoneType|ElementHandle>#
The method finds an element matching the specified selector within the page. If no elements match the selector, the return value resolves to null. To wait for an element on the page, use page.wait_for_selector(selector, **kwargs).

Shortcut for main frame's frame.query_selector(selector, **kwargs).
```

Sync api for `query_selector()` has different arguments to async api, missing the `strict` keyword

The **sync** api
https://github.com/microsoft/playwright-python/blob/a385b00a0e258e9fd7c618c05b2e3bc4cf1fb799/playwright/sync_api/_generated.py#L2515

The **async** api

https://github.com/microsoft/playwright-python/blob/a385b00a0e258e9fd7c618c05b2e3bc4cf1fb799/playwright/_impl/_frame.py#L258-L260

Causes TypeError when calling the sync api `query_selector()` with `strict` keyword argument.

### Code snippet to reproduce your bug

```shell
from playwright.sync_api import Page

# however you want to get your sync page...
page = Page()
page.query_selector('text=hello', strict=True)
```

### Relevant log output

```shell
TypeError: query_selector() got an unexpected keyword argument 'strict'
```

**Comment by ddmee** [comment]
I thought, just reading the docs, I was using the `page.query_selector` https://playwright.dev/python/docs/api/class-page/#page-query-selector but maybe I've got the `ElementHandle.query_selector`?

**Comment by mxschmitt** [comment]
Which version of Playwright are you using?

```py
from playwright._repo_version import version
print(version)
```
