### ISSUE TITLE
[Bug]: if the  browser crashed, then user_data_dir locked,  next time  it could not launch again

### ISSUE THREAD

**Issue by viponedream** [microsoft/playwright-python#968]
### Playwright version

lasted

### Operating system

Windows

### What happened? / Describe the bug

launch_persistent_context  need user_data_dir, but sometime it happened like the title described.
maybe user_data_dir should be specified or not to avoid this error.

**Comment by mxschmitt** [comment]
Do you have a reproducible for the crash?
