### ISSUE TITLE
ARM64 based driver

### ISSUE THREAD

**Issue by kumaraditya303** [microsoft/playwright-python#976]
https://github.com/microsoft/playwright/issues/7723 for Python

**Comment by safwanrahman** [comment]
@mxschmitt Is it possible to upload the source distribution by adding `sdist` while building in CI? Is there any reason to publish the `wheel` only? So people with linux ARM64 people can use this package by building it in local machine?

**Comment by mxschmitt** [comment]
@safwanrahman unfortunately not. Playwright itself requires also browsers which need to be ARM64/Linux compatible, we are in the progress of doing that, stay tuned!

**Comment by safwanrahman** [comment]
Thanks @mxschmitt!

**Comment by mxschmitt** [comment]
Closing since as of 1.18 it should work.

cc @safwanrahman if you use `pip install git+https://github.com/microsoft/playwright-python` it should also work today.
