### ISSUE TITLE
[Feature]: Add support for the Trio library

### ISSUE THREAD

**Issue by pemocarlo** [microsoft/playwright-python#994]
### Feature request

Have you considered supporting [Trio](https://github.com/python-trio/trio) ?
This is a friendlier alternative library to the built-in asyncio.

Unfortunately as of now, it is not possible to mix both libraries, so asyncio is the only alternative if we want to use playwright-python.

Thank you in advance!

**Comment by kumaraditya303** [comment]
Playwright heavily uses asyncio and even if playwright were to support trio then supporting sync api would be very hard with trio!

**Comment by mxschmitt** [comment]
Closing for now since there are no plans to support Trio library.

**Comment by carlosplanchon** [comment]
This would be a very interesting feature.

**Comment by vladionescu** [comment]
I'd also appreciate trio support. Trio is growing in popularity and offers what appears to be a more flexible concurrency API than asyncio.

**Comment by mikenerone** [comment]
I'd also like to see Trio support.
