### ISSUE TITLE
Error 1020   Access denied

### ISSUE THREAD

**Issue by viponedream** [microsoft/playwright-python#996]
### Your question

with chromium,  url is:  https://opensea.io
----------------------------------------------------------
Error 1020
Access denied
This website is using a security service to protect itself from online attacks.
-----------------------------------------------------------
but just open chrome,  the website open well. 
maybe the website can detect what we do ? when use playwright, it  thinks we are bot ?

How to bypass the detection?

**Comment by mxschmitt** [comment]
Exactly, most likely the website you are navigating to has some kind of bot protection (e.g. WAF) and hence its filtering the requests from Playwright out.

Bypassing this is not in scope of the Playwright project, since its focusing on end-to-end testing. Closing by that.
