### ISSUE TITLE
playwright cannot be installed to python3.10  32-bit or python3.11 32-bit

### ISSUE THREAD

**Issue by zhonghai9967** [microsoft/playwright-python#997]
### Your question

Installed playwright 1.16  to python 3.9.7 everything is normal.

pip install playwright
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting playwright
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/1d/8f/fd06a2d5088136f7e69627cf336498ec2cb6ac632d7a19fb1fb0f259bb64/playwright-1.16.1-py3-none-win32.whl (24.5 MB)
     |████████████████████████████████| 24.5 MB 6.4 MB/s
Collecting pyee>=8.0.1
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/56/37/29d137df23ed1d88d8dcee8a6b8e789d1162042f194b5ccd0a48f503429b/pyee-8.2.2-py2.py3-none-any.whl (12 kB)
Collecting greenlet>=1.0.0
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/0c/10/754e21b5bea89d0e73f99d60c83754df7cc64db74f47d98ab187669ce341/greenlet-1.1.2.tar.gz (91 kB)
  Preparing metadata (setup.py) ... done
Collecting websockets>=8.1
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/1c/f4/61aee1eb4baadf8477fb7f3bc6b04a50fe683ef8ad2f60282806821e4b3b/websockets-10.0.tar.gz (81 kB)
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for greenlet, since package 'wheel' is not installed.
Using legacy 'setup.py install' for websockets, since package 'wheel' is not installed.
Installing collected packages: websockets, pyee, greenlet, playwright
    Running setup.py install for websockets ... done
    Running setup.py install for greenlet ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Python311\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'D:\\temp\\pip-install-fatf6twf\\greenlet_efb4e1129ce740649352f95008bbfa1e\\setup.py'"'"'; __file__='"'"'D:\\temp\\pip-install-fatf6twf\\greenlet_efb4e1129ce740649352f95008bbfa1e\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'D:\temp\pip-record-gududk6j\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Python311\Include\greenlet'
         cwd: D:\temp\pip-install-fatf6twf\greenlet_efb4e1129ce740649352f95008bbfa1e\
    Complete output (72 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.11
    creating build\lib.win32-3.11\greenlet
    copying src\greenlet\__init__.py -> build\lib.win32-3.11\greenlet
    creating build\lib.win32-3.11\greenlet\tests
    copying src\greenlet\tests\test_contextvars.py -> build\lib.win32-3.11\greenlet\tests
    copying src\greenlet\tests\test_cpp.py -> build\lib.win32-3.11\greenlet\tests
    copying src\greenlet\tests\test_extension_interface.py -> build\lib.win32-3.11\greenlet\tests
    copying src\greenlet\tests\test_gc.py -> build\lib.win32-3.11\greenlet\tests
    copying src\greenlet\tests\test_generator.py -> build\lib.win32-3.11\greenlet\tests
    copying src\greenlet\tests\test_generator_nested.py -> build\lib.win32-3.11\greenlet\tests
    copying src\greenlet\tests\test_greenlet.py -> build\lib.win32-3.11\greenlet\tests
    copying src\greenlet\tests\test_leaks.py -> build\lib.win32-3.11\greenlet\tests
    copying src\greenlet\tests\test_stack_saved.py -> build\lib.win32-3.11\greenlet\tests
    copying src\greenlet\tests\test_throw.py -> build\lib.win32-3.11\greenlet\tests
    copying src\greenlet\tests\test_tracing.py -> build\lib.win32-3.11\greenlet\tests
    copying src\greenlet\tests\test_version.py -> build\lib.win32-3.11\greenlet\tests
    copying src\greenlet\tests\test_weakref.py -> build\lib.win32-3.11\greenlet\tests
    copying src\greenlet\tests\__init__.py -> build\lib.win32-3.11\greenlet\tests
    running egg_info
    writing src\greenlet.egg-info\PKG-INFO
    writing dependency_links to src\greenlet.egg-info\dependency_links.txt
    writing requirements to src\greenlet.egg-info\requires.txt
    writing top-level names to src\greenlet.egg-info\top_level.txt
    reading manifest file 'src\greenlet.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'docs\_build'
    warning: no files found matching '*.py' under directory 'appveyor'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching '.coverage' found anywhere in distribution
    adding license file 'LICENSE'
    adding license file 'LICENSE.PSF'
    adding license file 'AUTHORS'
    writing manifest file 'src\greenlet.egg-info\SOURCES.txt'
    copying src\greenlet\greenlet.c -> build\lib.win32-3.11\greenlet
    copying src\greenlet\greenlet.h -> build\lib.win32-3.11\greenlet
    copying src\greenlet\slp_platformselect.h -> build\lib.win32-3.11\greenlet
    creating build\lib.win32-3.11\greenlet\platform
    copying src\greenlet\platform\setup_switch_x64_masm.cmd -> build\lib.win32-3.11\greenlet\platform
    copying src\greenlet\platform\switch_aarch64_gcc.h -> build\lib.win32-3.11\greenlet\platform
    copying src\greenlet\platform\switch_alpha_unix.h -> build\lib.win32-3.11\greenlet\platform
    copying src\greenlet\platform\switch_amd64_unix.h -> build\lib.win32-3.11\greenlet\platform
    copying src\greenlet\platform\switch_arm32_gcc.h -> build\lib.win32-3.11\greenlet\platform
    copying src\greenlet\platform\switch_arm32_ios.h -> build\lib.win32-3.11\greenlet\platform
    copying src\greenlet\platform\switch_csky_gcc.h -> build\lib.win32-3.11\greenlet\platform
    copying src\greenlet\platform\switch_m68k_gcc.h -> build\lib.win32-3.11\greenlet\platform
    copying src\greenlet\platform\switch_mips_unix.h -> build\lib.win32-3.11\greenlet\platform
    copying src\greenlet\platform\switch_ppc64_aix.h -> build\lib.win32-3.11\greenlet\platform
    copying src\greenlet\platform\switch_ppc64_linux.h -> build\lib.win32-3.11\greenlet\platform
    copying src\greenlet\platform\switch_ppc_aix.h -> build\lib.win32-3.11\greenlet\platform
    copying src\greenlet\platform\switch_ppc_linux.h -> build\lib.win32-3.11\greenlet\platform
    copying src\greenlet\platform\switch_ppc_macosx.h -> build\lib.win32-3.11\greenlet\platform
    copying src\greenlet\platform\switch_ppc_unix.h -> build\lib.win32-3.11\greenlet\platform
    copying src\greenlet\platform\switch_riscv_unix.h -> build\lib.win32-3.11\greenlet\platform
    copying src\greenlet\platform\switch_s390_unix.h -> build\lib.win32-3.11\greenlet\platform
    copying src\greenlet\platform\switch_sparc_sun_gcc.h -> build\lib.win32-3.11\greenlet\platform
    copying src\greenlet\platform\switch_x32_unix.h -> build\lib.win32-3.11\greenlet\platform
    copying src\greenlet\platform\switch_x64_masm.asm -> build\lib.win32-3.11\greenlet\platform
    copying src\greenlet\platform\switch_x64_masm.obj -> build\lib.win32-3.11\greenlet\platform
    copying src\greenlet\platform\switch_x64_msvc.h -> build\lib.win32-3.11\greenlet\platform
    copying src\greenlet\platform\switch_x86_msvc.h -> build\lib.win32-3.11\greenlet\platform
    copying src\greenlet\platform\switch_x86_unix.h -> build\lib.win32-3.11\greenlet\platform
    copying src\greenlet\tests\_test_extension.c -> build\lib.win32-3.11\greenlet\tests
    copying src\greenlet\tests\_test_extension_cpp.cpp -> build\lib.win32-3.11\greenlet\tests
    running build_ext
    building 'greenlet._greenlet' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Python311\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'D:\\temp\\pip-install-fatf6twf\\greenlet_efb4e1129ce740649352f95008bbfa1e\\setup.py'"'"'; __file__='"'"'D:\\temp\\pip-install-fatf6twf\\greenlet_efb4e1129ce740649352f95008bbfa1e\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'D:\temp\pip-record-gududk6j\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Python311\Include\greenlet' Check the logs for full command output.

**Comment by zhonghai9967** [comment]
This problem only occurs with python 32-bit.
One of my applications must use python32 bit
Playwright can be installed normally in python64 bit.

**Comment by mxschmitt** [comment]
Seems like this is about an issue that [Greenlet](https://github.com/python-greenlet/greenlet) can't get installed on which Playwright depends on.

**Comment by kumaraditya303** [comment]
You need 32bit windows compiler, it is not a playwright issue as it requires compilation of 32 bit x86 assembly of greenlet, just install the compiler

**Comment by zhonghai9967** [comment]
@kumaraditya303   @mxschmitt  thank you！
What you said is right.
1.Install MSBuild tools，Choose to use C++ for desktop development
2.pip install greenlen
3.pip install playwright
